### ISSUE TITLE
Keepalived version 2.0.7 does not accept rules with "from all/wildcard(0.0.0.0/0)" 

### ISSUE THREAD

**Issue by 3hedgehogs** [acassen/keepalived#1001]
I have just tested new version on keepalived 2.0.7 with our existing configuration 
with a lot of static rules:

 
..<br/>  
from 0.0.0.0/0 fwmark 86017 lookup gw-main.1 preference 1 <br/> 
from 0.0.0.0/0 fwmark 86018 lookup gw-main.1 preference 2 <br/>
..  

OR

..<br/>
from all fwmark 86017 lookup gw-main.1 preference 1<br/>
from all fwmark 86018 lookup gw-main.1 preference 2<br/>
..<br/>

Both variant are not accepted by keepalived version 2.0.7. 
The first variant is working for keepalived version 1.4.4 on our Debian boxes.

Error output for the first variant:

Keepalived_vrrp[7785]: (Line 718) Invalid address prefix len 0 for address 0.0.0.0 - using 32<br/>
Keepalived_vrrp[7785]: (Line 719) number '0' outside range [1, 32]<br/>

For the second variant:

Keepalived_vrrp[42994]: (Line 9) VRRP parsed invalid IP all. skipping IP...<br/> 
Keepalived_vrrp[42994]: (Line 9) Invalid rule from address all  

PS. What is correct syntax in this case (for keepalived version 2.0.* )?

**Comment by pqarmitage** [comment]
Certainly from 0.0.0.0/0 should be allowed, and I will have a look at allowing that.

`from default` should work.

**Comment by pqarmitage** [comment]
I've had a further look at the code and I don't think `default` will work either at the moment.

**Comment by pqarmitage** [comment]
@3hedgehogs I've merged commit 843ffc8 which allows `from 0.0.0.0/0` and `from default` to work. I will push a further commit to allow `from all` and `from any` later, along with fixes for one or two other problems I have noticed while looking at this.

**Comment by pqarmitage** [comment]
Thr other identified fixes have now been merged.
