### ISSUE TITLE
Missing Error Check in function SSL_CTX_new()

### ISSUE THREAD

**Issue by lc3412** [acassen/keepalived#1003]
Hi,
Function SSL_CTX_new() returns a pointer to an SSL_CTX object on success or NULL on error. However, the function SSL_CTX_new() in keepalived/genhash/ssl.c didn't check the return value is NULL or not, before passing the return value as an argument to the function SSL_CTX_set_verify_depth(). See the following details.

![screenshot from 2018-09-19 16-32-44](https://user-images.githubusercontent.com/19151593/45741446-2928fb00-bc2a-11e8-99cf-bf5ec2f4e159.png)

Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by pqarmitage** [comment]
Many thanks for reporting this.

Commit a007e93 adds a check of the return value of SSL_CTX_new(). More importantly it also adds the same check to keepalived in check_ssl.c/build_ssl_ctx().
