### ISSUE TITLE
Missing Error Check in function SSL_new() 

### ISSUE THREAD

**Issue by lc3412** [acassen/keepalived#1004]
Hi,
Function SSL_new() returns a pointer to an SSL object on success or NULL on error. However, the function SSL_new() in keepalived/genhash/ssl.c didn't check the return value is NULL or not, before passing the return value as an argument to both the function SSL_set0_rbio() and SSL_set0_wbio(). See the following details.

![screenshot from 2018-09-19 16-33-43](https://user-images.githubusercontent.com/19151593/45742930-a5710d80-bc2d-11e8-8573-cbbe3e4984c8.png)

Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by pqarmitage** [comment]
Commit 31b0644 now makes genhash check the return value of SSL_new() and also BIO_new_socket(). It also applies similar updates to keepalived/check_ssl.c.
