### ISSUE TITLE
PID xxxx exited due to signal 9

### ISSUE THREAD

**Issue by JonathanNathanson** [acassen/keepalived#1020]
Hi,

I am using Keepalived to manage a virtual IP address failover between two freeradius servers. My config runs a script to check that the freeradius server is responding, and if it isn't, should force a new master election.

**Keepalived version (on Ubuntu 16.04):**

`root@CN3-RAD-AUTH2:/usr/local# keepalived -v
Keepalived v1.2.24 (08/06,2018)`

**/var/log/syslog** is full of this, repeated every two seconds ( which is how frequently the check script runs ):

`Sep 27 15:31:41 localhost Keepalived_vrrp[21941]: Process [22505] didn't respond to SIGTERM
Sep 27 15:31:41 localhost Keepalived_vrrp[21941]: pid 22505 exited due to signal 9`

**/etc/keepalived/keepalived.conf:**

        vrrp_script chk_radreply {

                script "/usr/local/bin/radreplycheck.sh"
                interval 2
                rise 1
                fall 4
                weight 60
                timeout 15

        }

        vrrp_instance freerad_ips {
                state SLAVE
                interface ens160
                virtual_router_id 61
                priority 50
                advert_int 1

                virtual_ipaddress {
                        10.248.1.43/24
                }

                track_script {
                        chk_radreply
                }

        }

The timeout is set to 15 as I am trying to work out why something isn't working, timeout is normally 1 or 2.

**/usr/local/bin/radreplycheck.sh:**

        #!/bin/bash
        # returns error codes as follows
        # 0 - everything okay (radius code 2, Access-Accept)
        # 64 - rejected (radius code 3, Access-Reject)
        # 65 - some other radius code
        # 66 - no response
        # 67 - something else
        
        USERNAME="############"
        USERPASS="###########"

        SECRET="##############"
        SERVER="127.0.0.1"

        OP="auth"

        FLAGS=" "

        BODY="
        User-Name=$USERNAME,
        User-Password=$USERPASS,
        Calling-Station-Id=44-44-44-44-44-44,
        NAS-Identifier=GB22-EX-1234,
        Called-Station-Id=AA-11-11-11-11-11:Dash12
        "

        #magic strings
        NORESP="No reply from server"
        RESPONSE="Received "

        ACCEPT="Received Access-Accept "
        REJECT="Received Access-Reject "
        
        ERROR=67

        # NB redirection of stderr which contains the "no response"
        # echo $BODY | radclient $FLAGS $SERVER $OP $SECRET 2>&1

        REPLY=`echo $BODY | radclient $FLAGS $SERVER $OP $SECRET 2>&1`

        case "$REPLY" in
                *$NORESP*)
                        ERROR=66
                        ;;
                *$RESPONSE*)
                        ERROR=65
                        case "$REPLY" in
                                *$ACCEPT*)
                                        ERROR=0
                                        ;;
                                *$REJECT*)
                                        ERROR=64
                                        ;;
                        esac
                        ;;
        esac
        
        echo $ERROR
        exit $ERROR
        #echo $REPLY

Any assistance with this would be greatly appreciated - if I have missed any important info then please do let me know.

**Comment by pqarmitage** [comment]
I am assuming that PID 22505 is the radreplycheck.sh script (I can't see anything else if could be in your configuration). Keepalived only sends SIGTERM to scripts if they have not completed within the timeout interval (which you currently have set to 15). If the script still does not terminate after a further second, then keepalived sends it a SIGKILL, and this is what is being logged.

From the man page for radclient:
```
-r num_retries
    Try to send each packet num_retries times, before giving up on it. The default is 10.
-t timeout
    Wait timeout seconds before deciding that the NAS has not responded to a request, and re-sending the packet. The default timeout is 3. 
```
so it would appear that the time before radclient exits if there is no response will be 30 seconds. You could try running the radreplycheck.sh script directly from a command prompt when keepalived is reporting the log entries and see how long it takes to complete to confirm this.

So it seems that you either need to increase the `timeout` value above 30 seconds, or specify one or both of `-r` and `-t` to radclient.

By the way, `state SLAVE` should be `state BACKUP`.

Your version of keepalived is very old. It is over 1600 non-merge commits behind the current version of keepalived, so it would be worth getting the latest version from github and building it.
