### ISSUE TITLE
Ask centos7 to install at least one version

### ISSUE THREAD

**Issue by Quantriple** [acassen/keepalived#1022]
Thank you very much(非常非常感谢)

**Comment by pqarmitage** [comment]
Could you please explain what your issue is, and what you would like done to fix it.

**Comment by Quantriple** [comment]
Ask centos7 to install at least one version(在cento7上安装哪个版本)

**Comment by Quantriple** [comment]
>           Could you please explain what your issue is, and what you would like done to fix it.

Ask centos7 to install at least one version(在cento7上安装哪个版本)

**Comment by pqarmitage** [comment]
On Centos 7, `yum install keepalived` will install keepalived.
