### ISSUE TITLE
Question: kernel requirements

### ISSUE THREAD

**Issue by scriptjs** [acassen/keepalived#1024]
I cannot seem to find where the kernel requirements for keepalived are spelled out. Is there a resource that you can point me to so I may verify the kernel I am using has the modules required. Many thanks.

**Comment by pqarmitage** [comment]
I  don't believe there is anywhere that spells out the kernel requirements.

Any kernel feature that keepalived would like to use introduced from 2.6.15 onwards is tested for at configure/compile time by checking for relevant definitions in the Linux header files. Kernels older than 2.6.15 aren't supported any more.

I suppose we could try starting a list, but it is going to be hard work identifying everything that is used in the kernel that is configurable.

An initial list would be:
BPF
EPOLL
SIGNALFD
TIMERFD
SYSCTL
PROC_FS
INET
IP_MULTICAST
IPV6
IP_VS (unless --disable-lvs is specified)
but there may well be others that I haven't thought of.

Other options may be necessary depending on what configure options are selected.

**Comment by scriptjs** [comment]
Hi. Thank you for your reply. I am currently working with 4.14.x kernels at the present time. Yeah, there are multiple configs for IP_VS as well. I plan to use keepalived for VRRP with a virtual IP for nginx HA load balancing.

**Comment by pqarmitage** [comment]
Yes, I saw the multiple config options for IP_VS, but didn't feel like listing them all. If `no_accept` (or `strict_mode`) is specified, then various NETFILTER_XTABLES/NETFILTER_XT options are required anf IP_SET and some sub options. If static or dynamic routes are specified, then IP_ADVANCED_ROUTER and various associated options will be required, and likewise if static or dynamic rules are specified then FIB_RULES will be needed.

@scriptjs Do you need any more information on this or can the issue be closed now?

**Comment by scriptjs** [comment]
I think you could close it but you may want to reference this in commit to docs so there could be some iteration to evolve kernel requirements for the project.

**Comment by pqarmitage** [comment]
@scriptjs Many thanks. I have already started adding the information to the INSTALL file, and will reference this issue when I commit it.
