### ISSUE TITLE
Keepalived reload not working

### ISSUE THREAD

**Issue by senthilnathann** [acassen/keepalived#1029]
Hi,

Keepalived reload not reflecting the configuration changes.

OS : Centos7.4
Keepalived version : 1.3.9

Pls help on this

**Comment by pqarmitage** [comment]
Please provide
1. The output of keepalived -v
2. The configurations before and after the reload.

Once we have that information we can investigate the issue.

**Comment by pqarmitage** [comment]
I have reproduced the problem with v1.3.9, but it has been fixed in the latest code. A git bisect shows that it was commit e875970 that resolved the problem. The first version of keepalived to include that commit was v2.0.6.

**Comment by senthilnathann** [comment]
Hi ,

We are facing same issue in keepalived v2.0.7 too.Is this fixed or not ? Please check and claririfiy on this .
