### ISSUE TITLE
vrrp master ip address

### ISSUE THREAD

**Issue by igregr** [acassen/keepalived#1038]
Would it be please possible to add also the master IP address to notification script? I would like to know what is the master ip address on a backup server. Or is it possible to find it in some other way (from backup server perspective)?

**Comment by pqarmitage** [comment]
kill -USR1 $(cat /var/run/keepalived.pid) will produce a file /tmp/keepalived.data. This will list the master router. Is that of any help to you?
```
------< VRRP Topology >------
 VRRP Instance = VI_1
   VRRP Version = 3
   State = BACKUP
   Master router = 10.1.0.1
   Master priority = 240
   Master advert int = 1.00 sec
   Wantstate = BACKUP
```

I could have a think about adding state parameters for notify scripts, but we don't have the code to do that at the moment.

**Comment by igregr** [comment]
Ah, great! Didn't know about this. It would be great if it could be also part of the notification scripts, but your solution works for me. Thanks.
