### ISSUE TITLE
virtual route removed after releasing temporary taken backup vrrp_instance

### ISSUE THREAD

**Issue by mruncles** [acassen/keepalived#1078]
I' do not know if it is an expected behavior, but for me it looks weird/unpleasant.

Given:
xenial: 1.2.19/1.2.24
3 nodes with 3 vips
Еach vip has corresponding vvrp_instance with priorities that assign 1 vip per node. (configuration differ on nodes only by priorities)
Each vrrp_instance has virtual_address and virtual_routes (default route) directives to assign on public facing interface.
Public interface has no other addresses/routes attached to it. No default route as well(public routing/addressing is managed solely by keepalived).

Scenario:
1. node1 node2 node3 - all nodes up/haproxy up ... everything works.
2. node2 haproxy goes down and releases vip2.
3. node1 takes vip2 (does not assign default virtual route, because it already exists).
4. node1 and node3 process public traffic.
5. haproxy on node 2 goes up.
6. vip2 transfers back on node2 and default virtual route is reinstated on it.
7. default virtual route is removed from node1, though it, stil,l has vrrp_instance (vip1) in master state.
8. node1 is not accessible from outside world (though it has vip1 assigned to it), node2 and node3 work as expected.

What is the best solution here?
1. Place virtual_routes directive only on highest prio vrrp_instance, so only node predefined vip controls default route assignement? (breaks my configuration templating)
2. Replace directive with script having same functionality. (not clean)
3. Add static address and route from same l2 segment? (redundant unused addresses)

Thanks in advance.

**Comment by pqarmitage** [comment]
Can you please provide a copy of your configuration file to help us understand what is happening.

**Comment by mruncles** [comment]
[keepalived.conf.gz](https://github.com/acassen/keepalived/files/2648037/keepalived.conf.gz)

This is my configuration in testing environment on node3

This is what happens when I stop and start haproxy on node2 (log from node3)

02:53:21 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip6_2) Transition to MASTER STATE
02:53:21 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip6_2) Received higher prio advert 70
02:53:21 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip6_2) Entering BACKUP STATE
02:53:21 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip6_2) removing protocol Virtual Routes
02:53:22 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip4_2) Transition to MASTER STATE
02:53:22 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip4_2) Received lower prio advert 70, forcing new election
02:53:24 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip4_2) Entering MASTER STATE
02:53:24 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip4_2) setting protocol VIPs.
02:53:24 fp3 Keepalived_healthcheckers[20481]: Netlink reflector reports IP 172.24.35.102 added
02:53:24 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip4_2) setting protocol Virtual Routes
02:53:24 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:53:24 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip4_2) Sending/queueing gratuitous ARPs on eth2 for 172.24.35.102
02:53:24 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:53:24 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:53:24 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:53:24 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:53:27 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:53:27 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip4_2) Sending/queueing gratuitous ARPs on eth2 for 172.24.35.102
02:53:27 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:53:27 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:53:27 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:53:27 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:53:29 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:53:29 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip4_2) Sending/queueing gratuitous ARPs on eth2 for 172.24.35.102
02:53:29 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:53:29 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:53:29 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:53:29 fp3 Keepalived_vrrp[20482]: Sending gratuitous ARP on eth2 for 172.24.35.102
02:54:28 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip4_2) Received higher prio advert 100
02:54:28 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip4_2) Entering BACKUP STATE
02:54:28 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip4_2) removing protocol Virtual Routes
02:54:28 fp3 Keepalived_vrrp[20482]: VRRP_Instance(vip4_2) removing protocol VIPs.
02:54:28 fp3 Keepalived_healthcheckers[20481]: Netlink reflector reports IP 172.24.35.102 removed


As we can see

removing protocol Virtual Routes <---- removing default routes from node. Though it, still, has 1 vip left.

**Comment by pqarmitage** [comment]
The behaviour you are experiencing is what I would expect to happen. Each vrrp instance assumes that the ip addresses, routes and rules configured are unique to that instance. The error really lies in keepalived not reporting that it fails to add the second and third default routes.

There is a way around this, but the first version that supported it was v1.2.24. If you specify `metric nn` against each route (when nn is different for each vrrp instance) then all three default routes can be installed, and when a vrrp instance transitions to backup (or fault) state, it will only remove its own virtual route.

**Comment by mruncles** [comment]
Thanks, it helped a lot.
