### ISSUE TITLE
The retry directive for MISC_CHECK checks does not work

### ISSUE THREAD

**Issue by igroost** [acassen/keepalived#1082]
Hello!

We are trying to use the retry directive for configurations with MIC_CHECK checks, but the check is triggered only once, no matter what number is specified in retry. Judging by the manual for checks MISC_CHECK this directive is supported. Tried to specify the directive at the level of virtual_server, real_server and check, in all cases there is a single start of check then real_server is switched off from balancing.

Tell me why does not work this directive?

Below are our configurations that were used for verification and logs.

Keepalived config

#Configuration File for keepalived

global_defs {
   router_id IPVS-TEST-102
   notification_email {
     mail@host
                      }
   notification_email_from host@host
   smtp_server 0.0.0.0
   smtp_connect_timeout 30
            }

###############################################################################################

#TEST-0
virtual_server 10.9.200.200 80       {
        delay_loop 5
        alpha 1
        omega 1
        lvs_sched rr
        lvs_method TUN
        smtp_alert on
        retry 3
        delay_before_retry 3 
        protocol TCP

    quorum 1

        quorum_up "/sbin/ip -4 addr add 10.9.200.200/32 dev lo"
        quorum_down "/sbin/ip -4 addr del 10.9.200.200/32 dev lo"

#web-1
real_server 10.1.57.100 80 {
        retry 3
        MISC_CHECK {
             retry 3
             misc_path "/etc/keepalived/HC/HC-DB-master 10.1.57.100"
                  }
                         }

#web-2
real_server 10.1.57.101 80 {
        retry 3
        MISC_CHECK {
             retry 3
             misc_path "/etc/keepalived/HC/HC-DB-master 10.1.57.101"
                  }
                            }
                                      }

###########################################################################################

MISC_CHECK file

#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin
curl -qs -m 3 http://$1/ | grep -qF "255"
rc=$?
echo $rc
exit $rc

Keepalived logs

Dec 10 13:03:35 ipvs-test-102-wan Keepalived[26500]: Starting Keepalived v2.0.0 (05/27,2018)
Dec 10 13:03:35 ipvs-test-102-wan Keepalived[26500]: Running on Linux 4.9.58-1.1.x86_64 #1 SMP Mon Oct 23 10:29:39 UTC 2017 (built for Linux 4.9.58)
Dec 10 13:03:35 ipvs-test-102-wan Keepalived[26500]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 10 13:03:35 ipvs-test-102-wan Keepalived[26501]: Starting Healthcheck child process, pid=26503
Dec 10 13:03:35 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 10 13:03:35 ipvs-test-102-wan Keepalived_healthcheckers[26503]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Dec 10 13:03:35 ipvs-test-102-wan Keepalived_healthcheckers[26503]: SECURITY VIOLATION - check scripts are being executed but script_security not enabled.
Dec 10 13:03:35 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Initializing ipvs
Dec 10 13:03:35 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Activating healthchecker for service [10.1.57.100]:tcp:80 for VS [10.9.200.200]:tcp:80
Dec 10 13:03:35 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Activating healthchecker for service [10.1.57.101]:tcp:80 for VS [10.9.200.200]:tcp:80
Dec 10 13:03:38 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Misc check for [[10.1.57.101]:tcp:80 VS [10.9.200.200]:tcp:80] by [/etc/keepalived/HC/HC-DB-master] succeeded.
Dec 10 13:03:38 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Adding service [10.1.57.101]:tcp:80 to VS [10.9.200.200]:tcp:80
Dec 10 13:03:38 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Gained quorum 1+0=1 <= 1 for VS [10.9.200.200]:tcp:80
Dec 10 13:03:38 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Remote SMTP server [91.207.59.201]:25 connected.
Dec 10 13:03:38 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Remote SMTP server [91.207.59.201]:25 connected.
Dec 10 13:03:38 ipvs-test-102-wan Keepalived_healthcheckers[26503]: SMTP alert successfully sent.
Dec 10 13:03:38 ipvs-test-102-wan Keepalived_healthcheckers[26503]: SMTP alert successfully sent.
Dec 10 13:03:40 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Misc check for [[10.1.57.100]:tcp:80 VS [10.9.200.200]:tcp:80] by [/etc/keepalived/HC/HC-DB-master] succeeded.
Dec 10 13:03:40 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Adding service [10.1.57.100]:tcp:80 to VS [10.9.200.200]:tcp:80
Dec 10 13:03:40 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Remote SMTP server [91.207.59.201]:25 connected.
Dec 10 13:03:40 ipvs-test-102-wan Keepalived_healthcheckers[26503]: SMTP alert successfully sent.
Dec 10 13:03:53 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Misc check for [[10.1.57.100]:tcp:80 VS [10.9.200.200]:tcp:80] by [/etc/keepalived/HC/HC-DB-master] failed (exited with status 1).
Dec 10 13:03:53 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Removing service [10.1.57.100]:tcp:80 to VS [10.9.200.200]:tcp:80
Dec 10 13:03:53 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Remote SMTP server [91.207.59.201]:25 connected.
Dec 10 13:03:53 ipvs-test-102-wan Keepalived_healthcheckers[26503]: SMTP alert successfully sent.
Dec 10 13:04:03 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Misc check for [[10.1.57.100]:tcp:80 VS [10.9.200.200]:tcp:80] by [/etc/keepalived/HC/HC-DB-master] succeeded.
Dec 10 13:04:03 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Adding service [10.1.57.100]:tcp:80 to VS [10.9.200.200]:tcp:80
Dec 10 13:04:03 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Remote SMTP server [91.207.59.201]:25 connected.
Dec 10 13:04:03 ipvs-test-102-wan Keepalived_healthcheckers[26503]: SMTP alert successfully sent.
Dec 10 13:05:51 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Misc check for [[10.1.57.100]:tcp:80 VS [10.9.200.200]:tcp:80] by [/etc/keepalived/HC/HC-DB-master] failed (exited with status 1).
Dec 10 13:05:51 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Removing service [10.1.57.100]:tcp:80 to VS [10.9.200.200]:tcp:80
Dec 10 13:05:51 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Remote SMTP server [91.207.59.201]:25 connected.
Dec 10 13:05:51 ipvs-test-102-wan Keepalived_healthcheckers[26503]: SMTP alert successfully sent.
Dec 10 13:05:56 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Misc check for [[10.1.57.100]:tcp:80 VS [10.9.200.200]:tcp:80] by [/etc/keepalived/HC/HC-DB-master] succeeded.
Dec 10 13:05:56 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Adding service [10.1.57.100]:tcp:80 to VS [10.9.200.200]:tcp:80
Dec 10 13:05:56 ipvs-test-102-wan Keepalived_healthcheckers[26503]: Remote SMTP server [91.207.59.201]:25 connected.
Dec 10 13:05:56 ipvs-test-102-wan Keepalived_healthcheckers[26503]: SMTP alert successfully sent.

**Comment by pqarmitage** [comment]
`retry` works for me with `misc_check`, in any of the 3 identified positions.

keepalived only logs the script failure after the retries have expired, so in your case the script will have returned a non-zero exit code 4 times before the failure is logged, so what you are seeing is exactly what I would expect.

To see what is happening, the following patch will log the exit code from the scripts each time they are run:
```
diff --git a/keepalived/check/check_misc.c b/keepalived/check/check_misc.c
index 715eb6c1..d458ed89 100644
--- a/keepalived/check/check_misc.c
+++ b/keepalived/check/check_misc.c
@@ -353,6 +353,7 @@ misc_check_child_thread(thread_t * thread)
 
        if (WIFEXITED(wait_status)) {
                int status = WEXITSTATUS(wait_status);
+log_message(LOG_INFO, "Script exited with status %d", status);
 
                if (status == 0 ||
                    (misck_checker->dynamic && status >= 2 && status <= 255)) {
```

**Comment by igroost** [comment]
When configuration TCP_CHECK in the logs you can see all the failed attempts

#TEST-0
virtual_server 10.9.200.200 80       {
        delay_loop 5
        alpha 1
        omega 1
        lvs_sched rr
        lvs_method TUN
        smtp_alert on
        retry 3
        delay_before_retry 3 
        protocol TCP

    quorum 1


        quorum_up "/sbin/ip -4 addr add 10.9.200.200/32 dev lo"
        quorum_down "/sbin/ip -4 addr del 10.9.200.200/32 dev lo"

#web-1
real_server 10.1.57.100 80 {
        retry 3
        TCP_CHECK {
            connect_timeout 3
                   }
                         }

#web-2
real_server 10.1.57.101 80 {
        retry 3
        TCP_CHECK {
            connect_timeout 3
                   }
                            }
                                      }

###########################################################################################


Dec 11 10:37:56 ipvs-test-102-wan Keepalived[23073]: Starting Keepalived v2.0.0 (05/27,2018)
Dec 11 10:37:56 ipvs-test-102-wan Keepalived[23073]: Running on Linux 4.9.58-1.1.x86_64 #1 SMP Mon Oct 23 10:29:39 UTC 2017 (built for Linux 4.9.58)
Dec 11 10:37:56 ipvs-test-102-wan Keepalived[23073]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 11 10:37:56 ipvs-test-102-wan Keepalived[23074]: Starting Healthcheck child process, pid=23076
Dec 11 10:37:56 ipvs-test-102-wan Keepalived_healthcheckers[23076]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 11 10:37:56 ipvs-test-102-wan Keepalived_healthcheckers[23076]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Dec 11 10:37:56 ipvs-test-102-wan Keepalived_healthcheckers[23076]: SECURITY VIOLATION - check scripts are being executed but script_security not enabled.
Dec 11 10:37:56 ipvs-test-102-wan Keepalived_healthcheckers[23076]: Initializing ipvs
Dec 11 10:37:56 ipvs-test-102-wan Keepalived_healthcheckers[23076]: Activating healthchecker for service [10.1.57.100]:tcp:80 for VS [10.9.200.200]:tcp:80
Dec 11 10:37:56 ipvs-test-102-wan Keepalived_healthcheckers[23076]: Activating healthchecker for service [10.1.57.101]:tcp:80 for VS [10.9.200.200]:tcp:80
Dec 11 10:37:59 ipvs-test-102-wan Keepalived_healthcheckers[23076]: TCP connection to [10.1.57.101]:tcp:80 success.
Dec 11 10:37:59 ipvs-test-102-wan Keepalived_healthcheckers[23076]: Adding service [10.1.57.101]:tcp:80 to VS [10.9.200.200]:tcp:80
Dec 11 10:37:59 ipvs-test-102-wan Keepalived_healthcheckers[23076]: Gained quorum 1+0=1 <= 1 for VS [10.9.200.200]:tcp:80
Dec 11 10:37:59 ipvs-test-102-wan Keepalived_healthcheckers[23076]: Remote SMTP server [91.207.59.201]:25 connected.
Dec 11 10:37:59 ipvs-test-102-wan Keepalived_healthcheckers[23076]: Remote SMTP server [91.207.59.201]:25 connected.
Dec 11 10:37:59 ipvs-test-102-wan Keepalived_healthcheckers[23076]: SMTP alert successfully sent.
Dec 11 10:37:59 ipvs-test-102-wan Keepalived_healthcheckers[23076]: SMTP alert successfully sent.
Dec 11 10:38:01 ipvs-test-102-wan Keepalived_healthcheckers[23076]: TCP connection to [10.1.57.100]:tcp:80 success.
Dec 11 10:38:01 ipvs-test-102-wan Keepalived_healthcheckers[23076]: Adding service [10.1.57.100]:tcp:80 to VS [10.9.200.200]:tcp:80
Dec 11 10:38:01 ipvs-test-102-wan Keepalived_healthcheckers[23076]: Remote SMTP server [91.207.59.201]:25 connected.
Dec 11 10:38:01 ipvs-test-102-wan Keepalived_healthcheckers[23076]: SMTP alert successfully sent.
Dec 11 10:40:06 ipvs-test-102-wan Keepalived_healthcheckers[23076]: TCP connection to [10.1.57.100]:tcp:80 failed.
Dec 11 10:40:07 ipvs-test-102-wan Keepalived_healthcheckers[23076]: TCP connection to [10.1.57.100]:tcp:80 failed.
Dec 11 10:40:08 ipvs-test-102-wan Keepalived_healthcheckers[23076]: TCP connection to [10.1.57.100]:tcp:80 failed.
Dec 11 10:40:09 ipvs-test-102-wan Keepalived_healthcheckers[23076]: TCP connection to [10.1.57.100]:tcp:80 failed.
Dec 11 10:40:09 ipvs-test-102-wan Keepalived_healthcheckers[23076]: Check on service [10.1.57.100]:tcp:80 failed after 3 retries.
Dec 11 10:40:09 ipvs-test-102-wan Keepalived_healthcheckers[23076]: Removing service [10.1.57.100]:tcp:80 to VS [10.9.200.200]:tcp:80
Dec 11 10:40:09 ipvs-test-102-wan Keepalived_healthcheckers[23076]: Remote SMTP server [91.207.59.201]:25 connected.
Dec 11 10:40:09 ipvs-test-102-wan Keepalived_healthcheckers[23076]: SMTP alert successfully sent.

I understand correctly that the lack of reports of three failed MIC_CHECK attempts is so done by design?

I understand that in the case of MIC_CHECK check the logic is as follows: check runs the number of times specified in retry in any of the sections (VIP,real_server,misc_check). But in a log of the message only the final result of cumulative performance of checks is written? All right?

Specify, in a situation when retry is 3, the first two checks are not successful, the last one is successful, what will be recorded in the log?

**Comment by pqarmitage** [comment]
`I understand correctly that the lack of reports of three failed MISC_CHECK attempts is so done by design?`
I suspect it is just down to how it was implemented at the time.

`But in a log of the message only the final result of cumulative performance of checks is written? All right?`
That is correct.

`Specify, in a situation when retry is 3, the first two checks are not successful, the last one is successful, what will be recorded in the log?`
In this case nothing will be recorded. The first check fails, the first retry fails, the second retry is successful and so nothing is logged. Even if there are three failures and the fourth check is successful, nothing will be logged since the third retry is successful. If there are 4 successive failures, then there will be a log entry after the fourth failure and the real server will only then be considered to be down.

**Comment by igroost** [comment]
> I suspect it is just down to how it was implemented at the time.

By implemented do you mean that the patch code proposed above was included in the official release? If Yes, which one?

**Comment by pqarmitage** [comment]
The purpose of the patch above was only so that you could see that the standard log failure message for MISC_CHECK was only output after retries + 1 failures. It was never my intention that it should be included in an official release.

I am currently looking at the various checkers to see when they output failure messages to the log. So far, most of them only log a failure when the retries have expired.

**Comment by igroost** [comment]
> In this case nothing will be recorded. The first check fails, the first retry fails, the second retry is successful and so nothing is logged. Even if there are three failures and the fourth check is successful, nothing will be logged since the third retry is successful. If there are 4 successive failures, then there will be a log entry after the fourth failure and the real server will only then be considered to be down.

Thanks for the answers. You can once again clarify the logic of the work. I understood so: 
1) retry is set to 3. The first two MIC_CHECK checks are unsuccessful, the third MIC_CHECK is successful. In this case RS will not be marked as fail and there will be no record in the log about unsuccessful check (there will be a record that MIC_CHECK has passed).

2) retry is set to 3. The first two MIC_CHECK checks are successful, the third MISC_CHECK is unsuccessful. How in this case RS will be marked and what will be recorded in the log?

**Comment by pqarmitage** [comment]
```
1. retry is set to 3. The first two MIC_CHECK checks are unsuccessful, the third MIC_CHECK is successful. In this case RS will not be marked as fail and there will be no record in the log about unsuccessful check (there will be a record that MIC_CHECK has passed).
```
There will be no record in the log about the unsuccessful checks nor will there be a record about the subsequent successful check.

```
2. retry is set to 3. The first two MIC_CHECK checks are successful, the third MISC_CHECK is unsuccessful. How in this case RS will be marked and what will be recorded in the log?
```
There will again be no log entries, because there were only 2 unsuccessful retries, and so the MISC_CHECK didn't fail.

The default value for `retry` is 0, which requires 1 failure to go to fault state. Setting `retry` to 3 requires 4 failures (1 + 3) in order to go to the fault state. In this case there will be 1 log entry to say that the checker has failed, and another one when the checker starts succeeding again.

**Comment by igroost** [comment]
Thanks for the answers. I think the ticket can be closed.

**Comment by igroost** [comment]
Thanks!

**Comment by pqarmitage** [comment]
Commit 06df618 makes all healthchecks log a failure after the retries have expired. Specifying log_all_failures on a checker or the global_defs checker_log_all_failures will cause all failures to be reported.
