### ISSUE TITLE
Keepalived will not work after network card restart

### ISSUE THREAD

**Issue by ox123** [acassen/keepalived#1092]
- version
[root@xx]# keepalived -v
Keepalived v1.2.13 (01/01,2018)

### problem:
-  when the network card restart , the keepalived can not provide service

###  is there any way to resolve this reliable issues? when I restart the network card ,I do not need to restart the keepalived and the keepalived can continue work

**Comment by pqarmitage** [comment]
Please use the current version of keepalived, which should support a network card restart.

**Comment by ox123** [comment]
Ok,Thanks,can you show the patch? I want to know how it resolved.

**Comment by pqarmitage** [comment]
Looking in the ChangeLog file, one feature added in v2.0.0 was
```
        * Process interface state changes immediately.
            Previously keepalived waited for advert timer expiry. The problem
            was that if an interface went down and came back up before the
            next timer expiry, and addresses, routes and VMACs that we had
            configured on that interface would be removed, but we wouldn't
            know about it.
```
Without searching through all the commit logs I'm not sure which commit it was.

**Comment by ox123** [comment]
Thanks any way
