### ISSUE TITLE
Keepalived still sending VRRP messages when interface is down

### ISSUE THREAD

**Issue by xflord** [acassen/keepalived#1097]
Hi 

I am using two virtual machines(WMware) to test my config file. The IP address is 192.168.23.131 and 192.168.23.139. Then I set up two vrrp instances, the VIPs are 192.168.23.201 and 192.168.23.202. (config file is attached  [config file.zip](https://github.com/acassen/keepalived/files/2729436/config.file.zip))

I set each machine with a master instance. So the VIP 192.168.23.201 will be attached with 192.168.23.131, and the 192.168.23.202 will be attached with 192.168.23.139.

When I use “ifdown” to disable the network of the first machine(192.168.23.131), then the two machines should be double master, and each machine should have two VIPs. 

But in fact, the second machine(192.168.23.139) has only ONE VIP(192.168.23.202). The other machine has two VIPs.

-  I use Wireshark in the second machine to find out what happened. It appears that before I disable the network, every machine sends out one VRRP message once.

![image](https://user-images.githubusercontent.com/10804808/50723606-f0e6f300-111a-11e9-961e-5e16bd59310e.png)

- After I disable the network, the first machine will send both VRRP message.

![image](https://user-images.githubusercontent.com/10804808/50723665-a154f700-111b-11e9-8466-c7476a69af9e.png)

How can I fix it, is there something wrong in my config file?

My OS is Centos 6.9
keepalived version info:

> [root@bogon keepalived]# keepalived -v
> Keepalived v2.0.10 (11/12,2018)
> 
> Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>
> 
> Built with kernel headers for Linux 2.6.32
> Running on Linux 2.6.32-696.23.1.el6.x86_64 #1 SMP Tue Mar 13 22:44:18 UTC 2018
> 
> configure options: --prefix=/usr/local/keepalived
> 
> Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING
> 
> System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC GLOB_BRACE SO_MARK SCHED_RT SCHED_RESET_ON_FORK

Log in second machine(192.168.23.139)

> Jan  5 19:01:19 bogon Keepalived_vrrp[99513]: Sending gratuitous ARP on eth2 for 192.168.23.202
> Jan  5 19:01:19 bogon Keepalived_vrrp[99513]: (VI_2) Received advert from 192.168.23.131 with lower priority 70, ours 100, forcing new election
> Jan  5 19:01:19 bogon Keepalived_vrrp[99513]: Sending gratuitous ARP on eth2 for 192.168.23.202
> Jan  5 19:01:19 bogon Keepalived_vrrp[99513]: (VI_2) Sending/queueing gratuitous ARPs on eth2 for 192.168.23.202
> Jan  5 19:01:19 bogon Keepalived_vrrp[99513]: Sending gratuitous ARP on eth2 for 192.168.23.202
> Jan  5 19:01:19 bogon Keepalived_vrrp[99513]: Sending gratuitous ARP on eth2 for 192.168.23.202
> Jan  5 19:01:19 bogon Keepalived_vrrp[99513]: Sending gratuitous ARP on eth2 for 192.168.23.202
> Jan  5 19:01:19 bogon Keepalived_vrrp[99513]: Sending gratuitous ARP on eth2 for 192.168.23.202
> Jan  5 19:01:20 bogon Keepalived_vrrp[99513]: Sending gratuitous ARP on eth2 for 192.168.23.202
> Jan  5 19:01:20 bogon Keepalived_vrrp[99513]: (VI_2) Sending/queueing gratuitous ARPs on eth2 for 192.168.23.202
> Jan  5 19:01:20 bogon Keepalived_vrrp[99513]: Sending gratuitous ARP on eth2 for 192.168.23.202
> Jan  5 19:01:20 bogon Keepalived_vrrp[99513]: Sending gratuitous ARP on eth2 for 192.168.23.202
> Jan  5 19:01:20 bogon Keepalived_vrrp[99513]: Sending gratuitous ARP on eth2 for 192.168.23.202
> Jan  5 19:01:20 bogon Keepalived_vrrp[99513]: Sending gratuitous ARP on eth2 for 192.168.23.202
> Jan  5 19:01:20 bogon Keepalived_vrrp[99513]: (VI_2) Received advert from 192.168.23.131 with lower priority 70, ours 100, forcing new election
> Jan  5 19:01:20 bogon Keepalived_vrrp[99513]: Sending gratuitous ARP on eth2 for 192.168.23.202
> Jan  5 19:01:20 bogon Keepalived_vrrp[99513]: (VI_2) Sending/queueing gratuitous ARPs on eth2 for 192.168.23.202

**Comment by pqarmitage** [comment]
@xflord The only way I can reproduce what you are seeing is if I add `dont_track_primary` to each vrrp instance configuration. It appears that if an interface is downed, packets can still be received on the interface, but cannot be sent. Machine 139 is therefore not receiving any adverts and so both instances are master. On machine 131, it is still receiving adverts from machine 139, and so VI_2 remains as backup.

The question is why is keepalived on 131 not seeing the interface going down, and consequently transition the vrrp instances to FAULT state (which is what I observe if I don't specify `dont_track_primary`). I can only imagine that ifdown is not behaving as expected. After you have downed the interface, can you execute `ip link show eth2` and post the output.

**Comment by xflord** [comment]
@pqarmitage thanks for replying. I think you are right, I find after I disabled the interface, it still showed the state as "UP".

Maybe it is a problem for Centos... Have you ever seen this before? How can I fix it? 

Here is the execute info.

> [root@localhost src]# ifup eth2
> 活跃连接状态：激活中  _`(activing)`_
> 活跃连接路径：/org/freedesktop/NetworkManager/ActiveConnection/7
> 状态：已激活   _`(activted)`_
> 连接被激活
>
> [root@localhost src]# ip addr
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>     inet6 ::1/128 scope host 
>        valid_lft forever preferred_lft forever
> 2: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
>     link/ether 00:0c:29:d5:e2:ad brd ff:ff:ff:ff:ff:ff
>     inet 192.168.23.131/24 brd 192.168.23.255 scope global eth2
>     inet 192.168.23.201/32 scope global eth2
>     inet6 fe80::20c:29ff:fed5:e2ad/64 scope link 
>        valid_lft forever preferred_lft forever
> 3: pan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN 
>     link/ether 0a:a1:bc:6e:fe:c6 brd ff:ff:ff:ff:ff:ff
>
> [root@localhost src]# ifdown eth2
> 设备状态：3 （断开连接） _`(disconnected)`_
>
> [root@localhost src]# ip addr
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>     inet6 ::1/128 scope host 
>        valid_lft forever preferred_lft forever
> 2: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
>     link/ether 00:0c:29:d5:e2:ad brd ff:ff:ff:ff:ff:ff
>     inet 192.168.23.201/32 scope global eth2
>     inet 192.168.23.202/32 scope global eth2
>     inet6 fe80::20c:29ff:fed5:e2ad/64 scope link 
>        valid_lft forever preferred_lft forever
> 3: pan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN 
>     link/ether 0a:a1:bc:6e:fe:c6 brd ff:ff:ff:ff:ff:ff
>
> [root@localhost src]# ip link show eth2
> 2: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
>     link/ether 00:0c:29:d5:e2:ad brd ff:ff:ff:ff:ff:ff

**Comment by xflord** [comment]
@pqarmitage thanks! `ip link set eth2 down` works for me.
