### ISSUE TITLE
Compiling error on CentOS 7.5 and CentOS 7.6

### ISSUE THREAD

**Issue by gccli** [acassen/keepalived#1098]
On CentOS 7.5
./configure --prefix=/usr --with-kernel-dir=/lib/modules/3.10.0-862.14.4.el7.x86_64/build
...
configure: error: kernel source path /lib/modules/3.10.0-862.14.4.el7.x86_64/build appears to be an unprocessed kernel source tree

On CentOS 7.6
./configure --prefix=/usr --with-kernel-dir=/lib/modules/3.10.0-957.el7.x86_64/build
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
configure: error: kernel source path /lib/modules/3.10.0-957.el7.x86_64/build appears to be an unprocessed kernel source tree

**Comment by gccli** [comment]
I download package from http://www.keepalived.org/software/keepalived-2.0.11.tar.gz

**Comment by pqarmitage** [comment]
The headers in /lib/modules/3.10.0-957.el7.x86_64/build are not kernel headers for including in applications (I think they are headers for building additional kernel modules), and the kernel header files needed by keepalived are not installed in that tree. The kernel headers for including in applications are installed from the kernel-headers rpm and are installed in /usr/include/linux.

If you extracted the headers from a kernel-headers rpm and installed them in a not standard directory, then you could use --with-kernel-dir to specify the path to those headers.

**Comment by gccli** [comment]
This issue occur when I run "make rpm":

./configure --prefix=/usr
make rpm
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-nftables --disable-libiptc --disable-libipset --disable-snmp-reply-v3-for-v2 --with-init=systemd --with-kernel-dir=/lib/modules/3.10.0-862.14.4.el7/build
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for x86_64-redhat-linux-gnu-pkg-config... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
configure: error: kernel source path /lib/modules/3.10.0-862.14.4.el7/build/include does not exist
error: Bad exit status from /var/tmp/rpm-tmp.dDVRvL (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.dDVRvL (%build)
make: *** [rpm] Error 1

in keepalived.spec
%configure $CONFIG_OPTS \
%{?el3:--includedir="/usr/kerberos/include"} \
%{?rh9:--includedir="/usr/kerberos/include"} \
    --with-kernel-dir="/lib/modules/%{kernel}/build"

**Comment by pqarmitage** [comment]
Commit 4e8cd6f removed the lines
```
%{?el3:--includedir="/usr/kerberos/include"}
%{?rh9:--includedir="/usr/kerberos/include"}
--with-kernel-dir="/lib/modules/%{kernel}/build"
```
so the configure entry is now just:
`%configure $CONFIG_OPTS`

You also need to have the kernel-headers package installed (I have just pushed commit 47b980e to update the keepalived.spec.in file to change the build-requires to include kernel-headers instead of kernel-devel).
