### ISSUE TITLE
VRRP IPv6: when selecting a LLA for outgoing VRRP announcements, filter out VRRP VIPs

### ISSUE THREAD

**Issue by Supermathie** [acassen/keepalived#1122]
I've identified a bug in keepalived 1.3.2 where VIPs are selected after a config reload as the source address for VRRP announcements.

(I'm quite happy to test a later version in our environment with some prior assurance this problem is addressed in that version)

By default, keepalived will select the first primary LLA on an interface to use for outgoing announcements. This works great on initial startup, but on configuration reload it will do this again which can lead to the undesired effect of a VRRP IP being selected as the source address.

The net impact of this is that under the right conditions two VRRP participants can both claim ownership on a VRRP instance (split brain). This happened organically in our environment and the root cause was traced to this.

I think that the correct thing to do is to:
* prefer the autoconfig LLA if one exists
* NEVER use any VIPs as the source address for VRRP announcements
* re-run the selection algorithm if the address we're using to send disappears

### Example

from `keepalived.conf`:
```
vrrp_instance net62a {
	state BACKUP
	interface net
	priority 125 # router B has 115
	virtual_router_id 52

	track_interface {
		bond0
	}
	virtual_ipaddress {
		fe80::ffff:2a/64 dev net
		2001:db8::2a/128 dev net
	}
}
vrrp_instance net62b {
	state BACKUP
	interface net
	priority 115 # router B has 125
	virtual_router_id 53

	track_interface {
		bond0
	}

	virtual_ipaddress {
		fe80::ffff:2b/64 dev net
		2001:db8::2b/128 dev net
	}
}
```

In our case Router A had (correctly) taken over net62b, then reloaded the configuration. It was then sending out advertisements using a VIP from net62b:

```
634.955611064   fe80::ffff:2b   VRRP    52      Announcement (v3)       125
635.684113843   fe80::ffff:2b   VRRP    53      Announcement (v3)       115
635.955858787   fe80::ffff:2b   VRRP    52      Announcement (v3)       125
636.684872148   fe80::ffff:2b   VRRP    53      Announcement (v3)       115
636.956241357   fe80::ffff:2b   VRRP    52      Announcement (v3)       125
637.684909382   fe80::ffff:2b   VRRP    53      Announcement (v3)       115
```

But when keepalived was restarted on Router B, it (correctly) took over net62b and claimed the `fe80::ffff:2b` address.

Router A could no longer then send out VRRP announcements *at all*, leading to a state where:

Router A claimed ownership of net62a with a priority of 125
Router B claimed ownership of net62b with a priority of 125, **and net62a with a priority of 115**

The following packets on the wire are all from Router B and Router A's announcements have disappeared:

```
637.685645011   fe80::ae1f:6bff:fe94:f084       VRRP    53      Announcement (v3)       125
638.686540296   fe80::ae1f:6bff:fe94:f084       VRRP    53      Announcement (v3)       125
639.696741883   fe80::ae1f:6bff:fe94:f084       VRRP    53      Announcement (v3)       125
640.566603635   fe80::ae1f:6bff:fe94:f084       VRRP    52      Announcement (v3)       115
640.697054695   fe80::ae1f:6bff:fe94:f084       VRRP    53      Announcement (v3)       125
641.578592501   fe80::ae1f:6bff:fe94:f084       VRRP    52      Announcement (v3)       115
```

Both Router A and Router B at this point had the VIPs for net62a assigned to their interfaces.

A full recovery was made once the cause was identified by doing a full restart of keepalived on both routers.

The hypothesis as to cause was then confirmed triggered again by reloading the configuration on Router B, causing the source address to change to a VIP:

```
2146.186463167  fe80::ae1f:6bff:fe94:f084       ff02::12        VRRP    53      Announcement (v3)       125
2147.186536401  fe80::ae1f:6bff:fe94:f084       ff02::12        VRRP    53      Announcement (v3)       125
2148.735164851  fe80::ffff:2b   ff02::12        VRRP    53      Announcement (v3)       125
2149.735719370  fe80::ffff:2b   ff02::12        VRRP    53      Announcement (v3)       125
```

**Comment by acassen** [comment]
1.3.2 is way too old. We are currently to release 2.0.12 with a bunch of fixes and extensions. I would strongly encourage you to upgrade if possible. We are not back-porting bug fixes. If you still have the same issue with 2.0.12 or later release you can re-open this issue thread.

**Comment by Supermathie** [comment]
I've done some testing on 2.0.12 and it looks like this problem doesn't recur given the different way that restarts are handled. :+1:

**Comment by Supermathie** [comment]
Turns out that it still *does* recur on 2.0.12 it just doesn't get triggered in the same way that it did on 1.3.2:

All captures below are from packets sent out by keepalived 2.0.12:
```
195.146763171	fe80::2e0:4cff:fe68:265e	VRRP	Announcement (v3)	115
196.146868581	fe80::2e0:4cff:fe68:265e	VRRP	Announcement (v3)	115
197.146896702	fe80::2e0:4cff:fe68:265e	VRRP	Announcement (v3)	115
198.146965961	fe80::2e0:4cff:fe68:265e	VRRP	Announcement (v3)	115
«router A starts up and takes over»
198.667205630	fe80::ffff:2a	VRRP	Announcement (v3)	125
199.667380676	fe80::ffff:2a	VRRP	Announcement (v3)	125
200.667439212	fe80::ffff:2a	VRRP	Announcement (v3)	125
201.667582446	fe80::ffff:2a	VRRP	Announcement (v3)	125
```
```
49.784512414	fe80::ffff:2a	VRRP	Announcement (v3)	125
50.784556776	fe80::ffff:2a	VRRP	Announcement (v3)	125
51.784603889	fe80::ffff:2a	VRRP	Announcement (v3)	125
«full restart of keepalived on router A»
52.455509032	fe80::ffff:2a	VRRP	Announcement (v3)	0
«below router B takes over»
54.017893705	fe80::2e0:4cff:fe68:265e	VRRP	Announcement (v3)	115
55.017959657	fe80::2e0:4cff:fe68:265e	VRRP	Announcement (v3)	115
56.018323460	fe80::2e0:4cff:fe68:265e	VRRP	Announcement (v3)	115
57.018471439	fe80::2e0:4cff:fe68:265e	VRRP	Announcement (v3)	115
«router A starts up and takes over»
57.443146596	fe80::ae1f:6bff:fe96:3c61	VRRP	Announcement (v3)	125
58.443277965	fe80::ae1f:6bff:fe96:3c61	VRRP	Announcement (v3)	125
59.443365539	fe80::ae1f:6bff:fe96:3c61	VRRP	Announcement (v3)	125
60.443498469	fe80::ae1f:6bff:fe96:3c61	VRRP	Announcement (v3)	125
```

A HUP reload no longer triggers the problem, but as evidenced by the first capture a VIP may still be selected as the source address.

**Comment by pqarmitage** [comment]
@Supermathie Can you please provide exactly what commands you are using to:
a) Stop keepalived
b) Make keepalived reload its configuration
c) Do a full reload

From the testing I have done, sending SIGTERM to the parent keepalived process to stop keepalived doesn't cause the problem, and sending a SIGHUP to the parent keepalived process to make keepalived reload its configuration also doesn't cause the problem.

The only way that I can make the problem occur is if keepalived abnormally terminates (for example by sending SIGKILL to the vrrp child process). In this case keepalived cannot remove the addresses it added while running, and so when keepalived starts again, it picks the first link local address to use as the source address for sending adverts. I agree this isn't right, but before I make any changes to the code, I do need to know how you are stopping, reloading and restarting keepalived, in order to make sure my understanding of what is happening is correct.

**Comment by pqarmitage** [comment]
@Supermathie I'm not sure if you are still experiencing the problem you reported, since you haven't responded for 11 days. However, commit 6d8fc7b resolves the issue of VIPs left configured on an interface when keepalived crashes being used as source addresses for adverts when keepalived restarts.

**Comment by Supermathie** [comment]
Everything's running in a docker container with access to the host network. I'm using TERM / HUP / `docker restart` (which does a TERM and then a normal startup).

(0I hadn't responded as I was moving, but things have mostly settled now)

**Comment by pqarmitage** [comment]
@Supermathie Does the latest code resolve your problem? Commit 6d8fc7b should stop VIPs being used as the source address of adverts.

**Comment by Supermathie** [comment]
It does, thanks!
