### ISSUE TITLE
Question: source IP address

### ISSUE THREAD

**Issue by aledbf** [acassen/keepalived#1132]
Hi, is there any alternative to HAProxy with proxy protocol enabled to preserve the source IP address of the connection? (without haproxy I get the IP where keepalived is running)
Thanks!

**Comment by acassen** [comment]
Hello, there is just not enough info in your question. Please add more emphasize. Please, provide configurations, exemples, ... and spot precisely feature requested.

**Comment by acassen** [comment]
no reply, but you probably refer to https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt
If you define virtual_server it will make the job. But IPVS is a layer4 loadbalancer so layer7 protocol header will never be added since it is out of scope.

**Comment by jobcespedes** [comment]
Hi, 

I was looking into this scenario. Keepalived native "proxy protocol". My use case is one where keepalive is used for LVS NAT mode. It is my understanding that "proxy protocol" is not a layer 7 protocol but a layer 4 one.

Any pointers on how to implement it directly on Keepalived?

**Comment by jobcespedes** [comment]
[Dpvs recently implemented it](https://github.com/iqiyi/dpvs/pull/923). Based on their work, It is more lines of code that I expected.

**Comment by jobcespedes** [comment]
For this purpose, we ended up creating a lightweight proxy called [ppp](https://github.com/krestomatio/ppp) to push the PROXY protocol header to TCP connections. It can be installed in front of Keepalived. It is  written in go. We are testing it.
