### ISSUE TITLE
typo in vrrp/vrrp_nftables.c: log_message(LOG_INGO

### ISSUE THREAD

**Issue by slimlv** [acassen/keepalived#1135]
there is bunch of lines with invalid priority in log_message in **vrrp/vrrp_nftables.c**: 

> 		case NFT_MSG_NEWTABLE: log_message(LOG_INGO, "%s", "NFT_MSG_NEWTABLE"); new_table(nlh);break;

**Comment by pqarmitage** [comment]
Many thanks for the report.

Commit 6d2eaa2 fixes the typos, but they were included in a `#ifdef INCLUDE_UNUSED_CODE` block, which is why the errors weren't detected.
