### ISSUE TITLE
Sync all the states (tcp connection) from the Master LVS to Backup LVS

### ISSUE THREAD

**Issue by kttang88** [acassen/keepalived#1138]
I configured the LVS as Master and Backup pair.
The keepalived.conf as below;
If the master is down, the backup will become master. how can I monitor the tcp connections states 
How to Sync all the states (tcp connection) from the Master LVS to Backup LVS so that the new master will have all the tcp connections states when it take over.
I added  lvs_sync_daemon_interface eno16780032 to sync the daemon, is this correct?
----------------------------------
vrrp_instance VI_1 {
  # initial state
  state MASTER
  interface eno16780032
  lvs_sync_daemon_interface eno16780032
  # arbitary unique number 0..255
  # used to differentiate multiple instances of vrrpd
  virtual_router_id 1
  # for electing MASTER, highest priority wins.
  # to be MASTER, make 50 more than other machines.
  priority 100
  authentication {
    auth_type abc
    auth_pass abc
  }
  virtual_ipaddress {
    10.140.25.43/24
  }
  # Invoked to master transition
  notify_master "/etc/keepalived/bypass_ipvs.sh del 10.140.25.43"
  # Invoked to slave transition
  notify_backup "/etc/keepalived/bypass_ipvs.sh add 10.140.25.43"
  # Invoked to fault transition
  notify_fault "/etc/keepalived/bypass_ipvs.sh add 10.140.25.43"
}

# virtual MM
virtual_server 10.140.25.43 1800 {
  delay_loop 15
  lb_algo rr
  lb_kind DR
  protocol TCP

# 10.140.25.16 
  real_server 10.140.25.16 1800 {
    TCP_CHECK {
      connect_timeout 3
    }
  }

# 10.140.25.28 
  real_server 10.140.25.28 1800 {
    TCP_CHECK {
      connect_timeout 3
    }
  }

}

**Comment by pqarmitage** [comment]
@kttang88 You don't state which version of keepalived you are using. Although using `ivs_sync_daemon_interface` configured on a vrrp instance will work, it is now deprecated, and `lvs_sync_daemon` should be configured in the `global_defs` section (if your version of keepalived is v1.2.22 or earlier you will need to use `lvs_sync_daemon_interface` as you currently have it). This should sync the IPVS 'connections' from the master to the backup.

Apart from `auth type abc` your configuration looks reasonable, although it is not easy to tell with the formatting. I assume the large bold entries are comments starting with '#'.

To monitor the IPVS connection states, run the following:
`ipvsadm -L -c -n`
On the backup LVS this will show the connections that the sync daemon has been notified of by the master.

**Comment by kttang88** [comment]
The version I have is : # ipvsadm --version

Current when I issue command ipvsadm -L -n, the master and backup server did not shows the same connection pools. On Master server, it shows there is 8 connection on real server 1 and 7 connection on real server 2, where on the backup server, it shows only 1 connection on real server 2. These 2 severs seems like not sync. I and wonder what is wrong?
Master LVS server:
# ipvsadm -L -c -n
ipvsadm v1.27 2008/5/15 (compiled with popt and IPVS v1.2.1)
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.40.25.43:18000 rr
  -> 10.40.25.16:18000                Route       1               8          0         
  -> 10.40.25.28:18000               Route       1                7          0         
--------------------------------------------------------------
Backup LVS server
# ipvsadm -L -n
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.40.25.43:18000 rr
  -> 10.40.25.16:18000            Route   1      0          0         
  -> 10.40.25.28:18000            Route   1      1          0         
[root@ssr7dismp2 ~]# 
Hope you can shape some lights on this.

**Comment by pqarmitage** [comment]
@kttang88 Unfortunately the information you have provided doesn't help.

1. I asked for the version of keepalived, not of ipvsadm (**keepalived -v**)
2. The ipvsadm output you have provided is the output of **ipvsadm -L -n**. What we need is the output of **ipvsadm -L -c -n**.
3. Could you please also provide the output of **ipvsadm -L --daemon** from both servers and the output of **ipvsadm -L --stats** from both also.

Please see [lvs tutorial](http://www.ultramonkey.org/papers/lvs_tutorial/html/) for more information about ipvs and the ipvs daemon especially under the section `Connection Synchronisation - Existing Solution`. Note the statement `A connection is synchronised once the number of packets passes a threshold (3) and then every frequency (50) packets`, so you will need to ensure that sufficient traffic is forwarded to the real servers in order to ensure that synchronisation is happening.

**Comment by kttang88** [comment]
Attached are the information requested. Hope it helps.
# ipvsadm -v
ipvsadm v1.27 2008/5/15 (compiled with popt and IPVS v1.2.1)
---------------------------------------
#Master
---------------------------------------
# ipvsadm -L -c -n
IPVS connection entries
pro expire state       source             virtual            destination
TCP 133:35 ESTABLISHED 10.142.81.39:49715 10.40.25.43:18000  10.40.25.16:18000
TCP 43:28  ESTABLISHED 10.40.25.18:50868  10.40.25.43:18000  10.40.25.16:18000
TCP 53:35  ESTABLISHED 10.142.81.39:65528 10.40.25.43:18000  10.40.25.28:18000
TCP 42:56  ESTABLISHED 10.40.25.26:43492  10.40.25.43:18000  10.40.25.28:18000
TCP 64:46  ESTABLISHED 10.40.25.22:59335  10.40.25.43:18000  10.40.25.28:18000
TCP 85:32  ESTABLISHED 10.40.25.13:56794  10.40.25.43:18000  10.40.25.28:18000
TCP 89:54  ESTABLISHED 10.40.25.26:43362  10.40.25.43:18000  10.40.25.16:18000
TCP 76:15  ESTABLISHED 10.142.81.39:49159 10.40.25.43:18000  10.40.25.16:18000
TCP 49:29  ESTABLISHED 10.40.25.22:57556  10.40.25.43:18000  10.40.25.16:18000
TCP 97:00  ESTABLISHED 10.40.25.14:60486  10.40.25.43:18000  10.40.25.28:18000
TCP 118:50 ESTABLISHED 10.40.25.17:60184  10.40.25.43:18000  10.40.25.16:18000
TCP 70:14  ESTABLISHED 10.142.81.76:49199 10.40.25.43:18000  10.40.25.16:18000
TCP 35:17  ESTABLISHED 10.40.25.14:60545  10.40.25.43:18000  10.40.25.16:18000
TCP 60:24  ESTABLISHED 10.142.81.76:49183 10.40.25.43:18000  10.40.25.28:18000
---------------------------------------
# ipvsadm -L --daemon
master sync daemon (mcast=eno16780032, syncid=1)
-------------------------------------------------------------------
# ipvsadm -L --stats
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port               Conns   InPkts  OutPkts  InBytes OutBytes
  -> RemoteAddress:Port
TCP  10.40.25.43:biimenu                 2      137        0    35137        0
  -> 10.40.25.16:biimenu                  1      122        0    33920        0
  -> 10.40.25.28:biimenu                  1       15        0     1217        0
-------------------------------------------------------------------
#Backup
-------------------------------------------------------------------
# ipvsadm -L -c -n
IPVS connection entries
pro expire state       source             virtual            destination
-------------------------------------------------------------------
# ipvsadm -L --daemon
backup sync daemon (mcast=eno16780032, syncid=1)
-------------------------------------------------------------------
# ipvsadm -L --stats
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port               Conns   InPkts  OutPkts  InBytes OutBytes
  -> RemoteAddress:Port
TCP  10.40.25.43:biimenu                 0        0        0        0        0
  -> 10.40.25.16:biimenu                  0        0        0        0        0
  -> 10.40.25.28:biimenu                  0        0        0        0        0
-------------------------------------------------------------------

**Comment by acassen** [comment]
Hello, This is really an IPVS configuration related. Please use lvs-users mailing list to help you. Keepalived is on top of IPVS and before runing, especially if you are in tricky env, please try setup IPVS conf in a standalone manner then when everything is debugged and you finally get your conf working then you can put on top of it Keepalived.
This is not a keepalived feature issue.
