### ISSUE TITLE
rs still online although health check failed

### ISSUE THREAD

**Issue by HW-lj** [acassen/keepalived#1144]
Hi,:
	I found in some cases that the real server will not offline.
	First, we config a VS with a rs which owns alpha. After a while, the rs will online. And then we modify the  TCP_CHECK's connect_port to a failed one.In fact, I consider anything in struct conn_opts_t will perform same, and then reload the keepalived service. Then the old rs will still be online.
	Correct me if I'm wrong, the main reason is when we migrate checkers, we can not pass the
judgement "if (old_c->compare == new_c->compare && new_c->compare(old_c, new_c)) in function migrate_checkers"
so the new_checker is not alive, while the old_checker is alive. And then when we so health check, it's 
absolutely failed.
But now the new_checker state is same as health check's state, we would not remove the service, never.
	There are two solutions as I can see. The first one is to remove  the judgement, because if the rs's address and port is same is enough to see they are same. Another way is , in alpha mode, we should keep the old checker offline first. As far as I can think of, the first one is better.

**Comment by pqarmitage** [comment]
Could you please provide the output of `keepalived -v` and also a copy of your configuration so that we can test this.

**Comment by HW-lj** [comment]
The outpuut of keepalived -v:
# /usr/sbin/keepalived -v
Keepalived v2.0.6 (07/23,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.19.25

configure options: --build=aarch64-Huawei-linux-gnu --host=aarch64-Huawei-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --enable-snmp-rfc --enable-sha1 --with-init=systemd build_alias=aarch64-Huawei-linux-gnu host_alias=aarch64-Huawei-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fasynchronous-unwind-tables -fstack-clash-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK

The config before reload, the port 22 is open.
`
! Configuration File for keepalived
  
virtual_server 9.82.128.242 22 {
    delay_loop 6
    lb_algo rr
    lb_kind DR
    protocol TCP
    alpha

    real_server 9.82.225.247 22 {
        weight 1
        TCP_CHECK {
            connect_port 22 #open
            connect_timeout 15
            retry 5
            delay_before_retry 3
        }
    }
}
`
then we modify the port 22 to 23, which is closed. And then reload the keepalived service.
! Configuration File for keepalived
  
virtual_server 9.82.128.242 22 {
    delay_loop 6
    lb_algo rr
    lb_kind DR
    protocol TCP
    alpha

    real_server 9.82.225.247 22 {
        weight 1
        TCP_CHECK {
            connect_port 23 #closed
            connect_timeout 15
            retry 5
            delay_before_retry 3
        }
    }
}
`
Then I find the real_server is still on line.

**Comment by HW-lj** [comment]
Any progress？

**Comment by pqarmitage** [comment]
Commit 32968e5 resolves this issue. Strangely the comment at the relevant place in the code was correct, but the code didn't adhere to the comment.
