### ISSUE TITLE
in the configuration file,track_bfd ignores bfd_instance after it

### ISSUE THREAD

**Issue by Mint-M** [acassen/keepalived#1146]
keepalived was build from the lastest snapshot version

OS:Linux localhost.localdomain 4.20.4-200.fc29.x86_64 #1 SMP Wed Jan 23 16:11:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

keepalived -v

> Keepalived v2.0.13 (unknown)
> 
> Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>
> 
> Built with kernel headers for Linux 4.20.4
> Running on Linux 4.20.4-200.fc29.x86_64 #1 SMP Wed Jan 23 16:11:28 UTC 2019
> 
> configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --disable-snmp-reply-v3-for-v2 --with-init=systemd --enable-regex --enable-bfd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
> 
> Config options:  LIBIPTC LIBIPSET_DYNAMIC NFTABLES LVS REGEX VRRP VRRP_AUTH BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_VRRP SNMP_CHECKER EINTR_CHECK
> 
> System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK
> 

When bfd_instance is written after track_bfd,bfd_instance is ignored by track_bfd.

[root@localhost keepalived]# more keepalived.conf 
! Configuration File for keepalived

global_defs {
    router_id 4
}

vrrp_instance eth0 {
    state BACKUP
    interface eth0
    virtual_router_id 112
    priority 90
    advert_int 1
    virtual_ipaddress {
        192.168.108.91/24 dev eth0
    }
    track_bfd {
        eth0
    }
}

bfd_instance eth0 {
    neighbor_ip 192.168.108.3
    source_ip 192.168.108.4
}

[root@localhost keepalived]# keepalived -t
(Line 17) (eth0) track bfd eth0 not found, ignoring...
[root@localhost keepalived]# vi keepalived.conf 
[root@localhost keepalived]# more keepalived.conf 
! Configuration File for keepalived

global_defs {
    router_id 4
}

bfd_instance eth0 {
    neighbor_ip 192.168.108.3
    source_ip 192.168.108.4
}

vrrp_instance eth0 {
    state BACKUP
    interface eth0
    virtual_router_id 112
    priority 90
    advert_int 1
    virtual_ipaddress {
        192.168.108.91/24 dev eth0
    }
    track_bfd {
        eth0
    }
}

[root@localhost keepalived]# keepalived -t
[root@localhost keepalived]#

**Comment by pqarmitage** [comment]
This is expected behaviour; the script has to be declared before it can be referenced. Exactly the same applies for `vrrp_script`s, for example.
