### ISSUE TITLE
vrrp_sync_group and vrrp_instance backup states are not initialized when vrrp_sync_group is used

### ISSUE THREAD

**Issue by Mint-M** [acassen/keepalived#1155]
Environment:2 VMs run with the same keepalived version and OS.
192.168.108.3<--->192.168.108.4

Master node configuration:

> ! Configuration File for keepalived
> 
> global_defs {
>     router_id 4
> }
> 
> vrrp_instance eth0 {
>     state BACKUP
>     interface eth0
>     virtual_router_id 111
>     priority 100
>     advert_int 1
>     virtual_ipaddress {
>         192.168.108.90/24 dev eth0
>     }
> }

Backup node configuration1:

> ! Configuration File for keepalived
> 
> global_defs {
>     router_id 3
> }
> 
> vrrp_instance eth0 {
>     state BACKUP
>     interface eth0
>     virtual_router_id 111
>     priority 90
>     advert_int 1
>     virtual_ipaddress {
>         192.168.108.90/24 dev eth0
>     }
>     notify_master /etc/keepalived/master.sh root
>     notify_backup /etc/keepalived/backup.sh root
> }
> 

Backup node configuration2:

> ! Configuration File for keepalived
> 
> global_defs {
>     router_id 3
> }
> 
> vrrp_sync_group VG_1 {
>     group {
>         eth0
>     }
> }
> 
> vrrp_instance eth0 {
>     state BACKUP
>     interface eth0
>     virtual_router_id 111
>     priority 90
>     advert_int 1
>     virtual_ipaddress {
>         192.168.108.90/24 dev eth0
>     }
>     notify_master /etc/keepalived/master.sh root
>     notify_backup /etc/keepalived/backup.sh root
> }

Backup node configuration3:

> ! Configuration File for keepalived
> 
> global_defs {
>     router_id 3
> }
> 
> vrrp_sync_group VG_1 {
>     group {
>         eth0
>     }
>     notify_master /etc/keepalived/master.sh root
>     notify_backup /etc/keepalived/backup.sh root
> }
> 
> vrrp_instance eth0 {
>     state BACKUP
>     interface eth0
>     virtual_router_id 111
>     priority 90
>     advert_int 1
>     virtual_ipaddress {
>         192.168.108.90/24 dev eth0
>     }
> }
> 

Situation1:
The master node was always running. When keepalived the backup node started, it went into backup state. Only the first configuration made the notify_backup script to be excuted.
It seems that as long as vrrp_sync_group are introduced, the state of vrrp instances are not initialized although scripts are excuted when the state changes.

> 55:16 localhost Keepalived[2477]: Starting Keepalived v2.0.13 (unknown)
> 55:16 localhost Keepalived[2477]: Running on Linux 4.20.13-200.fc29.x86_64 #1 SMP Wed Feb 27 19:42:55 UTC 2019 (built for Linux 4.20.4)
> 55:16 localhost Keepalived[2477]: Command line: '/usr/sbin/keepalived' '-D'
> 55:16 localhost Keepalived[2477]: Opening file '/etc/keepalived/keepalived.conf'.
> 55:16 localhost Keepalived[2478]: Starting VRRP child process, pid=2479
> 55:16 localhost Keepalived_vrrp[2479]: Registering Kernel netlink reflector
> 55:16 localhost Keepalived_vrrp[2479]: Registering Kernel netlink command channel
> 55:16 localhost Keepalived_vrrp[2479]: Opening file '/etc/keepalived/keepalived.conf'.
> 55:16 localhost Keepalived_vrrp[2479]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
> 55:16 localhost Keepalived_vrrp[2479]: Sync group VG_1 has only 1 virtual router(s) - this probably isn't what you want
> 55:16 localhost Keepalived_vrrp[2479]: Assigned address 192.168.108.3 for interface eth0
> 55:16 localhost Keepalived_vrrp[2479]: Assigned address fe80::20c:29ff:fe58:bf52 for interface eth0
> 55:16 localhost Keepalived_vrrp[2479]: Registering gratuitous ARP shared channel
> 55:16 localhost Keepalived_vrrp[2479]: (eth0) removing VIPs.
> 55:16 localhost Keepalived_vrrp[2479]: (eth0) Entering BACKUP STATE (init)
> 55:16 localhost Keepalived_vrrp[2479]: VRRP sockpool: [ifindex(2), family(IPv4), proto(112), unicast(0), fd(12,15)]
> 

Situation2:
The master node was not running. When keepalived the backup node started, it went into master state. Notify_master script was excuted as normal.

related logs:

> 51:16 localhost Keepalived[1896]: Starting Keepalived v2.0.13 (unknown)
> 51:16 localhost Keepalived[1896]: Running on Linux 4.20.13-200.fc29.x86_64 #1 SMP Wed Feb 27 19:42:55 UTC 2019 (built for Linux 4.20.4)
> 51:16 localhost Keepalived[1896]: Command line: '/usr/sbin/keepalived' '-D'
> 51:16 localhost Keepalived[1896]: Opening file '/etc/keepalived/keepalived.conf'.
> 51:16 localhost Keepalived[1897]: Starting VRRP child process, pid=1898
> 51:16 localhost Keepalived_vrrp[1898]: Registering Kernel netlink reflector
> 51:16 localhost Keepalived_vrrp[1898]: Registering Kernel netlink command channel
> 51:16 localhost Keepalived_vrrp[1898]: Opening file '/etc/keepalived/keepalived.conf'.
> 51:16 localhost Keepalived_vrrp[1898]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
> 51:16 localhost Keepalived_vrrp[1898]: Sync group VG_1 has only 1 virtual router(s) - this probably isn't what you want
> 51:16 localhost Keepalived_vrrp[1898]: Assigned address 192.168.108.3 for interface eth0
> 51:16 localhost Keepalived_vrrp[1898]: Assigned address fe80::20c:29ff:fe58:bf52 for interface eth0
> 51:16 localhost Keepalived_vrrp[1898]: Registering gratuitous ARP shared channel
> 51:16 localhost Keepalived_vrrp[1898]: (eth0) removing VIPs.
> 51:16 localhost Keepalived_vrrp[1898]: (eth0) Entering BACKUP STATE (init)
> 51:16 localhost Keepalived_vrrp[1898]: VRRP sockpool: [ifindex(2), family(IPv4), proto(112), unicast(0), fd(12,15)]
> 51:20 localhost Keepalived_vrrp[1898]: (eth0) Receive advertisement timeout
> 51:20 localhost Keepalived_vrrp[1898]: (eth0) Entering MASTER STATE
> 51:20 localhost Keepalived_vrrp[1898]: (eth0) setting VIPs.
> 51:20 localhost Keepalived_vrrp[1898]: Sending gratuitous ARP on eth0 for 192.168.108.90
> 51:20 localhost Keepalived_vrrp[1898]: (eth0) Sending/queueing gratuitous ARPs on eth0 for 192.168.108.90
> 51:20 localhost Keepalived_vrrp[1898]: Sending gratuitous ARP on eth0 for 192.168.108.90
> 51:20 localhost Keepalived_vrrp[1898]: Sending gratuitous ARP on eth0 for 192.168.108.90
> 51:20 localhost Keepalived_vrrp[1898]: Sending gratuitous ARP on eth0 for 192.168.108.90
> 51:20 localhost Keepalived_vrrp[1898]: Sending gratuitous ARP on eth0 for 192.168.108.90
> 51:20 localhost Keepalived_vrrp[1898]: VRRP_Group(VG_1) Syncing instances to MASTER state
> 51:25 localhost Keepalived_vrrp[1898]: Sending gratuitous ARP on eth0 for 192.168.108.90
> 51:25 localhost Keepalived_vrrp[1898]: (eth0) Sending/queueing gratuitous ARPs on eth0 for 192.168.108.90
> 51:25 localhost Keepalived_vrrp[1898]: Sending gratuitous ARP on eth0 for 192.168.108.90
> 51:25 localhost Keepalived_vrrp[1898]: Sending gratuitous ARP on eth0 for 192.168.108.90
> 51:25 localhost Keepalived_vrrp[1898]: Sending gratuitous ARP on eth0 for 192.168.108.90
> 51:25 localhost Keepalived_vrrp[1898]: Sending gratuitous ARP on eth0 for 192.168.108.90

Is this behaviour intended?
In some cases, I use notify_backup to control some services or processes however, this behaviour made my design impossible.

OS:Linux localhost.localdomain 4.20.4-200.fc29.x86_64 #1 SMP Wed Jan 23 16:11:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

keepalived -v

> Keepalived v2.0.13 (unknown)
> 
> Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>
> 
> Built with kernel headers for Linux 4.20.4
> Running on Linux 4.20.4-200.fc29.x86_64 #1 SMP Wed Jan 23 16:11:28 UTC 2019
> 
> configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --disable-snmp-reply-v3-for-v2 --with-init=systemd --enable-regex --enable-bfd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
> 
> Config options:  LIBIPTC LIBIPSET_DYNAMIC NFTABLES LVS REGEX VRRP VRRP_AUTH BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_VRRP SNMP_CHECKER EINTR_CHECK
> 
> System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK
>

**Comment by pqarmitage** [comment]
As far as I can see, backup node configuration 2 and backup node configuration 3 are identical. Should there be another backup configuration?

I have tested the above, and also created another backup node configuration, where there are notify_backup and notify_master scripts configured against the sync group.

What I have observed is that if a sync group is configured, the initial running of the notify_backup script (both the vrrp_instance and sync_group scripts) are not run, but if no sync group is configured the initial notify_backup is run. The behaviour is not correct, and the notify_backup scripts should be run,  regardless of whether a sync group is configured.

I will produce a patch to resolve this, but I also need to investigate if other notifies (email, SNMP) are being missed too.

**Comment by Mint-M** [comment]
@pqarmitage 

> As far as I can see, backup node configuration 2 and backup node configuration 3 are identical. Should there be another backup configuration?
Yeah, I posted a wrong copy for configuration 3.

> I have tested the above, and also created another backup node configuration, where there are notify_backup and notify_master scripts configured against the sync group.
That's exactly what I wanted to post in configuration 3.

> I will produce a patch to resolve this, but I also need to investigate if other notifies (email, SNMP) are being missed too.
Thanks for your work.

**Comment by pqarmitage** [comment]
Commit 561c976 resolves this issue.

**Comment by Mint-M** [comment]
@pqarmitage 
It seems that notify_backup won't take effect if it was configured for sync_group after the patch.
Is it expected?

> ! Configuration File for keepalived
> 
> global_defs {
>     router_id 3
> }
> 
> vrrp_sync_group VG_1 {
>     group {
>         eth0
>     }
>     notify_master /etc/keepalived/master.sh
>     notify_backup /etc/keepalived/backup.sh
> }
> 
> vrrp_instance eth0 {
>     state BACKUP
>     interface eth0
>     virtual_router_id 111
>     priority 90
>     advert_int 1
>     virtual_ipaddress {
>         192.168.108.90/24 dev eth0
>     }
> }
>

**Comment by pqarmitage** [comment]
A sync group notify_backup script should run at startup.

**Comment by pqarmitage** [comment]
Commit 240dd5d should resolve sending backup notifies on a sync group at startup.
