### ISSUE TITLE
keepalived-2.0.14 - RPM building on CentOs 7

### ISSUE THREAD

**Issue by BBQigniter** [acassen/keepalived#1176]
Just an info for Centos 7 users who want to build the RPM package on their own.

Building did work as expected but installing threw a dependency error for `iptables-libs`. I didn't find any package with that name for the most recent CentOS 7 version, so I edited the `keepalived.spec` file after running ./configure and replaced `Requires: iptables-libs` with `Requires: iptables-devel`. After rebuilding the RPM again installation worked and currently we haven't seen any issues yet.

**Comment by pqarmitage** [comment]
For CentOS up to version 7, `Requires: iptables-libs` should be replaced with `Requires: iptables`, or better still, unless you are using `--enable-libiptc-dynamic` or `--enable-libxtables-dynamic`, just delete the line.

Commit 96cf5aa resolves the problem.
