### ISSUE TITLE
Health check fd leak

### ISSUE THREAD

**Issue by HW-lj** [acassen/keepalived#1177]
We just config health checker and reload it again and again. then we will see the leakage of health check in /proc/[keepalived.pid]/fd @pqarmitage

**Comment by pqarmitage** [comment]
@HW-lj What configuration are you using?

**Comment by pqarmitage** [comment]
@HW-lj Can you please provide a copy of the output of `keepalived -v`. Can you also, as well as the config, provide details of how you are reloading keepalived (if you are using a script it would be helpful to have a copy of that).

Does it always leak the same number of fds every reload?

The output of `ls -l /proc/[keepalived.pid/fd` after several fds have leaked would be helpful.

**Comment by pqarmitage** [comment]
This issue appears to be sockets used for TCP_CHECK checks that are still open when the configuration is reloaded. The same will apply to HTTP_GET, SSL_GET, DNS_CHECK and SMTP_CHECK checkers.

**Comment by HW-lj** [comment]
> This issue appears to be sockets used for TCP_CHECK checks that are still open when the configuration is reloaded. The same will apply to HTTP_GET, SSL_GET, DNS_CHECK and SMTP_CHECK checkers.

Wow, you are so brilliant.It's my fault to forget the standard process of creating issue. Indeed, I use the version of 2.0.13, and I got off work last night.Except for the health checks, I I suspect it seems also exist in vrrp module, so could you have a look at it whenever you are available.

**Comment by pqarmitage** [comment]
smtp_alerts also have the potential to cause this problem. At the moment I can't see any other area that could experience this problem.

**Comment by pqarmitage** [comment]
Commit 7dfad19 should resolve this problem. Threads waiting on a file descriptor now indicate to the scheduler that if the thread is destroyed, the file descriptor should be closed.

**Comment by HW-lj** [comment]
The solution is so beautiful, it will take me some days to test it : )
