### ISSUE TITLE
fails to compile 2.0.14 on alpine 3.9.2

### ISSUE THREAD

**Issue by njfanxun** [acassen/keepalived#1201]
when i compile from  http://keepalived.org/software/keepalived-2.0.14.tar.gz
error info is:
make[1]: Entering directory '/tmp/keepalived-sources/lib'
make  all-am
make[2]: Entering directory '/tmp/keepalived-sources/lib'
  CC       memory.o
  CC       utils.o
  CC       notify.o
  CC       timer.o
  CC       scheduler.o
In file included from scheduler.c:59:
warnings.h:54:18: warning: "__GNUC_PREREQ" is not defined, evaluates to 0 [-Wundef]
 #if __GNUC__ && !__GNUC_PREREQ(8,0) && defined _HAVE_DIAGNOSTIC_PUSH_POP_PRAGMAS_
                  ^~~~~~~~~~~~~
warnings.h:54:31: error: missing binary operator before token "("
 #if __GNUC__ && !__GNUC_PREREQ(8,0) && defined _HAVE_DIAGNOSTIC_PUSH_POP_PRAGMAS_
                               ^
warnings.h:68:18: warning: "__GNUC_PREREQ" is not defined, evaluates to 0 [-Wundef]
 #if __GNUC__ && !__GNUC_PREREQ(8,0) && defined _HAVE_DIAGNOSTIC_PUSH_POP_PRAGMAS_
                  ^~~~~~~~~~~~~
warnings.h:68:31: error: missing binary operator before token "("
 #if __GNUC__ && !__GNUC_PREREQ(8,0) && defined _HAVE_DIAGNOSTIC_PUSH_POP_PRAGMAS_
                               ^
make[2]: Leaving directory '/tmp/keepalived-sources/lib'
make[2]: *** [Makefile:412: scheduler.o] Error 1
make[1]: *** [Makefile:321: all] Error 2
make[1]: Leaving directory '/tmp/keepalived-sources/lib'
make: *** [Makefile:429: all-recursive] Error 1

**Comment by pqarmitage** [comment]
Commit 5d1b119 resolves this issue.
