### ISSUE TITLE
Sending unsolicited Neighbour Advert on eth0 for 2a03:2870:15::588d:0:1

### ISSUE THREAD

**Issue by thojanssens** [acassen/keepalived#1204]
I replaced all IPv4 of my configuration file by IPv6 for a quick IPv6 test:

`unicast_src_ip`, `unicast_peer` and `virtual_ipaddress` contain only IPv6 address, no IPv4.

```
        interface eth0
        unicast_src_ip 2a02:2870:17:0:25a:4aff:de85:3568
        unicast_peer {
                2a02:2870:15:0:31a:4aff:ce45:4516
        }
        virtual_ipaddress {
                2a03:2870:15::588d:0:1/64 dev eth0
        }
```

I have the following error message from Keepalived:

> Keepalived_vrrp[4820]: Sending unsolicited Neighbour Advert on eth0 for 2a03:2870:15::588d:0:1

I might need to configure something for this IPv6 declared as virtual to work. My VPS provider allowed me to get a new IPv6 address, but then not sure what to do for Keepalived to be able to manage that IPv6 address.

What do these logs mean? If I understand these logs, maybe I can understand the problem better.

NB: fyi I don't understand what a virtual IP technically *really* is and how it is able to be bound to the interface of one server, then the other. I guess I must do something with that IPv6 address, configure it as a virtual IP, but no idea how.

**Comment by acassen** [comment]
this is not an issue this is for mailing list... Github issue is for bugs.
