### ISSUE TITLE
Unknown VRID(X) received on interface(eth0). ignoring...

### ISSUE THREAD

**Issue by iliesh** [acassen/keepalived#1207]
I have a setup, where I have multiple keepalived instances with different VRID. After upgrade to the latest version (Keepalived v2.0.15 (04/04,2019), git commit v2.0.14-53-g9de2817c+) I have a lot of warnings in the message log file that Unknown VRID received on an interface, is there a way to suppress this message to not flood log file? Is that a problem that I'm using a different VRID on the same mcast group or its recommended to use a separate mcast group for each VRID?
Thank you.

**Comment by acassen** [comment]
Hello, This log appear because you are receiving VRRP adverts on eth0 and you dont have configured vrrp_instance to similar to your remote  host. I mean if on RouterA you avec configured on eth0 vrrp_instance with, lets says, VRID=50 then on RouterB if you dont have configured corresponding VRRP_instance then this log will pop-up to inform you that something is wrong.

Would you provide your conf file ? (obfusced IP are ok).

**Comment by acassen** [comment]
addendum: this extension appeared in 21e6f5f

**Comment by acassen** [comment]
if you are running multiple Keepalived instances on the same interface but with different VRID in each conf file... then this will appear. Maybe we can turn this logging feature as conf keyword and make it disabled by default. But why are you running multiple keepalived instance on the same NIC ?

**Comment by pqarmitage** [comment]
Would it be sensible to only log unknown duplicate VRID if the LOG_DETAIL_BIT is set? It is quite possible there could be two independent sets of routers running VRRP on the same sub-network, inevitably using different VRIDs.

An alternative would be to add a configuration keyword `ignore_unknown_vrid`.

**Comment by pqarmitage** [comment]
Oops - I didn't see @acassen 's last comment before I responded.

**Comment by acassen** [comment]
@pqarmitage : sure but then most of the time vlan are in use (so <> NIC). Sharing the same NIC with multiple Keepalived instances, I dont see the use case to be honnest. But I really think we must make this disable by default. But having this pop-up might display a configuration or network design that could be optimized? dunno let me know.

**Comment by pqarmitage** [comment]
If there is a DMZ, with routerA and routerB connecting towards the internet, using VRID1, and routerY and routerZ connecting towards an internal network, using VRID2. They would need to be on the same vlan, and so the routers would see all VRRP adverts, even though routerA and routerB were only configured for VRID1 etc.

**Comment by acassen** [comment]
agreed. We need to make it disabled by default and tweak by configuration keywords.

**Comment by pqarmitage** [comment]
I'm happy to work up a patch to do that.

**Comment by iliesh** [comment]
@acassen ,

The config is pretty simple:

```
global_defs {
vrrp_version 3
script_user root
enable_script_security
enable_snmp_vrrp
enable_snmp_checker
enable_snmp_rfc
enable_snmp_rfcv3
enable_traps
    notification_email {
        admin@company.com
   }
   notification_email_from "[Keepalive] Service <support@company.com>"
   smtp_server 127.0.0.1
   smtp_connect_timeout 30
vrrp_mcast_group4 224.0.0.18
vrrp_mcast_group6 ff02::12
}

vrrp_instance WAN {
    state MASTER
    interface eth0
    virtual_router_id 21
    priority 100
    smtp_alert
    advert_int 1

    track_interface {
     eth0
     eth1
    }

    virtual_ipaddress {
        192.168.50.11/24 brd 192.168.50.255 dev eth0
        172.16.180.13/24 brd 172.16.180.255 dev eth1
    }

    notify_master "/usr/scripts/keepalived_notify.sh MASTER WAN"
    notify_backup "/usr/scripts/keepalived_notify.sh BACKUP WAN"
    notify_fault "/usr/scripts/keepalived_notify.sh FAULT WAN"
    notify_stop "/usr/scripts/keepalived_notify.sh STOP WAN"
}
```
This is for one server which is running one service, lets suppose an MySQL service, the other server running the same service have the same VRID (21), but with different priority (90). Everything is working fine, the failover is taking place on the second server in case the first server goes down. Then, in the same network - i have another service (let's suppose an web-server), running on another 2 servers (main and backup) with a different VRID (22), which also works perfectly, but because they are on the same network (192.168.50.0/24) and the same mcast grup: (224.0.0.18), i'm receiving the the vrrp packets with VRID from the first group (20) too, and that's why i have this warnings in the log file. The setup is working fine, i'm happy with it, except this warnings, so i just wonder how can i avoid them, or if there is a problem by receiving an unknown VRID can somehow disturb the keepalived service itself.

**Comment by pqarmitage** [comment]
Commit e95eb11 resolves this issue, and will only log unknown VRIDs if `log_unknown_vrids` is configured in the `global_defs` section of the configuration.

**Comment by acassen** [comment]
@iliesh ok... this is just a log. Before we didnt have this log and VRRP was silently ignoring any adverts falling into that case. We add this in order to have a pop-up when unsolicited VRRP advert are received. I aggreed we could have been less authoritative :)

@pqarmitage you are faster than me

I think we can close the issue. It will be part of next release in the mean time if this is somethings annoying you get code from master branch where this patch is now in place.
