### ISSUE TITLE
Notify on priority change

### ISSUE THREAD

**Issue by damiankaczkowski** [acassen/keepalived#1213]
Hi.

Could you please implement option to allow sending notifies on priority change even when state does not change? From what I see notifies are only send on state transition. I would like to control def gateway on multi wan system via keepalived. In my case state will change only after all wans are down.

Greets.

**Comment by pqarmitage** [comment]
Commit 1470d6b adds notification of vrrp instance priority changes via the notify FIFOs.

The reason for only implementing the notification via FIFOs, and not via scripts, is that the order of execution of scripts, if two priority changes occur in quick succession, is indeterminate, and therefore the last script to execute may not be the one for the latest priority change. The only guaranteed way to receive notifications in the correct order is to use notify FIFOs.

The keepalived.conf(5) man page describes how the use of FIFOs is configured. keepalived can also be configured to execute a configured program/script to read the FIFOs. A sample script for processing the notify FIFOs is in the source tree at `doc/samples/sample_notify_fifo.sh`.

If it is not clear how to use notify FIFOs, please post any issues/queries in this issue, and I will attempt to answer them.
