### ISSUE TITLE
Keepalived graceful takeover.

### ISSUE THREAD

**Issue by tamutamu** [acassen/keepalived#1225]
I am trying to load simulation, i have the below enviroment,
  - AWS
  - Keepalived Server A(master),  B(backup)  -  HAProxy × 3  -   WebAPP × 6
  -  lvs_method TUN
  - load simulator: gatling

  /etc/keepavlied/keepavlied.conf
  ```
   virtual_server 192.168.100.140 80 {
      script "/usr/bin/test -e /var/run/keepalived.lvs_healthy"
      lvs_sched rr
      lvs_method TUN
      protocol TCP 
  ```

After it simulate a load test of HTTP request(async) 500TPS by gatling(maxRetry=0) for 10min , execute command `systemclt stop keepavlied` on A(master).

As a result, it changes master node, A to B.

But it raises two or three of j.i.IOException which is Connection reset by peer".

Why it occurs connection reset even though tcp retry ?

How do it take over graceful ?

**Comment by pqarmitage** [comment]
The reason for the connection reset is that node B doesn't have any knowledge of the TCP connection established through node A, and so node B is not able to forward the traffic for the connection established through A (for example, if you have multiple real servers, which one was the connection forwarded to).

In order for the master node to update the backup node with the necessary information of established connections, you need to configure the connection synchronization daemon. See `lvs_sync_daemon` in keepalived.conf(5) man page, and the entry under `--start-daemon` on the ipvsadm(8) man page.
