### ISSUE TITLE
Keepalived graceful reaload config 

### ISSUE THREAD

**Issue by tamutamu** [acassen/keepalived#1228]
I am trying to load simulation, i have the below enviroment,
  - AWS
  - Keepalived Server A(master),  B(backup)  -  HAProxy × 3(A, B, C)  -   WebAPP × 6
  -  lvs_method TUN
  - load simulator: gatling

  /etc/keepavlied/keepavlied.conf
 ```
    virtual_server 192.168.100.140 80 {
      script "/usr/bin/test -e /var/run/keepalived.lvs_healthy"
      lvs_sched rr
      lvs_method TUN
      protocol TCP


  real_server 10.1.0.101 80 {  // HAProxy A
    ...
  }

  real_server 10.2.0.102 80 {  // HAProxy B
    ...
  }

  real_server 10.3.0.103 80 {  // HAProxy C
    ...
  }
  ```

It simulate a load test of HTTP request(async) 500TPS by gatling(maxRetry=0) for 10min.
In this situation, I want to stop transport request to Haproxy A from keepalived at runtime,  and further no connection lost.

I actually try, I update `/etc/keepalived/keepalived.conf`
```
  //real_server 10.1.0.101 80 {  // HAProxy A
  //  ...
  //}

  real_server 10.2.0.102 80 {  // HAProxy B
    ...
  }

  real_server 10.3.0.103 80 {  // HAProxy C
    ...
  }
  ```

execute command `kill -HUP $(cat /var/run/keepalived.pid)`.

As a result, it reload new configuration.

But it raises some of Request timeout".

Is there a way not to raise Request timeout when remove transport server(real_server) at runtime?

Does 'lvs_sync_daemon' have any effect ?

**Comment by pqarmitage** [comment]
If you remove the virtual server from the configuration, then the virtual server will be removed from the IPVS configuration and any existing connections will be lost.

If you want to be able to remove a virtual server without existing connections being lost, then it needs to have its weight set to 0 (which cannot be directly configured). The way to do it is to configure a checker against the real server, and add `inhibit_on_failure` in the virtual server or real server configuration block. If after loading the new config you cause the checker to fail, then the real server won't be removed, but if will be reconfigured to have weight 0, meaning that existing connections will persist but no new connections will be established to that real server.

A check script I use for testing is:
```
#!/bin/bash

if [[ -n $1 ]]; then
	NAME=$1
else
	NAME=${0##*/}
	NAME=${NAME%.sh}
fi

echo -n "$(date +"%a %b %e %X %Y")": \[$PPID:$$\] >>/tmp/$NAME.log
for i in $(seq 1 $#); do
	echo -n " '$1'" >>/tmp/$NAME.log
	shift
done
echo >>/tmp/$NAME.log

[[ ! -f /tmp/$NAME.ret ]] && echo 0 >/tmp/$NAME.ret

RET=$(cat /tmp/$NAME.ret)

if [[ $RET -ge 3 && $RET -le 15 ]]; then
	 echo $((RET - 1)) >/tmp/$NAME.ret
	 sleep $RET
fi

exit $RET
```
Save the above as /etc/keepalived/check_script.sh and make it executable.

In your keepalived configuration file in the `real_server 10.1.0.101 80` block add:
```
inhibit_on_failure
MISC_CHECK {
       script "/etc/keepalived/check_script.sh"
       delay_loop 10                      # check every 10 seconds
}
```

To cause the checker to fail, and the real server to be reconfigured to have weight 0, execute `echo  1 >/tmp/check_script.ret`

Once all connections to that real server have been closed, the configuration can be safely updated to remove the real server.

`lvs_sync_daemon` is not related to this.
