### ISSUE TITLE
Keepalived not present in any yum repository

### ISSUE THREAD

**Issue by rahulsinghidrive** [acassen/keepalived#1241]
Red Hat has not included the keepalived package in the base repository. The version available is 1.3.5, but latest version of keepalived is 2.0.15. Is there any reason why the new versions are not updated anymore in the yum repositories?

**Comment by pqarmitage** [comment]
The version of keepalived included in RHEL 8 beta is v2.0.7. From recollection, the version included in RHEL 7 is v1.3.5.

Red Hat have their own policies regarding version upgrades, based on RHEL remaining a stable environment. If you want Red Hat to update a version you would need to file a bug on their Bugzilla system. Alternatively you could download the source RPM from Red Hat, update the spec file and the source tarball to v2.0.15 and build an rpm file yourself.
