### ISSUE TITLE
Build failure when CFLAGS=-Os

### ISSUE THREAD

**Issue by nylon7** [acassen/keepalived#1258]
**Describe the bug**
make[2]: Entering directory '/home/users3/nylon7/keepalived-2.0.16/keepalived'
  CCLD     keepalived
vrrp/libvrrp.a(vrrp_ip_rule_route_parser.o): In function `get_time_rtt':
/home/users3/nylon7/keepalived-2.0.16/keepalived/vrrp/vrrp_ip_rule_route_parser.c:150: undefined reference to `__fpclas
sify'
../lib/liblib.a(parser.o): In function `read_double_func':
/home/users3/nylon7/keepalived-2.0.16/lib/parser.c:294: undefined reference to `__fpclassify'
collect2: error: ld returned 1 exit status
Makefile:471: recipe for target 'keepalived' failed

**To Reproduce**
`wget http://www.keepalived.org/software/keepalived-2.0.16.tar.gz`
`./configure`
`export CFLAGS=-Os`
`make`

**Distro (please complete the following information):**
 - Name : Ubuntu
 - Version : 18.04
 - Architecture : x86_64
 - GCC : 7.3.0

**Comment by acassen** [comment]
looks like -lm not in extra libs when it should be

**Comment by pqarmitage** [comment]
Line 782 et cf of configure.ac looks as though it should add -lm if fpclassify() needs it.

**Comment by pqarmitage** [comment]
Is this an issue of running configure in a different environment to the environment when make is run?

If the sequence were
```
export CFLAGS=-Os
./configure
make
```
does it work?

**Comment by nylon7** [comment]
hello @acassen 
* about   ./configure output 
> nylon7@atccpl06:~/keepalived-2.0.16$ export CFLAGS=-Os
nylon7@atccpl06:~/keepalived-2.0.16$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... ranlib
checking for grep that handles long lines and -e... /bin/grep
checking whether ln -s works... yes
checking for a sed that does not truncate output... /bin/sed
checking for strip... strip
checking for ldd... ldd
checking for ar... ar
checking the archiver (ar) interface... ar
checking diagnostic pragmas in functions... yes
checking diagnostic push/pop pragmas... yes
checking for -Wall... yes
checking for -Wextra... yes
checking for -Wunused... yes
checking for -Wstrict-prototypes... yes
checking for -Wabsolute-value... no
checking for -Waddress-of-packed-member... no
checking for -Walloca... yes
checking for -Walloc-zero... yes
checking for -Warray-bounds=2... yes
checking for -Wattribute-alias... no
checking for -Wbad-function-cast... yes
checking for -Wcast-qual... yes
checking for -Wchkp... yes
checking for -Wdate-time... yes
checking for -Wdisabled-optimization... yes
checking for -Wduplicated-branches... yes
checking for -Wduplicated-cond... yes
checking for -Wfloat-conversion... yes
checking for -Wfloat-equal... yes
checking for -Wformat-overflow... yes
checking for -Wformat-truncation... yes
checking for -Wimplicit-fallthrough=3... yes
checking for -Winit-self... yes
checking for -Winline... yes
checking for -Wjump-misses-init... yes
checking for -Wlogical-op... yes
checking for -Wmissing-declarations... yes
checking for -Wmissing-prototypes... yes
checking for -Wnested-externs... yes
checking for -Wnormalized... yes
checking for -Wnull-dereference... yes
checking for -Wold-style-definition... yes
checking for -Woverlength-strings... yes
checking for -Wpointer-arith... yes
checking for -Wredundant-decls... yes
checking for -Wshadow... yes
checking for -Wshift-overflow=2... yes
checking for -Wstack-protector... yes
checking for -Wstrict-overflow=4... yes
checking for -Wstrict-prototypes... yes
checking for -Wstringop-overflow=2... yes
checking for -Wsuggest-attribute=cold... no
checking for -Wsuggest-attribute=const... yes
checking for -Wsuggest-attribute=format... yes
checking for -Wsuggest-attribute=malloc... no
checking for -Wsuggest-attribute=noreturn... yes
checking for -Wsuggest-attribute=pure... yes
checking for -Wtrampolines... yes
checking for -Wundef... yes
checking for -Wuninitialized... yes
checking for -Wunsuffixed-float-constants... yes
checking for -Wunused-const-variable=2... yes
checking for -Wunused-macros... yes
checking for -Wvariadic-macros... yes
checking for PIE support... yes
checking for -Wformat -Werror=format-security support... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 support... yes
checking for -fexceptions support... yes
checking for -fstack-protector-strong support... yes
checking for --param=ssp-buffer-size=4 support... yes
checking for -grecord-gcc-switches support... yes
checking for -Wl,-z,relro support... yes
checking for -Wl,-z,now support... yes
checking for -O2 support... yes
checking for unaligned memory access... yes
checking for clock_gettime() requires -lrt... no
checking whether fpclassify() requires -lm... no
checking how to run the C preprocessor... gcc -E
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/prctl.h usability... yes
checking sys/prctl.h presence... yes
checking for sys/prctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking asm/types.h usability... yes
checking asm/types.h presence... yes
checking for asm/types.h... yes
checking linux/ethtool.h usability... yes
checking linux/ethtool.h presence... yes
checking for linux/ethtool.h... yes
checking linux/icmpv6.h usability... yes
checking linux/icmpv6.h presence... yes
checking for linux/icmpv6.h... yes
checking linux/if_ether.h usability... yes
checking linux/if_ether.h presence... yes
checking for linux/if_ether.h... yes
checking linux/if_packet.h usability... yes
checking linux/if_packet.h presence... yes
checking for linux/if_packet.h... yes
checking linux/ip.h usability... yes
checking linux/ip.h presence... yes
checking for linux/ip.h... yes
checking linux/sockios.h usability... yes
checking linux/sockios.h presence... yes
checking for linux/sockios.h... yes
checking linux/types.h usability... yes
checking linux/types.h presence... yes
checking for linux/types.h... yes
checking for linux/fib_rules.h... yes
checking for linux/if_addr.h... yes
checking for linux/if_link.h... yes
checking for linux/if_arp.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for int64_t... yes
checking for pid_t... yes
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for an ANSI C-conforming const... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for dup2... yes
checking for getcwd... yes
checking for gettimeofday... yes
checking for memmove... yes
checking for memset... yes
checking for select... yes
checking for setenv... yes
checking for socket... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strpbrk... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
checking for uname... yes
checking for pipe2... yes
checking for signalfd... yes
checking for inotify_init1... yes
checking for vsyslog... yes
checking for epoll_create1... yes
checking whether ETHERTYPE_IPV6 is declared... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking openssl/err.h usability... yes
checking openssl/err.h presence... yes
checking for openssl/err.h... yes
checking openssl/md5.h usability... yes
checking openssl/md5.h presence... yes
checking for openssl/md5.h... yes
checking for MD5_Init in -lcrypto... yes
checking for SSL_CTX_new in -lssl... yes
checking SSL_set_tlsext_host_name() - may be a definition... yes
checking for SSL_CTX_set_verify_depth... yes
checking for SSL_set0_rbio... yes
checking for OPENSSL_init_crypto... yes
checking for TLS_method... yes
checking whether IPV4_DEVCONF_ARP_IGNORE is declared... yes
checking whether IPV4_DEVCONF_ACCEPT_LOCAL is declared... yes
checking whether IPV4_DEVCONF_RP_FILTER is declared... yes
checking whether IPV4_DEVCONF_ARPFILTER is declared... yes
checking for linux/rtnetlink.h... yes
checking whether IPV6_RECVHOPLIMIT is declared... yes
checking whether IPV6_RECVPKTINFO is declared... yes
checking for nl_socket_modify_cb in -lnl... no
configure: WARNING: keepalived will be built without libnl support.
checking for magic_open in -lmagic... no
checking whether RTA_ENCAP is declared... yes
checking whether RTA_EXPIRES is declared... yes
checking whether RTA_NEWDST is declared... yes
checking whether RTA_PREF is declared... yes
checking whether FRA_SUPPRESS_PREFIXLEN is declared... yes
checking whether FRA_SUPPRESS_IFGROUP is declared... yes
checking whether FRA_TUN_ID is declared... yes
checking whether RTAX_CC_ALGO is declared... yes
checking whether RTAX_QUICKACK is declared... yes
checking whether RTEXT_FILTER_SKIP_STATS is declared... yes
checking whether FRA_L3MDEV is declared... yes
checking whether FRA_UID_RANGE is declared... yes
checking whether RTAX_FASTOPEN_NO_COOKIE is declared... yes
checking whether RTA_VIA is declared... yes
checking whether FRA_OIFNAME is declared... yes
checking whether FRA_PROTOCOL is declared... no
checking whether FRA_IP_PROTO is declared... no
checking whether FRA_SPORT_RANGE is declared... no
checking whether FRA_DPORT_RANGE is declared... no
checking whether RTA_TTL_PROPAGATE is declared... yes
checking whether IFA_FLAGS is declared... yes
checking whether IP_MULTICAST_ALL is declared... yes
checking whether LWTUNNEL_ENCAP_MPLS is declared... yes
checking whether LWTUNNEL_ENCAP_ILA is declared... yes
checking linux/netfilter/x_tables.h usability... yes
checking linux/netfilter/x_tables.h presence... yes
checking for linux/netfilter/x_tables.h... yes
checking xtables.h usability... no
checking xtables.h presence... no
checking for xtables.h... no
checking linux/netfilter/nf_tables.h usability... yes
checking linux/netfilter/nf_tables.h presence... yes
checking for linux/netfilter/nf_tables.h... yes
configure: WARNING: libnftnl missing
configure: WARNING: libmnl missing
checking for linux/if.h and net/if.h namespace collision... yes
checking for linux/if_ether.h then netinet/if_ether.h namespace collision... no
checking for libiptc/libiptc.h linux/if.h and net/if.h namespace collision... yes
checking linux/ip_vs.h usability... yes
checking linux/ip_vs.h presence... yes
checking for linux/ip_vs.h... yes
checking whether IP_VS_SVC_F_ONEPACKET is declared... yes
checking whether IPVS_DEST_ATTR_ADDR_FAMILY is declared... yes
checking whether IPVS_DAEMON_ATTR_SYNC_MAXLEN is declared... yes
checking whether IPVS_DAEMON_ATTR_MCAST_GROUP is declared... yes
checking whether IPVS_DAEMON_ATTR_MCAST_GROUP6 is declared... yes
checking whether IPVS_DAEMON_ATTR_MCAST_PORT is declared... yes
checking whether IPVS_DAEMON_ATTR_MCAST_TTL is declared... yes
checking whether IPVS_SVC_ATTR_STATS64 is declared... yes
checking whether IPVS_DEST_ATTR_STATS64 is declared... yes
checking whether IFLA_MACVLAN_MODE is declared... yes
checking whether MACVLAN_MODE_PRIVATE is declared... yes
checking whether PROC_EVENT_SID is declared... yes
checking whether PROC_EVENT_PTRACE is declared... yes
checking whether PROC_EVENT_COMM is declared... yes
checking whether PROC_EVENT_COREDUMP is declared... yes
checking whether SOCK_NONBLOCK is declared... yes
checking whether SOCK_CLOEXEC is declared... yes
checking whether IPVS_SVC_ATTR_PE_NAME is declared... yes
checking whether O_PATH is declared... yes
checking whether GLOB_BRACE is declared... yes
checking whether FRA_SRC is declared... yes
checking whether IFLA_INET6_ADDR_GEN_MODE is declared... yes
checking whether IFLA_VRF_MAX is declared... yes
checking whether SO_MARK is declared... yes
checking whether CLONE_NEWNET is declared... yes
checking for setns... yes
checking whether SCHED_RR is declared... yes
checking whether RLIMIT_RTTIME is declared... yes
checking whether SCHED_RESET_ON_FORK is declared... yes
checking for sphinx-build... Yes
checking for rpm... Yes
checking for rpmbuild... Yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating keepalived/Makefile
config.status: creating lib/Makefile
config.status: creating keepalived/core/Makefile
config.status: creating keepalived.spec
config.status: creating genhash/Makefile
config.status: creating keepalived/check/Makefile
config.status: creating keepalived/vrrp/Makefile
config.status: creating keepalived/bfd/Makefile
config.status: creating doc/Makefile
config.status: creating bin_install/Makefile
config.status: creating keepalived/dbus/Makefile
config.status: creating keepalived/etc/Makefile
config.status: creating keepalived/etc/init/Makefile
config.status: creating keepalived/etc/init.d/Makefile
config.status: creating doc/man/man8/Makefile
config.status: creating lib/config.h
config.status: creating lib/config_warnings.h
config.status: executing depfiles commands
Keepalived configuration
Keepalived version       : 2.0.16
Compiler                 : gcc
Preprocessor flags       :
Compiler flags           : -g -D_GNU_SOURCE -Wall -Wextra -Wunused -Wstrict-prototypes -Walloca -Walloc-zero -Warray-bounds=2 -Wbad-function-cast -Wcast-qual -Wchkp -Wdate-time -Wdisabled-optimization -Wduplicated-branches -Wduplicated-cond -Wfloat-conversion -Wfloat-equal -Wformat-overflow -Wformat-truncation -Wimplicit-fallthrough=3 -Winit-self -Winline -Wjump-misses-init -Wlogical-op -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wnormalized -Wnull-dereference -Wold-style-definition -Woverlength-strings -Wpointer-arith -Wredundant-decls -Wshadow -Wshift-overflow=2 -Wstack-protector -Wstrict-overflow=4 -Wstrict-prototypes -Wstringop-overflow=2 -Wsuggest-attribute=const -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wsuggest-attribute=pure -Wtrampolines -Wundef -Wuninitialized -Wunsuffixed-float-constants -Wunused-const-variable=2 -Wunused-macros -Wvariadic-macros -fPIE -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -O2
Linker flags             :  -pie
Extra Lib                :  -lcrypto  -lssl
Use IPVS Framework       : Yes
IPVS use libnl           : No
IPVS syncd attributes    : Yes
IPVS 64 bit stats        : Yes
HTTP_GET regex support   : No
fwmark socket support    : Yes
Use VRRP Framework       : Yes
Use VRRP VMAC            : Yes
Use VRRP authentication  : Yes
With ip rules/routes     : Yes
With track_process       : Yes
With linkbeat            : Yes
Use BFD Framework        : No
SNMP vrrp support        : No
SNMP checker support     : No
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
DBUS support             : No
SHA1 support             : No
Use JSON output          : No
libnl version            : None
Use IPv4 devconf         : Yes
Use iptables             : Yes
Use libiptc              : No
Use libipset             : No
Use nftables             : No
init type                : systemd
Strict config checks     : No
Build genhash            : Yes
Build documentation      : Yes
 WARNING - this build will not support IPVS with IPv6. Please install libnl/libnl-3 dev libraries to support IPv6 with IPVS.

@pqarmitage 

The same result

a part of config.log

> configure:6258: checking for clock_gettime() requires -lrt
> configure:6273: gcc -o conftest -Os -D_GNU_SOURCE    -Wl,-z,relro -Wl,-z,now conftest.c  >&5
> configure:6273: $? = 0
> configure:6274: result: no
> configure:6311: checking whether fpclassify() requires -lm
> configure:6326: gcc -o conftest     conftest.c  >&5
> configure:6326: $? = 0
> configure:6327: result: no
> configure:6346: checking how to run the C preprocessor
> configure:6377: gcc -E   conftest.c
> configure:6377: $? = 0
> configure:6391: gcc -E   conftest.c
> conftest.c:70:10: fatal error: ac_nonexistent.h: No such file or directory
>  #include <ac_nonexistent.h>
>           ^~~~~~~~~~~~~~~~~~
> compilation terminated.

**Comment by acassen** [comment]
and with the following sequence :
./build_setup
export CFLAGS=-Os
./configure
make

**Comment by nylon7** [comment]
@acassen 

I follow this sequence, but the same result

**Comment by pqarmitage** [comment]
I have discovered the following:

cat fpclassify.c
```
  # include <math.h>
  int main(int argc, char **argv)
  {
    double zero = 0.0;
    if (fpclassify(zero) == FP_ZERO)
      return 0;
    return 1;
  }
```
`gcc` **-O2** `-o fpclassify fpclassify.c`                     # compiles successfully

`gcc` **-Os** `-o fpclassify fpclassify.c`
>/tmp/ccaDJvIA.o: In function `main':
fpclassify.c:(.text.startup+0x8): undefined reference to `__fpclassify'
collect2: error: ld returned 1 exit status

I get the same results with gcc v7.3.1, v7.4.0, v9.0.1 and v9.1.1.

I do not understand why changing from -O2 to -Os should change whether libm is included in the default libs; the gcc documentation says
```
-Os

    Optimize for size. -Os enables all -O2 optimizations except those that often increase code size:

    -falign-functions  -falign-jumps 
    -falign-labels  -falign-loops 
    -fprefetch-loop-arrays  -freorder-blocks-algorithm=stc

    It also enables -finline-functions, causes the compiler to tune for code size rather than execution speed, and performs further optimizations designed to reduce code size.
```
so this doesn't suggest any different default libraries. Could this be a gcc bug?

So I think we need to make sure that the CFLAGS setting in the environment when configure is run is honoured throughout the run of configure. A quick test shows that that works, so I will update configure.ac accordingly. However, it will be necessary to run `configure` and `make` with consistent settings of CFLAGS, so the original example of `./configure; export CFLAGS=-Os; make` would still fail, but `export CFLAGS=-Os; ./configure; make` will work.

I wonder if we can issue a warning at make time if the settings of CFLAGS, LDFLAGS and LDLIBS are not consistent with the settings when configure was run?

**Comment by acassen** [comment]
@nylon7 If size of produced binary is the target here then you will have better saving than -Os by disabling components you just dont need while running configure

**Comment by tclin914** [comment]
It looks like a lack of "-lm" in compilation.
```
$ gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 207 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
$ cat fpclassify.c
# include <math.h> 
int main(int argc, char **argv)
{ 
  double zero = 0.0;
  if (fpclassify(zero) == FP_ZERO)
    return 0;
  return 1;
}
```
```
$ gcc -O2 -o fpclassify fpclassify.c // compile successfully with option -O2
$ gcc -Os -o fpclassify fpclassify.c // compile fail with option -Os
/tmp/ccvwJGcv.o: In function `main': 
fpclassify.c:(.text.startup+0x8): undefined reference to `__fpclassify'
collect2: error: ld returned 1 exit status
$ gcc -Os -o fpclassify fpclassify.c -lm // compile successfully with option -Os and -lm
```
In configuration, it tries to compile the above program to check if fpclassify requires -lm. 
But, it purely compiles the program without any option. 
` $ gcc -o conftest     conftest.c`

And I found CFLAGS cleared as empty before running this checking program in configure.ac in the following commit.
```
commit 96cf5aa30c2a11f2206240278ecff45fcd31d88c
Author: Quentin Armitage <quentin@armitage.org.uk>
Date:   Mon Mar 25 14:29:24 2019 +0000
        Fix rpmbuild on CentOS7, and rely on auto-requires
  configure.ac       | 25 +++++++++++++++++++++++++
  keepalived.spec.in | 20 ++++++++++++--------
  2 files changed, 37 insertions(+), 8 deletions(-)
```
```
+# Check if fpclassify() requires -lm
+CFLAGS=
+LDFLAGS=
+AC_MSG_CHECKING([whether fpclassify() requires -lm])
+AC_LINK_IFELSE([AC_LANG_SOURCE([[
+  # include <math.h>
+  int main(int argc, char **argv)
+  {
+    double zero = 0.0;
+    if (fpclassify(zero) == FP_ZERO)
+      return 0;
+    return 1;
+  }
+  ]])],
+  AC_MSG_RESULT([no]),
+  AC_MSG_RESULT([yes])
+    add_to_var([KA_LDFLAGS], [-lm])
+  )
+CFLAGS=$SAV_CFLAGS
+LDFLAGS=$SAV_LDFLAGS
+
```

It fixed rpmbuild on CentOS7. But my os is ubuntu.
Does it need to be fixed for more portable?

Thanks

**Comment by pqarmitage** [comment]
Commit 96cf5aa resolved a build problem reported against CentOS 7, and hence the comment. The fix, however, was a generic fix to the problem, namely that if using fpclassify() requires '-lm', then it was added to the LDFLAGS (should have been LIBS) setting for building keepalived.

The problems in this issue are that:
1; configure overrides the environment set CFLAGS while running; and
2. changing the CFLAGS environment variable between running configure and running make will (may) cause make to fail.

I am trying to work out the most general way of resolving this.

**Comment by pqarmitage** [comment]
@nylon7 Commit dea6cfb should resolve the problem of '-lm' being missing.
