### ISSUE TITLE
Arguments are not correctly passed to notify program

### ISSUE THREAD

**Issue by chr4** [acassen/keepalived#1267]
**Describe the bug**

Since `v2.0.16`, `notify` scripts seem to not pass the correct arguments to the called program.

E.g. This script

```
#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

umask 022

TYPE=$1
NAME=$2
STATE=$3

logger -t keepalived "Transition to state '$STATE' on VRRP instance '$NAME'."
```

called by `notify "myscript.sh"` upon transition only leads to the following log message:

```
Transition to state '' on VRRP instance ''.
```

**To Reproduce**

Use the script above with `v2.0.16`.

**Expected behavior**

The arguments are correctly passed.

**Keepalived version**

`v2.0.16-11-g1b96509+` (from snap), worked fine with `v2.0.15`.

**Distro (please complete the following information):**
 - Name Ubuntu
 - Version 18.04
 - Architecture x86_64

**Did keepalived coredump?**

No.

**Comment by skydevil56** [comment]
It works for me without problems (arguments are passed correctly) on version 2.0.16.

**Comment by pqarmitage** [comment]
This appears to be a feature of running keepalived in a snap. I have reproduced the problem running the keepalived snap on Ubuntu 18.04. I have also built the same code on Ubuntu 18.04 without any containerisation, and it doesn't have the problem.

I have also run the same snap on Ubuntu 16.04, and that doesn't exhibit the problem either. So this cannot be a keepalived problem, but looks like either a snap containerisation problem, or a change in snap containerisation from 16.04 to 18.04. I will take this up with Canonical to find out what is happening.

**Comment by chr4** [comment]
Thanks for looking into this!

A little offtopic: This caused some further issues, because it broke a running service due to the automatic update feature of snap, which apparently is less careful about updates than the automatic security patching from Ubuntu apt.

**Comment by pqarmitage** [comment]
I have investigate this further, and the problem is caused by the issue identified in issue #1266.

The code in question is:
```
        if (magic && flags & SC_EXECUTABLE) {
                const char *magic_desc = magic_file(magic, real_file_path ? real_file_path : script->args[0]);
                if (!strstr(magic_desc, " executable") &&
                    !strstr(magic_desc, " shared object")) {
                        log_message(LOG_INFO, "Please add a #! shebang to script %s", script->args[0]);
                        script->flags &= ~SC_EXECABLE;
                }
        }
```
If I force the checking for strings `executable` and `shared object` to fail, I get the script executing without parameters. So I think we have two issues:
1. Why is the check for `executable` and `shared object` failing - I will deal with that under issue #1266 2. Why, when the check fails, is the script executed without parameters. I will deal with that under this issue.

**Comment by pqarmitage** [comment]
Commit 62422b7 resolves the issue of the missing parameters. This problem only happened when keepalived thinks a script doesn't have a shebang.

**Comment by pqarmitage** [comment]
This update is now available in the snap edge channel. I'm not going to promote it yet to beta since there are too many recent commits that need some further testing first.

**Comment by chr4** [comment]
Thanks for looking into this and fixing it so quickly!
