### ISSUE TITLE
Keepalived v2.0.11 sometimes route to VIP isn't being deleted

### ISSUE THREAD

**Issue by yboaron** [acassen/keepalived#1268]
Sometimes after keepalived set & move a VIP in the node, the route for the VIP IP isn't being deleted.
The VIP (192.168.111.5) should be set to 'eth1' by keepalived as a secondary IP address.

This is the relevant part of both 'ip a' and 'ip route' before keepalived starts to run:
$ip a:
-----
eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 192.168.111.21/24 brd 192.168.111.255 scope global dynamic noprefixroute eth1
       valid_lft 2889sec preferred_lft 2889sec

$ ip r 
default via 192.168.111.1 dev eth1 proto dhcp metric 101 
10.128.0.0/14 dev tun0 scope link 
172.22.0.0/24 dev eth0 proto kernel scope link src 172.22.0.75 metric 100 
172.30.0.0/16 dev tun0 
192.168.111.0/24 dev eth1 proto kernel scope link src 192.168.111.21 metric 101 

Sometimes after keepalived set&move the VIP (192.168.111.5) from this node, I can still see the route to the VIP.
ip r:
-----
$ ip r 
default via 192.168.111.1 dev eth1 proto dhcp metric 101 
10.128.0.0/14 dev tun0 scope link 
172.22.0.0/24 dev eth0 proto kernel scope link src 172.22.0.75 metric 100 
172.30.0.0/16 dev tun0 
192.168.111.0/24 dev eth1 proto kernel scope link src 192.168.111.21 metric 101 
**192.168.111.5 dev eth1 proto kernel scope link src 192.168.111.5 metric 101** 
$ 
As a result of that, it's impossible to to communicate with the VIP from this node (e.g: ping 192.168.111.5);  I'm getting 'connect: Invalid argument' error (due to 'src 192.168.111.5').

I tried to search for a similar bug in keepalived bug list - but no luck, is it a known issue in V2.0.11?
I'm not sure if it's keepalived issue or maybe some kernel bug/issue.

**Keepalived version**
sh-4.4# keepalived --version
Keepalived v2.0.11 (01/06,2019), git commit v2.0.10-75-g40afb8e+
Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>
Built with kernel headers for Linux 4.19.13
Running on Linux 4.18.0-80.el8.x86_64 #1 SMP Wed Mar 13 12:02:46 UTC 2019
configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/i
nfo --enable-snmp --enable-snmp-rfc --enable-sha1 --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc
1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
Config options:  LIBIPTC LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3
System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS 
IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Distro (please complete the following information):**
 - Name rhel8
$ uname -mrs
Linux 4.18.0-80.el8.x86_64 x86_64
$

**Details of any containerisation or hosted service (e.g. AWS)**
Keepalived runs in a container with host networking on VM 

**Configuration file:**
The Keepalived.conf file :
-----------------------------------
vrrp_instance ostest_API {
    state BACKUP
    interface eth1
    virtual_router_id 169
    priority 40
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass ostest_api_vip
    }
    virtual_ipaddress {
        192.168.111.5
    }
    track_script {
        some_chk_script
    }
}

Many thanks in advance
Yossi

**Comment by pqarmitage** [comment]
@yboaron Below is the (edited) response I sent yesterday to your email to keepalived-devel with the same information:

When you say "set&move" the VIP, do you mean that the vrrp_instance becomes master, and then becomes backup again. If not, could you please explain what is happening.

With the keepalived configuration above keepalived doesn't do anything with routes (it will only add or delete routes if there are static_routes or virtual_routes statements). Note also that the highlighted route states 'proto kernel' which implies that the kernel added the route.

When the ip -r output shows the above, what does ip -a show? This looks like the route the kernel installs when an address with a subnet mask of /32 is added, and so suggests that the address is still configured.

It would be helpful if you could include what the keepalived logs show.

[It looks like you are running on RHEL 8, but ] the version of keepalived on RHEL 8 is 2.0.10. Have you built your own version of keepalived; if so is there a reason why you haven't used 2.0.15 or 2.0.16?

If you could answer the questions and provide the additional information requested, then we might be able to progress this issue.

**Comment by yboaron** [comment]
@pqarmitage - thanks a lot for a prompt response.
A. Yes, by "set&move" the VIP I meant that vrrp_instance becomes master and then backup.
B. We manage 3 VIPs with keepalived, this is the full keepalived.conf file:

vrrp_script chk_ocp {
    script "curl -o /dev/null -kLs https://0:6443/readyz"
    interval 1
    weight 50
}

vrrp_script chk_dns {
    script "host -t SRV _etcd-server-ssl._tcp.ostest.test.metalkube.org localhost"
    interval 1
    weight 50
}

vrrp_script chk_ingress {
    script "curl -o /dev/null -kLs https://0:1936/healthz"
    interval 1
    weight 50
}

vrrp_instance ostest_API {
    state BACKUP
    interface ens4
    virtual_router_id 169
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass ostest_api_vip
    }
    virtual_ipaddress {
        192.168.111.5/24
    }
    track_script {
        chk_ocp
    }
}

vrrp_instance ostest_DNS {
    state BACKUP
    interface ens4
    virtual_router_id 148
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass ostest_dns_vip
    }
    virtual_ipaddress {
        192.168.111.2/24
    }
    track_script {
        chk_dns
    }
}

vrrp_instance ostest_INGRESS {
    state BACKUP
    interface ens4
    virtual_router_id 10
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass cluster_uuid_ingress_vip
    }
    virtual_ipaddress {
        192.168.111.4/24
    }
    track_script {
        chk_ingress
    }
}

C. Keepalived runs in a container with host networking ( we build a customize container image , that includes keepalived + other tools that we need such as dig), and we use V2.0.11

Keepalived version:
sh-4.4# keepalived --version
Keepalived v2.0.11 (01/06,2019), git commit v2.0.10-75-g40afb8e+

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.19.13
Running on Linux 4.18.0-80.el8.x86_64 #1 SMP Wed Mar 13 12:02:46 UTC 2019

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --enable-snmp-rfc --enable-sha1 --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LIBIPTC LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK
sh-4.4#  

D. This time after 192.168.111.4/24 was set as master and then as backup once again, this is what we get:
*IP addresses and Ip routes before keepalived starts to  run:*

[core@master-0 ~]$ ip -4 a 
3: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 192.168.111.20/24 brd 192.168.111.255 scope global dynamic noprefixroute ens4
       valid_lft 2220sec preferred_lft 2220sec
[core@master-0 ~]$ ip r 
default via 192.168.111.1 dev ens4 proto dhcp metric 101 
172.22.0.0/24 dev ens3 proto kernel scope link src 172.22.0.91 metric 100 
192.168.111.0/24 dev ens4 proto kernel scope link src 192.168.111.20 metric 101

*   IP addresses and Ip routes when keepalived sets 192.168.111.4/24 VIP as master :*
[core@master-0 ~]$ ip -4 a 
3: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 192.168.111.20/24 brd 192.168.111.255 scope global dynamic noprefixroute ens4
       valid_lft 3205sec preferred_lft 3205sec
    inet 192.168.111.4/24 scope global secondary ens4
       valid_lft forever preferred_lft forever
[core@master-0 ~]$ ip route 
default via 192.168.111.1 dev ens4 proto dhcp metric 101 
172.22.0.0/24 dev ens3 proto kernel scope link src 172.22.0.91 metric 100 
192.168.111.0/24 dev ens4 proto kernel scope link src 192.168.111.20 metric 101 
192.168.111.0/24 dev ens4 proto kernel scope link src 192.168.111.4 metric 101 

*   IP addresses and Ip routes when keepalived sets 192.168.111.4/24 VIP as backup :*
[core@master-0 ~]$ ip -4 a 
3: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 192.168.111.20/24 brd 192.168.111.255 scope global dynamic noprefixroute ens4
       valid_lft 3477sec preferred_lft 3477sec
[core@master-0 ~]$ 
[core@master-0 ~]$ ip route 
default via 192.168.111.1 dev ens4 proto dhcp metric 101 
172.22.0.0/24 dev ens3 proto kernel scope link src 172.22.0.91 metric 100 
192.168.111.0/24 dev ens4 proto kernel scope link src 192.168.111.20 metric 101 
*192.168.111.0/24 dev ens4 proto kernel scope link src 192.168.111.4 metric 101* 
[core@master-0 ~]$

In this case the *192.168.111.0/24 dev ens4 proto kernel scope link src 192.168.111.4 metric 101* routing entry wasn't deleted as I expected.

E. The way I'm triggering VIP switch, is by chaning priority in keepalived.conf and restarting the keepalived container.

So, the detailed flow is :
1. increase priority in keepalived conf file and restart (stop&start) container
2. keepalived container will set as master for the VIP
3. Decrease priority in keepalived conf file and restart (stop&start) container
4. keepalived container will set as backup for the VIP

I managed to collect the logs from the container only after step '4'.

[core@master-0 ~]$ sudo crictl logs 336eac48c6164
Wed May 15 14:54:18 2019: Starting Keepalived v2.0.11 (01/06,2019), git commit v2.0.10-75-g40afb8e+
Wed May 15 14:54:18 2019: WARNING - keepalived was build for newer Linux 4.19.13, running on Linux 4.18.0-80.el8.x86_64 #1 SMP Wed Mar 13 12:02:46 UTC 2019
Wed May 15 14:54:18 2019: Command line: '/usr/sbin/keepalived' '-f' '/etc/keepalived/keepalived.conf' '--dont-fork' '--vrrp'
Wed May 15 14:54:18 2019:               '--log-detail' '--log-console'
Wed May 15 14:54:18 2019: Opening file '/etc/keepalived/keepalived.conf'.
Wed May 15 14:54:18 2019: Starting VRRP child process, pid=10
Wed May 15 14:54:18 2019: Registering Kernel netlink reflector
Wed May 15 14:54:18 2019: Registering Kernel netlink command channel
Wed May 15 14:54:18 2019: Opening file '/etc/keepalived/keepalived.conf'.
Wed May 15 14:54:18 2019: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Wed May 15 14:54:18 2019: (Line 27) Truncating auth_pass to 8 characters
Wed May 15 14:54:18 2019: (Line 45) Truncating auth_pass to 8 characters
Wed May 15 14:54:18 2019: (Line 63) Truncating auth_pass to 8 characters
Wed May 15 14:54:18 2019: WARNING - script `curl` resolved by path search to `/usr/bin/curl`. Please specify full path.
Wed May 15 14:54:18 2019: WARNING - script `host` resolved by path search to `/usr/bin/host`. Please specify full path.
Wed May 15 14:54:18 2019: WARNING - script `curl` resolved by path search to `/usr/bin/curl`. Please specify full path.
Wed May 15 14:54:18 2019: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Wed May 15 14:54:18 2019: Assigned address 192.168.111.20 for interface ens4
Wed May 15 14:54:18 2019: Assigned address fe80::d3a1:90b2:511a:5c45 for interface ens4
Wed May 15 14:54:18 2019: Registering gratuitous ARP shared channel
Wed May 15 14:54:18 2019: (ostest_API) removing VIPs.
Wed May 15 14:54:18 2019: (ostest_DNS) removing VIPs.
Wed May 15 14:54:18 2019: (ostest_INGRESS) removing VIPs.
Wed May 15 14:54:18 2019: (ostest_API) Entering BACKUP STATE (init)
Wed May 15 14:54:18 2019: (ostest_DNS) Entering BACKUP STATE (init)
Wed May 15 14:54:18 2019: (ostest_INGRESS) Entering BACKUP STATE (init)
Wed May 15 14:54:18 2019: VRRP sockpool: [ifindex(3), family(IPv4), proto(112), unicast(0), fd(10,11)]
Wed May 15 14:54:18 2019: Script `chk_ocp` now returning 7
Wed May 15 14:54:18 2019: VRRP_Script(chk_ocp) failed (exited with status 7)
Wed May 15 14:54:18 2019: Script `chk_ingress` now returning 7
Wed May 15 14:54:18 2019: VRRP_Script(chk_ingress) failed (exited with status 7)
Wed May 15 14:54:18 2019: VRRP_Script(chk_dns) succeeded
Wed May 15 14:54:18 2019: (ostest_DNS) Changing effective priority from 100 to 150
[core@master-0 ~]$

**Comment by pqarmitage** [comment]
@yboaron The route `192.168.111.0/24 dev ens4 proto kernel scope link src 192.168.111.4 metric 101` is not a route added by keepalived; if it were it would show `proto 112` rather than `proto kernel`. The route is added by the kernel when the address 192.168.111.4 is added.

Since you already have `192.168.111.20/24` configured on ens4, the virtual_ipaddress blocks should be configured without /24, e.g.
```
virtual_ipaddress {
192.168.111.4/24
}
```
but I don't think this will solve your problem.

I am guessing here, but I think what is happening is that when you stop the container, keepalived is not being terminated (i.e. it is not being sent a SIGTERM), and also when the container is shutting down it is saving the entries in the routing table to a file. When the container restarts, it reloads the routes, and that is where the route `192.168.111.0/24 dev ens4 proto kernel scope link src 192.168.111.4 metric 101` - it is not being added by keepalived.

What I think you should try doing is after you have edited the keepalived config in the container, rather than stopping and restarting the container, send a SIGHUP to the keepalived process in the container. That will make keepalived reload its configuration, and the priority of the vrrp_instance will change accordingly.

Another way to change the priority of vrrp instances is to use a track script, or a track file. I often use a track file (more efficient than a track script, and a change will occur near instantaneously), since you can write a numeric value to the file, the the priority of the vrrp instance will change accordingly.

I think if you try reloading the vrrp configuration using SIGHUP, or use a track_file or track_script to change the vrrp_instance's priority, you won't have the problem of the route being left behind when the address is deleted.

It is certainly the case that the route in question is not being added (or deleted) by keepalived. The route will have been initially added due to keepalived adding the 192.168.111.4/24 address, but it is the kernel that has added the route. After restarting the container, and with keepalived in backup mode, keepalived is not the cause of the route being installed, it is coming from somewhere else.

**Comment by yboaron** [comment]
@pqarmitage, thank you very much for the detailed explanation.
It sounds very reasonable that '192.168.111.0/24 dev ens4 proto kernel scope link src 192.168.111.4 metric 101' doesn't come from keepalived.

I'll try to reproduce it with SIGHUP or track_file and will update.

Thanks
Yossi

**Comment by yboaron** [comment]
@pqarmitage, 
I run the test with SIGHUP instead of restarting the container and got the same behavior.
First I changed manually the priority of all 3 VIPs in keepalived.conf file to be 22 (backup)

And then I run the [1] bash script, that force setting all 3 VIPs as masters and then back to backup.
After ~60 iterations I saw once again the unexpected route entries, see [2].

You can find in [3] the logs from the keepalived container.
As you mentioned before, It seems to me as kind of a bug or some race in the kernel and not something related to keepalived.

Will be glad to receive your feedback on that matter
Thanks 
Yossi

[1] 
#!/bin/bash

for i in {1..400}
do
   echo "Inside loop $i times"
   sudo sed -i -- 's/22/222/g' /var/lib/kubelet/pods/32ab6983489fc78d01b260c941ab94a5/volumes/kubernetes.io~empty-dir/conf-dir/keepalived.conf 
   sudo crictl exec  a8b6217e09587   kill -SIGHUP 1
   echo "Setting VIPs as active and sleep 30 seconds"
   sleep 30
   sudo sed -i -- 's/222/22/g' /var/lib/kubelet/pods/32ab6983489fc78d01b260c941ab94a5/volumes/kubernetes.io~empty-dir/conf-dir/keepalived.conf
   sudo crictl exec  a8b6217e09587   kill -SIGHUP 1
   echo "Setting VIPs as backup  and sleep 30 seconds"
   sleep 30

done

[2]
[core@master-0 ~]$ ip route 
default via 192.168.111.1 dev ens4 proto dhcp metric 101 
172.22.0.0/24 dev ens3 proto kernel scope link src 172.22.0.91 metric 100 
192.168.111.0/24 dev ens4 proto kernel scope link src 192.168.111.20 metric 101 
192.168.111.0/24 dev ens4 proto kernel scope link src 192.168.111.4 metric 101 
192.168.111.0/24 dev ens4 proto kernel scope link src 192.168.111.5 metric 101 
192.168.111.0/24 dev ens4 proto kernel scope link src 192.168.111.2 metric 101 
[core@master-0 ~]$ 

[3]
[keeaplived_container_log.txt](https://github.com/acassen/keepalived/files/3194987/keeaplived_container_log.txt)

**Comment by yboaron** [comment]
@pqarmitage ,
I found this line at the beginning of keepalived container log file:
"
WARNING - keepalived was build for newer Linux 4.19.13, running on Linux 4.18.0-80.el8.x86_64 #1 SMP Wed Mar 13 12:02:46 UTC 2019"

Do you think that this may lead to the 'strange'/unexpected behavior?

Yossi

**Comment by pqarmitage** [comment]
Yossi,
I noticed that yesterday and checked that there is no new functionality in Linux 4.19 that keepalived uses when compared to
Linux 4.18 so it shouldn't be a problem. However, in general it is best to build keepalived with the kernel headers of the
target system, so that keepalived doesn't try to use functionality in the kernel that doesn't exist, and also it doesn't not
use functionality that does exist; hence the warning when the versions don't match.
Quentin

**Comment by pqarmitage** [comment]
Re https://github.com/acassen/keepalived/issues/1268#issuecomment-493747074 does the route only get left after many iterations of transition from master to backup to master to backup etc, or does it only occur after a single iteration of master to backup. Also, when the route gets left is the address still configured on ens4?

I'm a bit confused with the script above, due to the strikethroughs. I presume it is:
#!/bin/bash
```
for i in {1..400}
do
echo "Inside loop $i times"
sudo sed -i -- 's/22/222/g' /var/lib/kubelet/pods/32ab6983489fc78d01b260c941ab94a5/volumes/kubernetes.io~empty-dir/conf-dir/keepalived.conf
sudo crictl exec a8b6217e09587 kill -SIGHUP 1
echo "Setting VIPs as active and sleep 30 seconds"
sleep 30
sudo sed -i -- 's/222/22/g' /var/lib/kubelet/pods/32ab6983489fc78d01b260c941ab94a5/volumes/kubernetes.io~empty-dir/conf-dir/keepalived.conf
sudo crictl exec a8b6217e09587 kill -SIGHUP 1
echo "Setting VIPs as backup and sleep 30 seconds"
sleep 30

done
```

Could you change it to something like:
```
for i in {1..400}
do
echo "Inside loop $i times"
sudo sed -i -- 's/22/222/g' /var/lib/kubelet/pods/32ab6983489fc78d01b260c941ab94a5/volumes/kubernetes.io~empty-dir/conf-dir/keepalived.conf
sudo crictl exec a8b6217e09587 kill -SIGHUP 1
sleep 2
(date; echo; ip route; echo; ip address show ens4; echo; echo) >>SOME_USEFUL_FILE
echo "Setting VIPs as active and sleep 30 seconds"
sleep 30
sudo sed -i -- 's/222/22/g' /var/lib/kubelet/pods/32ab6983489fc78d01b260c941ab94a5/volumes/kubernetes.io~empty-dir/conf-dir/keepalived.conf
sudo crictl exec a8b6217e09587 kill -SIGHUP 1
sleep 2
(date; echo; ip route; echo; ip address show ens4; echo; echo) >>SOME_USEFUL_FILE
echo "Setting VIPs as backup and sleep 30 seconds"
sleep 30

done
```
we can then see when the problem occurs, and also if the address has been left configured.

Another test that needs to be done is to remove the `/24`s from the VIPs, and see if the problem still exists then.

I don't have any RHEL8 containers, but I do have an RHEL8 virtual machine, and I will try the test in that to see if I can reproduce the problem.

**Comment by yboaron** [comment]
Quentin,

When the problem occurs, we have the route (e.g: 192.168.111.0/24 dev ens4 proto kernel scope link src 192.168.111.2 metric 101) although  192.168.111.2/24 IP address was deleted from ens4.

The real problem with the undeleted route is that in some cases (depends on the netmask configured for the VIP in keepalived.conf), 
the kernel may use (longest prefix match) the undeleted route entry to transmit a packet, and because the ip specified as src (e.g: 'src 192.168.111.2') is not defined, the kernel will drop the packet 
and report 'connect: Invalid argument' error.

Regarding using /32 instead of /24, it happened also with /32. I discovered originally this problem when I used /32 for the VIP.
 
I'll try to reproduce it with your suggestions and keep u posted
Yossi

**Comment by yboaron** [comment]
@pqarmitage,
Please find the bash script output file.
The problem occurs at 'Sun May 19 16:37:44 UTC 2019' in the output file.

[script_log.txt](https://github.com/acassen/keepalived/files/3195369/script_log.txt)

**Comment by pqarmitage** [comment]
@yboaron Apologies for the delay in looking at this.

The log is indeed very interesting, and I think points us in the direction of the cause of the problem.

At 16:37:12, the address entry for 192.168.111.20/24 shows:
>    inet 192.168.111.20/24 brd 192.168.111.255 scope global dynamic noprefixroute ens4
       valid_lft 1926sec preferred_lft 1926sec

At 16:37:44 it shows:
>    inet 192.168.111.20/24 brd 192.168.111.255 scope global dynamic noprefixroute ens4
       valid_lft 3570sec preferred_lft 3570sec

This means that the DHCP lease on 192.168.111.20/24 has been renewed between 16:37:12 and 16:37:44. It would appear that whatever is managing the DHCP leases is also doing something with the routes.

When I run keepalived on RHEL8 with your configuration I do not get any routes added when the addresses being added are members of an already configured subnet (i.e. as in your configuration). However, if the addresses being added are on different subnets that I do get routes added, but without any metric being shown by `ip route show`.

So the question is, what is managing the DHCP leases on your system, and can we confirm that it is that which is also adding the routes for the addresses that keepalived is adding. It looks to me as though what is happening is that whatever is managing the renewal of the lease saves all the routes before renewing the lease and restores them afterwards, while at the same time, keepalived is deleting the addresses.

On my RHEL8 system, NetworkManager is managing DHCP, and that seems to be the supported way for RHEL8. Are you using NetworkManager to manage your interfaces, or are you using something else like systemd-netword (we know that systemd-networkd interferes with network configuration set up by other processes - see [systemd issue](https://github.com/acassen/keepalived/issues/1170#issuecomment-490461367))?

I think what you need to do now is to re-run the script that I provided above, and then we need to see a copy of the system log from a couple of minutes before the problem occurred throught to a couple of minutes afterwards. I think we might see something about the DHCP lease being renewed, and what else is happening.

**Comment by yboaron** [comment]
@pqarmitage 
Thank you for dedicating your time and energy into this.
I'm using NetworkManager to manage my interfaces.
I managed to reproduce the problem using 'ip address add/delete' CLI commands, so as u wrote above seems that the bug is not related directly to keepalived.
I'll try to reproduce it and collect also the relevant system logs
Yossi

**Comment by pqarmitage** [comment]
@yboaron It's good that the bug does not appear to be with keepalived (at least for keepalived developers!). Did you use a script to reproduce the problem with `ip address add/delete' commands? If so, it would be very helpful if you could post the script here, and I will try it on my RHEL8 and Fedora systems.

If you end up reporting a bug against RHEL for example, could you please post a link to the bug report heretoo.

**Comment by pqarmitage** [comment]
@yboaron What I hadn't noticed previously is that the additional routes didn't appear at all until 16:37:44,so the routes are being added when the DHCP lease is renewed on 192.168.111.20, and aren't added at all simply by adding the 192.168.111.2 etc addresses.

I have managed to reproduce this problem on my Fedora 30 system. I have set the DHCP lease time to 120 seconds, so that the lease is removed approximately every minute. If I add a single address, e.g. 192.168.111.2/24, then initially NO route exists with 192.168.111.2 as the source address. Then, at precisely the time that the DHCP lease is renewed, the route with the source address 192.168.111.2/24 is added. So the problem appears to be caused by dhclient or NetworkManager.

**Comment by yboaron** [comment]
@pqarmitage, Yep; seems like a bug caused by dhclient or NetworkManager.
BTW, did you reproduce it using the 'ip a a/d' CLI commands?

**Comment by pqarmitage** [comment]
@yboaron 
>BTW, did you reproduce it using the 'ip a a/d' CLI commands?

Yes. All I did was:
`ip address add 192.168.111.2/24 dev ens4`
`ip route show` and from this see that there is no route installed with src 192.168.111.2
`ip addr show ens4` shows the valid_lft for 192.168.111.20. I think your system is renewing the DHCP lease when valid_lft has counted down to 1800 seconds.
After the DHCP lease has expired and been renewed, do
`ip route show`
and you will see the 192.168.111.0/24 with src 192.168.111.2 added.

If you want to be more certain that it is happening at the same time as the lease is renewed, then you could use the script above to output the routes and addresses every second, and you will see the route is added at the same time as the valid_lft is increased to around 3600 seconds.

**Comment by pqarmitage** [comment]
See https://github.com/systemd/systemd/issues/13555#issuecomment-531444829 for how to configure systemd .network files to avoid this problem.

**Comment by pqarmitage** [comment]
@wuchuxiong This is not a keepalived issue. From previous comments it was identified as a system-networkd issue. The link in https://github.com/acassen/keepalived/issues/1268#issuecomment-557470398 has suggestions for how to resolve this.
