### ISSUE TITLE
keepalived ignores ops in its configuration file

### ISSUE THREAD

**Issue by eseyman** [acassen/keepalived#127]
I'm using keepalived 1.2.15 on two servers and keepalived doesn't seem to be picking up the fact that the virtual_server stanza includes 'ops'.

Here's the section of the keepalived.conf file:
virtual_server 192.168.0.56 514 {
    delay_loop 6
    lvs_sched rr
    lb_kind DR
    ops
...
}

Here's what I'm seeing in syslog when I run 'keepalived -d':

Keepalived_healthcheckers[6083]:  System is compiled with LVS v1.2.1
Keepalived_healthcheckers[6083]:  VIP = 192.168.0.56, VPORT = 514
Keepalived_healthcheckers[6083]:    delay_loop = 6, lb_algo = rr
Keepalived_healthcheckers[6083]:    protocol = UDP
Keepalived_healthcheckers[6083]:    alpha is OFF, omega is OFF
Keepalived_healthcheckers[6083]:    quorum = 1, hysteresis = 0
Keepalived_healthcheckers[6083]:    lb_kind = DR

There's no mention of ops and running 'ipvsadm -S' shows that it isn't activated.

**Comment by pqarmitage** [comment]
Commit fee5891 adds reporting of ops mode with keepalived -d.

Using the latest git code,  I get the following, which confirms ops mode is being set.
> ipvsadm -S
-A -u 192.168.200.100 -s rr ops
