### ISSUE TITLE
send garp to unicast peer when leaving fault state

### ISSUE THREAD

**Issue by olivier-matz-6wind** [acassen/keepalived#1283]
Hi,

I have an issue in the following VRRP scenario:
- unicast peering
- fast advertisements (100ms)

```
Machine A
    version 3
    state BACKUP
    interface eth0
    garp_master_delay 1
    virtual_router_id 1
    priority 200
    advert_int 100
    unicast_peer {
      192.168.0.1
    }
    virtual_ipaddress {
      10.200.0.2/24
    }
    preempt_delay 30

Machine B
    version 3
    state BACKUP
    interface eth0
    garp_master_delay 1
    virtual_router_id 1
    priority 100
    advert_int 100
    unicast_peer {
      192.168.0.2
    }
    virtual_ipaddress {
      10.200.0.1/24
    }
    preempt_delay 30
```

1/ initial state: A is master

2/ set eth0 down on machine A

   A switch to fault, B becomes master

   B sends advertisements to A, but after some time, the
   ARP cache expires, so B regularly sends ARP requests that
   have no answers.

4/ set eth0 up on machine A

   A changes to backup, and after ~300ms (down timer), it thinks there
   is no other master so it changes to master, bypassing the preemt_delay.

I workarounded the issue by using static ARP entries.

Is there a feature in keepalived to solve this issue? Should keepalived
send gratuitous ARPs when leaving the fault state when using unicast
peers? Or is it something that should be done in a user script?

Quoting @pqarmitage 's answer on the mailing list:

> This is clearly an issue, and keepalived currently has no direct mechanism to send gratuitous ARPs when leaving fault state.
> I think your suggestion that keepalived when using unicasting should send gratuitous ARP messages when transitioning out of
> fault state is the correct solution.
> 

I'm using Keepalived v2.0.10, compiled from sources, running on ubuntu 18.04 (x86_64).

**Comment by pqarmitage** [comment]
Commit 327138e should resolve the problem. A GARP/NA message is sent when using unicasting whenever a VRRP instance transitions out of fault state; this could be due to an interface coming back up, or the unicast_src address being added back following deletion, both of which need a GARP message, or for other reasons such as a track_script, which doesn't need the GARP message, but it won't hurt sending one.

**Comment by olivier-matz-6wind** [comment]
Hi @pqarmitage, many thanks for the quick fix!
I'll come back to you as soon as we have tested it on our platform.

**Comment by olivier-matz-6wind** [comment]
Hi,

I confirm that the patch solves our issue. Thanks again.

Olivier
