### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by yctn** [acassen/keepalived#1296]
so i had this idea. maby it would be a good idea to add a REST API into keepalived.
keepalived is awesome. VRRP and the ipvs stuff it just works. very well.

but its not realy dynamic/easy to adjust.

currently we have a mysql database with all oure virtual servers, realservers and we use a php script to generate a config.  oure config is currently like 10 pages long. and with a bash command i can fetch a new config and reload. but still its self baked and not realy a good and sustainable sollution for long term.

i think more people who realy like to have this option. you dont have to ditch the config. but the possibility to change/add things over an api would be nice to have.

also with a REST API it would be alot easyer to wire stuff to keepalived. like kubernetes or mesos or etcd

**Comment by pqarmitage** [comment]
This would be a major change to keepalived, since at the moment it is not designed to expect configuration changes while it is running, other than a full config reload.

It would be helpful if you could provide specific examples of what functionality you would like, and how you would envisage the interface being implemented.

**Comment by Mint-M** [comment]
If keepalived can provide the state of instances through rest api, it would be a very useful function.
Currently, only logs shows related information, however, it is to complex to determine the state of instances by analysing the logs.
BTW, smtp alerts are not so reliable and emails might be ignored.

**Comment by pqarmitage** [comment]
@Mint-M notify_fifos can be used to reliably track the state of instances, as can SNMP.

**Comment by Mint-M** [comment]
@pqarmitage Sorry for my late reply.
notify_fifos seem to work only for local processes, doesn't it?
For instance, I have over one hundred servers running keepalived with different instances.
It's crucial to monitor whether any instance enters fault state using a central application (For example, a java application gathers information from keepalived through rest api and shows the current state on a web page).

**Comment by pqarmitage** [comment]
@Mint-M Using SNMP would appear to do exactly what you want.

**Comment by Mint-M** [comment]
@pqarmitage Thanks for your suggestion. SNMP seems to be much powerful than I thought.

**Comment by pqarmitage** [comment]
Closing since it appears using SNMP satisfies the requirement.

**Comment by yctn** [comment]
the only function that im missing in snmp(correct me if im wrong) is to add and remove realservers. and add and remove virtual servers

**Comment by pqarmitage** [comment]
The SNMP interfaces are predominantly read only. There are 6 attributes that the KEPALIVED-MIB says are read-write:
vrrpInstanceBasePriority
vrrpInstancePreempt
vrrpInstanceAccept
vrrpInstancePromoteSecondaries
vrrpInstanceUseLinkbeat
realServerWeight

These are all attributes of existing objects (vrrp instances and real servers). The SNMP interface currently does not support adding or deleting objects (vrrp instances, real servers, virtual servers or even virtual IP addresses for example). Furthermore, the changes above are not persistent, and will be lost of keepalived is stopped and restarted, or even if the configuration is reloaded.

Whilst I can see that the functionality would be useful for you, there haven't been requests from elsewhere for this, so it is likely that this functionality would only be implemented if someone wanted to sponsor its development.

**Comment by yctn** [comment]
clear answer  thx!
