### ISSUE TITLE
VRRP Sending packets with wrong sourceaddress

### ISSUE THREAD

**Issue by tuxis-ie** [acassen/keepalived#13]
I have an issue with keepalived in Vyatta. I created a bug there (https://bugzilla.vyatta.com/show_bug.cgi?id=8452) but I thought it might be wise to create an issue here too.

The issue is that keepalived is ignoring the mcast_src_ip setting for a part of the configuration. The master is sending out packets with the virtual address instead. This completely goes haywire after a failover, where suddenly a virtual address on another interface is used to send the packets.

Please see the Vyatta bug for details and let me know if I'm doing something wrong or something needs testing.

**Comment by amar911** [comment]
what is the use of mcast_src_ip     and how we can verify it
