### ISSUE TITLE
Wrong receiver when sending alert mails

### ISSUE THREAD

**Issue by Mint-M** [acassen/keepalived#1303]
**Describe the bug**
The receiver of the alerting repeats for several times and the content of the mail is placed at receivers.

**To Reproduce**
config:
global_defs {
    router_id fb
    vrrp_mcast_group4 224.0.0.251
    notification_email {
        root@localhost.localdomain
    }
    notification_email_from fb
    smtp_server 127.0.0.1
    smtp_connect_timeout 30
}

vrrp_instance eth0 {
    state BACKUP 
    interface eth0
    virtual_router_id 17
    priority 211
    advert_int 1
    virtual_ipaddress {
        192.168.199.199/24 dev eth0
    }
    smtp_alert
}

mail server:postfix 3.4.4

mail:
From fb@localhost.localdomain
Return-Path: <fb@localhost.localdomain>
X-Original-To: root@localhost.localdomain
Delivered-To: root@localhost.localdomain
Received: from localhost (localhost [127.0.0.1])
	by localhost.localdomain (Postfix) with SMTP id 330A1103469A
	for <root@localhost.localdomain>
From: fb@localhost.localdomain
Subject: [fb] VRRP Instance eth0 - Entering MASTER state
X-Mailer: Keepalived
To: "root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root@localhost.localdomain, root"@localhost.localdo=>,
	VRRP@localhost.localdomain, Instance@localhost.localdomain,
	is@localhost.localdomain, now@localhost.localdomain,
	owning@localhost.localdomain, VRRP@localhost.localdomain,
	"VIPs <="@localhost.localdomain
Message-Id: <20190610074635.330A1103469A@localhost.localdomain>

**Expected behavior**
In older versions, the receivers were correct.

From fb@localhost.localdomain
Return-Path: <fb@localhost.localdomain>
X-Original-To: root@localhost.localdomain
Delivered-To: root@localhost.localdomain
Received: from localhost (localhost [127.0.0.1])
	by localhost.localdomain (Postfix) with SMTP id 07B971030CD3
	for <root@localhost.localdomain>
From: fb@localhost.localdomain
Subject: [fb] VRRP Instance eth0 - Entering MASTER state
X-Mailer: Keepalived
To: root@localhost.localdomain
Message-Id: <20190610075105.07B971030CD3@localhost.localdomain>

=> VRRP Instance is now owning VRRP VIPs <=

**Keepalived version**
Running on Linux 5.0.13-300.fc30.x86_64 #1 SMP Mon May 6 00:39:45 UTC 2019

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-snmp-reply-v3-for-v2 --with-init=systemd --enable-bfd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LIBIPTC LIBIPSET_DYNAMIC NFTABLES LVS VRRP VRRP_AUTH BFD OLD_CHKSUM_COMPAT FIB_ROUTING EINTR_CHECK

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Distro (please complete the following information):**
5.1.3-300.fc30.x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
a local vm

**Configuration file:**
was attached above

**System Log entries**
Keepalived[70314]: Starting Keepalived v2.0.16 (unknown)
Keepalived[70314]: Running on Linux 5.0.13-300.fc30.x86_64 #1 SMP Mon May 6 00:39:45 UTC 2019 (built for Linux 5.0.9)
Keepalived[70314]: Command line: '/usr/sbin/keepalived' '-D'
Keepalived[70314]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived[70315]: Starting VRRP child process, pid=70316
systemd[1]: Started LVS and VRRP High Availability Monitor.
Keepalived_vrrp[70316]: Registering Kernel netlink reflector
Keepalived_vrrp[70316]: Registering Kernel netlink command channel
Keepalived_vrrp[70316]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived_vrrp[70316]: Assigned address 192.168.199.1 for interface eth0
Keepalived_vrrp[70316]: Assigned address fe80::20c:29ff:fe83:ebb5 for interface eth0
Keepalived_vrrp[70316]: Registering gratuitous ARP shared channel
Keepalived_vrrp[70316]: (eth0) removing VIPs.
audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=keepalived comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Keepalived_vrrp[70316]: (eth0) Entering BACKUP STATE (init)
Keepalived_vrrp[70316]: VRRP sockpool: [ifindex(2), family(IPv4), proto(112), unicast(0), fd(12,13)]
Keepalived_vrrp[70316]: Remote SMTP server [127.0.0.1]:25 connected.
Keepalived_vrrp[70316]: SMTP alert successfully sent.
Keepalived_vrrp[70316]: (eth0) Receive advertisement timeout
Keepalived_vrrp[70316]: (eth0) Entering MASTER STATE
Keepalived_vrrp[70316]: (eth0) setting VIPs.
Keepalived_vrrp[70316]: Sending gratuitous ARP on eth0 for 192.168.199.199
Keepalived_vrrp[70316]: (eth0) Sending/queueing gratuitous ARPs on eth0 for 192.168.199.199
Keepalived_vrrp[70316]: Sending gratuitous ARP on eth0 for 192.168.199.199
Keepalived_vrrp[70316]: Sending gratuitous ARP on eth0 for 192.168.199.199
Keepalived_vrrp[70316]: Sending gratuitous ARP on eth0 for 192.168.199.199
Keepalived_vrrp[70316]: Sending gratuitous ARP on eth0 for 192.168.199.199
Keepalived_vrrp[70316]: Remote SMTP server [127.0.0.1]:25 connected.
Keepalived_vrrp[70316]: SMTP alert successfully sent.
Keepalived_vrrp[70316]: Sending gratuitous ARP on eth0 for 192.168.199.199
Keepalived_vrrp[70316]: (eth0) Sending/queueing gratuitous ARPs on eth0 for 192.168.199.199
Keepalived_vrrp[70316]: Sending gratuitous ARP on eth0 for 192.168.199.199
Keepalived_vrrp[70316]: Sending gratuitous ARP on eth0 for 192.168.199.199
Keepalived_vrrp[70316]: Sending gratuitous ARP on eth0 for 192.168.199.199
Keepalived_vrrp[70316]: Sending gratuitous ARP on eth0 for 192.168.199.199

**Comment by pqarmitage** [comment]
Many thanks for reporting this. Now resolved by commit cbd64f1.
