### ISSUE TITLE
keepalived v2.0.7 notify_master not working

### ISSUE THREAD

**Issue by itssameermd** [acassen/keepalived#1320]
Below is my keepalived.conf, notify_master is not running : 
--------------------------------------
global_defs {
script_user root
enable_script_security
}

vrrp_script chk_haproxy {
    script "pidof haproxy"
    interval 2
}
vrrp_instance VI_1 {
    debug 2
    interface eth0 # interface to monitor
    state BACKUP
    virtual_router_id 51 # Assign one ID for this route
    priority 100 # 101 on master, 100 on bacp
    unicast_src_ip 172.31.X.X # My IP
    unicast_peer {
        172.31.X.X # peer IP
    }
    track_script {
        chk_haproxy
    }
    notify_master /etc/keepalived/master.sh
} 

-------------------------------------

My master.sh file is : 

#!/bin/bash
EIP=13.235.X.x
INSTANCE_ID=i-0098bf692ac8xxxxxx
/root/.local/bin/aws ec2 disassociate-address --public-ip $EIP
/root/.local/bin/aws ec2 associate-address --public-ip $EIP --instance-id $INSTANCE_ID

--------------------------------------

When failover happens, the state changes from backup to master but the notify_master script doesnt execute & elastic IP is not associated with backup instance.

Kindly assist.

**Comment by pqarmitage** [comment]
Using your config above, and testing both the lastest keepalived code and v2.0.7, the notify_master script runs for me.

It might be worth simplifying the script to something like:
```
#!/bin/bash

echo $(date): $* >>/tmp/master.log
```
to see whether the problem is that the script is not running, or the script is running but not doing what you expect.

Could you please post the keepalived logs from the time keepalived starts until the vrrp instance transitions to master state (when I first set this up the script wouldn't execute since i) it was writable by a non-root user and ii)the execute bit wasn't set. The logs will help diagnose this sort of issue).

Could you also please post the output of `ls -l /etc/keepalived/master.sh`

**Comment by itssameermd** [comment]
I have edited the master.sh file as per the above script. Below is mykeepalived logs from starting till the slave transitions to master. But the master.sh file didnt executed :

Jun 19 09:52:31 ip-172-31-6-20 systemd: Starting LVS and VRRP High Availability Monitor...
Jun 19 09:52:31 ip-172-31-6-20 Keepalived[1377]: Starting Keepalived v2.0.7 (08/23,2018)
Jun 19 09:52:31 ip-172-31-6-20 Keepalived[1377]: Running on Linux 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 (built for Linux 3.10.0)
Jun 19 09:52:31 ip-172-31-6-20 Keepalived[1377]: Command line: '/usr/sbin/keepalived' '-D'
Jun 19 09:52:31 ip-172-31-6-20 Keepalived[1377]: Opening file '/etc/keepalived/keepalived.conf'.
Jun 19 09:52:31 ip-172-31-6-20 systemd: Started LVS and VRRP High Availability Monitor.
Jun 19 09:52:31 ip-172-31-6-20 Keepalived[1378]: Starting VRRP child process, pid=1379
Jun 19 09:52:31 ip-172-31-6-20 Keepalived_vrrp[1379]: Registering Kernel netlink reflector
Jun 19 09:52:31 ip-172-31-6-20 Keepalived_vrrp[1379]: Registering Kernel netlink command channel
Jun 19 09:52:31 ip-172-31-6-20 Keepalived_vrrp[1379]: Opening file '/etc/keepalived/keepalived.conf'.
Jun 19 09:52:31 ip-172-31-6-20 Keepalived_vrrp[1379]: WARNING - script `pidof` resolved by path search to `/usr/sbin/pidof`. Please specify full path.
Jun 19 09:52:31 ip-172-31-6-20 Keepalived_vrrp[1379]: Assigned address 172.31.6.20 for interface eth0
Jun 19 09:52:31 ip-172-31-6-20 Keepalived_vrrp[1379]: Assigned address fe80::80b:80ff:fe57:c838 for interface eth0
Jun 19 09:52:31 ip-172-31-6-20 Keepalived_vrrp[1379]: Registering gratuitous ARP shared channel
Jun 19 09:52:31 ip-172-31-6-20 Keepalived_vrrp[1379]: VRRP sockpool: [ifindex(2), proto(112), unicast(1), fd(8,9)]
Jun 19 09:52:31 ip-172-31-6-20 Keepalived_vrrp[1379]: VRRP_Script(chk_haproxy) succeeded
Jun 19 09:52:31 ip-172-31-6-20 Keepalived_vrrp[1379]: (VI_1) Entering BACKUP STATE
Jun 19 09:52:47 ip-172-31-6-20 Keepalived_vrrp[1379]: (VI_1) Backup received priority 0 advertisement
Jun 19 09:52:48 ip-172-31-6-20 Keepalived_vrrp[1379]: (VI_1) Receive advertisement timeout
Jun 19 09:52:48 ip-172-31-6-20 Keepalived_vrrp[1379]: (VI_1) Entering MASTER STATE

------------------------------------------

Output of ls -l /etc/keepalived/master.sh : 

-rwx------. 1 root root 48 Jun 19 09:51 /etc/keepalived/master.sh

Nothing is written to /tmp/master.log.

Kindly advise

**Comment by pqarmitage** [comment]
@itssameermd Thank you for the update. From what you have said keepalived is doing what it is supposed to do, but for some reason the script that is executing isn't doing what you want it to do, which really isn't something we can help with. I think you need to raise this issue on an AWS support forum.

**Comment by pqarmitage** [comment]
To try and see what is happening when master.sh is executing, you could try modifying master.sh  as follows:
```
#!/bin/bash

set -x

(
EIP=13.235.X.x
INSTANCE_ID=i-0098bf692ac8xxxxxx
/root/.local/bin/aws ec2 disassociate-address --public-ip $EIP
/root/.local/bin/aws ec2 associate-address --public-ip $EIP --instance-id $INSTANCE_ID
) >>/tmp/master.log 2>&1

/tmp/master.log should then show you each command being executed and the results.
```

**Comment by pqarmitage** [comment]
Issue #1322 appears to also experiencing a problem of scripts not running. It appears that in that case it is an SElinux problem when running keepalived from systemd.
