### ISSUE TITLE
vrrp_script exit with status 1 but script exits 0

### ISSUE THREAD

**Issue by jwh331** [acassen/keepalived#1322]
Hello

I am using keepalived as failover between two daemons.

I wrote a simple script which is checking specific TCP port.

If I execute that script on terminal, it returns success.

but when I execute through keepalived vrrp_script, it always returns fail(exit code 1).
(log at /var/log/messages:  Keepalived_vrrp[13388]: /etc/keepalived/checkMq.sh exited with status 1)

What should I check more?
If somebody finds out my bad, I am really appreciated.

[Keepalived version]
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

[OS info.]
CentOS Linux release 7.6.1810 (Core), x64

and script and keepalived configurations.

=========== This is my script (checkMq.sh at master) ===========
#!/bin/bash

SERVER=localhost
PORT=1883

checkingport=`echo "quit" | telnet $SERVER $PORT | grep "Escape character is"`

result="$?"

if [ $result -eq 0 ]; then
  echo "awesome!"
  exit 0
else
  echo "awwwww.."
  exit 1
fi

=========== and this is my keepalived config. (master) ===========
! Configuration File for keepalived

global_defs {
   notification_email {
	#disabled
   }
   script_user root root
   enable_script_security
}

vrrp_script pchecker {
    script /etc/keepalived/checkMq.sh
    interval 2
    timeout 10
    weight -55
    rise 2
    fall 3
    user root root
}

vrrp_instance VI_1 {
    state MASTER
    interface enp1s0
    virtual_router_id 51
    priority 150
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 123499
    }
    virtual_ipaddress {
        192.168.0.70
    }
    track_script {
        pchecker
    }
}

Thank for your help in advance.

and sorry for my bad English :-]

**Comment by pqarmitage** [comment]
To see what is happening you could try modifying your script as follows:
```
#!/bin/bash

set -x

(
SERVER=localhost
PORT=400

checkingport=`echo "quit" | telnet $SERVER $PORT | grep "Escape character is"`

result="$?"

if [ $result -eq 0 ]; then
echo "awesome!"
exit 0
else
echo "awwwww.."
exit 1
fi
) >> /tmp/checkMq.log 2>&1
```

/tmp/checkMq.log should show each command being executed and the results.

**Comment by pqarmitage** [comment]
I forgot to say that the scripts works fine for me and returns 0 after a successful connection.

One way I test this sort of connectivity issue is I have a test program tcp_server (source in keepalived tree at test/tcp_server.c) which allows you to run a very simple tcp server that reports whenever a connection is established to it (tcp_server -h shows options, for example -p for port to listen on). For testing purposes you could try connecting to that rather than the Mq server.

**Comment by jwh331** [comment]
Thanks! you gave me a good hint..
I changed script and run again, It does not create any logs.
But execute it by myself, It create logs automatically.. weird.

It looks like keepalived cannot execute part of scripts.. I'll find more about settings.

**Comment by pqarmitage** [comment]
It doesn't seem as though the keepalived code has a problem since it works for me. Are you running using some sort of container? A description of your environment might be helpful to understand what might be the cause of the problem.

**Comment by jwh331** [comment]
No, I don't use any containers. just pure OS.

I found how to resolve this issue but cannot understand why.
When I turn on keepalived, I use "systemctl start keepalived" command. then It doesn't works.
But with simple "keepalived" command, finally It works well!
solution from here: https://serverfault.com/questions/709428/track-script-doesnt-work-after-keepalived-update
Anyway, thanks for your help!
now I should find some reasons and close later. haha

**Comment by pqarmitage** [comment]
I'll try running this under systemd later and see what I get. It could be something to do with the PATH environment is different when running under systemd, or some other environment variable. Alternatively it could be an SElinux issue.

Reading the link above, it appears that it is an SElinux configuration issue.

**Comment by pqarmitage** [comment]
I have now run keepalived with the relevant SElinux security context and I get the following reports in the system log:
```
Jun 20 14:28:14 host.domain python3[775]: SELinux is preventing keepalived from create access on the netlink_connector_socket Unknown.

     *****  Plugin catchall (100. confidence) suggests   **************************

     If you believe that keepalived should be allowed create access on the Unknown netlink_connector_socket by default.
     Then you should report this as a bug.
     You can generate a local policy module to allow this access.
     Do
     allow this access for now by executing:
     # ausearch -c 'keepalived' --raw | audit2allow -M my-keepalived1
     # semodule -X 300 -i my-keepalived.pp

Jun 20 14:28:24 host.domain setroubleshoot[775]: SELinux is preventing keepalived from setattr access on the file 1322.sh. For complete SELinux messages run: sealert -l c9959bda-fa49-4a3b-9a8d-575e2c1ac69c
Jun 20 14:28:24 host.domain python3[775]: SELinux is preventing keepalived from setattr access on the file 1322.sh.

     *****  Plugin catchall_labels (83.8 confidence) suggests   *******************

     If you want to allow keepalived to have setattr access on the 1322.sh file
     Then you need to change the label on 1322.sh
     Do
     # semanage fcontext -a -t FILE_TYPE '1322.sh'
     where FILE_TYPE is one of the following: keepalived_var_run_t, snmpd_var_lib_t.
     Then execute:
     restorecon -v '1322.sh'


     *****  Plugin catchall (17.1 confidence) suggests   **************************

     If you believe that keepalived should be allowed setattr access on the 1322.sh file by default.
     Then you should report this as a bug.
     You can generate a local policy module to allow this access.
     Do
     allow this access for now by executing:
     # ausearch -c 'keepalived' --raw | audit2allow -M my-keepalived1
     # semodule -X 300 -i my-keepalived.pp

Jun 20 14:28:33 host.domain audit[923]: AVC avc:  denied  { name_connect } for  pid=923 comm="telnet" dest=1833 scontext=system_u:system_r:keepalived_t:s0 tcontext=system_u:object_r:reserved_port_t:s0 tclass=tcp_socket permissive=0
Jun 20 14:28:34 host.domain setroubleshoot[775]: SELinux is preventing telnet from name_connect access on the tcp_socket port 1833 For complete SELinux messages run: sealert -l c0bf40d8-fe8c-46f0-8694-74e4a125457b
Jun 20 14:28:34 host.domain python3[775]: SELinux is preventing telnet from name_connect access on the tcp_socket port 1833.

     *****  Plugin connect_ports (92.2 confidence) suggests   *********************

     If you want to allow telnet to connect to network port 1833
     Then you need to modify the port type.
     Do
     # semanage port -a -t PORT_TYPE -p tcp 1833
         where PORT_TYPE is one of the following: agentx_port_t, connlcli_port_t, dns_port_t, dnssec_port_t, http_port_t, kerberos_port_t, mysqld_port_t, ocsp_port_t, smtp_port_t, snmp_port_t, squid_port_t.

     *****  Plugin catchall_boolean (7.83 confidence) suggests   ******************

     If you want to allow nis to enabled
     Then you must tell SELinux about this by enabling the 'nis_enabled' boolean.

     Do
     setsebool -P nis_enabled 1

     *****  Plugin catchall (1.41 confidence) suggests   **************************

     If you believe that telnet should be allowed name_connect access on the port 1833 tcp_socket by default.
     Then you should report this as a bug.
     You can generate a local policy module to allow this access.
     Do
     allow this access for now by executing:
     # ausearch -c 'telnet' --raw | audit2allow -M my-telnet
     # semodule -X 300 -i my-telnet.pp
```
Once I move the script (1322.sh) to /usr/libexec/keepalived, then it changes the errors to:
```
Jun 20 14:52:44 host.domain audit[1807]: AVC avc:  denied  { create } for  pid=1807 comm="keepalived1" scontext=system_u:system_r:keepalived_t:s0 tcontext=system_u:system_r:keepalived_t:s0 tclass=netlink_connector_socket permissive=0
Jun 20 14:52:44 host.domain audit[1809]: AVC avc:  denied  { setattr } for  pid=1809 comm="keepalived1" name="1322.sh" dev="dm-0" ino=1588329 scontext=system_u:system_r:keepalived_t:s0 tcontext=unconfined_u:object_r:etc_t:s0 tclass=file permissive=0
Jun 20 14:52:44 host.domain audit[1820]: AVC avc:  denied  { name_connect } for  pid=1820 comm="telnet" dest=1833 scontext=system_u:system_r:keepalived_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=tcp_socket permissive=0
Jun 20 14:52:49 host.domain setroubleshoot[1835]: SELinux is preventing keepalived1 from create access on the netlink_connector_socket Unknown. For complete SELinux messages run: sealert -l dad04adb-f66b-459b-8cc6-7004917fb328
Jun 20 14:52:49 host.domain python3[1835]: SELinux is preventing keepalived1 from create access on the netlink_connector_socket Unknown.

      *****  Plugin catchall (100. confidence) suggests   **************************

      If you believe that keepalived1 should be allowed create access on the Unknown netlink_connector_socket by default.
      Then you should report this as a bug.
      You can generate a local policy module to allow this access.
      Do
      allow this access for now by executing:
      # ausearch -c 'keepalived1' --raw | audit2allow -M my-keepalived1
      # semodule -X 300 -i my-keepalived1.pp


      *****  Plugin catchall (100. confidence) suggests   **************************

      Then you should report this as a bug.
      You can generate a local policy module to allow this access.
      Do
      allow this access for now by executing:
      # ausearch -c 'keepalived1' --raw | audit2allow -M my-keepalived1
      # semodule -X 300 -i my-keepalived1.pp

Jun 20 14:53:00 host.domain python3[1835]: SELinux is preventing keepalived1 from setattr access on the file 1322.sh.

      *****  Plugin catchall_labels (83.8 confidence) suggests   *******************

      If you want to allow keepalived1 to have setattr access on the 1322.sh file
      Then you need to change the label on 1322.sh
      Do
      # semanage fcontext -a -t FILE_TYPE '1322.sh'
      where FILE_TYPE is one of the following: keepalived_var_run_t, snmpd_var_lib_t.
      Then execute:
      restorecon -v '1322.sh'


      *****  Plugin catchall (17.1 confidence) suggests   **************************

      If you believe that keepalived1 should be allowed setattr access on the 1322.sh file by default.
      Then you should report this as a bug.
      You can generate a local policy module to allow this access.
      Do
      allow this access for now by executing:
      # ausearch -c 'keepalived1' --raw | audit2allow -M my-keepalived1
      # semodule -X 300 -i my-keepalived1.pp

Jun 20 14:53:09 host.domain setroubleshoot[1835]: SELinux is preventing telnet from name_connect access on the tcp_socket port 1833. For complete SELinux messages run: sealert -l a0bc9eb0-969c-4b0f-8ca1-69db1e34ba45
Jun 20 14:53:09 host.domain python3[1835]: SELinux is preventing telnet from name_connect access on the tcp_socket port 1833. 

      *****  Plugin connect_ports (92.2 confidence) suggests   *********************

      If you want to allow telnet to connect to network port 1833
      Then you need to modify the port type.
      Do
      # semanage port -a -t PORT_TYPE -p tcp 1833
          where PORT_TYPE is one of the following: agentx_port_t, connlcli_port_t, dns_port_t, dnssec_port_t, http_port_t, kerberos_port_t, mysqld_port_t, ocsp_port_t, smtp_port_t, snmp_port_t, squid_port_t.

      *****  Plugin catchall_boolean (7.83 confidence) suggests   ******************

      If you want to allow nis to enabled
      Then you must tell SELinux about this by enabling the 'nis_enabled' boolean.

      Do
      setsebool -P nis_enabled 1

      *****  Plugin catchall (1.41 confidence) suggests   **************************

      If you believe that telnet should be allowed name_connect access on the port 1833 tcp_socket by default.
      Then you should report this as a bug.
      You can generate a local policy module to allow this access.
      Do
      allow this access for now by executing:
      # ausearch -c 'telnet' --raw | audit2allow -M my-telnet
      # semodule -X 300 -i my-telnet.pp
```
I suggest when you run keepalived and the notify_master script is not working, you look in the system log to see if you are getting any relevant audit/selinux messages.

I think if you put any scripts you want to run in the /usr/libexec/keepalived directory, then SElinux should allow them to run.

So I think the solution is to follow the guidance given in the system log for adding the necessary SELinux permissions to your system.

**Comment by jwh331** [comment]
I checked /var/log/audit/audit.log too.
It shows 
`...type=AVC msg=audit(1561076144.880:71636): avc:  denied  { append } for  pid=5156 comm="ccheckMq.sh" name="log.log" dev="dm-0" ino=837554 scontext=system_u:system_r:keepalived_t:s0 tcontext=unconfined_u:object_r:etc_t:s0 tclass=file permissive=0
...`
and I move scripts to /usr/libexec/keepalived/ directory,
and use ausearch and semodule command.
finally run with systemctl. It works well!
I should check selinux log when something goes wrong..

**Comment by rdnkrkmz** [comment]
This is quite old issue, however today I hit the same.
First here is version (runs on VM)
```
[root@localhost ~]# keepalived -v
Keepalived v2.1.5 (07/13,2020)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.0
Running on Linux 4.18.0-553.8.1.el8_10.x86_64 #1 SMP Tue Jul 2 05:18:08 PDT 2024
```

When I start `keepalived` with `systemctl start keepalived` then my check script falsely return `0` instead of `1` but when I start it from command like as `[root@localhost ~]# keepalived -D -l -f /etc/keepalived/keepalived.conf` return codes now are correct. 

Additionally, I changed the `/usr/lib/systemd/system/keepalived.service` file and put `ExecStart=/usr/sbin/keepalived -D -l -f /etc/keepalived/keepalived.conf` but no luck.

Is not it weird even nowadays?

Actually I am wondering what is your resolution for this?

Any clue is appreciated.

**Comment by pqarmitage** [comment]
This could well be an SELinux policy/permissions issue. When you run keepalived from the command line it runs under a different SELinux context from when it is run by systemd.
