### ISSUE TITLE
Keepalived_healthcheckers exited due to segmentation fault

### ISSUE THREAD

**Issue by tmcsween** [acassen/keepalived#1323]
I'm running keepalived inside a docker container under supervisord. If I restart keepalived using  `/usr/bin/supervisorctl -c /etc/supervisor/supervisord.conf signal HUP keepalived`, Keepalived_healthcheckers seg faults, and all the IPVS connections drop.

Wed Jun 19 11:09:15 2019: Reloading ...
Wed Jun 19 11:09:15 2019: Opening file '/etc/keepalived/keepalived.conf'.
Wed Jun 19 11:09:15 2019: Reloading
Wed Jun 19 11:09:15 2019: Opening file '/etc/keepalived/keepalived.conf'.
Wed Jun 19 11:09:15 2019: Assigned address 192.169.22.20 for interface ens224
Wed Jun 19 11:09:15 2019: Assigned address fe80::250:56ff:fe9e:9fd9 for interface ens224
Wed Jun 19 11:09:15 2019: (Gx6) the first IPv6 VIP address must be link local
Wed Jun 19 11:09:15 2019: (Gx4) ip address 192.169.22.50/32 dev ens224, no longer exist
Wed Jun 19 11:09:15 2019: (Gx4) setting VIPs.
Wed Jun 19 11:09:15 2019: (Gx6) Entering BACKUP STATE (init)
Wed Jun 19 11:09:15 2019: VRRP sockpool: [ifindex(4), family(IPv4), proto(112), unicast(0), fd(12,13)]
Wed Jun 19 11:09:15 2019: VRRP sockpool: [ifindex(4), family(IPv6), proto(112), unicast(0), fd(14,15)]
Wed Jun 19 11:09:15 2019: Reloading
Wed Jun 19 11:09:15 2019: Got SIGHUP, reloading checker configuration
Wed Jun 19 11:09:15 2019: Opening file '/etc/keepalived/keepalived.conf'.
Wed Jun 19 11:09:15 2019: SECURITY VIOLATION - check scripts are being executed but script_security not enabled.
Wed Jun 19 11:09:15 2019: Reinitializing ipvs
Wed Jun 19 11:09:15 2019: Keepalived_healthcheckers exited due to segmentation fault (SIGSEGV).
Wed Jun 19 11:09:15 2019:   Please report a bug at https://github.com/acassen/keepalived/issues
Wed Jun 19 11:09:15 2019:   and include this log from when keepalived started, a description
Wed Jun 19 11:09:15 2019:   of what happened before the crash, your configuration file and the details below.
Wed Jun 19 11:09:15 2019:   Also provide the output of keepalived -v, what Linux distro and version
Wed Jun 19 11:09:15 2019:   you are running on, and whether keepalived is being run in a container or VM.
Wed Jun 19 11:09:15 2019:   A failure to provide all this information may mean the crash cannot be investigated.
Wed Jun 19 11:09:15 2019:   If you are able to provide a stack backtrace with gdb that would really help.
Wed Jun 19 11:09:15 2019:   Source version 2.0.16 , git commit v2.0.15-96-g4d492740+
Wed Jun 19 11:09:15 2019:   Built with kernel headers for Linux 4.4.179
Wed Jun 19 11:09:15 2019:   Running on Linux 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019
Wed Jun 19 11:09:15 2019:   Command line: '/usr/sbin/keepalived' '--dont-fork' '--log-console' '--log-detail'
Wed Jun 19 11:09:15 2019:   configure options: --prefix=/usr
Wed Jun 19 11:09:15 2019:   Config options: LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING EINTR_CHECK
Wed Jun 19 11:09:15 2019:   System options: PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API
Wed Jun 19 11:09:15 2019:                   LIBNL3 RTA_ENCAP RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP
Wed Jun 19 11:09:15 2019:                   FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS RTA_VIA FRA_OIFNAME
Wed Jun 19 11:09:15 2019:                   IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA
Wed Jun 19 11:09:15 2019:                   NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK
Wed Jun 19 11:09:15 2019:                   IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC
Wed Jun 19 11:09:15 2019:                   IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE
Wed Jun 19 11:09:15 2019:                   INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK
Wed Jun 19 11:09:15 2019: Healthcheck child process(6002) died: Respawning
Wed Jun 19 11:09:15 2019: Starting Healthcheck child process, pid=7605
Wed Jun 19 11:09:15 2019: Opening file '/etc/keepalived/keepalived.conf'.
Wed Jun 19 11:09:15 2019: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Wed Jun 19 11:09:15 2019: SECURITY VIOLATION - check scripts are being executed but script_security not enabled.
Wed Jun 19 11:09:15 2019: Initializing ipvs
Wed Jun 19 11:09:15 2019: IPVS cmd IP_VS_SO_SET_ADD(1154) error: Service already exists(17)
Wed Jun 19 11:09:15 2019: IPVS cmd IP_VS_SO_SET_ADDDEST(1159) error: Destination already exists(17)
Wed Jun 19 11:09:15 2019: IPVS cmd IP_VS_SO_SET_ADDDEST(1159) error: Destination already exists(17)
Wed Jun 19 11:09:15 2019: Gained quorum 1+0=1 <= 2 for VS [192.169.22.50]:tcp:3868
Wed Jun 19 11:09:15 2019: IPVS cmd IP_VS_SO_SET_ADD(1154) error: Service already exists(17)
Wed Jun 19 11:09:15 2019: IPVS cmd IP_VS_SO_SET_ADDDEST(1159) error: Destination already exists(17)
Wed Jun 19 11:09:15 2019: IPVS cmd IP_VS_SO_SET_ADDDEST(1159) error: Destination already exists(17)
Wed Jun 19 11:09:15 2019: Gained quorum 1+0=1 <= 2 for VS [2001:db8:2040:202::50]:tcp:3868
Wed Jun 19 11:09:15 2019: Activating healthchecker for service [192.169.22.13]:tcp:3868 for VS [192.169.22.50]:tcp:3868
Wed Jun 19 11:09:15 2019: Activating healthchecker for service [192.169.22.14]:tcp:3868 for VS [192.169.22.50]:tcp:3868
Wed Jun 19 11:09:15 2019: Activating healthchecker for service [2001:db8:2040:202::13]:tcp:3868 for VS [2001:db8:2040:202::50]:tcp:3868
Wed Jun 19 11:09:15 2019: Activating healthchecker for service [2001:db8:2040:202::14]:tcp:3868 for VS [2001:db8:2040:202::50]:tcp:3868
Wed Jun 19 11:09:16 2019: Misc check for [[192.169.22.13]:tcp:3868 VS [192.169.22.50]:tcp:3868] by [/usr/local/bin/ipvs-service-state-tracking] succeeded.
Wed Jun 19 11:09:17 2019: Misc check for [[192.169.22.14]:tcp:3868 VS [192.169.22.50]:tcp:3868] by [/usr/local/bin/ipvs-service-state-tracking] succeeded.
Wed Jun 19 11:09:17 2019: Misc check for [[2001:db8:2040:202::14]:tcp:3868 VS [2001:db8:2040:202::50]:tcp:3868] by [/usr/local/bin/ipvs-service-state-tracking] succeeded.
Wed Jun 19 11:09:18 2019: Misc check for [[2001:db8:2040:202::13]:tcp:3868 VS [2001:db8:2040:202::50]:tcp:3868] by [/usr/local/bin/ipvs-service-state-tracking] succeeded.

[keepalived.conf.txt](https://github.com/acassen/keepalived/files/3306510/keepalived.conf.txt)

**Comment by pqarmitage** [comment]
@tmcsween Many thanks for reporting this. This issue was resolved by commit 50382b8.

**Comment by pqarmitage** [comment]
@tmcsween Many thanks for reporting this. This issue was resolved by commit 50382b8.
