### ISSUE TITLE
/etc/keepalived/nginx_check.sh exited with status 127

### ISSUE THREAD

**Issue by ICannerxy** [acassen/keepalived#1325]
hello everyone,I have a trouble on keepalived + nginx .
I use centos7 yum install nginx and keepalived.
When I set up the environment to prepare for the test.
I'll check the keepalived log after I killed the nginx process.
Here's the log information.
--------------------------
.........
Jun 21 01:31:07 localhost Keepalived_vrrp[43346]: VRRP_Instance(VI_1) Changing effective priority from 100 to 80
Jun 21 01:31:09 localhost Keepalived_vrrp[43346]: /etc/keepalived/nginx_check.sh exited with status 127
Jun 21 01:31:11 localhost Keepalived_vrrp[43346]: /etc/keepalived/nginx_check.sh exited with status 127
Jun 21 01:31:13 localhost Keepalived_vrrp[43346]: /etc/keepalived/nginx_check.sh exited with status 127
Jun 21 01:31:15 localhost Keepalived_vrrp[43346]: /etc/keepalived/nginx_check.sh exited with status 127
........
---------------------------
My nginx_check.sh is as follows:
#!/bin/bash
counter=$(ps -C nginx --no-heading|wc -l)
if [ "${counter}" = "0" ]; then
        systemctl start nginx
fi
===========================================
my keepalived.conf is as follows:

! Configuration File for keepalived

global_defs {
   router_id LVS_DEVEL
}

vrrp_script chk_nginx {
        script "/etc/keepalived/nginx_check.sh"
        interval 2
        weight -20
}

vrrp_instance VI_1 {
    state MASTER
    interface ens33
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    track_script {
        chk_nginx
    }
    virtual_ipaddress {
        192.168.92.100 
    }
}

Help me,pls. I've been plagued by this question all day.

**Comment by pqarmitage** [comment]
@ICannerxy Could you please provide all the information requested in the template for filing a new issue; without that information we cannot diagnose the problem; for example due to not knowing the version of keepalived that you are using we can't tell if the script would be invoked via execve() or system(), but please note that other information is requested as well.

It is worth noting that system() can return 127 if it is unable to execute a shell in the child process. See issues #1320 and #1322 for a possible reason.

**Comment by jwh331** [comment]
Check these..
- run shell script manually.. Does it works well?
- execute privilege of script

**Comment by ICannerxy** [comment]
Thank you very much.
shell script is work well.
I found out what the problem was.When I use `systemctl start keepalived` . The program can monitor my script but it won't execute it.Error information when viewing logs
> .../etc/keepalived/nginx_check.sh exited withstatus 127
When I Everything's fine when I execute the command `/usr/sbin/keepalived` directly.

**Comment by ICannerxy** [comment]
command `systemctl start keepalived` is wrong
command `/us/sbin/keepalived` is fine

**Comment by pqarmitage** [comment]
Please see issue #1322. This looks like another SElinux issue.

**Comment by ICannerxy** [comment]
OK,Thank you.
