### ISSUE TITLE
keepalived-1.3.5 send ipv6 unsolicited neighbour advertisement and the NA packet router flag is 0.

### ISSUE THREAD

**Issue by UnknowSelf** [acassen/keepalived#1330]
My keepalived config file 
vrrp_script chk_conntrack_monitor {
    ...
}
vrrp_instance VR_2 {
    state BACKUP
    interface ha-67f1550f-87
    virtual_router_id 2
    priority 50
    garp_master_repeat 5
    garp_master_refresh 10
    nopreempt
    advert_int 2
    track_interface {
        ha-67f1550f-87
    }
    virtual_ipaddress {
        169.254.0.2/24 dev ha-67f1550f-87
    }
    virtual_ipaddress_excluded {
        10.0.0.1/24 dev qr-8edc679c-4d
        10.0.1.1/24 dev qr-d22c0173-ac
        fe80::f816:3eff:fe9a:79c6/64 dev qr-8edc679c-4d scope link
        fe80::f816:3eff:fea8:9d38/64 dev qr-d22c0173-ac scope link
        fe80::f816:3eff:fee6:a3e8/64 dev qg-d7f662b6-c3 scope link
        2001:1:1:b0a:200::1/72 dev qr-b427408e-55
        2001:1:1:b0a:300::1/72 dev qr-b427408e-55
        100.66.0.117/16 dev qg-d7f662b6-c3
    }
    virtual_routes {
        2001:1:1::/48 dev qg-d7f662b6-c3 scope link
        100.100.0.0/16 dev qg-d7f662b6-c3 scope link
        fe80::/56 dev qg-d7f662b6-c3 scope link
    }
    track_script {
        chk_conntrack_monitor
    }
    ...
}

The netns's ipv6 forwarding is enable, all the interface send ipv6 unsolicited neighbour advertisement packet and the router flag of packet is 0. How can I  make the ipv6 NA packet router flag is 1,or disalbe ipv6 neighbour advertisement?
@gudmundur @rubenk @ncopa @costela @sim-

**Comment by UnknowSelf** [comment]
@pqarmitage
@acassen 
@vincentbernat 
@andriyanov

**Comment by pqarmitage** [comment]
In version 1.3.5, if /proc/sys/net/ipv6/conf/ha-67f1550f-87/forwarding is set, then the router flag should be set (see setting and use of ifp->gna_router in the source code).

**Comment by acassen** [comment]
can add that 1.3.5 is way too old.

**Comment by pqarmitage** [comment]
This conforms with what Linux itself does - see [kernel documentation and comments](https://unix.stackexchange.com/questions/348533/is-net-ipv6-conf-all-forwarding-1-equivalent-to-enabling-forwarding-for-all-indi)

**Comment by UnknowSelf** [comment]
> In version 1.3.5, if /proc/sys/net/ipv6/conf/ha-67f1550f-87/forwarding is set, then the router flag should be set (see setting and use of ifp->gna_router in the source code).

I confirmed the interface ipv6 forwarding is 1, and the ifp->gna_router in source code:
static void vrrp_state_become_master(vrrp_t * vrrp)
{
    ...
    /* remotes neighbour update */
	if (vrrp->family == AF_INET6) {
		/* Refresh whether we are acting as a router for NA messages */
		ifp = IF_BASE_IFP(vrrp->ifp);
		ifp->gna_router = get_ipv6_forwarding(ifp);
	}
    ...
}
How can I make the ifp->gna_router = 1?

**Comment by UnknowSelf** [comment]
Hurry, wait online！

**Comment by pqarmitage** [comment]
@UnknowSelf I'm not clear what your previous comment meant?

I discovered that keepalived was only looking at the IPv6 forwarding state of the interface that a VRRP instance was configured on, rather than looking at the interface that a VIP or eVIP is configured on.
Commit 524d34a resolves that, and with the configuration above the Router flag in the NA message now follows the configuration of the interface that the address is configured on.

You will need to update to the latest code to incorporate this fix (v2.0.17 + this commit).

**Comment by UnknowSelf** [comment]
> @UnknowSelf I'm not clear what your previous comment meant?
> 
> I discovered that keepalived was only looking at the IPv6 forwarding state of the interface that a VRRP instance was configured on, rather than looking at the interface that a VIP or eVIP is configured on.
> Commit [524d34a](https://github.com/acassen/keepalived/commit/524d34aadd5f874a02664a9730dbe9309c0d346a) resolves that, and with the configuration above the Router flag in the NA message now follows the configuration of the interface that the address is configured on.
> 
> You will need to update to the latest code to incorporate this fix (v2.0.17 + this commit).

Thank you! That's I want.
