### ISSUE TITLE
keepalived in non default vrf hangs with vrrp configs

### ISSUE THREAD

**Issue by msridhar87** [acassen/keepalived#1332]
Keepalived in a non default vrf hangs with the below trace.

[New LWP 2491]
[New LWP 2492]
[New LWP 2494]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x000055be8f122e3c in ?? ()
(gdb) bt
#0  0x000055be8f122e3c in ?? ()
#1  0x000055be8f12340e in thread_cleanup_master ()
#2  0x000055be8f0fb739 in ?? ()
#3  0x000055be8f124b15 in launch_scheduler ()
#4  0x000055be8f0fb991 in start_vrrp_child ()
#5  0x000055be8f0e7d70 in keepalived_main ()
#6  0x00007ff4e7a0b2e1 in __libc_start_main (main=0x55be8f0e69b0 <main>,
    argc=4, argv=0x7ffc07c60668, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7ffc07c60658)
    at ../csu/libc-start.c:291
#7  0x000055be8f0e69ea in _start ()

After this keepalived does not receive any signal

**Comment by pqarmitage** [comment]
@msridhar87 - Can you please resubmit this issue using the bug report template. Without all the information being requested we simply do not have sufficient information to attempt to diagnose the problem.
