### ISSUE TITLE
Multicast requests waste IDC room bandwidth

### ISSUE THREAD

**Issue by guozilong110** [acassen/keepalived#1338]
**Describe what you need help/support for**
A clear and concise description of what you need help with.

Send a large number of multicast 224.0.0.81:8848, resulting in each server of IDC will receive packets.
The high concurrency of LVS results in a significant waste of bandwidth.
 

**Keepalived version**
Output of `keepalived -v` (a later version of keepalived might be needed).
ubuntu18.04 
Keepalived v2.0.17 (06/25,2019)
 
**Configuration file:**
Full copy of your configuration file, obfuscated if necessary to protect passwords and IP addresses
```
global_defs {
        router_id km_lvs03
        lvs_sync_daemon ens3 VI_2
}

vrrp_instance VI_2 {
        state MASTER
        dont_track_primary
        interface ens3
        track_interface {
                ens3
        }
        garp_master_delay 2
        mcast_src_ip 172.16.100.68
        nopreempt
        virtual_router_id 84
        priority 100
        advert_int 1
        authentication {
                auth_type PASS
                auth_pass 9999
        }
        virtual_ipaddress {
                172.16.100.60 dev ens3
        }
}
virtual_server  172.16.100.60 80 {
        delay_loop 3
        lb_algo wrr
        lb_kind DR
        nat_mask 255.255.255.0
#       persistence_timeout 50
        protocol TCP

        real_server 172.16.100.71 80 {
                weight 3
                TCP_CHECK {
                        connect_timeout 3
                        nb_get_retry 3
                        delay_before_retry 3
                        connect_port 80
                }
        }
        real_server 172.16.100.72 80 {
                weight 3
                TCP_CHECK {
                        connect_timeout 3
                        nb_get_retry 3
                        delay_before_retry 3
                        connect_port 80
                }
        }
}
```

**Comment by pqarmitage** [comment]
Traffic to 224.0.0.81:8848 is generated by the LVS sync daemon in the kernel, which your configuration has set up. 

Whilst keepalived has set up the sync daemon in accordance with the configuration, it cannot control the traffic to 224.0.0.81 itself; that is a matter for the sync daemon and the rate of establishing and dropping connections handled by LVS.
