### ISSUE TITLE
status_code group not working under 2.0.17

### ISSUE THREAD

**Issue by aholtzmbw** [acassen/keepalived#1350]
**Describe the bug**
We have an HTTP_GET url check on a site that returns a 302 Document Moved response.  Trying to setup a status_code option of something like "status_code 2xx 3xx" or even just "status_code 3xx" does not work.  I have to use "status_code 302" for the check to succeed.

**To Reproduce**
Setup an HTTP_GET url check on a site that returns any status code but use a status_code group item as the configuration option.  I have not tested if "2xx" works but I know that "3xx" does not.

**Expected behavior**
The HTTP_GET check should pass when using the status_code group.

**Keepalived version**
Keepalived v2.0.17 (06/27,2019), git commit v2.0.17-8-g836230e6

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.15.18
Running on Linux 5.0.0-19-generic #20~18.04.1-Ubuntu SMP Thu Jun 20 12:17:14 UTC 2019

configure options: --enable-json --enable-snmp --enable-snmp-vrrp --enable-snmp-checker --enable-sha1 --enable-strict-config-checks --enable-regex --prefix=/usr

Config options:  STRICT_CONFIG LIBIPTC LIBIPSET_DYNAMIC NFTABLES LVS REGEX VRRP VRRP_AUTH JSON OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_VRRP SNMP_CHECKER

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Distro (please complete the following information):**
Linux test-keepalived-1 5.0.0-19-generic #20~18.04.1-Ubuntu SMP Thu Jun 20 12:17:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I have also confirmed this isn't working under Centos 7.5 with the same git pull version.

**Configuration file:**
Relevant config:
    real_server 10.1.1.187 80 {
        HTTP_GET {
                url {
                        path /webmail/
                        digest 12493328522dfdaf22540e9dc516ce16
                        status_code 3xx
                }
                connect_timeout 10
                retry 1
                delay_before_retry 1
                connect_port 80
        }
    }

Changing the line to "status_code 302" resolves the issue in my case.

**System Log entries**
When it fails:
Keepalived_healthcheckers[22262]: HTTP_CHECK on service [10.1.1.187]:tcp:80 failed after 1 retry.

**Did keepalived coredump?**
No

**Additional context**
Output from a curl -vvv to that URL:
* Trying 10.1.1.187...
* TCP_NODELAY set
* Connected to 10.1.1.187 (10.1.1.187) port 80 (#0)
> GET /webmail/ HTTP/1.1
> Host: 10.1.1.187
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 302 Document Moved
< Expires: Tue, 09 Jul 2029 03:55:28 GMT
< Connection: close
< Server: (2019-01-21) RHEL7 x64
< Date: Tue, 09 Jul 2019 03:55:28 GMT
< Location: https://10.1.1.187/webmail/
< Content-Type: text/html
< Content-Length: 612
<
* Closing connection 0

**Comment by aholtzmbw** [comment]
I believe that I may have misread the Changelog in comparison with the documentation.

I see I can use "status_code 200-299 300-399" to achieve the results I wanted.  I will be closing this issue unless the 2xx and 3xx are truly meant to be operational.

**Comment by pqarmitage** [comment]
@aholtzmbw The original patch supported 2xx etc, but I decided that specifying a range was more flexible, and so I implemented that.

The ChangeLog a few lines below the entry you referenced states:
> Change how http status codes are configured
          Commit c7c23a2 - "support http status_code group" allowed status codes to
          be specified as 2xx, meaning 200-299. This commit changes the configuration
          so that 2xx etc is no longer used, but status code ranges can be specified,
          e.g. status_code 150 180-189 200-299 503 510-520

Apologies for any confusion caused.

**Comment by aholtzmbw** [comment]
No problem - thanks for the clarification!
