### ISSUE TITLE
BFD_Instance checker pipe write() error Resource temporarily unavailable

### ISSUE THREAD

**Issue by Mint-M** [acassen/keepalived#1351]
**Describe the issue**
Keepalived logs sometimes show 'BFD_Instance checker pipe write() error Resource temporarily unavailable' when BFD_Instance state changes.

Keepalived_bfd[666]: BFD_Instance(aaa) Detection time is 5000 ms (was 500 ms)
Keepalived_bfd[666]: BFD_Instance(aaa) --------------< Session parameters >-------------
Keepalived_bfd[666]: BFD_Instance(aaa)        min_tx  min_rx  tx_intv  mult  detect_time
Keepalived_bfd[666]: BFD_Instance(aaa) local    1000     100      100     5          500
Keepalived_bfd[666]: BFD_Instance(aaa) remote    100     100      100     5          500
Keepalived_bfd[666]: BFD_Instance(aaa) Detection time is 500 ms (was 5000 ms)
Keepalived_bfd[666]: BFD_Instance(aaa) Entering Up state
Keepalived_bfd[666]: BFD_Instance(aaa) Starting poll sequence
**Keepalived_bfd[666]: BFD_Instance(aaa) checker pipe write() error Resource temporarily unavailable**
Keepalived_vrrp[665]: Received BFD event: instance aaa is in state Up (delivered in 107 usec)

**To Reproduce**
Activate the bfd feature and make its state change.

**Expected behavior**
Such error information are not printed.

**Keepalived version**
Keepalived v2.0.16 (unknown)

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.0.9
Running on Linux 5.1.12-300.fc30.x86_64 #1 SMP Wed Jun 19 15:19:49 UTC 2019

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-snmp-reply-v3-for-v2 --with-init=systemd --enable-bfd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LIBIPTC LIBIPSET_DYNAMIC NFTABLES LVS VRRP VRRP_AUTH BFD OLD_CHKSUM_COMPAT FIB_ROUTING EINTR_CHECK

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Distro (please complete the following information):**
5.1.12-300.fc30.x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
A vm running with libvirt.

**Configuration file:**
global_defs {
    router_id aaa
    vrrp_mcast_group4 224.0.0.100
}

bfd_instance bbb {
    neighbor_ip 10.0.1.11
    source_ip 10.1.1.11
    min_tx 100
    min_rx 100
    max_hops 255
}

vrrp_instance vrrp-ins {
    state BACKUP
    interface eth0
    virtual_router_id 166
    priority 100
    advert_int 1
    virtual_ipaddress {
       10.1.1.1/16 dev eth0
    }
    track_bfd {
        bbb
    }
}

**Notify and track scripts**
No

**System Log entries**
There were too many logs after keepalived was started due to the changes of state.
It has run without such error for nine days.
After the BFD instance state was changed for one time after nine days ,such error was shown everytime when the state changed.
BFD_Instance(aaa) Expired after 500 ms (200 usec overdue)
BFD_Instance(aaa) Entering Down state (Local diagnostic - Control Detection Time Expired, Remote diagnostic - No Diagnostic)
BFD_Instance(aaa) checker pipe write() error Resource temporarily unavailable
Received BFD event: instance aaa is in state Down (delivered in 166 usec)

**Did keepalived coredump?**
No

**Additional context**
The output of ulimit -a.
Is this problem caused by pipe size ?

core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7662
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7662
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by pqarmitage** [comment]
@Mint-M Apologies for the delay in responding to this issue.

The keepalived bfd process sends information about bfd instance state changes to the vrrp and checker processes via pipes, and what is being logged is an error writing to one of those pipes.

From the logs that you have provided, the EAGAIN error is occurring on the write to the pipe to the checker process, and the write is successful to the vrrp process (the vrrp process is logging that it has received an event on its pipe). From the configuration that you have provided, there is no checker configuration, and so the only impact of this issue should be that you have filled a pipe that isn't being read from; all the keepalived functionality should be working properly.

The questions is: _why is the bfd process writing to the checker pipe when there is no checker configuration_ (the pipe has to be opened since a reload may add a BFD_CHECK checker when none existed before the reload)?

The following simple test program shows that when `ulimit -a` reports a pipe size of 8, the pipe is filled after 65536 bytes have been written to it:
```
#define _GNU_SOURCE
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <fcntl.h>

int main(int argc, char **argv)
{
	int pipes[2];
	char c;
	int i = 0;
	int ret;

	errno = EAGAIN;
	printf("EAGAIN - %m\n");

	pipe2(pipes, O_NONBLOCK);

	while ((ret = write(pipes[1], &c, 1)) == 1)
		i++;

	printf("ret = %d, errno - %d (%m), i = %d\n", ret, errno, i);
}
```

I will investigate further and update accordingly.

**Comment by Mint-M** [comment]
@pqarmitage Thanks for your reply.
The keepalived process started without any reload and the configuration file was always the same.
There were some other error logs which came with pipe write error.

BFD_Instance(aaa) checker pipe write() error Resource temporarily unavailable
Discarding packet from [10.1.50.11]:39529 (session is not found - your discriminator field is 1687441623)
BFD_Instance(aaa) checker pipe write() error Resource temporarily unavailable
BFD_Instance(aaa) checker pipe write() error Resource temporarily unavailable
Discarding packet from [10.0.0.11]:37165 (session is not found - your discriminator field is 1886882636)
Discarding packet from [10.0.0.11]:59709 (session is not found - your discriminator field is 1358930193)
Discarding packet from [10.0.0.11]:39529 (session is not found - your discriminator field is 1687441623)
Discarding packet from [10.0.0.11]:37165 (session is not found - your discriminator field is 1886882636)

**Comment by pqarmitage** [comment]
@Mint-M If you add the `vrrp` keyword to the bfd_instance configuration block, it will make the bfd process only send bfd event notifications to the vrrp process. That should stop the `checker pipe write() error Resource temporarily unavailable` error messages.

The `discarding packet` error messages are interesting. You appear to be receiving BFD packets from 10.0.0.11, which is not the neighbor_ip configured. Are there other bfd instances running on your network?

I note that the logs are referring to bfd instance aaa, whereas your configuration has bfd instance bbb. It would be very helpful if you could provide copies of all of your configuration files and example logs from each system.

**Comment by pqarmitage** [comment]
Commit 8a4a912 stops the bfd process sending notification events to the checker and/or vrrp process if they have no configuration, and hence might not be running. This stops the `checker pipe write() error Resource temporarily unavailable` errors.

**Comment by Mint-M** [comment]
@pqarmitage 
Thanks for your work. I will build the lastest version and check whether pipe errors disappear.

BTW,sorry for confusing you with the instance name. These errors were shown in production so I manually modify the names and ip of the prodution configuration (some other instances were simplyfied) and logs after copy it.

network architecture:
VM1(ipsec1) keepalived+libreswan  Firewall1 with ISP1<---->Firewall3 with ISP1  VM3 keepalived+libreswan
VM2(ipsec2) keepalived+libreswan  Firewall2 with ISP2<---->Firewall4 with ISP2  VM4 keepalived+libreswan

VM1 ip 10.8.0.1 hostname ipsec1 VM3 ip 10.0.0.1
VM2 ip 10.8.0.2 hostname ipsec2 VM4 ip 10.0.0.2

VM1 and VM2 are running with the same configuration and they are in IDC A.
VM3 and VM4 are running with the same configuration and they are in IDC B.

There are also VM5, VM6 in IDC C and VM7, VM8 in IDC D which appears in the configuration file.

The BFD packets are sent through ipsec to monitor whether there are packet losses on each ipsec.
There are three ipsec instance running but only one bfd process monitors each ipsec.
I'm afraid that there is no other bfd instances which is configured to pass through ipsec.

Here is the full configuration of VM1 which is the same as the one of VM2 except for smpt configuration and related logs.
IPs and names are still modified but it is supposed to cause no confution now.

ipsec1 Keepalived_vrrp[665]: Received BFD event: instance ipsec2 is in state Up (delivered in 27 usec)
ipsec1 Keepalived_vrrp[665]: VRRP_Instance(vrrp-ipsec2) Tracked BFD instance ipsec2 is UP
ipsec1 Keepalived_vrrp[665]: (vrrp-ipsec2) Entering BACKUP STATE
ipsec1 Keepalived_vrrp[665]: Remote SMTP server [127.0.0.1]:25 connected.
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) checker pipe write() error Resource temporarily unavailable
ipsec1 Keepalived_vrrp[665]: SMTP alert successfully sent.
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) Entering Up state
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) Starting poll sequence
ipsec1 Keepalived_vrrp[665]: Received BFD event: instance ipsec1 is in state Up (delivered in 20 usec)
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) checker pipe write() error Resource temporarily unavailable
ipsec1 Keepalived_vrrp[665]: (vrrp-ipsec2) received lower priority (100) advert from 10.8.0.2 - discarding
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) --------------< Session parameters >-------------
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2)        min_tx  min_rx  tx_intv  mult  detect_time
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) local     100     100      100     5          500
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) remote    100     100      100     5          500
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) Detection time is 500 ms (was 5000 ms)
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) --------------< Session parameters >-------------
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1)        min_tx  min_rx  tx_intv  mult  detect_time
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) local     100     100      100     5          500
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) remote    100     100      100     5          500
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) Detection time is 500 ms (was 5000 ms)
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) Expired after 500 ms (112 usec overdue)
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) Entering Down state (Local diagnostic - Control Detection Time Expired, Remote diagnostic - No Diagnostic)
ipsec1 Keepalived_vrrp[665]: Received BFD event: instance ipsec2 is in state Down (delivered in 19 usec)
ipsec1 Keepalived_vrrp[665]: VRRP_Instance(vrrp-ipsec2) Tracked BFD instance ipsec2 is DOWN
ipsec1 Keepalived_vrrp[665]: (vrrp-ipsec2) Entering FAULT STATE
ipsec1 Keepalived_vrrp[665]: Remote SMTP server [127.0.0.1]:25 connected.
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) checker pipe write() error Resource temporarily unavailable
ipsec1 Keepalived_vrrp[665]: SMTP alert successfully sent.
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) Expired after 500 ms (54 usec overdue)
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) Entering Down state (Local diagnostic - Control Detection Time Expired, Remote diagnostic - No Diagnostic)
ipsec1 Keepalived_vrrp[665]: Received BFD event: instance ipsec1 is in state Down (delivered in 15 usec)
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) checker pipe write() error Resource temporarily unavailable
ipsec1 Keepalived_bfd[666]: Discarding packet from [10.2.0.1]:59709 (session is not found - your discriminator field is 3470716847)
ipsec1 Keepalived_bfd[666]: Discarding packet from [10.0.0.1]:37165 (session is not found - your discriminator field is 1288358802)
ipsec1 Keepalived_bfd[666]: Discarding packet from [10.2.0.1]:59709 (session is not found - your discriminator field is 3470716847)
ipsec1 Keepalived_bfd[666]: Discarding packet from [10.0.0.1]:37165 (session is not found - your discriminator field is 1288358802)


! Configuration File for keepalived

@ipsec1 $NAME=ipsec1
@ipsec2 $NAME=ipsec2

@ipsec1 $PRIORITY=110
@ipsec2 $PRIORITY=100


global_defs {
    router_id $NAME
    vrrp_mcast_group4 224.0.0.100
}

bfd_instance ipsec1 {
@ipsec1    neighbor_ip 10.0.0.1
@ipsec2    neighbor_ip 10.0.0.2
@ipsec1    source_ip 10.8.0.1
@ipsec2    source_ip 10.8.0.2
    min_tx 100
    min_rx 100
    max_hops 255
}

bfd_instance ipsec2 {
@ipsec1    neighbor_ip 10.2.0.1
@ipsec2    neighbor_ip 10.2.0.2
@ipsec1    source_ip 10.8.0.1
@ipsec2    source_ip 10.8.0.2
    min_tx 100
    min_rx 100
    max_hops 255
}

bfd_instance ipsec3 {
@ipsec1    neighbor_ip 10.1.0.1
@ipsec2    neighbor_ip 10.1.0.2
@ipsec1    source_ip 10.8.0.1
@ipsec2    source_ip 10.8.0.2
    min_tx 100
    min_rx 100
    max_hops 255
}

vrrp_instance vrrp-ipsec1 {
    state BACKUP
    interface eth0
    virtual_router_id 166
@ipsec1 priority 100
@ipsec2 priority 110
    advert_int 1
    virtual_ipaddress {
       10.8.10.10/16 dev eth0
    }
@ipsec2    track_bfd {
@ipsec2        ipsec1
@ipsec2    }
    smtp_alert
}

vrrp_instance vrrp-ipsec2 {
    state BACKUP
    interface eth0
    virtual_router_id 167
    priority $PRIORITY
    advert_int 1
    virtual_ipaddress {
       10.8.10.12/16 dev eth0
    }
@ipsec1    track_bfd {
@ipsec1        ipsec2
@ipsec1    }
    smtp_alert
}

vrrp_instance vrrp-ipsec3 {
    state BACKUP
    interface eth0
    virtual_router_id 168
@ipsec1 priority 100
@ipsec2 priority 110
    advert_int 1
    virtual_ipaddress {
       10.8.10.11/16 dev eth0
    }
@ipsec2    track_bfd {
@ipsec2        ipsec3
@ipsec2    }
    smtp_alert
}

ipsec1 Keepalived_vrrp[665]: Received BFD event: instance ipsec2 is in state Up (delivered in 27 usec)
ipsec1 Keepalived_vrrp[665]: VRRP_Instance(vrrp-ipsec2) Tracked BFD instance ipsec2 is UP
ipsec1 Keepalived_vrrp[665]: (vrrp-ipsec2) Entering BACKUP STATE
ipsec1 Keepalived_vrrp[665]: Remote SMTP server [127.0.0.1]:25 connected.
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) checker pipe write() error Resource temporarily unavailable
ipsec1 Keepalived_vrrp[665]: SMTP alert successfully sent.
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) Entering Up state
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) Starting poll sequence
ipsec1 Keepalived_vrrp[665]: Received BFD event: instance ipsec1 is in state Up (delivered in 20 usec)
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) checker pipe write() error Resource temporarily unavailable
ipsec1 Keepalived_vrrp[665]: (vrrp-ipsec2) received lower priority (100) advert from 10.8.0.2 - discarding
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) --------------< Session parameters >-------------
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2)        min_tx  min_rx  tx_intv  mult  detect_time
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) local     100     100      100     5          500
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) remote    100     100      100     5          500
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) Detection time is 500 ms (was 5000 ms)
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) --------------< Session parameters >-------------
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1)        min_tx  min_rx  tx_intv  mult  detect_time
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) local     100     100      100     5          500
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) remote    100     100      100     5          500
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) Detection time is 500 ms (was 5000 ms)
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) Expired after 500 ms (112 usec overdue)
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) Entering Down state (Local diagnostic - Control Detection Time Expired, Remote diagnostic - No Diagnostic)
ipsec1 Keepalived_vrrp[665]: Received BFD event: instance ipsec2 is in state Down (delivered in 19 usec)
ipsec1 Keepalived_vrrp[665]: VRRP_Instance(vrrp-ipsec2) Tracked BFD instance ipsec2 is DOWN
ipsec1 Keepalived_vrrp[665]: (vrrp-ipsec2) Entering FAULT STATE
ipsec1 Keepalived_vrrp[665]: Remote SMTP server [127.0.0.1]:25 connected.
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec2) checker pipe write() error Resource temporarily unavailable
ipsec1 Keepalived_vrrp[665]: SMTP alert successfully sent.
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) Expired after 500 ms (54 usec overdue)
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) Entering Down state (Local diagnostic - Control Detection Time Expired, Remote diagnostic - No Diagnostic)
ipsec1 Keepalived_vrrp[665]: Received BFD event: instance ipsec1 is in state Down (delivered in 15 usec)
ipsec1 Keepalived_bfd[666]: BFD_Instance(ipsec1) checker pipe write() error Resource temporarily unavailable
ipsec1 Keepalived_bfd[666]: Discarding packet from [10.2.0.1]:59709 (session is not found - your discriminator field is 3470716847)
ipsec1 Keepalived_bfd[666]: Discarding packet from [10.0.0.1]:37165 (session is not found - your discriminator field is 1288358802)
ipsec1 Keepalived_bfd[666]: Discarding packet from [10.2.0.1]:59709 (session is not found - your discriminator field is 3470716847)
ipsec1 Keepalived_bfd[666]: Discarding packet from [10.0.0.1]:37165 (session is not found - your discriminator field is 1288358802)

**Comment by pqarmitage** [comment]
@Mint-M From the logs above, it appears that on VM ipsec1 bfd instances ipsec1 and ipsec 2 both go down, due to timeouts, and so keepalived on VM ipsec1 clears its knowledge of the sessions it now considers down. It then subsequently receives further BFD echo packets on bfd instances ipsec1 and ipsec2, relating to the sessions that VM ipsec1 has timed out. Due to having timed the bds sessions out, and hence clearing the session information, keepalived in VM ipsec1 then reports that it cannot find the sessions.

In order to prove the idea, it would be possible to add some diagnostics to report local port numbers and local and remote discriminators when bfd sessions are established, and when they go down, so that it can be seen whether the session not found messages do indeed relate to expired sessions.

**Comment by Mint-M** [comment]
@pqarmitage Thanks for your explanations. I took a look at all logs and found that all error logs about 'session is not found' appeared after bfd instances went down. It seems that bfd packets were retransmitted or lagged through ipsec vpn which caused this problem.

**Comment by pqarmitage** [comment]
@Mint-M Have you tested the latest patches? Can this issue be closed now?

**Comment by Mint-M** [comment]
@pqarmitage I have upgraded to the lastest version, however , pipe errors used to appear after more than a week. If such errors appear again , I will imform you about it.
