### ISSUE TITLE
Parent process priority being reset whenever a new process is forked (should be child process priority)

### ISSUE THREAD

**Issue by fslight911** [acassen/keepalived#1358]
**Describe the bug**
In process.c, the local_fork function checks the return code of the fork system call to reset the priority of the child process:

  /* If we are the child process, reset all elevated priorities */
  if (pid > 0)
    reset_process_priorities();

The 'if' should check (pid == 0), since fork returns 0 to the child process, and the child's PID to the parent process.

**To Reproduce**
- In keepalived.conf, configure vrrp_priority to -15 in global_defs.
- Start keepalived, and check process priorities with ps.  All processes will be running at priority 20 (nice value of 0) (because keepalived forks a process for a notification after setting elevated priority).
- Have keepalived reload its configuration.
- Check process priorities again with ps.  VRRP process will be running at priority 5 (nice value of -15), as configured.
- Let keepalived run for a while, until VRRP needs to fork a process.  Once the fork has been done, check process priorities again with ps.  VRRP process will be back to priority 20 (nice value of 0).

**Expected behavior**
Each keepalived process should retain its configured priority at all times.

**Keepalived version**
Version 2.0.17.

**Distro (please complete the following information):**
 - CentOS
 - Version 7
 - x86_64

**Configuration file:**
global_defs {
    vrrp_garp_lower_prio_repeat 1
    vrrp_higher_prio_send_advert true

    vrrp_priority -15
    vrrp_no_swap
}

vrrp_instance srv1 {
    state BACKUP
    interface eth0
    virtual_router_id 51
    priority 150
    nopreempt
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass voip
    }
    virtual_ipaddress {
  **.***.**.**/** brd **.***.**.*** dev eth0 label eth0:0
    }
}

**Comment by pqarmitage** [comment]
@fslight911 Many thanks for pointing out this error. Commit 5c14446 applies the change you set out above.
