### ISSUE TITLE
Linux does not have root privileges, how can I install keepalived???

### ISSUE THREAD

**Issue by y761350477** [acassen/keepalived#1363]
Linux does not have root privileges, how can I install keepalived???
Linux does not have root privileges, how can I install keepalived???
Linux does not have root privileges, how can I install keepalived???

**Comment by pqarmitage** [comment]
@y761350477 Could you please explain your problem in a little more detail. Do you for example mean that you cannot login as root, or `su` to root, or run a command with `sudo`.

If you are unable to run anything with root privileges, can you install any package?

**Comment by y761350477** [comment]
@pqarmitage Yes, my account is a normal user on the server. I don't have permission to install any software. I have queried a lot of information. I didn't find the installation instructions of keepalived ordinary users. Does it mean that you must obtain root privileges when running keepalived?

**Comment by y761350477** [comment]
> @y761350477 Could you please explain your problem in a little more detail. Do you for example mean that you cannot login as root, or `su` to root, or run a command with `sudo`.
> 
> If you are unable to run anything with root privileges, can you install any package?

1. I don't have root privileges, I can't install any software, I am trying to make keepalived work by executing keepalived source, but it failed.
2. Is it necessary to have root privileges in order to work properly?

**Comment by y761350477** [comment]
> @y761350477 Could you please explain your problem in a little more detail. Do you for example mean that you cannot login as root, or `su` to root, or run a command with `sudo`.
> 
> If you are unable to run anything with root privileges, can you install any package?
1. I don't have root privileges, I can't install any software, I am trying to make keepalived work by executing keepalived source, but it failed.
2. Is it necessary to have root privileges in order to work properly?

**Comment by y761350477** [comment]
> @y761350477 Could you please explain your problem in a little more detail. Do you for example mean that you cannot login as root, or `su` to root, or run a command with `sudo`.
> 
> If you are unable to run anything with root privileges, can you install any package?

@pqarmitage
1. I don't have root privileges, I can't install any software, I am trying to make keepalived work by executing keepalived source, but it failed.
2. Is it necessary to have root privileges in order to work properly?

**Comment by pqarmitage** [comment]
@y761350477 Yes, keepalived requires root privileges in order to run, since it modifies system configuration.
