### ISSUE TITLE
Can you use keepalived without root privileges on Linux?

### ISSUE THREAD

**Issue by y761350477** [acassen/keepalived#1365]
1. I don't have root privileges, I can't install any software, I am trying to make keepalived work by executing keepalived source, but it failed.
2. Is it necessary to have root privileges in order to work properly?

**Comment by pqarmitage** [comment]
Yes, keepalived requires root privileges in order to run, and so either the process running keepalived must have root privileges, so that keepalived inherits those root privileges, or the keepalived file must be owned by root and have the setuid bit set (to do this root privileges are required).
