### ISSUE TITLE
Unsafe permission found for script 'xxx.sh' -disabling

### ISSUE THREAD

**Issue by zlandyberg** [acassen/keepalived#1372]
Hello!
when I running keepalived-2.0.18, I get the following error,the notify_backup、notify_master config can't works
![_0BI{3}Z4VP}WANE{R6(2C5](https://user-images.githubusercontent.com/23549720/62683254-92575f80-b9f0-11e9-9dcf-41b75fc6b1a4.png)
Here is my configuration file
![G@}3W2)78$AS27BR%4YD3AH](https://user-images.githubusercontent.com/23549720/62683361-ca5ea280-b9f0-11e9-984d-541b949b323d.png)

**Comment by pqarmitage** [comment]
As the log entries state, the permissions for the  script /opt/TDS/canal/bin/restart.sh are not safe for keepalived to execute them. From your configuration, the scripts are executed with root privilege, but the scripts almost certainly can be modified by a user without root privilege (it might be that a non root user has write permission to one of the parent directories or to the restart.sh script itself). That means that a non root user could modify the script, and hence cause any commands to be executed with root privilege, thereby allowing the non root user full root access to the system.

**Comment by zlandyberg** [comment]
> As the log entries state, the permissions for the script /opt/TDS/canal/bin/restart.sh are not safe for keepalived to execute them. From your configuration, the scripts are executed with root privilege, but the scripts almost certainly can be modified by a user without root privilege (it might be that a non root user has write permission to one of the parent directories or to the restart.sh script itself). That means that a non root user could modify the script, and hence cause any commands to be executed with root privilege, thereby allowing the non root user full root access to the system.

but this script only has permission for the root user.

**Comment by zlandyberg** [comment]
@pqarmitage  but this script only has permission for the root user

**Comment by pqarmitage** [comment]
What are the permissions for /opt, /opt/TDS, /opt/TDS/canal and /opt/TDS/canal/bin?

**Comment by zlandyberg** [comment]
@pqarmitage 
![J FU9T25KU{ O2(PJ@J9U%Q](https://user-images.githubusercontent.com/23549720/62691052-6fcd4280-ba00-11e9-9a97-ee309e4d7f80.png)

**Comment by pqarmitage** [comment]
What we needed to see was the permissions of the directories, not of the contents of the directories, so we really needed the `ls -ld` command. However, from the output above we can see that /opt/TDS/canal and /opt/TDS/canal/bin are world writeable. 

This means that a non-root user can delete /opt/TDS/canal/bin/restart.sh and create a new version of restart.sh, that can then do anything with root privileges.

**Comment by zlandyberg** [comment]
@pqarmitage  First of all, thank you for helping me solve the permission problem. The new problem is that when I stop the master's keepalived, the backup log shows that the node becomes master, but the backup's notify_master is not executed. The log is shown below. I hope you can help me see what the problem is.
![ULMK)`6E(DJ2D368ZFC8D_Q](https://user-images.githubusercontent.com/23549720/62748207-583a9c00-ba8a-11e9-92e6-2ed1e29c2e8a.png)

**Comment by pqarmitage** [comment]
I have run your configuration and the notify_master script runs for me when the backup transitions to master.

Since you run the same script for notify_master, notify_backup and notify_fault, and you don't pass any parameters to the script, it is probably quite difficult to know what is happening.

If you had:
```
    notify_master "/opt/TDS/canal/bin/restart.sh ls02 master"
    notify_backup "/opt/TDS/canal/bin/restart.sh ls02 backup"
    notify_fault "/opt/TDS/canal/bin/restart.sh ls02 fault"
```
and you make the restart.sh script log the parameters passed to it, it might help you see what is happening.

**Comment by zlandyberg** [comment]
@pqarmitage  I deleted the notify_fault and notify_backup configurations. I found that the notify_master script was executed, but it didn't work. If I execute this script directly, I will generate two folders, canal and example, in the /opt/TDS/canal/logs directory. There will be a log file under the folder, but now only the canal folder is generated, and there is no log file under the folder.
**This is my configuration file** 
![config](https://user-images.githubusercontent.com/23549720/62761971-9fd91c00-baba-11e9-9234-e23397a0ec00.png)
**This is the result of executing the script directly**
![file](https://user-images.githubusercontent.com/23549720/62761985-a8315700-baba-11e9-9f2b-c8d6e0206ac5.png)
![8M05TGN4 ZI5QH(IEP5BDE](https://user-images.githubusercontent.com/23549720/62761994-ac5d7480-baba-11e9-8a79-5620c071baf7.png)
**This is the result of keepalived's notify_master execution script**
![master](https://user-images.githubusercontent.com/23549720/62762004-b1babf00-baba-11e9-8aba-19cad267a64e.png)
**This is  keepalived's log**
![log](https://user-images.githubusercontent.com/23549720/62762043-c6975280-baba-11e9-9783-a266fa8896ef.png)
**and This is the startup script**
![捕获](https://user-images.githubusercontent.com/23549720/62762237-39a0c900-babb-11e9-9df5-b6d305b5bf7b.PNG)
![捕获2](https://user-images.githubusercontent.com/23549720/62762247-402f4080-babb-11e9-8f89-09ba4939f973.PNG)

**Comment by pqarmitage** [comment]
The problem is that when keepalived executes the script, the canal directory is created without the owner execute bit set (this means that the directory is not searchable). The reason for this is that the umask is 0177, in other words the user execute bit and all the group and other bits are cleared for any file or directory created.

To solve your problem, you could add a line `umask u+x` near the beginning of your script, or you could add `chmod u+x $base/logs/canal` after `mkdir -p $base/logs/canal`.

When you execute the script directly, the umask setting will not be so restrictive (execute `umask` to see what it reports), and so $base/logs/canal is created with the execute bit set.

**Comment by pqarmitage** [comment]
An alternative to the above suggestions is to use the umask option in global_defs.

**Comment by zlandyberg** [comment]
@pqarmitage 

> An alternative to the above suggestions is to use the umask option in global_defs.

I just tried this method, it still can't start successfully.

**Comment by jimlinntu** [comment]
I encountered the same problem:

```bash
#!/bin/bash

echo "[!] I wake up!"

function f {
    echo "f is called!"
}

trap f SIGTERM
sleep infinity &
wait
echo "Gracefully shutdown!
```

```
global_defs {
    enable_script_security
    script_user root
}

vrrp_instance VRRP1 {
    state MASTER
    interface eth0
    virtual_router_id 41
    priority 200
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1066
    }
    virtual_ipaddress {
        172.31.238.100/24
    }
    notify_master "/etc/keepalived/script.sh"
}
```

```
m1_1  | Fri Jan  8 05:59:38 2021: Starting Keepalived v1.3.9 (10/21,2017)
m1_1  | Fri Jan  8 05:59:38 2021: Opening file '/etc/keepalived/keepalived.conf'.
m1_1  | Fri Jan  8 05:59:38 2021: Starting Healthcheck child process, pid=6
m1_1  | Fri Jan  8 05:59:38 2021: Starting VRRP child process, pid=7
m1_1  | Fri Jan  8 05:59:38 2021: Opening file '/etc/keepalived/keepalived.conf'.
m1_1  | Fri Jan  8 05:59:38 2021: Registering Kernel netlink reflector
m1_1  | Fri Jan  8 05:59:38 2021: Registering Kernel netlink command channel
m1_1  | Fri Jan  8 05:59:38 2021: Registering gratuitous ARP shared channel
m1_1  | Fri Jan  8 05:59:38 2021: Opening file '/etc/keepalived/keepalived.conf'.
m1_1  | Fri Jan  8 05:59:38 2021: Unsafe permissions found for script '/etc/keepalived/script.sh'.
m1_1  | Fri Jan  8 05:59:38 2021: Disabling notify script /etc/keepalived/script.sh due to insecure
m1_1  | Fri Jan  8 05:59:38 2021: Using LinkWatch kernel netlink reflector...
m1_1  | Fri Jan  8 05:59:39 2021: VRRP_Instance(VRRP1) Transition to MASTER STATE
m1_1  | Fri Jan  8 05:59:40 2021: VRRP_Instance(VRRP1) Entering MASTER STATE
```

**Comment by jimlinntu** [comment]
> I encountered the same problem:
> 
> ```shell
> #!/bin/bash
> 
> echo "[!] I wake up!"
> 
> function f {
>     echo "f is called!"
> }
> 
> trap f SIGTERM
> sleep infinity &
> wait
> echo "Gracefully shutdown!
> ```
> 
> ```
> global_defs {
>     enable_script_security
>     script_user root
> }
> 
> vrrp_instance VRRP1 {
>     state MASTER
>     interface eth0
>     virtual_router_id 41
>     priority 200
>     advert_int 1
>     authentication {
>         auth_type PASS
>         auth_pass 1066
>     }
>     virtual_ipaddress {
>         172.31.238.100/24
>     }
>     notify_master "/etc/keepalived/script.sh"
> }
> ```
> 
> ```
> m1_1  | Fri Jan  8 05:59:38 2021: Starting Keepalived v1.3.9 (10/21,2017)
> m1_1  | Fri Jan  8 05:59:38 2021: Opening file '/etc/keepalived/keepalived.conf'.
> m1_1  | Fri Jan  8 05:59:38 2021: Starting Healthcheck child process, pid=6
> m1_1  | Fri Jan  8 05:59:38 2021: Starting VRRP child process, pid=7
> m1_1  | Fri Jan  8 05:59:38 2021: Opening file '/etc/keepalived/keepalived.conf'.
> m1_1  | Fri Jan  8 05:59:38 2021: Registering Kernel netlink reflector
> m1_1  | Fri Jan  8 05:59:38 2021: Registering Kernel netlink command channel
> m1_1  | Fri Jan  8 05:59:38 2021: Registering gratuitous ARP shared channel
> m1_1  | Fri Jan  8 05:59:38 2021: Opening file '/etc/keepalived/keepalived.conf'.
> m1_1  | Fri Jan  8 05:59:38 2021: Unsafe permissions found for script '/etc/keepalived/script.sh'.
> m1_1  | Fri Jan  8 05:59:38 2021: Disabling notify script /etc/keepalived/script.sh due to insecure
> m1_1  | Fri Jan  8 05:59:38 2021: Using LinkWatch kernel netlink reflector...
> m1_1  | Fri Jan  8 05:59:39 2021: VRRP_Instance(VRRP1) Transition to MASTER STATE
> m1_1  | Fri Jan  8 05:59:40 2021: VRRP_Instance(VRRP1) Entering MASTER STATE
> ```

I found that this was caused by my folder not held by root.

After I put my script at `/script.sh` and `chown root /script.sh`, it works.

**Comment by pqarmitage** [comment]
Yes, the point is that since scripts by default are executed by root, if there is any way that a non root user can either modify the script directly, or modify any of the directories in the path, then a non root user could modify the script and hence execute something with root privileges. Consequently, with `enable_script_security` keepalived checks at startup that a script or the path is not modifiable, and if it is it refuses, for security reasons, to execute the script.

**Comment by huerni** [comment]
Hello，All permissions are set correctly for keepalived 2.2.8, but why am I still getting the following error?

```
global_defs {
   script_user root
   enable_script_security
}


vrrp_script chk {
    script "/opt/keepalived/check_and_failover.sh"
    interval 2
    #fall 2 # 连续2次失败（约4秒）才判定真正挂了
    weight -20
}


vrrp_instance VI_1 {
    state MASTER              
    interface ens33         
    virtual_router_id 88
    priority 100             
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        192.168.1.212         
    }
    track_script {
        chk 
    }
    notify_master "/opt/keepalived/on_master.sh"  
    # notify_backup "/etc/keepalived/on_backup.sh" 
    # notify_fault  "/etc/keepalived/on_fault.sh"   
}

```

<img width="372" height="18" alt="Image" src="https://github.com/user-attachments/assets/7f7c9b9f-e0c3-4cfd-bc49-02e4f96f8ca7" />

<img width="457" height="20" alt="Image" src="https://github.com/user-attachments/assets/caedbf1a-039d-4704-80d9-3ee87c7a8504" />

<img width="506" height="48" alt="Image" src="https://github.com/user-attachments/assets/30a3ef05-1d42-48a5-a841-0ee0e1cd2bbf" />



<img width="737" height="19" alt="Image" src="https://github.com/user-attachments/assets/d9b13c4c-fc31-4153-a35f-1798eb563168" />

<img width="638" height="20" alt="Image" src="https://github.com/user-attachments/assets/6a35c634-78da-4d49-887c-9a2fab9fe9e2" />

**Comment by pqarmitage** [comment]
@huerni I have tried your configuration with the same directory and file permissions and I am not getting the "Unsafe permissions" error that you have posted above. The permissions you show above look OK - what are the permissions for / - please post output of `ls -ld /`.

If the permissions look OK for / then I think your only option is to add some diagnostic code to lib/notify.c around line 700 to see why it is failing.

**Comment by huerni** [comment]
Thank you very much. The issue was with the ownership of the / directory—it was not owned by root. After changing the ownership to root, the problem was resolved. Thank you again!
