### ISSUE TITLE
PID file access rights

### ISSUE THREAD

**Issue by grishin-a** [acassen/keepalived#1378]
**Describe the bug**
After upgrading from version 1.4.5 to 2.0.16 I noticed that default access rights on the file /var/run/keepalived.pid was changed from 0644 to 0600, that breaks my deployment.
System (root user) umask is 0022. If I set this parameter manually in keepalived.conf or pass as the process parameter: umask 022, only then /var/run/keepalived.pid will be created with 0644 rights.
If I change https://github.com/acassen/keepalived/blob/c9d0b1e459a6d340aff800b72f248000921385c6/keepalived/core/main.c#L1711
to umask(022);
then also /var/run/keepalived.pid will be created with 0644 rights.

**To Reproduce**
Just start keepalived

**Expected behavior**
Process uses running user umask

**Keepalived version**
Keepalived v2.0.16 (05/03,2019), git commit v2.0.15-96-g4d492740+

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.19.0
Running on Linux 4.19.44 #1 SMP Wed Aug 14 17:59:41 2019

configure options: --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/keepalived-2.0.16 --htmldir=/usr/share/doc/keepalived-2.0.16/html --libdir=/usr/lib64 --with-init=custom --with-kernel-dir=/usr --enable-sha1 --enable-vrrp --enable-bfd --disable-dbus --disable-dbus-create-instance --disable-debug --disable-json --disable-regex --disable-regex-timers --disable-snmp --disable-snmp-checker --disable-snmp-rfc --disable-snmp-rfcv2 --disable-snmp-rfcv3 --disable-snmp-vrrp build_alias=x86_64-pc-linux-gnu host_alias=x86_64-pc-linux-gnu PKG_CONFIG_PATH=/usr/lib64/pkgconfig CFLAGS=-march=native -O2 -pipe -ftree-vectorize -fomit-frame-pointer LDFLAGS=-Wl,-O1 -Wl,--as-needed

Config options:  LIBIPTC LVS VRRP VRRP_AUTH BFD OLD_CHKSUM_COMPAT FIB_ROUTING EINTR_CHECK

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Distro (please complete the following information):**
 - Name Gentoo
 - Version -
 - Architecture x86_64

**Configuration file:**
global_defs {
    enable_script_security
    script_user root
}
vrrp_instance VI_1 {
     state BACKUP
     interface mybond
     virtual_router_id 1
     priority 40
     advert_int 1
     nopreempt
     virtual_ipaddress {
          192.168.1.100
     }
     track_interface {
        mybond
     }
}

**Comment by pqarmitage** [comment]
Commit 12f3a23 makes PID files have file permission owner=rw, group=r, other=r.
