### ISSUE TITLE
Creation of ipvlan interface for ipv4 is trying to add interface name as interface IP 

### ISSUE THREAD

**Issue by 3hedgehogs** [acassen/keepalived#1382]
**Describe the bug**
The attempt to create ipvlan interface is successfully finish with warning:
`
 Keepalived_vrrp[1998]: (VI_EXT_MP13): Success creating ipvlan interface vrrp10
 Keepalived_vrrp[1998]: VI_EXT_MP13: Failed to add interface address to vrrp10 
`

**To Reproduce**

`
vrrp_instance VI_EXT_MP13 {
  interface                 ens5
  state                     MASTER
  virtual_router_id         10
  priority                  151 
  advert_int                 10
  garp_master_delay           5
  preempt_delay               0
  
  use_ipvlan vrrp10 169.254.1.212/30
`

**Expected behavior**
ipvlan interface is created without warnings

**Keepalived version**
keepalived_514.snap

**Distro (please complete the following information):**
 - Name : Ubuntu
 - Version: 19.04
 - Architecture:  x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in VMs instance on CROC

**System Log entries**
`
Keepalived[1975]: Starting Keepalived v2.0.18 (07/26,2019), git commit v2.0.18+
Keepalived[1975]: WARNING - keepalived was build for newer Linux 5.0.18, running on Linux 5.0.0-25-gen
Keepalived[1975]: Command line: '/snap/keepalived/514/usr/sbin/keepalived-500'
Keepalived[1975]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived[1975]: Opening file '/var/cache/mng/keepalived/iprules.inc'.
Keepalived[1975]: Opening file '/var/cache/mng/keepalived/external_first_master.inc'.
Keepalived[1975]: Opening file '/var/cache/mng/keepalived/external_master.inc'.
Keepalived[1975]: Opening file '/var/cache/mng/keepalived/virtual_routes_master.inc'.
Keepalived[1975]: Opening file '/var/cache/mng/keepalived/internal_master.inc'.
Keepalived[1975]: Opening file '/var/cache/mng/keepalived/external_first_backup.inc'.
Keepalived[1975]: Opening file '/var/cache/mng/keepalived/external_backup.inc'.
Keepalived[1975]: Opening file '/var/cache/mng/keepalived/virtual_routes_backup.inc'.
Keepalived[1975]: Opening file '/var/cache/mng/keepalived/internal_backup.inc'.
Keepalived[1997]: Starting VRRP child process, pid=1998
Keepalived_vrrp[1998]: Registering Kernel netlink reflector
Keepalived_vrrp[1998]: Registering Kernel netlink command channel
Keepalived_vrrp[1998]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived_vrrp[1998]: Opening file '/var/cache/mng/keepalived/iprules.inc'.
Keepalived_vrrp[1998]: Opening file '/var/cache/mng/keepalived/external_first_master.inc'.
Keepalived_vrrp[1998]: Configuration specifies interface vrrp10 which doesn't currently exist - will u
Keepalived_vrrp[1998]: Opening file '/var/cache/mng/keepalived/external_master.inc'.
Keepalived_vrrp[1998]: Opening file '/var/cache/mng/keepalived/virtual_routes_master.inc'.
Keepalived_vrrp[1998]: Opening file '/var/cache/mng/keepalived/internal_master.inc'.
Keepalived_vrrp[1998]: Configuration specifies interface vrrp11 which doesn't currently exist - will u
Keepalived_vrrp[1998]: Opening file '/var/cache/mng/keepalived/external_first_backup.inc'.
Keepalived_vrrp[1998]: Opening file '/var/cache/mng/keepalived/external_backup.inc'.
Keepalived_vrrp[1998]: Opening file '/var/cache/mng/keepalived/virtual_routes_backup.inc'.
Keepalived_vrrp[1998]: Opening file '/var/cache/mng/keepalived/internal_backup.inc'.
Keepalived_vrrp[1998]: Please add a #! shebang to script /opt/mng/keepalived-scripts/notify.sh
Keepalived_vrrp[1998]: Please add a #! shebang to script /opt/mng/keepalived-scripts/notify.sh
Keepalived_vrrp[1998]: (VI_EXT_MP13): Success creating ipvlan interface vrrp10
Keepalived_vrrp[1998]: VI_EXT_MP13: Failed to add interface address to vrrp10
`

**Did keepalived coredump?**
no

**Comment by pqarmitage** [comment]
Commit 0eb2edf resolves the incorrect error message being reported. The issue only effected the logging of the error message and did not effect the functionality.

Many thanks for reporting this.

This will appear in the snap edge channel once built.
