### ISSUE TITLE
Documentation for virtual_router_id range is incorrect

### ISSUE THREAD

**Issue by cybertron** [acassen/keepalived#1394]
**Describe the bug**
The man page says that the range for the virtual_router_id configuration option is 0 to 255: "arbitrary unique number from 0 to 255". If you use 0 for this value, you get an error in the logs that reads: "VRID '0' not valid - must be between 1 & 255"

**To Reproduce**
Configure a VRID of 0.

**Expected behavior**
All of the documented VRIDs should work.

**Keepalived version**
2.0.18 and 1.3.5

**Distro (please complete the following information):**
Fedora 30 and CentOS 7

**Configuration file:**
vrrp_instance VI_1 {
    state MASTER
    interface eth0
    virtual_router_id 0
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        192.168.200.16
        192.168.200.17
        192.168.200.18
    }
}

**Comment by pqarmitage** [comment]
Commit 00fb2a1 corrects the documentation error.

Many thanks for reporting this.
