### ISSUE TITLE
Cannot receive state notification from fifo if vrrp enters FAULT during init

### ISSUE THREAD

**Issue by chenwng** [acassen/keepalived#1399]
**Describe the bug**
When vrrp enters FAULT during init due to track file with none-zero value, there is no notification received from fifo. 

**To Reproduce**
1. Config nofify fifo to send notify.
2. Config vrrp track file and a vrrp instance using the track file
3. Set 1 in the track file
4. Start keepalived.

**Expected behavior**
Notification like "INSTANCE "VI_1" FAULT 100" can be received from fifo.

**Keepalived version**
Keepalived v2.0.18 (09/29,2019), git commit v2.0.18-40-g18262c76

**Distro (please complete the following information):**
Tested it on Ubuntu and CentOS

**Details of any containerisation or hosted service (e.g. AWS)**
N/A

**Configuration file:**
```
global_defs {
   smtp_server 192.168.200.1
   smtp_connect_timeout 30
   router_id LVS_DEVEL
   vrrp_skip_check_adv_addr
   vrrp_strict
   notify_fifo /path/to/fifo
}

vrrp_track_file test {
        file "/path/to/trackfile"
}

vrrp_instance VI_1 {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 100
    advert_int 1
    virtual_ipaddress {
        192.168.200.16
        192.168.200.17
        192.168.200.18
    }
    track_file {
        test weight 0
    }
}

```

**Notify and track scripts**
N/A

**System Log entries**

**Did keepalived coredump?**
No.

**Additional context**
As far as I can tell, the issue is because [notify_fifo_open](https://github.com/acassen/keepalived/blob/18262c764640db580038a03e515386dfec12d349/keepalived/vrrp/vrrp.c#L3878) is at the end of vrrp_complete_init(void), which is after [vrrp state check/notify](https://github.com/acassen/keepalived/blob/18262c764640db580038a03e515386dfec12d349/keepalived/vrrp/vrrp.c#L3798) and [notify fd](https://github.com/acassen/keepalived/blob/18262c764640db580038a03e515386dfec12d349/keepalived/vrrp/vrrp_notify.c#L96) is not available.

**Comment by pqarmitage** [comment]
@chenwng Commit 88f36d0 implements your suggestion and moves the opening of the FIFOs to earlier in the init process, resulting in the FAULT notifications being written to the FIFOs.

**Comment by chenwng** [comment]
Thanks!
