### ISSUE TITLE
Small typo on load balancing documentation

### ISSUE THREAD

**Issue by solanav** [acassen/keepalived#1408]
On [this page](https://www.keepalived.org/doc/load_balancing_techniques.html#virtual-server-via-tunneling) the second paragraph of virtual server via tunneling contains the word "metho" and it should be "method".

**Comment by pqarmitage** [comment]
@solanav This typo, and a number of others, were corrected in commit 71062d9. We just need to regenerate the documentation.

**Comment by pqarmitage** [comment]
@solanav Since the documentation was so out of date, the documentation on keepalived.org has now been changed to keepalived.conf(5) man page, until the other documentation can be updated.
