### ISSUE TITLE
keepalived snap revision 618 does not initialise dbus

### ISSUE THREAD

**Issue by 3hedgehogs** [acassen/keepalived#1410]
**Describe the bug**

Dispite of compilation options in snap version of keepalived  and configuration the server does not initialise dbus.

**To Reproduce**

add enable_dbus to configuration
`
global_defs {
...
   enable_dbus
}`

**Expected behavior**

```
Acquired DBus bus org.keepalived.Vrrp1
Acquired the name org.keepalived.Vrrp1 on the session bus
```

in logs

**Keepalived version**

`Keepalived v2.0.19 (10/19,2019), git commit v2.0.19+

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.0.21
Running on Linux 5.3.0-18-generic #19-Ubuntu SMP Tue Oct 8 20:14:06 UTC 2019

configure options: --prefix= --prefix=/usr --enable-bfd --enable-dbus --enable-json --enable-regex --enable-snmp --enable-snmp-rfc --disable-libipset-dynamic LDFLAGS= -L/build/keepalived/stage/lib -L/build/keepalived/stage/usr/lib -L/build/keepalived/stage/lib/x86_64-linux-gnu -L/build/keepalived/stage/usr/lib/x86_64-linux-gnu

Config options:  LIBIPTC LIBIPSET NFTABLES LVS REGEX VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK`

**Distro (please complete the following information):**

NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"

**Comment by pqarmitage** [comment]
@3hedgehogs Do you know if this has worked with earlier versions of the snap?

Could you please also paste the log output relating to DBus when running keepalived in the snap.

**Comment by 3hedgehogs** [comment]
We have snap version of keepalived 514 on few our servers and they are correctly working with dbus.

```
    systemd[1]: Starting Service for snap application keepalived.daemon...
    Keepalived[1127]: Starting Keepalived v2.0.19 (10/19,2019), git commit v2.0.19+
    Keepalived[1127]: WARNING - keepalived was build for newer Linux 5.0.21, running on Linux 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019
    Keepalived[1127]: Command line: '/snap/keepalived/618/usr/sbin/keepalived-500'
    Keepalived[1127]: Opening file '/etc/keepalived/keepalived.conf'.
    Keepalived[1127]: Opening file '/var/cache/mng/keepalived/iprules.inc'.
    Keepalived[1127]: Opening file '/var/cache/mng/keepalived/external_first_master.inc'.
    Keepalived[1127]: Opening file '/var/cache/mng/keepalived/external_master.inc'.
    Keepalived[1127]: Opening file '/var/cache/mng/keepalived/virtual_routes_master.inc'.
    Keepalived[1127]: Opening file '/var/cache/mng/keepalived/internal_master.inc'.
    Keepalived[1127]: Opening file '/var/cache/mng/keepalived/external_first_backup.inc'.
    Keepalived[1127]: Opening file '/var/cache/mng/keepalived/external_backup.inc'.
    Keepalived[1127]: Opening file '/var/cache/mng/keepalived/virtual_routes_backup.inc'.
    Keepalived[1127]: Opening file '/var/cache/mng/keepalived/internal_backup.inc'.
    Keepalived[1155]: Starting VRRP child process, pid=1156
    Keepalived_vrrp[1156]: Registering Kernel netlink reflector
    Keepalived_vrrp[1156]: Registering Kernel netlink command channel
    Keepalived_vrrp[1156]: Opening file '/etc/keepalived/keepalived.conf'.
    Keepalived_vrrp[1156]: Opening file '/var/cache/mng/keepalived/iprules.inc'.
    Keepalived_vrrp[1156]: Opening file '/var/cache/mng/keepalived/external_first_master.inc'.
    Keepalived_vrrp[1156]: Configuration specifies interface vrrp10 which doesn't currently exist - will use if created
    Keepalived_vrrp[1156]: Opening file '/var/cache/mng/keepalived/external_master.inc'.
    Keepalived_vrrp[1156]: Opening file '/var/cache/mng/keepalived/virtual_routes_master.inc'.
    Keepalived_vrrp[1156]: Opening file '/var/cache/mng/keepalived/internal_master.inc'.
    Keepalived_vrrp[1156]: Configuration specifies interface vrrp11 which doesn't currently exist - will use if created
    Keepalived_vrrp[1156]: Opening file '/var/cache/mng/keepalived/external_first_backup.inc'.
    Keepalived_vrrp[1156]: Configuration specifies interface vrrp20 which doesn't currently exist - will use if created
    Keepalived_vrrp[1156]: Opening file '/var/cache/mng/keepalived/external_backup.inc'.
    Keepalived_vrrp[1156]: Opening file '/var/cache/mng/keepalived/virtual_routes_backup.inc'.
    Keepalived_vrrp[1156]: Opening file '/var/cache/mng/keepalived/internal_backup.inc'.
    Keepalived_vrrp[1156]: Configuration specifies interface vrrp21 which doesn't currently exist - will use if created
    systemd[1]: Started Service for snap application keepalived.daemon.
    Keepalived_vrrp[1156]: Please add a #! shebang to script /opt/mng/keepalived-scripts/notify.sh
    Keepalived_vrrp[1156]: Please add a #! shebang to script /opt/mng/keepalived-scripts/notify.sh
    Keepalived_vrrp[1156]: (VI_EXT_MP13NAT01): Success creating ipvlan interface vrrp10
    Keepalived_vrrp[1156]: (VI_INT_MP13NAT01): Success creating ipvlan interface vrrp11
    Keepalived_vrrp[1156]: (VI_EXT_MP13NAT02): Success creating ipvlan interface vrrp20
    Keepalived_vrrp[1156]: (VI_INT_MP13NAT02): Success creating ipvlan interface vrrp21
    Keepalived_vrrp[1156]: Using MII-BMSR/ETHTOOL NIC polling thread(s)...
    Keepalived_vrrp[1156]: Registering gratuitous ARP shared channel
    Keepalived_vrrp[1156]: (VI_EXT_MP13NAT01) Entering BACKUP STATE (init)
    Keepalived_vrrp[1156]: (VI_INT_MP13NAT01) Entering BACKUP STATE (init)
    Keepalived_vrrp[1156]: (VI_EXT_MP13NAT02) Entering BACKUP STATE (init)
    Keepalived_vrrp[1156]: (VI_INT_MP13NAT02) Entering BACKUP STATE (init)
```
with revision 514 after these lines there are
```
  Keepalived_vrrp[1133]: Acquired DBus bus org.keepalived.Vrrp1
  Keepalived_vrrp[1133]: Acquired the name org.keepalived.Vrrp1 on the session bus
```

**Comment by pqarmitage** [comment]
I suspect you need to install the following files:
```
/etc/dbus-1/system.d/org.keepalived.Vrrp1.conf
/usr/share/dbus-1/interfaces/org.keepalived.Vrrp1.Instance.xml
/usr/share/dbus-1/interfaces/org.keepalived.Vrrp1.Vrrp.xml
```
They are available in keepalived//dbus in the build tree once keepalived has been built.

I can reproduce the problem you describe with any snap version of keepalived (including 514 and 618) if the above files are missing, and once I have installed the files the problem does not occur.

I will see it I can find a way of making the snap install the files.

**Comment by 3hedgehogs** [comment]
You are right.  Sorry. My fault
I had keepalived installed from Ubuntu repository before snap instllation (514 revision).
And have noticed that dbus-1 files dispirited only after snap keepalived installation on new servers.

**Comment by pqarmitage** [comment]
I have now updated the snapcraft.yaml file to include and install the required three DBus files. keepalived snap revisions 628 and later will now automatically install the DBus files on installation.
