### ISSUE TITLE
Instance name becomes NULL after config reload 

### ISSUE THREAD

**Issue by msridhar87** [acassen/keepalived#1414]
version
========
keepalived -v
Keepalived v2.0.16 (05/03,2019), git commit v2.0.15-96-g4d492740+

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.9.189
Running on Linux 4.9.168 #1 SMP Debian 4.9.168-1+deb9u5

configure options: --enable-dbus --enable-dbus-create-instance

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING DBUS DBUS_CREATE_INSTANCE EINTR_CHECK

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV RTA_VIA FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

Initial state
================
 ps aux | grep keep
root       712  0.0  0.0  12656  1640 ttyS1    Ss+  15:30   0:00 /sbin/agetty --keep-baud 115200,38400,9600 ttyS1 vt220
root      1234  0.0  0.0  49416   576 ?        Ss   15:31   0:00 keepalived -P -f /etc/keepalived/keepalived.default.conf
root      6720  0.0  0.0  11108   992 ttyS0    S+   16:03   0:00 grep keep

Keepalived config
================
instance default
global_defs {
  vrrp_version 2
  enable_dbus
  dbus_service_name org.keepaliveddefault
  vrrp_netlink_cmd_rcv_bufs 31457280
  vrrp_netlink_cmd_rcv_bufs_force
  vrrp_netlink_monitor_rcv_bufs 31457280
  vrrp_netlink_monitor_rcv_bufs_force
}
#st_e101-049-1_v4_1
vrrp_instance e101-049-1_v4_1 {
  state BACKUP
  interface e101-049-1
  virtual_router_id 1
  priority 100
  advert_int 1.000000
  use_vmac e101-049-1.v257
  virtual_ipaddress {
    1.1.1.200
  }
}
#end_e101-049-1_v4_1

Reload keepalived process (1234)
=========================
 kill -SIGHUP 1234
 ps aux | grep keep
root       712  0.0  0.0  12656  1640 ttyS1    Ss+  15:30   0:00 /sbin/agetty --keep-baud 115200,38400,9600 ttyS1 vt220
root      1234  0.0  0.0  49416  2712 ?        Ss   15:31   0:00 keepalived -P -f /etc/keepalived/keepalived.default.conf
root      6863  0.1  0.1 344344  6576 ?        Sl   16:05   0:00 keepalived -P -f /etc/keepalived/keepalived.default.conf
root      6888  0.0  0.0  11108   936 ttyS0    S+   16:05   0:00 grep keep

Attach child process
==================
 gdb -p 6863
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 6863
[New LWP 6867]
[New LWP 6871]
[New LWP 6875]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f00c3643303 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
84      ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) p global_data->instance_name
$1 = 0x5579c7cf5790 "default"

Modify keepalived config - changing priority
=================================
instance default
global_defs {
  vrrp_version 2
  enable_dbus
  dbus_service_name org.keepaliveddefault
  vrrp_netlink_cmd_rcv_bufs 31457280
  vrrp_netlink_cmd_rcv_bufs_force
  vrrp_netlink_monitor_rcv_bufs 31457280
  vrrp_netlink_monitor_rcv_bufs_force
}
#st_e101-049-1_v4_1
vrrp_instance e101-049-1_v4_1 {
  state BACKUP
  interface e101-049-1
  virtual_router_id 1
  priority 10
  advert_int 1.000000
  use_vmac e101-049-1.v257
  virtual_ipaddress {
    1.1.1.200
  }
}
#end_e101-049-1_v4_1

Reload child process
================
 gdb -p 6863
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 6863
[New LWP 6867]
[New LWP 6871]
[New LWP 6875]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f00c3643303 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
84      ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) p global_data->instance_name
$1 = 0x0
(gdb)

After reload, the instance name becomes NULL. As a result, the dbus message does not have the instance name.

**Comment by pqarmitage** [comment]
Many thanks for your report and investigations. Commit 34649dc resolves this issue.

BTW, sending SIGUSR1 to the parent keepalived process makes the vrrp and checker processes write their configuration information to `/tmp/keepalived.data` and `/tmp/keepalived_check.data`. These files also show that instancename wasn't being set after a reload.
