### ISSUE TITLE
Add support for configuration snippets

### ISSUE THREAD

**Issue by johannbg** [acassen/keepalived#1422]
**Is your feature request to resolve a problem or provide enhanced functionality? Please describe.**
Add support for configuration snippets which are becoming the de facto standard to support modern deployment these days ( or by applications ). 

The "global" options would then just be kept in keepalived.conf either directly under /etc under /etc/keepalived/ or /etc/keepalived.d directory and VRRP instances in their own configuration snippets as in 

/etc/keepalived/10.conf
/etc/keepalived/20.conf
/etc/keepalived/foo.conf
/etc/keepalived/bar.conf

Or

/etc/keepalived.d/10.conf
/etc/keepalived.d/20.conf
/etc/keepalived.d/foo.conf
/etc/keepalived.d/bar.conf
etc

**Comment by pqarmitage** [comment]
If you have the following as /etc/keepalived.conf:
`include /etc/keepalived.d/*.conf`
keepalived will already do exactly as you suggest.

**Comment by johannbg** [comment]
Sweet. Beer points on that one closing this ;)
