### ISSUE TITLE
Enabling nftables.

### ISSUE THREAD

**Issue by johannbg** [acassen/keepalived#1424]
I'm getting Unknown keyword 'nftables' 
Is there any "On" switch in keepalived.conf that I'm missing? I'm not seeing vrrp_nftables ( iptables/equalent/counterpart ) in the man pages and I'm not seeing any keepalived table when I run nft list ruleset ( actually would be good if you could paste an output from nft list ruleset  on working nftable setup so I can see which rules are added )

I was actually wondering a bit about this since I dont have iptables installed and did not see any use "iptables" or use "nftables" option in keepalived.conf man pages which told it which one it should be using ( perhaps should just detect it startup ) which is why I was started looking into splitting the packages in sub packages ( you would end up with, keepalived-iptables, keepalived-nftables, keepalived-firewalld,keepalived-json, keepalived-dbus etc )

Here are the build options in total. 

Keepalived v2.0.19 (10/19,2019)

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.3.6
Running on Linux 5.3.8-300.fc31.x86_64 #1 SMP Tue Oct 29 14:28:41 UTC 2019

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --enable-snmp-rfc --enable-nftables --enable-sha1 --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LIBIPTC LIBIPSET_DYNAMIC NFTABLES LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Comment by pqarmitage** [comment]
keepalived.conf has the following re nftables:
```
           # Use nftables to implement no_accept mode and only send IGMP/MLD
           #   messages on the parent interface of a VMAC.
           #   TABLENAME must not exist, and must be different for each
           #   instance of keepalived running in the same network namespace.
           #   Default tablename is keepalived, and priority is -1.
           #   keepalived will create base chains in the table.
           #   counters means counters are added to the rules (primarily for
           #   debugging purposes).
           #   ifindex means create IPv6 link local sets using ifindex rather
           #   than ifnames. This is the default unless the vrrp_instance has
           #   set dont_track_primary. The alternative is to use interface names
           #   as part of the set key, but the nft utility prior to v0.8.3 will
           #   then not output interface names properly.
           nftables [TABLENAME]
           nftables_priority PRIORITY
           nftables_counters
           nftables_ifindex
```

The following configuration:
```
global_defs {
	nftables
	nftables_counters
}

vrrp_instance VI_1 {
    interface ens3
    state BACKUP
    virtual_router_id 253
    version 3
    priority 220
    advert_int 1
    use_vmac
    no_accept		# Adds additional nftables entries
    virtual_ipaddress {
      10.2.0.100/32
    }
}

vrrp_instance VI_6 {
    interface ens3
    state BACKUP
    virtual_router_id 253
    use_vmac
    priority 240
    advert_int 1
    virtual_ipaddress {
      fe80::4000/64
      2020:523:5fe3:2::3000
    }
}
```
produces the following nft configuration:
```
> nft list ruleset
table ip keepalived {
	map vmac_map {
		type iface_index : iface_index
		elements = { "vrrp.253" : "ens3" }
	}

	set vips {
		type ipv4_addr
		elements = { 10.2.0.100 }
	}

	chain out {
		type filter hook output priority filter - 1; policy accept;
		ip daddr 224.0.0.22 dup to 224.0.0.22 device oif map @vmac_map counter packets 4 bytes 160 drop
		ip saddr @vips counter packets 8 bytes 758 drop
	}

	chain in {
		type filter hook input priority filter - 1; policy accept;
		ip daddr @vips counter packets 0 bytes 0 drop
	}
}
table ip6 keepalived {
	map vmac_map {
		type iface_index : iface_index
		elements = { "vrrp6.253" : "ens3" }
	}

	chain out {
		type filter hook output priority filter - 1; policy accept;
		ip6 daddr ff02::16 dup to ff02::16 device oif map @vmac_map counter packets 10 bytes 1080 drop
	}
}
```

**Comment by johannbg** [comment]
I see immediately my personal failure there ( forgot to enclose it in brackets {} ) and confirm that these rules indeed get added ;)
