### ISSUE TITLE
persistence_granularity 0.0.0.0

### ISSUE THREAD

**Issue by vrit** [acassen/keepalived#1435]
**Describe the bug**
Setting persistence_granularity to 0.0.0.0 is not working. 0.0.0.0 is a valid settings for ipvs but the code use 0 has truth value. For example ([ipvswrapper.c#L420](https://github.com/acassen/keepalived/blob/3d0e5641794a3878791c0b84b7c389cf11aaab34/keepalived/check/ipvswrapper.c#L420)):

`if (vs->persistence_granularity)`

**Keepalived version**
1.3.15

**Distro (please complete the following information):**
 - Centos
 - 7.6
 - x86_64

**Comment by pqarmitage** [comment]
Many thanks for reporting this. Commit 44026be resolves the issue, but you will need to update keepalived to v2.0.19+ to include it.
