### ISSUE TITLE
'disable-libipset-dynamic' stops rpm package from being built when ipset-devel is not installed

### ISSUE THREAD

**Issue by Mint-M** [acassen/keepalived#1441]
**Describe the bug**
On CentOS8/RHEL8, ipset-devel is not provided on the yum repo and I have noticed that @pqarmitage had reported it to redhat(https://bugzilla.redhat.com/show_bug.cgi?id=1708735).

However, something has gone wrong which has stopped rpm package from being built since Keepalived v.2.0.19.
If 'CONFIG_OPTS="$CONFIG_OPTS --disable-libipset-dynamic"' is removed from keepalived.spec, the rpm package can be built correctly.

**To Reproduce**
Build keepalived rpm package using normal steps.
./build_setup
./configure
make rpm

**Distro (please complete the following information):**
4.18.0-80.11.2.el8_0.x86_64

**System Log entries**
checking for a sed that does not truncate output... /usr/bin/sed
checking for x86_64-redhat-linux-gnu-strip... no
checking for strip... strip
checking for x86_64-redhat-linux-gnu-ldd... no
checking for ldd... ldd
checking for x86_64-redhat-linux-gnu-ar... no
checking for x86_64-redhat-linux-gnu-lib... no
checking for x86_64-redhat-linux-gnu-link... no
checking for ar... ar
checking the archiver (ar) interface... ar
configure: error: disable-libipset-dynamic requires ipsets
error: Bad exit status from /var/tmp/rpm-tmp.ZqfkM9 (%build)

RPM build errors:
    Macro expanded in comment on line 32: %{?rhel} <= 7

    Macro expanded in comment on line 153: %{_sysconfdir}/init/keepalived.conf

    Macro expanded in comment on line 154: %{_datadir}/snmp/mibs/KEEPALIVED-MIB.txt

    Macro expanded in comment on line 155: %{_datadir}/snmp/mibs/VRRP-MIB.txt

    Macro expanded in comment on line 156: %{_datadir}/snmp/mibs/VRRPv3-MIB.txt

    Macro expanded in comment on line 162: %{_sysconfdir}/dbus-1/system.d/org.keepalived.Vrrp1.conf

    Macro expanded in comment on line 163: %{_datarootdir}/dbus-1/interfaces/org.keepalived.Vrrp1.Instance.xml

    Macro expanded in comment on line 164: %{_datarootdir}/dbus-1/interfaces/org.keepalived.Vrrp1.Vrrp.xml

    Bad exit status from /var/tmp/rpm-tmp.ZqfkM9 (%build)
make: *** [Makefile:895: rpm] Error 1

**Comment by pqarmitage** [comment]
Commit c8d2f14 resolves the issue.

In order to get around this problem with RHEL8 I downloaded the ipset SRPM package, built the rpms and installed ipset-devel from there. What is most frustrating is that RedHat are clearly building internally from a different set of RPMs, and so don't notice that the RPMs that are shipped are not the same set.
