### ISSUE TITLE
Ipv6 neighbor points to vmac for link local address even after the vrrp-v6 group is deleted

### ISSUE THREAD

**Issue by msridhar87** [acassen/keepalived#1456]
**Is your feature request to resolve a problem or provide enhanced functionality? Please describe.**
This enhancement is to solve the problem of ipv6 link local address pointing to vmac in peer even after we delete the vrrp v6 group. 

we have a link between 2 routers (R1 and R2, let the ports be P1 and P2)and IPv6 address configured. The neighbor information for the linklocal address of P1  in R2 will point to IF mac of P1. The moment we configure vrrp v6 group in P1, kernel sends out a NA and the neighbor information in R2 points to vmac. Now we go and delete the v6 vrrp group in P1, Even now the neighbor information in R2 points to vmac. 

connection details
================
R1 (E101-001-0) ------------------------- R2 (e101-001-0)

Router 1
======
Router - 1
==========
root@OS10:~# ifconfig e101-001-0
e101-001-0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        **inet6 1::1**  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::250:56ff:fe80:cd47  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:80:cd:47  txqueuelen 1000  (Ethernet)
        RX packets 18  bytes 6351 (6.2 KiB)
        RX errors 0  dropped 5  overruns 0  frame 0
        TX packets 90  bytes 12161 (11.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Router -2
=========
root@OS10:~# ifconfig e101-001-0
e101-001-0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        **inet6 1::2**  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::250:56ff:fe80:5790  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:80:57:90  txqueuelen 1000  (Ethernet)
        RX packets 1716  bytes 158299 (154.5 KiB)
        RX errors 0  dropped 64  overruns 0  frame 0
        TX packets 1890  bytes 131452 (128.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@OS10:~# ping6 1::1
PING 1::1(1::1) 56 data bytes
64 bytes from 1::1: icmp_seq=1 ttl=64 time=2018 ms
64 bytes from 1::1: icmp_seq=2 ttl=64 time=997 ms
64 bytes from 1::1: icmp_seq=3 ttl=64 time=0.818 ms
^C
--- 1::1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2021ms
rtt min/avg/max/mdev = 0.818/1005.427/2018.112/823.577 ms, pipe 2

root@OS10:~# ip neigh
100.104.34.253 dev eth0 lladdr e4:f0:04:96:df:1e STALE
100.104.34.252 dev eth0 lladdr e4:f0:04:96:c8:9e STALE
100.104.34.254 dev eth0 lladdr 00:00:5e:00:01:22 STALE
**fe80::250:56ff:fe80:cd47 dev e101-001-0 lladdr 00:50:56:80:cd:47 router REACHABLE**
fe80::e6f0:4ff:fe96:df1e dev eth0 lladdr e4:f0:04:96:df:1e router REACHABLE
fe80::e6f0:4ff:fe96:c89e dev eth0 lladdr e4:f0:04:96:c8:9e router REACHABLE
fe80::da9e:f3ff:feb2:71d5 dev eth0 lladdr d8:9e:f3:b2:71:d5 router REACHABLE
1::1 dev e101-001-0 lladdr 00:50:56:80:cd:47 router REACHABLE

Now configure vrrp v6 group in R1. After this step, neighbor information in R2 is
root@OS10:~# ip neigh
100.104.34.253 dev eth0 lladdr e4:f0:04:96:df:1e STALE
100.104.34.252 dev eth0 lladdr e4:f0:04:96:c8:9e STALE
100.104.34.254 dev eth0 lladdr 00:00:5e:00:01:22 STALE
**fe80::250:56ff:fe80:cd47 dev e101-001-0 lladdr 00:00:5e:00:02:01 router REACHABLE**
fe80::e6f0:4ff:fe96:df1e dev eth0 lladdr e4:f0:04:96:df:1e router REACHABLE
fe80::e6f0:4ff:fe96:c89e dev eth0 lladdr e4:f0:04:96:c8:9e router REACHABLE
fe80::da9e:f3ff:feb2:71d5 dev eth0 lladdr d8:9e:f3:b2:71:d5 router REACHABLE
1::1 dev e101-001-0 lladdr 00:50:56:80:cd:47 router REACHABLE

After removing the vrrp v6 group in R1, neighbor information still points to vmac in R2. 

**Describe the solution you would like**
Once we delete the v6 group, the neighbor information should be changed to IF mac.

**Describe alternatives you have considered**
Can clear the neighbor information in peer and learn the neighbors again.

**Would the feature request be of benefit only to you, or is it more generally applicable?**
Not sure
**Keepalived version**
root@OS10:~# keepalived -v
Keepalived v2.0.19 (10/19,2019)

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.9.189
Running on Linux 4.9.189 #1 SMP Debian 4.9.189-3+deb9u1

configure options: --enable-dbus --enable-dbus-create-instance

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING DBUS DBUS_CREATE_INSTANCE

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV RTA_VIA FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Additional context**
I have made the changes in keepalived. I have attached the patch files. 

[keepalived.default.conf.txt](https://github.com/acassen/keepalived/files/3885921/keepalived.default.conf.txt)
[neighbor_discovery_patch.txt](https://github.com/acassen/keepalived/files/3885922/neighbor_discovery_patch.txt)

**Comment by pqarmitage** [comment]
If you add a line `nftables` to the global_defs block, then it will add nftables configuration so that the NAs (MLD for IPv6) will be sent on the physical interface instead of the VMAC interface. This has the added benefit that no MLD reports for fe80::250:56ff:fe80:cd47 are ever sent from 00:00:5e:00:02:01 but they are always sent from 00:50:56:80:cd:47 (I love the :cd: symbol, but it is meant to say _cd_!).

For your configuration it sets the following nftables configuration
```
table ip6 keepalived {
	map vmac_map {
		type iface_index : iface_index
		elements = { "e101-001-0.v1" : "e101-001-0"}
	}

	chain out {
		type filter hook output priority -1; policy accept;
		ip6 daddr ff02::16 dup to ff02::16 device oif map @vmac_map drop
	}
}
```
