### ISSUE TITLE
dont_track_primary not working

### ISSUE THREAD

**Issue by jsfrerot** [acassen/keepalived#1465]
**Describe the bug**
I use a crossconnect cable for my firewalls as a secondary link for vrrp in case my 2 switches get diconnected from each other. This is to prevent my two firewall to become master

Now, when I reboot my SLAVE firewall that second link gets disconnected, with the "dont_track_primary" option under 1.3.5 I had no issue, but with 2.0.19, it's not working as expected and my master switch to FAULT

**To Reproduce**
create 2 vrrp_instance
set 1 with "dont_track_primary"
unplug cable from the interface with the "dont_track_primary" option

**Expected behavior**
The interface with "dont_track_primary" should not trigger keepalived to FAULT mode.

**Keepalived version**
Keepalived v2.0.19 (10/19,2019), git commit v2.0.19+

**Distro (please complete the following information):**
 - Name Centos
 - Version 7
 - Architecture x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
Running on baremetal

**Configuration file:**
vrrp_instance VI_1 {
  interface                 em4
  state                     BACKUP
  virtual_router_id         1
  priority                  10
  advert_int                1
  garp_master_delay         5
  preempt_delay             3
  dont_track_primary
...

**System Log entries**
Dec 11 12:56:56 sni-fw-002 Keepalived_vrrp[29440]: Netlink reports em4 down
Dec 11 12:57:02 sni-fw-002 Keepalived_vrrp[29440]: Deassigned address 172.31.2.2 from interface em4
Dec 11 12:57:02 sni-fw-002 Keepalived_vrrp[29440]: (VI_1) Entering FAULT STATE
Dec 11 12:57:02 sni-fw-002 Keepalived_vrrp[29440]: (VI_1) sent 0 priority
Dec 11 12:57:02 sni-fw-002 Keepalived_vrrp[29440]: (VI_1) removing VIPs.
Dec 11 12:57:02 sni-fw-002 Keepalived_vrrp[29440]: VRRP_Group(G1) Syncing instances to FAULT state
Dec 11 12:57:02 sni-fw-002 Keepalived_vrrp[29440]: (VI_3) Entering FAULT STATE
Dec 11 12:57:02 sni-fw-002 Keepalived_vrrp[29440]: (VI_3) removing VIPs.
Dec 11 12:57:12 sni-fw-002 Keepalived_vrrp[29440]: Netlink reports em4 up
Dec 11 12:57:13 sni-fw-002 Keepalived_vrrp[29440]: Assigned address 172.31.2.2 for interface em4
Dec 11 12:57:13 sni-fw-002 Keepalived_vrrp[29440]: (VI_1) Entering BACKUP STATE
Dec 11 12:57:13 sni-fw-002 Keepalived_vrrp[29440]: VRRP_Group(G1) Syncing instances to BACKUP state
Dec 11 12:57:13 sni-fw-002 Keepalived_vrrp[29440]: (VI_3) Entering BACKUP STATE
Dec 11 12:57:13 sni-fw-002 Keepalived_vrrp[29440]: Netlink reports em4 down
Dec 11 12:57:16 sni-fw-002 Keepalived_vrrp[29440]: Netlink reports em4 up
Dec 11 12:57:17 sni-fw-002 Keepalived_vrrp[29440]: (VI_1) Receive advertisement timeout
Dec 11 12:57:17 sni-fw-002 Keepalived_vrrp[29440]: (VI_3) Receive advertisement timeout
Dec 11 12:57:17 sni-fw-002 Keepalived_vrrp[29440]: (VI_3) Entering MASTER STATE
Dec 11 12:57:17 sni-fw-002 Keepalived_vrrp[29440]: (VI_3) setting VIPs.

**Comment by pqarmitage** [comment]
Commit 9cef808 resolves this issue.

**Comment by jsfrerot** [comment]
Hi @pqarmitage 
Seems I still have the issue with version 2.0.20, I see the commit in 2.0.20, but still suffer the issue.

Here are the logs:
`Jan 27 13:01:10 sni-fw-002 systemd[1]: Starting LVS and VRRP High Availability Monitor...
Jan 27 13:01:10 sni-fw-002 Keepalived[4171]: Starting Keepalived v2.0.20 (01/22,2020)
Jan 27 13:01:10 sni-fw-002 Keepalived[4171]: Running on Linux 4.4.211-1.el7.elrepo.x86_64 #1 SMP Thu Jan 23 08:11:08 EST 2020 (built fo
Jan 27 13:01:10 sni-fw-002 Keepalived[4171]: Command line: '/usr/sbin/keepalived' '-D'
Jan 27 13:01:10 sni-fw-002 Keepalived[4171]: Opening file '/etc/keepalived/keepalived.conf'.
Jan 27 13:01:30 sni-fw-002 Keepalived[4480]: Starting VRRP child process, pid=4481
...
Jan 27 13:31:17 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 down
Jan 27 13:31:20 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 up
Jan 27 13:31:25 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 down
Jan 27 13:31:29 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 up
Jan 27 13:31:40 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 down
Jan 27 13:31:43 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 up
Jan 27 13:32:04 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 down
Jan 27 13:32:08 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 up
Jan 27 13:35:45 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 down
Jan 27 13:35:48 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 up
Jan 27 13:35:52 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 down
Jan 27 13:35:57 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 up
Jan 27 13:36:00 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 down
Jan 27 13:36:03 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 up
Jan 27 13:36:25 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 down
Jan 27 13:36:28 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 up
Jan 27 13:37:05 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 down
Jan 27 13:37:09 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 up
Jan 27 13:37:56 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 down
Jan 27 13:38:02 sni-fw-002 Keepalived_vrrp[4481]: Deassigned address fe80::eef4:bbff:fedf:7a97 from interface em4
Jan 27 13:38:02 sni-fw-002 Keepalived_vrrp[4481]: Deassigned address 172.31.2.2 from interface em4
Jan 27 13:38:02 sni-fw-002 Keepalived_vrrp[4481]: (VI_1) Entering FAULT STATE
Jan 27 13:38:02 sni-fw-002 Keepalived_vrrp[4481]: (VI_1) sent 0 priority
Jan 27 13:38:02 sni-fw-002 Keepalived_vrrp[4481]: (VI_1) removing VIPs.
Jan 27 13:38:02 sni-fw-002 Keepalived_vrrp[4481]: VRRP_Group(G1) Syncing instances to FAULT state
Jan 27 13:38:02 sni-fw-002 Keepalived_vrrp[4481]: (VI_3) Entering FAULT STATE
Jan 27 13:38:02 sni-fw-002 Keepalived_vrrp[4481]: (VI_3) removing VIPs.
Jan 27 13:38:16 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 up
Jan 27 13:38:16 sni-fw-002 Keepalived_vrrp[4481]: Assigned address 172.31.2.2 for interface em4
Jan 27 13:38:16 sni-fw-002 Keepalived_vrrp[4481]: (VI_1) Entering BACKUP STATE
Jan 27 13:38:16 sni-fw-002 Keepalived_vrrp[4481]: VRRP_Group(G1) Syncing instances to BACKUP state
Jan 27 13:38:16 sni-fw-002 Keepalived_vrrp[4481]: (VI_3) Entering BACKUP STATE
Jan 27 13:38:17 sni-fw-002 Keepalived_vrrp[4481]: Netlink reports em4 down
Jan 27 13:38:20 sni-fw-002 Keepalived_vrrp[4481]: (VI_1) Receive advertisement timeout
Jan 27 13:38:20 sni-fw-002 Keepalived_vrrp[4481]: (VI_3) Receive advertisement timeout
Jan 27 13:38:20 sni-fw-002 Keepalived_vrrp[4481]: (VI_3) Entering MASTER STATE
`

and here is my config:

`vrrp_sync_group G1 {
  group {
    VI_1
    VI_3
  }
}
vrrp_instance VI_1 {
  interface                 em4
  state                     BACKUP
  virtual_router_id         1
  priority                  10
  advert_int                1
  garp_master_delay         5
  preempt_delay             3
  dont_track_primary
  notify_master "/opt/scripts/keepalived/state_change.sh INSTANCE VI_1 MASTER"
  notify_backup "/opt/scripts/keepalived/state_change.sh INSTANCE VI_1 BACKUP"
  notify_fault "/opt/scripts/keepalived/state_change.sh INSTANCE VI_1 FAULT"
  notify_stop "/opt/scripts/keepalived/state_change.sh INSTANCE VI_1 STOP"
  authentication {
    auth_type PASS
    auth_pass xxxxxxxx
  }
  track_interface {
    bond0.256
    bond1.1000
    bond1.1001
    bond1.1004
    bond1.1005
    bond1.1006
    bond1.1007
    bond1.1008
    bond1.1009
    bond1.1099
    bond1.1100
  }
  virtual_ipaddress {
    192.252.133.92/27 dev bond0.256 
    192.252.133.86/27 dev bond0.256 
    10.2.0.1/22 dev bond1.1000 
    10.2.4.1/22 dev bond1.1001 
    10.2.16.1/22 dev bond1.1004 
    10.2.20.1/22 dev bond1.1005 
    10.2.24.1/22 dev bond1.1006 
    10.2.28.1/22 dev bond1.1007 
    10.2.32.1/22 dev bond1.1008 
    10.2.36.1/22 dev bond1.1009 
    10.2.244.1/22 dev bond1.1099 
    10.2.252.1/24 dev bond1.1100 
  }
  
}
vrrp_instance VI_3 {
  interface                 bond0.202
  state                     BACKUP
  virtual_router_id         1
  priority                  10
  advert_int                1
  garp_master_delay         5
  preempt_delay             3
  authentication {
    auth_type PASS
    auth_pass xxxxxxxx
  }
  virtual_ipaddress {
    10.0.202.1/24 dev bond0.202 
  }
}
`
Note that em4 is my crossover cable, so when I reboot my Backup device, this NIC goes down which is I use dont_track_primary

**Comment by pqarmitage** [comment]
keepalived is behaving correctly here. Between 13:31:17 and 13:37:56 the link goes down and up several times and is down for no more than 5 seconds, and the keepalived instance remains in master state. Then at 13:38:02 the addresses are removed from the interface. Since keepalived uses the IPv4 address for sending adverts, it cannot continue to do so and goes to fault state due to the address being deleted. At 13:38:16 (six seconds after the link went down) the IPv4 address is reinstated and so the keepalived instance then transitions to backup and then master state.

So it seems that something removes the addresses 6 seconds after the link goes down, and it is this that causes the keepalived instance to transition to fault state. It might be NetworkManager that is removing the address, especially if the addresses are configured by NetworkManager. It may well work if you configure a static_ipaddress in keepalived to configure an address on em4, which might then not be removed following the interface going down, since keepalived would then have an address it could continue using

**Comment by jsfrerot** [comment]
@pqarmitage That is maybe the case. However this is not an issue when I use centos7 keepalived 1.3.5. When I reboot the backup server, the link on the master fails, but keepalived stays MASTER.
So if this is the expected behaviour for keepalived 2.x then I can't use it because each time I reboot the SLAVE, the MASTER switch to FAIL for a few seconds (or until the SLAVE is powered back on). In a production env I can't afford that.
However if there is another way to setup keepalived 2.x to have that same behavior 1.3.5 has, then I'd be happy to know how to configure it properly.

Note that I have configure the IP address on that crossover like this:
cat /etc/sysconfig/network-scripts/ifcfg-em4 
```
DEVICE=em4
BOOTPROTO=none
ONBOOT=yes
PREFIX=23
IPADDR=172.31.2.1
MTU=9000
```

**Comment by pqarmitage** [comment]
@jsfrerot I have done some testing with keepalived v2.0.20, and if you add the following line in the `vrrp_instance` block:
`mcast_src_ip 172.31.2.1`
then keepalived will continue using that IP address as the source address of the VRRP adverts even if the address is removed from the interface.

**Comment by jsfrerot** [comment]
@pqarmitage I just tested setting mcast_src_ip and I confirm it works for me. The master doesn't go into fail mode when the ip is unassigned (when the backup server reboots)

This solves my issue, thank you.
