### ISSUE TITLE
track_process doesn't seem to work on CentOS8.0

### ISSUE THREAD

**Issue by Mint-M** [acassen/keepalived#1468]
**Describe the bug**
track_process doesn't seem to work on CentOS8.0

**To Reproduce**
Use the configuration below to start keepalived.

**Expected behavior**
track_process works as is does on Centos7.7
Keepalived[2982]: Starting Keepalived v2.0.19 (unknown)
Keepalived[2982]: Running on Linux 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 (built for Linux 3.10.0)
Keepalived[2982]: Command line: '/usr/sbin/keepalived' '-D'
Keepalived[2982]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived[2983]: Starting VRRP child process, pid=2984
Keepalived_vrrp[2984]: Registering Kernel netlink reflector
systemd: Started LVS and VRRP High Availability Monitor.
Keepalived_vrrp[2984]: Registering Kernel netlink command channel
Keepalived_vrrp[2984]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived_vrrp[2984]: Assigned address 10.1.1.3 for interface eth0
Keepalived_vrrp[2984]: Assigned address fe80::5054:ff:fef5:8284 for interface eth0
Keepalived_vrrp[2984]: Registering gratuitous ARP shared channel
Keepalived_vrrp[2984]: (eth0) removing VIPs.
Keepalived_vrrp[2984]: (eth0) Entering BACKUP STATE (init)
Keepalived_vrrp[2984]: VRRP sockpool: [ifindex(2), family(IPv4), proto(112), unicast(0), fd(12,13)]
Keepalived_vrrp[2984]: (eth0) Receive advertisement timeout
Keepalived_vrrp[2984]: (eth0) Entering MASTER STATE
Keepalived_vrrp[2984]: (eth0) setting VIPs.
Keepalived_vrrp[2984]: Sending gratuitous ARP on eth0 for 10.1.1.1
Keepalived_vrrp[2984]: (eth0) Sending/queueing gratuitous ARPs on eth0 for 10.1.1.1
Keepalived_vrrp[2984]: Sending gratuitous ARP on eth0 for 10.1.1.1
Keepalived_vrrp[2984]: Sending gratuitous ARP on eth0 for 10.1.1.1
Keepalived_vrrp[2984]: Sending gratuitous ARP on eth0 for 10.1.1.1
Keepalived_vrrp[2984]: Sending gratuitous ARP on eth0 for 10.1.1.1
Keepalived_vrrp[2984]: Sending gratuitous ARP on eth0 for 10.1.1.1
Keepalived_vrrp[2984]: (eth0) Sending/queueing gratuitous ARPs on eth0 for 10.1.1.1
Keepalived_vrrp[2984]: Sending gratuitous ARP on eth0 for 10.1.1.1
Keepalived_vrrp[2984]: Sending gratuitous ARP on eth0 for 10.1.1.1
Keepalived_vrrp[2984]: Sending gratuitous ARP on eth0 for 10.1.1.1
Keepalived_vrrp[2984]: Sending gratuitous ARP on eth0 for 10.1.1.1
systemd: Stopping Unbound recursive Domain Name Server...
unbound: [2937:0] info: service stopped (unbound 1.6.6).
unbound: [2937:0] info: server stats for thread 0: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting
unbound: [2937:0] info: server stats for thread 0: requestlist max 0 avg 0 exceeded 0 jostled 0
unbound: [2937:0] info: server stats for thread 1: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting
unbound: [2937:0] info: server stats for thread 1: requestlist max 0 avg 0 exceeded 0 jostled 0
unbound: [2937:0] info: server stats for thread 2: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting
unbound: [2937:0] info: server stats for thread 2: requestlist max 0 avg 0 exceeded 0 jostled 0
unbound: [2937:0] info: server stats for thread 3: 0 queries, 0 answers from cache, 0 recursions, 0 prefetch, 0 rejected by ip ratelimiting
unbound: [2937:0] info: server stats for thread 3: requestlist max 0 avg 0 exceeded 0 jostled 0
Keepalived_vrrp[2984]: Quorum lost for tracked process unbound
Keepalived_vrrp[2984]: (eth0) Entering FAULT STATE
systemd: Stopped Unbound recursive Domain Name Server.
Keepalived_vrrp[2984]: (eth0) sent 0 priority
Keepalived_vrrp[2984]: (eth0) removing VIPs.

**Keepalived version**
Keepalived v2.0.19 (unknown)

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.0
Running on Linux 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Tue Sep 24 11:32:19 UTC 2019

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-nftables --disable-libipset --enable-snmp --enable-snmp-rfc --with-init=systemd --enable-bfd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LIBIPTC LVS VRRP VRRP_AUTH BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Distro (please complete the following information):**
4.18.0-80.11.2.el8_0.x86_64 #1 SMP Tue Sep 24 11:32:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Configuration file:**
global_defs {
    router_id test
    vrrp_mcast_group4 224.0.0.240
}

vrrp_track_process unbound {
    process "/usr/sbin/unbound" "-d"
}

vrrp_instance eth0 {
    state BACKUP
    interface eth0
    virtual_router_id 80
    priority 100
    advert_int 1
    virtual_ipaddress {
       10.1.1.1/16 dev eth0
    }
    track_process {
       unbound
    }
}

**System Log entries**
Keepalived[15291]: Starting Keepalived v2.0.19 (unknown)
Keepalived[15291]: Running on Linux 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Tue Sep 24 11:32:19 UTC 2019 (built for Linux 4.18.0)
Keepalived[15291]: Command line: '/usr/sbin/keepalived' '-D'
Keepalived[15291]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived[15291]: Failed to open process monitoring socket - errno 13 - Permission denied
Keepalived[15292]: Starting VRRP child process, pid=15293
systemd[1]: Started LVS and VRRP High Availability Monitor.
Keepalived_vrrp[15293]: Registering Kernel netlink reflector
Keepalived_vrrp[15293]: Registering Kernel netlink command channel
Keepalived_vrrp[15293]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived_vrrp[15293]: Assigned address 10.1.2.1 for interface eth0
Keepalived_vrrp[15293]: Assigned address fe80::5054:ff:feb7:51fa for interface eth0
Keepalived_vrrp[15293]: Failed to set/clear process event listen - errno 9 - Bad file descriptor
Keepalived_vrrp[15293]: (eth0) entering FAULT state (tracked process unbound quorum not achieved)
Keepalived_vrrp[15293]: (eth0) entering FAULT state
Keepalived_vrrp[15293]: Registering gratuitous ARP shared channel
Keepalived_vrrp[15293]: (eth0) removing VIPs.
Keepalived_vrrp[15293]: VRRP sockpool: [ifindex(2), family(IPv4), proto(112), unicast(0), fd(11,12)]

**Comment by pqarmitage** [comment]
The key log entry here appears to be:
`Keepalived[15291]: Failed to open process monitoring socket - errno 13 - Permission denied`

My guess is that this is most likely to be an SELinux permissions issue. Is there anything in the system logs at the same time reporting an SELinux permissions violation, and giving a command to run to enable the permission? Something that would be worth trying is running `setenforce Permissive` before tunning keepalived and seeing if that stops the problem occurring.

**Comment by Mint-M** [comment]
@pqarmitage Apologize for my negligence. I forgot to disable selinux on this machine. It works now.

**Comment by pqarmitage** [comment]
selinux-policy-3.14.3-20.el8 which dates from mid September included Selinux reference policy commit https://github.com/fedora-selinux/selinux-policy-contrib/commit/ec7fe75bc33ab662d1258c78b95a213f43e00d91#diff-18c45a4bf5be7f3bfdcd67ae2ee88995 which enabled  but from the kernel version reported above you haven't updated packages to that point in time.
