### ISSUE TITLE
Keepalived version 1.4.2 compile error CentOS7

### ISSUE THREAD

**Issue by immortalChensm** [acassen/keepalived#1471]
![image](https://user-images.githubusercontent.com/35517798/71571045-59409880-2b13-11ea-90d4-d34bf7719e73.png)

**Comment by pqarmitage** [comment]
keepalived v1.4.2 is too old for CentOS 7. In particular, CentOS 7 uses ipset v7, and support for that wasn't added until commit b7a98f9, which was first included in keepalived v2.0.10. It is probably sensible to upgrade to the latest version of keepalived - v2.0.19.

My guess is that RedHat backported ipset v7 to RHEL 7, and these backports of kernel functionality have caused us several problems in the past.
