### ISSUE TITLE
What does "protocol  112 unreachable" mean?

### ISSUE THREAD

**Issue by jvijay-work** [acassen/keepalived#1487]
_Support requests should be sent to_ keepalived-devel@lists.sourceforge.net

**Describe why you are unable to send the support request to the above email list**
sourceforge blocked by corporate firewall

**Describe what you need help/support for**
VIP failover from MASTER to  BACKUP not happening. 
TCPDUMP showing,
12:52:51.657678 IP <ip dest> > <ip src>: ICMP <ip dest> protocol 112 unreachable, length 48

**Details of what you would like to do with keepalived**
Desired Floating VIP across two RHEL 7 hosts.

**Keepalived version**

Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

Copyright(C) 2001-2017 Alexandre Cassen, <acassen@gmail.com>

Build options:  PIPE2 LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_OIFNAME FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK LIBIPTC LIBIPSET_DYNAMIC LVS LIBIPVS_NETLINK VRRP VRRP_AUTH VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC FIB_ROUTING INET6_ADDR_GEN_MODE SNMP_V3_FOR_V2 SNMP SNMP_KEEPALIVED SNMP_CHECKER SNMP_RFC SNMP_RFCV2 SNMP_RFCV3 SO_MARK

**Distro (please complete the following information):**
 - Name : RHEL
 - Version : 7.7
 - Architecture  x86_64 on vmware

**Details of any containerisation or hosted service (e.g. AWS)**
None

**Configuration file:**
NA

**Notify and track scripts**
None

**System Log entries**
Full keepalived system log entries from when keepalived started, if applicable

**Additional context**

**Comment by pqarmitage** [comment]
Protocol 112 is the VRRP protocol. I am guessing that your configuration is using unicast peers, and in this case the unicast peer isn't running keepalived, and so since nothing is listening for protocol 112 the configured peer is responding with an ICMP protocol unreachable message.
