### ISSUE TITLE
keepalived ignores received vrrp3 packets and checksums on master are wrong

### ISSUE THREAD

**Issue by telmich** [acassen/keepalived#1490]
**Describe the bug**
1) keepalived becomes master even though the operating system receives vrrp3 messages and the firewall is off
2) The sending keepalived seems to have wrong checksums in the vrrp packet

**To Reproduce**
I have the following two keepalived versions, one from alpine, one from devuan (this is an ongoing migration project) and start the "secondary" process on alpine, which after 3 seconds becomes the master even though it should not.

**Expected behavior**
1) keepalived does not become master  (alpine)
2) keepalived sends correct checksum (devuan)

**Keepalived version**
Output of `keepalived -v`

```
Devuan:
[13:23:16] router1.place5:~# keepalived --version
Keepalived v2.0.10 (11/12,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.20
Running on Linux 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15)
```

Alpine:
```
[13:24] router2.place5:~# keepalived --version
Keepalived v2.0.20 (01/25,2020), git commit v20200122-61-g49e4673747

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.4.5
Running on Linux 5.4.7-0-lts #1-Alpine SMP Thu, 02 Jan 2020 11:19:52 UTC
```

**Distro (please complete the following information):**
- devuan beowulf (= debian 10)
- alpine 3.12

**Details of any containerisation or hosted service (e.g. AWS)**
bare metal

**Configuration file:**
devuan config:
```
#
# cdist maintained - do not modify on the system, changes will be overwritten
#
global_defs {
    vrrp_version 3
}


vrrp_instance router_v6 {
    interface bond0.5
    virtual_router_id 1
    priority 150
    advert_int 1
    virtual_ipaddress {
        fe80::1/64 dev lo
        2a0a:e5c0:0:0::1/64 dev br-server
        2a0a:e5c0:0:2::1/64 dev bond0.3
        2a0a:e5c0:0:5::1/64 dev bond0.3
        2a0a:e5c0:0:6::1/64 dev bond0.5
        2a0a:e5c0:0:4::1/64 dev bond0.7
    }
    notify_backup "/usr/local/bin/vrrp_notify_backup.sh"
    notify_fault "/usr/local/bin/vrrp_notify_fault.sh"
    notify_master "/usr/local/bin/vrrp_notify_master.sh"
}
vrrp_instance router_v4 {
    interface bond0.5
    virtual_router_id 2
    priority 150
    advert_int 1
    virtual_ipaddress {
        185.203.112.1/24 dev bond0.3
        10.0.0.1/22 dev bond0.5
        10.0.8.1/22 dev bond0.7
    }
}
```

Alpine config:

```
#
# cdist maintained - do not modify on the system, changes will be overwritten
#
global_defs {
    vrrp_version 3
}


vrrp_instance router_v6 {
    interface bond0.5
    virtual_router_id 1
    priority 10
    advert_int 1
    virtual_ipaddress {
        fe80::1/64 dev lo
        2a0a:e5c0:0:0::1/64 dev bond0.2
        2a0a:e5c0:0:2::1/64 dev bond0.3
        2a0a:e5c0:0:5::1/64 dev bond0.3
        2a0a:e5c0:0:6::1/64 dev bond0.5
        2a0a:e5c0:0:4::1/64 dev bond0.7
    }
    notify_backup "/usr/local/bin/vrrp_notify_backup.sh"
    notify_fault "/usr/local/bin/vrrp_notify_fault.sh"
    notify_master "/usr/local/bin/vrrp_notify_master.sh"
}
vrrp_instance router_v4 {
    interface bond0.5
    virtual_router_id 2
    priority 10
    advert_int 1
    virtual_ipaddress {
        185.203.112.1/24 dev bond0.3
        10.0.0.1/22 dev bond0.5
        10.0.8.1/22 dev bond0.7
    }
}
```

**Notify and track scripts**
```
[13:31] router2.place5:~# cat /usr/local/bin/vrrp_notify_backup.sh
#!/bin/sh


/etc/init.d/radvd stop
/etc/init.d/openvpn stop
/etc/init.d/isc-dhcp-server stop
[13:31] router2.place5:~# cat /usr/local/bin/vrrp_notify_master.sh
#!/bin/sh

/etc/init.d/radvd start
/etc/init.d/openvpn start
/etc/init.d/isc-dhcp-server start
[13:31] router2.place5:~# 
```

**System Log entries**

[13:23] router2.place5:~# keepalived -n -D -l
Thu Jan 30 13:23:46 2020: Starting Keepalived v2.0.20 (01/25,2020), git commit v20200122-61-g49e4673747
Thu Jan 30 13:23:46 2020: Running on Linux 5.4.7-0-lts #1-Alpine SMP Thu, 02 Jan 2020 11:19:52 UTC (built for Linux 5.4.5)
Thu Jan 30 13:23:46 2020: Command line: 'keepalived' '-n' '-D' '-l'
Thu Jan 30 13:23:46 2020: Opening file '/etc/keepalived/keepalived.conf'.
Thu Jan 30 13:23:46 2020: Starting VRRP child process, pid=70033
Thu Jan 30 13:23:46 2020: Registering Kernel netlink reflector
Thu Jan 30 13:23:46 2020: Registering Kernel netlink command channel
Thu Jan 30 13:23:46 2020: Opening file '/etc/keepalived/keepalived.conf'.
Thu Jan 30 13:23:46 2020: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Thu Jan 30 13:23:46 2020: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Thu Jan 30 13:23:46 2020: Assigned address 10.0.0.4 for interface bond0.5
Thu Jan 30 13:23:46 2020: Assigned address fe80::21b:21ff:febc:bfd8 for interface bond0.5
Thu Jan 30 13:23:46 2020: Registering gratuitous ARP shared channel
Thu Jan 30 13:23:46 2020: Registering gratuitous NDISC shared channel
Thu Jan 30 13:23:46 2020: (router_v6) removing VIPs.
Thu Jan 30 13:23:46 2020: (router_v4) removing VIPs.
Thu Jan 30 13:23:46 2020: (router_v6) Entering BACKUP STATE (init)
Thu Jan 30 13:23:46 2020: (router_v4) Entering BACKUP STATE (init)
Thu Jan 30 13:23:46 2020: VRRP sockpool: [ifindex(15), family(IPv6), proto(112), unicast(0), fd(12,13)]
Thu Jan 30 13:23:46 2020: VRRP sockpool: [ifindex(15), family(IPv4), proto(112), unicast(0), fd(14,15)]

Thu Jan 30 13:23:50 2020: (router_v4) Receive advertisement timeout
Thu Jan 30 13:23:50 2020: (router_v4) Entering MASTER STATE
Thu Jan 30 13:23:50 2020: (router_v4) using locally configured advertisement interval (1000 milli-sec)
Thu Jan 30 13:23:50 2020: (router_v4) setting VIPs.
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.3 for 185.203.112.1
Thu Jan 30 13:23:50 2020: (router_v4) Sending/queueing gratuitous ARPs on bond0.3 for 185.203.112.1
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.5 for 10.0.0.1
Thu Jan 30 13:23:50 2020: (router_v4) Sending/queueing gratuitous ARPs on bond0.5 for 10.0.0.1
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.7 for 10.0.8.1
Thu Jan 30 13:23:50 2020: (router_v4) Sending/queueing gratuitous ARPs on bond0.7 for 10.0.8.1
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.3 for 185.203.112.1
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.5 for 10.0.0.1
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.7 for 10.0.8.1
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.3 for 185.203.112.1
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.5 for 10.0.0.1
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.7 for 10.0.8.1
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.3 for 185.203.112.1
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.5 for 10.0.0.1
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.7 for 10.0.8.1
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.3 for 185.203.112.1
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.5 for 10.0.0.1
Thu Jan 30 13:23:50 2020: Sending gratuitous ARP on bond0.7 for 10.0.8.1
^CThu Jan 30 13:23:52 2020: Stopping
Thu Jan 30 13:23:52 2020: (router_v4) sent 0 priority
Thu Jan 30 13:23:52 2020: (router_v4) removing VIPs.
Thu Jan 30 13:23:53 2020: Stopped - used 0.000000 user time, 0.016318 system time
Thu Jan 30 13:23:53 2020: Stopped Keepalived v2.0.20 (01/25,2020), git commit v20200122-61-g49e4673747

**Additional context**
The versions are slightly different, but the configuration is the same.

I am using one ipv6 vrrp instance which SEEMS to be doing the right job, only the IPv4 version causes a problem.

**Comment by telmich** [comment]
Regarding the checksums: I was sniffing traffic and according to tcpdump the checksum of the devuan instance is incorrect.

**Comment by telmich** [comment]
Copy from wireshark of the packet from the devuan system:

```
Virtual Router Redundancy Protocol
    Version 3, Packet type 1 (Advertisement)
    Virtual Rtr ID: 2
    Priority: 150 (Non-default backup priority)
    Addr Count: 3
    0000 .... = Reserved: 0
    .... 0000 0110 0100 = Adver Int: 100
    Checksum: 0x082d incorrect, should be 0xe862
        [Expert Info (Warning/Checksum): Bad checksum [should be 0xe862]]
    [Checksum Status: Bad]
    IP Address: 185.203.112.1
    IP Address: 10.0.0.1
    IP Address: 10.0.8.1
```

**Comment by pqarmitage** [comment]
The checksum of 0x082d looks correct to me (based on the ip address being used by devuan being 10.0.0.3); my recollection is the some older version of wireshark incorrectly reported bad checksums.

I have run your configurations, using keepalived v2.0.10 for the higher priority instances and keepalived v2.0.20 for the lower priority instances, and with a standard configuration it works fine.

If I configure alpine with an IP address of 10.0.0.4/32 (note the mask) then one second after becoming master, it receives a higher priority advert from devuan and drops back to being backup for 3 seconds then times out and becomes master again. The reason is that an advert with source address 10.0.0.3 is being dropped by the kernel since it has no reverse path for 10.0.0.3. When alpine becomes master, it adds address 10.0.0.1/24, thereby creating a reverse path for 10.0.0.3, and so it then receives adverts, sees that devuan has high priority, reverts to backup, removes address 10.0.0.1/24, has no reverse path to 10.0.0.3 and goes round in circles.

This may not be quite your scenario, but it appears that alpine is unable to receive adverts from devuan, and hence it becomes master. This is quite a common problem that people experience when setting up keepalived on a system for the first time, and usually relates to some routing or firewall issue.

The circumstances described above do not related to interworking between keepalived versions 2.0.10 and 2.0.20; they also occur with both instances being v2.0.20.

**Comment by telmich** [comment]
Thanks a lot for the quick follow up. I just saw that alpine by default installs reverse path filters as follows:

```
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.rp_filter = 1
```
I have resetted the rp_filter to 0 on all interfaces, however the result is still the same at the moment

```
/proc/sys/net/ipv4/conf# for f in */rp_filter; do echo $f; echo 0 > $f; done
``` 
I'll further investigate whether this is an alpine / config problem, the hint is much appreciated

**Comment by misterunknown** [comment]
@telmich Hm, I just saw your link in #alpine-linux... I recently saw a tweet which could maybe related to the rp_filter problem: https://twitter.com/nblr/status/1218542199551483906

You should check, if the setting is really active.

**Comment by telmich** [comment]
I was fearing that, too and I did actually disable it for all interfaces, as far as I can see:
```
[16:45] router1.place6:/proc/sys/net/ipv4/conf# cat */rp_filter
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
[16:58] router1.place6:/proc/sys/net/ipv4/conf# 
```

**Comment by telmich** [comment]
I found a new error message! It seems that someone in our team (not hinting at anyone) turned on nft while I was away and that actually did filter something.

Now keepalived on alpine DOES receive the message and DOES complain about incorrect checksums! So happy!

```
Thu Jan 30 18:27:22 2020: VRRP sockpool: [ifindex(14), family(IPv6), proto(112), unicast(0), fd(12,1
3)]                                                                                                 
Thu Jan 30 18:27:22 2020: VRRP sockpool: [ifindex(14), family(IPv4), proto(112), unicast(0), fd(14,1
5)]                                                                                                 
Thu Jan 30 18:27:22 2020: (router_v4) Invalid VRRPv3 checksum             
Thu Jan 30 18:27:23 2020: (router_v4) Invalid VRRPv3 checksum                                   
Thu Jan 30 18:27:24 2020: (router_v4) Invalid VRRPv3 checksum             
Thu Jan 30 18:27:25 2020: (router_v4) Invalid VRRPv3 checksum  
  ```

Now I only need to find out why keepalived on devuan creates the invalid checksum...

**Comment by telmich** [comment]
WAIT. Is it possible that the detection checksum code changed between the two versions?

**Comment by telmich** [comment]
So I claim that the VRRP3 code does not work correctly, because switching to VRRP2 for IPv4 by commenting out the following config, fixes the problem:

```
#global_defs {
#   vrrp_version 3
#}

```

**Comment by pqarmitage** [comment]
The only time I remember the checksum calculation changing is covered by the following comment in the keepalived.conf(5) man page:
```
    # The checksum calculation when using VRRPv3 changed after v1.3.6.
    #  Setting this flag forces the old checksum algorithm to be used
    #  to maintain backward compatibility, although keepalived will
    #  attempt to maintain compatibility anyway if it sees an old
    #  version checksum. Specifying never will turn off auto detection
    #  of old checksums. [This option may not be enabled - check output
    #  of `keepalived -v` for OLD_CHKSUM_COMPAT.]
    \fBold_unicast_checksum \fR[never]
```
so that doesn't appear to be relevant here.

Could you please try the following:
1) Capture the VRRP packets with wireshark/tcpdump and post the capture file here so that we can see the actual packets (please also post the IP addresses of devuan and alpine)
2) Can you build keepalived v2.0.10 on Alpine and see if you still have a problem

**Comment by telmich** [comment]
Compiling 2.0.10 now, testing:

* IPv4/vrrp2 still ok
* 2.0.10 on alpine also reports `Invalid VRRPv3 checksum`
* Attached are the vrrp packets from devuan as received by alpine: vrrplog20200131.pcap.gz
* Also attached a tcpdump from devuan - which also shows the incorrect checksum, so it's not broken on transfer

[vrrplog20200131.pcap.gz](https://github.com/acassen/keepalived/files/4139847/vrrplog20200131.pcap.gz)
[vrrplog-devuan.pcap.gz](https://github.com/acassen/keepalived/files/4139857/vrrplog-devuan.pcap.gz)

**Comment by telmich** [comment]
Ok, it seems that NAT44 that was activated caused the problem. I'm very, very sorry for the noise.

For the reference, we had these lines in our firewall:

```
-table ip nat {
-        chain prerouting {
-                type nat hook prerouting priority 0; policy accept;
-
-                ip daddr 185.203.114.3 dnat 10.3.16.20
-                ip daddr 185.203.114.4 dnat 10.3.16.21
-        }
-
-        chain postrouting {
-                type nat hook postrouting priority 100; policy accept;
-
-                # pEp
-                ip saddr 10.3.16.20 snat to 185.203.114.3
-                ip saddr 10.3.16.21 snat to 185.203.114.4
-
-                # Default NAT
-                ip saddr 10.3.0.0/16 ip daddr != 10.0.0.0/8 snat to 185.203.114.1
-        }
-}
```

**Comment by pqarmitage** [comment]
Many thanks for the update. The NAT is something else to add to the list of things to consider when issues get raised.

If you changed the rules from `ip daddr 185.203.114.3 dnat 10.3.16.20` to `ip daddr 185.203.114.3 dnat 10.3.16.20 accept` and so on, it would make the processing slightly more efficient, since once a NAT happens, the following rules won't be traversed.

Anyway, it's good that you have got it all sorted.

**Comment by acassen** [comment]
truly interresting ! @pqarmitage maybe this can be a hint for the so strange issue about csum alteration we get once...
