### ISSUE TITLE
typo in keepalived.spec.in

### ISSUE THREAD

**Issue by Mint-M** [acassen/keepalived#1497]
**Describe the bug**
'make rpm' would result build failure.

**To Reproduce**
Any steps necessary to reproduce the behaviour:
Building RPM package with the latest source code.

I'm afraid that 'Require' in line 38 and line 39 of keepalived.spec.in should be replace with 'Requires'.

make[4]: Entering directory '/root/keepalived-master'
make[4]: Leaving directory '/root/keepalived-master'
test -n "" \
|| find "keepalived-2.0.20" -type d ! -perm -755 \
	-exec chmod u+rwx,go+rx {} \; -o \
  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
  ! -type d ! -perm -444 -exec /bin/sh /root/keepalived-master/install-sh -c -m a+r {} {} \; \
|| chmod -R a+r "keepalived-2.0.20"
make[3]: Leaving directory '/root/keepalived-master'
tardir=keepalived-2.0.20 && ${TAR-tar} chof - "$tardir" | eval GZIP= gzip --best -c >keepalived-2.0.20.tar.gz
make[2]: Leaving directory '/root/keepalived-master'
if test -d "keepalived-2.0.20"; then find "keepalived-2.0.20" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "keepalived-2.0.20" || { sleep 5 && rm -rf "keepalived-2.0.20"; }; else :; fi
make[1]: Leaving directory '/root/keepalived-master'
rpmbuild -ba --build-in-place keepalived.spec
error: line 39: Unknown tag: Require: libnl3
make: *** [Makefile:895: rpm] Error 1

**Expected behavior**

**Keepalived version**
Output of `keepalived -v`

**Distro (please complete the following information):**
4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
A full copy of the configuration file, obfuscated if necessary to protect passwords and IP addresses

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started

**Did keepalived coredump?**
If so, can you please provide a stacktrace from the coredump, using gdb.

**Additional context**

**Comment by pqarmitage** [comment]
Many thanks for reporting this. Commit 0f99f34 resolves the issue.
