### ISSUE TITLE
Keepalived have web UI ?

### ISSUE THREAD

**Issue by Nurlan199206** [acassen/keepalived#1501]
Any WEB UI for keepalived?

**Comment by pqarmitage** [comment]
No there isn't a Web UI for keepalived. keepalived does have SNMP support, so it would be possible to use an SNMP base network monitoring tool with a web interface to view the status of keeaplived.

There are many open source SNMP packages available, so of which are listed at https://opensource.com/article/19/2/network-monitoring-tools, although I haven't tried any of them.
