### ISSUE TITLE
[question] same network for VIP and physical IP with use_vmac

### ISSUE THREAD

**Issue by ak503** [acassen/keepalived#1503]
Hello! 
I have next vrrp conf:

interface:
`
ethernet0: 192.168.1.1/24 
`
vrrp: 
```
vrrp_instance 1 {
    accept
    interface ethernet0
    virtual_router_id 1
    use_vmac vrrp0.1
    priority 100
    virtual_ipaddress {
        192.168.1.100/24
    }
}
```

On client with ip `192.168.1.2/24` i have:
```
ip neigh show
192.168.1.1 dev ethernet0 lladdr 08:00:27:20:55:25
192.168.1.100 dev ethernet0 lladdr 00:00:5e:00:01:01
```

`ping 192.168.1.1` is ok, but `ping 192.168.1.100` is not go

How i can use vmac and same network for VIP and physical IP?

**Comment by ak503** [comment]
problem was in virtual mashine

**Comment by Urvik08** [comment]
@ak503 Would you mind sharing the problem and how did you troubleshoot? I am seeing similar issue on my setup.

**Comment by ak503** [comment]
@Urvik08, I think virtual boxes have some problem for L2. I tested on real machines. And keepalived works well
