### ISSUE TITLE
Clear the statistics for VRRP

### ISSUE THREAD

**Issue by VasumathyJ** [acassen/keepalived#1506]
I started using keepalived recently. I can send the STATS signal to dump the statistics data for VRRP.
I can see the values of stats counters such as AdvertiseRcvd in the json format.
I want to be able to clear the stats counters - i thought that sending a SIGHUP to keepalived will clear the counters.
However SIGHUP seems to be only reloading the config.
Is there any way by which I can clear the existing values of the VRRP stats counters so that all counter values reset and starts from 0 again?

**Comment by pqarmitage** [comment]
I think the best way to do this is a configuration option to clear the stats after they are dumped.

@VasumathyJ Would that work for you?

**Comment by VasumathyJ** [comment]
It would be better if the option can clear the stats on demand - we will not always want the stats to be cleared after it is dumped. 
Thanks, I will wait for the feature to be included in a subsequent release.

**Comment by pqarmitage** [comment]
The problem with clearing the stats on demand is that there will be a window between reading the stats and clearing the stats, and any event recorded in the stats during that window will be lost.

Could you please describe in more detail what you are wanting to achieve, so that we can what is the best way to implement a solution for your needs that is also generally useful to other users.

**Comment by VasumathyJ** [comment]
Hi Quentin,
We are enabling VRRP on two of our routers so that they act as a redundant pair for downstream clients.In general our product provides the ability to view current statistics on all interfaces and also an ability to clear the ststs counters on all interfaces.
VRRP is a new feature that we are adding on our interfaces now. To adhere with our product guidelines, we need an ability to dump VRRP stats - which is already provided in keepalived via the STATS signal.
But we also need an ability to clear and reset stats counters to 0. Typically reset of counters is done during debugging to narrow down problems to a small window. If you compare with Cisco routers, typically on the interface an ability to clear counters is provided.
We actually do not need an ability to clear stats each time it gets dumped. We just need an ability to clear stats on demand. If that causes a small window of stats to be lost that is acceptable to us - Cisco router clear stats also typically have a similar window of stats loss when clear counters is invoked.
Regards,Vasumathy
    On Tuesday, 25 February 2020, 13:31:12 GMT+5:30, Quentin Armitage <notifications@github.com> wrote:  
 
 
Reopened #1506.

**Comment by pqarmitage** [comment]
Commit f8b7b4f adds an additional signal (SIGRTMAX - 1) that dumps the stats and clears them. I was not happy with the idea of clearing the stats independently of writing them, with the potential to lose some data, even if Cisco are happy to do so. Doing it this way means that other users will be able to use it without any loss of stats.

To get the relevant signal number, run `keepalived --signum=STATS_CLEAR`.
