### ISSUE TITLE
arp issues - arp_proxy and arp_proxy_pvlan

### ISSUE THREAD

**Issue by VasumathyJ** [acassen/keepalived#1507]
This is not a bug report. Just a request to document additional linux kernel parameters which can cause well known arp issues.

https://www.keepalived.org/doc/software_design.html
We had reviewed all the arp related params mentioned in above link. 
I also saw that the code modifies these params as mentioned in the comments in vrrp_if_config.c file

However even after reviewing all those params we still had an issue where when an arp req comes for the Virtual IP, the Master correctly responds with the virtual MAC but subsequently the Slave was also responding to the arp request for virtual IP with its physical MAC. The Slave's arp response came later and the client updated its arp table for the virtual IP with the physical MAC of the slave.

On further study we realized that the following arp params also had to be disabled in our environment - arp_proxy and arp_proxy_pvlan
Both had to be set to 0 on the parent interface.

We spent about 4-5 days figuring out the above. Including these arp params also in your documentation for review will help others who might hit the same problem.

**Comment by pqarmitage** [comment]
I assume you mean proxy_arp and proxy_arp_pvlan.

In order to be able to add something meaningful to the documentation, can you please describe the scenario that means that it is necessary to set these parameters to 0, since in most cases it is not necessary. In particular, I am not clear why the slave is sending an ARP response for an IP address that it hasn't got configured.

**Comment by VasumathyJ** [comment]
Hi Quentin,
Proxy ARP is a technique by which a proxy device on a given network answers the ARP queries for an IP address that is not on that network. The proxy is aware of the location of the traffic's destination, and offers its own MAC address as the (ostensibly final) destination.

On my interface proxy arp was enabled, hence the slave also responded to the arp request.
Regards,Vasumathy

Sent from Yahoo Mail on Android 
 
  On Tue, Feb 25, 2020 at 11:38 PM, Quentin Armitage<notifications@github.com> wrote:   
I assume you mean proxy_arp and proxy_arp_pvlan.

In order to be able to add something meaningful to the documentation, can you please describe the scenario that means that it is necessary to set these parameters to 0, since in most cases it is not necessary. In particular, I am not clear why the slave is sending an ARP response for an IP address that it hasn't got configured.

**Comment by pqarmitage** [comment]
Commit 9672ec3 adds a comment at the end of the keepalived.conf(5) man page.

Many thanks for reporting this problem.
