### ISSUE TITLE
Cannot change instance name at a reload - please restart

### ISSUE THREAD

**Issue by chenwng** [acassen/keepalived#1513]
**Describe the bug**

Hi,

When keepalived is running and the config file is truncated and keepalived is notified by HUP to reload,  `Cannot change instance name at a reload - please restart` is reported. And after this,  even with the original config file, keepalived cannot be reloaded and still reports the same error.

I understand an empty config file may not be a valid scenario. But during debugging, I found in this case, keepalived sets the instance name in global_data incorrectly.

https://github.com/acassen/keepalived/blob/dcb9e40d1c7cbe1d8ddfb54529d60b11f063706f/keepalived/core/main.c#L616

https://github.com/acassen/keepalived/blob/dcb9e40d1c7cbe1d8ddfb54529d60b11f063706f/keepalived/core/main.c#L632

In the above snippets, if unsupported_change is true, the global_data is restored but with empty instance_name.  And after that, no matter whatever the instance_name is set in the new config file,  keepalived won't accept it.

**To Reproduce**

* Create a simple keepalive.conf and run keepalived with it.
* Back up  keepalive.conf and truncate it.
* Reload keepalived with HUP signal. The error message is expected
* Restore keepalive.conf and reload keepalived again.

**Expected behavior**

Keepalived will keep the instance name and reload successfully with correct config file.

**Keepalived version**
Tested on Keepalived v2.0.18, but found the same code in master branch

**Distro (please complete the following information):**
CentOS 7

**Additional context**
Suggest to remove the lines from https://github.com/acassen/keepalived/blob/dcb9e40d1c7cbe1d8ddfb54529d60b11f063706f/keepalived/core/main.c#L614 to
https://github.com/acassen/keepalived/blob/dcb9e40d1c7cbe1d8ddfb54529d60b11f063706f/keepalived/core/main.c#L616
Because I think free_global_data will take care of the cleanup job later.

**Comment by pqarmitage** [comment]
@chenwng Many thanks for reporting this. Commit 13d1b2d implements your suggested change, and makes the same changes for net_namespace and nftables table name which had the same problems.

**Comment by chenwng** [comment]
Thanks!
