### ISSUE TITLE
keepalived >=2.0.19 does not build with --disable-lvs and --disable-libipset-dynamic

### ISSUE THREAD

**Issue by stintel** [acassen/keepalived#1516]
**Describe the bug**
keepalived >=2.0.19 does not build with --disable-lvs and --disable-libipset-dynamic

**To Reproduce**
./configure --disable-lvs --disable-libipset-dynamic
make

**Expected behavior**
keepalived builds

**Observed behavior**
```
make[2]: Entering directory '/home/stijn/Development/keepalived/keepalived'
  CCLD     keepalived
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: vrrp/libvrrp.a(vrrp_ipset.o): in function `ipset_initialise':
/home/stijn/Development/keepalived/keepalived/vrrp/vrrp_ipset.c:324: undefined reference to `keepalived_modprobe'
collect2: error: ld returned 1 exit status
```

**Keepalived version**
N/A

**Distro (please complete the following information):**
 - Name: OpenWrt
 - Version: master
 - Architecture: x86/64, mips64

**Details of any containerisation or hosted service (e.g. AWS)**
N/A

**Configuration file:**
N/A

**Notify and track scripts**
N/A

**System Log entries**
N/A

**Did keepalived coredump?**
N/A

**Additional context**
N/A

**Comment by pqarmitage** [comment]
Many thanks for reporting this. Commit 42c020a resolves the issue (it was checking for an incorrect define generated by configure).

The patch appears to apply cleanly to v2.0.19.
