### ISSUE TITLE
keepalived+nginx so slowly

### ISSUE THREAD

**Issue by lindychan** [acassen/keepalived#1522]
I installed and configured keepalive+nginx for HA, but the application is particularly slow through VIP access, sometimes even access timeout, how to solve?
Here is my configuration:

`! Configuration File for keepalived

global_defs {
   notification_email {
     acassen@firewall.loc
     failover@firewall.loc
     sysadmin@firewall.loc
   }
   notification_email_from Alexandre.Cassen@firewall.loc
   smtp_server 192.168.200.1
   smtp_connect_timeout 30
   router_id LVS_DEVEL
   vrrp_skip_check_adv_addr
   vrrp_strict
   vrrp_garp_interval 0
   vrrp_gna_interval 0
}
vrrp_script chk_nginx {
	script "/etc/keepalived/nginx_check.sh"
	interval 2
	weight -20
}
vrrp_instance VI_1 {
    state MASTER
    interface ens33
    virtual_router_id 52
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    track_script {
		chk_nginx
	}
    virtual_ipaddress {
        192.168.5.240/24 dev ens33
    }
    virtual_routes {
        default via 192.168.5.1    # 设置默认网关
    }
}
vrrp_instance VI_2 {
    state MASTER
    interface ens32
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    track_script {
		chk_nginx
	}
    virtual_ipaddress {
        192.168.10.240/24 dev ens32
    }
    virtual_routes {
        #default via 192.168.10.1    # 设置默认网关
    }`

**Comment by pqarmitage** [comment]
My understanding is that your problem is that access via the VIP addresses is slow.

If the VIP addresses are configured on the system, then keepalived has done it's job, and access via the VIPs is not a keepalived issue. The best thing to try is to configure the VIPs/virtual routes manually without running keepalived, and see what happens in that scenario.

**Comment by pqarmitage** [comment]
Closing due to response for over 1 week. If the problem persists then please provide the information requested in the comment above and the issue can be reopened.
