### ISSUE TITLE
Keepalived_healthcheckers logs

### ISSUE THREAD

**Issue by senthilnathann** [acassen/keepalived#1523]
_Support requests should be sent to_ keepalived-devel@lists.sourceforge.net

**Describe why you are unable to send the support request to the above email list**
Understanding why you cannot use the email list should help us improve it.

**Describe what you need help/support for**
A clear and concise description of what you need help with.
Hi,
Is there any posibilities to write the keepalived health checkers log separately ?

Ex : Keepalived_healthcheckers need to write in /var/log/keepalived_health.log
Keepalived_vrrp need to write in /var/log/keepalived_vrrp.log

Pls help me on this.

**Details of what you would like to do with keepalived**
Describe in details what you would like to achieve with keepalived

**Keepalived version**
Output of `keepalived -v` (a later version of keepalived might be needed).
Keepalived v2.0.7

**Distro (please complete the following information):**
 - Name CentOS
 - Version 7.4.1708
 - Architecture : x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details 

**Configuration file:**
Full copy of your configuration file, obfuscated if necessary to protect passwords and IP addresses

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started, if applicable

**Additional context**

**Comment by pqarmitage** [comment]
The straightforward answer to your question is Yes.

If you look at the log entries from keepalived, they should have, in the application field, one of`Keepalived`, Keepalived_vrrp`, `Keepalived_healthcheckers` or `Keepalived_bfd`.

You can configure your syslogger to log entries to different files based on the application, which will achieve what you want. How to do that is beyond the scope of keepalived itself.

**Comment by senthilnathann** [comment]
Yes , actually i am using "-S" option in /etc/sysconfig/keepalived file,that send all messages to my custom logs file.
I want to segregate the logs keepalived_vrrp , keepalived_healthcheckers logs in separate file.

For default (without -S ) , keepalived_vrrp logs are logged in messages ( local1) and keepalived_healthcheckers are logged in ( local2),if we have local2 configured in rsyslog.

Is able to do the same scenario using "-S" option ?

**Comment by pqarmitage** [comment]
Whether you need to specify the '-S' option to keepalived depends on how your system is set up to handle syslogging. For example (I am taking this from some old rsyslog configuration I used to use) with rsyslog you could have entries like the following in /etc/rsyslog.conf:
```
if $programname == 'Keepalived_healthchechers' then /var/log/keepalived/healthchecker.log
if $programname == 'Keepalived_healthcheckers' then ~
if $programname == 'Keepalived_vrrp' then /var/log/keepalived/vrrp.log
if $programname == 'Keepalived_vrrp' then ~
if $programname == 'Keepalived' then /var/log/keepalived/parent.log
if $programname == 'Keepalived' then ~
```

**Comment by senthilnathann** [comment]
Thanks ,It's working fine,Thanks for your valuable help. ....
