### ISSUE TITLE
keepalived logging

### ISSUE THREAD

**Issue by VParande** [acassen/keepalived#1525]
I need some more details about keepalived logging.
As per keepalived man page it supports different log levels. 
With this option -S, --log-facility=[0-7] i tried different values. But i did see any difference.

So I want to know what are all the different logs supported by keepalived.

**Comment by pqarmitage** [comment]
See issue #1523 for more comments on how to use logging. You will need to modify your syslog configuration to make use of keepalived logging to different levels.
