### ISSUE TITLE
Using STOP state for instances, deleted during a configuration reload

### ISSUE THREAD

**Issue by zdc** [acassen/keepalived#1526]
The current behavior of keepalived is to send `FAULT` status notifier for VRRP instances, deleted from the configuration file. There is even a special comment inside the vrrp.c about this: https://github.com/acassen/keepalived/blob/f0f31557ead9dd12343e5d9613a6e5fcdedf33aa/keepalived/vrrp/vrrp.c#L4082-L4087

From the first view, using the `STOP` state notifier should describe a situation more accurately. But the commit which adds this part of code is pretty fresh (https://github.com/acassen/keepalived/commit/8ee29f0d88cc5b9b23387d2a81ccb678137a87be), so it looks like there must be some non-obvious reason to use `FAULT` instead of `STOP`.

We actively using scripts for automation and want to be in-sync with the keepalived logic to avoid creating needless code. It would be great to get some comments about why was decided to use the `FAULT` state.
Or, if there is really no blockers, switch state to `STOP`, to make possible using stop scripts for deleted instances.

@pqarmitage maybe you can comment this moment a bit?

**Comment by pqarmitage** [comment]
`STOP` means that keepalived is shutting down, and so it would be inappropriate to send `STOP` for a VRRP instance that is deleted on a reload.

I think the comment in the commit referred to above explains the reasons why `FAULT` is sent:
```
	/* We don't have a way of saying that an instance is deleted;
	 * the nearest thing is to say the instance is in fault state,
	 * i.e. it cannot run, which it certainly can't if it isr
	 * deleted. */
```

I don't think we can change what is being sent when an instance is deleted, since other users may rely on `FAULT` being sent.

Perhaps your scripts, when receiving a `FAULT` message, should grep the keepalived config file looking for the VRRP instance, and if it doesn't exist, it should treat it as deleted.

**Comment by zdc** [comment]
Thank you, @pqarmitage, for the comment!

I have understood your main idea here. Yes, true, currently it looks like we need to parse a config file or apply some other intermediate action to detect such situations.

I am not trying to convince you into switching to another behavior but want to show you some situations in which the current one may confuse customers. Maybe this can help you to improve somehow the situation - like adding a new internal DELETED state or something like this.

If we configure some scripts, which send alarms to some target, how these alarms generally are treating:

- MASTER or BACKUP events - VRRP is in a normal state, no action is necessary;
- FAULT event - a VRRP instance or router require some action to fix failure state;
- STOP event - VRRP instance was stopped and not require any actions if we believe that there are no related bugs in a router of course.

That is why the FAULT event may confuse.
And, if we look from each VRRP instance point of view - when you are deleting instance from config, this means that you are stopping to serve this instance. And STOP event is expected here.

But again - I am only trying to provide you some alternative point of view, to show that the current situation may be improved further.
We will be happy to see some native way to distinguish the actual FAULT state from deleting an instance from a config. And the exact solution for this does not matter.

Thank you!

**Comment by pqarmitage** [comment]
Commit 2e1b19b adds an option for sending "DELETED" rather than "FAULT" after a VRRP instance is deleted on a reload.

In order to make keepalived send DELETED, you need to specify `notify_deleted` on each VRRP instance for which you want it to occur.
