### ISSUE TITLE
Role swap due to time lag between nodes

### ISSUE THREAD

**Issue by Sankaranarayanans** [acassen/keepalived#1529]
****Describe what you need help/support for****

We having keepalived cluster with priority as same in both the nodes. Recently we faced take over process that happened due to time lag between nodes. We just want to know the keepalive behavior in this case. The issue is reproducible. 
So want to confirm that role swap will occur if there is time lag btw cluster nodes and want to know detailed info's about the keywords below

1.) Receive advertisement timeout
2.) Received advert from xxxxx with lower priority xxx, ours xx, forcing new election

******Details of what you would like to do with keepalived******
want to confirm the behaviour during time lag between cluster nodes 

**Keepalived version**
Output of `keepalived -v` (a later version of keepalived might be needed).
root@172.20.133.249~#keepalived -v
Keepalived v2.0.7 (08/23,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019

configure options: --prefix=/root/sanjay/keepalived/build/2.0.7/

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG LIBNL3 RTA_ENCAP RTA_EXPIRES FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Distro (please complete the following information):**
root@172.20.133.249~#uname -a
Linux 172.20.133.249 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@172.20.133.249~#cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
root@172.20.133.249~#

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details 

**Configuration file:**
#PRIMARY=172.20.133.249
#BACKUP=172.20.133.250
global_defs {
	notification_email {
		xxx@xxxx.com
	}
	notification_email_from xxxx@xxxx.com
	smtp_server xxxxx
	smtp_connect_timeout 30
	router_id LVSID01
}
vrrp_sync_group VG1 {
	group {
		VI_1
		VI_GATEWAY
	}
}
vrrp_instance VI_GATEWAY {
	interface bond0
	virtual_router_id 89
	priority 100
	advert_int 1
	smtp_alert
	authentication {
		auth_type PASS
		auth_pass zzzz
	}
	virtual_ipaddress {
		172.20.31.72
	}
}
vrrp_instance VI_1 {
	interface bond0
	virtual_router_id 88
	priority 100
	advert_int 1
	smtp_alert
	authentication {
		auth_type PASS
		auth_pass zzzz
	}
	virtual_ipaddress {
		172.20.77.1
	}
}
virtual_server 172.20.77.1 80 {
	delay_loop 10
	lb_algo rr
	lb_kind DR
	
	persistence_timeout 1800
	protocol TCP
	real_server 172.20.5.78 80 {
		weight 1
		uthreshold 0
		lthreshold 0
		
		TCP_CHECK {
			connect_timeout 3
			connect_port 80
		}
	}
	real_server 172.20.18.189 80 {
		weight 1
		uthreshold 0
		lthreshold 0
		
		TCP_CHECK {
			connect_timeout 3
			connect_port 80
		}
	}
}
**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
172.20.133.249 --- Master 
root@172.20.133.249~#date ; ip addr
Wed Apr  1 15:35:29 IST 2020
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP group default qlen 1000
    link/ether 52:54:00:73:73:ab brd ff:ff:ff:ff:ff:ff
3: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:73:73:ab brd ff:ff:ff:ff:ff:ff
    inet 172.20.133.249/16 brd 172.20.255.255 scope global bond0
       valid_lft forever preferred_lft forever
    inet 172.20.77.1/32 scope global bond0
       valid_lft forever preferred_lft forever
    inet 172.20.31.72/32 scope global bond0
       valid_lft forever preferred_lft forever
    inet 172.20.42.100/16 brd 172.20.255.255 scope global secondary bond0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe73:73ab/64 scope link
       valid_lft forever preferred_lft forever
root@172.20.133.249~#

172.20.133.250 -- Slave
root@172.20.133.250~#date ; ip addr
root@172.20.133.250~#date
Wed Apr  1 15:35:31 IST 2020
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP group default qlen 1000
    link/ether 52:54:00:14:8f:ca brd ff:ff:ff:ff:ff:ff
3: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:14:8f:ca brd ff:ff:ff:ff:ff:ff
    inet 172.20.133.250/16 brd 172.20.255.255 scope global bond0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe14:8fca/64 scope link
       valid_lft forever preferred_lft forever
root@172.20.133.250~#

To reproduce this issue, am adjusting the time in slave server 

root@172.20.133.250~#date +%T -s "15:45:13"
15:45:13

Now slave server took over as master. below are logs

172.20.133.249

root@172.20.133.249~#t
Apr  1 15:36:01 172 Keepalived_vrrp[52809]: (VI_1) Master received advert from 172.20.133.250 with same priority 100 but higher IP address than ours
Apr  1 15:36:01 172 Keepalived_vrrp[52809]: (VI_1) Entering BACKUP STATE
Apr  1 15:36:01 172 Keepalived_vrrp[52809]: (VI_1) removing VIPs.
Apr  1 15:36:01 172 Keepalived_vrrp[52809]: VRRP_Group(VG1) Syncing instances to BACKUP state
Apr  1 15:36:01 172 Keepalived_vrrp[52809]: (VI_GATEWAY) Entering BACKUP STATE
Apr  1 15:36:01 172 Keepalived_vrrp[52809]: (VI_GATEWAY) removing VIPs.
Apr  1 15:36:01 172 Keepalived_vrrp[52809]: Remote SMTP server [192.168.100.16]:25 connected.
Apr  1 15:36:01 172 Keepalived_vrrp[52809]: Remote SMTP server [192.168.100.16]:25 connected.
Apr  1 15:36:01 172 kernel: [16169513.579748] IPv4: martian source 172.20.77.1 from 172.20.77.1, on dev bond0
Apr  1 15:36:01 172 kernel: [16169513.579755] ll header: 00000000: ff ff ff ff ff ff 52 54 00 14 8f ca 08 06        ......RT......
Apr  1 15:36:01 172 kernel: [16169513.579769] IPv4: martian source 172.20.77.1 from 172.20.77.1, on dev bond0
Apr  1 15:36:01 172 kernel: [16169513.579772] ll header: 00000000: ff ff ff ff ff ff 52 54 00 14 8f ca 08 06        ......RT......
Apr  1 15:36:01 172 kernel: [16169513.579799] IPv4: martian source 172.20.77.1 from 172.20.77.1, on dev bond0
Apr  1 15:36:01 172 kernel: [16169513.579802] ll header: 00000000: ff ff ff ff ff ff 52 54 00 14 8f ca 08 06        ......RT......
Apr  1 15:36:01 172 kernel: [16169513.579829] IPv4: martian source 172.20.77.1 from 172.20.77.1, on dev bond0
Apr  1 15:36:01 172 kernel: [16169513.579831] ll header: 00000000: ff ff ff ff ff ff 52 54 00 14 8f ca 08 06        ......RT......
Apr  1 15:36:01 172 kernel: [16169513.579874] IPv4: martian source 172.20.77.1 from 172.20.77.1, on dev bond0
Apr  1 15:36:01 172 kernel: [16169513.579877] ll header: 00000000: ff ff ff ff ff ff 52 54 00 14 8f ca 08 06        ......RT......
Apr  1 15:36:01 172 kernel: [16169513.579954] IPv4: martian source 172.20.31.72 from 172.20.31.72, on dev bond0
Apr  1 15:36:01 172 kernel: [16169513.579956] ll header: 00000000: ff ff ff ff ff ff 52 54 00 14 8f ca 08 06        ......RT......
Apr  1 15:36:01 172 kernel: [16169513.579991] IPv4: martian source 172.20.31.72 from 172.20.31.72, on dev bond0
Apr  1 15:36:01 172 kernel: [16169513.579998] ll header: 00000000: ff ff ff ff ff ff 52 54 00 14 8f ca 08 06        ......RT......
Apr  1 15:36:01 172 kernel: [16169513.580023] IPv4: martian source 172.20.31.72 from 172.20.31.72, on dev bond0
Apr  1 15:36:01 172 kernel: [16169513.580025] ll header: 00000000: ff ff ff ff ff ff 52 54 00 14 8f ca 08 06        ......RT......
Apr  1 15:36:01 172 kernel: [16169513.580054] IPv4: martian source 172.20.31.72 from 172.20.31.72, on dev bond0
Apr  1 15:36:01 172 kernel: [16169513.580057] ll header: 00000000: ff ff ff ff ff ff 52 54 00 14 8f ca 08 06        ......RT......
Apr  1 15:36:01 172 kernel: [16169513.580083] IPv4: martian source 172.20.31.72 from 172.20.31.72, on dev bond0
Apr  1 15:36:01 172 kernel: [16169513.580086] ll header: 00000000: ff ff ff ff ff ff 52 54 00 14 8f ca 08 06        ......RT......
Apr  1 15:36:01 172 Keepalived_vrrp[52809]: SMTP alert successfully sent.
Apr  1 15:36:01 172 Keepalived_vrrp[52809]: SMTP alert successfully sent.
Apr  1 15:37:16 172 kernel: [16169588.792842] net_ratelimit: 2 callbacks suppressed

172.20.133.250
Apr  1 15:45:13 172 systemd[1]: Time has been changed
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: (VI_GATEWAY) Receive advertisement timeout
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: (VI_1) Receive advertisement timeout
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: (VI_1) Entering MASTER STATE
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: (VI_1) setting VIPs.
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.77.1
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: (VI_1) Sending/queueing gratuitous ARPs on bond0 for 172.20.77.1
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.77.1
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.77.1
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.77.1
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.77.1
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: VRRP_Group(VG1) Syncing instances to MASTER state
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: (VI_GATEWAY) Entering MASTER STATE
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: (VI_GATEWAY) setting VIPs.
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.31.72
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: (VI_GATEWAY) Sending/queueing gratuitous ARPs on bond0 for 172.20.31.72
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.31.72
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.31.72
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.31.72
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.31.72
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Remote SMTP server [192.168.100.16]:25 connected.
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Remote SMTP server [192.168.100.16]:25 connected.
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: (VI_GATEWAY) Received advert from 172.20.133.249 with lower priority 100, ours 100, forcing new election
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.31.72
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: (VI_GATEWAY) Sending/queueing gratuitous ARPs on bond0 for 172.20.31.72
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.31.72
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.31.72
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.31.72
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.31.72
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: (VI_1) Received advert from 172.20.133.249 with lower priority 100, ours 100, forcing new election
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.77.1
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: (VI_1) Sending/queueing gratuitous ARPs on bond0 for 172.20.77.1
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.77.1
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.77.1
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.77.1
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: Sending gratuitous ARP on bond0 for 172.20.77.1
Apr  1 15:45:13 172 Keepalived_vrrp[41408]: SMTP alert successfully sent.
**Additional context**

**Comment by pqarmitage** [comment]
@Sankaranarayanans If you change the system time suddenly, you cannot expect applications that run timers to behave as expected. This is why ntp client utilities generally change the system clock by making it run slightly fast or slightly slow until time synchronisation is achieved.

By suddenly advancing the time on the backup system, when a timer next expires, it compares the time by which it expected certain events to happen against the current system time, and the time it expected those events to have occurred by is now in the past. It therefore considers that the events have timed out, and in this case determines that it hasn't received an advert sufficiently recently, and so takes over as master.

A backup VRRP instance will take over `3 * advert_int + a bit` (where `a bit` is shorter the higher the priority of the instance) after the last advert it received.

If you find that you are getting inconsistent delays in adverts being received by backups, you could try extending the advert interval.
