### ISSUE TITLE
VRRP Group: Syncing instances not coming back to backup/master state.

### ISSUE THREAD

**Issue by rajivginotra** [acassen/keepalived#1532]
**Describe the bug**
I have created two VRRP groups ENTERPRISE and MANAGEMENT. And each VRRP group has two VRRP instances which I need to tied up together so that when VIP moves, both of them move to different node.

In some of the cases where I am seeing that VRRP group has moved to FAULT state but it didn't came back anytime to master/backup state. Even though the interface is up.

Fri Apr  3 00:47:43 2020: VRRP_Group(ENTERPRISE): Syncing instances to FAULT state
Fri Apr  3 00:47:43 2020: (vip_17.113.112.68) entering FAULT state
Fri Apr  3 00:47:43 2020: (vip_17.113.112.111) entering FAULT state
.
.
.
Fri Apr  3 00:47:43 2020: Netlink reports enp94s0f0 up

But above VRRP instances didn't change the state from FAULT.

Any inputs would be appreciated in this regard.

**To Reproduce**
Any steps necessary to reproduce the behaviour:

**Expected behavior**

**Keepalived version**
Output of `keepalived -v`
Keepalived v2.0.18 (07/26,2019)

**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu] Ubuntu
 - Version [e.g. 29] 16.04.1-Ubuntu
 - Architecture [e.g. x86_64] x86_64
Linux 4.15.0-74-generic #83~16.04.1-Ubuntu SMP Wed Dec 18 04:56:23 UTC 2019 (built for Linux 4.4.211)

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

Running as container service

**Configuration file:**
A full copy of the configuration file, obfuscated if necessary to protect passwords and IP addresses
Actual IPs are obfuscated with 200.200.200.xx

global_defs {
  vrrp_version 3
  vrrp_iptables KEEPALIVED
  enable_script_security
  script_user keepalived_script
  vrrp_garp_master_delay 40
  vrrp_garp_master_refresh 60
}

vrrp_script node_health_check {
  script       "/node_health_check.py"
  interval 60  # check every 60 seconds
  timeout 40   # Script Timeout of 40 seconds
  fall 3       # require 3 failures for FAULT Transition
}

vrrp_sync_group ENTERPRISE {
 group {
  vip_17.113.112.68
  vip_17.113.112.111
 }
}

vrrp_sync_group MANAGEMENT {
 group {
  vip_200.200.200.68
  vip_200.200.200.111
 }
}

vrrp_instance vip_200.200.200.68 {
  state BACKUP
  interface eno1
  virtual_router_id 183
  nopreempt
  advert_int 1

  track_interface {
    eno1
  }

  virtual_ipaddress {
    200.200.200.68 dev eno1 scope global
  }

  unicast_src_ip 200.200.200.65
  unicast_peer {
    200.200.200.66
    200.200.200.67
    }

  track_script {
    node_health_check
  }

  
}

vrrp_instance vip_17.113.112.68 {
  state BACKUP
  interface enp94s0f0
  virtual_router_id 109
  nopreempt
  advert_int 1

  track_interface {
    enp94s0f0
  }

  virtual_ipaddress {
    17.113.112.68 dev enp94s0f0 scope global
  }

  unicast_src_ip 17.113.112.65
  unicast_peer {
    17.113.112.66
    17.113.112.67
    }

  track_script {
    node_health_check
  }

  
}

vrrp_instance vip_192.192.0.68 {
  state BACKUP
  interface enp94s0f1
  virtual_router_id 141
  nopreempt
  advert_int 1

  track_interface {
    enp94s0f1
  }

  virtual_ipaddress {
    192.192.0.68 dev enp94s0f1 scope global
  }

  unicast_src_ip 192.192.0.65
  unicast_peer {
    192.192.0.66
    192.192.0.67
    }

  track_script {
    node_health_check
  }

  
}

vrrp_instance vip_200.200.200.111 {
  state BACKUP
  interface eno1
  virtual_router_id 28
  nopreempt
  advert_int 1

  track_interface {
    eno1
  }

  virtual_ipaddress {
    200.200.200.111 dev eno1 scope global
  }

  unicast_src_ip 200.200.200.65
  unicast_peer {
    200.200.200.66
    200.200.200.67
    }

  track_script {
    node_health_check
  }

  
}

vrrp_instance vip_17.113.112.111 {
  state BACKUP
  interface enp94s0f0
  virtual_router_id 38
  nopreempt
  advert_int 1

  track_interface {
    enp94s0f0
  }

  virtual_ipaddress {
    17.113.112.111 dev enp94s0f0 scope host
  }

  unicast_src_ip 17.113.112.65
  unicast_peer {
    17.113.112.66
    17.113.112.67
    }

  track_script {
    node_health_check
  }
 
}

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started
Fri Apr  3 00:47:43 2020: Starting Keepalived v2.0.18 (07/26,2019)
Fri Apr  3 00:47:43 2020: Running on Linux 4.15.0-74-generic #83~16.04.1-Ubuntu SMP Wed Dec 18 04:56:23 UTC 2019 (built for Linux 4.4.211)
Fri Apr  3 00:47:43 2020: Command line: '/usr/sbin/keepalived' '--vrrp' '--dont-fork' '--log-console' '--log-detail'
Fri Apr  3 00:47:43 2020:               '--release-vips' '--pid' '/etc/keepalived/keepalived.pid' '&'
Fri Apr  3 00:47:43 2020: Opening file '/etc/keepalived/keepalived.conf'.
Fri Apr  3 00:47:43 2020: Starting VRRP child process, pid=90
Fri Apr  3 00:47:43 2020: Registering Kernel netlink reflector
Fri Apr  3 00:47:43 2020: Registering Kernel netlink command channel
Fri Apr  3 00:47:43 2020: Opening file '/etc/keepalived/keepalived.conf'.
Fri Apr  3 00:47:43 2020: (vip_200.200.200.68) Ignoring track_interface eno1 since own interface
Fri Apr  3 00:47:43 2020: Assigned address 200.200.200.65 for interface eno1
Fri Apr  3 00:47:43 2020: (vip_17.113.112.68) Ignoring track_interface enp94s0f0 since own interface
Fri Apr  3 00:47:43 2020: Assigned address 17.113.112.65 for interface enp94s0f0
Fri Apr  3 00:47:43 2020: (vip_192.192.0.68) Ignoring track_interface enp94s0f1 since own interface
Fri Apr  3 00:47:43 2020: Assigned address 192.192.0.65 for interface enp94s0f1
Fri Apr  3 00:47:43 2020: (vip_200.200.200.111) Ignoring track_interface eno1 since own interface
Fri Apr  3 00:47:43 2020: (vip_17.113.112.111) Ignoring track_interface enp94s0f0 since own interface
Fri Apr  3 00:47:43 2020: VRRP_Group(ENTERPRISE): Syncing instances to FAULT state
Fri Apr  3 00:47:43 2020: (vip_17.113.112.68) entering FAULT state
Fri Apr  3 00:47:43 2020: (vip_17.113.112.111) entering FAULT state
Fri Apr  3 00:47:43 2020: Registering gratuitous ARP shared channel
Fri Apr  3 00:47:43 2020: (vip_200.200.200.68) removing VIPs.
Fri Apr  3 00:47:43 2020: (vip_17.113.112.68) removing VIPs.
Fri Apr  3 00:47:43 2020: (vip_192.192.0.68) removing VIPs.
Fri Apr  3 00:47:43 2020: (vip_200.200.200.111) removing VIPs.
Fri Apr  3 00:47:43 2020: (vip_17.113.112.111) removing VIPs.
Fri Apr  3 00:47:43 2020: (vip_200.200.200.68) removing VIPs.
Fri Apr  3 00:47:43 2020: (vip_17.113.112.68) removing VIPs.
Fri Apr  3 00:47:43 2020: (vip_192.192.0.68) removing VIPs.
Fri Apr  3 00:47:43 2020: (vip_200.200.200.111) removing VIPs.
Fri Apr  3 00:47:43 2020: (vip_17.113.112.111) removing VIPs.
Fri Apr  3 00:47:43 2020: VRRP sockpool: [ifindex(4), family(IPv4), proto(112), unicast(1), fd(10,11)]
Fri Apr  3 00:47:43 2020: VRRP sockpool: [ifindex(2), family(IPv4), proto(112), unicast(1), fd(12,13)]
Fri Apr  3 00:47:43 2020: VRRP sockpool: [ifindex(3), family(IPv4), proto(112), unicast(1), fd(14,15)]
Fri Apr  3 00:47:43 2020: Netlink reports enp94s0f0 up
Fri Apr  3 00:47:49 2020: VRRP_Script(node_health_check) succeeded
Fri Apr  3 00:47:49 2020: (vip_192.192.0.68) Entering BACKUP STATE
Fri Apr  3 00:47:49 2020: vip_192.192.0.68: sending gratuitous ARP for 192.192.0.65
Fri Apr  3 00:47:49 2020: Sending gratuitous ARP on enp94s0f1 for 192.192.0.65
Fri Apr  3 00:47:49 2020: (vip_200.200.200.111) Entering BACKUP STATE
Fri Apr  3 00:47:49 2020: vip_200.200.200.111: sending gratuitous ARP for 200.200.200.65
Fri Apr  3 00:47:49 2020: Sending gratuitous ARP on eno1 for 200.200.200.65
Fri Apr  3 00:47:49 2020: VRRP_Group(MANAGEMENT) Syncing instances to BACKUP state
Fri Apr  3 00:47:49 2020: (vip_200.200.200.68) Entering BACKUP STATE
Fri Apr  3 00:47:53 2020: (vip_192.192.0.68) Receive advertisement timeout
Fri Apr  3 00:47:53 2020: (vip_192.192.0.68) Entering MASTER STATE
Fri Apr  3 00:47:53 2020: (vip_192.192.0.68) using locally configured advertisement interval (1000 milli-sec)
Fri Apr  3 00:47:53 2020: (vip_192.192.0.68) setting VIPs.
Fri Apr  3 00:47:53 2020: Sending gratuitous ARP on enp94s0f1 for 192.192.0.68
**Did keepalived coredump?**
If so, can you please provide a stacktrace from the coredump, using gdb.

**Additional context**

**Comment by pqarmitage** [comment]
When you are in the situation when the VRRP instances are in fault state but the interface is up, could you please send SIGUSR1 to the parent keepalived process. This is create /tmp/keepalived.data; could you please add that file to this issue.

**Comment by pqarmitage** [comment]
I can reproduce this problem, but I am having to make some guesses since you haven't provided a copy of /node_health_check.py.

Can you please confirm the following:
1. enp94s0f0 is down when keepalived starts
1. The script /node_health_check.py sets enp94s0f0 up near the beginning of the script
1. The script takes about 6 seconds to execute

**Comment by rajivginotra** [comment]
> guesses

Thanks @pqarmitage  for the quick reply. Please find the below reply

1. enp94s0f0 is down when keepalived starts
=> Yes initially the interface are set as down and then comes up. but before the keepalived process spawned before that the interface are marked up. if you see the below log it confirms that interface came up @00:47:42 and keepalived got spawned @00:47:43. 


Apr  3 00:47:42 192-192-0-65 charon: 07[KNL] interface enp94s0f0 activated

Fri Apr  3 00:47:43 2020: Starting Keepalived v2.0.18 (07/26,2019) 

2. The script /node_health_check.py sets enp94s0f0 up near the beginning of the script
This script check the health of K8s nodes. Above file doesn't bring the interface up, infact the other file(keepalived.py) which spawns the keepalived binary make the interface up and that happened before we sapwns it.
3. The script takes about 6 seconds to execute.
Are you talking of script mentioned in second point?

**Comment by pqarmitage** [comment]
While interface enp94s0f0 was activated at 00:47:52, at 00:47:53 the interface was still down since keepalived reported `entering FAULT state` at that time. In fact it was later in the same second that the interface came up, as indicated by `Netlink reports enp94s0f0 up`.

I can reproduce this problem reliably if I start keepalived with enp94s0f0 down and the vrrp_script ups the interface. I suspect the reason you get the problem intermittently is that usually the interface is up by the time keepalived starts, but occasionally it hasn't yet come up, as in the logs above.

I have a patch that resolves this issue, but need to do some final testing before I merge it.

**Comment by rajivginotra** [comment]
> While interface enp94s0f0 was activated at 00:47:52, at 00:47:53 the interface was still down since keepalived reported `entering FAULT state` at that time. In fact it was later in the same second that the interface came up, as indicated by `Netlink reports enp94s0f0 up`.
> 
> I can reproduce this problem reliably if I start keepalived with enp94s0f0 down and the vrrp_script ups the interface. I suspect the reason you get the problem intermittently is that usually the interface is up by the time keepalived starts, but occasionally it hasn't yet come up, as in the logs above.
> 
> I have a patch that resolves this issue, but need to do some final testing before I merge it.

Thanks for doing the RCA and fixing it. If possible can you just brief me what was the issue?

Any time frame when you will be releasing new keepalived version?

**Comment by pqarmitage** [comment]
Commit 1ef6d47 resolves the issue. There was some logic missing for handling interfaces coming up while a vrrp_script was running for the first time - see the commit for details.

To obtain the latest version of the code, you just need to pull it from github.
