### ISSUE TITLE
modified persistence_timeout in keepalived.conf; reload did not take effect

### ISSUE THREAD

**Issue by GeorgeGuo2018** [acassen/keepalived#1542]
**Describe the bug**
In my environment, I updated persistence_timeout vulue of virtual server 10.6.115.91 in the keepalived.conf.
And then exec:
[root@10-6 ~]# /var/run# cat keepalived.pid 
43
[root@10-6 ~]# /var/run# cat checkers.pid 
44
[root@10-6 ~]# /var/run# kill -SIGHUP 43
[root@10-6 ~]# /var/run# kill -SIGHUP 44

but the persistence_timeout option did not take effect  in the ipvs rules. for example:
[root@10-6 ~]# ipvsadm -L -n
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.6.172.104:40007 rr persistent 299
  -> 172.29.104.129:80          Masq    100    0          0         

Only if I exec  kill -SIGTERM 44, The persistence vuale then can take effect.
[root@10-6 ~]# ipvsadm -L -n
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn   
TCP  10.6.172.104:40007 rr persistent 299
  -> 172.29.104.129:80          Masq    100    0          0         

My environment is as follows:
Host ,Linux dce-10-6-172-89 3.10.0-1062, centos 7.6
keepalived was deployed in a pod with hostnetwork=true, and its version is v2.0.20 .

**To Reproduce**
edit persistence value in keepalived.conf.
Then try to reload the configration usind kill -SIGHUP keepalived's pid

**Expected behavior**
persistence_timeout value take effect in the ipvs rules on the host

**Keepalived version**
 v2.0.20

**Distro (please complete the following information):**
 - Name [centos]
 - Version [7.6]
 - Architecture [x86_64]

**Details of any containerisation or hosted service (e.g. AWS)**
none

**Configuration file:**
            # Service: default-gggg
            virtual_server 10.6.172.104 40007 {
              delay_loop 5
              lvs_sched rr
              lvs_method NAT
              persistence_timeout 299
              protocol TCP

              
              real_server 172.29.104.129 80 {
                weight 1
                TCP_CHECK {
                  connect_port 80
                  connect_timeout 3
                }
              } 
            }
        

**Notify and track scripts**
none

**System Log entries**
none

**Did keepalived coredump?**
none

**Additional context**
none

**Comment by pqarmitage** [comment]
Commit 57a6be3 resolves this issue.
