### ISSUE TITLE
What are the No destination available messages?

### ISSUE THREAD

**Issue by igroost** [acassen/keepalived#1547]
Hello.
Messages from the screenshot are sent to the server console. However, everything works fine on the ipvs side. In addition to the server console, there are no similar messages in any logs. Please tell me what these messages are about, how to disable them or redirect them to a file?

![image](https://user-images.githubusercontent.com/17481985/79507809-05fe4180-8041-11ea-9764-7f7ba8c76d23.png)

**Comment by pqarmitage** [comment]
This is not a keepalived issue, but an IPVS issue, so this really isn't the right place to ask the question.

However, this message is generated by the kernel in function _ip_vs_lc_schedule()_ in kernel source file _net/netfilter/ipvs/ip_vs_lc.c_. It means that the virtual server is using least-connection scheduling (lc) and for all real servers they are either overloaded or have their weight set to 0.
