### ISSUE TITLE
Local VS's pick random route methods

### ISSUE THREAD

**Issue by gregnetau** [acassen/keepalived#1550]
I am having an issue that i think has been present for some time but now is preventing me from running keepalived on my secondary firewall. I cannot find the source in configuration or otherwise.

OS - Gentoo Linux
Kernel - Linux sjc-fw2 5.6.5-gentoo-x86_64
Keepalived v2.0.20

Keepalived v2.0.20 (01/22,2020)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.3.0
Running on Linux 5.6.5-gentoo-x86_64 #1 SMP Sun Apr 19 18:58:09 PDT 2020

configure options: --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/keepalived-2.0.20 --htmldir=/usr/share/doc/keepalived-2.0.20/html --libdir=/usr/lib64 --with-init=custom --with-kernel-dir=/usr --enable-sha1 --enable-vrrp --enable-bfd --disable-dbus --disable-json --disable-regex --enable-snmp --enable-snmp-rfc build_alias=x86_64-pc-linux-gnu host_alias=x86_64-pc-linux-gnu PKG_CONFIG_PATH=/usr/lib64/pkgconfig CFLAGS=-march=native -O2 -pipe LDFLAGS=-Wl,-O1 -Wl,--as-needed

Config options:  LVS VRRP VRRP_AUTH BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK

When keepalived starts, it seems to randomly pick the forwarding method eg:

ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  103.x,y.a:80 wrr
  -> 10.200.7.192:80              (null)  80     0          0
TCP  103.x.y.a:443 wrr
  -> 10.200.7.192:443             (null)  80     0          0
TCP  103.x.y.b:443 wrr
  -> 10.200.7.192:443             (null)  80     1022       0

/etc/init.d/keepalived restart

 ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  103.x.y.a:80 wrr
  -> 10.200.7.192:80              Route   80     0          0
TCP  103.x.y.a:443 wrr
  -> 10.200.7.192:443             Route   80     0          0
TCP  103.x.y.b:443 wrr
  -> 10.200.7.192:443             Route   80     1156       0

And.. After a random number of restarts, it finally selects the correct method (masq) and services begin to work:

 ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  103.x.y.a:80 wrr
  -> 10.200.7.192:80              Masq    80     0          0
TCP  103.x.y.a:443 wrr
  -> 10.200.7.192:443             Masq    80     0          0
TCP  103.x.y.b:443 wrr
  -> 10.200.7.192:443             Masq    80     1185       2

Sanitised Config:

```
! Configuration File for keepalived

global_defs {
   notification_email {
   greg@meepmeep.com
}
   notification_email_from sjc-fw2@meepmeep.com
   smtp_server 10.200.1.251
   router_id SJC-FW2
   lvs_sync_daemon enp1s0f1 meepmeep_INT
   vrrp_version 3
   vrrp_iptables
}

vrrp_sync_group VG1 {
  group {
        meepmeep_120
        meepmeep_INT
  }
}

vrrp_sync_group VG2 {
  group {
        meepmeep_121
  }
}


vrrp_instance meepmeep_INT {
    preempt
    state BACKUP
    interface enp1s0f1
    virtual_router_id 9
    priority 5
    advert_int 1
    smtp_alert
    virtual_ipaddress {

        ! internal ipv4
        10.200.7.195/24 label enp1s0f1:3

   }
}


vrrp_instance meepmeep_120 {
    preempt
    state BACKUP
    interface enp1s0f0
    virtual_router_id 3
    priority 5
    advert_int 1
    smtp_alert
    virtual_ipaddress {

        ! external ips
        888.999.120.120/24 label enp1s0f0:28
   }


}

vrrp_instance meepmeep_121 {
    preempt
    state MASTER
    interface enp1s0f0
    virtual_router_id 4
    priority 100
    advert_int 1
    smtp_alert
    virtual_ipaddress {

        ! external ips
        888.999.120.121/24 label enp1s0f0:29
   }


}


#########################
# meepmeep shared vhost #
#########################

virtual_server 888.999.121.10 80 {
    delay_loop 5
    lb_algo wrr
    lb_kind NAT
    protocol TCP

        real_server 10.200.7.21 80 {
                weight 80
                        TCP_CHECK {
                                connect_timeout 2
                                bindto 10.200.7.192
                        }
        }

        real_server 10.200.7.22 80 {
                weight 80
                        TCP_CHECK {
                                connect_timeout 2
                                bindto 10.200.7.192
                        }

        }
}



################
# meepmeep cdn #
################

virtual_server 888.999.120.120 80 {
    delay_loop 5
    lb_algo wrr
    lb_kind nat
    protocol TCP

        real_server 10.200.7.192 8080 {
                weight 80
                        TCP_CHECK {
                                connect_timeout 2
                                bindto 10.200.7.192
                        }

        }
}

####################
# meepmeep cdn ssl #
####################

virtual_server 888.999.120.120 443 {
    delay_loop 5
    lb_algo wrr
    lb_kind nat
    protocol TCP

        real_server 10.200.7.192 443 {
                weight 80
                        TCP_CHECK {
                                connect_timeout 2
                                bindto 10.200.7.192
                        }

        }

}

virtual_server 888.999.120.121 443 {
    delay_loop 5
    lb_algo wrr
    lb_kind nat
    protocol TCP

        real_server 10.200.7.192 443 {
                weight 80
                        TCP_CHECK {
                                connect_timeout 2
                                bindto 10.200.7.192
                        }

        }
}

```

**Comment by pqarmitage** [comment]
I'm not sure what might be causing this, so I need to try to run it in a similar environment myself.

I have tried installing Gentoo into a VM, but it won't boot; it looks like GRUB isn't finding the disk partitions. Any pointers would be helpful.

Also, Gentoo in installing kernel v5.4.28, but I see you are using v5.6.5. What do I need to do in order to install v5.6.5?

**Comment by gregnetau** [comment]
@vzFqMJlWol!voy22zL5MSMC

**Comment by pqarmitage** [comment]
This problem is triggered by an invalid `lb_kind` being specified (`nat`); the valid `lb_kind` values are `NAT`, `TUN` and `DR`, and these are case sensitive. Specifying `lb_kind nat` triggered keepalived to configure invalid (and random) forwarding methods for the real servers.

Commit 2972b4e resolves the issue of keepalived configuring invalid and random forwarding methods, and it will now default to NAT if no valid forwarding method is specified.

The keyword `lb_kind` is now superseded by `lvs_method` since that is more descriptive of what it is configuring.
