### ISSUE TITLE
Direct Return mode not working on CentOS 8

### ISSUE THREAD

**Issue by nimasamii** [acassen/keepalived#1551]
**Describe the bug**
Minimal installation of current CentOS8 with virtual Server using lvs_mode DR is not working.

**To Reproduce**
Install 3 CentOS 8 Machines (e.g. VMs on libvirt with default (NAT) network): one Load Balancer and two Service VMs (192.168.122.100 & 192.168.122.101).
Network is 192.168.122.0/24
DNS/Gateway is 192.168.122.1
Loadbalancer IP 192.168.122.12, 
VIP 192.168.122.13 and
Service VMs are 192.168.122.100 & 192.168.122.101

Install httpd on Service VM and configure firewall:
dnf install -y httpd && systemctl enable --now httpd && firewall-cmd --permanent --zone=public --add-service=http && firewall-cmd --permanent --direct --add-rule ipv4 nat PREROUTING 0 -d 192.168.122.13 -p tcp -m tcp --dport 80 -j REDIRECT && firewall-cmd --reload

Install keepalived on Loadbalancer VM:
dnf install -y keepalived
Setup with config (see below)
firewall-cmd --permanent --zone=public --add-service=http && firewall-cmd --reload
systemctl enable --now keepalived

**Expected behavior**
HTTP request from client on network should be forwarded by the LB to Service VM and the reply directly routed back to the client.

**Keepalived version**
Keepalived v2.0.20 (unknown)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.0
Running on Linux 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LIBIPTC LIBIPSET_DYNAMIC NFTABLES LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK
**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu]
 - Version [e.g. 29]
 - Architecture [e.g. x86_64]

**Configuration file:**
global_defs {
   notification_email {
     acassen@firewall.loc
     failover@firewall.loc
     sysadmin@firewall.loc
   }
}

vrrp_instance VI_1 {
    state MASTER
    interface enp1s0
    virtual_router_id 50
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        192.168.122.13
    }
}

virtual_server 192.168.122.13 80 {
    delay_loop 10
    lb_algo rr
    lb_kind DR
    persistence_timeout 9600
    protocol TCP

    real_server 192.168.122.100 80 {
        weight 1
        TCP_CHECK {
           connect_timeout 10
           connect_port 80
        }
    }
    
    real_server 192.168.122.101 80 {
        weight 1
        TCP_CHECK {
           connect_timeout 10
           connect_port 80
        }
    }
}

**System Log entries**
Full keepalived system log entries from when keepalived started
systemd[1]: Starting LVS and VRRP High Availability Monitor...
Keepalived[25573]: Starting Keepalived v2.0.20 (unknown)
Keepalived[25573]: Running on Linux 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 (built for Linux 4.18.0)
systemd[1]: Started LVS and VRRP High Availability Monitor.
Keepalived[25573]: Command line: '/usr/sbin/keepalived' '-D'
Keepalived[25573]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived[25574]: Starting Healthcheck child process, pid=25575
Keepalived[25574]: Starting VRRP child process, pid=25576
Keepalived_healthcheckers[25575]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived_vrrp[25576]: Registering Kernel netlink reflector
Keepalived_vrrp[25576]: Registering Kernel netlink command channel
Keepalived_healthcheckers[25575]: Initializing ipvs
Keepalived_vrrp[25576]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived_healthcheckers[25575]: Gained quorum 1+0=1 <= 2 for VS [192.168.122.13]:tcp:80
Keepalived_healthcheckers[25575]: Activating healthchecker for service [192.168.122.100]:tcp:80 for VS [192.168.122.13]:tcp:80
Keepalived_healthcheckers[25575]: Activating healthchecker for service [192.168.122.101]:tcp:80 for VS [192.168.122.13]:tcp:80
lb2.local Keepalived_vrrp[25576]: Assigned address 192.168.122.12 for interface enp1s0
Keepalived_vrrp[25576]: Assigned address fe80::8621:bd2d:17c4:18e5 for interface enp1s0
Keepalived_vrrp[25576]: Registering gratuitous ARP shared channel
Keepalived_vrrp[25576]: (VI_1) removing VIPs.
Keepalived_vrrp[25576]: (VI_1) Entering BACKUP STATE (init)
Keepalived_vrrp[25576]: VRRP sockpool: [ifindex(2), family(IPv4), proto(112), unicast(0), fd(11,12)]
Keepalived_healthcheckers[25575]: TCP connection to [192.168.122.100]:tcp:80 success.
Keepalived_vrrp[25576]: (VI_1) Receive advertisement timeout
Keepalived_vrrp[25576]: (VI_1) Entering MASTER STATE
Keepalived_vrrp[25576]: (VI_1) setting VIPs.
Keepalived_vrrp[25576]: Sending gratuitous ARP on enp1s0 for 192.168.122.13
Keepalived_vrrp[25576]: (VI_1) Sending/queueing gratuitous ARPs on enp1s0 for 192.168.122.13
Keepalived_vrrp[25576]: Sending gratuitous ARP on enp1s0 for 192.168.122.13
Keepalived_vrrp[25576]: Sending gratuitous ARP on enp1s0 for 192.168.122.13
Keepalived_vrrp[25576]: Sending gratuitous ARP on enp1s0 for 192.168.122.13
Keepalived_vrrp[25576]: Sending gratuitous ARP on enp1s0 for 192.168.122.13
Keepalived_healthcheckers[25575]: TCP connection to [192.168.122.101]:tcp:80 success.
Keepalived_vrrp[25576]: Sending gratuitous ARP on enp1s0 for 192.168.122.13
Keepalived_vrrp[25576]: (VI_1) Sending/queueing gratuitous ARPs on enp1s0 for 192.168.122.13
Keepalived_vrrp[25576]: Sending gratuitous ARP on enp1s0 for 192.168.122.13
Keepalived_vrrp[25576]: Sending gratuitous ARP on enp1s0 for 192.168.122.13
Keepalived_vrrp[25576]: Sending gratuitous ARP on enp1s0 for 192.168.122.13
Keepalived_vrrp[25576]: Sending gratuitous ARP on enp1s0 for 192.168.122.13

**Did keepalived coredump?**
No

**Additional context**
Identical Setup on CentOS 7 works.

**Comment by pqarmitage** [comment]
Can you please provide the output of `ipvsadm -Ln`, and also send SIGUSR1 to the parent keepalived process and post the contents of /etc/keepalived_check.data.

**Comment by nimasamii** [comment]
Sure thing, here are the files you requested. Thanks for taking a look!

[ipvsadm-Ln.txt](https://github.com/acassen/keepalived/files/4512775/ipvsadm-Ln.txt)

[keepalived_check.data.txt](https://github.com/acassen/keepalived/files/4512776/keepalived_check.data.txt)

**Comment by pqarmitage** [comment]
keepalived is responsible for setting up the IPVS configuration; after that it is down to the IPVS code in the kernel to handle the forwarding of packets.

The output you have provided of `ipvsadm -Ln` shows that keepalived has set up the IPVS configuration correctly, and there is even one connection that the kernel IPVS code has forwarded.

The issue therefore isn't a keepalived issue, and is most likely to be a network configuration or firewall issue. One way to verify the problem isn't caused by keepalived is so set up the IPVS configuration using ipvsadm, and see that you still have the problem:
```
ipvsadm -A -t 192.168.122.13:80 -s rr -p 9600
ipvsadm -a -t 192.168.122.13:80 -r 192.168.122.100:80 -g -w 1
ipvsadm -a -t 192.168.122.13:80 -r 192.168.122.101:80 -g -w 1
```
