### ISSUE TITLE
IPVS not initialized

### ISSUE THREAD

**Issue by juanvasquezreyes** [acassen/keepalived#1552]
Not sure if I'm getting crazy, when I start the service using "systemctl start keepalived"
the healthchecks doesnt work getting this error "Keepalived_healthcheckers[3327]: WEB socket bind failed. Rescheduling"

But when I manually run it like this: **/usr/sbin/keepalived -nldD -f /etc/keepalived/keepalived.conf**
everything works perfect

So, I checked the logs and the only difference I found was that using the service I dont see the message "Initializing ipvs" as I do when I manually run it

So I'm thinking that IPVS is not being initialized when running the service, I'm using v1.3.5 keepalived version

Expected behaviour is to run the same using the service or using the manual execution

Starting to think that there is a configuration missing on my side

OS: Linux 7.7 (64-bit)             
System: VMware Guest
Keepalived v1.3.5

[root@xxxx]# ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  xxxx.90 :8000 rr persistent 50
  -> xxxx.82:8000           Route   1      0          0
  -> xxxx.83:8000           Route   1      0          0

configuration:

```
! Configuration File for keepalived
global_defs {
   router_id LVS_DEVEL
   vrrp_skip_check_adv_addr
   #vrrp_strict
   vrrp_garp_interval 0
   vrrp_gna_interval 0
}
vrrp_instance VI_1 {
    interface eth0
    virtual_router_id 51
    priority 101
    advert_int 1
    nopreempt
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        x.x.x.90 
    }
}
virtual_server x.x.x.90 8000 {
    delay_loop 30
    lb_algo rr
    lb_kind DR
    persistence_timeout 50
    protocol TCP
    real_server x.x.x.83 8000 {
        weight 1
        HTTP_GET {
            url {
                path /api/menu
                digest d41d8cd98f00b204e9800998ecf8427e
            }
            url {
                path /test
                digest d41d8cd98f00b204e9800998ecf8427e
            }
            connect_port 8000
            connect_timeout 3
            retry 3
            delay_before_retry 2
        }
    }
    real_server x.x.x.82 8000 {
        weight 1
        HTTP_GET {
            url {
                path /api/menu
                digest d41d8cd98f00b204e9800998ecf8427e
            }
            url {
                path /test
                digest d41d8cd98f00b204e9800998ecf8427e
            }
            connect_port 8000
            connect_timeout 3
            retry 3
            delay_before_retry 2
        }
    }
}
```

Logs when running the service:
Starting Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
Opening file '/etc/keepalived/keepalived.conf'.
Opening file '/etc/keepalived/keepalived.conf'.
Starting Healthcheck child process, pid=1500
Started LVS and VRRP High Availability Monitor.
Starting VRRP child process, pid=1501
Opening file '/etc/keepalived/keepalived.conf'.
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Unknown keyword 'retry'
Opening file '/etc/keepalived/keepalived.conf'.
(VI_1): Warning - nopreempt will not work with initial state MASTER
VRRP_Instance(VI_1) removing protocol VIPs.
------< Global definitions >------
...

Logs when running manually
Starting Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
Opening file '/etc/keepalived/keepalived.conf'.
Starting Healthcheck child process, pid=1906
Starting VRRP child process, pid=1907
**Initializing ipvs**
Opening file '/etc/keepalived/keepalived.conf'.
Unknown keyword 'retry'
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Opening file '/etc/keepalived/keepalived.conf'.
------< Global definitions >------
...

**Comment by pqarmitage** [comment]
Please provide the information requested in the `Bug report` issue template. Without that information we simply do not have anything we can look at.

**Comment by juanvasquezreyes** [comment]
> Please provide the information requested in the `Bug report` issue template. Without that information we simply do not have anything we can look at.

Just updated it

**Comment by pqarmitage** [comment]
Thanks for the update.

You state that you are running Linux 7.7, but that doesn't exist! I am guessing that you are running RHEL 7.7 or CentOS 7.7; is that correct?

Based on the above guess, I assume that you are running selinux in enforcing mode. When keepalived is run via systemctl, do you get any selinux messages in the log at about the same time as the `Keepalived_healthcheckers[3327]: WEB socket bind failed. Rescheduling"` message?

Again based on my above assumption, can you execute `setenforce Permissive` and then try starting keepalived via systemctl. Do you still get the WEB socket error?

As you may have guessed, I suspect that this is an selinux permissions problem. When a process is started as a systemd service it runs in a different context from when it is run from a command line, and this can cause selinux to block access in one case and not in another.

Since keepalived is running without the `WEB socket` error when run manually, but does get the error when run via systemctl, I think we can conclude that keepalived itself is working correctly and that it is something outside keepalived that is causing the on one circumstance and not the other.

**Comment by juanvasquezreyes** [comment]
I think you are right, I dont think is keepalived issue, is some conf , but not sure what conf I need to modify

[root@x.x.x.82]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.7 (Maipo)

[root@x.x.x.82]# cat /etc/selinux/config
# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
#SELINUX=enforcing
SELINUX=permissive
# SELINUXTYPE= can take one of three two values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected.
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted


here are the logs I get at the end, that's all I see
VRRP_Instance(VI_1) Sending/queueing gratuitous ARPs on eth0 for x.x.x.90
Sending gratuitous ARP on eth0 for x.x.x.90
Sending gratuitous ARP on eth0 for x.x.x.90
Sending gratuitous ARP on eth0 for x.x.x.90
Sending gratuitous ARP on eth0 for x.x.x.90
Sending gratuitous ARP on eth0 for x.x.x.90
Sending gratuitous ARP on eth0 for x.x.x.90
Sending gratuitous ARP on eth0 for x.x.x.90
Sending gratuitous ARP on eth0 for x.x.x.90
WEB socket bind failed. Rescheduling

**Comment by pqarmitage** [comment]
I can reproduce this problem on my CentOS 7.7 virtual machine and it is an SELinux permissions issue.

With the standard permissions, the error that keepalived is getting when it logs `WEB socket bind failed. Rescheduling` is EPERM, in other words permission denied. If I modify the SELinux settings for keepalived by executing `chcon -t bin_t /usr/sbin/keepalived` and then do `systemctl start keepalived` I no longer get the WEB socket error. Restoring the permissions with `chcon -t keepalived_exec_t /usr/sbin/keepalived` and starting keepalived again via systemctl, and the WEB socket error occurs again. In particular, when the SELinux type is set to keepalived_t, I get the following messages in /var/log/audit/audit.log:
```
type=AVC msg=audit(1587570621.107:223): avc:  denied  { name_connect } for  pid=24360 comm="keepalived" dest=8000 scontext=system_u:system_r:keepalived_t:s0 tcontext=system_u:object_r:soundd_port_t:s0 tclass=tcp_socket permissive=0
type=SYSCALL msg=audit(1587570621.107:223): arch=c000003e syscall=42 success=no exit=-13 a0=6 a1=1d70f80 a2=80 a3=7ffde01e4280 items=0 ppid=24359 pid=24360 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="keepalived" exe="/usr/sbin/keepalived" subj=system_u:system_r:keepalived_t:s0 key=(null)
type=PROCTITLE msg=audit(1587570621.107:223): proctitle=2F7573722F7362696E2F6B656570616C69766564002D44
```
which I don't get when the type is set to bin_t.

On Fedora, the log contains helpful messages about what to run in order to allow the program to do what it is trying to do, but I don't see there types of messages in any of the CentOS logs.

Anyway, it appears, as I expected, that this is an SELinux permissions issue.

**Comment by juanvasquezreyes** [comment]
> I can reproduce this problem on my CentOS 7.7 virtual machine and it is an SELinux permissions issue.
> 
> With the standard permissions, the error that keepalived is getting when it logs `WEB socket bind failed. Rescheduling` is EPERM, in other words permission denied. If I modify the SELinux settings for keepalived by executing `chcon -t bin_t /usr/sbin/keepalived` and then do `systemctl start keepalived` I no longer get the WEB socket error. Restoring the permissions with `chcon -t keepalived_exec_t /usr/sbin/keepalived` and starting keepalived again via systemctl, and the WEB socket error occurs again. In particular, when the SELinux type is set to keepalived_t, I get the following messages in /var/log/audit/audit.log:
> 
> ```
> type=AVC msg=audit(1587570621.107:223): avc:  denied  { name_connect } for  pid=24360 comm="keepalived" dest=8000 scontext=system_u:system_r:keepalived_t:s0 tcontext=system_u:object_r:soundd_port_t:s0 tclass=tcp_socket permissive=0
> type=SYSCALL msg=audit(1587570621.107:223): arch=c000003e syscall=42 success=no exit=-13 a0=6 a1=1d70f80 a2=80 a3=7ffde01e4280 items=0 ppid=24359 pid=24360 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="keepalived" exe="/usr/sbin/keepalived" subj=system_u:system_r:keepalived_t:s0 key=(null)
> type=PROCTITLE msg=audit(1587570621.107:223): proctitle=2F7573722F7362696E2F6B656570616C69766564002D44
> ```
> 
> which I don't get when the type is set to bin_t.
> 
> On Fedora, the log contains helpful messages about what to run in order to allow the program to do what it is trying to do, but I don't see there types of messages in any of the CentOS logs.
> 
> Anyway, it appears, as I expected, that this is an SELinux permissions issue.

Thank you, that solved my problem
Thanks

**Comment by pqarmitage** [comment]
Could you please update this to say what you did to resolve the problem.

**Comment by juanvasquezreyes** [comment]
I just ran the command provided in the two servers x.x.x.82 and x.x.x.83
[root@x.x.x.82]# chcon -t bin_t /usr/sbin/keepalived
[root@x.x.x.82]# systemctl restart keepalived

and in order to test I restarted the app that was running on port 8000 to see that healtchecks was working and according to the logs it solved the problem
```
Apr 22 11:02:46 x.x.x.82 Keepalived_vrrp[24548]: VRRP_Instance(VI_1) Transition to MASTER STATE
Apr 22 11:02:47 x.x.x.82 Keepalived_vrrp[24548]: VRRP_Instance(VI_1) Entering MASTER STATE
Apr 22 11:02:47 x.x.x.82 Keepalived_vrrp[24548]: VRRP_Instance(VI_1) setting protocol VIPs.
Apr 22 11:02:47 x.x.x.82 Keepalived_vrrp[24548]: Sending gratuitous ARP on eth0 for x.x.x.90.90
Apr 22 11:02:47 x.x.x.82 Keepalived_vrrp[24548]: VRRP_Instance(VI_1) Sending/queueing gratuitous ARPs on eth0 for x.x.x.90.90
Apr 22 11:02:47 x.x.x.82 Keepalived_vrrp[24548]: Sending gratuitous ARP on eth0 for x.x.x.90.90
Apr 22 11:02:47 x.x.x.82 Keepalived_vrrp[24548]: Sending gratuitous ARP on eth0 for x.x.x.90.90
Apr 22 11:02:47 x.x.x.82 Keepalived_vrrp[24548]: Sending gratuitous ARP on eth0 for x.x.x.90.90
Apr 22 11:02:47 x.x.x.82 Keepalived_vrrp[24548]: Sending gratuitous ARP on eth0 for x.x.x.90.90
Apr 22 11:02:52 x.x.x.82 Keepalived_vrrp[24548]: Sending gratuitous ARP on eth0 for x.x.x.90.90
Apr 22 11:02:52 x.x.x.82 Keepalived_vrrp[24548]: VRRP_Instance(VI_1) Sending/queueing gratuitous ARPs on eth0 for x.x.x.90.90
Apr 22 11:02:52 x.x.x.82 Keepalived_vrrp[24548]: Sending gratuitous ARP on eth0 for x.x.x.90.90
Apr 22 11:02:52 x.x.x.82 Keepalived_vrrp[24548]: Sending gratuitous ARP on eth0 for x.x.x.90.90
Apr 22 11:02:52 x.x.x.82 Keepalived_vrrp[24548]: Sending gratuitous ARP on eth0 for x.x.x.90.90
Apr 22 11:02:52 x.x.x.82 Keepalived_vrrp[24548]: Sending gratuitous ARP on eth0 for x.x.x.90.90
Apr 22 11:05:43 x.x.x.82 Keepalived_healthcheckers[24547]: Error connecting server [x.x.x.90.83]:8000.
Apr 22 11:05:45 x.x.x.82 Keepalived_healthcheckers[24547]: Error connecting server [x.x.x.90.83]:8000.
Apr 22 11:05:45 x.x.x.82 Keepalived_healthcheckers[24547]: Check on service [x.x.x.90.83]:8000 failed after 1 retry.
Apr 22 11:05:45 x.x.x.82 Keepalived_healthcheckers[24547]: Removing service [x.x.x.90.83]:8000 from VS [x.x.x.90.90]:8000
Apr 22 11:06:16 x.x.x.82 Keepalived_healthcheckers[24547]: MD5 digest success to [x.x.x.90.83]:8000 url(1).
Apr 22 11:06:47 x.x.x.82 Keepalived_healthcheckers[24547]: MD5 digest success to [x.x.x.90.83]:8000 url(2).
Apr 22 11:06:47 x.x.x.82 Keepalived_healthcheckers[24547]: Remote Web server [x.x.x.90.83]:8000 succeed on service.
Apr 22 11:06:47 x.x.x.82 Keepalived_healthcheckers[24547]: Adding service [x.x.x.90.83]:8000 to VS [x.x.x.90.90]:8000
```
