### ISSUE TITLE
keepalived 1.2.17 does not call vrrp_instance notify script 

### ISSUE THREAD

**Issue by ajschorr** [acassen/keepalived#156]
I upgraded my Fedora 21 system from keepalived 1.2.16 to 1.2.17, and the notify script is no longer called at startup nor when a state transition occurs. I am running "keepalived --vrrp -D" and a sample config file looks like this:

vrrp_instance firewall {
state BACKUP
interface lan0.3009
virtual_router_id 66
priority 150
advert_int 1
authentication {
auth_type PASS
auth_pass pw32wd
}
virtual_ipaddress {
192.168.1.1/28 brd 192.168.1.63 dev lan0.3004
}
notify /etc/keepalived_notify.sh
}

**Comment by rohara** [comment]
I believe this patch is causing the problem:

https://github.com/acassen/keepalived/commit/5c4177381bee24f9f7fbe33b8dc20c2d9cc2bccb

**Comment by acassen** [comment]
Try with following configuration

notify {
  /etc/keepalived_notify.sh
}

But I am considering reverting original patch causing this issue.

**Comment by DStape** [comment]
Do you see the same issue if you also revert 89f9102?

**Comment by rohara** [comment]
I also reverted that patch and it works as expected.

**Comment by ajschorr** [comment]
Changing to the altered syntax as suggested does work.

If the syntax is changed to require curly braces, shouldn't that be documented somewhere?  The man page has the old syntax.

**Comment by ajschorr** [comment]
Also, I noticed that with the changed syntax, the notify script is actually called twice at startup.  In my test, I'm simply logging the invocations to a log file, and I see this:

Thu Jun 18 10:46:51 EDT 2015 Called with args: INSTANCE pcr-ny4-mktdata-relay MASTER 200
Thu Jun 18 10:46:51 EDT 2015 Called with args: INSTANCE pcr-ny4-mktdata-relay MASTER 200

Is that intended?  That seems like another bug...

**Comment by DStape** [comment]
Unless two state transitions have occurred, then no, the the notification script should only get invoked once.

**Comment by ajschorr** [comment]
Well yes, that's my point.  I simply started up keepalived, and it immediately made those 2 calls to the notify script indicating MASTER state.  Should I open a separate bug for this?

**Comment by DStape** [comment]
Yes, open a separate bug. Could you show me your configuration please? I'll repro this and try and figure out where it's going wrong.

**Comment by DStape** [comment]
Ajschorr, I note that you already posted your config in your first post.

**Comment by ajschorr** [comment]
Ah, sorry, I would have posted it again, but I opened a new issue #157 and assumed that you would see it there.  It's pretty similar to what I posted above.  But please take a look at #157 to see a bunch of debug info.  I didn't dig deeper since I'm not familiar with the code base...
