### ISSUE TITLE
Is there only two processes on keepalived version 2.0.x ?

### ISSUE THREAD

**Issue by Damon-PingCap** [acassen/keepalived#1562]
**Describe the issue**
A clear and concise description of what the issue is.
I found there are three processes on the os when keepalived version 1.2.20  running，but only two processes on keepalived version 2.0.8 and 2.0.40 。 
Is this normal? 
OS is  centos 7.3

**Comment by pqarmitage** [comment]
That is correct, depending on your keepalived configuration, which you haven't provided.
