### ISSUE TITLE
VIP is keeping switching between nodes 

### ISSUE THREAD

**Issue by zhexuany** [acassen/keepalived#1563]
**Describe what you need help/support for**
We recently found that VIP keeps switching between two keepalive nodes. It results in communication link failures. Via tcpdump, we find that APP's mac address transporting to keepalive nodes. We want to know is it a bug or a bug fixed in the later version. We're like to locate the root cause. 

**Details of what you would like to do with keepalived**
Describe in details what you would like to achieve with keepalived

**Keepalived version**
2.0.8
**Operating System**
 - Name [Centos]
 - Version [7.3]
 - Architecture [x86_64]

**Details of any containerization or hosted service (e.g. AWS)**
Keepalived is installed on x86 machine. 

**Configuration file:**
```
! Configuration File for keepalived
global_defs {
   router_id db_prd
}

vrrp_script chk_haproxy {
         script "/etc/keepalived/check_haproxy.sh"
         interval 2
         weight 2
}
vrrp_instance VI_1 {
    state BACKUP    
    interface bond0  
    virtual_router_id 225  
    priority 90   
    advert_int 1   
    nopreempt
    authentication { 
        auth_type PASS
        auth_pass 1111
    }
    track_script { 
        chk_haproxy
    }
    virtual_ipaddress {
       172.28.60.221
    }
}
```

**System Log entries**
Full keepalived system log entries from when keepalived started.
![image](https://user-images.githubusercontent.com/13320708/80479198-3c14bd00-8981-11ea-8e91-975440718421.png)

**Comment by pqarmitage** [comment]
@zhexuany Can you please describe what you mean by: `we find that APP's mac address transporting to keepalive nodes`. Along with an explanation, the tcpdump output might be helpful.

The syslog entries you show above do not show any keepalived entries. This probably means that your syslogd is configured to write keepalived logs to another file. We will need to see the keepalived logs from both nodes to try and understand what is happening.

**Comment by pqarmitage** [comment]
Closing due to no response for over 8 days.

If the problem is still occurring for you and you can provide the additional information requested above, we can reopen the issue.
