### ISSUE TITLE
Net-namespace per vrrp instance

### ISSUE THREAD

**Issue by minhla12** [acassen/keepalived#1565]
**Is your feature request to resolve a problem or provide enhanced functionality? Please describe.**
This would be an enhanced functionality for network namespace. Currently a keepalived process can only be in a single network namespace. All vrrp instances in the keepalived process belong to the single network namespace. The namespace option is provided either as a global definition "net_namespace" in the config or as a "--namespace" option on the bin. 

**Describe the solution you would like**
I would like keepalived to be able to run each vrrp instance per network namespace in a single keepalived process. An example would be 1 keepalived process, vrrp_instance 1 in network namespace 1, vrrp_instance 2 in network namespace 2, vrrp_instance 3 in network namespace 3. Each vrrp_instance should have a "net_namespace" option.

**Describe alternatives you have considered**
The alternative currently is to run many keepalived processes, each belonging their own namespace. This results in many keepalived processes and can consume more memory than a single keepalived process. 

**Would the feature request be of benefit only to you, or is it more generally applicable?**
This would benefit any developer or organization interested in having keepalived in multi-tenant setup that is looking to lower the keepalived footprint.

**Keepalived version**
Keepalived v1.2.24 (02/14,2019)

**Comment by minhla12** [comment]
Hi, any update for the request?

**Comment by acassen** [comment]
netns are pid oriented. Current VRRP code run into a single same process. So right now no.

But this kind of feature looks like a commercial need or a large scale need. This can be a very nice nice extension, and if your company is considering running this feature it is a good opportunity to sponsorized Keepalived core-team for it.

Contact me privately if interested.

Right now we are extending code in order to prepare next step.

**Comment by acassen** [comment]
I would also strongly recommand upgrading to last release... 1.2.24 is way too old. I am closing the issue, since this is not an issue but rather a feature request.
