### ISSUE TITLE
keepalived 1.2.17 calls notify script twice when it starts in MASTER state

### ISSUE THREAD

**Issue by ajschorr** [acassen/keepalived#157]
Here is my configuration file:

vrrp_instance pcr-ny4-mktdata-relay {
  state MASTER
  interface lan0.3003
  virtual_router_id 99
  priority 200
  advert_int 1
  authentication {
    auth_type PASS
    auth_pass kaTest
  }
  virtual_ipaddress {
    192.168.53.250/24 brd 192.168.53.255 dev lan0.3003
  }
  notify {
     /tmp/katest.sh
  }
}

bash-4.3$ cat /tmp/katest.sh 
#!/bin/sh

echo "`date` Called with args: $@" >> /tmp/katest.log

After startup, I see:

bash-4.3$ cat /tmp/katest.log 
Thu Jun 18 15:05:57 EDT 2015 Called with args: INSTANCE pcr-ny4-mktdata-relay MASTER 200
Thu Jun 18 15:05:57 EDT 2015 Called with args: INSTANCE pcr-ny4-mktdata-relay MASTER 200

I am running it like so:

bash$ keepalived -f /extra_disk/tmp/katest/etc/keepalived/keepalived.conf --vrrp -l -D -n -d
Starting VRRP child process, pid=1112
Netlink reflector reports IP 192.168.50.139 added
Netlink reflector reports IP 10.25.3.133 added
Netlink reflector reports IP 192.168.53.139 added
Netlink reflector reports IP 192.168.53.250 added
Netlink reflector reports IP 192.168.55.139 added
Netlink reflector reports IP 192.168.61.139 added
Netlink reflector reports IP 10.211.0.5 added
Netlink reflector reports IP 192.168.63.139 added
Netlink reflector reports IP 192.168.62.139 added
Netlink reflector reports IP 192.168.60.139 added
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Opening file '/extra_disk/tmp/katest/etc/keepalived/keepalived.conf'.
Configuration is using : 65479 Bytes
------< Global definitions >------
 Router ID = ti139
 VRRP IPv4 mcast group = 224.0.0.18
 VRRP IPv6 mcast group = ff02::12
------< VRRP Topology >------
 VRRP Instance = pcr-ny4-mktdata-relay
   Using VRRPv2
   Want State = MASTER
   Runing on device = lan0.3003
   Gratuitous ARP repeat = 5
   Gratuitous ARP refresh repeat = 1
   Virtual Router ID = 99
   Priority = 200
   Advert interval = 1 sec

   Accept disabled
   Authentication type = SIMPLE_PASSWORD
   Password = kaTest
   Virtual IP = 1
     192.168.53.250/24 brd 192.168.53.255 dev lan0.3003 scope global
   Generic state transition scripts = 1

      /tmp/katest.sh
Using LinkWatch kernel netlink reflector...
Opening script file /tmp/katest.sh
VRRP sockpool: [ifindex(5), proto(112), unicast(0), fd(10,11)]
VRRP_Instance(pcr-ny4-mktdata-relay) Transition to MASTER STATE
VRRP_Instance(pcr-ny4-mktdata-relay) Entering MASTER STATE
VRRP_Instance(pcr-ny4-mktdata-relay) setting protocol VIPs.
VRRP_Instance(pcr-ny4-mktdata-relay) Sending gratuitous ARPs on lan0.3003 for 192.168.53.250
Opening script file /tmp/katest.sh
VRRP_Instance(pcr-ny4-mktdata-relay) Sending gratuitous ARPs on lan0.3003 for 192.168.53.250
^CStopping Keepalived v1.2.17 (06/18,2015)

**Comment by acassen** [comment]
well I am going to revert 2 patch related to notify since implementation is not tested.

**Comment by acassen** [comment]
Just reverted all changes related to script... please give it a try and report... Old syntax declaration is back. (eg: notify /tmp/katest.sh)

**Comment by ajschorr** [comment]
In my simple test case, this fix seems to work.  Thanks.

Stupid question -- when there are syntax errors in the configuration file, why doesn't keepalived print an error message and exit?  For example, if notify requires curly braces, and they're not present, as was the case until the patch was reverted, why didn't keepalived abort at startup?  Similarly, if I now run this version with curly braces still present, it does not complain.  It seems like it would be an improvement if the config file parser were to throw a fatal error when the grammar is violated.

Regards,
Andy

**Comment by ajschorr** [comment]
By the way, the bug where keepalived fails to remove VRRP addrs when stopped is still there.  Are you aware of that one?

Using LinkWatch kernel netlink reflector...
VRRP sockpool: [ifindex(5), proto(112), unicast(0), fd(10,11)]
VRRP_Instance(pcr-ny4-mktdata-relay) Transition to MASTER STATE
VRRP_Instance(pcr-ny4-mktdata-relay) Entering MASTER STATE
VRRP_Instance(pcr-ny4-mktdata-relay) setting protocol VIPs.
VRRP_Instance(pcr-ny4-mktdata-relay) Sending gratuitous ARPs on lan0.3003 for 192.168.53.250
Opening script file /tmp/katest.sh
VRRP_Instance(pcr-ny4-mktdata-relay) Sending gratuitous ARPs on lan0.3003 for 192.168.53.250
^CStopping Keepalived v1.2.17 (06/18,2015)

But 192.168.53.250 is still there:

bash-4.3$ ip -4 addr ls dev lan0.3003
5: lan0.3003@lan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    inet 192.168.53.139/24 brd 192.168.53.255 scope global lan0.3003
       valid_lft forever preferred_lft forever
    inet 192.168.53.250/24 brd 192.168.53.255 scope global secondary lan0.3003
       valid_lft forever preferred_lft forever

This bug has been around for years...

**Comment by acassen** [comment]
regarding stupid question :) : Well, current configuration parser is just not good enough :), I am into a process to completely rewrite that noisy parser. Jan Holmberg already produced some investigation code, I will dig into and produce new stuff around this area.
