### ISSUE TITLE
In the case of multiple network cards, VRRP fails to realize VIP switching (Track_scripts mode) after the interface of intance is set above the second network card

### ISSUE THREAD

**Issue by duanbaihong** [acassen/keepalived#1571]
**Describe the bug**
In the case of multiple network cards, VRRP fails to realize VIP switching (Track & U scripts mode) after the interface of intance is set above the second network card

**To Reproduce**
In the case of multiple network cards, VRRP fails to realize VIP switching (Track & U scripts mode) after the interface of intance is set above the second network card

**Expected behavior**

**Keepalived version**
all

**Configuration file:**
#NGINX 检测脚本
vrrp_script check_nginx {
    script "/usr/bin/curl 192.168.2.212:80 -I"
    interval 2
    timeout 10
    weight -10
    fall 2
    rise 1
}

#REDIS 检测脚本
vrrp_script check_redis {
    script "/a/apps/keepalived/etc/keepalived/redis_check.sh"
    interval 2
    timeout 10
    weight -10
    fall 2
    rise 1
}

#NGINX 实例
vrrp_instance NGINX_INSTANCE_1 {
    state BACKUP
    interface em3
    nopreempt
    virtual_router_id 200
    unicast_src_ip 192.168.2.211
    unicast_peer { 
        192.168.2.214
    }
    priority 99
    advert_int 2
    authentication {
        auth_type PASS
        auth_pass NGXPASS
    }
    track_script {
        check_nginx
    }
    virtual_ipaddress {
        192.168.2.217
    }
}

REDIS 实例
 vrrp_instance REDIS_INSTANCE_2 {
     state BACKUP
     interface em4
     nopreempt
     virtual_router_id 201
     mcast_src_ip 192.168.2.211
     priority 99
     advert_int 2
     authentication {
         auth_type PASS
         auth_pass RDSPASS
     }
     track_script {
         check_redis
     }
     virtual_ipaddress {
         192.168.2.218
     }
 }

**Notify and track scripts**
/bin/ps -ef |grep redis|grep -v grep

**Comment by pqarmitage** [comment]
I am not clear what your issue is here. Certainly there is no known issue with multiple interfaces and which ones are used; I have run keepalived with 248 interfaces successfully.

There is an error in your configuration as you have posted it, in the line above `vrrp_instance REDIS_INSTANCE_2 ` since there is no `#` at the beginning.

Since you are using `nopreempt` and the track_scripts have weights, the failure or success of a script will not cause a switch of which VRRP instance is master. Also, even if you weren't using `nopreempt` whether a switch of which VRRP instance is master would depend on the priorities configured in the keepalived configurations on the other systems.

Using `interval 2` and `timeout 10` is not ideal, since it will try re-running the script before it has timed out; the timeout should really be shorter than the interval.

Instead of your check_redis script, it would be much more efficient to use `track_process`.

I do not understand what you mean by `Track & U scripts mode`; could you please provide more information.

**Comment by duanbaihong** [comment]
> I am not clear what your issue is here. Certainly there is no known issue with multiple interfaces and which ones are used; I have run keepalived with 248 interfaces successfully.
> 
> There is an error in your configuration as you have posted it, in the line above `vrrp_instance REDIS_INSTANCE_2 ` since there is no `#` at the beginning.
> 
> Since you are using `nopreempt` and the track_scripts have weights, the failure or success of a script will not cause a switch of which VRRP instance is master. Also, even if you weren't using `nopreempt` whether a switch of which VRRP instance is master would depend on the priorities configured in the keepalived configurations on the other systems.
> 
> Using `interval 2` and `timeout 10` is not ideal, since it will try re-running the script before it has timed out; the timeout should really be shorter than the interval.
> 
> Instead of your check_redis script, it would be much more efficient to use `track_process`.
> 
> I do not understand what you mean by `Track & U scripts mode`; could you please provide more information.


Thank you for your answer! It may be that my description is not clear enough. I will describe it again.
1. When the interface of my NGINX_INSTANCE_1 is set as long as it is not the first online, the VIP will not be switched when the priority is lowered, and the VIPs of both KEEPALIVED hosts will exist at the same time. I feel that KEEPALIVED cannot receive multicast packets, but I use TCPDUMP packet capture can be received again. So there may be a problem with KEEPALIVED.
When I set it to INTERFACE eth0 on both sides there is no problem.
2. The configuration I put on is not the latest. I will re-attach my most configuration! And I paid for the configuration with no problems and problems now.
3. I have figured out the nopreempt parameter, and it is not necessary to set it in an application scenario like mine.

### The following is the normal configuration
`! Configuration File For Keepalived
#
# 第一台配置 192.168.2.205
global_defs {
    router_id ZMNID0
    script_user root
    enable_script_security
    vrrp_mcast_group4 224.0.0.18
    vrrp_higher_prio_send_advert true
    vrrp_garp_master_repeat 4
    vrrp_garp_lower_prio_repeat 2
    vrrp_garp_master_delay 5
    vrrp_garp_master_refresh 60
    vrrp_garp_master_refresh_repeat 1
}

#NGINX 检测脚本
vrrp_script check_nginx {
    script "/usr/bin/curl 127.0.0.1:80 -I"
    interval 2
    timeout 10
    weight -10
    fall 3
    rise 1
    init_fail
}

#REDIS 检测脚本
vrrp_script check_redis {
    script "/a/apps/keepalived/etc/keepalived/redis_check.sh"
    #script "/usr/bin/ps -ef|grep redis-sentinel"
    interval 2
    timeout 10
    weight -10
    fall 3
    rise 1
    init_fail
}


#NGINX 实例
vrrp_instance NGINX_INSTANCE_1 {
    state BACKUP
    interface eth0
    virtual_router_id 200
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass NGXPASS1
    }
    track_script {
        check_nginx
    }
    virtual_ipaddress {
        192.168.2.217/24 dev eth2
    }
}

# REDIS 实例
vrrp_instance REDIS_INSTANCE_2 {
    state BACKUP
    interface eth0
    virtual_router_id 201
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass RDSPASS
    }
    track_script {
        check_redis
    }
    virtual_ipaddress {
        192.168.2.218/24 dev eth3
    }
}`

### The following is a configuration that does not work properly (a VIP will exist on both sides of the synchronization):
`! Configuration File For Keepalived
#
# 第一台配置 192.168.2.205
global_defs {
    router_id ZMNID0
    script_user root
    enable_script_security
    vrrp_mcast_group4 224.0.0.18
    vrrp_higher_prio_send_advert true
    vrrp_garp_master_repeat 4
    vrrp_garp_lower_prio_repeat 2
    vrrp_garp_master_delay 5
    vrrp_garp_master_refresh 60
    vrrp_garp_master_refresh_repeat 1
}

#NGINX 检测脚本
vrrp_script check_nginx {
    script "/usr/bin/curl 127.0.0.1:80 -I"
    interval 2
    timeout 10
    weight -10
    fall 3
    rise 1
    init_fail
}

#REDIS 检测脚本
vrrp_script check_redis {
    script "/a/apps/keepalived/etc/keepalived/redis_check.sh"
    #script "/usr/bin/ps -ef|grep redis-sentinel"
    interval 2
    timeout 10
    weight -10
    fall 3
    rise 1
    init_fail
}


#NGINX 实例
vrrp_instance NGINX_INSTANCE_1 {
    state BACKUP
    interface eth1
    virtual_router_id 200
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass NGXPASS1
    }
    track_script {
        check_nginx
    }
    virtual_ipaddress {
        192.168.2.217/24 dev eth2
    }
}

# REDIS 实例
vrrp_instance REDIS_INSTANCE_2 {
    state BACKUP
    interface eth1
    virtual_router_id 201
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass RDSPASS
    }
    track_script {
        check_redis
    }
    virtual_ipaddress {
        192.168.2.218/24 dev eth3
    }
}`

That is, if the INTERFACE in INSTANCE is set as the second network card, there will be a problem

**Comment by pqarmitage** [comment]
When you change the interface of NGING_INSTANCE_1 do you change it in the configuration on the other system as well?

It is possible that there may be a firewall issue or connectivity issue between some of your interfaces. This is not a known keepalived issue, and I have run keepalived when there are several hundred interfaces and using any of the interfaces works.

**Comment by pqarmitage** [comment]
Closing due to no response for over 1 week. If you are still experiencing the problem please update this issue and we can reopen it.
