### ISSUE TITLE
Keepalived --enable-profile failed,on CentOS 7.2

### ISSUE THREAD

**Issue by duanbaihong** [acassen/keepalived#1572]
**Describe the bug**
The following error will appear during Make:
```
make[3]: 对“all-am”无需做任何事。
make[3]: 离开目录“/tmp/tmp/keepalived-2.0.20/keepalived/etc”
make[2]: 离开目录“/tmp/tmp/keepalived-2.0.20/keepalived/etc”
make[2]: 进入目录“/tmp/tmp/keepalived-2.0.20/keepalived”
  CC       main.o
  CCLD     keepalived
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/gcrt1.o: relocation R_X86_64_32S against `__libc_csu_fini' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/gcrt1.o: could not read symbols: 错误的值
collect2: 错误：ld 返回 1
make[2]: *** [keepalived] 错误 1
make[2]: 离开目录“/tmp/tmp/keepalived-2.0.20/keepalived”
make[1]: *** [all-recursive] 错误 1
make[1]: 离开目录“/tmp/tmp/keepalived-2.0.20/keepalived”
make: *** [all-recursive] 错误 1
```
**To Reproduce**
Any steps necessary to reproduce the behaviour:
My compilation parameters: / configure --prefix = / a / apps / keepalived --enable-json --enable-sha1 --enable-profile;
make

**Keepalived version**
keepalived-2.0.20

**Distro (please complete the following information):**
CentOS
7.2.1511
x86_64

**Comment by pqarmitage** [comment]
Many thanks for reporting this. If you add the `--disable-hardening` option, then it should build OK.

I will try and add a test for this problem in configure.ac.

**Comment by pqarmitage** [comment]
Commit acff467 resolves this issue.
