### ISSUE TITLE
Keepalived service can’t start after os system reboot

### ISSUE THREAD

**Issue by tanshaolong** [acassen/keepalived#1574]
**Describe the issue**
I installed keepalived at a mysql cluster and set “enabled” value of keepalived service to yes. The keepalived worked well. I reboot a mysql node but I found the keepalived service didn’t start after the os started. I can start the keepalived service manually.
   I don’t know the reason of the issue. I just guest some services that keepalived is necessary start slow than keepalived service. Maybe, this cause the issue. Who could give some hint how to fix it? Thank for you. 

**To Reproduce**
reboot os and can't find keepalived service is started

**Expected behavior**
Keepalived service is started after os reboot

**Keepalived version**
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

**Distro (please complete the following information):**
 - Name: Centos
 - Version 7.3
 - Architecture x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
keepalived run at vm of vmware

**Configuration file:**
```
global_defs {
   router_id LVS_DEVEL
}

vrrp_script check_mysql {
    script "/etc/keepalived/mysql_check.sh"
    interval 2
    weight -5
    fall 3
    rise 2
}

vrrp_instance VI_1 {
    state MASTER
    priority 255
    interface ens192
    virtual_router_id 52
    advert_int 1
    mcast_src_ip 192.168.**.**
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        192.168.**.**/21 dev ens192
    }

    track_script {
        check_mysql
    }
}
```

**Notify and track scripts**
```
# cat /etc/keepalived/mysql_check.sh
MYSQL=/usr/bin/mysql
MYSQL_HOST=127.0.0.1
MYSQL_USER=root
MYSQL_PASSWORD="********"
MYSQL_PORT=3306
LOG_FILE=/etc/keepalived/check_mysql.log
CHECK_TIME=3

#mysql is working MYSQL_OK is 1 , mysql down MYSQL_OK is 0
MYSQL_OK=1

function check_mysql_helth (){
    $MYSQL -h $MYSQL_HOST -u $MYSQL_USER -p${MYSQL_PASSWORD} -P${MYSQL_PORT} -e "show status;" >/dev/null 2>&1
    if [ $? = 0 ] ;then
    MYSQL_OK=1
    else
    MYSQL_OK=0
    fi
    return $MYSQL_OK
}
while [ $CHECK_TIME -ne 0 ]
do
let "CHECK_TIME -= 1"
check_mysql_helth
if [ $MYSQL_OK = 1 ] ; then
CHECK_TIME=0
#echo `date --date=today +"%Y-%M-%d %H:%m:%S"` - [INFO] - mysql available: success[$MYSQL_OK] >> $LOG_FILE
exit 0
fi
if [ $MYSQL_OK -eq 0 ] && [ $CHECK_TIME -eq 0 ]
then
systemctl stop keepalived
echo `date --date=today +"%Y-%M-%d %H:%m:%S"` - [INFO] - mysql invaild. keepalived stop. >> $LOG_FILE

exit 1
fi
done
```

**System Log entries**
```
```
May 18 22:54:55 localhost Keepalived[887]: Starting Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
May 18 22:54:55 localhost Keepalived[887]: Opening file '/etc/keepalived/keepalived.conf'.
May 18 22:54:55 localhost Keepalived[1143]: Starting Healthcheck child process, pid=1145
May 18 22:54:55 localhost Keepalived[1143]: Starting VRRP child process, pid=1146
May 18 22:54:55 localhost Keepalived_vrrp[1146]: Registering Kernel netlink reflector
May 18 22:54:55 localhost Keepalived_vrrp[1146]: Registering Kernel netlink command channel
May 18 22:54:55 localhost Keepalived_vrrp[1146]: Registering gratuitous ARP shared channel
May 18 22:54:55 localhost Keepalived_vrrp[1146]: Opening file '/etc/keepalived/keepalived.conf'.
May 18 22:54:55 localhost Keepalived_vrrp[1146]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
May 18 22:54:55 localhost Keepalived_vrrp[1146]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
May 18 22:54:55 localhost Keepalived_vrrp[1146]: VRRP_Instance(VI_1) removing protocol VIPs.
May 18 22:54:55 localhost Keepalived_vrrp[1146]: Using LinkWatch kernel netlink reflector...
May 18 22:54:55 localhost Keepalived_vrrp[1146]: VRRP sockpool: [ifindex(2), proto(112), unicast(0), fd(10,11)]
May 18 22:54:55 localhost systemd: Started LVS and VRRP High Availability Monitor.
May 18 22:54:55 localhost Keepalived_vrrp[1146]: VRRP_Instance(VI_1) Transition to MASTER STATE
May 18 22:54:55 localhost kernel: nf_conntrack version 0.5.0 (16384 buckets, 65536 max)
May 18 22:54:55 localhost systemd: PID file /var/run/sshd.pid not readable (yet?) after start.
May 18 22:54:55 localhost systemd: Started OpenSSH server daemon.
May 18 22:54:55 localhost kernel: IPVS: Registered protocols (TCP, UDP, SCTP, AH, ESP)
May 18 22:54:55 localhost kernel: IPVS: Connection hash table configured (size=4096, memory=64Kbytes)
May 18 22:54:55 localhost kernel: IPVS: Creating netns size=2040 id=0
May 18 22:54:55 localhost kernel: IPVS: Creating netns size=2040 id=1
May 18 22:54:55 localhost kernel: IPVS: ipvs loaded.
May 18 22:54:55 localhost Keepalived_healthcheckers[1145]: Opening file '/etc/keepalived/keepalived.conf'.
May 18 22:54:56 localhost Keepalived[1143]: Stopping
May 18 22:54:56 localhost Keepalived_vrrp[1146]: VRRP_Instance(VI_1) sent 0 priority
May 18 22:54:56 localhost systemd: Stopping LVS and VRRP High Availability Monitor...
May 18 22:54:56 localhost Keepalived_healthcheckers[1145]: Stopped
May 18 22:54:57 localhost Keepalived_vrrp[1146]: Stopped
```
```

**Did keepalived coredump?**
No

**Additional context**
No

**Comment by pqarmitage** [comment]
I presume you have run `systemctl enable keepalived` to enable keepalived. If not, could you please explain what you have done to enable keepalived.

When I reboot my CentOS 7 VM with keepalived enabled, it starts up without a problem.

From the logs above, which I assume is following an OS reboot, keepalived does start, but for some reason systemd then stops keepalived - the log entry `systemd: Stopping LVS and VRRP High Availability Monitor...` is what you get if you execute `systemctl stop keealived`. I do not know why systemd is stopping keepalived, but unfortunately it is outside the scope of keepalived itself; in this case keepalived appears to merely be doing what it is told to do, i.e. it starts up and then it stops.

I suggest you look at what keepalived is doing, and is there any other service that for some reason is stopping keepalived. You could try disabling other services selectively to see if one of those is causing the problem.
