### ISSUE TITLE
Problem with keepalived restart

### ISSUE THREAD

**Issue by inspirit1986** [acassen/keepalived#1577]
Hi, I have a little problem.
So, I have two nodes in keepalived cluster.
One node is master(prio 30) and one is backup(prio 20).

When I restart keepalived on master(systemctl restart keepalived) then keepalived on backup node goes to Master state immediately then it goes back to backup state again.

How can I can make restart keepalived service on master node and backup node stay in backup state.

**Comment by pqarmitage** [comment]
This depends on the reason you want to restart keepalived. If what you really want to do is load a new configuration, then you should **reload** keepalived (_systemctl reload keepalived_) as opposed to **restart** it; then the keepalived instance will not stop running, and will remain master for any vrrp instances for which it was master and the new configuration dictates it should still be master.

Restarting keepalived, on the other hand, stops keepalived and then starts it again. When keepalived stops, it sends a special advert for any instances for which it was master, with the priority set to 0; this triggers a faster takeover by another instance to become master compared to if the restarting master just stopped sending adverts (this is part of the VRRP protocol). When keepalived starts again, instances will start in the backup state and only take over as master again if the normal timeout expires, which is 3 advert intervals plus a bit (depends on priority). So the scenario you describe above is correct for restarting.

If you had higher priorities, e.g. using 250 and 240 the takeovers as master would happen slightly quicker.

I suppose the real question is: Why are you restarting keepalived at all? But that I think is not part of this issue.
