### ISSUE TITLE
keepalived Pre-defined variables / Sequence blocks

### ISSUE THREAD

**Issue by 79U** [acassen/keepalived#1581]
**Is your feature request to resolve a problem or provide enhanced functionality? Please describe.**

keepalived currently only supports sequence blocks with fixed steps, which is quite useful for continuous/regular resources configuration. however, we need sometimes to allocate a list of user-defined resources. it should be defined like a variable but act like sequence blocks.

**Describe the solution you would like**

I want keepalived to support custom lists or nested loops, for example：

      $real_server= \
           real_server 1.0.0.${list.iter} 80 { \
               weight 1 \
               HTTP_GET { \
                   url { \
                       path / \
                   } \
                } \
             }
            
      $list=[1, 12, 23 ]
      $real_server

${list.iter} is the element of a custom list , $real_server iterate over all the elements in the custom list

**Would the feature request be of benefit only to you, or is it more generally applicable?**

I think it should be a generic configuration. The predefined configuration makes the configuration file easy and concise, so the discontinuous configuration should also be popular

**Keepalived version**

    Keepalived v2.0.18 (07/26,2019)

    Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

    Built with kernel headers for Linux 2.6.32
    Running on Linux 4.9.0 #5 SMP Thu Sep 27 20:07:46 CST 2018

    configure options: --prefix=/usr/local/keepalived --disable-snmp --enable-strict-config-checks --enable-bfd

    Config options:  STRICT_CONFIG LVS VRRP VRRP_AUTH BFD OLD_CHKSUM_COMPAT FIB_ROUTING

    System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV6_ADVANCED_API LIBNL1 IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC GLOB_BRACE SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Comment by xgxzj** [comment]
it's an enhancement

**Comment by pqarmitage** [comment]
It is an enhancement but it is a good idea.

**Comment by xgxzj** [comment]
using a similar syntax like '~SEQ(VAR, 1,2,21)', say, '~LST(VAR, 1, 12, 13, ...)', for example, and limiting the length, seems to be an easier and quicker solution.

**Comment by pqarmitage** [comment]
Commit 264eb68 adds the `~LST(VAR, 1, 12, 13, ...)` option. If also extends it to allow substitution of more that one variable, so
`~LST({IP, IP1}, {10,1},{20,4},{5,6},{12,8}) 192.168.${IP}.${IP1}`
produces:
```
192.168.10.1
192.168.20.4
192.168.5.6
192.168.12.8
```

More details are near the end of the keepalived.conf(5) man page.
