### ISSUE TITLE
keepalived reload problem

### ISSUE THREAD

**Issue by inspirit1986** [acassen/keepalived#1587]
Hi, I have a problem with keepalived **reload** mechanism and persistence_timeout setup

**To Reproduce**
- start keepalived without persistence_timeout option in configuration
- ipvsadm -Ln (show that we are no persistence flag in ipvs config. ok)
- add **persistence_timeout 13** in keeaplived virtual_service config
-  run systemctl reload keepalived
- ipvsadm -Ln (nothing differs. no persistence flag on virtual_server)
- run systemct restart keepalived
- ipvsadm -Ln (persistence flag exist.)

**Expected behavior**
I expect - when I add persistence_timeout 13 in keepalived config file and **reload** it - this change correctly reflect to ipvs configuration at the end. 

**Keepalived version**
Keepalived v2.0.20 (01/22,2020)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.0
Running on Linux 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --enable-json --enable-snmp-rfc --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LIBIPTC LVS VRRP VRRP_AUTH JSON OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK

**Distro (please complete the following information):**
Centos 8 X86_64

**Details of any containerisation or hosted service (e.g. AWS)**
nope

**Configuration file:**

```
global_defs
{
        router_id name_1
        lvs_timeouts tcp 300 tcpfin 120 udp 300
        vrrp_garp_lower_prio_repeat 1
        vrrp_garp_master_refresh 60
        vrrp_garp_master_refresh_repeat 2
##        lvs_sync_daemon eth0 VI_1
        enable_script_security
        script_user root
}

vrrp_instance VI_1
{
        state MASTER

        unicast_src_ip 192.168.201.45
        unicast_peer {
                          192.168.201.46
                }
        priority 30
        interface eth0
        virtual_router_id 1
        advert_int 1
        virtual_ipaddress {
           192.168.201.51 dev eth0
        }
        notify_backup "/etc/iptables backup"
        notify_master "/etc/iptables master"
}

virtual_server 192.168.201.51 3128 {
  delay_loop 5
  lb_algo wrr
  lb_kind DR
  protocol TCP



    real_server 192.168.201.45 3128 {
          weight 100
            MISC_CHECK {
                misc_path "/usr/bin/keepalived_check 192.168.201.45 3128"
                misc_timeout 60
              }
        }

    real_server 192.168.201.46 3128 {
          weight 200
            MISC_CHECK {
                misc_path "/usr/bin/keepalived_check 192.168.201.46 3128"
                misc_timeout 60
              }
        }
  }

virtual_server 192.168.201.51 8080 {
  delay_loop 5
  lb_algo wrr
  lb_kind DR
  protocol TCP
  persistence_timeout 13

    real_server 192.168.201.45 8080 {
          weight 100
            MISC_CHECK {
                misc_path "/usr/bin/keepalived_check 192.168.201.45 8080"
                misc_timeout 60
              }
        }

    real_server 192.168.201.46 8080 {
          weight 200
            MISC_CHECK {
                misc_path "/usr/bin/keepalived_check 192.168.201.46 8080"
                misc_timeout 60
              }
        }
  }

```

**Comment by pqarmitage** [comment]
This was resolved in commit 57a6be3.
