### ISSUE TITLE
keepalived restart related issue

### ISSUE THREAD

**Issue by senthilnathann** [acassen/keepalived#1589]
**Describe the issue**
I have restarted my high priority IP keepalived machine ,it's went to backup state and after few seconds ,automatically come back to  Master state.

Initial state : Master
After restart : Went to backup
After few seconds : Automatically came back to Master

We are using same priority for both Master & Backup.

Why automatically changed as Master ?  

High priority IP is the reason ?

It's only happens in some virtual machines ,why it's happens ?

**To Reproduce**
Not able to reproduce the issue,it's happens some virtual machines

**Expected behavior**
If we restart the keepalived , keepalived went to back state and maintain the same state until any issues will happen

**Keepalived version**
v1.2.13

**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu]
 - Version [e.g. 29]
 - Architecture [e.g. x86_64]
CentOS Linux release 7.6.1810

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
vrrp_instance VI_1 {
        priority 100
        interface bond0
        virtual_router_id 150
        advert_int 1
        authentication {
                auth_type PASS
                auth_pass ******
        }
        virtual_ipaddress {
                *****
                ******
                ******
        }
        virtual_ipaddress_excluded {
                ******
}
Same configuration file has been used in BACKUP server .

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Master LOG : 

May 29 03:08:37 10 Keepalived[40798]: Stopping Keepalived v1.2.13 (03/01,2018)
May 29 03:08:37 10 Keepalived_vrrp[40800]: VRRP_Instance(VI_1) sending 0 priority
May 29 03:08:37 10 Keepalived_vrrp[40800]: VRRP_Instance(VI_1) removing protocol VIPs.
May 29 03:08:37 10 Keepalived_vrrp[40800]: VRRP_Instance(VI_1) removing protocol E-VIPs.
May 29 03:08:37 10 Keepalived[32598]: Starting Keepalived v1.2.13 (03/01,2018)
May 29 03:08:37 10 Keepalived[32599]: Starting Healthcheck child process, pid=32600
May 29 03:08:37 10 Keepalived[32599]: Starting VRRP child process, pid=32601
May 29 03:08:37 10 Keepalived_vrrp[32601]: Netlink reflector reports IP 10.20.0.14 added
May 29 03:08:37 10 Keepalived_vrrp[32601]: Netlink reflector reports IP fe80::5054:ff:fec2:d5dc added
May 29 03:08:37 10 Keepalived_vrrp[32601]: Registering Kernel netlink reflector
May 29 03:08:37 10 Keepalived_vrrp[32601]: Registering Kernel netlink command channel
May 29 03:08:37 10 Keepalived_vrrp[32601]: Registering gratuitous ARP shared channel
May 29 03:08:37 10 Keepalived_vrrp[32601]: Opening file '/etc/keepalived/keepalived.conf'.
May 29 03:08:37 10 Keepalived_vrrp[32601]: Configuration is using : 109564 Bytes
May 29 03:08:37 10 Keepalived_vrrp[32601]: Using LinkWatch kernel netlink reflector...
May 29 03:08:37 10 Keepalived_vrrp[32601]: VRRP_Instance(VI_1) Entering BACKUP STATE
May 29 03:08:37 10 Keepalived_vrrp[32601]: VRRP sockpool: [ifindex(2), proto(112), unicast(0), fd(10,11)]
May 29 03:08:41 10 Keepalived_vrrp[32601]: VRRP_Instance(VI_1) Transition to MASTER STATE
May 29 03:08:42 10 Keepalived_vrrp[32601]: VRRP_Instance(VI_1) Entering MASTER STATE
May 29 03:08:42 10 Keepalived_vrrp[32601]: VRRP_Instance(VI_1) setting protocol VIPs.
May 29 03:08:42 10 Keepalived_vrrp[32601]: VRRP_Instance(VI_1) setting protocol E-VIPs.

**Did keepalived coredump?**
If so, can you please provide a stacktrace from the coredump, using gdb.

**Additional context**

**Comment by pqarmitage** [comment]
This may have been an issue in v1.2.13, but I have tested this with v2.0.20 (the current version) and the issue does not occur; i.e. if two or more VRRP instances have the same priority, the existing master will carry on as master.

Please upgrade to v2.0.20 and if you still have the problem then update this issue and it can be reopened.
