### ISSUE TITLE
Invalid parameter of startup_script_timeout generates segfault

### ISSUE THREAD

**Issue by Mint-M** [acassen/keepalived#1591]
**Describe the bug**
Invalid parameter of startup_script_timeout generates segfault.
I forget to delete 'SECONDS ' copied from man page and accidentally find this bug. 

**To Reproduce**
Build the snapshot version of keepalived(after commit 3c434317a0f9b15cb75d631bb2e0c86ae109835c).
Use the configuration below to start keepalived from systemd or simply test configuration (keepalived -t).

**Expected behavior**
Exit normally.

**Keepalived version**
Keepalived v2.0.20 (unknown)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.0
Running on Linux 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-nftables --disable-libipset --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA IPTABLES NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK

**Distro (please complete the following information):**
CentOS 8.1
4.18.0-147.5.1.el8_1.x86_64 

**Details of any containerisation or hosted service (e.g. AWS)**
KVM

**Configuration file:**
! Configuration File for keepalived

global_defs {
    startup_script 
    startup_script_timeout SECONDS 1000
    vrrp_mcast_group4 224.0.0.28
}

vrrp_instance eth0 {
    state BACKUP
    interface eth0
    virtual_router_id 7
    priority 100
    advert_int 1
    virtual_ipaddress {
        10.0.0.1/16 dev eth0
    }
}

**Notify and track scripts**
Independent

**System Log entries**
keepalived -t
(Line 4) startup script missing
(Line 5) invalid number 'SECONDS'
(Line 5) startup_script_timeout 'SECONDS' must be in [1, 1000] - ignoring
moSegmentation fault (core dumped)

May 29 17:23:48 centos8-builder Keepalived[15888]: VRRP child process(25409) died: Respawning
May 29 17:23:48 centos8-builder Keepalived[15888]: Starting VRRP child process, pid=25417
May 29 17:23:48 centos8-builder Keepalived_vrrp[25417]: Registering Kernel netlink reflector
May 29 17:23:48 centos8-builder Keepalived_vrrp[25417]: Registering Kernel netlink command channel
May 29 17:23:48 centos8-builder Keepalived_vrrp[25417]: Opening file '/etc/keepalived/keepalived.conf'.
May 29 17:23:48 centos8-builder Keepalived_vrrp[25417]: Assigned address  for interface eth0
May 29 17:23:48 centos8-builder Keepalived_vrrp[25417]: Assigned address  for interface eth0
May 29 17:23:48 centos8-builder Keepalived[15888]: pid 25417 exited due to segmentation fault (SIGSEGV).
May 29 17:23:48 centos8-builder Keepalived[15888]:   Please report a bug at https://github.com/acassen/keepalived/issues
May 29 17:23:48 centos8-builder Keepalived[15888]:   and include this log from when keepalived started, a description
May 29 17:23:48 centos8-builder Keepalived[15888]:   of what happened before the crash, your configuration file and the details below.
May 29 17:23:48 centos8-builder Keepalived[15888]:   Also provide the output of keepalived -v, what Linux distro and version
May 29 17:23:48 centos8-builder Keepalived[15888]:   you are running on, and whether keepalived is being run in a container or VM.
May 29 17:23:48 centos8-builder Keepalived[15888]:   A failure to provide all this information may mean the crash cannot be investigated.
May 29 17:23:48 centos8-builder Keepalived[15888]:   If you are able to provide a stack backtrace with gdb that would really help.
May 29 17:23:48 centos8-builder Keepalived[15888]:   Source version 2.0.20
May 29 17:23:48 centos8-builder Keepalived[15888]:   Built with kernel headers for Linux 4.18.0
May 29 17:23:48 centos8-builder Keepalived[15888]:   Running on Linux 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020
May 29 17:23:48 centos8-builder Keepalived[15888]:   Command line: '/usr/sbin/keepalived' '-D'
May 29 17:23:48 centos8-builder Keepalived[15888]:   configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix=
May 29 17:23:48 centos8-builder Keepalived[15888]:                      --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin
May 29 17:23:48 centos8-builder Keepalived[15888]:                      --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share
May 29 17:23:48 centos8-builder Keepalived[15888]:                      --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec
May 29 17:23:48 centos8-builder Keepalived[15888]:                      --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man
May 29 17:23:48 centos8-builder Keepalived[15888]:                      --infodir=/usr/share/info --disable-nftables --disable-libipset --with-init=systemd
May 29 17:23:48 centos8-builder Keepalived[15888]:                      build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu
May 29 17:23:48 centos8-builder Keepalived[15888]:                      PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe
May 29 17:23:48 centos8-builder Keepalived[15888]:                      -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS
May 29 17:23:48 centos8-builder Keepalived[15888]:                      -fexceptions -fstack-protector-strong -grecord-gcc-switches
May 29 17:23:48 centos8-builder Keepalived[15888]:                      -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1
May 29 17:23:48 centos8-builder Keepalived[15888]:                      -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic
May 29 17:23:48 centos8-builder Keepalived[15888]:                      -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
May 29 17:23:48 centos8-builder Keepalived[15888]:                      LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
May 29 17:23:48 centos8-builder Keepalived[15888]:   Config options: LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING
May 29 17:23:48 centos8-builder Keepalived[15888]:   System options: PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API
May 29 17:23:48 centos8-builder Keepalived[15888]:                   LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN
May 29 17:23:48 centos8-builder Keepalived[15888]:                   FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS
May 29 17:23:48 centos8-builder Keepalived[15888]:                   FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL
May 29 17:23:48 centos8-builder Keepalived[15888]:                   FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS
May 29 17:23:48 centos8-builder Keepalived[15888]:                   IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA IPTABLES
May 29 17:23:48 centos8-builder Keepalived[15888]:                   NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY
May 29 17:23:48 centos8-builder Keepalived[15888]:                   IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC
May 29 17:23:48 centos8-builder Keepalived[15888]:                   SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK
May 29 17:23:48 centos8-builder Keepalived[15888]:                   SCHED_RESET_ON_FORK
May 29 17:23:48 centos8-builder Keepalived[15888]: VRRP child process(25417) died: Respawning
May 29 17:23:48 centos8-builder Keepalived[15888]: Starting VRRP child process, pid=25424

**Did keepalived coredump?**
GNU gdb (GDB) Red Hat Enterprise Linux 8.2-6.el8_0
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/keepalived...Reading symbols from .gnu_debugdata for /usr/sbin/keepalived...(no debugging symbols found)...done.
(no debugging symbols found)...done.
[New LWP 15781]

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments
Core was generated by `keepalived -t'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000555b2fb4e5f7 in inet_sockaddrip4 ()
Missing separate debuginfos, use: dnf debuginfo-install keepalived-2.0.20-1.el8.x86_64
(gdb) bt
#0  0x0000555b2fb4e5f7 in inet_sockaddrip4 ()
#1  0x0000555b2fb3410b in vrrp_complete_init ()
#2  0x0000555b2fb26c5b in start_vrrp ()
#3  0x0000555b2fb05e73 in keepalived_main ()
#4  0x00007f157f8e9873 in __libc_start_main () from /lib64/libc.so.6
#5  0x0000555b2fb0343e in _start ()

**Additional context**
Keepalived also crashes continuously after started from systemd which causes cpu and disk usage.
May be a limitation should be implemented?

**Comment by Mint-M** [comment]
Even the correct parameters could cause crash.
    startup_script /etc/keepalived/start.sh
    startup_script_timeout 1000

**Comment by pqarmitage** [comment]
Commit 8048c91 resolved this issue.

Many thanks for reporting it.
