### ISSUE TITLE
Bug on snmp result of vrrpInstanceInitialState

### ISSUE THREAD

**Issue by Denden54** [acassen/keepalived#1593]
I have an error on snmp result for a vrrp as we can see here :

12:46:07 # snmpwalk -v2c -cpublic SERVER KEEPALIVED-MIB::vrrpInstanceTable
KEEPALIVED-MIB::vrrpInstanceName.1 = STRING: 5
KEEPALIVED-MIB::vrrpInstanceVirtualRouterId.1 = Gauge32: 5
KEEPALIVED-MIB::vrrpInstanceState.1 = INTEGER: master(2)
KEEPALIVED-MIB::vrrpInstanceInitialState.1 = INTEGER: backup(1)
KEEPALIVED-MIB::vrrpInstanceWantedState.1 = INTEGER: master(2)
KEEPALIVED-MIB::vrrpInstanceBasePriority.1 = INTEGER: 150
KEEPALIVED-MIB::vrrpInstanceEffectivePriority.1 = INTEGER: 150
KEEPALIVED-MIB::vrrpInstanceVipsStatus.1 = INTEGER: allSet(1)
KEEPALIVED-MIB::vrrpInstancePrimaryInterface.1 = STRING: eth0
KEEPALIVED-MIB::vrrpInstanceTrackPrimaryIf.1 = INTEGER: notTracked(2)
KEEPALIVED-MIB::vrrpInstanceAdvertisementsInt.1 = Gauge32: 5 seconds(VRRPv2) / centiseconds(VRRPv3)
KEEPALIVED-MIB::vrrpInstancePreempt.1 = INTEGER: preempt(1)
KEEPALIVED-MIB::vrrpInstancePreemptDelay.1 = Gauge32: 0 seconds
KEEPALIVED-MIB::vrrpInstanceAuthType.1 = INTEGER: ah(2)
KEEPALIVED-MIB::vrrpInstanceLvsSyncDaemon.1 = INTEGER: disabled(2)
KEEPALIVED-MIB::vrrpInstanceGarpDelay.1 = Gauge32: 5 seconds
KEEPALIVED-MIB::vrrpInstanceSmtpAlert.1 = INTEGER: disabled(2)
KEEPALIVED-MIB::vrrpInstanceNotifyExec.1 = INTEGER: disabled(2)
KEEPALIVED-MIB::vrrpInstanceAccept.1 = INTEGER: 0
KEEPALIVED-MIB::vrrpInstancePromoteSecondaries.1 = INTEGER: false(2)
KEEPALIVED-MIB::vrrpInstanceUseLinkbeat.1 = INTEGER: false(2)
KEEPALIVED-MIB::vrrpInstanceVrrpVersion.1 = INTEGER: vrrpv2(2)

We can see this line : 
KEEPALIVED-MIB::vrrpInstanceInitialState.1 = INTEGER: backup(1)

But if we check the configuration of the vrrp : 

> global_defs {
>   enable_traps
>   router_id SERVER
> }
> 
> vrrp_instance 5 {
>   virtual_router_id 5
> 
>   advert_int 5
> 
>   priority 150
>   state MASTER
>   interface eth0
>   virtual_ipaddress {
>       <IP>
>   }
> 
>   authentication {
>     auth_type <type>
>     auth_pass <pass>
>   }
> }

The initial state should be master.

Am I wrong ?

**Comment by pqarmitage** [comment]
`state MASTER` in the configuration doesn't actually do anything.

As it says in the keepalived.conf(5) man page.
```
    # Initial state, MASTER|BACKUP
    # As soon as the other machine(s) come up,
    # an election will be held and the machine
    # with the highest priority will become MASTER.
    # So the entry here doesn't matter a whole lot.
```

If a VRRP instance has priority 255 it will start in master state, otherwise it will start in backup state. If the priority is less than 255, then there may be another instance with a higher priority, so it is not safe to transition to master.

So, even though `state MASTER` is configured, because the priority is not 255 the vrrp instance will startup in backup mode, and so what SNMP is reporting is what actually is the situation.
