### ISSUE TITLE
Keepalive 2.1 crashing on start with segfault

### ISSUE THREAD

**Issue by braninl** [acassen/keepalived#1621]
**Describe the bug**
After Snap automatically refreshed Keepalived to 2.1 this morning, Keepalived started crashing on start once a minute.  Reverting to 2.0.20 immediately fixed the issue.

**To Reproduce**
Any steps necessary to reproduce the behaviour:  Use snap to install Keepalived on Ubuntu 18.04.4 in Classic mode.  Allow snap to refresh Keepalived to 2.1.  See it crash.  Use snap revert keepalived to go back to 2.0.20.  See it not crash.

**Expected behavior**
Keepalived should not crash on start.

**Keepalived version**
Keepalived v2.0.20 (01/22,2020), git commit v2.0.20+

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.15.18
Running on Linux 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020

configure options: --prefix= --prefix=/usr --enable-bfd --enable-dbus --enable-json --enable-regex --enable-snmp --enable-snmp-rfc --disable-libipset-dynamic LDFLAGS= -L/build/keepalived/stage/lib -L/build/keepalived/stage/usr/lib -L/build/keepalived/stage/lib/x86_64-linux-gnu -L/build/keepalived/stage/usr/lib/x86_64-linux-gnu

Config options:  LIBIPTC LIBIPSET NFTABLES LVS REGEX VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK

**Distro (please complete the following information):**
Ubuntu 18.04.4 LTS on x86_64
Linux XXX 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Details of any containerisation or hosted service (e.g. AWS)**
On-premise Vsphere VM, without any containerisation used.

**Configuration file:**
global_defs {
  notification_email {
    alerts.it@XXX.com
  }
  notification_email_from XXX@XXX.com
  smtp_server X.X.X.X
  smtp_connect_timeout 30
  router_id XXX
  script_user root
  enable_script_security
  vrrp_garp_lower_prio_repeat 1
  vrrp_garp_lower_prio_delay 10
  vrrp_garp_master_refresh 60
  vrrp_higher_prio_send_advert true
}

vrrp_script chkhaproxy {
  script "/usr/bin/killall -0 haproxy"
  interval 2
  fall 2
  rise 2
  weight 100
}

vrrp_instance lass-Internal {
  virtual_router_id 102
  advert_int 4
  priority 8
  state BACKUP
  interface ens160
  authentication {
    auth_type PASS
    auth_pass XXX
  }
  virtual_ipaddress {
    X.X.X.X dev ens160
  }
  smtp_alert
  track_script {
    chkhaproxy
  }
}

**Notify and track scripts**
See configuration file above.  Just checking haproxy running.

**System Log entries**
The following is in Syslog, repeating every minute:
Jun 13 10:23:58 XXX Keepalived[4521]: Starting VRRP child process, pid=26174
Jun 13 10:23:58 XXX Keepalived_vrrp[26174]: Registering Kernel netlink reflector
Jun 13 10:23:58 XXX Keepalived_vrrp[26174]: Registering Kernel netlink command channel
Jun 13 10:23:58 XXX Keepalived_vrrp[26174]: Opening file '/etc/keepalived/keepalived.conf'.
Jun 13 10:23:58 XXX Keepalived_vrrp[26174]: Please add a #! shebang to script /usr/bin/killall
Jun 13 10:23:58 XXX Keepalived_vrrp[26174]: Registering gratuitous ARP shared channel
Jun 13 10:23:58 XXX Keepalived_vrrp[26174]: (lass-Internal) Entering BACKUP STATE (init)
Jun 13 10:23:58 XXX Keepalived_vrrp[26174]: Remote SMTP server [X.X.X.X]:25 connected.
Jun 13 10:23:58 XXX Keepalived_vrrp[26174]: VRRP_Script(chkhaproxy) succeeded
Jun 13 10:23:58 XXX Keepalived_vrrp[26174]: (lass-Internal) Changing effective priority from 8 to 108
Jun 13 10:23:59 XXX kernel: [170754.104305] keepalived-415[26174]: segfault at 1c9c380 ip 00007f132899ccc0 sp 00007ffebd201cf0 error 4 in libc-2.23.so[7f132894e000+1c0000]
Jun 13 10:23:59 XXX Keepalived[4521]: pid 26174 exited due to segmentation fault (SIGSEGV).
Jun 13 10:23:59 XXX Keepalived[4521]:   Please report a bug at https://github.com/acassen/keepalived/issues
Jun 13 10:23:59 XXX Keepalived[4521]:   and include this log from when keepalived started, a description
Jun 13 10:23:59 XXX Keepalived[4521]:   of what happened before the crash, your configuration file and the details below.
Jun 13 10:23:59 XXX Keepalived[4521]:   Also provide the output of keepalived -v, what Linux distro and version
Jun 13 10:23:59 XXX Keepalived[4521]:   you are running on, and whether keepalived is being run in a container or VM.
Jun 13 10:23:59 XXX Keepalived[4521]:   A failure to provide all this information may mean the crash cannot be investigated.
Jun 13 10:23:59 XXX Keepalived[4521]:   If you are able to provide a stack backtrace with gdb that would really help.
Jun 13 10:23:59 XXX Keepalived[4521]:   Source version 2.1.0 , git commit v2.1.0+
Jun 13 10:23:59 XXX Keepalived[4521]:   Built with kernel headers for Linux 4.4.223
Jun 13 10:23:59 XXX Keepalived[4521]:   Running on Linux 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020
Jun 13 10:23:59 XXX Keepalived[4521]:   Command line: '/snap/keepalived/1294/usr/sbin/keepalived-415'
Jun 13 10:23:59 XXX Keepalived[4521]:   configure options: --prefix= --prefix=/usr --enable-bfd --enable-dbus --enable-json --enable-regex
Jun 13 10:23:59 XXX Keepalived[4521]:                      --enable-snmp --enable-snmp-rfc --disable-libipset-dynamic LDFLAGS=
Jun 13 10:23:59 XXX Keepalived[4521]:                      -L/build/keepalived/stage/lib -L/build/keepalived/stage/usr/lib
Jun 13 10:23:59 XXX Keepalived[4521]:                      -L/build/keepalived/stage/lib/x86_64-linux-gnu
Jun 13 10:23:59 XXX Keepalived[4521]:                      -L/build/keepalived/stage/usr/lib/x86_64-linux-gnu
Jun 13 10:23:59 XXX Keepalived[4521]:   Config options: LIBIPSET NFTABLES LVS REGEX VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING
Jun 13 10:23:59 XXX Keepalived[4521]:                   SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS
Jun 13 10:23:59 XXX Keepalived[4521]:   System options: PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API
Jun 13 10:23:59 XXX Keepalived[4521]:                   LIBNL3 RTA_ENCAP RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP
Jun 13 10:23:59 XXX Keepalived[4521]:                   FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS RTA_VIA FRA_OIFNAME
Jun 13 10:23:59 XXX Keepalived[4521]:                   IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPSET_PRE_V7
Jun 13 10:23:59 XXX Keepalived[4521]:                   IPTABLES NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY
Jun 13 10:23:59 XXX Keepalived[4521]:                   IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC
Jun 13 10:23:59 XXX Keepalived[4521]:                   SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK
Jun 13 10:23:59 XXX Keepalived[4521]:                   SCHED_RESET_ON_FORK
Jun 13 10:23:59 XXX Keepalived[4521]: VRRP child process(26174) died: Respawning
Jun 13 10:23:59 XXX Keepalived[4521]: Restart of VRRP process delayed 60 seconds to limit respawn rate

**Did keepalived coredump?**
I don't believe there is a coredump.

**Additional context**
This happens on all 6 of our servers running Keepalived (for 3 different VRRP and HAProxy instances), regardless if the server is a MASTER or a BACKUP.

**Comment by mkrogh** [comment]
Have the same problem on a bunch of servers, except for one pair.

The pair that are working does **NOT** have the following config:

```
global_defs {
  notification_email {
      mail@example.com
  }
  ...
}
```

Removing the `notification_email` seems to have stopped the segfaulting for now.

**Comment by pqarmitage** [comment]
Commit 04e18f4 resolves this issue. @branini Many thanks for reporting this, and @mkrogh many thanks for the diagnosis, which helped identify the cause of the issue.

**Comment by pqarmitage** [comment]
amd64, i386, ppc64 and s390x stable snaps have been updated, arm snaps are currently building.

**Comment by acassen** [comment]
my bad :/ going to push a new 2.1.1 minute release

**Comment by pqarmitage** [comment]
All snaps now pushed to stable.

**Comment by acassen** [comment]
We definitely/terribly need to request to the community for getting a box to run our regressions test env on it...

**Comment by braninl** [comment]
Thank you!   I can confirm that the email issue was causing my segfaults previously and updating to the latest snap has fixed the issue.
