### ISSUE TITLE
 keepalived running too long，which lead to print “scheduler：epoll_wait error ：invalid argument”

### ISSUE THREAD

**Issue by zhouxudong199** [acassen/keepalived#1631]
**Describe the bug**

 keepalived running too long，which lead to print “scheduler：epoll_wait error ：invalid argument”

**To Reproduce**

add same vs or rs to keepalived.conf 
systemctl start keepalived 
wait some time。

gdb att checker process.
watch master-> epoll_count

**Expected behavior**
when keepalived.conf is not changed, the  epoll_count is not  increased。
under a lot of checkers, donot print  "scheduler：epoll_wait error ：invalid argument" （because epoll_count is reversed）

**Keepalived version**
keepalived 2.0.20

**Additional context**

**Comment by zhouxudong199** [comment]
sloved by https://github.com/acassen/keepalived/pull/1632

**Comment by pqarmitage** [comment]
@zhouxudong199 You patch is now merged - many thanks for your help.
