### ISSUE TITLE
when persistence_timeout is set large value, vs cannot up

### ISSUE THREAD

**Issue by zhouxudong199** [acassen/keepalived#1641]
**Describe the bug**
when persistence_timeout is set a large value , as 4294967295.
vs is not up, and /var/log/message print : 
error IPVS cmd IP_VS_SO_SET_ADD(1154) error: Invalid operation.

**To Reproduce**
1.persistence_timeout is set a large value , as 4294967295.
2.start keepalived.service
3.ipvsadm -ln.  vs not up。

**Expected behavior**
cat /var/log/message, can find keepalived give reason.

**Keepalived version**
keepalived 2.0.20

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
 persistence_timeout 4294967295

**System Log entries**
Jun 20 16:55:18 localhost audit: PROCTITLE proctitle=2F7573722F7362696E2F6B656570616C69766564002D44002D2D616C6C
Jun 20 16:55:18 localhost Keepalived[1481891]: Starting VRRP child process, pid=1481893
Jun 20 16:55:18 localhost Keepalived_vrrp[1481893]: Registering Kernel netlink reflector
Jun 20 16:55:18 localhost Keepalived_vrrp[1481893]: Registering Kernel netlink command channel
Jun 20 16:55:18 localhost keepalived-start-post.sh[1481894]: exec started post
Jun 20 16:55:18 localhost systemd[1]: Started LVS and VRRP High Availability Monitor.
Jun 20 16:55:18 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=keepalived comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 20 16:55:18 localhost [/bin/bash]: [systemctl restart keepalived.service] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.4.91.54)]
Jun 20 16:55:18 localhost Keepalived_healthcheckers[1481892]: Registering Kernel netlink command channel
Jun 20 16:55:18 localhost Keepalived_healthcheckers[1481892]: IPVS cmd IP_VS_SO_SET_ADD(1154) error: Invalid operation.  Possibly wrong module version, address not unicast, ...(22)
Jun 20 16:55:18 localhost Keepalived_healthcheckers[1481892]: IPVS cmd (unknown)(1168) error: No such file or directory(2)
Jun 20 16:55:18 localhost Keepalived_healthcheckers[1481892]: IPVS cmd IP_VS_SO_SET_ADDDEST(1159) error: No such file or directory(2)
Jun 20 16:55:18 localhost Keepalived_healthcheckers[1481892]: Gained quorum 1+0=1 <= 1 for VS [22.22.48.42]:tcp:22
Jun 20 16:55:18 localhost Keepalived_healthcheckers[1481892]: Gained quorum 1+0=1 <= 1 for VS [22.22.48.42]:tcp:80
Jun 20 16:55:18 localhost Keepalived_healthcheckers[1481892]: Gained quorum 1+0=1 <= 1 for VS [22.22.48.42]:tcp:443
Jun 20 16:55:18 localhost Keepalived_healthcheckers[1481892]: Gained quorum 1+0=1 <= 1 for VS [22.22.48.42]:tcp:21
Jun 20 16:55:18 localhost Keepalived_healthcheckers[1481892]: Gained quorum 1+0=1 <= 1 for VS [22.22.48.42]:tcp:40000
Jun 20 16:55:18 localhost Keepalived_healthcheckers[1481892]: Gained quorum 1+0=1 <= 1 for VS [22.22.48.42]:tcp:25
Jun 20 16:55:18 localhost Keepalived_healthcheckers[1481892]: Gained quorum 1+0=1 <= 1 for VS [22.22.48.42]:udp:5001

**Comment by zhouxudong199** [comment]
cause: ip_vs_service_user timeout  is unsigned. but ipvs donot allow it >(UINT_MAX / HZ).
ipvsadm whose authors is Wensong Zhang，which set range is MAX_TIMEOUT(31 days). this value is same as keepalived LVS_MAX_TIMEOUT.

solved by https://github.com/acassen/keepalived/pull/1640. wait authority to verify.

**Comment by pqarmitage** [comment]
@zhouxudong199 Many thanks for the patch. Now merged.
