### ISSUE TITLE
Question about smooth migration from multicast to unicast

### ISSUE THREAD

**Issue by yboaron** [acassen/keepalived#1643]
Hello all,

I have 3 servers that run Keepalived to manage a VIP (192.168.111.5) and VRRP packets sent in multicast mode,[1] is the relevant conf file.

Due to planned changes in the network (block multicast traffic),  Keepalived should migrate to unicast.
I need to migrate (one by one) the 3 servers from Keepalived multicast to unicast and keep the VIP available also during the migration.

Updating the servers conf file to support unicast [2] causes conflict during the migration which will cause the VIP to be defined in two servers.

Is there any configuration/script/other trick under Keepalived 'umbrella' that can be useful in such a case or this kind of problem should be solved outside of Keepalived scope? 

Thanks in advance
Yossi

[1] multicast config:

vrrp_script chk_api { 
   script "/usr/bin/curl -o /dev/null -kLs http://localhost:1936/healthz" 
   interval 1 
   weight 50 
} 
vrrp_instance ostest_API { 
   state BACKUP 
   interface enp2s0 
   virtual_router_id 14 
   priority 40 
   advert_int 1 
 
   authentication { 
       auth_type PASS 
       auth_pass ostest_api_vip 
   } 
   virtual_ipaddress { 
       192.168.111.5/24 
   } 
   track_script { 
       chk_api 
   } 
}
 
[2] unicast config:

vrrp_script chk_api { 
   script "/usr/bin/curl -o /dev/null -kLs http://localhost:1936/healthz" 
   interval 1 
   weight 50 
} 
 
 
 
vrrp_instance ostest_API { 
   state BACKUP 
   interface enp2s0 
   virtual_router_id 14 
   priority 40 
   advert_int 1 
 
   unicast_src_ip 192.168.111.21 
   unicast_peer { 
       192.168.111.20 
       192.168.111.22 
   } 
 
   authentication { 
       auth_type PASS 
       auth_pass ostest_api_vip 
   } 
   virtual_ipaddress { 
       192.168.111.5/24 
   } 
   track_script { 
       chk_api
   } 
}

**Comment by pqarmitage** [comment]
You cannot migrate the servers one by one from multicast to unicast. Multicast and unicast are separate domains and will not interoperate.

The only way you can migrate from multicast to unicast is to reload the configurations on all three keepalived instances simultaneously, although I think even then you will have an interval  3of * advert interval + a bit when no instance is master.

keepalived v2.1.2 supports a new feature `reload_time_file` which allows multiple keepalived instances to all reload simultaneously (assuming the system clocks a synchronized). I think this is the best option for you, making all keepalived instances move from multicast to unicast simultaneously.
