### ISSUE TITLE
When set lvs_sync_daemon ttl port maxlen 0, no info or error,but 0 is not effective

### ISSUE THREAD

**Issue by zhouxudong199** [acassen/keepalived#1646]
**Describe the bug**
When set lvs_sync_daemon ttl port maxlen 0, no info or error,but 0 is not effective

**To Reproduce**
 set lvs_sync_daemon ttl port maxlen 0 in keepalived.conf

**Expected behavior**
tell me why not effective or actual value

**Keepalived version**
keepalived 2.0.20

details and analysis
1、keepalived manpage：https://www.keepalived.org/manpage.html
           #  maxlen (1..65507) maximum packet length (limit is mtu - 20 - 8)
           #  port (1..65535) UDP port number to use, default 8848
           #  ttl (1..255)
2、keepalived code：
if (!read_unsigned_strvec(strvec, i + 1, &val, 0, 65535 - 20 - 8, false))
     report_config_error(CONFIG_GENERAL_ERROR, "Invalid lvs_sync_daemon maxlen (%s) - ignoring", strvec_slot(strvec, i+1));  
if (!read_unsigned_strvec(strvec, i + 1, &val, 0, 65535, false))
  report_config_error(CONFIG_GENERAL_ERROR, "Invalid lvs_sync_daemon port (%s) - ignoring", strvec_slot(strvec, i+1));
if (!read_unsigned_strvec(strvec, i + 1, &val, 0, 255, false))
  report_config_error(CONFIG_GENERAL_ERROR, "Invalid lvs_sync_daemon ttl (%s) - ignoring", strvec_slot(strvec, i+1));

Above, are different .
meanwhile 
3、ipvs code （4.19.90）
if (c->sync_maxlen)
  xxx
else
 c->sync_maxlen = mtu - hlen;

if (!c->mcast_port)
	c->mcast_port = IP_VS_SYNC_PORT; // 8848
if (!c->mcast_ttl)
	c->mcast_ttl = 1;

so if set 0.
port is 8848; ttl is 1; maxlen is mtu - hlen;

4、use ipvsadm to configurate. 

set_option(options, OPTC_SYNC_MAXLEN);
parse = string_to_number(optarg, 1, 65535 - 20 - 8);

set_option(options, OPTC_MCAST_TTL);
parse = string_to_number(optarg, 1, 255);

set_option(options, OPTC_MCAST_PORT);
parse = string_to_number(optarg, 1, 65535);

those range is same as keepalived manpage.

**Comment by zhouxudong199** [comment]
PR is marged .closed

**Comment by pqarmitage** [comment]
@zhouxudong199 Many thanks for these patches, which I have now merged.

By the way, don't always assume that the ipvsadm code is correct. There are some instances of the ranges allowed by ipvsadm being either too large or too small (I have some patches for these that I need to submit for ipvsadm). The best place to check permissible values is the kernel code.

**Comment by zhouxudong199** [comment]
Thanks,  about your suggestions , I can't agree more.

Usually , I  check  those values by ipvs code firstly , like my commit logs showing.
Due to lack of my capable as same as my poor English. when I have some doubt, I will refer ipvsadm.

As you said , I will do more check from kernel  instead of  ipvsadm.
Thanks your valuable advices. I will keep it in mind.
发件人: Quentin Armitage [mailto:notifications@github.com]
发送时间: 2020年6月23日 17:18
收件人: acassen/keepalived <keepalived@noreply.github.com>
抄送: Zhouxudong (EulerOS) <zhouxudong8@huawei.com>; Mention <mention@noreply.github.com>
主题: Re: [acassen/keepalived] When set lvs_sync_daemon ttl port maxlen 0, no info or error,but 0 is not effective (#1646)


@zhouxudong199<https://github.com/zhouxudong199> Many thanks for these patches, which I have now merged.

By the way, don't always assume that the ipvsadm code is correct. There are some instances of the ranges allowed by ipvsadm being either too large or too small (I have some patches for these that I need to submit for ipvsadm). The best place to check permissible values is the kernel code.
