### ISSUE TITLE
keepalived segfault using track_process in vrrp_instance

### ISSUE THREAD

**Issue by szahri** [acassen/keepalived#1647]
Hi there,
I have the same problem as described by #1150  on Redhat Linux Server 7.8 (Maipo) with 3.10.0-1127-19.1.el7.x86_64 kernel.
I used the exact same config as the poster in the #1150  just to ensure I received the same error and I did.

Log below :
`2020-06-23T11:01:09.072862+00:00 testserver Keepalived[60605]: Starting VRRP child process, pid=60668 2020-06-23T11:01:09.073183+00:00 testserver Keepalived_vrrp[60668]: Registering Kernel netlink reflector 2020-06-23T11:01:09.073438+00:00 testserver Keepalived_vrrp[60668]: Registering Kernel netlink command channel 2020-06-23T11:01:09.074092+00:00 testserver Keepalived_vrrp[60668]: Opening file '/etc/keepalived/keepalived.conf'. 2020-06-23T11:01:09.074393+00:00 testserver Keepalived_vrrp[60668]: (Line 31) (VI_1) track process check_haproxy not found, ignoring... 2020-06-23T11:01:09.074699+00:00 testserver Keepalived_vrrp[60668]: Assigned address 10.10.20.206 for interface eth0 2020-06-23T11:01:09.074995+00:00 testserver Keepalived_vrrp[60668]: Assigned address fe80::21d:d8ff:feb7:1f49 for interface eth0 2020-06-23T11:01:09.076648+00:00 testserver kernel: keepalived[60668]: segfault at ffffffffffffffe8 ip 000056003819f4c9 sp 00007ffe7f20d550 error 5 in keepalived[560038162000+7f000] 2020-06-23T11:01:09.076975+00:00 testserver Keepalived[60605]: pid 60668 exited due to segmentation fault (SIGSEGV). 2020-06-23T11:01:09.077239+00:00 testserver Keepalived[60605]: Please report a bug at https://github.com/acassen/keepalived/issues 2020-06-23T11:01:09.077476+00:00 testserver Keepalived[60605]: and include this log from when keepalived started, a description 2020-06-23T11:01:09.077826+00:00 testserver Keepalived[60605]: of what happened before the crash, your configuration file and the details below. 2020-06-23T11:01:09.078111+00:00 testserver Keepalived[60605]: Also provide the output of keepalived -v, what Linux distro and version 2020-06-23T11:01:09.078348+00:00 testserver Keepalived[60605]: you are running on, and whether keepalived is being run in a container or VM. 2020-06-23T11:01:09.078625+00:00 testserver Keepalived[60605]: A failure to provide all this information may mean the crash cannot be investigated. 2020-06-23T11:01:09.078859+00:00 testserver Keepalived[60605]: If you are able to provide a stack backtrace with gdb that would really help. 2020-06-23T11:01:09.079085+00:00 testserver Keepalived[60605]: Source version 2.1.2 2020-06-23T11:01:09.079313+00:00 testserver Keepalived[60605]: Built with kernel headers for Linux 3.10.0 2020-06-23T11:01:09.079537+00:00 testserver Keepalived[60605]: Running on Linux 3.10.0-1127.el7.x86_64 #1 SMP Tue Feb 18 16:39:12 EST 2020 2020-06-23T11:01:09.079780+00:00 testserver Keepalived[60605]: Command line: '/usr/sbin/keepalived' '-D' 2020-06-23T11:01:09.080006+00:00 testserver Keepalived[60605]: configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= 2020-06-23T11:01:09.080229+00:00 testserver Keepalived[60605]: --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin
`

I'm using the latest stable code 2.1.2.

Result of ` keepalived -v`:
```

[root]# keepalived -v
Keepalived v2.1.2 (06/14,2020)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-1127.el7.x86_64 #1 SMP Tue Feb 18 16:39:12 EST 2020

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-nftables --disable-iptables --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic LDFLAGS=-Wl,-z,relro

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV6_ADVANCED_API RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTA_VIA FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION VRRP_VMAC IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RESET_ON_FORK

```

My keepalived.conf:

```
global_defs {
   notification_email_from myadmin@myserver
   smtp_server localhost
   smtp_connect_timeout 30
   router_id LVS_DEVEL
}

vrrp_track_process check_nginx {
  process   "nginx"
  weight    10
  quorum    1
  delay     2000
}

vrrp_instance VI_1 {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        10.10.20.208
    }
    track_process {
       check_haproxy
  }
}
```

**Comment by acassen** [comment]
please provide your keepalived.conf

**Comment by pqarmitage** [comment]
@szahri I think you will find commit 9907087, which I merged yesterday, resolves your problem.

It's good to be ahead of the game! :)

**Comment by acassen** [comment]
we need to push a new 2.1.3

**Comment by szahri** [comment]
That would be most appreciated if you can push to a new 2.1.3.
I will then confirm if that fixes my issue?

**Comment by pqarmitage** [comment]
@szahri Version 2.1.3 has now been pushed.

**Comment by pqarmitage** [comment]
Closing due to no response for over 1 week. If you are still experiencing the problem, please update this issue and we can reopen it.
