### ISSUE TITLE
after transition the Master ,few seconds not send the vrrp packets

### ISSUE THREAD

**Issue by senthilnathann** [acassen/keepalived#1653]
**Describe the issue**
We are trying to swap the Master/Backup using to restart the keepalived in Master.
Backup took over as master ,after take over first VRRP packet sent ,then take few seconds ( 3-4 seconds )to send next VRRP packet.Due to this issue  Master again back to Master . So we are not able to swap the Master/Backup.

We have configured 80 + virtual ips in this keepalived cluster. 

How much time take to process the VRRP packets ?

How many virtual ip address are able to configure in keepalived ?

**To Reproduce**
Pls restart the keepalived with more vip configs

**Expected behavior**
Every second keepalived need to send vrrp packets

**Keepalived version**
Output of `keepalived -v`
Keepalived v2.0.7 (08/23,2018)
**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu]
 - Version [e.g. 29]
 - Architecture [e.g. x86_64]

CentOS 7

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
A full copy of the configuration file, obfuscated if necessary to protect passwords and IP addresses

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started

**Did keepalived coredump?**
If so, can you please provide a stacktrace from the coredump, using gdb.

**Additional context**

**Comment by pqarmitage** [comment]
There should be no problem with have 80 + VIPs with IPv4, although the practical limit with IPv6 is about 90, depending on the interface MTU. The time to process a VRRP packet should be a small number of microseconds.

In order to allow us to investigate the problem further, can you please provide the following information:

1. Full output of `keepalived -v`

2. Copies of your keepalived configuration files

**Comment by pqarmitage** [comment]
Please also provide the  system logs over the time period of the problem occurring.

**Comment by pqarmitage** [comment]
Closing due to no response for over 1 week. If you are still experiencing the issue, please update this issue report with the information requested above and we can reopen this case.
