### ISSUE TITLE
Error in documentation of strict_mode

### ISSUE THREAD

**Issue by wodry** [acassen/keepalived#1656]
**Describe the bug**
In https://github.com/acassen/keepalived/blob/master/doc/man/man5/keepalived.conf.5
in line 1654 is written:

> If vrrp_strict is not specified, it takes the value of vrrp_strict

This sentence does not make sense.

**To Reproduce**
Read the sentence.

**Expected behavior**
Reading a sentence that makes sense.

**Comment by pqarmitage** [comment]
Commit 09aa833 when merge will resolve this.
