### ISSUE TITLE
After recovering from multi-master / split-brain, no new ARPs are sent

### ISSUE THREAD

**Issue by boudekerk** [acassen/keepalived#166]
Hi,

we've succesfully been using Keepalived for a while now, but recently have had an issue where it didn't properly recover from a split-brain scenario. Let me explain. During the snapshotting of a VM which was MASTER at the time (let's call it node1), our BACKUP node (node2) became MASTER, we assume because node1 was momentarily unreachable (that's a separate issue). Now, while it was transitioning node2 received a higher prio advert (according to the logs, they have equal priority configured) from node1 and fell back to BACKUP STATE. So far so good.

Now the issue is, that by this time node2 had already sent out ARPs for the VIPs, since node1 never changed state during all of this, it didn't send any. The result was that our VIPs had become unreachable.

See here the logs from node2, node1 didn't log anything.
Jun 23 13:41:16 web1 Keepalived_vrrp[3021]: VRRP_Instance(VI_1) Transition to MASTER STATE
Jun 23 13:41:16 web1 Keepalived_vrrp[3021]: VRRP_Instance(VI_1) Entering MASTER STATE
Jun 23 13:41:16 web1 Keepalived_vrrp[3021]: VRRP_Instance(VI_1) setting protocol VIPs.
Jun 23 13:41:16 web1 Keepalived_vrrp[3021]: VRRP_Instance(VI_1) Sending gratuitous ARPs on eth0 for 1.2.3.4
Jun 23 13:41:16 web1 Keepalived_vrrp[3021]: VRRP_Instance(VI_1) Sending gratuitous ARPs on eth0 for 5.6.7.8
Jun 23 13:41:16 web1 Keepalived_healthcheckers[3020]: Netlink reflector reports IP 1.2.3.4 added
Jun 23 13:41:16 web1 Keepalived_vrrp[3021]: Remote SMTP server [127.0.0.1]:25 connected.
Jun 23 13:41:16 web1 Keepalived_vrrp[3021]: VRRP_Instance(VI_1) Received higher prio advert
Jun 23 13:41:16 web1 Keepalived_vrrp[3021]: VRRP_Instance(VI_1) Entering BACKUP STATE
Jun 23 13:41:16 web1 Keepalived_vrrp[3021]: VRRP_Instance(VI_1) removing protocol VIPs.
Jun 23 13:41:16 web1 Keepalived_vrrp[3021]: Remote SMTP server [127.0.0.1]:25 connected.
Jun 23 13:41:16 web1 Keepalived_healthcheckers[3020]: Netlink reflector reports IP 5.6.7.8 added
Jun 23 13:41:16 web1 Keepalived_healthcheckers[3020]: Netlink reflector reports IP 1.2.3.4 removed
Jun 23 13:41:16 web1 Keepalived_healthcheckers[3020]: Netlink reflector reports IP 5.6.7.8 removed

I assume this is a bug? If so, shouldn't in a split brain situation either the node having become MASTER last keep its state or whichever node is MASTER after any such resolution send out ARPs? Or perhaps there's a better solution?

I hope the above is clear, if not we'll be happy to elaborate.

Kind regards,
Bartosz

**Comment by acassen** [comment]
For such an issue you should consider having a look at following vrrp_instance keywords

garp_master_refresh <sec>
  => Will periodically send gratuitous ARP every <sec> while in MASTER state

garp_master_repeat <nb>
  => While becoming MASTER sending gratuitous ARP, send <nb> time each gratuitous ARP

garp_master_refresh_repeat <nb>
  => While in MASTER state and garp_master_refresh timer fired, send <nb>
       time each gratuitous ARP

in some really wired issues this will just the everything on it foots

regs,
