### ISSUE TITLE
check_misc: delay_before_retry does not default to delay_loop

### ISSUE THREAD

**Issue by wodry** [acassen/keepalived#1665]
**Describe the bug**
When a real server misc_check fails it is retried after 1 second and not after 10 seconds, which is the value of delay_loop.

**To Reproduce**
Set up following virtual/real server:
```
virtual_server 10.7.2.26 53 {
    lb_algo wlc
    lvs_method DR
    protocol TCP
    delay_loop 10
    retry 3

    real_server 10.7.2.222 53 {
        weight 10
        MISC_CHECK {
            misc_path "/usr/bin/dig -4 +tcp +short +time=3 +tries=3 @10.7.2.222 example.com"
            misc_timeout 10
        }
    }
}
```
Stop the DNS-Server at 10.7.2.222:53

The real server transitions to DOWN after 3 (three) seconds, since every retry check happens after 1 s. See log:
```
Jun 28 11:48:41 hostname Keepalived_healthcheckers[20498]: Misc check for [[10.7.2.222]:tcp:53 VS [10.7.2.26]:tcp:53] by [/usr/bin/dig] failed after 3 retries (exited with status 9).
Jun 28 11:48:42 hostname Keepalived_healthcheckers[20498]: Misc check for [[10.7.2.222]:tcp:53 VS [10.7.2.26]:tcp:53] by [/usr/bin/dig] failed after 3 retries (exited with status 9).
Jun 28 11:48:43 hostname Keepalived_healthcheckers[20498]: Misc check for [[10.7.2.222]:tcp:53 VS [10.7.2.26]:tcp:53] by [/usr/bin/dig] failed after 3 retries (exited with status 9).
Jun 28 11:48:44 hostname Keepalived_healthcheckers[20498]: Misc check for [[10.7.2.222]:tcp:53 VS [10.7.2.26]:tcp:53] by [/usr/bin/dig] failed after 3 retries (exited with status 9).
Jun 28 11:48:44 hostname Keepalived_healthcheckers[20498]: Removing service [10.7.2.222]:tcp:53 to VS [10.7.2.26]:tcp:53
```
**Expected behavior**
After initial check failure, every retry check occurs after `delay_loop` (in this example 10) seconds.
This is behavior known e.g. from Nagios. E.g. if the above service would not be available for 5 seconds, it should _not_ be removed from the balancer, since the first retry check (after 10 s) would already succeed again.

**Keepalived version**
2.0.20

**Distro (please complete the following information):**
Keepalived compiled on Ubuntu 18.04.1 x86_64

**Comment by wodry** [comment]
My fault, I forogt to set `delay_before_retry` to 10. With that set, it works as expected.

**Comment by wodry** [comment]
According to https://github.com/acassen/keepalived/blob/v2.0.20/keepalived/check/check_data.c#L1104
`delay_before_retry` should default to the value of `delay_loop` in 2.0.20
```
			if (checker->delay_before_retry == ULONG_MAX) {
				checker->delay_before_retry =
					checker->rs->delay_before_retry != ULONG_MAX ?
						checker->rs->delay_before_retry :
					checker->default_delay_before_retry ?
						checker->default_delay_before_retry :
						checker->delay_loop;
			}
```
So the misc_check behavior stated in my OP should be wrong, there should be a bug.

**Comment by pqarmitage** [comment]
@wodry, yes this is all rather confusing, and certainly the description in keepalived.conf(5) man page is not correct.

It would not be right to alter default behaviour now, which users will be relying upon, and so I am updating the keepalived.conf(5) man page so it says:
```
    # delay before retry after failure. Defaults to delay_loop for DNS_CHECK,
    # 3 seconds for HTTP_CHECK and SSL_CHECK, and 1 second otherwise.
```

This will be commit cc4494f once I have merged it.
