### ISSUE TITLE
keepalived reports: "No VIP" in case all VIPs are in included files

### ISSUE THREAD

**Issue by 3hedgehogs** [acassen/keepalived#1670]
**Describe the bug**
If all VIPs are only defined in included files keepalived process warns: "No VIP specified; at least one is sensible"
After defined vmac interface is UP everything is working as expected and VIPs are up too. 

**To Reproduce**
No any VIPs in main keepalived.conf only in included files:
example line in keepalived.conf: 

..
vrrp_instance VI_EXT_NAME {
include external_first_master.inc
...

external_first_master.inc:
virtual_ipaddress {
  XX.XX.XX.XX/21 dev vrrp_ext_1
}

**Expected behavior**
No warnings

**Keepalived version**
snap revision 1418,  v2.1.3 (06/25,2020), git commit v2.1.3-8-g37054e6

**Comment by pqarmitage** [comment]
I have tried this and I think the following messages are relevant:
```
Tue Jun 30 14:48:30 2020: (Line 1) Unknown keyword '10.2.0.100/32'
Tue Jun 30 14:48:30 2020: (Line 2) Unknown keyword '10.2.0.101/32'
Tue Jun 30 14:48:30 2020: (Line 3) Unknown keyword '10.1.0.24/32'
```

I'll have look at this further.

**Comment by pqarmitage** [comment]
Commit 3fc6126 resolves this issue; many thanks for reporting it.

I had thought this would be a straightforward fix, but it turned out that the changes needed were somewhat more substantial than I had anticipated; nevertheless, I think the structure of the code is cleaner now.
