### ISSUE TITLE
dns checker will never print  "after n retries"

### ISSUE THREAD

**Issue by wangxp006** [acassen/keepalived#1671]
**Describe the bug**
dns checker will never printf  after n retries

**To Reproduce**
1.  shutdown real server interface
2.  check  fail log in /var/log/message

[root@openEuler ~]# grep  22.22.1.88  /var/log/messages | grep 53 | grep -v grep
Jun 30 16:28:44 openEuler Keepalived_healthcheckers[49862]: DNS_CHECK ([22.22.1.88]:udp:53) read timeout from socket
Jun 30 16:28:51 openEuler Keepalived_healthcheckers[49862]: DNS_CHECK ([22.22.1.88]:udp:53) read timeout from socket
Jun 30 16:28:58 openEuler Keepalived_healthcheckers[49862]: DNS_CHECK ([22.22.1.88]:udp:53) read timeout from socket
Jun 30 16:29:05 openEuler Keepalived_healthcheckers[49862]: DNS_CHECK ([22.22.1.88]:udp:53) read timeout from socket
Jun 30 16:29:05 openEuler Keepalived_healthcheckers[49862]: Removing service [22.22.1.88]:udp:53 to VS [22.22.72.35]:udp:53

**Expected behavior**
Jun 30 19:30:43 openEuler Keepalived_healthcheckers[50925]: DNS_CHECK ([22.22.1.88]:udp:53) read timeout from socket
Jun 30 19:30:50 openEuler Keepalived_healthcheckers[50925]: DNS_CHECK ([22.22.1.88]:udp:53) read timeout from socket
Jun 30 19:30:57 openEuler Keepalived_healthcheckers[50925]: DNS_CHECK ([22.22.1.88]:udp:53) read timeout from socket
Jun 30 19:31:04 openEuler Keepalived_healthcheckers[50925]: DNS_CHECK ([22.22.1.88]:udp:53) read timeout from socket **after 3 retries**
Jun 30 19:31:04 openEuler Keepalived_healthcheckers[50925]: Removing service [22.22.1.88]:udp:53 to VS [22.22.72.35]:udp:53

**Keepalived version**
keepalived 2.0.20

**Configuration file:**
 ```
virtual_server 22.22.72.35 53 {
    delay_loop 6
    lb_algo rr
    lb_kind DR
    protocol UDP
    #alpha
    hysteresis 0
    quorum 1
    quorum_up "/usr/sbin/ip addr add 22.22.72.35 dev lo"

    real_server 22.22.1.88 53 {
        weight 2
        DNS_CHECK {
            connect_port 53
            connect_timeout 1
            retry 3
            type A
            name lvs-test.com
            bindto 22.22.102.249
        }
    }
}
```

**Comment by wangxp006** [comment]
PR is here #1672

**Comment by pqarmitage** [comment]
What a wonderful bit of code it was
`if (checker->has_run && ... && !checker->has_run)`
I am surprised that Coverity didn'y pick it up.

Many thanks for the patch and I will merge it when I next do some merging.

**Comment by wangxp006** [comment]
My PR is here #1672 ，you can check whether the modification is ok。

**Comment by pqarmitage** [comment]
@wangxp006 Your PR is now merged; many thanks for your help.
