### ISSUE TITLE
failure of udp checker caused leakage of fd

### ISSUE THREAD

**Issue by wangxp006** [acassen/keepalived#1673]
**Describe the bug**
failure of udp checker caused leakage of fd

**To Reproduce**
1. startup keepalived with udp checker confgration
2. shutdown the interface linked to real server 
3. check the fd in /proc/${checker_pid}/fd
 **Before shutdown**
[root@openEuler fd]# cd /proc/56081/fd
[root@openEuler fd]# ls
0  1  2  3  4  5  6  7
**After few minutes**
[root@openEuler fd]# cd /proc/56081/fd
[root@openEuler fd]# ls
0    105  112  12   127  134  141  149  156  163  170  178  185  192  2    206  213  220  228  235  242  25   257  264  271  279  286  293  30   307  38  45  52  6   67  74  81  89  96
1    106  113  120  128  135  142  15   157  164  171  179  186  193  20   207  214  221  229  236  243  250  258  265  272  28   287  294  300  31   39  46  53  60  68  75  82  9   97
10   107  114  121  129  136  143  150  158  165  172  18   187  194  200  208  215  222  23   237  244  251  259  266  273  280  288  295  301  32   4   47  54  61  69  76  83  90  98
100  108  115  122  13   137  144  151  159  166  173  180  188  195  201  209  216  223  230  238  245  252  26   267  274  281  289  296  302  33   40  48  55  62  7   77  84  91  99
101  109  116  123  130  138  145  152  16   167  174  181  189  196  202  21   217  224  231  239  246  253  260  268  275  282  29   297  303  34   41  49  56  63  70  78  85  92
102  11   117  124  131  139  146  153  160  168  175  182  19   197  203  210  218  225  232  24   247  254  261  269  276  283  290  298  304  35   42  5   57  64  71  79  86  93
103  110  118  125  132  14   147  154  161  169  176  183  190  198  204  211  219  226  233  240  248  255  262  27   277  284  291  299  305  36   43  50  58  65  72  8   87  94
104  111  119  126  133  140  148  155  162  17   177  184  191  199  205  212  22   227  234  241  249  256  263  270  278  285  292  3    306  37   44  51  59  66  73  80  88  95

**Expected behavior**
Checker's fd number remains stable

**Keepalived version**
keepalived-2.0.20

**Configuration file:**
```
virtual_server 22.22.94.33 53 {
    delay_loop 6
    lb_algo rr
    lb_kind DR
    protocol UDP
    alpha
    hysteresis 0
    quorum 1
    quorum_up "/usr/sbin/ip addr add 22.22.94.33 dev lo"
        
    real_server 22.22.103.237 53 {
        weight 1
        UDP_CHECK {
            connect_port 53
            connect_timeout 1
            retry 1
            delay_before_retry 1
            bindto 22.22.116.103
            require_reply
        }
    }

}
```

**Comment by wangxp006** [comment]
PR is here #1674

**Comment by pqarmitage** [comment]
Your PR is now merged; many thanks for your help.
