### ISSUE TITLE
tcp checker and dns checker will not go offline when interface link to RS is down

### ISSUE THREAD

**Issue by wangxp006** [acassen/keepalived#1679]
**Describe the bug**
tcp checker and dns checker will not go offline when interface link to RS is down

**To Reproduce**
1. startup keepalived
2. delete ip address of the interface linked to RS
TCP  and DNS checker will not go offline 
[root@openEuler keepalived]# ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  22.22.94.33:5001 rr
  -> 22.22.103.237:5001           Route   1      0          0         
UDP  22.22.94.33:53 rr
  -> 22.22.98.217:53              Route   2      0          0   

**Expected behavior**
[root@openEuler keepalived]# ipvsadm -Ln                            
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  22.22.94.33:5001 rr
UDP  22.22.94.33:53 rr

**Keepalived version**
keepalived-2.0.20

**Configuration file:**
```
global_defs {
        checker_log_all_failures on
 }


virtual_server 22.22.94.33 53 {
    delay_loop 6
    lb_algo rr
    lb_kind DR
    protocol UDP
    alpha
    hysteresis 0
    quorum 1
    quorum_up "/usr/sbin/ip addr add 22.22.94.33 dev lo"

    real_server 22.22.98.217 53 {
        weight 2
        DNS_CHECK {
            connect_port 53
            connect_timeout 1
            retry 1
            type A
            name lvs-test.com
            bindto 22.22.116.103
        }
    }
}

virtual_server 22.22.94.33 5001 {
    delay_loop 6
    lb_algo rr
    lb_kind DR
    protocol TCP
    alpha
    hysteresis 0
    quorum 1
    quorum_up "/usr/sbin/ip addr add 22.22.94.33 dev lo"

    real_server 22.22.103.237 5001 {
        weight 1
        TCP_CHECK {
            connect_port 22
            connect_timeout 10
            retry 3
            delay_before_retry 3
            bindto 22.22.116.103
        }
    }

}
```

**System Log entries**
[root@openEuler keepalived]# grep "22.22.98.217" /var/log/messages 
Jul  2 15:43:32 openEuler Keepalived_healthcheckers[62465]: DNS_CHECK ([22.22.98.217]:udp:53) UDP socket bind failed. Rescheduling.
Jul  2 15:43:38 openEuler Keepalived_healthcheckers[62465]: DNS_CHECK ([22.22.98.217]:udp:53) UDP socket bind failed. Rescheduling.
Jul  2 15:43:44 openEuler Keepalived_healthcheckers[62465]: DNS_CHECK ([22.22.98.217]:udp:53) UDP socket bind failed. Rescheduling.
[root@openEuler keepalived]# grep "22.22.103.237" /var/log/messages             
[root@openEuler keepalived]# grep "UDP socket bind failed. Rescheduling"  /var/log/messages 
Jul  2 15:43:32 openEuler Keepalived_healthcheckers[62465]: DNS_CHECK ([22.22.98.217]:udp:53) UDP socket bind failed. Rescheduling.
Jul  2 15:43:38 openEuler Keepalived_healthcheckers[62465]: DNS_CHECK ([22.22.98.217]:udp:53) UDP socket bind failed. Rescheduling.
Jul  2 15:43:44 openEuler Keepalived_healthcheckers[62465]: DNS_CHECK ([22.22.98.217]:udp:53) UDP socket bind failed. Rescheduling.
Jul  2 15:43:50 openEuler Keepalived_healthcheckers[62465]: DNS_CHECK ([22.22.98.217]:udp:53) UDP socket bind failed. Rescheduling.

**Comment by wangxp006** [comment]
My PR is Here #1680 。

**Comment by pqarmitage** [comment]
Please see comments against PR #1680. The current behaviour is the correct behaviour by design; additional configuration options need to be added for what you are wanting to achieve.
