### ISSUE TITLE
keepalived master proccess exits when USR1 is received

### ISSUE THREAD

**Issue by thresheek** [acassen/keepalived#169]
I'm trying to test out the vrrp data/stats dump feature and ran into the following problem:

on console 1:
host # LC_ALL=C keepalived -n -l -D
Starting VRRP child process, pid=21187
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Opening file '/etc/keepalived/keepalived.conf'.
Truncating auth_pass to 8 characters
Configuration is using : 64461 Bytes
Using LinkWatch kernel netlink reflector...
VRRP_Instance(VI_1) Entering BACKUP STATE
VRRP sockpool: [ifindex(2), proto(112), unicast(1), fd(10,11)]
VRRP_Instance(VI_1) Transition to MASTER STATE
VRRP_Instance(VI_1) Entering MASTER STATE
VRRP_Instance(VI_1) setting protocol VIPs.
VRRP_Instance(VI_1) Sending gratuitous ARPs on eth0 for 127.0.0.34
...

On console 2:
host # cat /var/run/keepalived.pid
21186
host # kill -USR1 21186

Then on console 1 the following message is received and the master process exits:

User defined signal 1

leaving the child running

host # ps ax | grep -i keep
21187 pts/1    S      0:00 keepalived -n -l -D

I understand that I should really send USR1 signal to the child proccess, but there is no way to find its PID to send the signal to - which is a separate issue.

**Comment by pq17** [comment]
Resolved in commit 63126b2

**Comment by pqarmitage** [comment]
Resolved in commit 63126b2
