### ISSUE TITLE
Build failed for 2.1.5 version

### ISSUE THREAD

**Issue by juanvasquezreyes** [acassen/keepalived#1698]
I was testing keepalived version keepalived-2.0.20 and it has been working fine, but I tried to install the latest version and I'm facing this issue

../../keepalived/include/namespaces.h:42:49: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
  CC       keepalived_netlink.o
  CC       namespaces.o
In file included from /usr/include/netlink/handlers.h:19:0,
                 from /usr/include/netlink/socket.h:16,
                 from namespaces.c:171:
/usr/include/netlink/netlink-kernel.h:193:2: error: unknown type name '__u32'
  __u32 group;

I just ran:
 ```
./configure --prefix=/usr/local/keepalived-2.1.5
...
Keepalived configuration
Keepalived version       : 2.1.0
Compiler                 : gcc
Preprocessor flags       : -D_GNU_SOURCE
Compiler flags           : -g -g -O2 -Wall -Wextra -Wunused -Wstrict-prototypes -Wbad-function-cast -Wcast-align -Wcast-qual -Wdisabled-optimization -Wdouble-promotion -Wfloat-equal -Wformat-security -Wframe-larger-than=5120 -Winit-self -Winline -Wjump-misses-init -Wlogical-op -Wmissing-declarations -Wmissing-field-initializers -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Woverlength-strings -Wpointer-arith -Wredundant-decls -Wshadow -Wstack-protector -Wstrict-overflow=4 -Wstrict-prototypes -Wsuggest-attribute=const -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wsuggest-attribute=pure -Wsync-nand -Wtrampolines -Wundef -Wuninitialized -Wunknown-pragmas -Wunsuffixed-float-constants -Wunused-macros -Wvariadic-macros -Wwrite-strings -fPIE -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -O2
Linker flags             : -pie -Wl,-z,relro -Wl,-z,now
Extra Lib                : -lm -lcrypto -lssl -lnl
Use IPVS Framework       : Yes
IPVS use libnl           : Yes
IPVS syncd attributes    : No
IPVS 64 bit stats        : No
HTTP_GET regex support   : No
fwmark socket support    : Yes
Use VRRP Framework       : Yes
Use VRRP VMAC            : Yes
Use VRRP authentication  : Yes
With ip rules/routes     : Yes
With track_process       : Yes
With linkbeat            : Yes
Use BFD Framework        : No
SNMP vrrp support        : No
SNMP checker support     : No
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
DBUS support             : No
SHA1 support             : No
Use JSON output          : No
libnl version            : 1
Use IPv4 devconf         : No
Use iptables             : No
Use nftables             : No
init type                : systemd
Strict config checks     : No
Build genhash            : Yes
Build documentation      : No
```

I'm using a Red Hat Enterprise Linux Server release 7.7 (Maipo)
3.10.0-1062.el7.x86_64

I recompiled 2.0.20 version and it is still working, but looks like after 2.1.0 version it stopped working

**Comment by pqarmitage** [comment]
@juanvasquezreyes You appear not to have the relevant -devel libraries installed for building keepalived. The INSTALL file in the root of the source tree lists the necessary packages . You appear to be missing libnl3-devel ipset-devel iptables-devel and libnftnl-devel and/or libmnl-devel.

Without libnftnl-devel installed I get the error you are getting, but once I install libnftnl-devel keepalived successfully builds.

**Comment by juanvasquezreyes** [comment]
That solve the problem, thank you.

**Comment by pqarmitage** [comment]
@juanvasquezreyes Commit 5de3213 fixes building with libnl1, and it was probably useful that the build did fail since otherwise you would have been building with suboptimal libraries.

I will see if I can find a way of configure detecting important runtime libraries being installed without the -devel versions installed.
