### ISSUE TITLE
Keepalived_vrrp exited due to segmentation fault (SIGSEGV)

### ISSUE THREAD

**Issue by d-mihaylenko** [acassen/keepalived#1701]
Keepalived not work at debian10.4

keepalived -v
Keepalived v2.0.10 (11/12,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.20
Running on Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07)

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --with-kernel-dir=debian/ --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus --enable-dbus-create-instance --enable-json --enable-bfd build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/build/keepalived-8agDac/keepalived-2.0.10=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS DBUS_CREATE_INSTANCE

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

kern.log
Jul 22 22:00:21 db0kl12 kernel: [  499.705972] keepalived[22296]: segfault at 90 ip 000055d84a3fc1c0 sp 00007ffdbc751b20 error 4 in keepalived[55d84a3d0000+62000]
Jul 22 22:00:21 db0kl12 kernel: [  499.705976] Code: 00 4d 85 ed 75 18 e9 56 20 00 00 0f 1f 80 00 00 00 00 49 89 dd 48 85 db 0f 84 04 01 00 00 49 8b 6d 10 49 8b 5d 00 48 8b 45 50 <48> 8b 80 90 00 00 00 44 8b 70 10 45 85 f6 74 d8 48 85 db 75 30 e9

**Comment by pqarmitage** [comment]
In order for us to investigate this, we are going to need the following:

i) A copy of your configuration file
ii) If possible a stack backtrace produced by gdb from a corefile produced following the segfault.

**Comment by pqarmitage** [comment]
It might be worth seeing if upgrading keepalived to v2.1.5 resolves the problem you are experiencing.

**Comment by pqarmitage** [comment]
Closing due to no response for over 1 week. If you are still experiencing problems please update this issue with further details, including the details requested above, and we can reopen this issue.
