### ISSUE TITLE
keepalived -p pidfile -r vrrp_pidfile permission issue

### ISSUE THREAD

**Issue by sheshesheshe** [acassen/keepalived#1734]
I found that the pidfile and vrrpfile generated by "keepalived XXXX -p pidfile -r vrrp_pidfile" only have read and write permissions for user, but neither group nor other has any permissions.

reproduce the behaviour:
[root@fusion3 ~]# keepalived -P -f /var/lib/neutron/ha_confs/c68176f0-043b-4bea-992f-fe327cd2e57e/keepalived.conf -p /var/lib/neutron/ha_confs/c68176f0-043b-4bea-992f-fe327cd2e57e.pid -r /var/lib/neutron/ha_confs/c68176f0-043b-4bea-992f-fe327cd2e57e.pid-vrrp
[root@fusion3 ~]# ls -l /var/lib/neutron/ha_confs/c68176f0-043b-4bea-992f-fe327cd2e57e.pid
-rw------- 1 root root 7 Sep 17 10:43 /var/lib/neutron/ha_confs/c68176f0-043b-4bea-992f-fe327cd2e57e.pid

Expected behavior：
-rw-r--r-- 1 root root 7 Sep 17 10:43 /var/lib/neutron/ha_confs/c68176f0-043b-4bea-992f-fe327cd2e57e.pid

Keepalived version：
[root@fusion3 ~]# keepalived -v
Keepalived v2.0.16 (05/03,2019), git commit v2.0.15-96-g4d492740+

**Comment by pqarmitage** [comment]
Commit 12f3a23 resolved this issue, and this was first included in v2.0.19.

While investigating this I discovered there is also an issue of not setting read and execute permissions for group and other when keepalived creates directories under /run for pid files, which is now resolved by commit 131ad5e.
