### ISSUE TITLE
unable to set weight 0 on real-server

### ISSUE THREAD

**Issue by marco-a-itl** [acassen/keepalived#1757]
**Describe the bug**
After moving from release `v2.0.20` to release `v2.1.5`, if weight `0` is set on a real-server in keepalived.conf, ipvs is programmed with weight `1`, instead of weight `0`.

**To Reproduce**
Start keepalived with the following configuration file:
```
virtual_server 10.0.2.15 80 {
    protocol TCP

    real_server 10.0.2.16 80 {
                weight 0
    }
}
```
and check ipvs configuration with `ipvsadm -Ln`: real-server has wrong weight `1`.
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.0.2.15:80 wlc
  -> 10.0.2.16:80                 Masq    1      0          0

```

**Expected behavior**
Setting weight `0` on a real-server in keepalived.conf should be reflected on ipvs configuration, which should have weight `0` for the real-server as well.

**Keepalived version**
```
Keepalived v2.1.5 (07/13,2020)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019

configure options:

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION NET_LINUX_IF_ETHER_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RESET_ON_FORK
```

**Distro (please complete the following information):**
 - Name `CentOS`
 - Version `7.6.1810`
 - Architecture `x86_64`

**Comment by marco-a-itl** [comment]
Looks like the weight is changed inside `init_service_rs()`, where the following check is made:

```
                       if (rs->effective_weight < 1)
                               rs->weight = 1;
```

If the intention behind that recently added code was to clamp `rs->weight` within a valid range, maybe the code could be changed like this:

```
diff --git a/keepalived/check/ipwrapper.c b/keepalived/check/ipwrapper.c
index f060feb..88d042e 100644
--- a/keepalived/check/ipwrapper.c
+++ b/keepalived/check/ipwrapper.c
@@ -388,8 +388,8 @@ init_service_rs(virtual_server_t *vs)
                                        rs->num_failed_checkers++;
                        }

-                       if (rs->effective_weight < 1)
-                               rs->weight = 1;
+                       if (rs->effective_weight < 0)
+                               rs->weight = 0;
                        else if (rs->effective_weight > IPVS_WEIGHT_MAX - 1)
                                rs->weight = IPVS_WEIGHT_MAX - 1;
                        else

```

**Comment by pqarmitage** [comment]
@marco-a-itl This is a bit more complicated that just the change suggested above. The main place the change needs to be made is in `update_svr_wgt()`, which in itself is quite straightforward. The complication is that if a real server has a weight of 0 it doesn't form part of the quorum, and so the quorum calculation now needs to change as well.

I will have a look at this over the next few days.

**Comment by glomazdov** [comment]
Is there any other way to take the real server out of service? When I use ipvsadm -w 0, after the stop / start of the service, the real server itself returns to the balancing table with its original weight.
How to remove a real server for maintenance completely.

**Comment by pqarmitage** [comment]
Manually changing the IPVS configuration set up by keepalived is not supported; it is managed by keepalived.

If you want to change the IPVS configuration, such as taking a real server out of service, then there are two options:
1. update the keepalived configuration file(s) and tell keepalived to reload the configuration (SIGHUP)
2. For each real_server that you might want to be able to take out of service configure a FILE_CHECK checker; then you can write a non-zero value to the tracked file and the real server will be disabled/removed (use `inhibit_on_failure` if you want the weight set to 0).

**Comment by pqarmitage** [comment]
Commit e2b4d10 allows weight 0 to be specified for real servers. Since this is only useful if using a dynamic MISC_CHECK or a FILE_CHECK commits 8761a68..511fad3 also sort out dynamic MISC_CHECKs and FILE_CHECKs so that multiple MISC_CHECKs can be used, MISC_CHECKs and FILE_CHECKs can be used together, and reloading works properly with MISC_CHECKs and FILE_CHECKs.
