### ISSUE TITLE
unable to ping the failover IP once it is moved

### ISSUE THREAD

**Issue by shettypriy** [acassen/keepalived#1769]
I have configured two debian10 machines where I have installed haproxy and keepalived on each of the machines. Also, failover IP is configured on both the servers on the network interface. When I stop the haproxy service on machine A the failover IP is moved from machine A to machine B network interface. However, when I try to ping the failover IP which is moved to machine B from another machine , say machine C, there is no response. It says 'Unable to connect to remote host: Connection timed out' when a telnet is done. Also,I am unable to ping to that failover IP from other machine(machine C). Failover IPs of both the machines are whitelisted in UFW firewall. Could you anyone help me on this

**Comment by pqarmitage** [comment]
@shettypriy You refer to stopping haproxy, but don't mention doing anything with keepalived. Is this a keepalived issue?

If we are to be able to help any further, will will need the following information
1. Copies of your keepalived configurations
1. Copies of any scripts that the keepalived configurations use
1. Output of `keepalived -v`
1. The MAC and IP addresses of the machines
1. Output of `ip neighbour show` from all the machines when you have the problem
1. Confirmation that you can ping and telnet to the native IP addresses of the machines

**Comment by shettypriy** [comment]
1. [keepalived_machineA.txt](https://github.com/acassen/keepalived/files/5464860/keepalived_machineA.txt)
   [keepalived_machineB.txt](https://github.com/acassen/keepalived/files/5464861/keepalived_machineB.txt)
2. Shell script that is used to move the failover IP from machine A to machine B and vice versa. We are suing the hetzner server failover IP.
[haproxy_failover.txt](https://github.com/acassen/keepalived/files/5464873/haproxy_failover.txt)

3. Keepalived v2.0.10 (11/12,2018)

4. Unfortuantely, I cannot share the server IP and MAc address sicne it is a prduction server

5. same as above

6. When the failover IP or the virtual IP are on the respective machines , I am able to ping and telnet. Once they are moved from another machine ping and telnet does not work. 

Also, I have configured the failoverIP on network interface of respective machine by updating in the file /etc/network/interfaces file. As per hetzner  https://robot.your-server.de/doc/webservice/en.html#get-failover , failover IP should be configured on each of the server where the IP moves. Doing this also did not work. COuld you please guide me how I can go about fixing it. WHy does the failover IP when moved from machine A to machine B, does not respond ping or telnet
