### ISSUE TITLE
Messages in the log IPVS cmd IP_VS_SO_SET_ADD(1154) error: Service already exists(17)

### ISSUE THREAD

**Issue by igroost** [acassen/keepalived#1772]
After updating to keeaplived-2.1.5, many messages of the form appeared in the logIPVS cmd IP_VS_SO_SET_ADD(1154) error: Service already exists(17). Tell me, what is the reason?

**Comment by pqarmitage** [comment]
The reason for those messages is that when keepalived last terminated it didn't remove the old IPVS configuration for some reason.

**Comment by igroost** [comment]
We are talking about the config file i.e. balancing settings which are then passed to ipvsadm? How can I understand the reason why the configuration was not deleted? The solution in this case is simply restarting the service or is it better to restart the entire machine?

**Comment by wangxp006** [comment]
@igroost 
The keepalived configuration does not pass to ipvsadm directly, but pass to ipvs in kernel. 
Both keepalived and ipvsadm  interact with the ipvs in kernel through netlink. 
For a normal keepalive exit process, the kernel ipvs is notified via netlink to delete the configuration. However, if keepalived exits abnormally (for example, coredump occurs), the kernel is not notified to delete the configuration. Then the next time keepalived starts, the same configuration of pass to ipvs in kernel will cause the current problem. 
If you want to clear the previous configuration before starting keepalived, try executing ipvsadm -C.

**Comment by igroost** [comment]
@wangxp006 Thanks for the answer.
