### ISSUE TITLE
Is there a plan to tag a new keepalived release?

### ISSUE THREAD

**Issue by libesz** [acassen/keepalived#1805]
**Describe the issue**
A would need recent new features in a release. Is it planned still in this year?

**To Reproduce**
-

**Expected behavior**
-

**Keepalived version**
-

**Distro (please complete the following information):**
- Alpine edge

**Details of any containerisation or hosted service (e.g. AWS)**
-

**Configuration file:**
-

**Notify and track scripts**
-

**System Log entries**
-

**Did keepalived coredump?**
-

**Additional context**
- I would like to announce the newest keepalived (containing new features that I would use in production) to linux distributions (specifically to the next Alpine linux, which will be released at the end of this year). So that I would need a tagged release.

Thanks in advance!

**Comment by acassen** [comment]
yes planed for Xmas

**Comment by libesz** [comment]
Thanks. Did it happen? 😄

**Comment by acassen** [comment]
I think we can close it now.
