### ISSUE TITLE
SSL_GET check never timeouts if TLS 1.2 connection is terminated incorrectly

### ISSUE THREAD

**Issue by rzerda** [acassen/keepalived#1817]
**Describe the bug**

During check, if active TLS 1.2 connection between keepalived and realserver is blackholed for some time, check will not timeout and no further checks for this realserver and URL will be performed.

**To Reproduce**

VM1 has keepalived (find the config below), VM2 has Nginx 1.14 and snakeoil certs from ssl-cert deb package.

1. start nginx on VM2 with TLS configured by uncommenting the corresponding lines in `/etc/nginx/sites-available/default`
2. start keepalived on VM1
3. wait for realserver to appear in `ipvsadm -ln` output
4. apply the iptables rule on VM2 (realserver): `iptables -I OUTPUT -p tcp --sport 443 -m u32 --u32 "52&0xFF000000=0x15000000" -j DROP`
5. wait 2 minutes or whatever it takes for realserver to “forget” the connection
6. (optional) remove iptables rule added in step 4
7. stop nginx on VM2

Observed no keepalived log messages about failing realserver, no further checks for this realserver, realserver stays in the virtual server config.

**Expected behavior**

Check failed after configured timeout, realserver removed from virtual server, checks continue as usual.

**Keepalived version**

```

Keepalived v2.1.5 (12/16,2020), git commit v2.1.5-256-g1732b3f2
Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>
Built with kernel headers for Linux 4.15.18
Running on Linux 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020
Distro: Ubuntu 18.04.5 LTS
configure options:
Config options:  LIBIPSET_DYNAMIC NFTABLES SYSTEMD LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING
System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 MEMFD_CREATE IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPSET_PRE_V7 IPTABLES NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK
```

**Distro (please complete the following information):**

Ubuntu 18.04.5 x86_64

**Details of any containerisation or hosted service (e.g. AWS)**

None, experiments are conducted in VMs on VMware Workstation.

**Configuration file:**

```

virtual_server 10.0.0.1 443 {
  delay_loop 6
  lb_algo rr
  lb_kind TUN
  protocol TCP
  real_server 192.168.60.131 443 {
        weight 1
        SSL_GET {
          url {
            path /
          }
          connect_timeout 1
          retry 1
        }
  }
}
```

**Notify and track scripts**
 
 None.

**System Log entries**

```
Dec 17 13:37:36 keepalived-bionic Keepalived[16282]: Starting Keepalived v2.1.5 (12/16,2020), git commit v2.1.5-256-g1732b3f2
Dec 17 13:37:36 keepalived-bionic Keepalived[16282]: WARNING - keepalived was built for newer Linux 4.15.18, running on Linux 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020
Dec 17 13:37:36 keepalived-bionic Keepalived[16282]: Command line: './bin/keepalived' '-n'
Dec 17 13:37:36 keepalived-bionic Keepalived[16282]: Configuration file /etc/keepalived/keepalived.conf
Dec 17 13:37:36 keepalived-bionic Keepalived[16282]: NOTICE: setting config option max_auto_priority should result in better keepalived performance
Dec 17 13:37:36 keepalived-bionic Keepalived[16282]: Starting Healthcheck child process, pid=16283
Dec 17 13:37:36 keepalived-bionic Keepalived_healthcheckers[16283]: Initializing ipvs
Dec 17 13:37:36 keepalived-bionic Keepalived_healthcheckers[16283]: Gained quorum 1+0=1 <= 1 for VS [10.0.0.1]:tcp:443
Dec 17 13:37:36 keepalived-bionic Keepalived_healthcheckers[16283]: Activating healthchecker for service [192.168.60.131]:tcp:443 for VS [10.0.0.1]:tcp:443
Dec 17 13:37:43 keepalived-bionic Keepalived_healthcheckers[16283]: Remote Web server [192.168.60.131]:tcp:443 succeed on service.
Dec 17 13:42:35 keepalived-bionic Keepalived[16282]: Stopping
Dec 17 13:42:35 keepalived-bionic Keepalived_healthcheckers[16283]: Shutting down service [192.168.60.131]:tcp:443 from VS [10.0.0.1]:tcp:443
Dec 17 13:42:35 keepalived-bionic Keepalived_healthcheckers[16283]: Stopped
Dec 17 13:42:35 keepalived-bionic Keepalived[16282]: Stopped Keepalived v2.1.5 (12/16,2020), git commit v2.1.5-256-g1732b3f2
```

**Did keepalived coredump?**

No.

**Additional context**

iptables rule simulates drop of SSL Encrypted Alert message, last packet in TLS 1.2 with L7 data. Not sure if other TLS protocol versions are affected.

**Comment by pqarmitage** [comment]
I can see the cause of the problem in the code, and will produce a patch in the morning. It looks as though all TLS protocol versions are affected.

**Comment by pqarmitage** [comment]
Commit 4ca6354 resolves this issue.

I found `iptables -I OUTPUT -s x.x.x.x -d y.y.y.y -p tcp --sport 443 --tcp-flags FIN FIN -j DROP` was sufficient to trigger the problem. The entry `-m u32 --u32 "52&0xFF000000=0x15000000"` did not work for me.
