### ISSUE TITLE
Incorrect state if tracked interface was in bridge

### ISSUE THREAD

**Issue by omikhaylov** [acassen/keepalived#1823]
**Describe the bug**
If tracked interface is placed into the bridge, then gets out from the bridge and changes state to 'DOWN', instance will still be in 'MASTER' state.

**Сontext**
Device has 2 interfaces: eth0 and eth1.
Initially interface eth0 has no settings and does not consist in any bridge. It only has state 'UP'.
Interface eth1 was configured with ip addess (in /eth/network/interfaces). Interface eth1 also has state 'UP'.
In initial situation instance has state 'MASTER'.

**Configuration file:**
vrrp_sync_group 0 {
  group {
    eth1_1
  }
}
vrrp_instance eth1_1 {
  interface eth1
  track_interface {
    eth0
  }
  virtual_ipaddress {
    192.168.255.3/29 label eth1:900
  }
  priority 100
  advert_int 1
  virtual_router_id 1
}

**To Reproduce**
1. Create bridge interface: brctl addbr br0
2. Add interface eth0 to bridge: ip link set dev eth0 master br0
3. Put interface out from the bridge and put it down: ip link set dev eth0 nomaster && ip link set dev eth0 down

After these steps instance eth1_1 state stays unchanged.

**Expected behavior**
Instance should have changed it's state to 'FAULT'.

**Keepalived version**
Keepalived v2.1.5 (unknown)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.9.189
Running on Linux 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3st1 (2019-09-12)

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --enable-dbus --enable-log-file --enable-snmp-vrrp --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-json --with-init=systemd build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/root/build/keepalived/keepalived=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH JSON OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS FILE_LOGGING LOG_FILE_APPEND

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV RTA_VIA FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPSET_PRE_V7 IPTABLES NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK

**Distro:**
 - Debian 9 x86_64

**System Log entries**
***syslog***
Dec 24 19:04:57 GW1 systemd[1]: Starting Keepalive Daemon (LVS and VRRP)...
Dec 24 19:04:58 GW1 Keepalived[1010]: Starting Keepalived v2.1.5 (unknown)
Dec 24 19:04:58 GW1 Keepalived[1010]: WARNING - keepalived was build for newer Linux 4.9.189, running on Linux 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3st1 (2019-09-12)
Dec 24 19:04:58 GW1 Keepalived[1010]: Command line: '/usr/sbin/keepalived' '-d' '-P' '-S' '7' '-x' '-g' '--flush-log-file'
Dec 24 19:04:58 GW1 Keepalived[1010]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 24 19:04:58 GW1 systemd[1]: Started Keepalive Daemon (LVS and VRRP).
Dec 24 19:04:58 GW1 Keepalived[1013]: NOTICE: setting config option max_auto_priority should result in better keepalived performance
Dec 24 19:04:58 GW1 Keepalived[1013]: Starting VRRP child process, pid=1014
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]: Registering Kernel netlink reflector
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]: Registering Kernel netlink command channel
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]: Starting SNMP subagent
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]: NET-SNMP version 5.7.3 AgentX subagent connected
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]: Sync group 0 has only 1 virtual router(s) - this probably isn't what you want - removing
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]: Registering gratuitous ARP shared channel
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]: ------< Global definitions >------
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Network namespace = (default)
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Network namespace ipvs = (main namespace)
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Router ID = [unknown]
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Default smtp_alert = unset
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Default smtp_alert_vrrp = unset
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Default smtp_alert_checker = unset
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Checkers log all failures = false
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Dynamic interfaces = false
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Default interface = eth0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  LVS flush = false
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  LVS flush on stop = disabled
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  VRRP notify priority changes = false
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  VRRP IPv4 mcast group = 224.0.0.18
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  VRRP IPv6 mcast group = ff02::12
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Gratuitous ARP delay = 5
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Gratuitous ARP repeat = 5
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Gratuitous ARP refresh timer = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Gratuitous ARP refresh repeat = 1
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Gratuitous ARP lower priority delay = 5
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Gratuitous ARP lower priority repeat = 5
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Send advert after receive lower priority advert = true
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Send advert after receive higher priority advert = false
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Gratuitous ARP interval = 0.000000
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Gratuitous NA interval = 0.000000
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  VRRP default protocol version = 2
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  VRRP check unicast_src = false
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  VRRP skip check advert addresses = false
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  VRRP strict mode = false
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Max auto priority = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Min auto priority delay = 1000000 usecs
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  VRRP process priority = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  VRRP don't swap = false
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  VRRP realtime priority = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  VRRP realtime limit = 10000
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Checker process priority = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Checker don't swap = false
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Checker realtime priority = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Checker realtime limit = 10000
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  SNMP vrrp enabled
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  SNMP checker enabled
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  SNMP RFCv2 enabled
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  SNMP RFCv3 enabled
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  SNMP traps disabled
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  SNMP socket = default (unix:/var/agentx/master)
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  DBus disabled
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  DBus service name =
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Script security disabled
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Default script uid:gid 0:0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  vrrp_netlink_cmd_rcv_bufs = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  vrrp_netlink_cmd_rcv_bufs_force = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  vrrp_netlink_monitor_rcv_bufs = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  vrrp_netlink_monitor_rcv_bufs_force = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  process_monitor_rcv_bufs = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  process_monitor_rcv_bufs_force = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  lvs_netlink_cmd_rcv_bufs = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  lvs_netlink_cmd_rcv_bufs_force = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  lvs_netlink_monitor_rcv_bufs = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  lvs_netlink_monitor_rcv_bufs_force = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  rs_init_notifies = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  no_checker_emails = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  rx_bufs_multiples = 3
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  umask = 0177
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]: ------< VRRP Topology >------
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  VRRP Instance = eth1_1
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    VRRP Version = 2
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Wantstate = BACKUP
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Interface = eth1
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Using src_ip = 192.168.1.100
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Gratuitous ARP delay = 5
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Gratuitous ARP repeat = 5
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Gratuitous ARP refresh = 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Gratuitous ARP refresh repeat = 1
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Gratuitous ARP lower priority delay = 5
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Gratuitous ARP lower priority repeat = 5
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Send advert after receive lower priority advert = true
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Send advert after receive higher priority advert = false
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Virtual Router ID = 1
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Priority = 100
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Advert interval = 1 sec
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Accept = enabled
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Preempt = enabled
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Promote_secondaries = disabled
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Authentication type = none
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Virtual IP :
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:      192.168.255.3/29 dev eth1 scope global label eth1:900
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    No sockets allocated
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Tracked interfaces :
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:      eth0 weight 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Using smtp notification = no
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Notify deleted = Fault
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Notify priority changes = false
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]: ------< Interfaces >------
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Name = lo
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    index = 1
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    IPv4 address = 127.0.0.1
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    IPv6 address = (none)
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    State = UP, RUNNING, no broadcast, loopback, no multicast
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    MTU = 65536
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    HW Type = LOOPBACK
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    NIC netlink status update
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Reset ARP config counter 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Original arp_ignore 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Original arp_filter 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Original promote_secondaries 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Reset promote_secondaries counter 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Name = eth0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    index = 2
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    IPv4 address = (none)
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    IPv6 address = (none)
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    MAC = 00:50:56:9e:a8:45
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    MAC broadcast = ff:ff:ff:ff:ff:ff
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    State = UP, RUNNING
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    MTU = 1500
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    HW Type = ETHERNET
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    NIC netlink status update
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Reset ARP config counter 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Original arp_ignore 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Original arp_filter 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Original promote_secondaries 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Reset promote_secondaries counter 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Tracking VRRP instances :
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:      eth1_1, weight 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:  Name = eth1
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    index = 3
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    IPv4 address = 192.168.1.100
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    IPv6 address = (none)
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    MAC = 00:50:56:9e:d6:4b
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    MAC broadcast = ff:ff:ff:ff:ff:ff
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    State = UP, RUNNING
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    MTU = 1500
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    HW Type = ETHERNET
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    NIC netlink status update
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Reset ARP config counter 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Original arp_ignore 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Original arp_filter 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Original promote_secondaries 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Reset promote_secondaries counter 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:    Tracking VRRP instances :
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]:      eth1_1, weight 0
Dec 24 19:04:58 GW1 Keepalived_vrrp[1014]: (eth1_1) Entering BACKUP STATE (init)
Dec 24 19:05:02 GW1 Keepalived_vrrp[1014]: (eth1_1) Entering MASTER STATE
Dec 24 19:05:11 GW1 kernel: [  122.833577] br0: port 1(eth0) entered blocking state
Dec 24 19:05:11 GW1 kernel: [  122.833579] br0: port 1(eth0) entered disabled state
Dec 24 19:05:11 GW1 kernel: [  122.833882] device eth0 entered promiscuous mode
Dec 24 19:05:23 GW1 Keepalived_vrrp[1014]: Interface eth0 deleted
Dec 24 19:05:23 GW1 Keepalived_vrrp[1014]: Netlink reports eth0 up
Dec 24 19:05:23 GW1 kernel: [  134.998854] device eth0 left promiscuous mode
Dec 24 19:05:23 GW1 kernel: [  134.998926] br0: port 1(eth0) entered disabled state
Dec 24 19:05:23 GW1 Keepalived_vrrp[1014]: Netlink reports eth0 down

**Did keepalived coredump?**
No

**Comment by pqarmitage** [comment]
When the command `ip link set eth0 nomaster` is executed, netlink sends an RTM_DELLINK message followed by an RTM_NEWLINK message. When a link is deleted normally, an RTM_NEWLINK with status down is sent before the RTM_DELLINK message is sent, and so keepalived ignores the RTM_DELLINK message since it doesn't need to process it. The consequence of this is that when we just get an RTM_DELLINK message followed by an RTM_NEWLINK message it isn't handled properly.

I will need to investigate further to work out how to resolve this issue.

**Comment by pqarmitage** [comment]
There was a comment in `cleanup_lost_interface()` which said `/* If this is just a tracking interface, we don't need to do anything */`, and that was what was wrong. If an interface is deleted in the normal way (`ip link del ...`), netlink sends an RTM_NEWLINK message with flags !UP and !RUNNING (i.e. link down), which is what keepalived expected before the RTM_DELLINK message; consequently keepalived processed the link down message and did not need to process the RTM_DELLINK message. However, for setting an interface to have no master, there is an RTM_DELLINK followed by an RTM_NEWLINK, and both messages have the UP and RUNNING flags set.

The change that was needed was to process the RTM_DELLINK message if the link was still up, which commit a34ff98 implements.
