### ISSUE TITLE
SMTP_SERVER different port doesnt work

### ISSUE THREAD

**Issue by bodzio4519** [acassen/keepalived#1830]
hi, I have a keepalived config where I want the smtp connection to use a different host and port due to the server being mailserver and there is an open relay internal server which will be able to send page emails out. But the configuration does not seem to work as the port number is ignored.

Keepalived v2.0.10

I try like that: 
```
   notification_email_from keepalvd@example.com
   smtp_server 192.168.165.111 26
   smtp_connect_timeout 30
   smtp_alert
```
and like that:
```
   notification_email_from keepalvd@example.com
   smtp_server 192.168.165.111 [26]
   smtp_connect_timeout 30
   smtp_alert
```

Port 25 works, i checked in wireshark

**Comment by pqarmitage** [comment]
The correct syntax is `smtp_server 192.168.165.111 26`. The `[` and `]` are used in the man page to denote parameters that are optional.

I have tested this with both the current version (v2.2.0) and v2.0.10, and it works as expected, i.e. it connects to the specified port, or port 25 if no port is specified.

**Comment by pqarmitage** [comment]
If you execute `kill -USR1 $(cat /run/keepalived.pid)` while keepalived is running and look at the generated file /tmp/keepalived.data, you should see around line 6:
```
 Smtp server = 192.168.165.111
 Smtp server port = 26
```

If not, can you please post your fully configuration file, and the output of `keepalived -v`.
