### ISSUE TITLE
compiling in the build enviroment

### ISSUE THREAD

**Issue by emper0r** [acassen/keepalived#1843]
_Support requests should be sent via_ https://groups.io/g/keepalived-users

**Describe what you need help/support for**
Hi Alex, we are trying to compiling the last tarball into a build enviroment container with tool compilation to not install this tools on production server but when we do ./configure and make after that we zipped that directory to do the last make install on the server producion to install binaries and get the last result there. and we got this error on compilation 

```
make[1]: Entering directory '/root/download/keepalived/keepalived-2.2.1_x86_64/lib' /bin/sh: line 50: cd: /tmp/keepalived-2.2.1_x86_64/lib: No such file or directory
```

**Distro (please complete the following information):**
 - Name: Centos
 - Version: 7
 - Architecture: x86_64

we are trying to do now from git with build option or directly with make rpm to test but the other software from source we use as generic ./configure, make  and make install steps in ansible deployment.

thanks in advance

**Comment by pqarmitage** [comment]
I think it is safe to say this is not a supported way of building/deploying keepalived.

A more supported way to does this would be: 

In the build environment container after `make`, execute:
```
mkdir /tmp/ka_install
make install DESTDIR=/tmp/ka_install
tar -C /tmp/ka_install -cvf ../keepalived-install.tar .
```
Copy /tmp/keepalived-install.tar to the production system as, for example /tmp/keepalived-install.tar
```
cd /
tar -xf /tmp/keepalived-install.tar
```
Using `make install DESTDIR=...` is what rpmbuild does to install the files in a directory where it can then package them in the .rpm file.

It might be easier, and it is certainly what I would do, to build an rpm in the container and then install that on the production system. I would get the keepalived.spec file by extracting it from the CentOS keepalived source rpm, and then modify the spec file to suit your needs. If you want a RedHat created .spec file for keepalived v2.2.1 one can be downloaded from [keepalived.spec](https://src.fedoraproject.org/rpms/keepalived/blob/master/f/keepalived.spec) (it is the Fedora 34 keepalived.spec file).
