### ISSUE TITLE
Configuration from older systems breaks newer keepalived versions.

### ISSUE THREAD

**Issue by rsjohn** [acassen/keepalived#1846]
I am not sure what the proper solution for this is but I felt you should be aware of this.

https://askubuntu.com/questions/1312333/keepalived-not-working-on-20-04/1312769#1312769

**Comment by pqarmitage** [comment]
@rsjohn Many thanks for alerting us to this question on askubuntu. I have updated the question to try an explain the rational for what happened.

I am not sure there is a "proper solution", since a cannot see a way of changing `vrrp_strict` that will not cause problems for someone.
