### ISSUE TITLE
vrrp_instance notify_stop never executes

### ISSUE THREAD

**Issue by davewongillies** [acassen/keepalived#185]
I'm attempting to use the `notify_stop` option in my `vrrp_instance` but I'm noticing that when stopping keepalived that it never gets executed. The only log entry I see in syslog is:
```
Aug 21 01:34:10 my-keepalived-server Keepalived[30476]: Stopping Keepalived v1.2.13 (06/15,2014)
```
Is this the correct option to use when I want notifications of `vrrp_instance`s being stopped when shutting down keepalived or is there something else I should be using?

```
vrrp_instance my_instance {
    state BACKUP
    interface eth0
    virtual_router_id 1
    priority 50
    advert_int 5

    smtp_alert
    notify_stop "/usr/local/sbin/keepalived_notify.sh"
    notify "/usr/local/sbin/keepalived_notify.sh"

    authentication {
        auth_type PASS
        auth_pass myp@assw0rd
    }

    include /etc/keepalived/conf.d/vrrp/instance.my_instance/*.conf
}
```
NB, the `notify` option works as expected when failing over my keepalived servers.

**Comment by acassen** [comment]
1.2.13 is too old, consider upgrading.

**Comment by davewongillies** [comment]
I've built version 1.2.19 and I'm still seeing exactly the same behaviour:
```
Aug 21 04:53:44 my-keepalived-server Keepalived[5662]: Stopping Keepalived v1.2.19 (08/21,2015)
```

**Comment by ksyblast** [comment]
I have the same issue, Keepalived v1.2.24

**Comment by acassen** [comment]
Hello,

1.2.19 is also way too old. Current stable release is 2.0.16, there has been tons of extensions and fixes since 1.2.19 release. Please consider upgrading to last stable.

**Comment by davewongillies** [comment]
@acassen thanks for replying to this almost 4 years later. I'm not in a job where I use keepalived anymore.

**Comment by acassen** [comment]
fun enough :)... I received a pop-up on GitHub just today... didn't look at the date... sorry about that.
