### ISSUE TITLE
nftables/iptables filter on interfaces when VRRP state is backup

### ISSUE THREAD

**Issue by louis-oui** [acassen/keepalived#1857]
**Is your feature request to resolve a problem or provide enhanced functionality? Please describe.**

We have some applications that do not support traffic on both VRRP nodes at the same time. When vmac is off (I cannot enable vmac in my architecture), at switchover, ARP update is not performed at the exact time on every machines. There is short time-slot where both nodes receives traffic. I want to ensure no traffic will disturb applications when state is backup.

**Describe the solution you would like**

My idea to implement nftables or iptables filter but only on interfaces that are backup. Interfaces that stays master should still accept traffic. I would like the possibility to be use notify scripts to be notified of the VRRP state per interface in addition to the group. So that I can script the addition/deletion of nftables / iptables.

**Describe alternatives you have considered**

- Shutting off applications at backup is not an option because there is a replication mechanism from the master to the backup that needs the process to be up
- Implement support for custom nftables / iptables rules in keepalived seems to be complex. What would be the format in keepalived ? Would it support all iptables / nftables syntax and possibilities ?
- Parsing keepalived.conf to get the correspondence between interfaces and group is complex

**Would the feature request be of benefit only to you, or is it more generally applicable?**

The suggested solution is flexible enough to support all use cases of filtering needs with iptables / nftables .

**Keepalived version**
any

**Additional context**
Add any other context about the feature request here.

**Comment by pqarmitage** [comment]
When a VRRP instance transitions to backup, keepalived removes any VIPs that it has configured for that VRRP instance, regardless of whether a VMAC is being used or not. If a packet is received on a system addressed to the VIP, but the VIP is not at that time configured on the system, the packet will not be passed to any application (the kernel drops the packet). Indeed, the packet does not even hit the INPUT chain of iptables. This means that not only is it unnecessary to add an iptables/nftables rule to drop the packet, but the rule will not even be traversed by the packet.

If you configure notify scripts for each VRRP instance then you will get a notification per VRRP instance in a sync group when the sync group changes state from master to backup and vice versa. You state `Parsing keepalived.conf to get the correspondence between interfaces and group is complex`. Using notifies for the VRRP instances means that you will only need to find the correspondence between VRRP instances and interfaces (why do you need the interface anyway; presumably you were thinking of adding that to the nftables/iptables rule, but using the VIP for the rule should be sufficient and is probably better). Are you parsing keepalived.conf to get the VIPs for each VRRP instance?

I am not sure what you mean by `use notify scripts to be notified of the VRRP state per interface`. It is the VRRP instances and the sync groups that change state, and hence can trigger notifications. When a VRRP instance transitions between master state and backup state there cannot be any change of state of the interface the VRRP instance is configured on. Furthermore, if using unicast peers, it is possible for the VRRP instance not to have an interface configured.

**Comment by louis-oui** [comment]
> When a VRRP instance transitions to backup, keepalived removes any VIPs that it has configured for that VRRP instance, regardless of whether a VMAC is being used or not. If a packet is received on a system addressed to the VIP, but the VIP is not at that time configured on the system, the packet will not be passed to any application (the kernel drops the packet). Indeed, the packet does not even hit the INPUT chain of iptables. This means that not only is it unnecessary to add an iptables/nftables rule to drop the packet, but the rule will not even be traversed by the packet.

@pqarmitage That is true. However, my application is actually an IPSec daemon. I want to filter packet that are not destined to the VIP with the FORWARD chain of iptables.

**Comment by pqarmitage** [comment]
@louis-oui Unfortunately I don't see any alternative to you writing a script that 'knows' the relationship between VRRP instances and interfaces, or parses the keepalived configuration file.
