### ISSUE TITLE
VRRPv3 IPv6 master / master after disabling vmac_xmit_base

### ISSUE THREAD

**Issue by louis-oui** [acassen/keepalived#1865]
**Describe the bug**
VRRPv3 IPv6 - Reload conf after disabling vmac_xmit_base results in master / master
VRRPv3 IPv4 OK

**To Reproduce**
# member 1
ip -6 addr add  fd00:100::3/64 dev ens4
# member 2
ip -6 addr add  fd00:100::4/64 dev ens4

killall keepalived
sleep 2
cat>/etc/keepalived/keepalived.conf <<\EOF
global_defs
{
router_id router
dynamic_interfaces
}

vrrp_sync_group group15 {
group {
vrrp
}
}

vrrp_instance vrrp {
version 3
state BACKUP
interface ens4

use_vmac vrrp
vmac_xmit_base

garp_master_delay 5

virtual_router_id 15

priority 200
advert_int 1.0

virtual_ipaddress {
fd00:100::1/64
}

preempt_delay 0
}
EOF
keepalived -D
sleep 5
ip a show vrrp
sleep 10
sed -e 's|vmac_xmit_base|#vmac_xmit_base|g' -i /etc/keepalived/keepalived.conf
kill -s SIGHUP $(pgrep keepalived | head -n1) #signal for conf reload
sleep 2
ip a show vrrp

**Observed behavior**
Conf reload with master / master
tcpdump -nni ens4 => does not show any vrrp packet (ip proto 112)

**Expected behavior**
Conf reload with master / backup

**Keepalived version**
Keepalived v2.2.1 (01/17,2021)

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.15.18
Running on Linux 4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020
Distro: Ubuntu 18.04 LTS

configure options: CFLAGS=-g -O0 --prefix=/usr --sysconfdir=/etc --with-extra-cflags=-I/usr/include/libnl3 --with-extra-ldflags= --disable-lvs --with-init=systemd --host=x86_64-linux-gnu host_alias=x86_64-linux-gnu

Config options:  SYSTEMD VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 MEMFD_CREATE IPV4_DEVCONF IPV6_ADVANCED_API RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK

**Distro (please complete the following information):**
 - Name ubuntu
 - Version 18.04
 - Architecture x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
no container

**Configuration file:**
see to reproduce

**Notify and track scripts**
NA

**System Log entries**

# member 1
journalctl _PID=$(pgrep keepalived | tail -n1)  | cat
-- Logs begin at Fri 2020-10-23 11:17:41 UTC, end at Wed 2021-03-03 18:17:15 UTC. --
Mar 03 18:10:16 ubuntu Keepalived_vrrp[7901]: Registering Kernel netlink reflector
Mar 03 18:10:16 ubuntu Keepalived_vrrp[7901]: Registering Kernel netlink command channel
Mar 03 18:10:16 ubuntu Keepalived_vrrp[7901]: Sync group group15 has only 1 virtual router(s) - this probably isn't what you want - removing
Mar 03 18:10:16 ubuntu Keepalived_vrrp[7901]: (vrrp) the first IPv6 VIP address should be link local
Mar 03 18:10:16 ubuntu Keepalived_vrrp[7901]: Assigned address fe80::e56:39ff:feb3:bd01 for interface ens4
Mar 03 18:10:16 ubuntu Keepalived_vrrp[7901]: (vrrp): Success creating VMAC interface vrrp
Mar 03 18:10:16 ubuntu Keepalived_vrrp[7901]: Registering gratuitous NDISC shared channel
Mar 03 18:10:16 ubuntu Keepalived_vrrp[7901]: (vrrp) Entering BACKUP STATE (init)
Mar 03 18:10:16 ubuntu Keepalived_vrrp[7901]: VRRP sockpool: [ifindex(  3), family(IPv6), proto(112), fd(12,13)]
Mar 03 18:10:19 ubuntu Keepalived_vrrp[7901]: (vrrp) Receive advertisement timeout
Mar 03 18:10:19 ubuntu Keepalived_vrrp[7901]: (vrrp) Entering MASTER STATE
Mar 03 18:10:19 ubuntu Keepalived_vrrp[7901]: (vrrp) setting VIPs.
Mar 03 18:10:19 ubuntu Keepalived_vrrp[7901]: (vrrp) Sending/queueing Unsolicited Neighbour Adverts on vrrp for fd00:100::1
Mar 03 18:10:19 ubuntu Keepalived_vrrp[7901]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:19 ubuntu Keepalived_vrrp[7901]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:19 ubuntu Keepalived_vrrp[7901]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:19 ubuntu Keepalived_vrrp[7901]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:19 ubuntu Keepalived_vrrp[7901]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:24 ubuntu Keepalived_vrrp[7901]: (vrrp) Sending/queueing Unsolicited Neighbour Adverts on vrrp for fd00:100::1
Mar 03 18:10:24 ubuntu Keepalived_vrrp[7901]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:24 ubuntu Keepalived_vrrp[7901]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:24 ubuntu Keepalived_vrrp[7901]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:24 ubuntu Keepalived_vrrp[7901]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:24 ubuntu Keepalived_vrrp[7901]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:31 ubuntu Keepalived_vrrp[7901]: Reloading
Mar 03 18:10:31 ubuntu Keepalived_vrrp[7901]: Sync group group15 has only 1 virtual router(s) - this probably isn't what you want - removing
Mar 03 18:10:31 ubuntu Keepalived_vrrp[7901]: (vrrp) the first IPv6 VIP address should be link local
Mar 03 18:10:31 ubuntu Keepalived_vrrp[7901]: (vrrp) Found matching interface vrrp
Mar 03 18:10:31 ubuntu Keepalived_vrrp[7901]: Assigned address fe80::e56:39ff:feb3:bd01 for interface ens4
Mar 03 18:10:31 ubuntu Keepalived_vrrp[7901]: (vrrp) setting VIPs.
Mar 03 18:10:31 ubuntu Keepalived_vrrp[7901]: VRRP sockpool: [ifindex( 33), family(IPv6), proto(112), fd(12,13)]
Mar 03 18:10:31 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:32 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:33 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:34 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:35 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:36 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:37 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:38 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:39 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:40 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:41 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:42 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:43 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:44 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:45 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:46 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:47 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:48 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:49 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:50 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:51 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:52 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:53 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:54 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:55 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:56 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:57 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:58 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:59 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:11:00 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:11:01 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:11:02 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:11:03 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:11:04 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:11:05 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:11:06 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:11:07 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:11:08 ubuntu Keepalived_vrrp[7901]: (vrrp): send advert error 22 (Invalid argument)

# member 2
journalctl _PID=$(pgrep keepalived | tail -n1)  | cat
-- Logs begin at Fri 2020-10-23 11:17:41 UTC, end at Wed 2021-03-03 18:18:05 UTC. --
Mar 03 18:10:17 ubuntu Keepalived_vrrp[28334]: Registering Kernel netlink reflector
Mar 03 18:10:17 ubuntu Keepalived_vrrp[28334]: Registering Kernel netlink command channel
Mar 03 18:10:17 ubuntu Keepalived_vrrp[28334]: Sync group group15 has only 1 virtual router(s) - this probably isn't what you want - removing
Mar 03 18:10:17 ubuntu Keepalived_vrrp[28334]: (vrrp) the first IPv6 VIP address should be link local
Mar 03 18:10:17 ubuntu Keepalived_vrrp[28334]: Assigned address fe80::e56:39ff:fe79:1901 for interface ens4
Mar 03 18:10:17 ubuntu Keepalived_vrrp[28334]: (vrrp): Success creating VMAC interface vrrp
Mar 03 18:10:17 ubuntu Keepalived_vrrp[28334]: Registering gratuitous NDISC shared channel
Mar 03 18:10:17 ubuntu Keepalived_vrrp[28334]: (vrrp) Entering BACKUP STATE (init)
Mar 03 18:10:17 ubuntu Keepalived_vrrp[28334]: VRRP sockpool: [ifindex(  8), family(IPv6), proto(112), fd(12,13)]
Mar 03 18:10:32 ubuntu Keepalived_vrrp[28334]: Reloading
Mar 03 18:10:32 ubuntu Keepalived_vrrp[28334]: Sync group group15 has only 1 virtual router(s) - this probably isn't what you want - removing
Mar 03 18:10:32 ubuntu Keepalived_vrrp[28334]: (vrrp) the first IPv6 VIP address should be link local
Mar 03 18:10:32 ubuntu Keepalived_vrrp[28334]: (vrrp) Found matching interface vrrp
Mar 03 18:10:32 ubuntu Keepalived_vrrp[28334]: Assigned address fe80::e56:39ff:fe79:1901 for interface ens4
Mar 03 18:10:32 ubuntu Keepalived_vrrp[28334]: VRRP sockpool: [ifindex( 21), family(IPv6), proto(112), fd(12,13)]
Mar 03 18:10:35 ubuntu Keepalived_vrrp[28334]: (vrrp) Receive advertisement timeout
Mar 03 18:10:35 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:35 ubuntu Keepalived_vrrp[28334]: (vrrp) Entering MASTER STATE
Mar 03 18:10:35 ubuntu Keepalived_vrrp[28334]: (vrrp) setting VIPs.
Mar 03 18:10:35 ubuntu Keepalived_vrrp[28334]: (vrrp) Sending/queueing Unsolicited Neighbour Adverts on vrrp for fd00:100::1
Mar 03 18:10:35 ubuntu Keepalived_vrrp[28334]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:35 ubuntu Keepalived_vrrp[28334]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:35 ubuntu Keepalived_vrrp[28334]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:35 ubuntu Keepalived_vrrp[28334]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:35 ubuntu Keepalived_vrrp[28334]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:36 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:37 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:38 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:39 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:40 ubuntu Keepalived_vrrp[28334]: (vrrp) Sending/queueing Unsolicited Neighbour Adverts on vrrp for fd00:100::1
Mar 03 18:10:40 ubuntu Keepalived_vrrp[28334]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:40 ubuntu Keepalived_vrrp[28334]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:40 ubuntu Keepalived_vrrp[28334]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:40 ubuntu Keepalived_vrrp[28334]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:40 ubuntu Keepalived_vrrp[28334]: Sending unsolicited Neighbour Advert on vrrp for fd00:100::1
Mar 03 18:10:40 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:41 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:42 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:43 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:44 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:45 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:46 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:47 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:48 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:49 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:50 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:51 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:52 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:53 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:54 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:55 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:56 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:57 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)
Mar 03 18:10:58 ubuntu Keepalived_vrrp[28334]: (vrrp): send advert error 22 (Invalid argument)

**Did keepalived coredump?**

No

**Additional context**

**Comment by pqarmitage** [comment]
Commit e48e804 resolves the issue. The problem was caused by the VMAC interface not having a link local IPv6 address, since it it is needed with vmac_xmit_base. If vmac_xmit_base is removed, a link local address needs to be added to the VMAC interface, which is what commit e48e804 does.

**Comment by louis-oui** [comment]
Thank you for the fix. It works
