### ISSUE TITLE
How to adjusting keepalived log levels？

### ISSUE THREAD

**Issue by zhuchen-heavy** [acassen/keepalived#1866]
Does keepalived support adjusting log levels？
If support，How to adjusting keepalived log levels？

**Comment by pqarmitage** [comment]
The log levels are hard coded, and the significant majority of log messages are logged to LOG_INFO. It is possible to change the facility that messages are logged to, with local0-local7, user and daemon being the available options (daemon is the default). The keepalived(8) man page explains this, although keepalived has not always worked in accordance with the documentation in this respect.
