### ISSUE TITLE
Build failure because IFLA_VRF_MAX undeclared

### ISSUE THREAD

**Issue by qingfenghanghua** [acassen/keepalived#1874]
**Describe the bug**
Hi，when i build keepalived-2.2.2 on my machine，it failed。just like this:

keepalived_netlink.c: In function ‘netlink_if_link_populate’:
keepalived_netlink.c:1660:70: error: ‘IFLA_VRF_MAX’ undeclared (first use in this function)
  struct rtattr* linkattr[max(max(IFLA_MACVLAN_MAX, IFLA_IPVLAN_MAX), IFLA_VRF_MAX) + 1];

make[2]: *** [keepalived_netlink.o] Error 1
make[2]: Leaving directory `/root/package/keepalived-2.2.2/keepalived/core'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/package/keepalived-2.2.2/keepalived'
make: *** [all-recursive] Error 1

**To Reproduce**
I guess our system kernel is not support VRF, but _HAVE_VRRP_IPVLAN is declared。We update linux kernel based on release。

**Expected behavior**
Can you add a new judgment to solve the situation ? 

**Keepalived version**
2.2.2
Output of `keepalived -v`
```

**Distro (please complete the following information):**
 - Name: Centos
 - Version: 7
 - Architecture: x86_64
 - GCC: 4.8.5

**Comment by acassen** [comment]
Hello, what is the kernel version running on your compiling host ? We drop support to old kernel, this means for kernel < 3.10.

**Comment by qingfenghanghua** [comment]
kernel version: 4.18.16-1.el7.elrepo.x86_64, we use EulerOS。

by the way ,this is running configure command output:
checking whether IFLA_IPVLAN_MODE is declared... yes
checking whether IFLA_VRF_MAX is declared... no

**Comment by acassen** [comment]
oh, yes I see... ifdef is wrong around...

**Comment by qingfenghanghua** [comment]
ok，I also want to learn another question。how to change the log level？ I notice we print many logs(include health check detail) in new version。when I running in the production environment, I hope only print error level logs

**Comment by acassen** [comment]
Following patch should solve the issue. Please confirm:

[vrf.patch.gz](https://github.com/acassen/keepalived/files/6106902/vrf.patch.gz)

**Comment by qingfenghanghua** [comment]
> Following patch should solve the issue. Please confirm:
> 
> [vrf.patch.gz](https://github.com/acassen/keepalived/files/6106902/vrf.patch.gz)

well,it solve the problem, thanks very much

**Comment by acassen** [comment]
we just merged this patch. Many thanks for feedback.

**Comment by pqarmitage** [comment]
@qingfenghanghua The only option for how much is logged is the `-D` command line option. You will probably find that this is set in /etc/sysconfig/keepalived. If you remove `-D` the the amount that is logged will be reduced.
