### ISSUE TITLE
wierd keepalived no route to host issue

### ISSUE THREAD

**Issue by stfast** [acassen/keepalived#1876]
**Describe the issue**

Keepalived is working at full capacity and functionality, but strange and wierd error probably implicitly related to Keepalived. Particular keepalived VIP stops responding on specific port (others still working). VIP responds to ICMP and other ports. This could be system (kernel, sysctl, openvswitch, firewalld, fail2ban, keepalived, conntrackd) related, without any errors in system log, but restarting keepalived solves an issue and service starts responding on particular port again.

I found very similar issue with same keepalived version 2.1.5:

https://unix.stackexchange.com/questions/600753/keepalived-no-route-to-host-firewall-issue

- working port (all at the same time)
 
[remote client] ~ #  nc -v sameip.si 25
Connection to sameip.si port 25 [tcp/smtp] succeeded!
220 sameip.si ESMTP Postfix
quit
221 2.0.0 Bye

- non-working port (all at the same time)

[remote client] ~ # nc -v sameip.si 143 !!!!!!!!!!!!!!!!!!!
nc: connectx to sameip.si port 143 (tcp) failed: Connection refused !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

[one-hop-up]# telnet sameip.si  25 !!!!!!!!!!!!!!!!!!!!!!!!!
Trying sameip.si ...
Connected to sameip.si .
Escape character is '^]'.
220 sameip.si  ESMTP Postfix
quit
221 2.0.0 Bye
Connection closed by foreign host.

[one-hop-up]# telnet sameip.si  143 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Trying sameip.si ...
telnet: connect to address sameip.si : No route to host !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

[one-hop-up]# telnet sameip.si  25
Trying sameip.si ...
Connected to sameip.si .
Escape character is '^]'.
220 sameip.si  ESMTP Postfix
quit
221 2.0.0 Bye
Connection closed by foreign host.

[one-hop-up]# telnet sameip.si  143
Trying sameip.si ...
telnet: connect to address sameip.si : No route to host

[root@sentinel1 keepalived]# ping sameip.si 
PING sameip.si  (sameip.si ) 56(84) bytes of data.
64 bytes from sameip.si : icmp_seq=1 ttl=64 time=1.05 ms
64 bytes from sameip.si : icmp_seq=2 ttl=64 time=0.468 ms

[server] ~#  systemctl restart keepalived
Redirecting to /bin/systemctl restart keepalived.service

- port starts responding 

[client] ~ # nc -v sameip.si 143
Connection to sameip.si port 143 [tcp/imap] succeeded!
* OK IMAP4 ready
quit

**To Reproduce**

Random occurrence without issues in system logs. No keepalived failover is happening, there isn't any fail2ban ipset blocking IP (tried with disabled firewalld and fail2ban). This is repeatable when keepalived failover happens one hop-up
on a firewall and is resolvable with restarting  keepalived on hop-down where IP is configured.

**Expected behavior**
At least some system (kernel,openvswitch,keepalived) errors in system log.

**Keepalived version**

Keepalived v2.1.5 (07/13,2020)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.8.0
Running on Linux 5.10.13-200.fc33.x86_64 #1 SMP Thu Feb 4 14:54:51 UTC 2021

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstated

Config options:  NFTABLES LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE ...

**Distro (please complete the following information):**
 - Fedora
 - Version 33
 - Architecture x86_64

**Details of any containerisation or hosted service (e.g. AWS)**

**Configuration file:**
cat /etc/keepalived/keepalived.conf
! Configuration File for keepalived

global_defs {
	notification_email {
		sysadmin@domain.si
	}

	enable_script_security
	script_user root

	notification_email_from courier1@domain.si
	smtp_server localhost
	smtp_connect_timeout 30

	router_id mx1.domain.si
}

vrrp_sync_group domain.si { 
	group { 
		#imap.vlan242.domain.si
		vlan103.domain.si 
		vlan242.domain.si 
		vlan102.domain.si
		#smtp.vlan242.domain.si
	} 

	notify_master "/usr/libexec/keepalived/primary-backup.sh primary"
	notify_backup "/usr/libexec/keepalived/primary-backup.sh backup"
	notify_fault "/usr/libexec/keepalived/primary-backup.sh fault"
} 

vrrp_instance vlan103.domain.si {
	state MASTER
	interface vrrp0
	virtual_router_id 1
	priority 150
	advert_int 1
	garp_master_delay 1

	use_vmac
	vmac_xmit_base

	authentication {
		auth_type PASS
		auth_pass *****
	}
	virtual_ipaddress {
		172.16.103.25/24 dev vlan103-ha
	}
	smtp_alert
}

vrrp_instance vlan242.domain.si {
	state MASTER
	interface vrrp0
	virtual_router_id 2
	priority 150
	advert_int 1
	garp_master_delay 1

	use_vmac
	vmac_xmit_base

	authentication {
		auth_type PASS
		auth_pass *****
	}
	virtual_ipaddress {
		## ISP PA IPv4: XXX.XXX.XXX.128/26
		## ISP PA-DMZ2 VLAN: XXX.XXX.XXX.144/28
		XXX.XXX.XXX.146/28 dev isp-v242-ha
	}
	smtp_alert
}

vrrp_instance smtp.vlan242.domain.si {
	state MASTER
	interface vrrp0
	virtual_router_id 4
	priority 150
	advert_int 1
	garp_master_delay 1

	use_vmac
	vmac_xmit_base

	authentication {
		auth_type PASS
		auth_pass *****
	}
	virtual_ipaddress {
		# ISP PA IPv4: XXX.XXX.XXX.128/26
		# ISP PA-DMZ2 VLAN: XXX.XXX.XXX.144/28
		XXX.XXX.XXX.149/28 dev isp-v242-ha1
	}
	smtp_alert

	track_interface {
		isp-v242-ha1 weight -2
	}
}

vrrp_instance imap.vlan242.domain.si {
	state MASTER
	interface vrrp0
	virtual_router_id 5
	priority 150
	advert_int 1
	garp_master_delay 1

	use_vmac
	vmac_xmit_base

	authentication {
		auth_type PASS
		auth_pass *****
	}
	virtual_ipaddress {
		# ISP PA IPv4: XXX.XXX.XXX.128/26
		# ISP PA-DMZ2 VLAN: XXX.XXX.XXX.144/28
		XXX.XXX.XXX.150/28 dev isp-v242-ha2
	}
	smtp_alert

	track_interface {
		isp-v242-ha2 weight -2
	}
}

vrrp_instance vlan102.domain.si {
	state MASTER
	interface vrrp0
	virtual_router_id 3
	priority 150
	advert_int 1
	garp_master_delay 1

	use_vmac
	vmac_xmit_base

	authentication {
		auth_type PASS
		auth_pass *****
	}
	virtual_ipaddress {
		192.168.102.25/24 dev vlan102-ha
	}
	smtp_alert
}

**Notify and track scripts**

None.

**System Log entries**
Nothing at time of an error.

**Did keepalived coredump?**
No.

**Additional context**

**Comment by pqarmitage** [comment]
keepalived adds and removes VIPs as needed (i.e. when a VRRP instance becomes master or backup). Once keepalived has added an IP address, it is than handled by the kernel like any other configured IP address, and keepalived has no involvement in the packet handling in relation to that address, and it has no knowledge or involvement at a protocol (TCP/UDP) or port level.

When you restart keepalived the VIPs are removed, and then re-added to the system, so that could reset any problem being caused in relating to the VIP.

Unfortunately you will need to look elsewhere for the cause of your problem since keepalived cannot be the cause of a problem of some ports working on an IP address and other ports not working.

**Comment by stfast** [comment]
As stated in doc/source/software_design.rst

    net.ipv4.conf.all.arp_ignore = 1
    net.ipv4.conf.all.arp_announce = 1

solves a problem on IP destination.

I recommend myself next time :-)
