### ISSUE TITLE
why change  the master/standby states , the network was interrupted for more than 5 minutes？

### ISSUE THREAD

**Issue by wanghui076020** [acassen/keepalived#1878]
_Support requests should be sent via_ https://groups.io/g/keepalived-users

we have a keepalived server,when master node power off,the virtual ip is bound to another node.but we try to ping virtual ip,but could not establish connection for 5 minutes。

**Keepalived version**
keepalived-2.0.20-16.h3.eulerosv2r9.x86_64

**Distro (please complete the following information):**
Linux eSight-cluster-01 4.18.0-147.5.1.2.h340.eulerosv2r9.x86_64 #1 SMP Sat Jan 30 09:00:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Details of any containerisation or hosted service (e.g. AWS)**

**Configuration file:**
! Configuration File for keepalived
global_defs {
    router_id LVS_DEVEL_1_group_153  #unique identification
    script_user ossadm
}

vrrp_instance LVS_HW {
    state BACKUP
    interface eth0      #maintenance iface
    virtual_router_id 153     #set vrrd
    priority 1     #priority,higher will be master
    advert_int 1     #advert interval s
    nopreempt        # no preempt when all started state is not master
    virtual_ipaddress {     #VIP
    #-----------------ipflag-----------------
        {DIP}/23  dev eth0   label eth0:lvs_dip
        {VIP}/23  dev eth0   label eth0:lvs
    } #END_virtual-_-Ipaddress
    virtual_ipaddress_excluded {     #VIP IPv6
    #-----------------ipv6flag-----------------
    } #END_virtual-_-Ipv6address
    track_script {    #declare script
    }
    notify_master "/opt/oss/manager/apps/**/lvs_handler.sh to_master"
    notify_backup "/opt/oss/manager/apps/**lvs_handler.sh to_backup"

    unicast_peer {
    #-----------------unicastflag-----------------
        {IP1}
        {IP2}
    }

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started, if applicable

**Additional context**

**Comment by wanghui076020** [comment]
![image](https://user-images.githubusercontent.com/13825517/111562241-d1ef4b80-87d0-11eb-8b53-3baa01cb2ad7.png)

**Comment by popinjack** [comment]
what's your problem？What does the network was interrupted mean for more than 5 minutes

**Comment by pqarmitage** [comment]
What do the system logs show about when the backup became master?

When the problem occurs, is the VIP configured on the new master (output of `ip address show eth0`)?

What can you see using tcpdump/wireshark?

Does the solution to https://github.com/acassen/keepalived/issues/1876 help?

**Comment by wanghui076020** [comment]
Thanks all,The Problem is solved. The Reason is that broadband remote access server(BRAS) services are deployed .When the floatIp   was changed to standby node, the BRAS gateway would restore floatIp for 3-10mins.
