### ISSUE TITLE
"notify" script sends stop while being in sync_group configuration

### ISSUE THREAD

**Issue by MikhaylovOA** [acassen/keepalived#1879]
**Describe the bug**
While "notify" script only appears in sync_group, keepalived still sends STOP to script. Which should not be possible according to documentation.

**To Reproduce**
Using config below and stopping service via systemctl.

**Expected behavior**
keepalived sends only "MASTER"|"BACKUP"|"FAULT" to script accordingly and sends nothing on stopping service.

**Keepalived version**
Keepalived v2.0.18 (unknown)

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.9.189
Running on Linux 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3st1 (2019-09-12)

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --enable-dbus --enable-log-file --enable-snmp-vrrp --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-json --with-init=systemd build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/root/build/keepalived/keepalived=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  LIBIPTC LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH JSON OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS FILE_LOGGING LOG_FILE_APPEND

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV RTA_VIA FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Distro:**
 - Name: Debian
 - Version: 9
 - Architecture: x86_64

**Configuration file:**
global_defs {
  enable_dbus
}
vrrp_sync_group 0 {
  notify "/etc/keepalived/scripts/notify_common"
  group {
    eth0_1
    eth1_2
  }
}
vrrp_instance eth0_1 {
  interface eth0
  virtual_routes {
    src 172.16.100.100 0.0.0.0/0 via 172.16.100.1 dev eth0
  }
  virtual_ipaddress {
    172.16.100.100/24 label eth0:900
  }
  nopreempt
  priority 50
  advert_int 3
  garp_master_refresh 5
  virtual_router_id 1
}
vrrp_instance eth1_2 {
  interface eth1
  virtual_ipaddress {
    192.168.100.1/24 label eth1:900
  }
  nopreempt
  priority 50
  advert_int 3
  garp_master_refresh 5
  virtual_router_id 2
}

**Notify and track scripts**
root@Hub1-n2:~# cat /etc/keepalived/scripts/notify_common
#!/bin/bash

echo $3 > /root/state
exit 0

**Comment by pqarmitage** [comment]
Apologies for not having responded to you message on keepalived-users@groups.io already.

I will investigate this later, but as you have suggested it may well be a documentation error. The comment "note: STOP is only applicable to instances" was added to the documentation when there was a general update to the documentation rather than when the code handling STOP was updated.

**Comment by pqarmitage** [comment]
The man page was incorrect. Commit acb5337 updates it so that it no longer says that STOP is not sent.
