### ISSUE TITLE
keepalived complains: (Line NNN) Unknown keyword 'vrrp_garp_extra_if' (v 2.2.2) - should be vrrp_vmac_garp_intvl ?

### ISSUE THREAD

**Issue by msoltyspl** [acassen/keepalived#1887]
**Describe the bug**
keepalived complains: (Line NNN) Unknown keyword 'vrrp_garp_extra_if' (v 2.2.2)

Greping the sources finds that string absolutely nowhere besides the man page - but looking at the commit that added this option it seems that the intention was to name it `vrrp_vmac_garp_intvl` - its handler takes `all` and numerical value, as explained in the manual. Same goes for per-instance option (garp_extra_if vs. vmac_garp_intvl).

```
git show 3dcd13cacfe099148fdd6aaecccccd2824171f32
vim keepalived/vrrp/vrrp_parser.c
```

**Keepalived version**
```
Keepalived v2.2.2 (03/05,2021)

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.10.13
Running on Linux 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000
Distro: Arch Linux

configure options: --prefix=/usr --sysconfdir=/etc --sbindir=/usr/bin --localstatedir=/var --runstatedir=/run CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now CPPFLAGS=-D_FORTIFY_SOURCE=2

Config options:  LIBIPSET_DYNAMIC NFTABLES LVS VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT INIT=systemd SYSTEMD_NOTIFY

System options:  VSYSLOG MEMFD_CREATE IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA IPTABLES NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK
```

**Distro (please complete the following information):**
 - Name: Arch
 - Version: n/a, rolling release distro
 - Architecture: x86_64

**Configuration file:**
```
global_defs {
  enable_script_security
  max_auto_priority
  vrrp_garp_extra_if    120
  vrrp_version         3
}

vrrp_instance test {
  interface               qeth60
  promote_secondaries
  use_vmac                float60
  state                   MASTER
  virtual_router_id       1
  priority                100
  advert_int              1
  accept

  virtual_ipaddress {
    192.168.60.150/24 noprefixroute
  }
}

```

**Comment by pqarmitage** [comment]
@msoltyspl Many thanks for the bug report. I can't remember what my intention in respect of the keyword names was when I added this feature, but I think I probably started with `vmac_garp_intvl` and then changed it to `garp_extra_if` - certainly the latter names seem more sensible to me.

Commit 974a7eb adds `vrrp_garp_extra_if` and `garp_extra_if` keywords as synonyms for `vrrp_vmac_garp_intvl` and `vmac_garp_intvl` and marks the `vrrp_vmac_garp_intvl` and `vmac_garp_intvl` keywords as deprecated.
