### ISSUE TITLE
Healthchecker: MISC_CHECK in the last virtual_server makes the healthchecker respawn like hell

### ISSUE THREAD

**Issue by TomGudman** [acassen/keepalived#189]
Hi,

## Context
We discovered that having the **last** virtual server with **more than one** MISC_CHECK makes keepalived healthchecker process crashing forever. It will keep respawning. Starting keepalived with -R makes keepalived crash straight away with a segfault. Rolling back version we found 1.2.12 is fine but 1.2.13 seems to introduce the bug and this is true across all newer versions up to 1.2.19.

## Environment
- Centos 6.6 or Centos 6.7
- Keepalived 1.2.13 to 1.2.19

## How to reproduce
1. You need at least 2 virtual server definitions in keepalived.conf
2. The second virtual server definition needs 2 real server with a MISC_CHECK each
3. Start keepalived (keepalived -D -d -S 0)

## Consequences
1. Keepalived does not stop well, it does not clean the ipvs table anymore (requires a ipvsadm -C)
2. Log files will fill very quickly ;-)
```
Oct 21 13:16:41 xxx.x.x Keepalived[27599]: Healthcheck child process(28167) died: Respawning
Oct 21 13:16:41 xxx.x.x Keepalived[27599]: Starting Healthcheck child process, pid=28168
```

## Workaround
1. Ensure the **last** virtual_server definition does **not** contain real_server with MISC_CHECK
2. If that's the case, move the virtual_server higher in the file. 

## Configuration sample
```
virtual_server 1.2.3.10 80 {
[..]
}

virtual_server 1.2.3.4 587 {
    # LVS
    lb_algo sh
    lb_kind DR
    protocol TCP
    # Check every 15 secs
    delay_loop 15

    real_server 1.2.3.3 587 {
        weight 256
        MISC_CHECK {
		misc_path '/bin/true'
	}
    }
    real_server 1.2.3.7 587 {
        weight 256
        MISC_CHECK {
		misc_path '/bin/true'
	}
    }
}
```

**Comment by pqarmitage** [comment]
This was resolved by commit 586bb1b .
