### ISSUE TITLE
Keepalived doesn't work on CentOS 8.

### ISSUE THREAD

**Issue by hack3rcon** [acassen/keepalived#1891]
Hello,
I used [Keepalived](https://tecadmin.net/ip-failover-setup-using-keepalived-on-centos-redhat/) tutorial to configure Keepalived on two CentOS web servers:
Server 1:  192.168.56.7
Server 2:  192.168.56.9
Virtual IP: 192.168.56.110
And after it, I added below Firewalld rule:

```
# firewall-cmd --add-rich-rule='rule protocol value="vrrp" accept' --permanent
# firewall-cmd --reload
```
But I can't ping my Virtual IP address:
```
# ping 192.168.56.110
PING 192.168.56.110 (192.168.56.110) 56(84) bytes of data.
ping: sendmsg: Operation not permitted
ping: sendmsg: Operation not permitted
ping: sendmsg: Operation not permitted
ping: sendmsg: Operation not permitted
ping: sendmsg: Operation not permitted
```
And cURL doesn't show anything too:
`# curl -l 192.168.56.110`
I used "ip addr show NIC" command and Virtual IP address is assigned to my NIC, but why it doesn't work?

Thank you.

**Comment by pqarmitage** [comment]
@hack3rcon Unfortunately you haven't provided any of the necessary information to ascertain what is happening here.

You will need to provide:

1. A copy of your keepalived configurations
2. The output of `keepalived -v`
3. What version of CentOS you are using
4. The output of `ip addr show`
5. The output of `iptables -nvL` and `nft list ruleset`
6. The keepalived logs from the two servers
7. Which server you are running the ping command on

**Comment by pqarmitage** [comment]
Closing due to no response for over 1 week. If further information is provided this issue can be reopened.
