### ISSUE TITLE
detail log for vrrp master's mac address

### ISSUE THREAD

**Issue by Archer-Code** [acassen/keepalived#1897]
Is there a detailed log that records the MAC address of a VRRP master node? Due to application scenario limitations, such logs are required to accurately locate faults. We can upgrade the version of keepalived.

**Keepalived version**
keepalived -v 
Keepalived v2.0.6 (07/23,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.19.36
Running on Linux 4.19.36-vhulk1907.1.0.h988.eulerosv2r8.aarch64 #1 SMP Fri Mar 5 09:59:53 UTC 2021

configure options: --build=aarch64-Huawei-linux-gnu --host=aarch64-Huawei-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --enable-snmp-rfc --enable-sha1 --enable-log-file=yes --with-init=systemd build_alias=aarch64-Huawei-linux-gnu host_alias=aarch64-Huawei-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fasynchronous-unwind-tables -fstack-clash-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 FILE_LOGGING LOG_FILE_APPEND

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Distro (please complete the following information):**
 - Name centos7
 - Version 
 - Architecture x86_64

**Configuration file:**
vrrp_instance VR_1 {
    state BACKUP
    interface eth0
    virtual_router_id 1
    priority 50
    garp_master_delay 60
    nopreempt
    advert_int 2
    track_interface {
        eth0
    }
    virtual_ipaddress {
        fe80::b9fe:b9fe/64 dev eth0
    }
}

**Notify and track scripts**
None

**System Log entries**
2021-04-20T14:55:58.558716+08:00|info|Keepalived_vrrp[85691]|Registering Kernel netlink reflector
2021-04-20T14:55:58.558897+08:00|info|Keepalived_vrrp[85691]|Registering Kernel netlink command channel
2021-04-20T14:55:58.559083+08:00|info|Keepalived_vrrp[85691]|(VR_1) Ignoring track_interface eth0 since own interface
2021-04-20T14:55:58.559131+08:00|info|Keepalived_vrrp[85691]|Registering gratuitous NDISC shared channel
2021-04-20T14:55:58.559751+08:00|info|Keepalived_vrrp[85691]|(VR_1) Entering BACKUP STATE (init)

**Comment by pqarmitage** [comment]
keepalived does not receive any layer 2 information. When using IPv4 it receives the IP header, but it does not receive the IP header when using IPv6. When keepalived receives a message with recvmsg() it receives that sender's IP address, but not the sender's layer 2 address.
