### ISSUE TITLE
Wrong version in 1.2.19 spec file

### ISSUE THREAD

**Issue by btpier** [acassen/keepalived#192]
In the 1.2.19 tarball, the keepalived.spec.in file has the Version still set to 1.2.18:

Summary: HA monitor built upon LVS, VRRP and services poller
Name: keepalived
Version: 1.2.18
Release: 5

This makes the rpm build fail with the previously closed unpackaged files issue. Changing it to 1.2.19 allows the rpm to build cleanly.

**Comment by acassen** [comment]
fixed
