### ISSUE TITLE
Confusing/misleading documentation of quoted strings?

### ISSUE THREAD

**Issue by henkdswiss** [acassen/keepalived#1922]
I think something is wrong in:
https://github.com/acassen/keepalived/blob/c2417780e4bc5d7c1177605c637bfb66f92e31f0/doc/man/man5/keepalived.conf.5.in#L97-L106

The example shows a string where the double quote characters are followed by whitespace, yet the explanation seems to state that they are not and therefore the whole thing is treated as one single string.

```
"abcd" efg h jkl "mnop"
```
should probably be 
```
"abcd"efg h jkl "mnop"
```
for the surrounding explanation to make sense.

Can you please check if you see what I mean? Off the top of my hat I can’t explain it any better and I’m uncertain it’s clear what I mean …

**Comment by pqarmitage** [comment]
Yes, I absolutely agree that this is confusing, to say the least. The first and last `"`s are part of delimiting the example, whereas the `"` before `e` and `m` are part of the quoted string.

Commit 80d8fc3 updates the description, and I hope it is clearer now.

Many thanks for reporting this.
