### ISSUE TITLE
/tmp/keepalived.data  is not suitable for multi instance mode

### ISSUE THREAD

**Issue by Cambrian-Lee** [acassen/keepalived#1928]
**Is your feature request to resolve a problem or provide enhanced functionality? Please describe.**

As described in the official document:
"keepalived reacts to a set of signals.  You can send a signal to the parent"
```shell
kill -SIGNAL $(cat /run/keepalived.pid)
```
if I run a multi-instance mode on single keepalived.conf, just like:
```
! Configuration File for keepalived

#### visit https://www.keepalived.org/manpage.html for detail


global_defs {
    router_id HA_168_38_103_132
    script_user root
}

vrrp_script check_process {
    script "/home/keepalived/etc/test/keepalived_process_check.sh status"
    interval 10
    fall 2
    rise 1
    weight 10
    user root
}

vrrp_instance test {
    state BACKUP
    nopreempt
    interface eno2
    track_interface {
    eno2
    }
    unicast_peer {
    168.38.103.132
    168.38.103.136
    }
    virtual_router_id 140
    priority 140
    virtual_ipaddress {
    168.38.103.140/24 brd 168.38.103.255 dev eno2 scope global label eno2:test
    }

    track_script {
    check_process
    }
    notify_master "/home/keepalived/etc/test/notify_process.sh master" root
    notify_backup "/home/keepalived/etc/test/notify_process.sh backup" root
    notify_fault  "/home/keepalived/etc/test/notify_process.sh fault" root
}

vrrp_instance ljf {
    state BACKUP
    nopreempt
    interface eno2
    track_interface {
    eno2
    }
    unicast_peer {
    168.38.103.132
    168.38.103.136
    }
    virtual_router_id 141
    priority 140
    virtual_ipaddress {
    168.38.103.141/24 brd 168.38.103.255 dev eno2 scope global label eno2:ljf
    }

    track_script {
    check_process
    }
    notify_master "/home/keepalived/etc/test/notify_process.sh master" root
    notify_backup "/home/keepalived/etc/test/notify_process.sh backup" root
    notify_fault  "/home/keepalived/etc/test/notify_process.sh fault" root
}
``` 
when I send a signal to the parent, /tmp/keepalived.data generated,  details of two of instance(test, ljf) will be printed.

However, if I use different keepalived.conf to create keepalived instance, just like:
configuration file 1：
```
! Configuration File for keepalived

#### visit https://www.keepalived.org/manpage.html for detail
instance test

global_defs {
    router_id HA_168_38_103_132
    script_user root
}

vrrp_script check_process {
    script "/home/keepalived/etc/test/keepalived_process_check.sh status"
    interval 10
    fall 2
    rise 1
    weight 10
    user root
}

vrrp_instance test {
    state BACKUP
    nopreempt
    interface eno2
    track_interface {
    eno2
    }
    unicast_peer {
    168.38.103.132
    168.38.103.136
    }
    virtual_router_id 140
    priority 140
    virtual_ipaddress {
    168.38.103.140/24 brd 168.38.103.255 dev eno2 scope global label eno2:test
    }

    track_script {
    check_process
    }
    notify_master "/home/keepalived/etc/test/notify_process.sh master" root
    notify_backup "/home/keepalived/etc/test/notify_process.sh backup" root
    notify_fault  "/home/keepalived/etc/test/notify_process.sh fault" root
}

```
configuration file 2：
```
! Configuration File for keepalived

#### visit https://www.keepalived.org/manpage.html for detail
instance ljf

global_defs {
    router_id HA_168_38_103_132
    script_user root
}

vrrp_script check_process {
    script "/home/keepalived/etc/ljf/keepalived_process_check.sh status"
    interval 10
    fall 2
    rise 1
    weight 10
    user root
}

vrrp_instance ljf {
    state BACKUP
    nopreempt
    interface eno2
    track_interface {
    eno2
    }
    unicast_peer {
    168.38.103.132
    168.38.103.136
    }
    virtual_router_id 141
    priority 140
    virtual_ipaddress {
    168.38.103.141/24 brd 168.38.103.255 dev eno2 scope global label eno2:ljf
    }

    track_script {
    check_process
    }
    notify_master "/home/keepalived/etc/test/notify_process.sh master" root
    notify_backup "/home/keepalived/etc/test/notify_process.sh backup" root
    notify_fault  "/home/keepalived/etc/test/notify_process.sh fault" root
}
```

there will be different parent for each instance:
```shell
root     29515     1  0 17:10 ?        00:00:00 /usr/sbin/keepalived -D -d -f /home/keepalived/etc/test/keepalived.conf
root     29516 29515  0 17:10 ?        00:00:00 /usr/sbin/keepalived -D -d -f /home/keepalived/etc/test/keepalived.conf
root     30259     1  0 17:10 ?        00:00:00 /usr/sbin/keepalived -D -d -f /home/keepalived/etc/ljf/keepalived.conf
root     30260 30259  0 17:10 ?        00:00:00 /usr/sbin/keepalived -D -d -f /home/keepalived/etc/ljf/keepalived.conf
```
if I send a signal to each parent, only one file: /tmp/keepalived.data generated, old files will be overwritten by new ones, details files can not exist at the sametime for each instance

**Describe the solution you would like**
when send a signal to each parent of instance, add a suffix on previous file: /tmp/keepalived.data_${instance}

**Describe alternatives you have considered**
A clear and concise description of any alternative solutions or features you have considered.

**Would the feature request be of benefit only to you, or is it more generally applicable?**
the feature will be useful for some monitor programs, users run multi-instance mode through different keepalived.conf for the purpose of isolation of different programs. monitor programs can check the master/backup status By identifying different files(/tmp/keepalived.data_${instance})，if  master/backup status get changed or abnormal, send warning messages.

**Keepalived version**
```shell
[root@localhost home]# /usr/sbin/keepalived -v
Keepalived v2.0.10 (11/12,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.0
Running on Linux 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Fri Apr 24 15:25:09 CST 2020

```

**Additional context**
Add any other context about the feature request here.

**Comment by pqarmitage** [comment]
I should first mention that the keepalived*.data files are designed for debugging keepalived, and we do not guarantee to maintain the current format of the files.

A preferred way of tracking the master/backup status of each VRRP instance would be to use a notify_fifo (using notify_master/notify_backup scripts is not reliable since if there is a very quick transition BACKUP -> MASTER -> BACKUP for example, the order of execution of the scripts is not guaranteed), and to record the latest state in a file.

Commit 540d043 adds a new `global_defs` keyword `data_use_instance` which makes keepalived include the instance name (and also network namespace name if specified) in the name of the dump files. The filename format is /tmp/keepalived.${instance}.data, /tmp/keepalived_parent.${instance}.data etc, or /tmp/keepalived.${network_namespace}_${instance}.data etc if a network namespace is also configured.
