### ISSUE TITLE
Add new track_script to instance and reload when state is master, then state changes to backup->master(Openwrt, keepalived v2.0.16)

### ISSUE THREAD

**Issue by fvpuaguv** [acassen/keepalived#1941]
**Describe the bug**
hi,
I have a question and hope to get your help 

I run keepalived on the openwrt system, and device state is master. 
I added a new vrrp_script configuration to vrrp_instance, and reload, then the state changed to backup.
Different scripts have the same situation
Is this state change normal?  Why does the state switch to backup after adding a script?
I hope its state will always be master 

log:
Keepalived[5490]: Reloading ...
Keepalived[5490]: Opening file '/tmp/keepalived.conf'.
Keepalived_vrrp[5508]: Reloading
Keepalived_vrrp[5508]: Opening file '/tmp/keepalived.conf'.
Keepalived_vrrp[5508]: VRRP_Script(cpu_mem_disk) considered successful on reload
Keepalived_vrrp[5508]: Unable to load magic database
Keepalived_vrrp[5508]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Keepalived_vrrp[5508]: (abc) ip address 2.2.2.2/24 dev br-lan, no longer exist
Keepalived_vrrp[5508]: Netlink: error: Invalid argument, type=RTM_NEWROUTE(24), seq=1626922788, pid=0
Keepalived_vrrp[5508]: VRRP_Script(wan_status) succeeded
Keepalived_vrrp[5508]: (abc) Entering BACKUP STATE

thanks

**Comment by pqarmitage** [comment]
@fvpuaguv Could you please provide copies of your config file both before and after the reload. Please also provide copies of any scripts (including the cpu_mem_disk and wan_status scripts), so that we can attempt to reproduce the problem.

**Comment by fvpuaguv** [comment]
hi,
1. openwrt uci config file before modified:
config global_defs
        option router_id '12F0'

config vrrp_script 'cpu_mem_disk'
        option name 'cpu_mem_disk'
        option script '/usr/sbin/cpu_mem_disk'
        option interval '5'
        option weight '0'
        option fall '10'
        option rise '5'

config vrrp_script 'wan_status'
        option name 'wan_status'
        option script '/usr/sbin/wan_status'
        option interval '5'
        option weight '0'
        option fall '10'
        option rise '5'

config ipaddress
        option name 'ip1'
        option device 'br-lan'
        option address '2.2.2.2/24'
        option scope 'global'

config route
        option name 'rt1'
        option address '1.2.3.4/24'
        option gateway '2.2.2.2'
        option device 'br-hb'

config vrrp_instance
        option name 'abc'
        option virtual_router_id '123'
#       list track_script 'cpu_mem_disk'
#       list track_script 'wan_status'
        option priority '12'
        option nopreempt '1'
        option state 'BACKUP'
        list virtual_ipaddress 'ip1'
        list virtual_routes 'rt1'
        option interface 'br-hb'

2. keepalive  config file before modified:
global_defs {
        router_id 12F0
}

static_ipaddress {
}

static_routes {
}

vrrp_script cpu_mem_disk {
        script /usr/sbin/cpu_mem_disk
        interval 5
        weight 0
        fall 10
        rise 5
}

vrrp_script wan_status {
        script /usr/sbin/wan_status
        interval 5
        weight 0
        fall 10
        rise 5
}

vrrp_instance abc {
        state BACKUP
        interface br-hb
        virtual_router_id 123
        priority 12
        nopreempt
        notify_backup "/bin/busybox env -i ACTION=NOTIFY_BACKUP TYPE=INSTANCE NAME=abc /sbin/hotplug-call keepalived"
        notify_master "/bin/busybox env -i ACTION=NOTIFY_MASTER TYPE=INSTANCE NAME=abc /sbin/hotplug-call keepalived"
        notify_fault "/bin/busybox env -i ACTION=NOTIFY_FAULT TYPE=INSTANCE NAME=abc /sbin/hotplug-call keepalived"
        notify_stop "/bin/busybox env -i ACTION=NOTIFY_STOP TYPE=INSTANCE NAME=abc /sbin/hotplug-call keepalived"
        virtual_ipaddress {
                2.2.2.2/24 dev br-lan scope global
        }
        virtual_routes {
                1.2.3.4/24 via 2.2.2.2 dev br-hb
        }
}

3.  openwrt uci config file before reload:
config global_defs
        option router_id '12F0'

config vrrp_script 'cpu_mem_disk'
        option name 'cpu_mem_disk'
        option script '/usr/sbin/cpu_mem_disk'
        option interval '5'
        option weight '0'
        option fall '10'
        option rise '5'

config vrrp_script 'wan_status'
        option name 'wan_status'
        option script '/usr/sbin/wan_status'
        option interval '5'
        option weight '0'
        option fall '10'
        option rise '5'

config ipaddress
        option name 'ip1'
        option device 'br-lan'
        option address '2.2.2.2/24'
        option scope 'global'

config route
        option name 'rt1'
        option address '1.2.3.4/24'
        option gateway '2.2.2.2'
        option device 'br-hb'

config vrrp_instance
        option name 'abc'
        option virtual_router_id '123'
        list track_script 'cpu_mem_disk'
#       list track_script 'wan_status'
        option priority '12'
        option nopreempt '1'
        option state 'BACKUP'
        list virtual_ipaddress 'ip1'
        list virtual_routes 'rt1'
        option interface 'br-hb'

4. keepalive config file before reload:
global_defs {
        router_id 12F0
}

static_ipaddress {
}

static_routes {
}

vrrp_script cpu_mem_disk {
        script /usr/sbin/cpu_mem_disk
        interval 5
        weight 0
        fall 10
        rise 5
}

vrrp_script wan_status {
        script /usr/sbin/wan_status
        interval 5
        weight 0
        fall 10
        rise 5
}

vrrp_instance abc {
        state BACKUP
        interface br-hb
        virtual_router_id 123
        priority 12
        nopreempt
        notify_backup "/bin/busybox env -i ACTION=NOTIFY_BACKUP TYPE=INSTANCE NAME=abc /sbin/hotplug-call keepalived"
        notify_master "/bin/busybox env -i ACTION=NOTIFY_MASTER TYPE=INSTANCE NAME=abc /sbin/hotplug-call keepalived"
        notify_fault "/bin/busybox env -i ACTION=NOTIFY_FAULT TYPE=INSTANCE NAME=abc /sbin/hotplug-call keepalived"
        notify_stop "/bin/busybox env -i ACTION=NOTIFY_STOP TYPE=INSTANCE NAME=abc /sbin/hotplug-call keepalived"
        virtual_ipaddress {
                2.2.2.2/24 dev br-lan scope global
        }
        virtual_routes {
                1.2.3.4/24 via 2.2.2.2 dev br-hb
        }
        track_script {
                cpu_mem_disk
        }
}
5. cpu_mem_disk script:
#!/bin/sh
DEBUG="logger -t keepalive -p debug "
ERROR="logger -t keepalive -p err "
exit 0


thanks

**Comment by fvpuaguv** [comment]
openwrt /etc/init.d/keepalive start and reload code:
```
reload_service() {
        process_config
        #SIGHUP is used by keepalived to do init.d reload
        procd_send_signal keepalived
}

start_service() {
    prepare_start
        procd_open_instance
        procd_set_param command /usr/sbin/keepalived
        procd_append_param command -n # don't daemonize, procd will handle that for us
        procd_append_param command -f "$KEEPALIVED_CONF"
        procd_append_param command -D

        process_config

        # set auto respawn behavior
        procd_set_param respawn
        procd_close_instance
}
```

**Comment by pqarmitage** [comment]
I will need to try this later, but a couple of immediate comments:

1) the virtual_route will not work for two reasons. 1.2.3.4/24 is not valid, if you want /24 it needs to be 1.2.3.0/24. Also 2.2.2.2 is on interface br-lan, and so you should either not specify `dev-hb` for the route, or specify `dev br-lan`.
2) What is the purpose of the  cpu_mem_disk script - it doesn't appear to do anything.

**Comment by fvpuaguv** [comment]
Thank you very much, I have corrected the question you mentioned, and the virtual IP and routing have taken effect
```
16: br-lan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether cc:d3:9d:9e:12:ec brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 brd 192.168.1.255 scope global br-lan
       valid_lft forever preferred_lft forever
    inet 2.2.2.2/24 scope global br-lan
       valid_lft forever preferred_lft forever

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.32.254  0.0.0.0         UG    0      0        0 br-wan
1.1.1.0         0.0.0.0         255.255.255.0   U     0      0        0 br-hb
1.2.3.0         2.2.2.1         255.255.255.0   UG    0      0        0 br-lan
```

The purpose of the script is to detect resource usage(cpu/memory/disk)
In order to prove that the problem has nothing to do with the specific content of the script, I deleted the content in the script

**Comment by pqarmitage** [comment]
@fvpuaguv Many apologies for the long delay in implementing this useful suggestion; I didn't find it easy to find the best way to implement it, and the solution only occurred to me a couple of weeks ago. It has also needed quite a lot of testing of a wide range of scenarios.

Anyway, commit 1ebdb27 now implements this suggestion.
