### ISSUE TITLE
Mutually exclusive vrrp instances — avoid split brain

### ISSUE THREAD

**Issue by gurubert** [acassen/keepalived#195]
Hi,

is it possible to configure keepalived so that two vrrp instances will not become master on the same host?

**Comment by pqarmitage** [comment]
Their may be some really weird and wonderful way of doing this, but there doesn't appear to be a standard way of doing it.

One possibility might be the following.
Suppose you have instances A and B. If you create a sub interface of the interface B is on, say a macvlan, and bring it up before starting keepalived, and in the configuration make instance B track that interface, and in the notify_master script for instance A set the interface down, and in the notify_backup and notify_fault scripts set the interface up, then instance B should go down whenever instance A is up.
This hasn't been tested; this is provided as an idea that MIGHT work.

Can you provide a use case for what you want to achieve. If it is of more general use, it might be possible to add the functionality to keepalived.

**Comment by acassen** [comment]
After discussion with Quentin, we decided to close this issue since we never get more inputs.

Thanks,
