### ISSUE TITLE
manpage does not mention enable_snmp_keepalived keyword

### ISSUE THREAD

**Issue by kingsleytart** [acassen/keepalived#1961]
**Describe the bug**
The man5 page on keepalived.conf mentions a series of keywords that are available if keepalived has been built with SNMP support, ie:

-    snmp_socket
-    enable_snmp_vrrp
-    enable_snmp_checker
-    enable_snmp_rfc
-    enable_snmp_rfcv2
-    enable_snmp_rfcv3
-    enable_traps

But it doesn't mention **enable_snmp_keepalived** which was the actual keyword my setup (on Debian 10) needed in order for it to work. I only chanced upon it in someone's example config after 2 days of googling.

**To Reproduce**
man keepalived.conf

**Keepalived version**
v2.0.10

but I can also see here on github that info is missing in the manpage source

**Comment by pqarmitage** [comment]
The reason that `enable_snmp_keepalived` is not mention is that the keyword has been deprecated since keepalived v2.0.0. `enable_snmp_keepalived` enabled the non-RFC SNMP support for the VRRP functionality, but not the checker SNMP support. `enable_snmp_keepalived` suggests that all SNMP functionality should be enabled (i.e. including checker support), which it did not.

`enable_snmp_keepalived` is replaced by `enable_snmp_vrrp` which better describes what the keyword does, and it is included in the keepalived.conf(5) man page.

**Comment by kingsleytart** [comment]
In my installation running keepalived v2.0.10 I already had the following snmp stuff in global_defs:

```    snmp_socket tcp:127.0.0.1:705
    enable_snmp_vrrp
    enable_snmp_checker
    enable_snmp_rfc
    enable_snmp_rfcv2
    enable_snmp_rfcv3
    enable_traps
```

but it didn't work until I added enable_snmp_keepalived.

However I now can't reproduce the issue so I really can't explain what was going on.

So is that a different bug?

Cheers,
Kingsley.

**Comment by pqarmitage** [comment]
The same function handles both "enable_snmp_vrrp" and "enable_snmp_keepalived" and it doesn't check which of the two was used, so it isn't possible to get different behaviour between using one or the other. The only suggestion I can make is that you had a typo?

BTW, v2.0.10 is really quite old now, and it would probably be worth building v2.2.2.

**Comment by kingsleytart** [comment]
Interesting.

Regarding the keepalived version, it's what Debian 10's package manager
installed. I find server maintenance a lot easier if I can just use the
distro's package management to update everything rather than spend half
my time recompiling things.

Are there any pressing reasons to go newer than 2.0.10?

Cheers,
Kingsley.

**Comment by kingsleytart** [comment]
(following on)

I have, however, noticed that if one of the VIPs is already up on the
server when keepalived (2.0.10) starts, it doesn't seem to know about
it, and that VIP can end up being enabled on two hosts in the cluster.

Easy enough to reproduce, eg on a 2 host system:

1. administritavely disable host A, or do something else that makes
keepalived downscore this host and drop the VRRP instance
2. kill -9 keepalived on host B
3. undo what you did in step (1)
4. restart keepalived on host B

Cheers,
Kingsley.
