### ISSUE TITLE
keepalived nopreempt

### ISSUE THREAD

**Issue by edieruby** [acassen/keepalived#198]
I use the nopreempt model, the currently A is  master ,and B is backup, the check script  is check their own tomcat working. when I kill A's tomcat , B change to master and A is backup. 
    And then I kill B's tomcat , the B'log is VRRP_Script(check) failed, at this time A'log is VRRP_Script(check) succeeded.
     A's priority should be higher than B, but B is still master ,didn't has a master selection. 
the right  situation should be B become backup ,and A become master.
    the check script is like this ,when it has vip and tomcat working ,exit 0; has vip and no tomcat, exit 1;
doesn't have vip, exit 0;

**Comment by wangxingge** [comment]
I think you are miss understanding of "nopreempt".

if you want your server A could auto failback when your check script succes, you should set your state to master in your keepalived.conf.
