### ISSUE TITLE
Child (PID 24646) failed to terminate after kill - filling up logs

### ISSUE THREAD

**Issue by Adi-AA** [acassen/keepalived#1989]
**Describe the bug**
Child (PID 24646) failed to terminate after kill on MASTER node
And VRRP_Script(chk_manual_failover) failed (exited with status 1) on backup node. 

**To Reproduce**
Attached all the necessary logs.

**Expected behavior**
The logs are filling up with messages Child (PID 24646) failed to terminate after kill on MASTER node, need to stop these messages and should be able to see the keepalived.log on backup which I dont see currently.

**Keepalived version**
[root@esdfwlbp0003 nginx]# keepalived -v
Keepalived v2.0.18 (07/26,2019)

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-1160.11.1.el7.x86_64 #1 SMP Mon Nov 30 13:05:31 EST 2020

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-lvs --disable-fwmark --disable-snmp --disable-sha1 --with-init=none build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic LDFLAGS=-Wl,-z,relro

Config options:  VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV6_ADVANCED_API RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION VRRP_VMAC IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SCHED_RT SCHED_RESET_ON_FORK
[root@esdfwlbp0003 nginx]#

**Distro (please complete the following information):**
 - Name: [e.g. Fedora, Ubuntu] Linux
 - Version: [e.g. 29]
 - Architecture: [e.g. x86_64]

[root@esdfwlbp0003 nginx]# nginx -V
nginx version: nginx/1.17.3 (nginx-plus-r19)
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details
N/A
**Configuration file:**
[root@esdfwlbp0003 nginx]# cat /etc/keepalived/keepalived.conf
global_defs {
        vrrp_version 3
}

vrrp_script chk_manual_failover {
        script "/usr/libexec/keepalived/nginx-ha-manual-failover"
        interval 10
        weight 50
}

vrrp_script chk_nginx_service {
        script "/usr/libexec/keepalived/nginx-ha-check"
        interval 3
        weight 50
}

vrrp_instance VI_1 {
        interface ens192
        priority 101
        virtual_router_id 51
        advert_int 1
        accept
        garp_master_refresh 5
        garp_master_refresh_repeat 1
        unicast_src_ip 10.162.84.5
        unicast_peer {
                10.162.84.6
        }
        virtual_ipaddress {
                10.162.84.7
                10.162.84.8
                10.162.84.9
                10.162.84.10
                10.162.84.11
                10.162.84.12
                10.162.84.13
                10.162.84.14
                10.162.84.15
                10.162.84.16
                10.162.84.17
                10.162.84.18
                10.162.84.19
                10.162.84.20
                10.162.84.21
                10.162.84.22
                10.162.84.23
                10.162.84.24
                10.162.84.25
                10.162.84.26
                10.162.84.27
                10.162.84.28
                10.162.84.29
                10.162.84.30
                10.162.84.31
                10.162.84.32
                10.162.84.33
                10.162.84.34
                10.162.84.35
                10.162.84.36
                10.162.84.37
                10.162.84.38
                10.162.84.39
                10.162.84.40
                10.162.84.41
                10.162.84.42
                10.162.84.43
                10.162.84.44
                10.162.84.45
                10.162.84.46
                10.162.84.47
                10.162.84.48
                10.162.84.49
                10.162.84.50
                10.162.84.51
                10.162.84.52
                10.162.84.53
                10.162.84.54
                10.162.84.55
                10.162.84.56
                10.162.84.57
                10.162.84.58
                10.162.84.59
                10.162.84.60
                10.162.84.61
                10.162.84.62
                10.162.84.63
                10.162.84.64
                10.162.84.65
                10.162.84.66
                10.162.84.67
                10.162.84.68
                10.162.84.69
                10.162.84.70
                10.162.84.71
                10.162.84.72
                10.162.84.73
                10.162.84.74
                10.162.84.75
                10.162.84.76
                10.162.84.77
                10.162.84.78
                10.162.84.79
                10.162.84.80
                10.162.84.81
                10.162.84.82
                10.162.84.83
                10.162.84.84
                10.162.84.85
                10.162.84.86
                10.162.84.87
                10.162.84.88
                10.162.84.89
                10.162.84.90
                10.162.84.91
                10.162.84.92
                10.162.84.93
                10.162.84.94
                10.162.84.95
                10.162.84.96
                10.162.84.97
                10.162.84.98
                10.162.84.99
                10.162.84.100
                10.162.84.101
                10.162.84.102
                10.162.84.103
                10.162.84.104
                10.162.84.105
                10.162.84.106
                10.162.84.107
                10.162.84.108
                10.162.84.109
                10.162.84.110
                10.162.84.111
                10.162.84.112
                10.162.84.113
                10.162.84.114
                10.162.84.115
                10.162.84.116
                10.162.84.117
                10.162.84.118
                10.162.84.119
                10.162.84.120
                10.162.84.121
                10.162.84.122
                10.162.84.123
                10.162.84.124
                10.162.84.125
                10.162.84.126
                10.162.84.127
                10.162.84.128
                10.162.84.129
                10.162.84.130
                10.162.84.131
                10.162.84.132
                10.162.84.133
                10.162.84.134
                10.162.84.135
                10.162.84.136
                10.162.84.137
                10.162.84.138
                10.162.84.139
                10.162.84.140
                10.162.84.141
                10.162.84.142
                10.162.84.143
                10.162.84.144
                10.162.84.145
                10.162.84.146
                10.162.84.147
                10.162.84.148
                10.162.84.149
                10.162.84.150
                10.162.84.151
                10.162.84.152
                10.162.84.153
                10.162.84.154
                10.162.84.155
                10.162.84.156
                10.162.84.157
                10.162.84.158
                10.162.84.159
                10.162.84.160
                10.162.84.161
                10.162.84.162
                10.162.84.162
                10.162.84.164
                10.162.84.165
                10.162.84.166
                10.162.84.167
                10.162.84.168
                10.162.84.169
                10.162.84.170
                10.162.84.171
                10.162.84.172
                10.162.84.173
                10.162.84.174
                10.162.84.175
                10.162.84.176
                10.162.84.177
                10.162.84.178
                10.162.84.179
                10.162.84.180
                10.162.84.181
                10.162.84.182
                10.162.84.183
                10.162.84.184
                10.162.84.185
                10.162.84.186
                10.162.84.187
                10.162.84.188
                10.162.84.189
                10.162.84.190
                10.162.84.191
                10.162.84.192
                10.162.84.193
                10.162.84.194
                10.162.84.195
                10.162.84.196
                10.162.84.197
                10.162.84.198
                10.162.84.199
                10.162.84.200
                10.162.84.201
                10.162.84.202
                10.162.84.203
                10.162.84.204
                10.162.84.205
                10.162.84.206
                10.162.84.207
                10.162.84.208
                10.162.84.209
                10.162.84.210
                10.162.84.211
                10.162.84.212
                10.162.84.213
                10.162.84.214
                10.162.84.215
                10.162.84.216
                10.162.84.217
                10.162.84.218
                10.162.84.219
                10.162.84.220
                10.162.84.221
                10.162.84.222
                10.162.84.223
                10.162.84.224
                10.162.84.225
                10.162.84.226
                10.162.84.227
                10.162.84.228
                10.162.84.229
                10.162.84.230
                10.162.84.231
                10.162.84.232
                10.162.84.233
                10.162.84.234
                10.162.84.235
                10.162.84.236
                10.162.84.237
                10.162.84.238
                10.162.84.239
                10.162.84.240
                10.162.84.241
                10.162.84.242
                10.162.84.243
                10.162.84.244
                10.162.84.245
                10.162.84.246
                10.162.84.247
                10.162.84.248
                10.162.84.249
                10.162.84.250
                10.162.84.251
                10.162.84.252
                10.162.84.253
                10.162.84.254
                10.162.84.255
}
        track_script {
                chk_nginx_service
                chk_manual_failover
        }
        notify "/usr/libexec/keepalived/nginx-ha-notify"
}

**Notify and track scripts**
[root@esdfwlbp0003 nginx]# cd /usr/libexec/keepalived
[root@esdfwlbp0003 keepalived]# ll
total 12
-rwxr-xr-x 1 root root 477 Aug 29  2019 nginx-ha-check
-rwxr-xr-x 1 root root  74 Aug 29  2019 nginx-ha-manual-failover
-rwxr-xr-x 1 root root 638 Aug 29  2019 nginx-ha-notify
[root@esdfwlbp0003 keepalived]# cat nginx-ha-notify
#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

umask 022

TYPE=$1
NAME=$2
STATE=$3

STATEFILE=/var/run/nginx-ha-keepalived.state

logger -t nginx-ha-keepalived "Transition to state '$STATE' on VRRP instance '$NAME'."

case $STATE in
        "MASTER")
                  service nginx start ||:
                  echo "STATE=$STATE" > $STATEFILE
                  exit 0
                  ;;
        "BACKUP"|"FAULT")
                  echo "STATE=$STATE" > $STATEFILE
                  exit 0
                  ;;
        *)        logger -t nginx-ha-keepalived "Unknown state: '$STATE'"
                  exit 1
                  ;;
esac
[root@esdfwlbp0003 keepalived]# cat nginx-ha-manual-failover
#!/bin/sh

[ -f "/var/run/keepalived-manual-failover" ] && exit 1

exit 0
[root@esdfwlbp0003 keepalived]# cat nginx-ha-check
#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

STATEFILE=/var/run/nginx-ha-keepalived.state

if [ -s "$STATEFILE" ]; then
    . "$STATEFILE"
    case "$STATE" in
        "BACKUP"|"MASTER"|"FAULT")
                service nginx status || service nginx-debug status
                exit $?
                ;;
        *|"")
                logger -t nginx-ha-keepalived "Unknown state: '$STATE'"
                exit 1
                ;;
    esac
fi

service nginx status
exit $?
[root@esdfwlbp0003 keepalived]#

**System Log entries**
Attached
Full keepalived system log entries from when keepalived started
Attached - note: on backup node the logs are written in messages (attached).

**Did keepalived coredump?**
Not sure, let me know how to check
[keepalived status on backup_node.txt](https://github.com/acassen/keepalived/files/7131758/keepalived.status.on.backup_node.txt)
[Keepalived_status_MASER_node.txt](https://github.com/acassen/keepalived/files/7131759/Keepalived_status_MASER_node.txt)
[Keepalived.conf_MASTER_003.txt](https://github.com/acassen/keepalived/files/7131760/Keepalived.conf_MASTER_003.txt)
[Keepalived.conf_backup_node_0004.txt](https://github.com/acassen/keepalived/files/7131761/Keepalived.conf_backup_node_0004.txt)
If so, can you please provide a stacktrace from the coredump, using gdb.

**Additional context**
The logs fi.es are too big (1gb) so could bring them out of jump server, so attached some of them by splitting.
[Backup_node_message_logs01.txt](https://github.com/acassen/keepalived/files/7131876/Backup_node_message_logs01.txt)
[Backup_node_message_logs02.txt](https://github.com/acassen/keepalived/files/7131877/Backup_node_message_logs02.txt)
[Master_node_keepalived_logs01.txt](https://github.com/acassen/keepalived/files/7131886/Master_node_keepalived_logs01.txt)

**Comment by pqarmitage** [comment]
Commit 79e1ec8 resolved this issue, although I think there were some later commits that also helped. The commit was first included in keepalived v2.0.19, although I think it would be safest to go for at least v2.0.21.

Issue #1364 gives all the details in relation to this issue and its resolution.

On the basis that you will need to build a new version of keepalived, it would be worth considering v2.2.4 since that has the most bug fixes.
