### ISSUE TITLE
cannot run gui with vrrp_script 

### ISSUE THREAD

**Issue by ddeeppnneett** [acassen/keepalived#2005]
Hi, 

Keepalived and nginx work fine with me.  Instead of nginx, I wrote my own gui-software which is bug-free and it doesn't work  with keepalived.  Then I find all the gui softwares, for example firefox and xterm, cannot be run by keepalived.  

So, how to make keepalived keep firefox running?

Thanks.

```
#!/bin/bash
#This is the chk_gui.sh used in keepalived.conf

A=$(ps -C firefox --no-header |wc -l)
if [ $A -eq 0 ]; then
/usr/bin/firefox
sleep 2
A=$(ps -C firefox  --no-header |wc -l)
if [ $A -eq 0 ] ; then
   killall keepalived
fi
fi
```

```
! Configuration File for keepalived
#This is keepalived.conf

global_defs {
  router_id linux
}
vrrp_script chk_gui {
  script "/etc/keepalived/chk_gui.sh"
  interval 2
  weight -20
}
vrrp_instance VI_1 {
    state MASTER
    interface eth0
    virtual_router_id 33
    mcast_src_ip 192.168.1.104
    priority 100
    nopreempt
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    track_script{
      chk_nginx
    }
    virtual_ipaddress {
        192.168.1.200
    }
}
```
 

#xterm
#######

> # systemctl status keepalived.service
> ○ keepalived.service - LVS and VRRP High Availability Monitor
>      Loaded: loaded (/usr/lib/systemd/system/keepalived.service; disabled; vendor preset: disabled)
>      Active: inactive (dead)
>        Docs: man:keepalived(8)
>              man:keepalived.conf(5)
>              man:genhash(1)
>              https://keepalived.org
> Oct 01 18:36:09 linux Keepalived_vrrp[29459]: Assigned address 192.168.1.104 for interface eth0
> Oct 01 18:36:09 linux Keepalived_vrrp[29459]: Registering gratuitous ARP shared channel
> Oct 01 18:36:09 linux Keepalived_vrrp[29459]: (VI_1) removing VIPs.
> Oct 01 18:36:09 linux Keepalived_vrrp[29459]: (VI_1) Entering BACKUP STATE (init)
> Oct 01 18:36:09 linux Keepalived_vrrp[29459]: VRRP sockpool: [ifindex(  2), family(IPv4), proto(112), fd(13,14)]
> Oct 01 18:36:11 linux Keepalived[29458]: Stopping
> Oct 01 18:36:12 linux Keepalived_vrrp[29459]: Stopped - used (self/children) 0.000795/0.040980 user time, 0.009619/0.036618 system time
> Oct 01 18:36:12 linux Keepalived[29458]: CPU usage (self/children) user: 0.003624/0.043549 system: 0.007249/0.046237
> Oct 01 18:36:12 linux Keepalived[29458]: Stopped Keepalived v2.2.4 (08/21,2021)
> Oct 01 18:36:12 linux systemd[1]: keepalived.service: Deactivated successfully.
> 

#firefox
########

> # systemctl status keepalived.service
>  keepalived.service - LVS and VRRP High Availability Monitor
>      Loaded: loaded (/usr/lib/systemd/system/keepalived.service; disabled; vendor preset: disabled)
>      Active: active (running) since Fri 2021-10-01 18:37:54 CST; 2s ago
>        Docs: man:keepalived(8)
>              man:keepalived.conf(5)
>              man:genhash(1)
>              https://keepalived.org
>    Main PID: 29522 (keepalived)
>       Tasks: 4 (limit: 13078)
>      Memory: 2.0M
>         CPU: 188ms
>      CGroup: /system.slice/keepalived.service
>              ├─29522 /usr/bin/keepalived --dont-fork -D
>              ├─29523 /usr/bin/keepalived --dont-fork -D
>              ├─29524 /bin/bash /etc/keepalived/chk_gui.sh
>              └─29533 sleep 2
> 
> Oct 01 18:37:54 linux Keepalived_vrrp[29523]: WARNING - default user 'keepalived_script' for script execution does not exist - please >
> Oct 01 18:37:54 linux Keepalived[29522]: Startup complete
> Oct 01 18:37:54 linux systemd[1]: Started LVS and VRRP High Availability Monitor.
> Oct 01 18:37:54 linux Keepalived_vrrp[29523]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
> Oct 01 18:37:54 linux Keepalived_vrrp[29523]: (VI_1) Warning - nopreempt will not work with initial state MASTER - clearing
> Oct 01 18:37:54 linux Keepalived_vrrp[29523]: Assigned address 192.168.1.104 for interface eth0
> Oct 01 18:37:54 linux Keepalived_vrrp[29523]: Registering gratuitous ARP shared channel
> Oct 01 18:37:54 linux Keepalived_vrrp[29523]: (VI_1) removing VIPs.
> Oct 01 18:37:54 linux Keepalived_vrrp[29523]: (VI_1) Entering BACKUP STATE (init)
> Oct 01 18:37:54 linux Keepalived_vrrp[29523]: VRRP sockpool: [ifindex(  2), family(IPv4), proto(112), fd(13,14)]
> 
>

**Comment by pqarmitage** [comment]
The problem is that a program with a GUI needs a logged in session to run at, in order to display the GUI. keepalived runs detached from any terminal or login session (if it is run by systemd then it is never associated from a login session; if it is started from within a login session it detaches itself from that). As a consequence of this, attempting to run any process from keepalived that requires a GUI cannot work. Furthermore, keepalived runs with root privileges, and so if the script did manage to run firefox, it would be running with root privileges which is not a good idea.

I note that your chk_gui.sh script executes `killall keepalived`. This is not the right way to stop keepalived. If keepalived is started by systemd, then you should stop it with `systemctl stop keepalived`. If not run by systemctl, then `kill -TERM $(cat /run/keepalived.pid)` is the way to stop it; the parent process will then stop the child keepalived processes in a controlled way.
