### ISSUE TITLE
Ubuntu 14.4 LTS and keepalived

### ISSUE THREAD

**Issue by ido1** [acassen/keepalived#203]
Hi I have one question and one problem about Keepalived v1.2.7  on Ubuntu 14.04.2 LTS (VXNET3).

1. Is it recommended to upgrade the Keepalived to the last version (1.2.19)? (the last version in the Ubuntu repository is 1.2.7)   

2. I have some problem with the failover, once i stopped the Keepalived service in one node, the IPs aren't failover to the other node, I also see the VIP on both of the nodes if i run "ip a"

**Comment by SethHamilton** [comment]
Same issue. I can stop the service and the VIP isn't removed.

**Comment by acassen** [comment]
Hello,

please upgrade, 1.2.7 is too old... current stable is 1.2.19. All release on website are stable release.

I am about to submit a new stable release with a BUNCH of enhancements.

regs

**Comment by SethHamilton** [comment]
I'm actually having this problem on v1.2.19

**Comment by acassen** [comment]
hello,

did you try the current release into Keepalived github master branch ? this is candidate for the next stable release. Since 1.2.19 we fixed a lot of issues and add bunch of enhancements

regs,

**Comment by ido1** [comment]
the problem solved by install the keepalived version from apt repository + change the VXNET3 to E1000

**Comment by SethHamilton** [comment]
I'll take a look at the master branch, thank you.
