### ISSUE TITLE
nopreempt option ignored in keepalived v2.0.10

### ISSUE THREAD

**Issue by aborrero** [acassen/keepalived#2032]
**Describe the bug**
The `nopreempt` option in keepalived 2.0.10 is apparently ignored.

What happens:
* primary server A, secondary server B
* reboot A, B takes over as primary
* A boots, takes over as primary

This adds an unnecessary transition, and we're trying to avoid it with `nopreempt` without luck.

I can see this in the logs of node A:

```
(VRRP1) Backup received priority 0 advertisement
(VRRP1) Entering MASTER STATE
(VRRP1) Master received advert from 208.80.153.189 with same priority 1 but higher IP address than ours
(VRRP1) Entering BACKUP STATE
(VRRP1) Entering MASTER STATE
(VRRP1) Master received advert from 208.80.153.189 with same priority 1 but higher IP address than ours
(VRRP1) Entering BACKUP STATE
```

I can see this in the logs of node B:
```
(VRRP1) Received advert from 208.80.153.188 with lower priority 1, ours 1, forcing new election
```

**To Reproduce**
Use this config file:
```
global_defs {
}

vrrp_instance VRRP1 {
  state BACKUP
  interface eno2.2120
  virtual_router_id 52
  nopreempt
  priority 1
  advert_int 1
  authentication {
    auth_type PASS
    auth_pass x
  }
  track_interface {
    eno2.2107
  }
  virtual_routes {
    185.15.57.0/29 table 10 nexthop via 185.15.57.10 dev eno2.2107 onlink
    172.16.128.0/24 table 10 nexthop via 185.15.57.10 dev eno2.2107 onlink
  }
  virtual_ipaddress {
    185.15.57.9/30 dev eno2.2107
    208.80.153.190/29 dev eno2.2120
  }
  unicast_peer {
    208.80.153.189
  }
}
```

Same in the other node, except for a different `unicast_peer`.

If I set different `priority` value on each node (let's say node A `priority 1` and node B `priority 2`) the transition happens as well, despite `nopreempt` being used.

**Expected behavior**
* primary server A, secondary server B
* reboot A, B takes over as primary
* A boots, nothing else happens, B stays as primary and A is secondary.

**Keepalived version**
```
Keepalived v2.0.10 (11/12,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.20
Running on Linux 5.10.0-0.bpo.7-amd64 #1 SMP Debian 5.10.40-1~bpo10+1 (2021-06-04)

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --with-kernel-dir=debian/ --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus --enable-dbus-create-instance --enable-json --enable-bfd build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/build/keepalived-8agDac/keepalived-2.0.10=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS DBUS_CREATE_INSTANCE

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK
```

If this bug has been fixed in later versions of keepalived, please indicate which one.
Our setup uses a VRF so we cannot use the latest released one yet (per #1972, which hasn't been included in a release yet I think).

**Comment by pqarmitage** [comment]
This is not a `nopreempt` issue; I have tested your configuration with v2.0.10 and `nopreempt` works as expected.

Even with `nopreempt` it is a bad idea for 2 different systems to have the same VRRP priority; you should always aim to have different priorities on each of the vrrp instances using the same virtual_router_id.

I suspect that this problem relates to the networking not being stable on machine A after the reboot when keepalived starts; we have seen this quite a few times before.

The way to prove this is rather than rebooting machine A, stop keepalived running on machine A, wait a few seconds to that machine B has taken over as master, and then start keepalived on machine A again. I suspect that you will see the behaviour you expect for `nopreempt`.

The solution is almost certainly to delay keepalived starting when the machine boots. It was to help workaround these problems that I added `global_def` `vrrp_startup_delay`, but that is not available in v2.0.10.

**Comment by aborrero** [comment]
> This is not a `nopreempt` issue; I have tested your configuration with v2.0.10 and `nopreempt` works as expected.
> 

Thanks for your tests! really appreciated.

> Even with `nopreempt` it is a bad idea for 2 different systems to have the same VRRP priority; you should always aim to have different priorities on each of the vrrp instances using the same virtual_router_id.
> 

OK, I set them equal as part of experimentation for this problem.

> I suspect that this problem relates to the networking not being stable on machine A after the reboot when keepalived starts; we have seen this quite a few times before.
> 

Let's assume network in machine A is flaky or takes a long time to load. How that results in machine A taking over machine B, which is MASTER already, and has stable network and such?

You think that machine A, despite being being told `init BACKUP` + `nopreempt` takes over MASTER because it can't see the other node alive?

> The way to prove this is rather than rebooting machine A, stop keepalived running on machine A, wait a few seconds to that machine B has taken over as master, and then start keepalived on machine A again. I suspect that you will see the behaviour you expect for `nopreempt`.
> 

I could definitely try this.

**Comment by pqarmitage** [comment]
> Let's assume network in machine A is flaky or takes a long time to load. How that results in machine A taking over machine B, which is MASTER already, and has stable network and such?
>
> You think that machine A, despite being being told init BACKUP + nopreempt takes over MASTER because it can't see the other node alive?

Machine A would take over because it is not receiving any adverts; however machine A is in a state where it can send packets on the network, otherwise machine B would not see the advert.

There are all sorts of different scenarios that have been observed happening from a network point of view when a machine boots. One example is a machine starts being able to receive packets, then stops for a few seconds, and then starts receiving again. The only way I know to work around this problem is to delay keepalived starting, or at least to delay the VRRP code from starting to run.

The following is in the current keepalived.conf(5) man page, and although it refers to bond interfaces, the issues can apply to other interfaces as well:
```
    # On some systems when bond interfaces are created, they can start passing traffic
    # and then have a several second gap when they stop passing traffic inbound. This
    # can mean that if keepalived is started at boot time, i.e. at the same time as
    # bond interfaces are being created, keepalived doesn't receive adverts and hence
    # can become master despite an instance with higher priority sending adverts.
    # This option specifies a delay in seconds before vrrp instances start up after
    # keepalived starts,
    \fBvrrp_startup_delay \fR5.5
```

**Comment by aborrero** [comment]
I was able to try the service startup delay today.

The delay was added by using the systemd service definition:
```
[Service]
ExecStartPre=-/bin/sleep 30
```

Log in machine rebooting:
```
  10:35:40  systemd[1]: Starting Keepalive Daemon (LVS and VRRP)...
  10:36:10  systemd[1]: Started Keepalive Daemon (LVS and VRRP).
  10:36:10  Keepalived[2082]: Starting Keepalived v2.0.10 (11/12,2018)
  10:36:10  Keepalived[2082]: Running on Linux 5.10.0-0.bpo.7-amd64 #1 SMP Debian 5.10.40-1~bpo10+1 (2021-06-04) (built for Linux 4.18.20)
  10:36:10  Keepalived[2082]: Command line: '/usr/sbin/keepalived' '--dont-fork'
  10:36:10  Keepalived[2082]: Opening file '/etc/keepalived/keepalived.conf'.
  10:36:10  Keepalived[2082]: Starting VRRP child process, pid=2084
  10:36:10  Keepalived_vrrp[2084]: Registering Kernel netlink reflector
  10:36:10  Keepalived_vrrp[2084]: Registering Kernel netlink command channel
  10:36:10  Keepalived_vrrp[2084]: Opening file '/etc/keepalived/keepalived.conf'.
  10:36:10  Keepalived_vrrp[2084]: (Line 25) Warning - cannot track route 185.15.57.0/29 with no interface specified, not tracking
  10:36:10  Keepalived_vrrp[2084]: (Line 26) Warning - cannot track route 172.16.128.0/24 with no interface specified, not tracking
  10:36:10  Keepalived_vrrp[2084]: Registering gratuitous ARP shared channel
  10:36:10  Keepalived_vrrp[2084]: (VRRP1) Entering BACKUP STATE (init)
  10:36:14  Keepalived_vrrp[2084]: (VRRP1) Entering MASTER STATE
  10:36:18  Keepalived_vrrp[2084]: (VRRP1) Received advert from 208.80.153.189 with lower priority 1, ours 3, forcing new election
```
The rebooting machine takes over the other, despite `nopreempt` being in use. I also tried setting different priorities as you suggested.

The log shows the 30 second delay before service startup, which should be more than enough to cover for any network instability after boot.

I suspect there is a bug in the logic somewhere. Could you please point to where exactly is the logic to don't preempt in https://github.com/acassen/keepalived/blob/v2.0.10/keepalived/vrrp/vrrp.c ? (or other file)

**Comment by pqarmitage** [comment]
The code for a backup instance remaining in backup state despite received adverts being of lower priority is in vrrp_state_backup() in vrrp.c. Just search for `preempt`.

**Comment by pqarmitage** [comment]
@aborrero What is the result of trying the following suggestion?
> The way to prove this is rather than rebooting machine A, stop keepalived running on machine A, wait a few seconds so that machine B has taken over as master, and then start keepalived on machine A again

**Comment by pqarmitage** [comment]
Closing due to no response for a fortnight. If there are any updates we can reopen the issue.

**Comment by aborrero** [comment]
> @aborrero What is the result of trying the following suggestion?
> 
> > The way to prove this is rather than rebooting machine A, stop keepalived running on machine A, wait a few seconds so that machine B has taken over as master, and then start keepalived on machine A again

Sorry for the month-long delay.

I was able to confirm that this scenario works. In other words, the issue I'm experiencing only seems to involve a rebooting server.

The test I just did is:

* machine A is primary
* machine B is backup
* stop keepalived on machine A
* machine B takes over the primary state
* wait a couple of minutes
* start keepalived on machine A
* machine A inits into backup state
* machine B keeps its primary state

This is clearly different when a reboot is involved.

**Comment by pqarmitage** [comment]
The only thing that I can think of is that when machine A reboots, eno2.2107 and/or eno2.2120 go down on machine B. This would cause the vrrp instance on machine B to go to fault state. If keepalived is running when the interfaces come back up, then the vrrp instance on machine A would become master since, due to having a higher priority, its timeout for receiving no adverts will be quicker than on machine B.

One way around this would be to configure `vrrp_startup_delay` to stop vrrp running for a number of seconds after keepalived starts, so that the interfaces have come back up and machine B has had time to become master again.

**Comment by aborrero** [comment]
> The only thing that I can think of is that when machine A reboots, eno2.2107 and/or eno2.2120 go down on machine B. This would cause the vrrp instance on machine B to go to fault state. If keepalived is running when the interfaces come back up, then the vrrp instance on machine A would become master since, due to having a higher priority, its timeout for receiving no adverts will be quicker than on machine B.
> 

This is unlikely, as traffic is still flowing...

> One way around this would be to configure `vrrp_startup_delay` to stop vrrp running for a number of seconds after keepalived starts, so that the interfaces have come back up and machine B has had time to become master again.

Do you think this can make a difference compared to the the pure systemd `sleep` approach I already tested?

**Comment by aborrero** [comment]
I have another theory. Imagine both being configured with `nopreempt`.

* machine A prio 1 is standby
* machine B prio 2 is master
* machine B reboots, machine A takes over master role
* upon boot, machine B sends an advert with prio 2 per normal VRRP operation, even though it has `nopreempt`.
* machine A recvs the advert with higher prio, and event though it has `nopreempt` locally, there is no way to know if the other node is master already, so it gives up the master role.
* machine B proceeds to take over master role. It had `nopreempt` locally, it was never its intention, but the other peer gave up the role.

This is to say that the problem might not be in the new node entering the conversation having `nopreempt`, but previous nodes somehow preferring to stay with the master node and ignoring higher prio adverts from newer nodes. Kind of `don't-let-others-preempt-me`.

How do you feel about this theory?

**Comment by wsnipex** [comment]
I have the same issue with keepalived 2.1.5, no matter if vrrp_startup_delay is set or not.
As for the OP, it only happens when the inactive node is rebooted.
It doesn't matter if both have the same or a different priority: When the (rebooted) backup node has higher prio, the other node will give up master because of that and when both have the same prio, the "higher ip" wins.

it seems to me that  addr_cmp  is bogus here: https://github.com/acassen/keepalived/blob/v2.1.5/keepalived/vrrp/vrrp.c#L2084
Or noprempt should be considered

**Comment by wsnipex** [comment]
logs for the reboot inactive/backup node with same priority:

current master:
```
Oct 12 08:27:43 node1 Keepalived_vrrp[1250]: (VI_1) Master received advert from 10.1.1.12 with same priority 101 but higher IP address than ours
Oct 12 08:27:43 node1 Keepalived_vrrp[1250]: (VI_1) Entering BACKUP STATE
Oct 12 08:27:43 node1 Keepalived_vrrp[1250]: (VI_1) removing VIPs.

```

rebooted node:
```
Oct 12 08:27:40 node2 Keepalived_vrrp[1259]: VRRP_Script(check_ssh) succeeded
Oct 12 08:27:40 node2 Keepalived_vrrp[1259]: (VI_1) Entering BACKUP STATE
Oct 12 08:27:40 node2 Keepalived_vrrp[1259]: VI_1: sending gratuitous ARP for 10.1.1.12
Oct 12 08:27:40 node2 Keepalived_vrrp[1259]: Sending gratuitous ARP on ens192 for 10.1.1.12
Oct 12 08:27:43 node2 Keepalived_vrrp[1259]: (VI_1) Receive advertisement timeout
Oct 12 08:27:43 node2 Keepalived_vrrp[1259]: (VI_1) Entering MASTER STATE
Oct 12 08:27:43 node2 Keepalived_vrrp[1259]: (VI_1) setting VIPs.

```

**Comment by wsnipex** [comment]
well, it's exactly the same issue as described by the OP(which is still unsolved afaict), but if you prefer I can open a new issue.

**Comment by a180285** [comment]
I have the same issue. Finnally add `global_def vrrp_startup_delay` resolved.

My key issue is as @pqarmitage mentioned in config.
The bond interface is not ready, when keepalived started.


@wsnipex I have exactly same logs as you. But the differnce is when I look at log arround. And use another machine to ping your rebooting machine. I see that, keepalived is started before rebooting machine can reply the ping message. Which means keepalived start to work before bond interface is ready on rebooting machine. 

So I set `vrrp_startup_delay` to 60 solved my problem.

> logs for the reboot inactive/backup node with same priority:
> 
> current master:
> 
> ```
> Oct 12 08:27:43 node1 Keepalived_vrrp[1250]: (VI_1) Master received advert from 10.1.1.12 with same priority 101 but higher IP address than ours
> Oct 12 08:27:43 node1 Keepalived_vrrp[1250]: (VI_1) Entering BACKUP STATE
> Oct 12 08:27:43 node1 Keepalived_vrrp[1250]: (VI_1) removing VIPs.
> ```
> 
> rebooted node:
> 
> ```
> Oct 12 08:27:40 node2 Keepalived_vrrp[1259]: VRRP_Script(check_ssh) succeeded
> Oct 12 08:27:40 node2 Keepalived_vrrp[1259]: (VI_1) Entering BACKUP STATE
> Oct 12 08:27:40 node2 Keepalived_vrrp[1259]: VI_1: sending gratuitous ARP for 10.1.1.12
> Oct 12 08:27:40 node2 Keepalived_vrrp[1259]: Sending gratuitous ARP on ens192 for 10.1.1.12
> Oct 12 08:27:43 node2 Keepalived_vrrp[1259]: (VI_1) Receive advertisement timeout
> Oct 12 08:27:43 node2 Keepalived_vrrp[1259]: (VI_1) Entering MASTER STATE
> Oct 12 08:27:43 node2 Keepalived_vrrp[1259]: (VI_1) setting VIPs.
> ```
