### ISSUE TITLE
Suggestion to avoid lost notifties

### ISSUE THREAD

**Issue by ryancaicse** [acassen/keepalived#2035]
Hi, developers, it seems there is a potential deadlock bug between the signal (Line 700) and wait sites (Line 996) between threads, because it is possible for the thread dbus_thread created at Line 994 to signal first and, later, the main thread goes to the wait site forever without signal notified anymore.

Although, it is very impossible in practice because the main thread creates it child thread and reaches the wait site immediately. But it seems possible in theory.

wait site:
https://github.com/acassen/keepalived/blob/93e7cd14d708a6cc3d0c0006574cfdec14961aac/keepalived/vrrp/vrrp_dbus.c#L991-L997
signal site:
https://github.com/acassen/keepalived/blob/93e7cd14d708a6cc3d0c0006574cfdec14961aac/keepalived/vrrp/vrrp_dbus.c#L697-L703

**To avoid this problem, the recommended usage of thread_cond_signal and thread_cond_wait would be**

```
pthread_mutex_t count_lock;
pthread_cond_t count_nonzero;
unsigned count;

decrement_count()
{
    pthread_mutex_lock(&count_lock);
    while (count == 0)
        pthread_cond_wait(&count_nonzero, &count_lock);
    count = count - 1;
    pthread_mutex_unlock(&count_lock);
}

increment_count()
{
    pthread_mutex_lock(&count_lock);
    if (count == 0)
        pthread_cond_signal(&count_nonzero);
    count = count + 1;
    pthread_mutex_unlock(&count_lock);
}
```

**Comment by pqarmitage** [comment]
@ryancaicse Many thanks for pointing this out. I believe commit 7245f45 resolves the issue.

**Comment by ryancaicse** [comment]
@pqarmitage Thanks!
