### ISSUE TITLE
Failover for one bridge-interface forces other bridge-iface failover

### ISSUE THREAD

**Issue by laxxie** [acassen/keepalived#2039]
Ubuntu 20.04 
5.13.0-21-generic
Keepalived v2.0.19 (10/19,2019)
---

We have a setup with two nodes with the same configs. There is one vlan interface bond0.222 and two vxlan interfaces br-1004 and br-1047.

If we force a failover for br-1047 (vrid 1)  it will force a failover for br-1004(vrid 2) too, bond0.222 remains untouched. Keepalived is sending an advertisement with prio 0 for vrid 2 and not only for vrid 1.

**Journal**

> Nov 16 15:49:34 node1 Keepalived_vrrp[50291]: (vrrp-br-1004) sent 0 priority
> Nov 16 15:49:34 node1 Keepalived_vrrp[50291]: (vrrp-br-1004) Entering BACKUP STATE
> 
> Nov 16 15:49:34 node2 Keepalived_vrrp[47823]: (vrrp-br-1004) Entering MASTER STATE
> Nov 16 15:49:34 node2 Keepalived_vrrp[47823]: (vrrp-br-1004) Backup received priority 0 advertisement

**TCPdump**

> 15:49:34.003827 IP (tos 0xc0, ttl 255, id 190, offset 0, flags [none], proto VRRP (112), length 40)
>     10.10.10.1 > 10.10.10.2: vrrp 10.10.10.1 > 10.10.10.2: VRRPv2, Advertisement, vrid 1, prio 0, authtype simple, intvl 1s, length 20, addrs: 
> 
> 
> 15:49:34.004150 IP (tos 0xc0, ttl 255, id 22766, offset 0, flags [none], proto VRRP (112), length 40)
>     10.10.10.1 > 10.10.10.2: vrrp 10.10.10.1 > 10.10.10.2: VRRPv2, Advertisement, vrid 2, prio 0 , authtype simple, intvl 1s, length 20, addrs: 

**part of the config**

>
>    vrrp_instance vrrp-br-1004 {
>
>     state EQUAL
>
>     interface eno2
> 
>     dont_track_primary
>     nopreempt
>     priority 100
>     smtp_alert
>     virtual_router_id 2
>     unicast_src_ip 10.10.10.1
>     unicast_peer {
>         10.10.10.2
>     }
> 
>     authentication {
>         auth_type PASS
>         auth_pass A=
>     }
> 
>     track_interface {
>     br-1004
>     }

Are there any known issues with multiple bridge-interfaces?

**Comment by pqarmitage** [comment]
There are no known issues with using multiple bridge interfaces.

If you provide the following we can investigate further:
- Your full configuration file
- The output of `keepalived -v`
- The full keepalived logs from when keepalived starts
- The output of `ip -d show link`

**Comment by laxxie** [comment]
I'm sorry, today we found the problem. There was a fault in the **virtual_ipaddress_excluded** section. In the configuration for br-1004 we set

> \<IP\> dev br-1047

and not br-1004
