### ISSUE TITLE
Cannot ping virtual ip address

### ISSUE THREAD

**Issue by saodis** [acassen/keepalived#2046]
### I encountered a problem. I can't Ping the virtual IP address

keepalived version is v1.3.5，Install using `yum install keepalived`
![image](https://user-images.githubusercontent.com/51149477/142727304-2ec777ff-8ba9-4934-accd-f38d688b5d22.png)

Keepalived configuration
![image](https://user-images.githubusercontent.com/51149477/142726746-b1726f9b-d4c9-42b6-a4db-ee01f3caed28.png)

gateway：192.168.2.1
master：192.168.2.111
backup：192.168.2.112
vip：192.168.2.110
Cannot ping virtual ip address
![image](https://user-images.githubusercontent.com/51149477/142726863-a85a1ec2-5c47-4717-9692-818bc08790bb.png)
![image](https://user-images.githubusercontent.com/51149477/142727680-ff75e2f8-f49a-4486-8881-e24df2a6bc74.png)

I tried many methods, and finally found that it was the firewall problem.
My firewall is disabled by default. In this case, I need to use keepalived, I have to turn on the firewall first and then turn off the firewall.
Why is that?
![image](https://user-images.githubusercontent.com/51149477/142727895-6e0402f4-49bf-4878-86aa-bf628efcce30.png)
![image](https://user-images.githubusercontent.com/51149477/142727893-9fddad19-337d-411c-b4bc-89de33b17f14.png)

**Comment by pqarmitage** [comment]
You don't provide a copy of your configuration, but from what you describe I guess you either have `global_def` `vrrp_strict` configured, or you have `no_accept` configured on your vrrp_instance, and that the priority of the vrrp instance in less than 255.

In either case, keepalived sets up firewall rules (iptables with such an old version of keepalived) to stop any traffic being received on the virtual ip addresses; this is to comply with the VRRP RFCs.

I am guessing that when the firewalld service is stopped, it clears all the iptables rules that have been configured, including rules that 'belong' to other processes, and this allows traffic to the virtual ip addresses to then be received.

**Comment by saodis** [comment]
@pqarmitage 
Isn't the configuration file here??

![image](https://user-images.githubusercontent.com/51149477/142750429-afd16797-af76-49ec-851f-3c6188851ddf.png)

**Comment by saodis** [comment]
My firewall has not been configured. After the operating system is installed, the firewall is disabled.

**Comment by pqarmitage** [comment]
Apologies, I didn't notice the configuration as a screenshot, configurations are normally provided as part of the text of an issue.

After starting keepalived, there is the following firewall configuration:
```
Chain INPUT (policy ACCEPT 8 packets, 608 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set keepalived dst

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 89 packets, 3848 bytes)
 pkts bytes target     prot opt in     out     source               destination         
Name: keepalived
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 168
References: 1
Number of entries: 1
Members:
192.168.2.110
```
and this is what is stopping the ping working. The iptables/ipset entries are added due to the `vrrp_strict` config item.

After executing `systemctl start firewalld` and then `systemctl stop firewalld`, the iptables/ipsets configuration is:
```
Chain INPUT (policy ACCEPT 8 packets, 608 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 89 packets, 3848 bytes)
 pkts bytes target     prot opt in     out     source               destination         
Name: keepalived
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 168
References: 1
Number of entries: 1
Members:
192.168.2.110
```
There is now no longer the rule in the INPUT chain to block the incoming ping traffic, and so ping works.
