### ISSUE TITLE
VRRP_Instance(VI_1) Cant sent advert to xx.xxx.xxx.xx (Operation not permitted)

### ISSUE THREAD

**Issue by Cugar15** [acassen/keepalived#205]
Hello,

  I'm trying to setup keepalived and looks like I've done most of the steps correctly - at least I think...
However both master and backup node have an issue with vrrp.

Below is the log file of the backup node. It's starting in BACKUP and then failing over to MASTER state. 

Any idea what causes the message - its' repeated every 1sec.

Thanks for helping.
Cugar

Dec  8 23:28:46 178 Keepalived[24982]: Starting Keepalived v1.2.19 (12/08,2015)
Dec  8 23:28:46 178 Keepalived[24983]: Starting Healthcheck child process, pid=24985
Dec  8 23:28:46 178 Keepalived_healthcheckers[24985]: Initializing ipvs 2.6
Dec  8 23:28:46 178 Keepalived[24983]: Starting VRRP child process, pid=24986
Dec  8 23:28:46 178 Keepalived_healthcheckers[24985]: Registering Kernel netlink reflector
Dec  8 23:28:46 178 Keepalived_healthcheckers[24985]: Registering Kernel netlink command channel
Dec  8 23:28:46 178 Keepalived_healthcheckers[24985]: Opening file '/etc/keepalived/keepalived.conf'.
Dec  8 23:28:46 178 Keepalived_vrrp[24986]: Registering Kernel netlink reflector
Dec  8 23:28:46 178 Keepalived_vrrp[24986]: Registering Kernel netlink command channel
Dec  8 23:28:46 178 Keepalived_vrrp[24986]: Registering gratuitous ARP shared channel
Dec  8 23:28:46 178 Keepalived_vrrp[24986]: Opening file '/etc/keepalived/keepalived.conf'.
Dec  8 23:28:46 178 Keepalived_healthcheckers[24985]: Configuration is using : 8489 Bytes
Dec  8 23:28:46 178 Keepalived_vrrp[24986]: Truncating auth_pass to 8 characters
Dec  8 23:28:46 178 Keepalived_vrrp[24986]: Configuration is using : 65956 Bytes
Dec  8 23:28:46 178 Keepalived_vrrp[24986]: Using LinkWatch kernel netlink reflector...

Dec  8 23:28:46 178 Keepalived_vrrp[24986]: VRRP_Instance(VI_1) Entering BACKUP STATE
Dec  8 23:28:46 178 Keepalived_healthcheckers[24985]: Using LinkWatch kernel netlink reflector...
Dec  8 23:28:46 178 Keepalived_vrrp[24986]: VRRP_Script(chk_nginx) succeeded
Dec  8 23:28:50 178 Keepalived_vrrp[24986]: VRRP_Instance(VI_1) Cant sent advert to xx.xxx.xxx.xx (Operation not permitted)
Dec  8 23:28:50 178 Keepalived_vrrp[24986]: VRRP_Instance(VI_1) Transition to MASTER STATE
Dec  8 23:28:51 178 Keepalived_vrrp[24986]: VRRP_Instance(VI_1) Entering MASTER STATE
Dec  8 23:28:51 178 Keepalived_vrrp[24986]: Opening script file /etc/keepalived/backup.sh
Dec  8 23:28:51 178 Keepalived_vrrp[24986]: VRRP_Instance(VI_1) Cant sent advert to xx.xxx.xxx.xx (Operation not permitted)

**Comment by acassen** [comment]
must be run with root privilegies

**Comment by Cugar15** [comment]
Thanks for the comment. 
The process keepalived runs under user root.

**Comment by pqarmitage** [comment]
I could see the same problem when I ran this with a unicast_peer { xx.xxx.xxx.xx } configured on the vrrp instance.
After executing the following command:
iptables -I OUTPUT 1 -d xx.xxx.xxx.xx -j ACCEPT
then I stopped getting the "Cant sent advert" message. Clearly this isn't the entry you would want to add to iptables, but it proves that it is iptables configuration that is blocking the message.

If you can't see where iptables is blocking the message, execute:
iptables -t raw -d xx.xxx.xxx.xx -j TRACE
then run keepalived and look at the syslog entries created by netfilter to see which rule is blocking the packet (don't forget to delete the trace entry afterwards!).

**Comment by Cugar15** [comment]
yes, I'm using unicast_peer - and the firewall is the problem. 
Adding iptables -I OUTPUT 1 -d xx.xxx.xxx.xx -j ACCEPT and the respective input, I can see keepalive working.

Would you be able to provide a recommended iptables configuration? - I was searching the web and what I was using previsouly obvioulsy failed miserable. 
Thanks a ton in advance!

**Comment by pqarmitage** [comment]
Cugar15,

I'm happy to help with resolving your iptables configuration, but the solution will depend on your current configuration.

I suggest you send me an email offline from here - you can find my email address in the Signed-off-by tag of some recent commits. Once we've sorted it out, we can update this issue with the details of what was done.

**Comment by vineet01** [comment]
I could get it to work by allowing both outgoing+incoming traffic for VRRP and AH (using AH for authentication between keepalived nodes).

> iptables -I OUTPUT -d desti.nation.ip.address -p Ah -j ACCEPT
> iptables -I OUTPUT -d desti.nation.ip.address -p vrrp -j ACCEPT

And similarly allow incoming,outgoing traffic for both protocols on both nodes (2 nodes in my case).
