### ISSUE TITLE
Doesn't the official provide build help documents?

### ISSUE THREAD

**Issue by mingtdlb** [acassen/keepalived#2051]
Doesn't the official provide build help documents?

**Comment by pqarmitage** [comment]
@mingtdlb I am not clear what this issue is about. Could you please explain.

**Comment by pqarmitage** [comment]
@mingtdlb If you are asking for build instructions, see the INSTALL file in the root of the source tree.

**Comment by mingtdlb** [comment]
@pqarmitage Building keepalived from Sources

**Comment by pqarmitage** [comment]
@mingtdlb As I mentioned above, the INSTALL file contains the building instructions.
