### ISSUE TITLE
master VR enter backup if  intervals is short between two HUP signal

### ISSUE THREAD

**Issue by czqChen** [acassen/keepalived#208]
After keepalived received HUP signal, then reload configration file, and the master VR enter  VRRP_STATE_GOTO_MASTER state. If another HUP signal arrived,  in function vrrp_init_state, because vrrp->wantstate equal to VRRP_STATE_GOTO_MASTER, so the VR enter VRRP_STATE_BACK state. 

Refer to vrrp_scheduler.c#L234.

**Comment by pqarmitage** [comment]
Resolved by commit e33e8b6
