### ISSUE TITLE
rpmbuild fails in RHEL7 due to no "libkmod-devel" package

### ISSUE THREAD

**Issue by jearls** [acassen/keepalived#2083]
**Describe the bug**
The spec file for keepalived requires `libkmod-devel` package for building and `libkmod` for running.  RHEL7 does not provide those package names; instead, it has `kmod-devel` and `kmod-libs`.

**To Reproduce**
Try to build on RHEL7 (or CentOS 7 or Oracle Linux 7).

**Expected behavior**
The rpmbuild should work on RHEL7.

**Keepalived version**
```
2.2.7
```

**Distro (please complete the following information):**
 - Name: Oracle Linux (or CentOS or Red Hat Enterprise Linux)
 - Version: 7
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
N/A

**Configuration file:**
N/A

**Notify and track scripts**
N/A

**System Log entries**
N/A

**Did keepalived coredump?**
N/A

**Additional context**
The spec file should require the proper package names for EL7 (`kmod-devel` and `kmod-libs`).

**Comment by pqarmitage** [comment]
Many thanks for reporting this. It transpires that all RedHat based systems need packages `kmod-devel` and kmod-libs`.

Commit b8d4758 resolves this issue. Commit 92f9f05 resolves another issue in the keepalived.spec file.
