### ISSUE TITLE
rpmbuild fails in 2.2.7 due to looking for `%{_sysconfdir}/keepalived/keepalived.conf` file which is never installed

### ISSUE THREAD

**Issue by jearls** [acassen/keepalived#2084]
**Describe the bug**
The 2.2.7 keepalived.spec file tries to install `%{_sysconfdir}/keepalived/keepalived.conf`, but that file is never installed - what is installed is `%{_sysconfdir}/keepalived/keepalived.conf.sample`.

**To Reproduce**
Try to build the package via `make rpm`.

**Expected behavior**
Expect the package to build without error.

**Keepalived version**
```
2.2.7
```

**Distro (please complete the following information):**
 - Name: Oracle Linux
 - Version: 7
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
N/A

**Configuration file:**
N/A

**Notify and track scripts**
N/A

**System Log entries**
N/A

**Did keepalived coredump?**
N/A

**Additional context**

**Comment by pqarmitage** [comment]
Commit 92f9f05 resolves this.
