### ISSUE TITLE
Statefile reports primary and backup node states inconsistently 

### ISSUE THREAD

**Issue by Robbie558** [acassen/keepalived#2093]
**Describe the bug**

We are running two VRRP instances on keepalived when there is a fail-over between the nodes for one of these VRRP instances from MASTER to BACKUP the statefile (`/var/run/nginx-ha-keepalived.state`) is updated to BACKUP, despite the node still being in MASTER state for the other VRRP instance.  I can see that the `/usr/lib/keepalived/nginx-ha-notify` file configures the statefile and does not handle the instance name.

**To Reproduce**
As above, configure two VIPs managing different IP addresses.  Set the priority for one VIP lower than the other, start the service and then reverse the priority setting between the nodes and reload the service.

**Expected behavior**
VIP state is tracked independently in the statefile.

**Keepalived version**
```
version 2.0.19
```

**Distro (please complete the following information):**
 - Name: Ubuntu
 - Version: 20.04
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
N/A

**Configuration file:**
```
global_defs {
        vrrp_version 3
}

vrrp_script chk_manual_failover {
        script "/usr/lib/keepalived/nginx-ha-manual-failover"
        interval 10
        weight 50
}

vrrp_script chk_nginx_service {
        script "/usr/lib/keepalived/nginx-ha-check"
        interval 3
        weight 50
}

vrrp_instance VI_1 {
        interface eth0
        priority 101
        virtual_router_id 51
        advert_int 1
        accept
        unicast_src_ip 172.2.3.11
        unicast_peer {
                172.2.3.12
        }
        virtual_ipaddress {
                172.2.3.10
        }
        virtual_ipaddress_excluded {
                172.2.3.102
                172.2.3.104
                ...
        }
        track_script {
                chk_nginx_service
                chk_manual_failover
        }
        notify "/usr/lib/keepalived/nginx-ha-notify"
}

vrrp_instance VI_2 {
        interface eth0
        priority 100
        virtual_router_id 53
        advert_int 1
        accept
        unicast_src_ip 172.2.3.11
        unicast_peer {
                172.2.3.12
        }
        virtual_ipaddress {
                172.2.3.236
        }
        track_script {
                chk_nginx_service
                chk_manual_failover
        }
        notify "/usr/lib/keepalived/nginx-ha-notify"
}

```

**Notify and track scripts**
```
N/A
```

**System Log entries**

**NODE 1**
```
Feb 03 14:44:04 lb01 Keepalived_vrrp[2892]: (VI_2) Entering MASTER STATE
Feb 03 14:44:04 lb01 Keepalived_vrrp[2892]: (VI_2) using locally configured advertisement interval (1000 milli-sec)
Feb 03 14:46:31 lb01 Keepalived_vrrp[2892]: (VI_2) Master received advert from 172.2.3.12 with higher priority 201, ours 200
Feb 03 14:46:31 lb01 Keepalived_vrrp[2892]: (VI_2) Entering BACKUP STATE
Feb 03 14:52:02 lb01 Keepalived_vrrp[2892]: (VI_2) Backup received priority 0 advertisement
Feb 03 14:52:02 lb01 Keepalived_vrrp[2892]: (VI_2) Entering MASTER STATE
Feb 03 14:52:02 lb01 Keepalived_vrrp[2892]: (VI_2) using locally configured advertisement interval (1000 milli-s
```
Statefile:
```
cat /var/run/nginx-ha-keepalived.state 
STATE=MASTER
```

**NODE 2**
```
Feb 03 14:46:30 lb02 Keepalived_vrrp[214415]: (VI_2) received lower priority (200) advert from 172.2.3.11 - discarding
Feb 03 14:46:31 lb02 Keepalived_vrrp[214415]: (VI_2) Entering MASTER STATE
Feb 03 14:46:31 lb02 Keepalived_vrrp[214415]: (VI_2) using locally configured advertisement interval (1000 milli-sec)
Feb 03 14:52:02 lb02 Keepalived[214414]: Stopping
Feb 03 14:52:02 lb02 systemd[1]: Stopping LVS and VRRP High Availability Monitor...
Feb 03 14:52:02 lb02 Keepalived_vrrp[214415]: (VI_2) sent 0 priority
Feb 03 14:52:03 lb02 systemd[1]: Stopped LVS and VRRP High Availability Monito
```
Statefile:
```
cat /var/run/nginx-ha-keepalived.state 
STATE=MASTER
```

**Did keepalived coredump?**
```
No
```

**Additional context**
N/A

**Comment by pqarmitage** [comment]
`/usr/lib/keepalived/nginx-ha-notify `, `/usr/lib/keepalived/nginx-ha-manual-failover" and `/usr/lib/keepalived/nginx-ha-check` are not files provided by keepalived. Are they files that are part of the nginx package?

If you can provide copies of the above scripts I will have a look at the issue. It is probably `/usr/lib/keepalived/nginx-ha-notify ` that is the important script here. I can see the script is probably part of the nginx-ha-keepalived package, but I haven't found a copy of the package yet.

**Comment by Robbie558** [comment]
Thanks @pqarmitage for you reply.  The script are in fact part of the `nginx-ha-keepalived` package which isnt publicly available. I can find very limited documentation on the state file (`nginx-ha-keepalived.state`) in their documentation; [see here](https://docs.nginx.com/nginx/admin-guide/high-availability/ha-keepalived/), and certaining nothing in respect to multiple VRRP instances. I shall reach out to support at F5 / Nginx for further support.
