### ISSUE TITLE
I have a question about the value of weight in vrrp_script

### ISSUE THREAD

**Issue by thissuper** [acassen/keepalived#2108]
Hi, what does this weight value mean? I didn't understand the meaning of the [document](https://www.keepalived.org/manpage.html)!
![image](https://user-images.githubusercontent.com/57950591/155278939-eb7eec18-c650-4d71-9e5c-17975b7a05e6.png)

If weight = - 30 is set, it means that when the return value of the detection script is not equal to "0", the weight of the master will be reduced by 30? What is the relationship between this weight and the return value of the detection script in vrrp_script?

### master
```shell
...
vrrp_script check_run {
  script "/usr/local/bin/check.sh"
  interval 3
  rise 1
  fall 1
  weight -30
}
vrrp_instance VI_1 {
  state master
  priority 150
  ...
}
```
### backup
```shell
...
vrrp_script check_run {
  script "/usr/local/bin/check.sh"
  interval 3
  rise 1
  fall 1
  weight -30
}
vrrp_instance VI_1 {
  state backup
  priority 100
  ...
}
```

**Comment by pqarmitage** [comment]
You have shown some snippets of of configuration. In the vrrp_instance blocks do you have a track_script block, e.g.:
```
track_script {
    check_run
}
```

By default, if a track_script fails (i.e. exists with non-zero exit code), any vrrp instance using that track_script will go to fault state until the track_script starts returning a 0 exit code. Sometimes, however, you don't want the vrrp_instance to go to failed state, but you want the priority of the vrrp_instance to change; if the priority is reduced it can enable the backup taking over as master.

For example, suppose you are using keepalived in conjunction with haproxy. If haproxy fails on the master, you might want the backup to take over as master and this can be achieved by reducing the priority of the 'master' vrrp_instance to be less than the priority of the 'backup' instance.

Suppose a vrrp_instance has configured priority 150. If you have a track_script configured with weight 10, then so long as the track_script is returning 0 exit code, the priority of the vrrp_instance will be increased to 160 (150 + 10). If the script starts failing, the priority will revert to 150. On the other hand, if the weight is -10, then when the script is returning success the priority will remain 150, but if the script is failing, the priority will be reduced to 140 (150 + -10).

If you have priority 150 configured on the 'master' and the weight of the track_script is 10, and on the backup the priority is 145, with the track_script also having a weight of 10, then so long as the track_script on the master is returning success, the master will have priority 160, and (if the track_script on the backup is also returning success) the priority the backup will be 155. If the track script on the 'master' starts failing, the 'master's priority will reduce to 150, and so the 'backup' will take over as master. If the track_script on the backup now starts failing as well, the 'backup's priority will reduce to 145 and the 'master' will take over as master again.

So far as I remember keepalived only checks whether the exit code is 0 or non-zero; different non-zero values make no difference to how keepalived behaves.

**Comment by thissuper** [comment]
@pqarmitage thanks a lot
