### ISSUE TITLE
VRRP/unicast - Master/Backup flipflopping once IO on peer node

### ISSUE THREAD

**Issue by Cugar15** [acassen/keepalived#211]
Hello,
  I'm running a simple keepalived configuration for testing and monitoring right now.

Node:xxxx
vrrp_script chk_nginx {
    script "pidof nginx"
    interval 2
}

vrrp_instance VI_1 {
    interface eth0
    state MASTER
    priority 200

    virtual_router_id 33
    unicast_src_ip xxx.xx.xxx.xx
    unicast_peer {
       yyy.yy.yyy.yy
    }
    authentication {
        auth_type PASS
        auth_pass 11111111
    }
    track_script {
        chk_nginx
    }
    notify /etc/keepalived/master.sh
}

On node yyy (cut out): 
...
vrrp_instance VI_1 {
    interface eth0
    state BACKUP
    priority 100

    virtual_router_id 33
    unicast_src_ip yyy.yy.yyy.yy
    unicast_peer {
        xxx.xx.xxx.xx
    }
..
    notify /etc/keepalived/backup.sh
...

Once executing a file based backup of an sql database on the master node, the backup node is flipflopping between Master and Backup state. The example log below is a simple dump of the state by the backup.sh script into a log. This happens for ca 30min - which is the duration of the backup...
....
Wed Dec 23 12:01:01 CET 2015 : Change to: BACKUP
Wed Dec 23 12:01:05 CET 2015 : Change to: BACKUP
Wed Dec 23 12:03:26 CET 2015 : Change to: BACKUP
Wed Dec 23 12:04:32 CET 2015 : Change to: BACKUP
Wed Dec 23 12:04:45 CET 2015 : Change to: BACKUP
Wed Dec 23 12:05:45 CET 2015 : Change to: MASTER 
...
In the syslog of Node Master node (xxx), the following is recorded:
Dec 23 12:04:32 xxx Keepalived_vrrp[28037]: VRRP_Instance(VI_1) Received lower prio advert, forcing new election
Dec 23 12:04:32 xxx Keepalived_vrrp[28037]: VRRP_Instance(VI_1) Received lower prio advert, forcing new election

There is no flipflopping of the state of the Master node observed...

1) Any idea what the reason could create this flipflop behaviour?

2) As seen in the log, the notify script of the backup node is not called every time a state transition is happening.
    The syslog seems to be correct... the transitioning from B->M->B_>... is correctly recorded.
    Why is the execution of the notify script skipped sometimes??

3) Is there a way, to make vrrp with unicast less sensitive?

Thanks,
Cugar15

**Comment by pqarmitage** [comment]
You could increase the advert_int in the vrrp_instance configurations, which has been known to help in this sort of situation, but of course that would also delay a failover to backup.

An alternative could be to increase the priority of the keepalived_vrrp child process and/or lock the process into memory.

Commit e1cb8f4 adds options to configure the child process priorities and lock the processes in memory, which may help alleviate this problem.
