### ISSUE TITLE
How can I make keepalived as DEBIAN package

### ISSUE THREAD

**Issue by caibo2014** [acassen/keepalived#212]
will someone provide a control files and a postinst file or something?

thanks.

**Comment by gurubert** [comment]
Keepalived 1.2.19 is already available as a Debian package: https://packages.debian.org/sid/keepalived

You may start from there.

**Comment by caibo2014** [comment]
but I want to chang some code and make a deb for myself. could you kindly give me some guide? 
thanks!

**Comment by cswingler** [comment]
That's a little outside the scope of this issue tracker imo, you can take the dpkg and unpack the metadata from it as a starting off point. Past that, off to Google or the Debian-user mailing list to ask "how do I make a dpkg?" :-)

**Comment by caibo2014** [comment]
@cswingler 
You misunderstood what I meant. Many software will be available under a variety of operating systems packaged script , I would like to know keepalvied there are similar script.

you can see ceph, for example.
