### ISSUE TITLE
Keepalived and kernel routing question

### ISSUE THREAD

**Issue by Adi-AA** [acassen/keepalived#2127]
_Support requests should be sent via_ https://groups.io/g/keepalived-users

**Describe why you are unable to send the support request to the above email list**
This is just to know if keepalived team is the right one to help with my request.

**Describe what you need help/support for**
We have ubuntu running on a VM and has nginx on it.
We are trying to do a bgp config where in when any of the virtual_addresses fails they can failover to a different data center
We added virtual_ipaddresses in keepalived but they are not propagating to kernel route table and not participating in bgp (bird process)
**Details of what you would like to do with keepalived**
How can we get keepalived talk to kernel routing (bird process)

**Keepalived version**
Output of `keepalived -v` (a later version of keepalived might be needed).

Keepalived v2.2.7 (01/16,2022)

Copyright(C) 2001-2022 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.4.60
Running on Linux 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022
Distro: Ubuntu 20.04.4 LTS

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --enable-bfd --disable-lvs --disable-snmp --with-init=none build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/data/builder/debuild/nginx-ha-keepalived-2.2.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -Wl,--as-needed CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options: VRRP VRRP_AUTH VRRP_VMAC BFD OLD_CHKSUM_COMPAT INIT=none

System options: VSYSLOG MEMFD_CREATE IPV6_MULTICAST_ALL IPV4_DEVCONF RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK
**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu]
 - Version [e.g. 29]
 - Architecture [e.g. x86_64]

**Details of any containerisation or hosted service (e.g. AWS)**
none

**Configuration file:**
[10:51 AM] Allen, Scott
global_defs {
vrrp_version 3
}vrrp_script chk_manual_failover {
script "/usr/lib/keepalived/nginx-ha-manual-failover"
interval 10
weight 50
}vrrp_script chk_nginx_service {
script "/usr/lib/keepalived/nginx-ha-check"
interval 3
weight 50
}vrrp_instance VI_1 {
interface ens160
priority 101
virtual_router_id 51
advert_int 1
accept
garp_master_refresh 5
garp_master_refresh_repeat 1
unicast_src_ip 10.62.217.185/22
unicast_peer {
10.62.217.184
}
virtual_ipaddress {
10.62.217.201
}
track_script {
chk_nginx_service
chk_manual_failover
}
notify "/usr/lib/keepalived/nginx-ha-notify"
}

[10:52 AM] Allen, Scott
global_defs {
vrrp_version 3
}vrrp_script chk_manual_failover {
script "/usr/lib/keepalived/nginx-ha-manual-failover"
interval 10
weight 50
}vrrp_script chk_nginx_service {
script "/usr/lib/keepalived/nginx-ha-check"
interval 3
weight 50
}vrrp_instance VI_1 {
interface ens160
priority 101
virtual_router_id 51
advert_int 1
accept
garp_master_refresh 5
garp_master_refresh_repeat 1
unicast_src_ip 10.62.217.183/22
unicast_peer {
10.62.217.179
}
virtual_ipaddress {
192.168.1.1
192.168.1.2
192.168.1.3
192.168.1.4
192.168.1.5
}
track_script {
chk_nginx_service
chk_manual_failover
}
notify "/usr/lib/keepalived/nginx-ha-notify"
}

##BACKUP:
[10:52 AM] Allen, Scott
global_defs {
vrrp_version 3
}vrrp_script chk_manual_failover {
script "/usr/lib/keepalived/nginx-ha-manual-failover"
interval 10
weight 50
}vrrp_script chk_nginx_service {
script "/usr/lib/keepalived/nginx-ha-check"
interval 3
weight 50
}vrrp_instance VI_1 {
interface ens160
priority 101
virtual_router_id 51
advert_int 1
accept
garp_master_refresh 5
garp_master_refresh_repeat 1
unicast_src_ip 10.62.217.183/22
unicast_peer {
10.62.217.179
}
virtual_ipaddress {
192.168.1.1
192.168.1.2
192.168.1.3
192.168.1.4
192.168.1.5
}
track_script {
chk_nginx_service
chk_manual_failover
}
notify "/usr/lib/keepalived/nginx-ha-notify"
}

[10:52 AM] Allen, Scott
global_defs {
vrrp_version 3
}vrrp_script chk_manual_failover {
script "/usr/lib/keepalived/nginx-ha-manual-failover"
interval 10
weight 50
}vrrp_script chk_nginx_service {
script "/usr/lib/keepalived/nginx-ha-check"
interval 3
weight 50
}vrrp_instance VI_1 {
interface ens160
priority 100
virtual_router_id 51
advert_int 1
accept
garp_master_refresh 5
garp_master_refresh_repeat 1
unicast_src_ip 10.62.217.179/22
unicast_peer {
10.62.217.183
}
virtual_ipaddress {
192.168.1.1
192.168.1.2
192.168.1.3
192.168.1.4
192.168.1.5
}
track_script {
chk_nginx_service
chk_manual_failover
}
notify "/usr/lib/keepalived/nginx-ha-notify"
}

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them
none
**System Log entries**
Full keepalived system log entries from when keepalived started, if applicable
none
**Additional context**
Please loop @sallen1301 in this communications.

**Comment by pqarmitage** [comment]
@Adi-AA @sallen1301 The addresses you are adding are /32 addresses. When a /32 address is configured on an interface, no entry is added to the routeing table (because there is no other address in the subnet to route to). For example:
```
# ip addr show eth5
46: eth5@if47: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether e6:b1:e0:10:3c:17 brd ff:ff:ff:ff:ff:ff link-netns medium
    inet 10.1.5.3/24 brd 10.1.5.255 scope global eth5
       valid_lft forever preferred_lft forever
    inet 10.62.217.183/22 scope global eth5
       valid_lft forever preferred_lft forever
    inet6 fd00:0:1:105::3/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::e4b1:e0ff:fe10:3c17/64 scope link 
       valid_lft forever preferred_lft forever

# ip rou
10.1.5.0/24 dev eth5 proto kernel scope link src 10.1.5.3 
10.62.216.0/22 dev eth5 proto kernel scope link src 10.62.217.183

# ip addr add 10.2.5.1 dev eth5
# ip addr show eth5
46: eth5@if47: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether e6:b1:e0:10:3c:17 brd ff:ff:ff:ff:ff:ff link-netns medium
    inet 10.1.5.3/24 brd 10.1.5.255 scope global eth5
       valid_lft forever preferred_lft forever
    inet 10.62.217.183/22 scope global eth5
       valid_lft forever preferred_lft forever
    inet 10.2.5.1/32 scope global eth5
       valid_lft forever preferred_lft forever
    inet6 fd00:0:1:105::3/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::e4b1:e0ff:fe10:3c17/64 scope link 
       valid_lft forever preferred_lft forever

# ip rou
10.1.5.0/24 dev eth5 proto kernel scope link src 10.1.5.3 
10.62.216.0/22 dev eth5 proto kernel scope link src 10.62.217.183 
```

If you add the address with a subnet mask of less than 32, then an entry does get added to the (kernel) routeing table:
```
# ip addr del 10.2.5.1/32 dev eth5
# ip addr add 10.2.5.1/24 dev eth5
# ip addr show eth5
46: eth5@if47: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether e6:b1:e0:10:3c:17 brd ff:ff:ff:ff:ff:ff link-netns medium
    inet 10.1.5.3/24 brd 10.1.5.255 scope global eth5
       valid_lft forever preferred_lft forever
    inet 10.62.217.183/22 scope global eth5
       valid_lft forever preferred_lft forever
    inet 10.2.5.1/24 scope global eth5
       valid_lft forever preferred_lft forever
    inet6 fd00:0:1:105::3/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::e4b1:e0ff:fe10:3c17/64 scope link 
       valid_lft forever preferred_lft forever

# ip rou
10.1.5.0/24 dev eth5 proto kernel scope link src 10.1.5.3 
10.2.5.0/24 dev eth5 proto kernel scope link src 10.2.5.1 
10.62.216.0/22 dev eth5 proto kernel scope link src 10.62.217.183
```
Your keepalived configuration does not specify a subnet mask for the `virtual_ipaddress`es and so the subnet mask defaults to /32, and hence no route is added.

If you change your configuration to specify the virtual ip addresses as follows:
```
        virtual_ipaddress {
                192.168.1.1/24
                192.168.2.2/30
                192.168.3.3/28
                192.168.4.4/26
                192.168.5.5/25
        }
```
(note I have changed the addresses so that they are now in different subnets)

then routes are added:
```
# ip rou
10.1.5.0/24 dev eth5 proto kernel scope link src 10.1.5.3 
10.62.216.0/22 dev eth5 proto kernel scope link src 10.62.217.183 
192.168.1.0/24 dev eth5 proto kernel scope link src 192.168.1.1 
192.168.2.0/30 dev eth5 proto kernel scope link src 192.168.2.2 
192.168.3.0/28 dev eth5 proto kernel scope link src 192.168.3.3 
192.168.4.0/26 dev eth5 proto kernel scope link src 192.168.4.4 
192.168.5.0/25 dev eth5 proto kernel scope link src 192.168.5.5 
```

Propagating those routes into bird is of course another matter and is down to your configuration of bird.

I hope this helps.
