### ISSUE TITLE
where can i get the dpkg-buildpackage script about keepalived.

### ISSUE THREAD

**Issue by s09816** [acassen/keepalived#213]
I want to compile the source code, and then package it.there is not a package script in the source code.

other project have the package script,such as ceph,tgt   can you provide a script?

**Comment by wienczny** [comment]
Having a "debian"-Directory inside the upstream source is not considered a good practice by Debian maintainers. You shoud use keepalived_1.2.19-1.debian.tar.xz linked here https://packages.debian.org/jessie/keepalived or apt-get source keeepalived to get you started
