### ISSUE TITLE
Can not set virtual route to table greater than 255

### ISSUE THREAD

**Issue by huihongxiao** [acassen/keepalived#214]
Keepalived v1.2.19 (09/05,2015) is used.

I want to create virtual_routes which belongs to a specified route table. I can get the expected result if the route table id is less than 255. However, If I specify the table id greater than 255, the route will fall into the main routing table. For example, 

virtual_routes {
        0.0.0.0/0 gw 192.168.0.1 table 1024
}

**Comment by gurubert** [comment]
There are only 255 routing tables in the kernel, you cannot assign an ID larger than 252.

255 (local), 254 (main) and 253 (default) are reserved values.

**Comment by huihongxiao** [comment]
But with ip route command, I can set table ID larger than 255.

[root@ha-controller fedora]# cat /etc/iproute2/rt_tables 
253     default
1024    723035c7-f587-4eb9-ab64-b5eb80443b21
1025    noscope
0       unspec
254     main
255     local
