### ISSUE TITLE
How to obtain the ARM version of keepalived?

### ISSUE THREAD

**Issue by fantastic2085** [acassen/keepalived#2141]
_Support requests should be sent via_ https://groups.io/g/keepalived-users

**Describe why you are unable to send the support request to the above email list**
Understanding why you cannot use the email list should help us improve it.

**Describe what you need help/support for**
A clear and concise description of what you need help with.
**I don't know where can I get a Keepalived docker image that supports arm**

**Details of what you would like to do with keepalived**
Describe in details what you would like to achieve with keepalived

**Keepalived version**
Output of `keepalived -v` (a later version of keepalived might be needed).

**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu]
 - Version [e.g. 29]
 - Architecture [e.g. x86_64]

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details 

**Configuration file:**
Full copy of your configuration file, obfuscated if necessary to protect passwords and IP addresses

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started, if applicable

**Additional context**

**Comment by cyb3rz3us** [comment]
If you're running the RH family ofLinux, `keepalived` in appstream repo...

**Comment by fantastic2085** [comment]
I want to use keepalive's Docker image, https://hub.docker.com/r/arcts/keepalived/tags, Can keepalived downloaded from this link run on arm processors?

**Comment by pqarmitage** [comment]
I run keepalived on ARMv5, ARMv7 and ARMv8 processors. I simply download the source from Github, install the prerequisite packages, build it and then install it (see the INSTALL file in the root of the source tree for insttructions).

The docker images that are at [https://hub.docker.com/r/arcts/keepalived/tags](https://hub.docker.com/r/arcts/keepalived/tags) are all extremely old versions of keepalived, so you should not use them.

The keepalived project does not support docker images, so if you want a docker image you will need to find a third party's image.
