### ISSUE TITLE
Can we have the prehand notify?

### ISSUE THREAD

**Issue by SimonLiuhd** [acassen/keepalived#2144]
**Is your feature request to resolve a problem or provide enhanced functionality? Please describe.**
Can we have the notify before status changes?

**Describe the solution you would like**
To resolve the brain slipt:
        before a machine will have the virtual IP address, I want to execute a script to check that its pair has the same virtual IP address ot not (use addtional network channel), if the pair holds the same VIP, in the script we can keep the instance to have the VIP and still keep the BACKUP status.

**Would the feature request be of benefit only to you, or is it more generally applicable?**
I think it is general.

**Comment by pqarmitage** [comment]
I don't see how this can work. If the current master system dies, it will take some time for the other system, which should now become master, to timeout connecting to the old master. If you have two backup systems, the order of them timing out cannot be guaranteed. If the two backup systems have priorities 101 and 100 and you are using VRRPv3 with even 1 second advert intervals, the system with priority 100 will only wait for 1/256 second longer than the system with priority 101 to take over as master. If you are using 10msec advert intervals, then the additional wait time is only 1/25600 second.

A better solution, if you have an additional network channel, is to run VRRP over that interface as well, and to put the two VRRP instances on each system into a sync group.

**Comment by SimonLiuhd** [comment]
> I don't see how this can work. If the current master system dies, it will take some time for the other system, which should now become master, to timeout connecting to the old master. If you have two backup systems, the order of them timing out cannot be guaranteed. If the two backup systems have priorities 101 and 100 and you are using VRRPv3 with even 1 second advert intervals, the system with priority 100 will only wait for 1/256 second longer than the system with priority 101 to take over as master. If you are using 10msec advert intervals, then the additional wait time is only 1/25600 second.
> 
> A better solution, if you have an additional network channel, is to run VRRP over that interface as well, and to put the two VRRP instances on each system into a sync group.

Thanks for your pefect reply.
Thanks a lot
