### ISSUE TITLE
Keepalived to support ipv4 and ipv6 on same vrrp virtual router-id

### ISSUE THREAD

**Issue by shwethakeepalived** [acassen/keepalived#2146]
_Support requests should be sent via_ https://groups.io/g/keepalived-users
We have customer requirement to use the dual - ipv4 and ipv6 on same interface and same virtual router id. 
But when ipv6 VIP is added under virtual_ipaddress_excluded , getting netlink error.

**Describe what you need help/support for**
Need to support ipv4 and ipv6 on same vrid which is part of same interface

**Details of what you would like to do with keepalived**
Need ipv6 and ipv4 support. Can you please help us or provide guideline to help in configuring same.

**Keepalived version**
v2.0.19

**Distro (please complete the following information):**
 - Name [Ubuntu]
 - Version 
 - Architecture
 - 4.14.67-yocto-standard

**Configuration file:**
Full copy of your configuration file, obfuscated if necessary to protect passwords and IP addresses
vrrp_instance VI_1_100
{
  interface 1.x19.301
  virtual_router_id 2
  use_vmac
  garp_master_refresh 60
  priority 200
  advert_int 1
  virtual_ipaddress
  {
    xx.xx.xx.100/24
  }
  virtual_ipaddress_excluded
  {
    xxxx::100/64
  }
}

Mon Jun 20 22:42:24 2022: Reloading
Mon Jun 20 22:42:24 2022: Opening file '/etc/arc/vrrpd/keepalived.conf'.
Mon Jun 20 22:42:24 2022: (VI_2_301) Found matching interface vrrp.2
Mon Jun 20 22:42:24 2022: Assigned address xx.xx.xx.1 for interface 1.x19.301
Mon Jun 20 22:42:24 2022: Assigned address fe80::4665:7fff:fea5:5221 for interface 1.x19.301
Mon Jun 20 22:42:24 2022: Adding iptables rules to default chains, but chains not configured
Mon Jun 20 22:42:24 2022: (VI_2_301) ip address xx.xx.xx.100/24 dev 1.x19.301, no longer exist
Mon Jun 20 22:42:24 2022: (VI_2_301) ip address xxxx::100/64 dev 1.x19.301, no longer exist
Mon Jun 20 22:42:24 2022: (VI_2_301) setting VIPs.
Mon Jun 20 22:42:24 2022: (VI_2_301) setting E-VIPs.
**Mon Jun 20 22:42:24 2022: Netlink: error: Permission denied(13), type=RTM_NEWADDR(20), seq=1655719590, pid=0**
Mon Jun 20 22:42:24 2022: Sending gratuitous ARP on vrrp.2 for xx.xx.xx.100
Mon Jun 20 22:42:24 2022: (VI_2_301) Sending/queueing gratuitous ARPs on vrrp.2 for xx.xx.xx.100
Mon Jun 20 22:42:24 2022: Sending unsolicited Neighbour Advert on vrrp.2 for xxxx::100
Mon Jun 20 22:42:24 2022: (VI_2_301) Sending/queueing Unsolicited Neighbour Adverts on vrrp.2 for xxxx::100
Mon Jun 20 22:42:24 2022: Sending gratuitous ARP on vrrp.2 for xx.xx.xx.100

root@ASM3001:/var/log# ifconfig vrrp.2   --------------------> here only ipv4 is created
vrrp.2    Link encap:Ethernet  HWaddr 00:00:5e:00:01:02
          inet addr:xx.xx.xx.100  Bcast:0.0.0.0  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:15432 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:705540 (689.0 KiB)

###################################
Changed the config file:
vrrp_instance VI_1_100
{
  interface 1.x19.100
  virtual_router_id 1
  use_vmac
  garp_master_refresh 60
  priority 100
  advert_int 1
  virtual_ipaddress
  {
    xxxx::10/64
  }
  virtual_ipaddress_excluded
  {
    xx.xx.xx.100/24
  }
}

root@ASM3001:/var/log# ifconfig vrrp.1
vrrp.1    Link encap:Ethernet  HWaddr 00:00:5e:00:02:01
          inet addr:xx.xx.xx.100  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::4665:7fff:fea5:5221/64 Scope:Link
          inet6 addr: xxxx::10/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:103 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:7842 (7.6 KiB)

Only ipv6 advert is sent. ipv4 is not sent
root@ASM3001:/var/log# tcpdump -i 1.x19.100
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on 1.x19.100, link-type EN10MB (Ethernet), capture size 262144 bytes
22:50:36.660322 IP6 fe80::4665:7fff:fea5:5221 > ff02::12: ip-proto-112 24

Mon Jun 20 22:48:33 2022: (VI_1_100) Receive advertisement timeout
Mon Jun 20 22:48:33 2022: (VI_1_100) Entering MASTER STATE
Mon Jun 20 22:48:33 2022: (VI_1_100) using locally configured advertisement interval (1000 milli-sec)
Mon Jun 20 22:48:33 2022: (VI_1_100) setting VIPs.
Mon Jun 20 22:48:33 2022: (VI_1_100) setting E-VIPs.
Mon Jun 20 22:48:33 2022: Sending unsolicited Neighbour Advert on vrrp.1 for xxxx::10
Mon Jun 20 22:48:33 2022: (VI_1_100) Sending/queueing Unsolicited Neighbour Adverts on vrrp.1 for xxxx::10
Mon Jun 20 22:48:33 2022: Sending gratuitous ARP on vrrp.1 for xx.xx.xx.100
Mon Jun 20 22:48:33 2022: (VI_1_100) Sending/queueing gratuitous ARPs on vrrp.1 for xx.xx.xx.100
Mon Jun 20 22:48:33 2022: Sending unsolicited Neighbour Advert on vrrp.1 for xxxx::10
Mon Jun 20 22:48:33 2022: Sending gratuitous ARP on vrrp.1 for xx.xx.xx.100
Mon Jun 20 22:48:33 2022: Sending unsolicited Neighbour Advert on vrrp.1 for xxxx::10
Mon Jun 20 22:48:33 2022: Sending gratuitous ARP on vrrp.1 for xx.xx.xx.100
Mon Jun 20 22:48:33 2022: Sending unsolicited Neighbour Advert on vrrp.1 for xxxx::10
Mon Jun 20 22:48:33 2022: Sending gratuitous ARP on vrrp.1 for xx.xx.xx.100
Mon Jun 20 22:48:33 2022: Sending unsolicited Neighbour Advert on vrrp.1 for xxxx::10
Mon Jun 20 22:48:33 2022: Sending gratuitous ARP on vrrp.1 for xx.xx.xx.100
Mon Jun 20 22:48:33 2022: send_instance_notifies to VRRPD daemon when any state change
Mon Jun 20 22:48:33 2022: send_vrrp_state_change_to_vrrpd system cmd successfull exec dcli vrrpd show master-alarm VI_1_100 vrrp.1

Please let us know config to be used to support both ipv4 and ipv6 on same virtual router id. And also to send advertisement on both

**Comment by pqarmitage** [comment]
I will have a look at this in more detail later, but in the first instance I would suggest that you use 2 VRRP instances, one IPv4 and the other IPv6. They can use the same virtual router id (VRID) since the IPv4 and IPv6 spaces are independent of each other. You could also put the 2 VRRP instances into a sync group, so that on each system they will either both be master or both be backup.

```
vrrp_sync_groupVI_1_100 {
  group {
    VI_1_100_4
    VI_1_100_6
  }
}

vrrp_instance VI_1_100_4
{
  interface 1.x19.301
  virtual_router_id 2
  use_vmac
  garp_master_refresh 60
  priority 200
  advert_int 1
  virtual_ipaddress
  {
    xx.xx.xx.100/24
  }
}

vrrp_instance VI_1_100_6
{
  interface 1.x19.301
  virtual_router_id 2
  use_vmac
  garp_master_refresh 60
  priority 200
  advert_int 1
  virtual_ipaddress
  {
    xxxx::100/64
  }
}
```

The priorities of the 2 VRRP instances on any system should be the same, but of course, the priorities will be different on different systems.

I don't know why you are getting the Netlink error - can you manually add the IPv6 address to the vrrp.2 vmac interface to see if you also get an error that way?

**Comment by shwethakeepalived** [comment]
Hi,

Thank you for the response

The above suggested change is working
vrrp_sync_groupVI_1_100 {
  group {
    VI_1_100_4
    VI_1_100_6
  }
}

vrrp_instance VI_1_100_4
{
  interface 1.x19.301
  virtual_router_id 2
  use_vmac
  garp_master_refresh 60
  priority 200
  advert_int 1
  virtual_ipaddress
  {
    xx.xx.xx.100/24
  }
}

vrrp_instance VI_1_100_6
{
  interface 1.x19.301
  virtual_router_id 2
  use_vmac
  garp_master_refresh 60
  priority 200
  advert_int 1
  virtual_ipaddress
  {
    xxxx::100/64
  }
}

The different linux device vrrp.1 for ipv6 and vrrp1.1 for ipv4 is created.

Tue Jun 21 23:01:21 2022: send_instance_notifies to VRRPD daemon when any state change
Tue Jun 21 23:01:21 2022: send_vrrp_state_change_to_vrrpd system cmd successfull exec dcli vrrpd show master-alarm VI_1_100_4 vrrp1.1
Tue Jun 21 23:01:21 2022: VRRP_Group(VI_1_100) Syncing instances to MASTER state
Tue Jun 21 23:01:21 2022: (VI_1_100_6) Entering MASTER STATE
Tue Jun 21 23:01:21 2022: (VI_1_100_6) using locally configured advertisement interval (1000 milli-sec)
Tue Jun 21 23:01:21 2022: (VI_1_100_6) setting VIPs.
Tue Jun 21 23:01:21 2022: Sending unsolicited Neighbour Advert on vrrp.1 for xxxx::10
Tue Jun 21 23:01:21 2022: (VI_1_100_6) Sending/queueing Unsolicited Neighbour Adverts on vrrp.1 for xxxx::10
Tue Jun 21 23:01:21 2022: Sending unsolicited Neighbour Advert on vrrp.1 for xxxx::10
Tue Jun 21 23:01:21 2022: Sending unsolicited Neighbour Advert on vrrp.1 for xxxx::10
Tue Jun 21 23:01:21 2022: Sending unsolicited Neighbour Advert on vrrp.1 for xxxx::10
Tue Jun 21 23:01:21 2022: Sending unsolicited Neighbour Advert on vrrp.1 for xxxx::10
Tue Jun 21 23:01:21 2022: send_instance_notifies to VRRPD daemon when any state change
Tue Jun 21 23:01:21 2022: send_vrrp_state_change_to_vrrpd system cmd successfull exec dcli vrrpd show master-alarm VI_1_100_6 vrrp.1
Tue Jun 21 23:01:26 2022: Sending gratuitous ARP on vrrp1.1 for xx.xx.xx.100
Tue Jun 21 23:01:26 2022: (VI_1_100_4) Sending/queueing gratuitous ARPs on vrrp1.1 for xx.xx.xx.100

And advert is sent for both of them

Thank you

**Comment by luckylinux** [comment]
I attempted to use the snippets of code in `keepalived 2.2.7` (Debian GNU/Linux Bookworm: `Keepalived v2.2.7 (01/16,2022)`) and `keepalived 2.28` (Fedora GNU/Linux 40: `Keepalived v2.2.8 (04/04,2023), git commit v2.2.7-154-g292b299e+`), getting an error in both cases:


The Key is to change
```
vrrp_sync_groupVI_1_100 {
group {
VI_1_100_4
VI_1_100_6
}
}
```

To:
```
vrrp_sync_group VI_1_100 {
group {
VI_1_100_4
VI_1_100_6
}
}
```

Note the Space after `vrrp_sync_group`.

**Comment by araujorm** [comment]
We have noticed the "Netlink: error: Permission denied(13), type=RTM_NEWADDR(20)" issue with IPv6 VIP addresses not being configured by keepalived with a single VRRP instance (IPv6 VIP addresses added under virtual_ipaddress_excluded) when using NetworkManager and having IPv6 explicitly disabled. If we configure IPv6 to have at least "Link-Local" configuration (e.g. using nmtui) then keepalived works as expected.

Could it be that when the IPv6 VIPs are configured under regular virtual_ipaddress blocks something else is done that prevents this happening, and the "Permission denied" error is in fact a misleading message, consisting on another error?

Anyway, this setup seems to be working for us (Rocky Linux 9), with a single VRRP instance and without the need of a vrrp_sync_group.

**Comment by pqarmitage** [comment]
@araujorm Could you please provide a copy  of your configuration so that I can try it out. Also, the output of `ip addr show` before you run keepalived would be helpful.
