### ISSUE TITLE
Script always failed (exited with status 1)

### ISSUE THREAD

**Issue by BramFr** [acassen/keepalived#2147]
**Describe what you need help/support for**
Explain why i`ll get a exited code 1. If i run the script local everythings works fine.

**Details of what you would like to do with keepalived**
Lookup if pod (kubernetes) is running on specific node.

**Keepalived version**
root@linux01:~# keepalived -v
Keepalived v2.1.5 (07/13,2020)

**Distro (please complete the following information):**
root@linux01:~# uname -a
Linux linux01 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

**Details of any containerisation or hosted service (e.g. AWS)**
Installed native

**Configuration file:**
```
vrrp_script chk_adguard-primary {
    script "/etc/keepalived/chk_adguard-primary.sh"
    #script "/usr/bin/kubectl get pod --field-selector spec.nodeName=linux01 -l app=adguard-primary -n security --ignore-not-found=false | /usr/bin/grep -i Running"
    interval 1                      
    user root
}
vrrp_instance VI_2 {
    state MASTER
    interface eno1
    virtual_router_id 102
    priority 100
    advert_int 1
    authentication {
        auth_type xxxxxxxxxxxxxxxxxxxx
        auth_pass xxxxxxxxxxxxxxxxxxxx
    }
    track_script {
        chk_adguard-primary
    }
    unicast_src_ip 192.168.1.20      # The IP address of this machine
    unicast_peer {
      192.168.1.21                         # The IP address of peer machines
      192.168.1.22                         # The IP address of peer machines
    }
    virtual_ipaddress {
        192.168.1.31
    }
}
```

**Notify and track scripts**
Script:
```
root@linux01:~# cat /etc/keepalived/chk_adguard-primary.sh
#!/bin/bash
var=$(/usr/bin/kubectl get pod --field-selector spec.nodeName=linux01 -l app=adguard-primary -n security --ignore-not-found=false)
if [[ $var == *"Running"* ]]; then
 exit 0
else
 exit 1
fi
```
run script:
```
root@linux01:~# bash /etc/keepalived/chk_adguard-primary.sh && echo 0 || echo 1
0
```

**System Log entries**
```
Jun 24 14:11:14 linux01 Keepalived_vrrp[1048177]: Script `chk_adguard-primary` now returning 1
Jun 24 14:11:14 linux01 Keepalived_vrrp[1048177]: VRRP_Script(chk_adguard-primary) failed (exited with status 1)
Jun 24 14:11:14 linux01 Keepalived_vrrp[1048177]: (VI_2) Entering FAULT STATE
```

**Comment by pqarmitage** [comment]
How are you running keepalived? If you are running it via systemd, it will be running in a restricted environment that may, for example, not have access to kubectl, or deny kubectl access to resources that it needs.

If you are not already doing so, can you try running keepalived from the command line, and see if you still get the problem.

**Comment by BramFr** [comment]
> How are you running keepalived? If you are running it via systemd, it will be running in a restricted environment that may, for example, not have access to kubectl, or deny kubectl access to resources that it needs.
> 
> If you are not already doing so, can you try running keepalived from the command line, and see if you still get the problem.

You are right..

```
root@linux01:~# /usr/sbin/keepalived --dont-fork -D -l
..
..
Fri Jun 24 14:37:33 2022: VRRP_Script(chk_adguard-primary) succeeded
Fri Jun 24 14:37:33 2022: (VI_2) Entering BACKUP STATE
Fri Jun 24 14:37:33 2022: VI_2: sending gratuitous ARP for 192.168.1.20
Fri Jun 24 14:37:33 2022: Sending gratuitous ARP on eno1 for 192.168.1.20
```
Is there any why to fix/workaround this?

**Comment by pqarmitage** [comment]
@BramFr The answer is Yes, there is a way to fix this, but unfortunately I don't know how.

A useful starting point to read (I searched for "systemd service confinement") might be: [reducing-your -attack-surface-with-systemd](https://krvtz.net/posts/reducing-your-attack-surface-with-systemd.html).  Of course, you want to go the opposite way and open up what the keepalived service is allowed to do.

Resolving this is outside the scope of keepalived, but the above should give you some pointers for what to look at.
