### ISSUE TITLE
how to configure Keepalived for external user

### ISSUE THREAD

**Issue by hkvincent** [acassen/keepalived#2151]
I saw some documents about Keepalived that just told me how to set it accessible in the same network, and how to configure it can be accessed globally?

Let's say

1. I have bought two EC2 in AWS, there have different IPs and may not be in the same network, how do I configure the virtual IP section?

2. Maybe I bought two servers in the same network, I can configure it, but the external user how to use the private IP to access our website (Nginx).

I understand how to configure in a private network like assigning it VIP to be 192.168.100.100, and internal users can access this server with 192.168.100.100. , But I do not understand the principle of the public used in Keepalived,

**Comment by pqarmitage** [comment]
@hkvincent I think you are asking very reasonable questions, and I certainly cannot give you direct answers.

In the first place what you need to do is
1. work out how to set up what you want to achieve without considering or using keepalived.
Once you have that sorted and working
2. consider how to implement that using keepalived. 

If you need help sorting out 1 above, then it is not a keepalived issue and you will need to look for support elsewhere. If you have resolved 1 above, and then need help sorting out 2, then if you provide all the information relating to what you configured for 1 above, then we can help with the keepalived configuration. Either open a new issue or update this one and we can reopen it.
