### ISSUE TITLE
RPM: cannot find file ~/rpmbuild/BUILDROOT/keepalived-2.2.7-1.el7.x86_64/etc/keepalived/keepalived.conf

### ISSUE THREAD

**Issue by SimonLiuhd** [acassen/keepalived#2155]
**Describe the bug**
when execute "make rpm", it breaks with error message "cannot find file ~/rpmbuild/BUILDROOT/keepalived-2.2.7-1.el7.x86_64/etc/keepalived/keepalived.conf"

**To Reproduce**
download the source for v2.2.7, enter the uncompressed folder, modify the keepalived.spec.in per [commit b8d4758a944bfa04d7fa4ffbdfcf0fba78e45d0c](https://github.com/acassen/keepalived/commit/b8d4758a944bfa04d7fa4ffbdfcf0fba78e45d0c),
the execute with "./confuration" and "make rpm)

**Expected behavior**
the make rpm can be succeeded

**Keepalived version**
2.2.7

**Distro (please complete the following information):**
 - Name: centos
 - Version: 7.9
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
normal VM on vmware

**Comment by pqarmitage** [comment]
You also need to apply commit 92f9f05, and possibly d6f5fc6.

**Comment by SimonLiuhd** [comment]
It seams that it has been fixed in master.
Could we release a nre version?
