### ISSUE TITLE
There are memory leaks when the configuration is repeated

### ISSUE THREAD

**Issue by kwb0523** [acassen/keepalived#2165]
**Describe the bug**
During the asan version test, a memory leak was detected, the reason is that when the configuration was repeatedly configured, the original configuration would be overwritten, but its memory was not released, so resulting a memory leak.

**To Reproduce**

Duplicate configuration virtualhost in url.

    real_server 192.168.1.1 80 {
        weight 1
        HTTP_GET {
            url {
                virtualhost test
                path /index.html
                status_code 200
                virtualhost test
            }
            bindto 192.168.1.1
            connect_port 80
            connect_timeout 1
            delay_before_retry 1
        }
    }

**Expected behavior**
systemctl start keepalived
systemctl stop keepalived

**Keepalived version**
Keepalived v2.2.4 (08/21,2021)

**Additional context**
asan log report mem leak in url_virtualhost_handler.

**Comment by kwb0523** [comment]
thete are some other configurations have the same problems, I will make some commits to fix them.

**Comment by pqarmitage** [comment]
@kwb0523 Many thanks for the patches; now merged.
