### ISSUE TITLE
How the keepalived's open files work for services

### ISSUE THREAD

**Issue by SimonLiuhd** [acassen/keepalived#2167]
**Describe the issue**
Some services are managed by keepalived (keepalived notify_master/backup to start/stop the service), Does the ulimit open files of the services inherit from keepalived service? If they inherit，the number is shared by all the services?

**To Reproduce**
Any steps necessary to reproduce the behaviour:

**Expected behavior**

**Keepalived version**
Output of `keepalived -v`

**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu]
 - Version [e.g. 29]
 - Architecture [e.g. x86_64]

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
A full copy of the configuration file, obfuscated if necessary to protect passwords and IP addresses

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started

**Did keepalived coredump?**
If so, can you please provide a stacktrace from the coredump, using gdb.

**Additional context**

**Comment by pqarmitage** [comment]
See the man page setrlimit(2):
```
A child process created via fork(2) inherits its parent's resource limits.  Resource limits are preserved across execve(2).
```
