### ISSUE TITLE
let keepalived become the initial state with nopeermpt mode

### ISSUE THREAD

**Issue by jhdu1994** [acassen/keepalived#2168]
- Keepalived configuration for both devices has `state` field as `BACKUP`.  These two devices will negotiate the master and backup according to the `priority`. How do I clean up keepalived again so that both devices renegotiate master and backup based on `priority` value in `nopreempt` mode ? That is, let keepalived become the initial state

- keepalived version:  Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

config info
```conf
global_defs {
  router_id 0
  script_user root
  enable_script_security
}
vrrp_instance VI_1 {
  state BACKUP
  interface eth1
  virtual_router_id 51
  priority 100
  unicast_src_ip 1.1.1.200
  unicast_peer {
    1.1.1.226
  }
  advert_int 1
  authentication {
    auth_type PASS
    auth_pass 1111
  }
  track_interface {
    eth0
    eth1
  }
  virtual_ipaddress {
    23.23.23.23/23 dev eth0
  }
  nopreempt
  preempt_delay 300
}
```

**Comment by jhdu1994** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by pqarmitage** [comment]
@jhdu1994 Your previous comment does not appear to be in English.

**Comment by pqarmitage** [comment]
The above message from @jhdu1994 appears to translate as:

_This is a vacation autoresponse from QQ mailbox._

_Hello, recently, I was on leave, unable to personally reply to your message. I will be after the holidays and get back to you as soon as possible._

**Comment by jhdu1994** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by pqarmitage** [comment]
The only way to do this is to remove to `nopreempt` element of the configuration.

1. Edit the keepalived configuration on the higher priority instance to comment out `nopreempt`
2. Make keepalived re-read its configuration - execute `kill -HUP $(cat /var/run/keepalived.pid)`
3. Wait for the higher priority instance to take over as master
4. Edit the keepalived configuration on the higher priority instance to reinstate `nopreempt`

This will make the higher priority instance become master again, which I think is what you want to achieve.
