### ISSUE TITLE
BACKUP state doesn't work

### ISSUE THREAD

**Issue by HalacliSeda** [acassen/keepalived#2171]
Hello,
I use keepalived 2.1.5. 
My backup state also run as master. 
Master keepalived.conf:
vrrp_script check_haproxy {
 script "/usr/bin/killall -0 haproxy"
 interval 2
 weight -5
 fall 2
 rise 1
}
vrrp_instance VI_01 {
 state MASTER
 interface eth0
 virtual_router_id 1
 priority 150
 advert_int 1
 virtual_ipaddress {
  10.245.20.22 dev eth0 label eth0:1
 }
 authentication {
  auth_type PASS
  auth_pass gHKnCsaQ
 }
 track_script {
  check_haproxy
 }
}

Backup keepalived.conf:
vrrp_script check_haproxy {
 script "/usr/bin/killall -0 haproxy"
 interval 2
 weight -5
 fall 2
 rise 1
}
vrrp_instance VI_01 {
 state BACKUP
 interface eth0
 virtual_router_id 1
 priority 70
 advert_int 1
 virtual_ipaddress {
  10.245.20.22 dev eth0 label eth0:1
 }
 authentication {
  auth_type PASS
  auth_pass gHKnCsaQ
 }
 track_script {
  check_haproxy
 }
}

And journal log here:
Keepalived_vrrp[1440321]: Registering Kernel netlink reflector
Keepalived_vrrp[1440321]: Registering Kernel netlink command channel
Keepalived_vrrp[1440321]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived_vrrp[1440321]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Keepalived_vrrp[1440321]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Keepalived_vrrp[1440321]: Assigned address 10.245.20.25 for interface eth0
Keepalived_vrrp[1440321]: Assigned address fe80::f816:3eff:fe94:6c80 for interface eth0
Keepalived_vrrp[1440321]: Registering gratuitous ARP shared channel
Keepalived_vrrp[1440321]: (VI_01) removing VIPs.
Keepalived_vrrp[1440321]: (VI_01) Entering BACKUP STATE (init)
Keepalived_vrrp[1440321]: VRRP sockpool: [ifindex(  2), family(IPv4), proto(112), fd(11,12)]
Keepalived_vrrp[1440321]: VRRP_Script(check_haproxy) succeeded
Keepalived_vrrp[1440321]: (VI_01) Receive advertisement timeout
Keepalived_vrrp[1440321]: (VI_01) Entering MASTER STATE
Keepalived_vrrp[1440321]: (VI_01) setting VIPs.
Keepalived_vrrp[1440321]: (VI_01) Sending/queueing gratuitous ARPs on eth0 for 10.245.20.22
Keepalived_vrrp[1440321]: Sending gratuitous ARP on eth0 for 10.245.20.22
Keepalived_vrrp[1440321]: Sending gratuitous ARP on eth0 for 10.245.20.22
Keepalived_vrrp[1440321]: Sending gratuitous ARP on eth0 for 10.245.20.22
Keepalived_vrrp[1440321]: Sending gratuitous ARP on eth0 for 10.245.20.22
Keepalived_vrrp[1440321]: Sending gratuitous ARP on eth0 for 10.245.20.22

I always set up this way but this time it doesn't work. How can I resolve this problem? Thank you.

**Comment by pqarmitage** [comment]
Backup state DOES work. The only reason that your backup instance becomes master is that it is not receiving adverts from the master. You need to investigate why the backup is not receiving adverts.
