### ISSUE TITLE
Nopreempt is set, and the VIP will still be occupied after the master node goes offline and goes online

### ISSUE THREAD

**Issue by yanliangchao** [acassen/keepalived#2174]
### **This is the content of the configuration file**

```
global_defs {
   router_id MES
   vrrp_skip_check_adv_addr
   vrrp_garp_interval 0
   vrrp_gna_interval 0
}
vrrp_script chk_nginx {
    script "/usr/local/keepalived-1.3.2/sh/check_nginx.sh"
    interval 2
    weight 2
}
vrrp_instance VI_1 {
    state BACKUP
    interface eth0
    virtual_router_id 81
    priority 100
    advert_int 1
    nopreempt
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    track_script {
       chk_nginx
    }
    virtual_ipaddress {
        10.110.33.181
    }
}
```

### **This is the log of the master keepalived during the period of donw and up of the master node eth0**
![image](https://user-images.githubusercontent.com/32755174/182511268-84d3fb72-e8ea-4916-bf92-6c5554df1765.png)

### **This is the log of the slave keepalived during the period of donw and up of the master node eth0**
![image](https://user-images.githubusercontent.com/32755174/182511454-73924837-3ebd-498a-ab79-770103535c1a.png)

**We can see that during the master node eth0 down, the slave node takes over the VIP, but after the master node eth0 up, the VIP is snatched from the slave node. I have set nopreempt in the configuration. I don't know how to carry out the next step of troubleshooting. Can you help me? Looking forward to your reply.**

**Comment by pqarmitage** [comment]
I am guessing, but you don't actually say, that the version of keepalived you are using is v1.3.2. That version is extremely old, and there have been over 3000 bug fix and enhancement commits since then. So of these relate to nopreempt which didn't work properly in older versions.

If you upgrade to a recent version, e.g. v2.2.7 it should resolve your issue.

**Comment by yanliangchao** [comment]
Thank you for your reply. I will try them
