### ISSUE TITLE
Cannot compile version 2.2.7 on debian10

### ISSUE THREAD

**Issue by abolinhas** [acassen/keepalived#2177]
**Describe the bug**
I can not compile the version 2.2.7 on debian 10, i get this error
```
checking for g_bus_own_name in -lgio-2.0... no

configure: error: DBUS support requested but libgio-2.0 not found.
```

**To Reproduce**
`./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode  --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus --enable-dbus-create-instance --enable-json --enable-bfd --disable-systemd`

**Expected behavior**
Compilation successfully

**Keepalived version**
2.2.7

**Distro (please complete the following information):**
 - Name: Debian
 - Version: 10.10
 - Architecture: 64

**Additional context**
libgio is installed with version 2.58 (based on last system update)
`libglib2.0-0 is already the newest version (2.58.3-2+deb10u3).`

**Comment by pqarmitage** [comment]
You need to install the dev version of libglib2, i.e. libglib2.0-dev (see the INSTALL file in the root of the source tree).

**Comment by abolinhas** [comment]
Fixed, thanks
