### ISSUE TITLE
nopreempt mode not work in dial-pluggin bond NIC cable

### ISSUE THREAD

**Issue by tangkelu** [acassen/keepalived#2178]
**Describe what you need help/support for**
    Hi，I have 2 nodes with bond network interface run dial-plugging cable failover test. But the high priority(200) always keep the VIPs，I think it really takes 30 seconds for the bond network interface from [Netlink reports bond0 up] to traffic [Received advert], at this point it will enter the BACKUP state and re-enter the MASTER state. I don't know how to avoid high priority node always preempt VIPs,  nopreempt not work, please help! Thanks.

Below is my reproduce steps:
1. high priority(200) node in MASTER state, keep VIPs
2. dial-out high priority(200) node bond network interface cable, keepalived entering FAULT state, low priority(100) node entering MASTER state
3. plugging high priority(200) node network interface cable, keepalived reports bond0 up, entering BACKUP state
4. after 3s keepalived received advert timeout, entering MASTER state, setting VIPs
5. after 30s (from bond0 up) keepalived received advert from low priority(100) , ours 200, forcing new elect 
6. low priority(100) node VIPs removed

**Keepalived version**
[root@node-12-240 ]# keepalived --version
Keepalived v2.0.20 (unknown)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019

configure options: LDFLAGS=-L/usr/local/openssl-1.1.1k/lib/ /usr/local/openssl-1.1.1k/lib/libssl.a /usr/local/openssl-1.1.1k/lib/libcrypto.a --prefix=/usr --disable-dependency-tracking --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-nftables --disable-libiptc --with-init=systemd PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig

Config options:  IPTABLES_CMD LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RESET_ON_FORK

**Distro (please complete the following information):**
CentOS 7

**Configuration file:**
bond network interface configuration
[root@node-12-240 ]# cat /etc/sysconfig/network-scripts/ifcfg-bond0
DEVICE="bond0"
ONBOOT=yes
BONDING_OPTS="mode=6 miimon=100"
BOOTPROTO=static
IPADDR=10.4.12.240
NETMASK=255.255.255.0
GATEWAY=10.4.12.1

keepalived configuration(current node priority is 200, another node priority is 100）
[root@node-12-240 high]# cat /etc/keepalived/keepalived.conf
global_defs {
    router_id ef6a3512-d578-11eb-86fa-02423addbc44
    vrrp_garp_master_refresh 30
}

vrrp_instance INTERNAL_HA {

    unicast_peer {
        11.9.7.234
    }

    priority 200

    virtual_ipaddress {
        11.9.7.8/24 label bond0:iv dev bond0
    }

    virtual_router_id 8
    unicast_src_ip 11.9.7.119
    interface bond0

    state BACKUP
    advert_int 1
    nopreempt
    preempt_delay 40
    notify_master /etc/slb/scripts/INTERNAL_HA/entering_master.py
    notify_backup /etc/slb/scripts/INTERNAL_HA/entering_backup.py

    authentication {
        auth_type PASS
        auth_pass 111111
    }
}

vrrp_instance SLB_HA {

    unicast_peer {
        10.4.12.241
    }

    priority 200

    virtual_ipaddress {
        10.4.12.243/24 label bond0:ov dev bond0
    }

    virtual_router_id 243
    unicast_src_ip 10.4.12.240
    interface bond0
    state BACKUP
    advert_int 1
    nopreempt
    preempt_delay 40
    notify_master /etc/slb/scripts/SLB_HA/entering_master.py
    notify_backup /etc/slb/scripts/SLB_HA/entering_backup.py

    authentication {
        auth_type PASS
        auth_pass 111111
    }
}

**System Log entries**
Aug 09 15:15:15 node-12-240 Keepalived_vrrp[1108437]: Netlink reports bond0 down
Aug 09 15:15:15 node-12-240 Keepalived_vrrp[1108437]: (INTERNAL_HA) Entering FAULT STATE
Aug 09 15:15:15 node-12-240 Keepalived_vrrp[1108437]: (INTERNAL_HA) sent 0 priority
Aug 09 15:15:15 node-12-240 Keepalived_vrrp[1108437]: (INTERNAL_HA) removing VIPs.
Aug 09 15:15:15 node-12-240 Keepalived_vrrp[1108437]: (SLB_HA) Entering FAULT STATE
Aug 09 15:15:15 node-12-240 Keepalived_vrrp[1108437]: (SLB_HA) sent 0 priority
Aug 09 15:15:15 node-12-240 Keepalived_vrrp[1108437]: (SLB_HA) removing VIPs.
Aug 09 15:15:53 node-12-240 Keepalived_vrrp[1108437]: Netlink reports bond0 up
Aug 09 15:15:53 node-12-240 Keepalived_vrrp[1108437]: (INTERNAL_HA) Entering BACKUP STATE
Aug 09 15:15:53 node-12-240 Keepalived_vrrp[1108437]: INTERNAL_HA: sending gratuitous ARP for 11.9.7.119
Aug 09 15:15:53 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 11.9.7.119
Aug 09 15:15:53 node-12-240 Keepalived_vrrp[1108437]: (SLB_HA) Entering BACKUP STATE
Aug 09 15:15:53 node-12-240 Keepalived_vrrp[1108437]: SLB_HA: sending gratuitous ARP for 10.4.12.240
Aug 09 15:15:53 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 10.4.12.240
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: (INTERNAL_HA) Receive advertisement timeout
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: (INTERNAL_HA) Entering MASTER STATE
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: (INTERNAL_HA) setting VIPs.
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 11.9.7.8
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: (INTERNAL_HA) Sending/queueing gratuitous ARPs on bond0 for 11.9.7.8
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 11.9.7.8
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 11.9.7.8
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 11.9.7.8
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 11.9.7.8
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: (SLB_HA) Receive advertisement timeout
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: (SLB_HA) Entering MASTER STATE
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: (SLB_HA) setting VIPs.
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 10.4.12.243
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: (SLB_HA) Sending/queueing gratuitous ARPs on bond0 for 10.4.12.243
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 10.4.12.243
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 10.4.12.243
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 10.4.12.243
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 10.4.12.243
Aug 09 15:16:02 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 11.9.7.8
Aug 09 15:16:02 node-12-240 Keepalived_vrrp[1108437]: (INTERNAL_HA) Sending/queueing gratuitous ARPs on bond0 for 11.9.7.8
Aug 09 15:16:02 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 11.9.7.8
Aug 09 15:16:02 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 11.9.7.8
Aug 09 15:16:02 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 11.9.7.8
Aug 09 15:16:02 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 11.9.7.8
Aug 09 15:16:02 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 10.4.12.243
Aug 09 15:16:02 node-12-240 Keepalived_vrrp[1108437]: (SLB_HA) Sending/queueing gratuitous ARPs on bond0 for 10.4.12.243
Aug 09 15:16:02 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 10.4.12.243
Aug 09 15:16:02 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 10.4.12.243
Aug 09 15:16:02 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 10.4.12.243
Aug 09 15:16:02 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 10.4.12.243
Aug 09 15:16:24 node-12-240 Keepalived_vrrp[1108437]: (INTERNAL_HA) Received advert from 11.9.7.234 with lower priority 100, ours 200, forcing new elect
Aug 09 15:16:24 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 11.9.7.8
Aug 09 15:16:24 node-12-240 Keepalived_vrrp[1108437]: (INTERNAL_HA) Sending/queueing gratuitous ARPs on bond0 for 11.9.7.8
Aug 09 15:16:24 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 11.9.7.8
Aug 09 15:16:24 node-12-240 Keepalived_vrrp[1108437]: Sending gratuitous ARP on bond0 for 11.9.7.8

**Comment by pqarmitage** [comment]
The key messages here (for INTERNAL_HA) are:
```
Aug 09 15:15:53 node-12-240 Keepalived_vrrp[1108437]: (INTERNAL_HA) Entering BACKUP STATE
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: (INTERNAL_HA) Receive advertisement timeout
Aug 09 15:15:57 node-12-240 Keepalived_vrrp[1108437]: (INTERNAL_HA) Entering MASTER STATE
```
(there are similar messages for SLB_HA).

This is reporting that 4 seconds after INTERNAL_HA entered backup state it had received no adverts from any other instance, and so it (quite properly) becomes master - it isn't preempting because it has not seen any adverts from another master. Your point 5 above confirms this, saying that it took 30 seconds before the high priority node saw any adverts from the low priority node.

The problem would seem to be that it appears to take about 30 seconds between when the interface is being reported as up and network traffic being received on the interface. This could be a problem within the system or a problem in the switch that the bonded interfaces are connected to.

You have configured `preempt_delay` but that is not relevant here since no preemption is taking place; preemption is taking over from a lower priority master, and no such master has been seen.

I think what you need to do first is to investigate what is causing the 30 delay in traffic being passed over the interface after a cable is plugged in.

It might be that there is a solution to add a new keepalived keyword `interface_up_delay nn` which would make keepalived delay nn (seconds/milliseconds ?) after netlink reports an interface up before keepalived considers the interface to be working. I don't like the solution, because it is only working around another problem, i.e. why is it taking so long for the interface to start passing traffic after it is reported to be up.

**Comment by pqarmitage** [comment]
`systemctl restart network` could easily behave very differently from a network cable being plugged in; there is a difference between restarting the network configuration and an interface physically coming up.

Can you try running wireshark on the bond interface (on both the higher and lower priority instances) when you plug the cable in, and see when they start seeing VRRP adverts from the other instance.

A further thought - it is interesting that the lower priority instance is still sending adverts 27 seconds after the higher priority instance becomes master. As soon as the lower priority instance sees a higher priority advertisement it should revert to backup state, so this suggests that VRRP adverts are not passing between the higher and lower priority systems for 30 seconds after the interface is reported as being up.

This really does look like network traffic (or at least VRRP adverts) are not being received over the bond interfaces for 30 seconds after the network cable is plugged in.

**Comment by tangkelu** [comment]
The problem has been identified.The switch enable MST(Cisco) and the bond network interface from UP(blocking) to traffic(forwarding) need 30s. The bond network interface immediately traffic when I disable switch STP.

Thanks for you help!

**Comment by pqarmitage** [comment]
It's always fun diagnosing network issues when you have no idea of what the network is like!

My recollection is that the right way on Cisco to configure interfaces that are connected to hosts (or really to devices that are not switches) is to configure `spanning-tree portfast`. I can't remember how quickly rapid spanning tree allows a port to come up, but that may also be a solution.

I think based on what you have identified that it would probably be useful to add a keyword `interface_up_delay` as I suggested above, especially to cater for spanning tree and similar delays. Although normally an interface used by keepalived would not need to run spanning tree, we need to support such usage.
