### ISSUE TITLE
How to stop HA transition when NIC down for a few seconds

### ISSUE THREAD

**Issue by cnliuhb** [acassen/keepalived#2181]
### **1. Description:**
I have two hosts configured in nopreempt mode. 
When bringing down master NIC for a few seconds: ifconfig nic down && ifconfig nic up,  HA transition happened.
I want some configuration interval to set limit.
And if the down time is over this limit, HA transition should happen. Otherwise, transition should be avoided.

The old standby side has log:
> Aug 12 14:01:59 hb Keepalived_vrrp[2629]: (VI_1) Receive advertisement timeout
Aug 12 14:01:59 hb Keepalived_vrrp[2629]: (VI_1) Entering MASTER STATE
Aug 12 14:01:59 hb Keepalived_vrrp[2629]: (VI_1) setting VIPs.
Aug 12 14:01:59 hb Keepalived_vrrp[2629]: (VI_1) Sending/queueing gratuitous ARPs on enp0s8 for 192
.168.56.230
Aug 12 14:01:59 hb Keepalived_vrrp[2629]: Sending gratuitous ARP on enp0s8 for 192.168.56.230
Aug 12 14:01:59 hb Keepalived_vrrp[2629]: message repeated 4 times: [ Sending gratuitous ARP on enp
0s8 for 192.168.56.230]
Aug 12 14:01:59 hb Keepalived_vrrp[2629]: VRRP_Group(VG1) Syncing instances to MASTER state

And the old master side has log:
> Aug 12 14:01:49 ha Keepalived_vrrp[2822]: Netlink reports enp0s8 down
Aug 12 14:01:49 ha Keepalived_vrrp[2822]: (VI_1) Entering FAULT STATE
Aug 12 14:01:49 ha Keepalived_vrrp[2822]: (VI_1) sent 0 priority
Aug 12 14:01:49 ha Keepalived_vrrp[2822]: (VI_1) removing VIPs.
Aug 12 14:01:49 ha Keepalived_vrrp[2822]: VRRP_Group(VG1) Syncing instances to FAULT state
Aug 12 14:01:49 ha Keepalived_vrrp[2822]: Deassigned address fe80::a00:27ff:feb7:78bc from interface enp0s8
Aug 12 14:01:49 ha Keepalived_vrrp[2822]: Deassigned address 192.168.56.2 from interface enp0s8
Aug 12 14:01:53 ha Keepalived_vrrp[2822]: Netlink reports enp0s8 up
Aug 12 14:01:53 ha Keepalived_vrrp[2822]: (VI_1) Entering BACKUP STATE
Aug 12 14:01:53 ha Keepalived_vrrp[2822]: VI_1: sending gratuitous ARP for 192.168.56.2
Aug 12 14:01:53 ha Keepalived_vrrp[2822]: Sending gratuitous ARP on enp0s8 for 192.168.56.2
Aug 12 14:01:53 ha Keepalived_vrrp[2822]: VRRP_Group(VG1) Syncing instances to BACKUP state
Aug 12 14:01:53 ha Keepalived_vrrp[2822]: Assigned address 192.168.56.2 for interface enp0s8
Aug 12 14:01:55 ha Keepalived_vrrp[2822]: Assigned address fe80::a00:27ff:feb7:78bc for interface enp0s8

Which configuration  change can stop HA transition?
I have enlarged "advet_int" to 3, but it does not help?

### **2. Version:**
Keepalived v2.2.7 (08/12,2022) commit: e7c9e7f16535a31ccf61154011519ff9c97d52a3

### **3. Configuration:**

Host1 Configuration:

> vrrp_sync_group VG1 {
     group {
         VI_1
     }
}
vrrp_instance VI_1 {
     state BACKUP
     nopreempt
     version 3
     interface enp0s8
     virtual_router_id 51
     priority 150
     advert_int 3
     unicast_src_ip 192.168.56.2
     unicast_peer {
         192.168.56.3
     }
     authentication {
         auth_type PASS
         auth_pass pass
     }
     virtual_ipaddress {
         [192.168.56.230/24](http://192.168.56.230/24)
     }
}

Host2 configuration:

> vrrp_sync_group VG1 {
     group {
         VI_1
     }
}
vrrp_instance VI_1 {
     state BACKUP
     nopreempt
     version 3
     interface enp0s8
     virtual_router_id 51
     priority 149
     advert_int 3
     unicast_src_ip 192.168.56.3
     unicast_peer {
         192.168.56.2
     }
     authentication {
         auth_type PASS
         auth_pass pass
     }
     virtual_ipaddress {
         [192.168.56.230/24](http://192.168.56.230/24)
     }
}

**Comment by pqarmitage** [comment]
I think the simlpest thing to do, since this appears to be a manual process, would be to stop keepalived on the other system(s), then do you ifdown/ifup, and then restart keepalived on the other system(s).

**Comment by pqarmitage** [comment]
@cnliuhb I had completely forgotten that I had implemented interface up/down debounce timers, which I think are exactly what you want; specifically you want a down debounce timer.

You need to add a block as follows:
```
interface_up_down_delays {
   enp0s8 9 0
}
```
replacing 9 with however long you want to allow the interface to be down for before keepalived transitions it to fault state. The 0 means no delay in a transition to up state. The down and up timers are specified in seconds, with a resolution of 1 microsecond.

You will need to ensure that your advert interval is sufficiently long so that any backup instances do not transition to master.

**Comment by cnliuhb** [comment]
@pqarmitage 
Thanks a lot. The new configuration did solve my issue.
