### ISSUE TITLE
if script user not specified, the vrrp_script gets ignored by keepalived

### ISSUE THREAD

**Issue by petersutty** [acassen/keepalived#2184]
**Describe the bug**
if script user not specified, the vrrp_script gets ignored by keepalived

**To Reproduce**
remove any explicit users from keepalived.conf

**Expected behavior**
       By default the scripts will be executed by user keepalived_script if that user exists, or if not by root

**Keepalived version**
1:2.0.10-1
Output of `keepalived -v`
Keepalived v2.0.10 (11/12,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.20
Running on Linux 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30)

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --with-kernel-dir=debian/ --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus --enable-dbus-create-instance --enable-json --enable-bfd build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/build/keepalived-8agDac/keepalived-2.0.10=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS DBUS_CREATE_INSTANCE

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Distro (please complete the following information):**
 - Name: debian
 - Version: 10
 - Architecture: x86-64

**Details of any containerisation or hosted service (e.g. AWS)**
NA - keepalived running on virtual machine

**Configuration file:**
```
global_defs {
        notification_email {
                jan@aadsflkj.com
        }
        notification_email_from from@sgfgfsfdgdf.com
        smtp_server 10.33.3.100
        smtp_connect_timeout 30
        router_id 01
        enable_script_security
}

vrrp_script chk_haproxy {           # Requires keepalived
        script "/usr/bin/killall -0 haproxy"     # cheaper than pidof
        interval 2                      # check every 2 seconds
        weight 2                        # add 2 points of prio if OK
}

vrrp_instance instance_lan {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 101                    # 101 on master, 100 on backup
        virtual_ipaddress {
# there is a limit on the label 15 chars!!!
                10.99.3.10/32 dev eth0 label eth0:stats
                10.99.3.13/32 dev eth0 label eth0:morph
                10.99.3.14/32 dev eth0 label eth0:demoshop
                10.99.3.30/32 dev eth0 label eth0:cdn
        }
        track_script {
            chk_haproxy
        }
        nopreempt
        smtp_alert
}
```

**Notify and track scripts**
```
NA
```

**System Log entries**
```
Aug 18 06:49:16 01 systemd[1]: Starting Keepalive Daemon (LVS and VRRP)...
Aug 18 06:49:16 01 Keepalived[68329]: Starting Keepalived v2.0.10 (11/12,2018)
Aug 18 06:49:16 01 Keepalived[68329]: Running on Linux 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) (built for Linux 4.18.20)
Aug 18 06:49:16 01 Keepalived[68329]: Command line: '/usr/sbin/keepalived'
Aug 18 06:49:16 01 Keepalived[68329]: Opening file '/etc/keepalived/keepalived.conf'.
Aug 18 06:49:16 01 Keepalived[68330]: Starting VRRP child process, pid=68331
Aug 18 06:49:16 01 systemd[1]: Started Keepalive Daemon (LVS and VRRP).
Aug 18 06:49:16 01 Keepalived_vrrp[68331]: Registering Kernel netlink reflector
Aug 18 06:49:16 01 Keepalived_vrrp[68331]: Registering Kernel netlink command channel
Aug 18 06:49:16 01 Keepalived_vrrp[68331]: Opening file '/etc/keepalived/keepalived.conf'.
Aug 18 06:49:16 01 Keepalived_vrrp[68331]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Aug 18 06:49:16 01 Keepalived_vrrp[68331]: (Line 16) Unable to set default user for vrrp script chk_haproxy - removing
Aug 18 06:49:16 01 Keepalived_vrrp[68331]: (Line 31) (instance_lan) track script chk_haproxy not found, ignoring...
Aug 18 06:49:16 01 Keepalived_vrrp[68331]: Registering gratuitous ARP shared channel

```

**Did keepalived coredump?**
```
NA
```

**Additional context**
sudo ls -la /usr/bin/killall 
-rwxr-xr-x 1 root root 32480 Aug 16  2021 /usr/bin/killall

adding "user root" to the script (vrrp_script chk_haproxy) fixes the issue

**Comment by pqarmitage** [comment]
The behahiour is correct. You have specified `enable_script_security` part of which means that scripts are run by the user `keepalived_script` unless another user is specified. Since the user `keepalived_script` does not exist, keepalived cannot run the scripts, as the logs say.

**Comment by petersutty** [comment]
then the manual pages must be wrong ?
# Don't run scripts configured to be run as root if any part of the path
# is writable by a non-root user.
enable_script_security

/usr/bin/killall  - all the path is 755 root:root

The config without any explicit users worked just fine in debian
stretch Keepalived
v1.3.2 (12/03,2016)

**Comment by pqarmitage** [comment]
@petersutty Many thanks for pointing out the documentation deficiency. I will update the man page to read:
```
    # Don't run scripts configured to be run as root if any part of the path
    # is writable by a non-root user. Also, enforce the default script_user is
    # keepalived_script, and don't default to the user under which keepalived
    # is running (usually root).
    enable_script_security
```

By the way, using `vrrp_track_process` is much more efficient than using a script to check whether another process is running.

**Comment by petersutty** [comment]
Thanks for suggestion
All the best
