### ISSUE TITLE
Local, non-default OpenSSL install

### ISSUE THREAD

**Issue by dayjavid** [acassen/keepalived#219]
Is there a way to configure/make/install keepalived using a custom location for openssl?
Using keepalived-1.2.19, running on RedHat 6. 

I don't have the ability to use root or to install rpms with yum. I've compiled my own openssl to a custom prefix directory and would like keepalived to be able to recognize it.

Running ./configure displays:
```
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for strip... strip
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking openssl/ssl.h usability... no
checking openssl/ssl.h presence... no
checking for openssl/ssl.h... no
configure: error:
  !!! OpenSSL is not properly installed on your system. !!!
  !!! Can not include OpenSSL headers files.            !!!
```

So I tried editing configure to look in my own location for ssl stuff.
I changed line 3741 (ish) to look like this:
```
3740 LOCAL_SSL=/custom/local/include/openssl
3741 for ac_header in ${LOCAL_SSL}/ssl.h ${LOCAL_SSL}/md5.h ${LOCAL_SSL}/err.h
```

I got this output:
```
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for strip... strip
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking /custom/local/include/openssl/ssl.h usability... no
checking /custom/local/include/openssl/ssl.h presence... no
checking for /custom/local/include/openssl/ssl.h... no
configure: error:
  !!! OpenSSL is not properly installed on your system. !!!
  !!! Can not include OpenSSL headers files.            !!!
```

I would imagine at least the "Presence" check would pass as when I run:
```
(16:30:35)->ls -al /custom/local/include/openssl/ssl.h
-rw-r--r--. 1 ##### ##### 149176 Jan  8 16:14 /custom/local/include/openssl/ssl.h

```
It's obviously there.

Before I dug any further I figured I'd post here. Numerous google searches have turned up next to nothing so far.

**Comment by pqarmitage** [comment]
You really need to be editing configure.in or configure.ac (it has recently changed from the latter to the former), and then regenerating the configure file by running autoreconf.

Try adding in configure.in/configure.ac:
**LOCAL_SSL=/custom/local/include**
**CFLAGS="$CFLAGS -I $LOCAL_SSL"**
before the AC_CHECK_HEADERS(openssl,...) line

You will also probably need to add
**LDFLAGS="$LDFLAGS -L/custom/local/lib"**
or wherever the libraries are installed.

**Comment by neutrino1** [comment]
Hi,

FYI I faced the issue as @dayjavid on fedora 20 

> checking openssl/ssl.h usability... no
checking openssl/ssl.h presence... no
checking for openssl/ssl.h... no
configure: error: 
  !!! OpenSSL is not properly installed on your system. !!!
  !!! Can not include OpenSSL headers files.            !!!


and by installing the package openssl-devel it was resolved "yum install openssl-devel".

**Comment by pqarmitage** [comment]
You said in your original post that you don't have access to root. If that is the case then you won't be able to run keepalived since it absolutely needs root privileges to work.

**Comment by pqarmitage** [comment]
I updated the INSTALL file about three months ago so that it now indicates what packages need to be installed for various flavours of Linux in order to build keepalived.

**Comment by neutrino1** [comment]
> I updated the INSTALL file about three months ago so that it now indicates what packages need to be installed for various flavours of Linux in order to build keepalived.
great, but sorry I was not aware of it

> You said in your original post that you don't have access to root. If that is the case then you won't be able to run keepalived since it absolutely needs root privileges to work.
May be @dayjavid had root issue but I was having the problem even with root access, but now its solved as I told before

**Comment by 6ixni9e** [comment]
vi /data/keepalived-2.2.0/configure.ac
LOCAL_SSL = /usr/local/openssl/include/
CFLAGS = "$ CFLAGS -I $ LOCAL_SSL"

#before the AC_CHECK_HEADERS(openssl,...) line

./configure --prefix=/data/keepalived  CFLAGS="-I/usr/local/openssl/include" LDFLAGS="-L/usr/local/openssl/lib"

**Comment by coffeemug01** [comment]
Hi,
I am trying to build keepalived from GIT source.

#cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"

# openssl version
OpenSSL 1.1.1f  31 Mar 2020

Got the following error while running ./configure

checking openssl/ssl.h presence... no
checking for openssl/ssl.h... no
configure: error:
  !!! OpenSSL is not properly installed on your system. !!!
  !!! Can not include OpenSSL headers files.            !!!

Steps tried: 
Added
LOCAL_SSL = /usr/include/openssl/
CFLAGS = "$ CFLAGS -I $ LOCAL_SSL"

in configure.ac

Then run  
  ./configure --prefix=/data/keepalived CFLAGS="-I/usr/include/openssl/" LDFLAGS="-L/usr/include/openssl/"

Still same issue.

Kindly support

**Comment by nser77** [comment]
@coffeemug01 seems you are missing ssl.h header files.

Please review the INSTALL file in Keepalived project root directory and based on you flavor install the required packages; then re run 'configure' command.


Regards

**Comment by coffeemug01** [comment]
thank you for the input.
but ssl.h is available.

# ll /usr/include/openssl/ssl.h
-rw-r--r-- 1 root root 111253 Jul  4  2022 /usr/include/openssl/ssl.h

**Comment by nser77** [comment]
@coffeemug01 there is maybe more things that we can try to check.

# 1
> You really need to be editing configure.in or configure.ac (it has recently changed from the latter to the former), and then regenerating the configure file by running autoreconf.
> 
> Try adding in configure.in/configure.ac: **LOCAL_SSL=/custom/local/include** **CFLAGS="$CFLAGS -I $LOCAL_SSL"** before the AC_CHECK_HEADERS(openssl,...) line
> 
> You will also probably need to add **LDFLAGS="$LDFLAGS -L/custom/local/lib"** or wherever the libraries are installed.


First off all, I seed that you may missed this part of an old comment:

```
You will also probably need to add LDFLAGS="$LDFLAGS -L/custom/local/lib" or wherever the libraries are installed.
```

# 2

What version of keepalived are you trying to install?

You are using a very old version of openssl (1.1.1f): have you tryied to upgrade it?

# 3
Finally, from source code I see the following section in ```configure.ac```:

```
dnl ----[ Checks for openssl ]----
# check for openssl headers
NEED_EVP=no
NEED_SSL=no
if test "$enable_vrrp" != no -a \
	"$enable_vrrp_auth" != no; then
  NEED_EVP=yes
fi
if test "$enable_lvs" != no; then
  NEED_EVP=yes
  NEED_SSL=yes
fi
AC_CHECK_HEADERS([openssl/ssl.h openssl/err.h], [],
  [
    if test $NEED_SSL = yes; then
      AC_MSG_ERROR([
  !!! OpenSSL is not properly installed on your system. !!!
  !!! Can not include OpenSSL headers files.            !!!])
    fi
  ])
AC_CHECK_HEADERS([openssl/md5.h openssl/evp.h], [],
  [
    if test $NEED_EVP = yes; then
      AC_MSG_ERROR([
  !!! OpenSSL is not properly installed on your system. !!!
  !!! Can not include OpenSSL EVP headers files.        !!!])
    fi
  ])
``` 

In Keepalived 2.2.7, Seems there is a flag to manage openssl at configuration time.

If you don't need LVS module, try to configure keepalived as following:

```
./configure --disable-lvs
```

## 3.1
```openssl/err.h``` must also exist (in my case ```/usr/include/openssl/err.h```)

**Comment by pqarmitage** [comment]
@coffeemug01 
```
Then run
./configure --prefix=/data/keepalived CFLAGS="-I/usr/include/openssl/" LDFLAGS="-L/usr/include/openssl/"
```
`--prefix` is for specifying where files are installed after they have been built, and does not affect what configure does.
LDFLAGS specifies where the library files used by the liker are, in the case of openssl libssl.so, and the default location will be /usr/lib64/libssl.so or /usr/lib/libssl.so. This shouldn't affect configure.
CFLAGS should really be CPPFLAGS, since CPPFLAGS is passed to the preprocessor, which is what handles include statements. Since the include statements in keepalived source files are:
`#include <openssl/ssl.h>"`
etc., then if the file to be included is /usr/include/openssl/ssl.h the include path needs to be /usr/include, which is almost certainly in your default include path, so you shouldn't need to specify `CPPFLAGS="-I /usr/include"`.

The tests that configure does not only includes checking for the existence of the file, but also that it can compile conftest.c which includes the header file. It could be that the compilation part of the test is failing (I seem to remember that there have been some issues with some versions of openssl in the past).

What I do when I have problems with working out why configure is failing is I run
`bash -x ./configure >/tmp/configure.log 2>1`
and then look at /tmp/configure.log to see exactly what is failing (it will be towards the end).

If you cannot see what is wrong and configure is still failing, then you could post the relevant part of configure.log here and we can have a look at it.

**Comment by coffeemug01** [comment]
Thank you for the inputs.
I am trying to build the following version
Keepalived v2.2.7 (03/06,2023)

I downloaded the latest code from GIT https://github.com/acassen/keepalived

I am using a custom linux Docker container to build keepalived as per the project requirement. The issue happens in that.

The same source code, i tried building in a Ubuntu machine and it built the keeapalived executable after the following steps.
1052  unzip keepalived-master.zip
 1053  ls
 1054  cd keepalived-master/
 1055  ./autogen.sh
 1056  sudo ./autogen.sh
 1057  apt-get install autotools-dev
 1058  sudo apt-get install autotools-dev
 1059  sudo ./autogen.sh
 1060  apt-get install automake
 1061  sudo apt-get install automake
 1062  sudo ./autogen.sh
 1063  ./configure
 1064  sudo apt-get install build-essential
 1065  ./configure
 1066  apt-get install openssl libssl-dev
 1067  sudo apt-get install openssl libssl-dev
 1068  ./configure
 1069  make install
 1070  make
 1071  sudo make install
 1072  openssl version

Openssl version remain the same in both the Container and Ubuntu machine. 
I understand there is some env issue in my container blocking the build. I will debug as per the suggestions and come back on this. thank you.

**Comment by coffeemug01** [comment]
Hi,
I upgraded openssl version in the container.
Code/keepalived-master# openssl version
OpenSSL 3.1.0 14 Mar 2023 (Library: OpenSSL 3.1.0 14 Mar 2023)

Keepalived source version v2.2.7
**Still the same issue with openssl while running ./configure.**

Code/keepalived-master# bash -x ./configure --disable-lvs --prefix=/data/keepalived CPPFLAGS="-I/usr/include/openssl/" LDFLAGS="-L/usr/lib/x86_64-linux-gnu/"  >/tmp/configure.log 2>1

**Following is the log**

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /opt/toolchain/bin/x86_64-next-linux-gnu-gcc accepts -g... yes
checking for /opt/toolchain/bin/x86_64-next-linux-gnu-gcc option to accept ISO C89... none needed
checking whether /opt/toolchain/bin/x86_64-next-linux-gnu-gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of /opt/toolchain/bin/x86_64-next-linux-gnu-gcc... gcc3
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... /opt/toolchain/bin/x86_64-next-linux-gnu-ranlib
checking for grep that handles long lines and -e... /usr/bin/grep
checking whether ln -s works... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for strip... /opt/toolchain/bin/x86_64-next-linux-gnu-strip
checking for ldd... ldd
checking the archiver (/opt/toolchain/bin/x86_64-next-linux-gnu-ar) interface... ar
checking msghdr.msg_controllen is size_t... yes
checking diagnostic pragmas in functions... yes
checking diagnostic push/pop pragmas... yes
checking for -Wall... yes
checking for -Wextra... yes
checking for -Wunused... yes
checking for -Wstrict-prototypes... yes
checking for -Wabi... no
checking for -Wabsolute-value... no
checking for -Waddress-of-packed-member... no
checking for -Walloca... yes
checking for -Walloc-larger-than=4096... no
checking for -Walloc-zero... yes
checking for -Warith-conversion... no
checking for -Warray-bounds=2... yes
checking for -Wattribute-alias=2... no
checking for -Wbad-function-cast... yes
checking for -Wc11-c2x-compat... no
checking for -Wcast-align... yes
checking for -Wcast-qual... yes
checking for -Wchkp... yes
checking for -Wdate-time... yes
checking for -Wdisabled-optimization... yes
checking for -Wdouble-promotion... yes
checking for -Wduplicated-branches... yes
checking for -Wduplicated-cond... yes
checking for -Wfloat-conversion... yes
checking for -Wfloat-equal... yes
checking for -Wformat-overflow... yes
checking for -Wformat-security... no
checking for -Wformat-signedness... yes
checking for -Wformat-truncation... yes
checking for -Wframe-larger-than=5120... yes
checking for -Wimplicit-fallthrough=3... yes
checking for -Winit-self... yes
checking for -Winline... yes
checking for -Winvalid-pch... yes
checking for -Wjump-misses-init... yes
checking for -Wlogical-op... yes
checking for -Wmissing-declarations... yes
checking for -Wmissing-field-initializers... yes
checking for -Wmissing-include-dirs... yes
checking for -Wmissing-prototypes... yes
checking for -Wnested-externs... yes
checking for -Wnormalized... yes
checking for -Wnull-dereference... yes
checking for -Wold-style-definition... yes
checking for -Woverlength-strings... yes
checking for -Wpointer-arith... yes
checking for -Wredundant-decls... yes
checking for -Wshadow... yes
checking for -Wshift-overflow=2... yes
checking for -Wstack-protector... yes
checking for -Wstrict-overflow=4... yes
checking for -Wstringop-overflow=2... yes
checking for -Wstringop-truncation... yes
checking for -Wsuggest-attribute=cold... yes
checking for -Wsuggest-attribute=const... no
checking for -Wsuggest-attribute=format... yes
checking for -Wsuggest-attribute=malloc... yes
checking for -Wsuggest-attribute=noreturn... yes
checking for -Wsuggest-attribute=pure... yes
checking for -Wsync-nand... yes
checking for -Wtrampolines... yes
checking for -Wundef... yes
checking for -Wuninitialized... yes
checking for -Wunknown-pragmas... yes
checking for -Wunsafe-loop-optimizations... yes
checking for -Wunsuffixed-float-constants... yes
checking for -Wunused-const-variable=2... yes
checking for -Wunused-macros... no
checking for -Wvariadic-macros... yes
checking for -Wwrite-strings... yes
checking for function __attribute__((error(msg))) support... no
checking for function __attribute__((warn_unused_result)) support... yes
checking for PIE support... yes
checking for -Wformat -Werror=format-security support... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 support... yes
checking for -fexceptions support... yes
checking for -fstack-protector-strong support... yes
checking for --param=ssp-buffer-size=4 support... yes
checking for -grecord-gcc-switches support... yes
checking for -Wl,-z,relro support... yes
checking for -Wl,-z,now support... yes
checking for -O2 support... yes
CFLAGS=-g -g -O2 -Wall -Wextra -Wunused -Wstrict-prototypes -Walloca -Walloc-zero -Warray-bounds=2 -Wbad-function-cast -Wcast-align -Wcast-qual -Wchkp -Wdate-time -Wdisabled-optimization -Wdouble-promotion -Wduplicated-branches -Wduplicated-cond -Wfloat-conversion -Wfloat-equal -Wformat-overflow -Wformat-signedness -Wformat-truncation -Wframe-larger-than=5120 -Wimplicit-fallthrough=3 -Winit-self -Winline -Winvalid-pch -Wjump-misses-init -Wlogical-op -Wmissing-declarations -Wmissing-field-initializers -Wmissing-include-dirs -Wmissing-prototypes -Wnested-externs -Wnormalized -Wnull-dereference -Wold-style-definition -Woverlength-strings -Wpointer-arith -Wredundant-decls -Wshadow -Wshift-overflow=2 -Wstack-protector -Wstrict-overflow=4 -Wstringop-overflow=2 -Wstringop-truncation -Wsuggest-attribute=cold -Wsuggest-attribute=format -Wsuggest-attribute=malloc -Wsuggest-attribute=noreturn -Wsuggest-attribute=pure -Wsync-nand -Wtrampolines -Wundef -Wuninitialized -Wunknown-pragmas -Wunsafe-loop-optimizations -Wunsuffixed-float-constants -Wunused-const-variable=2 -Wvariadic-macros -Wwrite-strings -fno-strict-aliasing -fPIE -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -O2
checking for unaligned memory access... yes
checking for unaligned memory access causes warnings... no
checking for clock_gettime() requires -lrt... no
checking how to run the C preprocessor... /opt/toolchain/bin/x86_64-next-linux-gnu-gcc -E
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/prctl.h usability... yes
checking sys/prctl.h presence... yes
checking for sys/prctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking linux/errqueue.h needs sys/time.h... no
checking asm/types.h usability... yes
checking asm/types.h presence... yes
checking for asm/types.h... yes
checking linux/ethtool.h usability... yes
checking linux/ethtool.h presence... yes
checking for linux/ethtool.h... yes
checking linux/icmpv6.h usability... yes
checking linux/icmpv6.h presence... yes
checking for linux/icmpv6.h... yes
checking linux/if_ether.h usability... yes
checking linux/if_ether.h presence... yes
checking for linux/if_ether.h... yes
checking linux/if_packet.h usability... yes
checking linux/if_packet.h presence... yes
checking for linux/if_packet.h... yes
checking linux/ip.h usability... yes
checking linux/ip.h presence... yes
checking for linux/ip.h... yes
checking linux/sockios.h usability... yes
checking linux/sockios.h presence... yes
checking for linux/sockios.h... yes
checking linux/types.h usability... yes
checking linux/types.h presence... yes
checking for linux/types.h... yes
checking for linux/fib_rules.h... yes
checking for linux/if_addr.h... yes
checking for linux/if_link.h... yes
checking for linux/if_arp.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for int64_t... yes
checking for pid_t... yes
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for an ANSI C-conforming const... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for dup2... yes
checking for dup3... yes
checking for getcwd... yes
checking for gettimeofday... yes
checking for malloc... yes
checking for memmove... yes
checking for memset... yes
checking for realloc... yes
checking for select... yes
checking for setenv... yes
checking for socket... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strpbrk... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
checking for uname... yes
checking for vsyslog... yes
checking for memfd_create... yes
checking whether O_TMPFILE is declared... yes
checking whether ETHERTYPE_IPV6 is declared... yes
checking whether IPV6_MULTICAST_ALL is declared... no
checking openssl/ssl.h usability... no
checking openssl/ssl.h presence... no
checking for openssl/ssl.h... no
checking openssl/err.h usability... no
checking openssl/err.h presence... no
checking for openssl/err.h... no
checking openssl/md5.h usability... no
checking openssl/md5.h presence... no
checking for openssl/md5.h... no
root@9c524442e1d9:

Kindly provide your inputs. thanks.

**Comment by pqarmitage** [comment]
Apologies, there was an error in the command I asked you to execute. It should be:
`bash -x ./configure >/tmp/configure.log 2>&1`

Please can you run the above and either diagnose the problem from the output or post the relevant output here.

**Comment by coffeemug01** [comment]
Thank you. Please find the relevant log here.

+ as_lineno=8118
+ as_lineno_stack=as_lineno_stack=
+ eval '${ac_cv_header_openssl_ssl_h+:}' false
++ false
+ printf '%s\n' 'configure:8118: checking openssl/ssl.h usability'
+ printf %s 'checking openssl/ssl.h usability... '
checking openssl/ssl.h usability... + cat confdefs.h -
+ ac_fn_c_try_compile 2005
+ as_lineno=8118
+ as_lineno_stack=as_lineno_stack=as_lineno_stack=
+ rm -f conftest.o
+ ac_try='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ case "(($ac_try" in
+ ac_try_echo='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ eval 'ac_try_echo="$as_me:8118: $CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5"'
++ ac_try_echo='configure:8118: /opt/toolchain/bin/x86_64-next-linux-gnu-gcc -c -g -O2   -D_GNU_SOURCE conftest.c >&5'
+ printf '%s\n' 'configure:8118: /opt/toolchain/bin/x86_64-next-linux-gnu-gcc -c -g -O2   -D_GNU_SOURCE conftest.c >&5'
+ ac_status=1
+ test -s conftest.err
+ grep -v '^ *+' conftest.err
+ cat conftest.er1
+ mv -f conftest.er1 conftest.err
+ printf '%s\n' 'configure:8118: $? = 1'
+ test 1 = 0
+ printf '%s\n' 'configure: failed program was:'
+ sed 's/^/| /' conftest.c
+ ac_retval=1
+ eval as_lineno_stack=as_lineno_stack=
++ as_lineno_stack=as_lineno_stack=
+ : unset as_lineno
+ as_fn_set_status 1
+ return 1
+ ac_header_compiler=no
+ rm -f core conftest.err conftest.o conftest.c
+ printf '%s\n' 'configure:8118: result: no'
+ printf '%s\n' no
no
+ printf '%s\n' 'configure:8118: checking openssl/ssl.h presence'
+ printf %s 'checking openssl/ssl.h presence... '
checking openssl/ssl.h presence... + cat confdefs.h -
+ ac_fn_c_try_cpp 2021
+ as_lineno=8118
+ as_lineno_stack=as_lineno_stack=as_lineno_stack=
+ ac_try='$CPP $CPPFLAGS conftest.c'
+ case "(($ac_try" in
+ ac_try_echo='$CPP $CPPFLAGS conftest.c'
+ eval 'ac_try_echo="$as_me:8118: $CPP $CPPFLAGS conftest.c"'
++ ac_try_echo='configure:8118: /opt/toolchain/bin/x86_64-next-linux-gnu-gcc -E   -D_GNU_SOURCE conftest.c'
+ printf '%s\n' 'configure:8118: /opt/toolchain/bin/x86_64-next-linux-gnu-gcc -E   -D_GNU_SOURCE conftest.c'
+ ac_status=1
+ test -s conftest.err
+ grep -v '^ *+' conftest.err
+ cat conftest.er1
+ mv -f conftest.er1 conftest.err
+ printf '%s\n' 'configure:8118: $? = 1'
+ test 1 = 0
+ printf '%s\n' 'configure: failed program was:'
+ sed 's/^/| /' conftest.c
+ ac_retval=1
+ eval as_lineno_stack=as_lineno_stack=
++ as_lineno_stack=as_lineno_stack=
+ : unset as_lineno
+ as_fn_set_status 1
+ return 1
+ ac_header_preproc=no
+ rm -f conftest.err conftest.i conftest.c
+ printf '%s\n' 'configure:8118: result: no'
+ printf '%s\n' no
no
+ case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+ printf '%s\n' 'configure:8118: checking for openssl/ssl.h'
+ printf %s 'checking for openssl/ssl.h... '
checking for openssl/ssl.h... + eval '${ac_cv_header_openssl_ssl_h+:}' false
++ false
+ eval 'ac_cv_header_openssl_ssl_h=$ac_header_compiler'
++ ac_cv_header_openssl_ssl_h=no
+ eval 'ac_res=$ac_cv_header_openssl_ssl_h'
++ ac_res=no
+ printf '%s\n' 'configure:8118: result: no'
+ printf '%s\n' no
no
+ eval as_lineno_stack=
++ as_lineno_stack=
+ unset as_lineno
+ eval test '"x$ac_cv_header_openssl_ssl_h"' = xyes
++ test xno = xyes
+ test yes = yes
+ as_fn_error 0 '
  !!! OpenSSL is not properly installed on your system. !!!
  !!! Can not include OpenSSL headers files.            !!!' 8127 5
+ as_status=0
+ test 0 -eq 0
+ as_status=1
+ test 5
+ as_lineno=8127
+ as_lineno_stack=as_lineno_stack=
+ printf '%s\n' 'configure:8127: error:
  !!! OpenSSL is not properly installed on your system. !!!
  !!! Can not include OpenSSL headers files.            !!!'
+ printf '%s\n' 'configure: error:
  !!! OpenSSL is not properly installed on your system. !!!
  !!! Can not include OpenSSL headers files.            !!!'
configure: error:
  !!! OpenSSL is not properly installed on your system. !!!
  !!! Can not include OpenSSL headers files.            !!!
+ as_fn_exit 1
+ set +e
+ as_fn_set_status 1
+ return 1
+ exit 1
+ exit_status=1
+ echo
+ printf '%s\n' '## ---------------- ##

**Comment by coffeemug01** [comment]
Following are the last lines from the log

+ test -s confdefs.h
+ printf '%s\n' '## ----------- ##
## confdefs.h. ##
## ----------- ##'
+ echo
+ cat confdefs.h
+ echo
+ test 0 '!=' 0
+ printf '%s\n' 'configure: exit 1'
+ rm -f core '*.core' 'core.conftest.*'
+ rm -f -r 'conftest*' confdefs.h 'conf18719*'
+ exit 1

**Comment by nser77** [comment]
@coffeemug01 

Based on this input:

> Hi, I upgraded openssl version in the container.

and on this previous comment:

> #cat /etc/os-release
> NAME="Ubuntu"
> VERSION="20.04.5 LTS (Focal Fossa)"

Have you tryed to use the official Keepalived Docker Image? 
Please, take a look to #665.

Anyway, seems you should run:

```
./configure --disable-dynamic-linking
```

PD: I don't know if #2052 update #665.

**Comment by coffeemug01** [comment]
Thank you for the information.

I downloaded container 
         docker pull osixia/keepalived

Able to build keeoalived after installing necessary packages.
Following is the docker container information
bash-5.0# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.10.3
PRETTY_NAME="Alpine Linux v3.10"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
bash-5.0# openssl version
OpenSSL 1.1.1k  25 Mar 2021
bash-5.0# 

I tried ./configure --disable-dynamic-linking in my project container, but gave openssl error again.
thank you

**Comment by coffeemug01** [comment]
ok. thank you. let me analyse my container environment and come back.

**Comment by coffeemug01** [comment]
> Thank you for your information. I am working on a conan project to build keepalived which uses the project docker container to build the executable. I understand this is an environment issue. I downloaded 3.0.4-1 openssl version and run the following command in my conan project. self.run("./configure CPPFLAGS=-I{ssl_dir}/include/ LDFLAGS=-L{ssl_dir}/lib/".format(ssl_dir=openssl_strbuf.getvalue().rstrip("\n")))
> 
> setting latest openssl paths explicitly. Then the error was different.
> 
> checking openssl/ssl.h presence... yes checking for openssl/ssl.h... yes checking openssl/err.h usability... yes checking openssl/err.h presence... yes checking for openssl/err.h... yes checking openssl/md5.h usability... yes checking openssl/md5.h presence... yes checking for openssl/md5.h... yes checking openssl/evp.h usability... yes checking openssl/evp.h presence... yes checking for openssl/evp.h... yes checking for EVP_DigestInit_ex in -lcrypto... no configure: error: OpenSSL EVP libraries are required
> 
> Can you please suggest what may be the reason for this error? thanks


This issue is solved by using AutoToolsBuildEnvironment() in conan project file.
            autotools = AutoToolsBuildEnvironment(self)
            autotools.configure()
Also
    default_options = {"openssl:shared":True}
           
thank you.
