### ISSUE TITLE
keepalived -> configuration file doesnt exist

### ISSUE THREAD

**Issue by imrahuldevopser** [acassen/keepalived#2196]
vim /etc/keepalived/
 keepalived.conf file does not exist in my scenerio. so please tell me whats th .conf file here ant the correct location.

**Comment by pqarmitage** [comment]
In the past, keepalived used to install with a configuration file `/etc/keepalived/keepalived.conf` which is the default configuration file name (it can be changed at configure time). The configuration file that keepalived uses can be specified with the `-f` option, but if there is no `-f` option the default is used. `keepalived -h` shows in the first few lines the default config file.

The problem with this was that if keepalived were started after installation without modifying the installed default file, it certainly would not work, for example there is no FQDN firewall.loc (and the smtp_server is very unlikely to be correct), so all email addresses would fail. More concerning would be if VRID 51 were already in use on eth0 of the system where keepalived were installed, then it could interfere with the operation of a live VRRP virtual router. It simply is not possible to installed a default configuration file that could be either useful or safe.

I therefore took the decision some time ago that it wasn't safe to install a default configuration file, which would then be used by keepalived if it were started without modifying the configuration file. Accordingly, a sample configuration file is now installed as `/etc/keepalived/keepalived.conf.sample` (or whatever the default configuration file is with `.sample` appended). The sample file can be modified and copied to `/etc/keepalived/keepalived/conf`, thereby ensuring that keepalived only starts with a configuration file that is intended to be used on the specific system in question.

**Comment by imrahuldevopser** [comment]
but not file exist

**Comment by pqarmitage** [comment]
This case was updated at Mon, 12 Sep 2022 06:42:53 -0700 (12/09/22 13:42:53 UTC) to state:
```
but not file exist
```

That update and the original comment:
```
vim /etc/keepalived/
keepalived.conf file does not exist in my scenerio. so please tell me whats th .conf file here ant the correct location.
```
appear to have been deleted, so I am assuming that there is no longer an issue.

**Comment by imrahuldevopser** [comment]
> In the past, keepalived used to install with a configuration file `/etc/keepalived/keepalived.conf` which is the default configuration file name (it can be changed at configure time). The configuration file that keepalived uses can be specified with the `-f` option, but if there is no `-f` option the default is used. `keepalived -h` shows in the first few lines the default config file.
> 
> The problem with this was that if keepalived were started after installation without modifying the installed default file, it certainly would not work, for example there is no FQDN firewall.loc (and the smtp_server is very unlikely to be correct), so all email addresses would fail. More concerning would be if VRID 51 were already in use on eth0 of the system where keepalived were installed, then it could interfere with the operation of a live VRRP virtual router. It simply is not possible to installed a default configuration file that could be either useful or safe.
> 
> I therefore took the decision some time ago that it wasn't safe to install a default configuration file, which would then be used by keepalived if it were started without modifying the configuration file. Accordingly, a sample configuration file is now installed as `/etc/keepalived/keepalived.conf.sample` (or whatever the default configuration file is with `.sample` appended). The sample file can be modified and copied to `/etc/keepalived/keepalived/conf`, thereby ensuring that keepalived only starts with a configuration file that is intended to be used on the specific system in question.

Thankyou for this information. Thanks a lot.
