### ISSUE TITLE
problem on vmware virtual environment

### ISSUE THREAD

**Issue by ManuelRighi** [acassen/keepalived#220]
Hello,
I have keepalived version 1.2.19 on vmware virtual infrastructure.
When vmware take a snapshot of one of two virtual machine thath use keepalived, randomly, the virtual ip does not work, but I see virtual ip “attached” on primary load balancer if I write on console “ip address list”.
I think virtual ip go to secondary load balancer / VM when vmware take snapshot, return to primary VM after 1-2 seconds, but after this virtual ip not work …
I need to restart keepalived on both VM and virtual IP return to work.

When problem occours, I see this on syslog on the secondary VM

Jan 24 16:03:13 cls-mysql-lb2 Keepalived_vrrp[13777]: VRRP_Instance(FloatIPClusterMysql1) Transition to MASTER STATE
Jan 24 16:03:13 cls-mysql-lb2 Keepalived_vrrp[13777]: VRRP_Group(SyncGroupCluster3) Syncing instances to MASTER state
Jan 24 16:03:13 cls-mysql-lb2 snmpd[1405]: Connection from UDP: [10.10.20.70]:52842->[10.10.20.84]:161
Jan 24 16:03:13 cls-mysql-lb2 snmpd[1405]: Connection from UDP: [10.10.20.70]:52846->[10.10.20.84]:161
Jan 24 16:03:14 cls-mysql-lb2 Keepalived_vrrp[13777]: VRRP_Instance(FloatIPClusterMysql1) Entering MASTER STATE
Jan 24 16:03:14 cls-mysql-lb2 Keepalived_vrrp[13777]: Remote SMTP server [10.10.20.55]:25 connected.
Jan 24 16:03:14 cls-mysql-lb2 Keepalived_vrrp[13777]: SMTP alert successfully sent.
Jan 24 16:03:15 cls-mysql-lb2 Keepalived_vrrp[13777]: VRRP_Instance(FloatIPClusterMysql1) Received higher prio advert
Jan 24 16:03:15 cls-mysql-lb2 Keepalived_vrrp[13777]: VRRP_Instance(FloatIPClusterMysql1) Entering BACKUP STATE
Jan 24 16:03:15 cls-mysql-lb2 Keepalived_vrrp[13777]: VRRP_Group(SyncGroupCluster3) Syncing instances to BACKUP state
Jan 24 16:03:15 cls-mysql-lb2 Keepalived_vrrp[13777]: Remote SMTP server [10.10.20.55]:25 connected.
Jan 24 16:03:15 cls-mysql-lb2 Keepalived_vrrp[13777]: SMTP alert successfully sent.

On primary VM I not find anithing.

Can you help me ?
Tnx
Manuel

**Comment by ManuelRighi** [comment]
Both VM are Ubuntu 14.04.3 LTS

**Comment by acassen** [comment]
would you give a try with current keepalived version in github tree ? bunch of fixes have been merged.
