### ISSUE TITLE
Add configure options for all paths

### ISSUE THREAD

**Issue by levin1** [acassen/keepalived#2210]
Hi, I want to be able to control path for data files that are hard coded to /tmp and maybe others if there are any. Thanks.

**Comment by pqarmitage** [comment]
The only files that are written by default to /tmp are files intended for debugging purposes. While there is no configuration file or command line options to specify the location of those files, there is a configure option, `--with-tmp-dir=DIR`, that allows the directory to be specified where all the files that would be written to /tmp are written.

If this is not sufficient for you, can you please specify for which files you want to be able to specify the location.

**Comment by levin1** [comment]
> there is a configure option, --with-tmp-dir=DIR

Oh, I see, I use old version, without support of these, it was added in 59f7b7dc550
