### ISSUE TITLE
Keepalived LB nodes unable to access the RealServer's ports

### ISSUE THREAD

**Issue by lukedevon** [acassen/keepalived#2213]
Hi , 

I have configured Keepalived DR mode LB,  based on following:

1. LB-Master
1.1 VIP - 10.11.12.100
2. LB-Backup
3. RealServer-1, http-port 80
4. RealServer-2, http-port 80
5. Client

Client able to access RealServer-1 and 2 via the VIP. 
But when I curl the VIP from LB-Master, I am getting connection time out.

**From LB-Master:**
curl 10.11.12.100 80

curl: (7) Failed to connect to 10.11.12.100 port 80: Connection timed out
curl: (7) Couldn't connect to server

what could be the mistake that I have done? is there a way to fix issue?

Thanks
Luke.

**Comment by pqarmitage** [comment]
So far as I remember, IPVS doesn't work for connections initiated from the system on which IPVS is configured. In other words it only works for packets forwarded by the IPVS system.

The simplest way to test IPVS configuration is to configure it with the `ipvsadm` command, and once it works, convert that configuration into the keepalived configuration.

**Comment by seaurching** [comment]
@pqarmitage I have same issus with configured the real server
![image](https://user-images.githubusercontent.com/7349963/226818542-c17cbd0a-9384-46ac-a2e9-e43592662d02.png)
When use `curl` to realserver 192.168.180.135, get response; while connect to 192.168.180.136, will timeout. For kernel ip_forward have been enabled with equal 1
![image](https://user-images.githubusercontent.com/7349963/226818849-659dcce3-a53e-4ab4-bbcb-b840c138850c.png)
