### ISSUE TITLE
keepalived 2.2.7 permission problem

### ISSUE THREAD

**Issue by snzhaoyua** [acassen/keepalived#2214]
**Describe the bug**

1. We ran keepalived with user usera.

2. User usera could access directory /opt/directory1
```bash
whoami
usera
ls /opt/directory1
file1 file2
```

3. directory1 was owned by User userb, usera and userb belongs to same group, userb       
```bash
ls /opt
drwxr-x---  10 userb       userb       4096 Oct 18 04:50 directory1
```

4. keepalived check script as below:
```
vrrp_script chk_gaussdb {
    script "/opt/check.sh"
}
```

```
cat /opt/check.sh
ls /opt/directory1
```

<font color='red'>check.sh could not access /opt/directory1</font>

Problem does not exist on keepalived 2.2.4

**Keepalived version**
```
Keepalived v2.2.7 (09/13,2022)

Copyright(C) 2001-2022 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
```

**Comment by pqarmitage** [comment]
keepalived does not use supplemental groups; in fact it explicitly clears them. If you want to run the script with usera user permissions and userb group permissions, then you will need to add a line `user usera userb` in the vrrp_script block.

**Comment by snzhaoyua** [comment]
> From the output you have provided above, it _might_ be that usera does not have execute permission of /opt/check.sh (if it exists, since the output you show for `ls /opt` appears to show that it does not exist), but I cannot tell from the information you have provided.
> 
> Could you please provide:
> 
> 1. Your full keepalived configuration
> 2. The output of `keepalived -v`
> 3. The output of grep "user[ab]" /etc/group /etc/passwd
> 4. The full output of `ls -l /opt` - the output you have provided does not include /opt/check.sh which I presume exists
> 5. The full keepalived logs from when keepalived starts.
> 
> Once we have the above information we can investigate this issue.

hi, i updated the issue, sensitive data was removed, i did my best...

**Comment by snzhaoyua** [comment]
after add code below, works fine.
```
vrrp_script my_script {
  user usera userb
}
```
but problem still exists when using notify_master, notify_backup or notify_fault

**Comment by pqarmitage** [comment]
The configuration file you posted does not have any notify scripts, so no comment was made about them.

As the keepalived.conf(5) man page states:
`notify_master /path/to_master.sh [username [groupname]]`

Have you added the username and groupname?
