### ISSUE TITLE
vrrp_script fails if it runs "docker ps"

### ISSUE THREAD

**Issue by fansari** [acassen/keepalived#2215]
**Describe the bug**
When I write a vrrp_script which tries to run "docker ps" the script always fails.
I would like to check whether a docker container is up.
For this I added the keepalived_script user into the docker group but even then the script fails.

I would like to do something like "docker ps | grep nginx | grep Up" in a script.

The strange thing is: all the script works when I run it as user keepalived_script from the shell.

I have set SELinux to "permissive" for this test.

**To Reproduce**
Write a vrrp_script where you access a file or grep for some "docker ps" output.
In this example there is a container called "nginx".

```
#!/bin/bash

output=$(docker ps | grep nginx | grep Up)

if [[ -z "$output" ]];
then
  exit 1
fi
```

**Expected behavior**
The script should not fail.

**Keepalived version**
```
Keepalived v2.2.4 (08/21,2021)

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.14.0
Running on Linux 5.14.0-171.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Oct 1 12:56:27 UTC 2022
Distro: CentOS Stream 9

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/sha
re --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --enable-snmp-rfc --enable-nftables --disable-iptab
les --enable-sha1 --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CC=gcc CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -greco
rd-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-6
4-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1

Config options:  NFTABLES LVS VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 INIT=systemd SYSTEMD_NOTIFY

System options:  VSYSLOG MEMFD_CREATE IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_F
ASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_AT
TR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK
```

**Distro (please complete the following information):**
 - Name: CentOS
 - Version: Stream release 9
 - Architecture:  x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
```
global_defs {
    dynamic_interfaces
    enable_script_security
}

vrrp_script keepalived_check {
      script "/usr/local/bin/keepalived/keepalived_check.sh"
      interval 1
      timeout 5
      rise 3
      fall 3
}


vrrp_instance VRRP1 {
    state BACKUP
    nopreempt

#   Specify the network interface to which the virtual address is assigned
    interface ens18

#   The virtual router ID must be unique to each VRRP instance that you define
    virtual_router_id 52

#   Set the value of priority higher on the master server than on a backup server
    priority 100

    advert_int 1

    track_interface {
        br_nginx
        dummy0
    }

    track_script {
      keepalived_check
    }

    authentication {
        auth_type PASS
        auth_pass xxx
    }

    virtual_ipaddress {
        10.xx.xxx.xxx/24
    }

    notify /usr/local/bin/keepalived/nftables-master.sh
}
```

**Notify and track scripts**
```
#!/bin/bash

output=$(docker ps | grep nginx | grep Up)

if [[ -z "$output" ]];
then
  exit 1
fi
```

**System Log entries**
```
Oct 20 09:23:02 my-server Keepalived_vrrp[2652632]: Registering Kernel netlink command channel
Oct 20 09:23:02 my-server Keepalived[2652631]: Startup complete
Oct 20 09:23:02 my-server systemd[1]: Started LVS and VRRP High Availability Monitor.
Oct 20 09:23:02 my-server Keepalived_vrrp[2652632]: Assigned address 10.xx.xx.xx for interface ens18
Oct 20 09:23:02 my-server Keepalived_vrrp[2652632]: Assigned address fe80::xxxx:xxxx:xxxx:xxxx for interface ens18
Oct 20 09:23:02 my-server Keepalived_vrrp[2652632]: Registering gratuitous ARP shared channel
Oct 20 09:23:02 my-server Keepalived_vrrp[2652632]: (VRRP1) removing VIPs.
Oct 20 09:23:02 my-server Keepalived_vrrp[2652632]: VRRP sockpool: [ifindex(  2), family(IPv4), proto(112), fd(13,14)]
Oct 20 09:23:02 my-server Keepalived_vrrp[2652632]: Script `keepalived_check` now returning 1
Oct 20 09:23:02 my-server Keepalived_vrrp[2652632]: VRRP_Script(keepalived_check) failed (exited with status 1)
```

**Did keepalived coredump?**
```
No.
```

**Additional context**

**Comment by fansari** [comment]
Current workaround for me is to setup a systemd timer and corresponding service which writes the output of "docker ps | grep nginx" into a logfile. Then the keepalive script can read this.

For SELinux I had to add:

```
setsebool -P domain_can_mmap_files on
```

and this policy because I write the output to "/var/lib/scripts/keepalived/nginx.log" and keepalived must be able to read from there.

```
module mykeealived 1.0;

require {
        type var_lib_t;
        type systemd_systemctl_exec_t;
        type keepalived_t;
        class file { execute execute_no_trans getattr open read };
}

#============= keepalived_t ==============
allow keepalived_t systemd_systemctl_exec_t:file { execute execute_no_trans getattr open read };
allow keepalived_t var_lib_t:file { getattr open read };
```

**Comment by pqarmitage** [comment]
@fansari Apologies for not responding to this issue sooner. You are right that there needs to be additions to the SELinux policy, and that is outside the scope of keepalived itself; so far as I understand it that is something that the distro keepalived package maintainers must sort out, depending on how they set up keepalived in their distro. In addition, if a user (like you) needs keepalived to work outside the distro's SELinux policy, then there is no alternative but for the user to extend the policy.

Is setting `setsebool -P domain_can_mmap_files on` somewhat broader in scope than is necessary? Can it be limited to processes running in the context of keepalived?

**Comment by pqarmitage** [comment]
Closing due to no response for over 2 months.

**Comment by 1liminal1** [comment]
Hey there, 

I am having the same issue. Is there a way to selectively expand the security? I am using Alma Linux? 

Thanks so much

**Comment by 1liminal1** [comment]
Unable to access script `/usr/bin/docker` - disabling

Is the error Im getting :)

**Comment by SamB-GB** [comment]
I am also seeing the same issue.

This is my script

`#!/bin/sh
if [ -z "`docker ps --filter "name=traefik" --filter "status=running" -q`" ]; then
  echo "Traefik container is not running."
  exit 1
else
  echo "Traefik container is running."
fi`

**Comment by pqarmitage** [comment]
@SamB-GB You state you are seeing the same issue. Can you please explain exactly what you are seeing.

I note that your script does not have an explicit exit in the case of the _if_ test being false. While this means that the exit code will be the exit code of the _echo_ statement, it is not good practice to rely on that.

I think I would try changing
`if [ -z "`docker ps --filter "name=traefik" --filter "status=running" -q`" ]; then`
to
`if [ -z "`/usr/bin/docker ps --filter "name=traefik" --filter "status=running" -q`" ]; then`

You could also try adding near the beginning of the script:
`ls -l /usr/bin/docker >>/tmp/check_docker.log
to make sure that the script can see the docker executable.

You could also add a check:
```
if [[ ! -x /usr/bin/docker ]]; then echo /usr/bin/docker not executable >> /tmp/check_docker.log; else echo /usr/bin/docker is executable >>/tmp/check_docker.log; fi
```

This might give some indication about what is the cause of it failing.

**Comment by SamB-GB** [comment]
> @SamB-GB You state you are seeing the same issue. Can you please explain exactly what you are seeing.
> 
> I note that your script does not have an explicit exit in the case of the _if_ test being false. While this means that the exit code will be the exit code of the _echo_ statement, it is not good practice to rely on that.
> 
> I think I would try changing `if [ -z "`docker ps --filter "name=traefik" --filter "status=running" -q`" ]; then` to `if [ -z "`/usr/bin/docker ps --filter "name=traefik" --filter "status=running" -q`" ]; then`
> 
> You could also try adding near the beginning of the script: `ls -l /usr/bin/docker >>/tmp/check_docker.log to make sure that the script can see the docker executable.
> 
> You could also add a check:
> 
> ```
> if [[ ! -x /usr/bin/docker ]]; then echo /usr/bin/docker not executable >> /tmp/check_docker.log; else echo /usr/bin/docker is executable >>/tmp/check_docker.log; fi
> ```
> 
> This might give some indication about what is the cause of it failing.

It turns out the user that the script was running as had to have docker set as its primary group.
