### ISSUE TITLE
keepalived doesn't use vrrp_garp_master_refresh

### ISSUE THREAD

**Issue by Tiduster** [acassen/keepalived#223]
Hi !
I want to use vrrp_garp_master_refresh to make sure my network is aware of every failover between the slave and the master (we had at least one incident when it was not the case).

I used code from master branch on January 18th 2016.

When I set vrrp_garp_master_refresh to 10 in the global_defs section, I can see the parameter in the dumped configuration at startup.

```
2016-01-18T11:14:20+00:00 xxxlb04 Keepalived_vrrp[5824]:  Gratuitous ARP delay = 5
2016-01-18T11:14:20+00:00 xxxlb04 Keepalived_vrrp[5824]:  Gratuitous ARP refresh timer = 10
2016-01-18T11:14:20+00:00 xxxlb04 Keepalived_vrrp[5824]:  Gratuitous ARP repeat = 5
2016-01-18T11:14:20+00:00 xxxlb04 Keepalived_vrrp[5824]:  Gratuitous ARP refresh repeat = 1
```

But if I use tcpdump to check the GARP, there is nothing to see.
However, when I stop keepalived on the master server, I can see the garp request sent during the switch :

```
tcpdump -nteli any arp
ethertype ARP Request who-has xxx.xx.xx.xx (ff:ff:ff:ff:ff:ff) tell xxx.xx.xx.xx, length 46
ethertype ARP Request who-has yyy.yy.y.yy (ff:ff:ff:ff:ff:ff) tell yyy.yy.y.yy, length 46
```

I thought I would see this kind of request every 10 seconds using
"*vrrp_garp_master_refresh 10*". Am I misunderstanding something ?

Official documentation :
```
global_defs {          # Block identification
    notification_email {
       ...
    }
       ...
    vrrp_garp_master_refresh <INTEGER>     # Periodic delay in seconds
                       #  sending gratuitous ARP while in MASTER state
                       #  Default: 0 (no refreshing)
    vrrp_garp_master_refresh_repeat <INTEGER> # how many gratuitous
ARP messages shoule be sent
                       #  at each periodic repeat
                       #  Default: once (per period)
}
```

Here is my full keepalived.conf file :

```
global_defs {
    notification_email {
    xxx@polyconseil.fr
    xxx@polyconseil.fr
    }
    notification_email_from xxx@blue-solutions.com
    smtp_server 127.0.0.1
    smtp_connect_timeout 30
    vrrp_garp_master_refresh 10
}

vrrp_script 23c1ddc2-8091-5efc-aecc-9dd80657bfe0 {
    script "killall -0 haproxy"
    interval 2
    fall 2
    rise 4
}

vrrp_sync_group sync-group {
    group {
    ws-bi-vrrp
    ws-lb-vrrp
    }
}

vrrp_instance ws-bi-vrrp {
    interface eth2
    state BACKUP
    nopreempt
    advert_int 2
    virtual_router_id 16
    smtp_alert
    priority 118
    authentication {
        auth_type PASS
        auth_pass xxxxxxxxxx
    }
    track_interface {
    eth2
    }
    virtual_ipaddress {
    xxx.xx.xx.xx
    }
    track_script {
        23c1ddc2-8091-5efc-aecc-9dd80657bfe0
    }
}
vrrp_instance ws-lb-vrrp {
    interface eth1
    state BACKUP
    nopreempt
    advert_int 2
    virtual_router_id 20
    smtp_alert
    priority 118
    authentication {
        auth_type PASS
        auth_pass xxxxxxxxxx
    }
    track_interface {
    eth1
    eth2
    }
    virtual_ipaddress {
    yyy.yy.y.yy
    }
    track_script {
        23c1ddc2-8091-5efc-aecc-9dd80657bfe0
    }
}
```

Best regards,

PS : 
At first I use Debian version 1.2.13-1 and the parameter wasn't in the dumped configuration.
See : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810347
With latest version, the option appears to be taken into account, but it doesn't seem to work.

**Comment by pq17** [comment]
vrrp_garp_master_refresh is indeed the interval between sending gratuitous ARPs. However, these should only be sent after the transition to master, so as to speed up reconvergence. 

vrrp_garp_master_refresh_repeat is the parameter for how many of the messages should be sent after a transition to master, before it stops sending gratuitous ARPs and just responds to ARP requests.

**Comment by Tiduster** [comment]
Hi !
Thanks for your quick response.
Official documentation state : **Periodic delay in seconds sending gratuitous ARP while in MASTER state**. It doesn't say anything about the transition.

So I just misunderstood the doc ? I will try that right away.

**Comment by andreykaipov** [comment]
For anybody else from the future that encounters this issue -- check what version of Keepalived you're using.

The changelog http://www.keepalived.org/changelog.html has the entry `Fix unused global vrrp_garp_master_refresh` corresponding to PR https://github.com/acassen/keepalived/pull/379 for release 1.2.23 (2016-07-11). The apt archive for Ubuntu 16.04 has Keepalived at 1.2.19, which didn't even support any of the global garp parameters! Installing the latest version from source fixed every issue I had with the configuration.
