### ISSUE TITLE
Compilation problems ： error: macro "EVP_MD_CTX_new" passed 1 arguments, but takes just 0

### ISSUE THREAD

**Issue by JavenLaw** [acassen/keepalived#2230]
Linux Release Version ：CentOS 7.9
Keepalived Version ：keepalived-2.2.7

1，Download the keepalived-2.2.7 source package
2，configure && make
3，Everything is OK，because I use the system default openssl

**Here is system default openssl infomation :  OpenSSL 1.0.2k-fips**

When I compilation keepalived-2.2.7，it use system default  header file path ： /usr/inclue/openssl
There are some default header files in there

**Then i downloaded the latest version of openssl ：OpenSSL 3.0.7**

I installed OpenSSL 3.0.7，everything is ok

**Then i try to delete system default  header file ： /usr/inclue/openssl
And move new version  OpenSSL 3.0.7 's  header file to  : /usr/inclue/openssl**

just like this ： 

rm -rf  /usr/inclue/openssl                            **[delete system default  header file]**

cp -r  /usr/local/openssl-3.0.7/include/openssl  /usr/inclue/openssl/        **[move new  version openssl header file here ]**

**Then，I recompile keepalived-2.2.7**

something error ： 

```
  CC       main.o
In file included from /usr/include/openssl/x509.h:29,
                 from /usr/include/openssl/ssl.h:31,
                 from ../../keepalived/include/check_data.h:34,
                 from ../../keepalived/include/check_api.h:35,
                 from ../../keepalived/include/tracker.h:32,
                 from ../../keepalived/include/vrrp.h:42,
                 from ../../keepalived/include/global_data.h:50,
                 from main.c:44:
/usr/include/openssl/evp.h:696:32: error: macro "EVP_MD_CTX_new" passed 1 arguments, but takes just 0
  696 | EVP_MD_CTX *EVP_MD_CTX_new(void);
      |                                ^
In file included from main.c:23:
../../lib/config.h:46: note: macro "EVP_MD_CTX_new" defined here
   46 | #define EVP_MD_CTX_new() EVP_MD_CTX_create()
      |
make[2]: *** [Makefile:408: main.o] Error 1
```

I compared the two folder：

system default header file for openssl   

  **VS**     

latest  version for openssl 

**They are different，and the error could be ：**

latest  version for openssl ‘s  header file ： **evp.h   already defined "EVP_MD_CTX_new"**
but keepalived-2.2.7 header file in ：**keepalived-2.2.7/lib/ config.h  also defined "EVP_MD_CTX_new"**

because system default header file for openssl ’s  evp.h not defined "EVP_MD_CTX_new"
so when I use system default header file for openssl to compilation keepalived-2.2.7 is OK

**Here is my confused :**  
1，If I install the latest version OpenSSL 3.0.7，because I want to use the latest version OpenSSL
but use system default header file for openssl to compilation keepalived-2.2.7，will it cause unknown problems？

2，If I don't want to use the old version OpenSSL 1.0.2k-fips，I just delete system default version OpenSSL 1.0.2k-fips
how do I use new version OpenSSL 3.0.7's header file to compilation keepalived-2.2.7?

Thanks

**Comment by pqarmitage** [comment]
Simply moving the OpenSSL header files is unlikely to work unless you also update the library files and pkgconfig files. openSSL probably provides a `make install` to do this.

In the keepalived lib/config.h file, there is a comment for EVP_MD_CTX_new: `/* Named changed in OpenSSL v1.1.0 */`.

You will need to rerun the keepalived configure script after upgrading the OpenSSL header files so that it will regenerate lib/config.h so that it will be suitable for the new build environment that you have created.

If you haven't also updated the library and pkgconfig files, then it is likely that the keepalived build will fail elsewhere as well.

**Comment by JavenLaw** [comment]
Thank you so much.
