### ISSUE TITLE
Keepalived entering fault state on reboot

### ISSUE THREAD

**Issue by nichols89ben** [acassen/keepalived#2237]
**Describe the bug**
Trying to figure out why the system fails to come back online. Anytime either the master or backup is rebooted, it fails, showing eth0 down or src address not configured. When keepalived is restarted, everything comes back online

**To Reproduce**
Any steps necessary to reproduce the behaviour: sudo reboot raspberry pi

**Expected behavior**
Once the master is rebooted, it will take the place of master again and the other instance will revert to back up 

**Keepalived version**
Keepalived v2.1.5 (07/13,2020)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.10.46
Running on Linux 5.15.76-v7+ #1597 SMP Fri Nov 4 12:13:17 GMT 2022

configure options: --build=arm-linux-gnueabihf --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/arm-linux-gnueabihf --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --with-kernel-dir=debian/ --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus --enable-json --enable-bfd --enable-regex build_alias=arm-linux-gnueabihf CFLAGS=-g -O2 -ffile-prefix-map=/build/keepalived-KUiI8G/keepalived-2.1.5=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  NFTABLES LVS REGEX VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK
```




**Configuration file:**
```
global_defs {

router_id pihole-dns-01

script_user root

enable_script_security

}

vrrp_script chk_ftl {

script "/etc/scripts/chk_ftl"

interval 1

weight -10

}

vrrp_instance PIHOLE {

state MASTER

interface eth0

virtual_router_id 55

priority 200

advert_int 1

unicast_src_ip [192.168.1.208/24](https://192.168.1.208/24)

unicast_peer {

[192.168.1.206/24](https://192.168.1.206/24)

}

authentication {

auth_type PASS

auth_pass

}

virtual_ipaddress {

[192.168.1.2/24](https://192.168.1.2/24)

}

track_script {

chk_ftl

}

}

________________________________________________________________

global_defs {

router_id pihole-dns-02

script_user root

enable_script_security

}

vrrp_script chk_ftl {

script "/etc/scripts/chk_ftl"

interval 1

weight -10

}

vrrp_instance PIHOLE {

state BACKUP

interface eth0

virtual_router_id 55

priority 100

advert_int 1

unicast_src_ip [192.168.1.206/24](https://192.168.1.206/24)

unicast_peer {

[192.168.1.208/24](https://192.168.1.208/24)

}

authentication {

auth_type PASS

auth_pass

}

virtual_ipaddress {

[192.168.1.2/24](https://192.168.1.2/24)

}

track_script {

chk_ftl

}

}
```
**System Log entries**
raspberryben@raspberrypi:~ $ sudo systemctl status keepalived.service

● keepalived.service - Keepalive Daemon (LVS and VRRP)

Loaded: loaded (/lib/systemd/system/keepalived.service; enabled; vendor preset: enabled)

Active: active (running) since Mon 2022-12-26 23:56:27 EST; 1min 58s ago

Main PID: 677 (keepalived)

Tasks: 2 (limit: 4915)

CPU: 6.727s

CGroup: /system.slice/keepalived.service

├─677 /usr/sbin/keepalived --dont-fork

└─721 /usr/sbin/keepalived --dont-fork


Dec 26 23:56:28 raspberrypi Keepalived[677]: Starting VRRP child process, pid=721

Dec 26 23:56:28 raspberrypi Keepalived_vrrp[721]: Registering Kernel netlink reflector

Dec 26 23:56:28 raspberrypi Keepalived_vrrp[721]: Registering Kernel netlink command channel

Dec 26 23:56:28 raspberrypi Keepalived_vrrp[721]: Opening file '/etc/keepalived/keepalived.conf'.

Dec 26 23:56:28 raspberrypi Keepalived_vrrp[721]: (PIHOLE): entering FAULT state (interface eth0 down)

Dec 26 23:56:28 raspberrypi Keepalived_vrrp[721]: (PIHOLE) entering FAULT state

Dec 26 23:56:28 raspberrypi Keepalived_vrrp[721]: Registering gratuitous ARP shared channel

Dec 26 23:56:28 raspberrypi Keepalived_vrrp[721]: bind unicast_src [192.168.1.208](https://192.168.1.208/) failed 99 - Cannot assign requested a>

Dec 26 23:56:28 raspberrypi Keepalived_vrrp[721]: VRRP_Script(chk_ftl) succeeded

Dec 26 23:56:32 raspberrypi Keepalived_vrrp[721]: Netlink reports eth0 up

lines 1-20/20 (END)


________________________________________________________________

raspberryben@raspberrypi:~ $ sudo systemctl status keepalived.service

● keepalived.service - Keepalive Daemon (LVS and VRRP)

Loaded: loaded (/lib/systemd/system/keepalived.service; enabled; vendor preset: enabled)

Active: active (running) since Mon 2022-12-26 23:55:51 EST; 5min ago

Main PID: 5288 (keepalived)

Tasks: 2 (limit: 1596)

CPU: 31.097s

CGroup: /system.slice/keepalived.service

├─5288 /usr/sbin/keepalived --dont-fork

└─5289 /usr/sbin/keepalived --dont-fork


Dec 26 23:55:51 raspberrypi Keepalived[5288]: NOTICE: setting config option max_auto_priority should result in better keepalived perform>

Dec 26 23:55:51 raspberrypi Keepalived[5288]: Starting VRRP child process, pid=5289

Dec 26 23:55:51 raspberrypi Keepalived_vrrp[5289]: Registering Kernel netlink reflector

Dec 26 23:55:51 raspberrypi Keepalived_vrrp[5289]: Registering Kernel netlink command channel

Dec 26 23:55:51 raspberrypi Keepalived_vrrp[5289]: Opening file '/etc/keepalived/keepalived.conf'.

Dec 26 23:55:51 raspberrypi Keepalived_vrrp[5289]: Registering gratuitous ARP shared channel

Dec 26 23:55:51 raspberrypi Keepalived_vrrp[5289]: (PIHOLE) Entering BACKUP STATE (init)

Dec 26 23:55:51 raspberrypi Keepalived_vrrp[5289]: VRRP_Script(chk_ftl) succeeded

Dec 26 23:56:13 raspberrypi Keepalived_vrrp[5289]: (PIHOLE) Backup received priority 0 advertisement

Dec 26 23:56:14 raspberrypi Keepalived_vrrp[5289]: (PIHOLE) Entering MASTER STATE

**When back up is rebooted**


raspberryben@raspberrypi:~ $ sudo systemctl status keepalived.service

● keepalived.service - Keepalive Daemon (LVS and VRRP)

Loaded: loaded (/lib/systemd/system/keepalived.service; enabled; vendor preset: enabled)

Active: active (running) since Tue 2022-12-27 00:05:10 EST; 2min 28s ago

Main PID: 496 (keepalived)

Tasks: 2 (limit: 1596)

CPU: 12.090s

CGroup: /system.slice/keepalived.service

├─496 /usr/sbin/keepalived --dont-fork

└─616 /usr/sbin/keepalived --dont-fork


Dec 27 00:05:11 raspberrypi Keepalived[496]: NOTICE: setting config option max_auto_priority should result in better keepalived performa>

Dec 27 00:05:11 raspberrypi Keepalived[496]: Starting VRRP child process, pid=616

Dec 27 00:05:11 raspberrypi Keepalived_vrrp[616]: Registering Kernel netlink reflector

Dec 27 00:05:11 raspberrypi Keepalived_vrrp[616]: Registering Kernel netlink command channel

Dec 27 00:05:11 raspberrypi Keepalived_vrrp[616]: Opening file '/etc/keepalived/keepalived.conf'.

Dec 27 00:05:11 raspberrypi Keepalived_vrrp[616]: Registering gratuitous ARP shared channel

Dec 27 00:05:11 raspberrypi Keepalived_vrrp[616]: bind unicast_src [192.168.1.206](https://192.168.1.206/) failed 99 - Cannot assign requested address

Dec 27 00:05:11 raspberrypi Keepalived_vrrp[616]: (PIHOLE): entering FAULT state (src address not configured)

Dec 27 00:05:11 raspberrypi Keepalived_vrrp[616]: (PIHOLE) Entering FAULT STATE

Dec 27 00:05:12 raspberrypi Keepalived_vrrp[616]: VRRP_Script(chk_ftl) succeeded

lines 1-20/20 (END)

**Comment by pqarmitage** [comment]
The problem is that keepalived is starting up too early. keepalived reports that eth0 is down (which is not a problem in itself, since keepalived can recover from this situation), but the problem relates to the message `bind unicast_src [192.168.1.206](https://192.168.1.206/) failed 99 - Cannot assign requested address`. It would appear that although `/lib/systemd/system/keepalived.service` has:
```
After=network-online.target
Wants=network-online.target
```
keepalived is actually starting up before the 192.168.1.206/24 address has been configured on eth0. The bind() call then fails, and keepalived cannot listen on the socket. See systemd.special(7) man page for a description of `network-online.target`.

The solution to this problem is to delay keepalived starting running the vrrp code. This is achieved by adding a `vrrp_startup_delay` entry in the global_defs section of the config (see keepalived.conf(5) man page for more details). You will need to experiment with the amount of delay to find out what works for you.

**Comment by nichols89ben** [comment]
Thank you, that fixed the issue. To answer your latter question, that was the log when the backup was rebooted and failed to come back online. However, the startup delay resolved that, as well
