### ISSUE TITLE
Lvs+keepalived+nginx's online and offline operations on keepalived directly

### ISSUE THREAD

**Issue by opencmit2** [acassen/keepalived#2240]
Lvs+keepalived+nginx directly carries out online and offline operations on keepalived. After modifying keepalived.config, when reloading, there will be a one-second loss of business orders. This phenomenon has not been solved. Is there a better way not to restart the keepalived process

**Comment by pqarmitage** [comment]
@opencmit2 I don't really understand what you are asking. However, if you are asking about modifying keepalived's configuration and then getting keepalived to use that new configuration without restarting the keepalived process, then the best way is to send SIGHUP to the parent keepalived process. keepalived will continue running and will read the new configuration and make any changes necessary to update from the old configuration to the new configuration.

**Comment by opencmit2** [comment]
At the time of production release, we switch between production and grayscale by modifying keepalived.conf to ensure uninterrupted links and business. When I modify keepalived.conf and reload, some links will be lost on keepalived, which will cause some links to be interrupted. I am eager to hope that I do not need reload when modifying keepalived.conf

**Comment by pqarmitage** [comment]
@opencmit2 I think you need to provide complete details of what you are doing including:

- the output of `keepalived -v`, and `uname -a`
- a copy of keepalived.conf before it is modified
- a copy of keepalived.conf after it is modified
- the keepalived syslogs for 5 minutes before and after the reload
- the exact commands you execute to do the reload

Once we can see this, then we might be able to work out what is happening.

**Comment by pqarmitage** [comment]
Closing due to no reply for over two weeks.
