### ISSUE TITLE
keepalived does not seem to correctly configure the sync daemon.

### ISSUE THREAD

**Issue by yctn** [acassen/keepalived#2242]
i have the following global_defs in my config.
```
global_defs {
        lvs_timeouts tcp 3600 tcpfin 720 udp 300
        lvs_sync_daemon eth2
}
```
then this shows up ion my logs.
```
lvs_sync_daemon requires interface, VRRP instance
```
here some more info.
```
ipvsadm --list --daemon
master sync daemon (mcast=eth1, syncid=0)

keepalived -v
Keepalived v2.0.19 (10/19,2019)
```

i think i am missing something in the global_defs but i am not quite sure what.

**Comment by pqarmitage** [comment]
The man page for keepalive.conf(5) for keepalived v2.0.19 states:
```
    # Sync daemon as provided by IPVS kernel code only support
    # a single daemon instance at a time to synchronize connection table.
    # Binding interface, vrrp instance and optional
    #  syncid for lvs syncd
    #  syncid (0 to 255) for lvs syncd
    #  maxlen (1..65507) maximum packet length
    #  port (1..65535) UDP port number to use
    #  ttl (1..255)
    #  group - multicast group address (IPv4 or IPv6)
    # NOTE: maxlen, port, ttl and group are only available on Linux 4.3 or later.
    \fBlvs_sync_daemon \fR<INTERFACE> <VRRP_INSTANCE> [id <SYNC_ID>] [maxlen <LEN>] \e
                    [port <PORT>] [ttl <TTL>] [group <IP ADDR>]
```
so both an interface and vrrp instance are required.

Later, in commit ef3bbd6fe I added code to remove the requirement to specify a VRRP instance, and then both the master and backup sync daemons run on all systems regardless of the state of any VRRP instance.

So your choice is either remain with keepalived v2.0.19 and add a VRRP interface, or upgrade to a recent version of keepalived and the VRRP interface doesn't need to be added.
