### ISSUE TITLE
The nopreempt option is ignored

### ISSUE THREAD

**Issue by arudyavsky** [acassen/keepalived#2257]
**Describe the bug**
The nopreempt option is completely ignored/not work.

**To Reproduce**
I use two VirtualBox with Debian 11. Both are configured as Backup.

- A is Master, B is Backup
- A was down, B become Master
- A is up state again and become Master, B - Backup

**Expected behavior**
If nopreempt is set, after A comming up, A should stay Bacup, B - Master.

I have try:
- vrrp_startup_delay for pause afret reboot - no effect
- unicast_peer  - no effect
- After=network-online.target in systemd - no effect
- delete nopreempt - no effect

Always the higher priority wins and become Master. 

**Keepalived version**
```
Keepalived v2.1.5 (07/13,2020)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.10.70
Running on Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21)

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --with-kernel-dir=debian/ --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus --enable-json --enable-bfd --enable-regex build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -ffile-prefix-map=/build/keepalived-jCUlld/keepalived-2.1.5=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  NFTABLES LVS REGEX VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK
```

**Distro (please complete the following information):**
 - Name: Debian
 - Version: 11
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
I use two VirtualBox with Debian 11. Only keepalived was installed.  Pause is used to stop/start VM.

**Configuration file:**
Configuration is very simple
```
global_defs {
   max_auto_priority 99
   vrrp_startup_delay 10
}

vrrp_instance VI_1 {
  state BACKUP
  interface enp0s3
  virtual_router_id 51
  priority 51                        # 51 for A node, 50 - for B
  advert_int 1
  nopreempt
  virtual_ipaddress {
    192.168.1.180
  }
}
```

**Notify and track scripts**
Not used

**System Log entries**
```
A node (was Master - down - up again)

Mar 20 03:14:43 keepalived1 Keepalived[9757]: Starting Keepalived v2.1.5 (07/13,2020)
Mar 20 03:14:43 keepalived1 Keepalived[9757]: WARNING - keepalived was build for newer Linux 5.10.70, running on Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21)
Mar 20 03:14:43 keepalived1 Keepalived[9757]: Command line: '/usr/sbin/keepalived' '--dont-fork'
Mar 20 03:14:43 keepalived1 Keepalived[9757]: Opening file '/etc/keepalived/keepalived.conf'.
Mar 20 03:14:43 keepalived1 Keepalived[9757]: Starting VRRP child process, pid=9759
Mar 20 03:14:43 keepalived1 Keepalived_vrrp[9759]: Registering Kernel netlink reflector
Mar 20 03:14:43 keepalived1 Keepalived_vrrp[9759]: Registering Kernel netlink command channel
Mar 20 03:14:43 keepalived1 Keepalived_vrrp[9759]: Opening file '/etc/keepalived/keepalived.conf'.
Mar 20 03:14:43 keepalived1 Keepalived_vrrp[9759]: Registering gratuitous ARP shared channel
Mar 20 03:14:43 keepalived1 Keepalived_vrrp[9759]: Delaying startup for 10 seconds
Mar 20 03:14:53 keepalived1 Keepalived_vrrp[9759]: (VI_1) Entering BACKUP STATE (init)
Mar 20 03:14:57 keepalived1 Keepalived_vrrp[9759]: (VI_1) Entering MASTER STATE

B node (was Backup - become Master - Backup again)

Mar 20 03:14:44 keepalived2 Keepalived[9673]: Starting Keepalived v2.1.5 (07/13,2020)
Mar 20 03:14:44 keepalived2 Keepalived[9673]: WARNING - keepalived was build for newer Linux 5.10.70, running on Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21)
Mar 20 03:14:44 keepalived2 Keepalived[9673]: Command line: '/usr/sbin/keepalived' '--dont-fork'
Mar 20 03:14:44 keepalived2 Keepalived[9673]: Opening file '/etc/keepalived/keepalived.conf'.
Mar 20 03:14:44 keepalived2 Keepalived[9673]: Starting VRRP child process, pid=9693
Mar 20 03:14:44 keepalived2 Keepalived_vrrp[9693]: Registering Kernel netlink reflector
Mar 20 03:14:44 keepalived2 Keepalived_vrrp[9693]: Registering Kernel netlink command channel
Mar 20 03:14:44 keepalived2 Keepalived_vrrp[9693]: Opening file '/etc/keepalived/keepalived.conf'.
Mar 20 03:14:44 keepalived2 Keepalived_vrrp[9693]: Registering gratuitous ARP shared channel
Mar 20 03:14:44 keepalived2 Keepalived_vrrp[9693]: Delaying startup for 10 seconds
Mar 20 03:14:54 keepalived2 Keepalived_vrrp[9693]: (VI_1) Entering BACKUP STATE (init)
Mar 20 03:15:25 keepalived2 Keepalived_vrrp[9693]: (VI_1) Entering MASTER STATE
Mar 20 03:15:42 keepalived2 Keepalived_vrrp[9693]: (VI_1) Master received advert from 192.168.1.181 with higher priority 51, ours 50
Mar 20 03:15:42 keepalived2 Keepalived_vrrp[9693]: (VI_1) Entering BACKUP STATE
```

**Did keepalived coredump?**
```
no
```

**Additional context**
I found several other issues with the same symptoms https://github.com/acassen/keepalived/issues/2032, https://github.com/acassen/keepalived/issues/2209, https://github.com/acassen/keepalived/issues/2220. But they have been closed.

**Comment by pqarmitage** [comment]
nopreempt does work, and has been tested multiple times.

This issue is usually due to protocol 112 not being explicitly enabled in your firewalls. See issue #2209 for a detailed explanation.

**Comment by arudyavsky** [comment]
I didn't find any information that Debian blocks VRRP by default. I don't use firewall, iproute. No router, host network only. I don't know anything about blocking VRRP by VirtualBox. What should I do?

**Comment by pqarmitage** [comment]
This is definitely not a preempt issue (nopreempt stops a higher priority instance becoming master when a lower priority instance is already master). Node A becomes master at 03:14:57, and node B becomes master at 03:15:25, but node B is lower priority than node A. Also it takes a further 17 seconds after node B becomes master before it sees the adverts from node A. The only reason that this can happen is that node B is not receiving the adverts from node A.

This doesn't look like the firewall issue described in #2209 since in that case node B should start seeing adverts from node A as soon as node B has sent an advert.

You will need to investigate why node B is not receiving adverts from node A until 03:15:42. Does extending the startup delay help?

This is not a keepalived issue, and unfortunately there is little more that we can help with.

**Comment by arudyavsky** [comment]
Pause. I need more time for tests...

**Comment by arudyavsky** [comment]
I have done over 10 tests and the behavior is always the same. I set "advert_int 5" (5 seconds to get rid of network transients). To avoid multicasting 224.0.0.18, I use 'unicast_peer {}'. Other settings remain the same. I captured networks by "tcpdump -vvv -ni enp0s3 vrrp" on all two nodes.

Initial state:
Node A (192.168.1.181) - Master. Prio 51 
Node B (192.168.1.182) - Backup. Prio 50

A send Advertisment to B (id: 26,27)
```
12:59:56.317297 IP (tos 0xc0, ttl 255, id 26, offset 0, flags [none], proto VRRP (112), length 40)
    192.168.1.181 > 192.168.1.182: VRRPv2, Advertisement, vrid 51, prio 51, authtype none, intvl 5s, length 20, addrs: 192.168.1.180
13:00:01.317582 IP (tos 0xc0, ttl 255, id 27, offset 0, flags [none], proto VRRP (112), length 40)
    192.168.1.181 > 192.168.1.182: VRRPv2, Advertisement, vrid 51, prio 51, authtype none, intvl 5s, length 20, addrs: 192.168.1.180
```
B reseived advert (id: 26,27)
```
12:59:56.319173 IP (tos 0xc0, ttl 255, id 26, offset 0, flags [none], proto VRRP (112), length 40)
    192.168.1.181 > 192.168.1.182: VRRPv2, Advertisement, vrid 51, prio 51, authtype none, intvl 5s, length 20, addrs: 192.168.1.180
13:00:01.319601 IP (tos 0xc0, ttl 255, id 27, offset 0, flags [none], proto VRRP (112), length 40)
    192.168.1.181 > 192.168.1.182: VRRPv2, Advertisement, vrid 51, prio 51, authtype none, intvl 5s, length 20, addrs: 192.168.1.180
```
A stopped at 13:00:03 (no reboot, no restart. VM paused).
B become Master and send Advertisment to A (id: 1,2).
```
Mar 30 13:00:17 keepalived2 Keepalived_vrrp[737]: (VI_1) Entering MASTER STATE

13:00:17.125212 IP (tos 0xc0, ttl 255, id 1, offset 0, flags [none], proto VRRP (112), length 40)
    192.168.1.182 > 192.168.1.181: VRRPv2, Advertisement, vrid 51, prio 50, authtype none, intvl 5s, length 20, addrs: 192.168.1.180
13:00:22.125483 IP (tos 0xc0, ttl 255, id 2, offset 0, flags [none], proto VRRP (112), length 40)
    192.168.1.182 > 192.168.1.181: VRRPv2, Advertisement, vrid 51, prio 50, authtype none, intvl 5s, length 20, addrs: 192.168.1.180

A started again at 13:08:18 (~8 min elapsed). No restart, No reboot. VM unpaused and continue executing from last state. 
B send advert to A (id: 97)
```
13:08:18.156173 IP (tos 0xc0, ttl 255, id 97, offset 0, flags [none], proto VRRP (112), length 40)
    192.168.1.182 > 192.168.1.181: VRRPv2, Advertisement, vrid 51, prio 50, authtype none, intvl 5s, length 20, addrs: 192.168.1.180
```
A received Advert from B. The same id = 97. But time not syncing...
```
13:00:03.474683 IP (tos 0xc0, ttl 255, id 97, offset 0, flags [none], proto VRRP (112), length 40)
    192.168.1.182 > 192.168.1.181: VRRPv2, Advertisement, vrid 51, prio 50, authtype none, intvl 5s, length 20, addrs: 192.168.1.180
```
A ignore this advert (id:97) and continue sending self advertisments (id: 28,29) to B.  
```
Mar 30 13:00:03 keepalived1 Keepalived_vrrp[797]: (VI_1) Received advert from 192.168.1.182 with lower priority 50, ours 51, forcing new election

13:00:03.474798 IP (tos 0xc0, ttl 255, id 28, offset 0, flags [none], proto VRRP (112), length 40)
    192.168.1.181 > 192.168.1.182: VRRPv2, Advertisement, vrid 51, prio 51, authtype none, intvl 5s, length 20, addrs: 192.168.1.180
13:00:08.475860 IP (tos 0xc0, ttl 255, id 29, offset 0, flags [none], proto VRRP (112), length 40)
    192.168.1.181 > 192.168.1.182: VRRPv2, Advertisement, vrid 51, prio 51, authtype none, intvl 5s, length 20, addrs: 192.168.1.180
```
B receive advert (id: 28,29). 51 > 50 - highter prio wins. B become Backup and stop sending adverts to A.
```
Mar 30 13:08:18 keepalived2 Keepalived_vrrp[737]: (VI_1) Master received advert from 192.168.1.181 with higher priority 51, ours 50
Mar 30 13:08:18 keepalived2 Keepalived_vrrp[737]: (VI_1) Entering BACKUP STATE

13:08:18.156472 IP (tos 0xc0, ttl 255, id 28, offset 0, flags [none], proto VRRP (112), length 40)
    192.168.1.181 > 192.168.1.182: VRRPv2, Advertisement, vrid 51, prio 51, authtype none, intvl 5s, length 20, addrs: 192.168.1.180
13:08:23.157644 IP (tos 0xc0, ttl 255, id 29, offset 0, flags [none], proto VRRP (112), length 40)
    192.168.1.181 > 192.168.1.182: VRRPv2, Advertisement, vrid 51, prio 51, authtype none, intvl 5s, length 20, addrs: 192.168.1.180
```
We have initial state again...

My probles is that:
- I don`t know what will be on the nodes. VM or baremetal.
- Some routers/switches/units routers/switches don't understand that VIP changes and keep sending packets to the same MAC address according to their translation table. SIP phones, for example.

**Comment by pqarmitage** [comment]
After VM A is paused, keepalived on VM B stops receiving adverts and takes over as master, which is correct.

When VM A is unpaused, the time on VM A has not moved forwards, and keepalived on VM A is still in master state and so it continues sending adverts (processes on VM A are not aware that the VM was paused, and they see it that time has moved forward continuously without a pause). keepalived is behaving correctly in this circumstance.

The problem is that pausing the VM is not a valid test of keepalived's behaviour. If you stop the keepalived process on VM A, wait for at least 20 seconds, then start keepalived again, you will see that keepalived on VM A remains in backup state, demonstrating that nopreempt is working correctly.
