### ISSUE TITLE
BFD multihop on port 3784 (RFC5881) instead of port 4784 (RFC5883)

### ISSUE THREAD

**Issue by mwetterw** [acassen/keepalived#2267]
**Describe the bug**
When letting keepalived do multihop BFD, it still uses port 3784 which is the one for direct (single hop) BFD only.
So when keepalived is for example talking BFD with bird, bird will verify if the TTL is equal to 255. If it isn't, it will reject it.
RFC5881 has a MUST clause for this, so bird is correct to do this check and to reject the packets coming from keepalived.

[RFC5881](https://www.rfc-editor.org/rfc/rfc5881#section-5)

```
5.  TTL/Hop Limit Issues
   If BFD authentication is not in use on a session, all BFD Control
   packets for the session MUST be sent with a Time to Live (TTL) or Hop
   Limit value of 255.  All received BFD Control packets that are
   demultiplexed to the session MUST be discarded if the received TTL or
   Hop Limit is not equal to 255.  A discussion of this mechanism can be
   found in [[GTSM](https://www.rfc-editor.org/rfc/rfc5881#ref-GTSM)].
```

**To Reproduce**
Try to mount a multihop BFD session between keepalived on one side, and a program which is not keepalived on the other side.
(Make sure there is at least one routing hop between the 2 BFD endpoints to make sure the original TTL will be decreased.)

**Expected behavior**
Keepalived should use port 4784 for multihop, and port 3784 for direct (single hop) BFD.

**Keepalived version**
```
# keepalived -v
keepalived vv2.2.7 (01/16,2022)

Copyright(C) 2001-2022 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.19.88
Running on Linux 6.1.19 SMP Wed Mar 29 14:17:28 UTC 2023

configure options:  

Config options: 

System options:
```
(Build is a bit custom, so the above options are empty. I just activated VRRP, BFD and LVS.)

**Distro (please complete the following information):**
 - Name: N/A
 - Version: N/A
 - Architecture: x86_64
(Distro is not an existing one, it's a custom distro.)

**Details of any containerisation or hosted service (e.g. AWS)**

**Configuration file:**
```
$BFD= \
bfd_instance bfd_$RS_NUM { \
    neighbor_ip 192.168.0.$RS_NUM \
    source_ip 192.168.0.${_INSTANCE} \
    min_rx 20 \
    min_tx 50 \
    idle_tx 1000 \
    ttl 64 \
    max_hops 2 \
    checker \
}
~SEQ(RS_NUM, 1, 3) $BFD

virtual_server 192.168.1.254 8080 {
[...]
    alpha
    connect_timeout 1
    retry 1
    delay_before_retry 1
    delay_loop 1
    warmup 10

    $RS= \
    real_server 192.168.0.$RS_NUM 8080 { \
        BFD_CHECK { \
            name bfd_$RS_NUM \
        } \
    }

    ~SEQ(RS_NUM, 1, 3) $RS
}

```

**Notify and track scripts**

**System Log entries**
Keepalived looks happy in the logs, but all BFD sessions are DOWN, so no backend will be enabled.

**Did keepalived coredump?**
No

**Additional context**
Things work when connecting 2 keepalived through BFD, because both keepalived agree on their BFD standard, so they will succeed to communicate. It becomes problematic when trying to interoperate with other software talking BFD.

**Comment by pqarmitage** [comment]
Commit [fc7840c](https://github.com/acassen/keepalived/pull/2269/commits/fc7840cd1ba0a5bc1171fd970aa8de97ec45a1ff) (along with commit [7f607ec](https://github.com/acassen/keepalived/pull/2269/commits/7f607ec95edffabdbd5f9a668b9a047605acf878) to fix compiling when using sockaddr_storage) adds a _multihop_ option for bfd_instance blocks.

Although in theory the _max_hops_ configuration option could be used to determine that multihop is being used, some users may already be specifying that and using port 3784 (admittedly contrary to RFC5881). I therefore decided to add the keyword _multihop_ to specify the use of port 4784 instead of port 3784.
