### ISSUE TITLE
I compiled keepalived on ARM successfully, but when I tried to execute the keepalived binary file, an error occurred.

### ISSUE THREAD

**Issue by JamesIsHuang** [acassen/keepalived#2285]
**Describe the bug**
I compiled keepalived on ARM successfully, but when I tried to execute the keepalived binary file, an error occurred.

Error message: keepalived: keepalived: cannot execute binary file.

**Comment by pqarmitage** [comment]
We need much more information to have any chance of identifying what the cause of the problem might be.

**Comment by nser77** [comment]
A lot of information and details are missing, maybe other users can ask you to paste more relevant informations.

Anyway, the error meens that OS do not reconize the file as executable script; if you compiled on ARM, the architecture could be the problem.

**Comment by JamesIsHuang** [comment]
I fixed it. Thank you.
