### ISSUE TITLE
A compilation error occurs when VRRP_VMAC is not enabled

### ISSUE THREAD

**Issue by lbo874** [acassen/keepalived#2294]
**Describe the bug**
Compilation encountered a compilation error. Error in function netlink_if_address_filter When I cancel the option VRRP_ VMAC.

The make log is as follows:
keepalived_netlink.c: In function ‘netlink_if_address_filter’:
keepalived_netlink.c:1180:21: error: ‘VRRP_VMAC_BIT’ undeclared (first use in this function)
 1180 |         !__test_bit(VRRP_VMAC_BIT, &vrrp->flags) ||
      |                     ^~~~~~~~~~~~~
keepalived_netlink.c:1180:21: note: each undeclared identifier is reported only once for each function it appears in
keepalived_netlink.c:1181:20: error: ‘VRRP_VMAC_XMITBASE_BIT’ undeclared (first use in this function)
 1181 |         __test_bit(VRRP_VMAC_XMITBASE_BIT, &vrrp->flags) ||
      |                    ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:407: keepalived_netlink.o] Error 1
make[2]: Leaving directory '/root/github/keepalived/keepalived/core'
make[1]: *** [Makefile:562: all-recursive] Error 1
make[1]: Leaving directory '/root/github/keepalived/keepalived'
make: *** [Makefile:447: all-recursive] Error 1

**Expected behavior**
Compile sucess

**Keepalived version**
Keepalived v2.2.4 (08/21,2021)

I guess it's because：
When VRRP_VMAC is disabled, VRRP_VMAC_BIT and VRRP_VMAC_XMITBASE_BIT do not take effect in enum vrrp_flags_bits. However, conditional compilation is missing when VRRP_VMAC_BIT and VRRP_VMAC_XMITBASE_BIT are used in netlink_if_address_filter():
https://github.com/acassen/keepalived/blob/master/keepalived/core/keepalived_netlink.c#L1180

**Comment by lbo874** [comment]
Please take a look at this issue. Thank you very much.

**Comment by pqarmitage** [comment]
Patch now merged. Apologies for the delay.
