### ISSUE TITLE
Keepalived.service got notification from from PID 3977, but reception only permitted for main PID 3976. + Ignoring track_interface enp0s1 since own interface

### ISSUE THREAD

**Issue by kunal-2309** [acassen/keepalived#2302]
vrrp_instance VI_1 {
    state MASTER
    interface enp0s1
    virtual_router_id 51
    priority 255

    virtual_ipaddress {
        192.168.64.200
    }

    unicast_src_ip 192.168.64.8
    unicast_peer {
        192.168.64.9
    }

    track_interface {
        enp0s1
    }
This is my config file. I don't understand what I am doing wrong
<img width="1728" alt="Screenshot 2023-05-19 at 3 07 03 AM" src="https://github.com/acassen/keepalived/assets/82146002/87ba271f-3edd-44e6-8d06-0c8d76793cee">

**Comment by pqarmitage** [comment]
Please provide some details regarding what is happening. What is the contents of your keepalived.service file? What version of keepalived are you using? What kernel and systemd versions are you using? What distro and version are you running on?

The problem probably relates to the keepalived.service file configuration.

There is some explanation in source file lib/systemd.c:
```
/* Clear the environment variable NOTIFY_SOCKET to stop any
 * child processes we create sending notify messages to systemd */
void
systemd_unset_notify(void)
{
        /* This is only called in a child process of the main
         * process. If the systemd service type is notify (e.g. Debian),
         * then systemd will log:
         *   keepalived.service: Got notification message from PID nnnn, but reception only permitted for main PID nnnm
         * We therefore need to appear as though our parent process (the main process) is sending the message.
         *
         * In fact, it seems a bit daft to send a message just to clear a local environment variable, but this seems to
         * be the only option offered by systemd.
         */
        if (parent_is_systemd) {
#ifdef HAVE_SD_PID_NOTIFY
                sd_pid_notify(getppid(), 1, "");
#else
                /* The above systemd message will be logged, but we don't have the functionality to stop it other
                 * than setting NotifyAccess=all, but that is dangerous. */
                sd_notify(1, "");
#endif
        }
}
```
The code to use `sd_pid_notify()` was only added in November 2022, and so the first release version of keepalived that included the functionality is v2.2.8 which was released in May this year.

If you are using a version of keepalived prior to v2.2.8, then either upgrade to v2.2.8 or ignore the log message.
