### ISSUE TITLE
pid 131 exited with permanent error missing permission. Terminating

### ISSUE THREAD

**Issue by Lewis1990** [acassen/keepalived#2307]
[service@3e02cd4de182 home]$ /usr/sbin/keepalived --dont-fork --log-console -p /home/service/keepalived.pid -r /home/service/vrrp.pid -f /etc/keepalived/keepalived.conf
Mon Jun 12 22:31:00 2023: Starting Keepalived v2.2.7 (01/16,2022)
Keepalived[130]: Starting Keepalived v2.2.7 (01/16,2022)
Mon Jun 12 22:31:00 2023: WARNING - keepalived was built for newer Linux 4.18.0, running on Linux 3.10.0-862.14.1.5.h520.eulerosv2r7.x86_64 #1 SMP Wed Nov 25 18:33:06 UTC 2020
Keepalived[130]: WARNING - keepalived was built for newer Linux 4.18.0, running on Linux 3.10.0-862.14.1.5.h520.eulerosv2r7.x86_64 #1 SMP Wed Nov 25 18:33:06 UTC 2020
Mon Jun 12 22:31:00 2023: Command line: '/usr/sbin/keepalived' '--dont-fork' '--log-console' '-p' '/home/service/keepalived.pid'
Keepalived[130]: Command line: '/usr/sbin/keepalived' '--dont-fork' '--log-console' '-p' '/home/service/keepalived.pid'
Mon Jun 12 22:31:00 2023:               '-r' '/home/service/vrrp.pid' '-f' '/etc/keepalived/keepalived.conf'
Keepalived[130]:               '-r' '/home/service/vrrp.pid' '-f' '/etc/keepalived/keepalived.conf'
Mon Jun 12 22:31:00 2023: Configuration file /etc/keepalived/keepalived.conf
Keepalived[130]: Configuration file /etc/keepalived/keepalived.conf
Mon Jun 12 22:31:00 2023: NOTICE: setting config option max_auto_priority should result in better keepalived performance
Keepalived[130]: NOTICE: setting config option max_auto_priority should result in better keepalived performance
Mon Jun 12 22:31:00 2023: Starting VRRP child process, pid=131
Keepalived[130]: Starting VRRP child process, pid=131
Mon Jun 12 22:31:00 2023: **Error 1 while registering gratuitous ARP shared channel**
Keepalived_vrrp[131]: **Error 1 while registering gratuitous ARP shared channel**
Mon Jun 12 22:31:00 2023: Stopped
Keepalived_vrrp[131]: Stopped
Mon Jun 12 22:31:00 2023: **pid 131 exited with permanent error missing permission. Terminating**
Keepalived[130]: pid 131 exited with permanent error missing permission. Terminating
Mon Jun 12 22:31:00 2023: Stopped Keepalived v2.2.7 (01/16,2022)
Keepalived[130]: Stopped Keepalived v2.2.7 (01/16,2022)

**Comment by qqliuxiaoran** [comment]
Hello,Can you tell me how you solved this problem. In my case, i run keepalived with non-root users
