### ISSUE TITLE
Does keepalived have an official docker image repository?

### ISSUE THREAD

**Issue by fantastic2085** [acassen/keepalived#2309]
_Support requests should be sent via_ https://groups.io/g/keepalived-users

**Describe why you are unable to send the support request to the above email list**
Understanding why you cannot use the email list should help us improve it.
**Does keepalived have an official docker image repository

Now that containers are becoming more and more popular, hopefully keepalived will have an official docker image repository, including x86 and arm docker image repositories**

**Describe what you need help/support for**
A clear and concise description of what you need help with.

**Details of what you would like to do with keepalived**
Describe in details what you would like to achieve with keepalived

**Keepalived version**
Output of `keepalived -v` (a later version of keepalived might be needed).

**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu]
 - Version [e.g. 29]
 - Architecture [e.g. x86_64]

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details 

**Configuration file:**
Full copy of your configuration file, obfuscated if necessary to protect passwords and IP addresses

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started, if applicable

**Additional context**

**Comment by pqarmitage** [comment]
No, we do not provide a docker image. It is not something that the maintainers of keepalived use, and therefore not something that we could maintain properly.

There appear to be various docker images on docker hub, with at least one of them having recent updates.
