### ISSUE TITLE
VRRP child process(488824) died: Respawning

### ISSUE THREAD

**Issue by hackernewbie91** [acassen/keepalived#2312]
hallo, I have problem on my keepalived running on 2 server, but on master server every few minute show keepalived state like bellow, and email notification that I have configured on both server send me allert look like vrrp instance is down. when I check keepalived status shown bellow :
pid 488824 exited due to signal 9 (Killed) - has rlimit_rttime been exceeded?
Jun 23 13:44:39 proxy1 Keepalived[488822]: VRRP child process(488824) died: Respawning

but keepalived still running. please any body can help me ?

**Comment by pqarmitage** [comment]
keepalived runs with a parent process, and child processes for handling VRRP, IPVS and BFD (the child processes are only run if there is relevant configuration for them). One of the purposes of the parent keepalived process is to monitor the child processes, and if one terminates for some reason, to restart it. This is why you get messages that a child process has died, but by the time you look at is running again.

The parent process is logging that the VRRP child process was sent signal 9 (SIGKILL), which is what caused the child process to terminate. The big question is what process sent SIGKILL to the VRRP process (it won't have been the keepalived parent process). You will need to investigate to see what is happening on you system and what process is sending the SIGKILL. If you are running with keepalived using realtime priority, it is possible that it has used too much CPU time (hence the message "has rlimit_rttime been exceeded"). Another possibility is that the OOM (out of memory) reaper has killed keepalived if there is insufficient memory available for processes). I would expect the system logs to have entries saying what is killing keepalived, but it depends on what is doing it and why.

**Comment by Ming0706** [comment]
I have encountered the same problem with you recently. Have you solved your problem?

**Comment by hackernewbie91** [comment]
No more. Solved

**Comment by Ming0706** [comment]
Unset the "vrrp_rt_priority" parameter? Do you know how to handle this issue if this parameter must? thank you.

**Comment by hackernewbie91** [comment]
Thats right. Correct

**Comment by Ming0706** [comment]
Have you ever thought about how to solve this problem if you have to set the "vrrp_rt_priority" parameter?

**Comment by Ming0706** [comment]
Okay, thank you.

**Comment by pqarmitage** [comment]
Under normal circumstances I wouldn't expect _vrrp_rt_priority_ to be a problem, unless you are running with very large VRRP configurations (I would be very interested to see a configuration where including _vrrp_rt_priority_ causes the VRRP keepalived process to be killed). Increasing _vrrp_rlimit_rttime_ to a sufficiently large value should stop the VRRP process being killed when using _vrrp_rt_priority_ (but you need to be careful not to make it too large in case keepalived starts using excessive CPU time, in which case it can lock out all other processes on a single core machine, or tie up one core of a multi-core machine completely, although this would be suggestive of a bug.
