### ISSUE TITLE
Keepalived_vrrp exited due to segmentation fault (SIGSEGV)

### ISSUE THREAD

**Issue by islipfd19** [acassen/keepalived#2313]
**Describe the bug**
Segmentation fault is produced

**To Reproduce**
Unable to force a reproducible condition. Start keepalive as expected and allow it to run.

**Expected behavior**
Keepalive is not expected to experience a segmentation fault

**Keepalived version**
Keepalived v2.2.2 (03/05,2021)

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.20
Running on Linux 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022
Distro: Raspbian GNU/Linux 10 (buster)

configure options: 

Config options:  LVS VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT INIT=systemd

System options:  VSYSLOG MEMFD_CREATE IPV4_DEVCONF LIBNL1 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK

**Distro (please complete the following information):**
 - Name: Raspbian GNU/Linux (Raspbian GNU/Linux 10 (buster))
 - Version: 10
 - Architecture: armv7l

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
########################
########################
vrrp_script chk_myscript {
#  script       "/usr/local/bin/mycheckscript.sh"
  script "/usr/local/bin/mycheckscript.sh"
  weight -15
  interval 15   # check every 2 seconds
  fall 8       # require 2 failures for KO
  rise 8       # require 2 successes for OK
  timeout 8    # was 3
}

# Identify the VRRP instance as, in this case, "failover_link".
vrrp_instance failover_link {
    track_script {
        chk_myscript
    }
    # Added Apr 13th, 2021. track interface itself. failover is pointless
    # if the rimary link goes down and keepalived isn't wathing it
    track_interface {
        eth0 weight -15
    }

    # Initial state of the keepalived VRRP instance on this host
    # (MASTER or BACKUP). Once started, only priority matters.
    state BACKUP

    # interface this VRRP instance is bound to.
    interface eth0

    # Arbitrary value between 1 and 255 to distinguish this VRRP
    # instance from others running on the same device. It must match
    # with other peering devices. 
    virtual_router_id 15

    # Highest priority value takes the MASTER role and the
    # virtual IP (default value is 100).
    priority 100

    # Time, in seconds, between VRRP advertisements. The default is 1,
    # but in some cases you can achieve more reliable results by
    # increasing this value.
    advert_int 4

    # Authentication method: AH indicates ipsec Authentication Header.
    # It offers more security than PASS, which transmits the
    # authentication password in plaintext. Some implementations
    # have complained of problems with AH, so it may be necessary
    # to use PASS to get keepalived's VRRP working.
    #
    # The auth_pass will only use the first 8 characters entered.
    authentication {
        auth_type AH
        auth_pass XXXXXXXX
    }

    # VRRP advertisements ordinarily go out over multicast. This 
    # configuration paramter causes keepalived to send them
    # as unicasts. This specification can be useful in environments
    # where multicast isn't supported or in instances where you want
    # to limit which devices see your VRRP announcements. The IP
    # address(es) can be IPv4 or IPv6, and indicate the real IP of
    # other members.
    unicast_peer {
        192.168.1.201
    }
    # Virtual IP address(es) that will be shared among VRRP
    # members. "Dev" indicates the interface the virtual IP will
    # be assigned to. And "label" allows for clearer description of the
    # virtual IP.
    virtual_ipaddress {
        192.168.1.202 dev eth0 label eth0:vip    
    }
# this is to re-add default gateway of wwan0 if that interface
# were to go down because it isn't auto added
#    notify /usr/local/bin/notify.sh MASTER
#{
        notify_master "/usr/local/bin/notify.sh MASTER"
        notify_backup "/usr/local/bin/notify.sh BACKUP"
        notify_fault "/usr/local/bin/notify.sh FAULT"
#        notify_backup "/var/vcap/jobs/keepalived/bin/action.sh BACKUP"
#        notify_fault  "/var/vcap/jobs/keepalived/bin/action.sh FAULT"
#    }
}

**Notify and track scripts**
***mycheckscript.sh:
#!/bin/bash -x
#if ping -c 1 8.8.8.8 &> /dev/null
IP=`nslookup one.one.one.one 8.8.8.8 | grep "Address:" | grep -m1 -v "#53" | awk -F" " '{print $2}'`
fping -I wwan0 -c1 -t300 "$IP" 2>/dev/null 1>/dev/null
#fping -I wwan0 -c1 -t300 one.one.one.one 2>/dev/null 1>/dev/null
if [ "$?" == 0 ]; then
  exit 0
else
  exit 1
fi

***notify.sh:
#!/bin/bash

TYPE=$1
NAME=$2
STATE=$3

WAN=`qmicli -d /dev/cdc-wdm0 -w`
WANIP=`ifconfig $WAN | grep inet | awk -F" " '{print $2}'`

case $TYPE in
        "MASTER") ip route add default via "$WANIP"
                  wget -O - http://freedns.afraid.org/dynamic/update.php?XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX >> /tmp/freedns_XXXXXXXXXXXXXXXXXXXXXXX 2>&1 &
                  wget -O - http://freedns.afraid.org/dynamic/update.php?XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX >> /tmp/freedns_XXXXXXXXXXXXXXXXXXXXXXXXXX 2>&1 &
                  echo "<html><head></head><body>master</body></html>" > /var/www/html/keepalived.html
        exit 0
        ;;
        "BACKUP") echo "<html><head></head><body>backup</body></html>" > /var/www/html/keepalived.html
        exit 0
        ;;
        "FAULT") echo "<html><head></head><body>fault</body></html>" > /var/www/html/keepalived.html
        exit 0
        ;;
        *) echo "unknown state"
            exit 1
        ;;
esac

**System Log entries**
Jun 27 05:07:16 ariel systemd[1]: Started Keepalive Daemon (LVS and VRRP).
Jun 27 05:07:16 ariel Keepalived[4958]: Starting Keepalived v2.0.10 (11/12,2018)
Jun 27 05:07:16 ariel Keepalived[4958]: Running on Linux 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 (built for Linux 4.18.20)
Jun 27 05:07:16 ariel Keepalived[4958]: Command line: '/usr/sbin/keepalived' '--dont-fork' '-D'
Jun 27 05:07:16 ariel Keepalived[4958]: Opening file '/etc/keepalived/keepalived.conf'.
Jun 27 05:07:16 ariel Keepalived[4958]: Starting VRRP child process, pid=4960
Jun 27 06:57:39 ariel Keepalived[4958]: Keepalived_vrrp exited due to segmentation fault (SIGSEGV).
Jun 27 06:57:39 ariel Keepalived[4958]:   Please report a bug at https://github.com/acassen/keepalived/issues
Jun 27 06:57:39 ariel Keepalived[4958]:   and include this log from when keepalived started, a description
Jun 27 06:57:39 ariel Keepalived[4958]:   of what happened before the crash, your configuration file and the details below.
Jun 27 06:57:39 ariel Keepalived[4958]:   Also provide the output of keepalived -v, what Linux distro and version
Jun 27 06:57:39 ariel Keepalived[4958]:   you are running on, and whether keepalived is being run in a container or VM.
Jun 27 06:57:39 ariel Keepalived[4958]:   A failure to provide all this information may mean the crash cannot be investigated.
Jun 27 06:57:39 ariel Keepalived[4958]:   If you are able to provide a stack backtrace with gdb that would really help.
Jun 27 06:57:39 ariel Keepalived[4958]:   Source version 2.0.10 
Jun 27 06:57:39 ariel Keepalived[4958]:   Built with kernel headers for Linux 4.18.20
Jun 27 06:57:39 ariel Keepalived[4958]:   Running on Linux 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022
Jun 27 06:57:39 ariel Keepalived[4958]:   Command line: '/usr/sbin/keepalived' '--dont-fork' '-D'
Jun 27 06:57:39 ariel Keepalived[4958]:   configure options: --build=arm-linux-gnueabihf --prefix=/usr --includedir=${prefix}/include
Jun 27 06:57:39 ariel Keepalived[4958]:                      --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc
Jun 27 06:57:39 ariel Keepalived[4958]:                      --localstatedir=/var --disable-silent-rules
Jun 27 06:57:39 ariel Keepalived[4958]:                      --libdir=${prefix}/lib/arm-linux-gnueabihf
Jun 27 06:57:39 ariel Keepalived[4958]:                      --libexecdir=${prefix}/lib/arm-linux-gnueabihf --runstatedir=/run
Jun 27 06:57:39 ariel Keepalived[4958]:                      --disable-maintainer-mode --disable-dependency-tracking --with-kernel-dir=debian/
Jun 27 06:57:39 ariel Keepalived[4958]:                      --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus
Jun 27 06:57:39 ariel Keepalived[4958]:                      --enable-dbus-create-instance --enable-json --enable-bfd
Jun 27 06:57:39 ariel Keepalived[4958]:                      build_alias=arm-linux-gnueabihf CFLAGS=-g -O2
Jun 27 06:57:39 ariel Keepalived[4958]:                      -fdebug-prefix-map=/build/keepalived-meS43e/keepalived-2.0.10=.
Jun 27 06:57:39 ariel Keepalived[4958]:                      -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro
Jun 27 06:57:39 ariel Keepalived[4958]:                      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2
Jun 27 06:57:39 ariel Keepalived[4958]:   Config options: LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING
Jun 27 06:57:39 ariel Keepalived[4958]:                   SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS DBUS_CREATE_INSTANCE
Jun 27 06:57:39 ariel Keepalived[4958]:   System options: PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF LIBNL3 RTA_ENCAP
Jun 27 06:57:39 ariel Keepalived[4958]:                   RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID
Jun 27 06:57:39 ariel Keepalived[4958]:                   RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE
Jun 27 06:57:39 ariel Keepalived[4958]:                   RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE
Jun 27 06:57:39 ariel Keepalived[4958]:                   FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS
Jun 27 06:57:39 ariel Keepalived[4958]:                   LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY
Jun 27 06:57:39 ariel Keepalived[4958]:                   IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH
Jun 27 06:57:39 ariel Keepalived[4958]:                   GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK
Jun 27 06:57:39 ariel Keepalived[4958]: VRRP child process(4960) died: Respawning
Jun 27 06:57:39 ariel Keepalived[4958]: Starting VRRP child process, pid=16088

**Did keepalived coredump?**
```
If so, can you please provide a stacktrace from the coredump, using gdb.
```

**Additional context**

**Comment by islipfd19** [comment]
Shortly after the segmentation fault occurs, keepalived causes CPU to hit 100% utilization

**Comment by pqarmitage** [comment]
@islipfd19 You state above that you are running keepalived v2.2.2, but the log entries show that you are running v2.0.10.

We have fixed a number of segfault issues in keepalived so I suggest that you upgrade keepalived to the current version (v2.2.8) and see if the segfault still occurs with that. If it does, then the only way we are likely to be able to fix it is symbolic stack backtrace is provided, so we can see where the fault is occurring.

If you still get the segfault after upgrading to keepalived v2.2.8 and can provide the stack backtrace, then we can reopen this isssue.
