### ISSUE TITLE
keepalived instances without explicit interface cannot be monitored via DBus

### ISSUE THREAD

**Issue by twogee** [acassen/keepalived#2337]
`vrrp_instance` configured without explicit `interface` creates DBus path `/org/keepalived/Vrrp1/Instance/none/<VRID>/IPv4` that cannot be queried via `org.keepalived.Vrrp1.Vrrp` interface (failing due to instance `none/<VRID>/IPv4` not found).

I'm using keepalived 2.2.4 on Ubuntu 22.04

**Comment by pqarmitage** [comment]
Commit 5dd228e resolves this issue. Commit b91a718 adds _global_def_s configuration option _dbus_no_interface_name_ which allows specifying a string to use instread of "none"; the purpose of this is in case a system has an interface named "none".
