### ISSUE TITLE
Template 'keepalived.conf' in the etc folder is somewhat misleading

### ISSUE THREAD

**Issue by gesture1968** [acassen/keepalived#2339]
The template keepalived.conf file has the 'vrrp_strict' option set by default, but also has the instance 'priority' set to 100. According to the documentation, when 'vrrp_strict' is used: _**'unless the vrrp_instance has priority 255, the system will not receive packets addressed to the VIPs/eVIPs, and the VIPs/eVIPs can only be used for routeing purposes'**_, implying that with this template, the virtual IP address cannot be used for 'normal' high availability purposes. So if the template is used as a starting point, the virtual IP is inaccessable, but this is not mentioned. It took hours to find out why the virtual IP was not reachable/pingable.  It might be more clear if either the template is changed with a default priority of 255, or at least give extra directions in the template on how to use the 'vrrp_strict' and 'priority' dependency

**Comment by pqarmitage** [comment]
Commit a7c4085 adds:
```
    # Allow packets addressed to the VIPs above to be received
    accept
```
to the sample configuration, which should help in future.

@gesture1968 Many thanks for reporting this.
