### ISSUE TITLE
Dedicated log file

### ISSUE THREAD

**Issue by tseegers** [acassen/keepalived#2354]
**Describe the bug**
A would like send keepalived logs to dedicated files, as the man page describes:
       -g, --log-file=FILE
              Write log entries to FILE. FILE will have _vrrp, _healthcheckers, and _bfd inserted before the last '.' in FILE for the log output for those processes.

**To Reproduce**
```
user@hostname~$ cat /etc/default/keepalived 
# Options to pass to keepalived
# DAEMON_ARGS are appended to the keepalived command-line
DAEMON_ARGS="--log-file=/app/log/keepalived/keepalived.log --enable-log-file"
user@hostname:~$ sudo systemctl restart keepalived.service 
user@hostname:~$ sudo journalctl -xeu keepalived.service
[...]
oct. 27 16:35:42 hostname keepalived[1888336]: -g requires configure option --enable-log-file
oct. 27 16:35:42 hostname keepalived[1888336]: Unknown option --enable-log-file
```
And the service fails to start.

**Expected behavior**
Starting the service with the dedicated log

**Keepalived version**
```
Keepalived v2.2.7 (01/16,2022)

```

**Distro (please complete the following information):**
 - Name: Debian 12
 - Version:6.1.0-12-amd64

**Configuration file:**
```
global_defs {
  enable_script_security
  max_auto_priority
}

vrrp_script repmgr_status {
  script "/etc/keepalived/repmgr_status.sh"
  interval 5
  fall 2
}

vrrp_instance vrrp_vip_pg15 {
   virtual_router_id 100
   state BACKUP
   priority 50
   advert_int 1
   interface ens18
   authentication {
                auth_type PASS
                auth_pass xxx
   }
   virtual_ipaddress {
       192.168.1.x/24 brd 192.168.1.255 scope global
   }
   track_script {
      repmgr_status
   }
}
user@hostname:~$ cat /etc/default/keepalived
# Options to pass to keepalived

# DAEMON_ARGS are appended to the keepalived command-line
DAEMON_ARGS="--log-file=/app/log/keepalived/keepalived.log --enable-log-file"
```

**System Log entries**
With option  --enable-log-file in /etc/default/keepalived
```
user@hostname:~$ sudo journalctl -xeu keepalived.service
oct. 27 17:02:28 hostname keepalived[1920063]: -g requires configure option --enable-log-file
oct. 27 17:02:28 hostname keepalived[1920063]: Unknown option --enable-log-file
oct. 27 17:02:28 hostname systemd[1]: keepalived.service: Main process exited, code=exited, status=1/FAILURE
```
Without option --enable-log-file:
```
user@hostname:~$ sudo journalctl -xeu keepalived.service
oct. 27 17:04:36 hostname keepalived[1920505]: -g requires configure option --enable-log-file
oct. 27 17:04:36 hostname systemd[1]: keepalived.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by pqarmitage** [comment]
When I implemented `-g requires configure option --enable-log-file` what I meant (and on reflection I should have been clearer but there was a clear distinction to me) was it was an option to the configure script. Adding `--enable-log-file` to /etc/default/keepalived` is adding a configurat**ion** option, whereas a configur**e** option is an option specified to the configure script which is run when keepliaved is being built.

If you run `keepalived --help` you will find with your build of keepalived that no `-g, --file=` option is listed. If you specify `--enable-log-file` as an option to configure and then build keepalived, then `keepalived --help` will show the `-g` option.

The reason for making `--enable-log-file` a configure/build time option is that most people won't use it, and so there is no point in having the overhead of the logging code in the executable.

I will have a think about how to make the message re `--enable-log-file` clearer, but you will need to build keepalived yourself to add that option if your distro does not include it.
