### ISSUE TITLE
VIPs are not cleaned up when the keepaived process is killed.

### ISSUE THREAD

**Issue by watanabebousquet** [acassen/keepalived#2361]
Hi,Team,
**I'm testing the MySQL router with keepalived, I have two nodes with keepalived daemon.
If I manualy kill keepalived daemon (kill -9 keepalived ) on master from
them, A vip(192.168.56.66) is bound to the backup,but But the VIP on the master is still not released.
Is this an expected behaviour? Looking forward to your help.**

TestCase：

`--- Master 
[root@s59 ~]# ps -ef | grep keepalived
root      3907     1  0 Dec06 ?        00:00:00 /usr/local/sbin/keepalived -D
root      3908  3907  0 Dec06 ?        00:00:02 /usr/local/sbin/keepalived -D
root     21170  3878  0 01:01 pts/2    00:00:00 grep --color=auto keepalived
[root@s59 ~]# 
[root@s59 ~]# kill -9 3908 3907 
[root@s59 ~]# ps -ef | grep keepalived
root     21201  3878  0 01:01 pts/2    00:00:00 grep --color=auto keepalived
[root@s59 ~]# 
[root@s59 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:c0:a5:d6 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic enp0s3
       valid_lft 78357sec preferred_lft 78357sec
    inet6 fe80::4019:6e50:14d3:baa6/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:f1:4e:3d brd ff:ff:ff:ff:ff:ff
    inet 192.168.56.59/24 brd 192.168.56.255 scope global noprefixroute enp0s8
       valid_lft forever preferred_lft forever
    inet 192.168.56.66/24 brd 192.168.56.255 scope global secondary enp0s8:1        <<<<<<<<<<<<<<<<<<<<
       valid_lft forever preferred_lft forever
    inet6 fe80::f0c2:279b:393b:ea48/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
[root@s59 ~]# 

---backup

[root@s65 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:e2:e5:a1 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic enp0s3
       valid_lft 78408sec preferred_lft 78408sec
    inet6 fe80::22b9:ef1a:dcc3:eb16/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:2c:9c:35 brd ff:ff:ff:ff:ff:ff
    inet 192.168.56.65/24 brd 192.168.56.255 scope global noprefixroute enp0s8
       valid_lft forever preferred_lft forever
    inet 192.168.56.66/24 brd 192.168.56.255 scope global secondary enp0s8:1             <<<<<<<<<<<<<<<<
       valid_lft forever preferred_lft forever
    inet6 fe80::fdc1:175a:32fc:d5b8/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever`

--version

[root@s59 ~]# keepalived -v
Keepalived v2.2.7 (01/16,2022)

Copyright(C) 2001-2022 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 5.4.17-2102.201.3.el7uek.x86_64 #2 SMP Fri Apr 23 09:05:55 PDT 2021
Distro: Oracle Linux Server 7.9

configure options: 

Config options:  LVS VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT INIT=systemd

System options:  VSYSLOG RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTA_VIA IFA_FLAGS NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE SO_MARK

**Comment by pqarmitage** [comment]
Yes, what you are observing is expected behaviour. If SIGKILL (signal 9) is sent to the keepalived process, the kernel immediately terminates the process, and so the process cannot remove the VIPs.

The correct way to terminate keepalived is to send SIGTERM to the **parent** keepalived process (in your example above PID 3907). This will cause keepalived to do an orderly shutdown during which it will remove the VIPs.

**Comment by stepcheunghk** [comment]
Hello sir @watanabebousquet , how's your MySQL Router x Keepalived test going? 

How does your healthcheck script look like? 
Are you checking the existence of MySQL router process?
