### ISSUE TITLE
Can keepalived control the appending order of IPv6 protocol stack IPs?

### ISSUE THREAD

**Issue by opencmit2** [acassen/keepalived#2366]
Can keepalived control the appending order of IPv6 protocol stack IPs?

**Comment by pqarmitage** [comment]
Unfortunately I do not understand what you are asking for; if you could provide an explanation, possibly with some examples, that might help.

You might find my comments in issue #2367 helpful.

**Comment by pqarmitage** [comment]
Closing due to no response for over 2 weeks.
