### ISSUE TITLE
How to implement two mutual exclusive VIPs

### ISSUE THREAD

**Issue by SimonLiuhd** [acassen/keepalived#2369]
There 2 machines (ServerA and ServerB), we want to have 2 VIPs, such as VIP1 and VIP2, 
1. When the VIP1 is on the ServerA, VIP2 MUST be on the ServerB
2. When the VIP1 is switched to ServerB, at the same time, VIP2 MUST be switched to ServerA
3. one checking PID to achieve the above

please help.
Thanks a lot.

Simon

**Comment by SimonLiuhd** [comment]
It is the similar with vrrp_sync_group that **one** track_script supports 2 binding VIPs that are always on one machine. 
While what we need is the **one** track_script supports 2 binding VIPs that are always on different machines.

**Comment by pqarmitage** [comment]
The following configuration outline may meet your needs. You haven't stated what you want to happen if one machine fails; with the configuration below the other machine will have both VIPs.

On machine A:
```
vrrp_vip1 {
    virtual_router_id 1
    priority 100
    virtual_ipaddress {
      VIP1
    }
   .
   .
   .
}

vrrp_vip2 {
    virtual_router_id 2
    priority 50
    virtual_ipaddress {
      VIP2
    }
   .
   .
   .
}
```

and on machine B:
```
vrrp_vip1 {
    virtual_router_id 1
    priority 50
    virtual_ipaddress {
      VIP1
    }
   .
   .
   .
}

vrrp_vip2 {
    virtual_router_id 2
    priority 100
    virtual_ipaddress {
      VIP2
    }
   .
   .
   .
}
```

If both machines are operating normally, machine A will have VIP1 and machine B will have VIP2. If either machine fails, then the other machine will have both VIPs; I am not clear if that is what you want.

**Comment by SimonLiuhd** [comment]
@pqarmitage
Thanks for your quick help.
If both machines are operating normally, it is what I need.

How can we get that there is no VIP2 on the machine A when the machine B fails?
Thanks again

**Comment by pqarmitage** [comment]
I think your solution is not to use VRRP at all but simply manually configure the relevant addresses on machine A and machine B.
