### ISSUE TITLE
 vip appears on both machines

### ISSUE THREAD

**Issue by yanyanguo** [acassen/keepalived#2370]
I encountered a split-brain problem with keepalived on two machines. I don’t know how to solve it besides changing to unicast mode. 
The keepalived version is: Keepalived v1.2.20.
The configuration is non-preemptive mode. 
The specific configuration is as follows: 

The first machine: 
! Configuration File for keepalived
global_defs {
   router_id configproxy1
   vrrp_skip_check_adv_addr
   vrrp_garp_interval 0
   vrrp_gna_interval 0
}
vrrp_script nginx_check {
  script "/tools/nginx_check.sh"
  interval 1
}
vrrp_instance VI_1 {
  state BACKUP
  interface ens192
  virtual_router_id 11
  nopreempt
  priority 100
  advert_int 1
  authentication {
    auth_type PASS
    auth_pass 1111
  }
  virtual_ipaddress {
    172.xxx.xxx.xxx   # ignore
  }
  track_script {
    nginx_check
  }

}

The second machine: 
! Configuration File for keepalived
global_defs {
   router_id configproxy2
   vrrp_skip_check_adv_addr
   vrrp_garp_interval 0
   vrrp_gna_interval 0
}
vrrp_script nginx_check {
  script "/tools/nginx_check.sh"
  interval 1
}
vrrp_instance VI_1 {
  state BACKUP
  interface ens192
  virtual_router_id 11
  nopreempt
  priority 50
  advert_int 1
  authentication {
    auth_type PASS
    auth_pass 1111
  }
  virtual_ipaddress {
    172.xxx.xxx.xxx   # ignore
  }
  track_script {
    nginx_check
  }

}

The phenomenon is that after the two machines start keepalived, the vip appears on both machines. tcpdump -i ens192 vrrp -n shows that regardless of whether the priority is high or low, they are sending requests to the public multicast address 224.0.0.18.

I don’t know how to solve it. I have checked the firewall and selinux. Is there a problem with my configuration? The upper layer switches of these two virtual machines are not the same, but I don’t know how to check the specific problem.

**Comment by pqarmitage** [comment]
What keepalived entries are shown in the system logs? That can indicate the cause of a proble,

The next thing to check is whether the systems are RECEIVING the adverts from the other systems. Using tcpdump or wireshark should show you that. It might be, for example, that the registration of 224.0.0.18 with IGMP is not working properly. Is IGMP properly configured on the upper layer switches?

Do using unicast work successfully?

keepalived version 1.2.20 is unbelievably old and you should upgrade to a current version, e.g. v2.2.8.

**Comment by pqarmitage** [comment]
Closing due to no response for nearly 2 months.
