### ISSUE TITLE
Keepalived VIP not getting original source IP of the request to VIP

### ISSUE THREAD

**Issue by gabbar023** [acassen/keepalived#2371]
Hi all, 

I'm trying to create a VIP in same segment of my subnet, to be used as LB ip. But when the request is forwarded to my VIP, the source ip is overriden by Host IP where VIP is attached to. This is my vrrp_instance config. 

How can i fix this to ensure the original source ip is being forwarded to VIP whenever request is made to VIP, not the host ip where the vip is attached.

vrrp_instance haproxy-vip {
  state MASTER                      # set BACKUP for others
  priority 100                      #set priority less than 100 for other
  interface ens160                       # Network card, check ifconfig 
  virtual_router_id 60                #same router id everywhere
  advert_int 1

  unicast_src_ip 10.197.12.26       # The IP address of this machine
  unicast_peer {
    10.197.12.25,10.197.12.24      # The IP address of peer machines
  }
   
  # The virtual ip address shared between the two loadbalancers
  virtual_ipaddress {
    10.197.12.27               # The VIP address for Master
      }

# Use the Defined Script to Check whether to initiate a fail over
  track_script {
    chk_haproxy
  }
}

**Comment by pqarmitage** [comment]
I am not sure I understand what you mean by `But when the request is forwarded to my VIP, the source ip is overriden by Host IP where VIP is attached to`.

However, your configuration does not look valid, and you should see some errors logged by keepalived.

If you change the unicast_peer block to be as follows, then it might work for you:
```
unicast_peer {     # The IP address of peer machines
    10.197.12.25
    10.197.12.24 
}
```

**Comment by pqarmitage** [comment]
The modification of the source IP of requests to 10.3.4.28 is not done by keepalived.

You appear to be using haproxy, and I presume this is where the source address change is occurring. For example see https://serverfault.com/questions/173391/lvs-vs-haproxy-which-should-i-choose which says point _I am using HAProxy for pure tcp servers and works very well. The source Ip hidden is a problem for all load balancer_, along with other similar comments.
