### ISSUE TITLE
After restart NIC, keepalived can not become master state

### ISSUE THREAD

**Issue by bobbyz3g** [acassen/keepalived#2378]
**Describe the bug**
I have two hosts. On one host, I stopped the network interface used by unicast_src using the `ifdown` command, and then started the network interface using `ifup`. At this time, keepalived re-enters the Backup state. Then, I manually stopped the keepalived service on the other host, and the current host cannot become the master.

**To Reproduce**
1. Login hostA, run `ifdown ifcfg-<src-nic>`
2. Run  `ifup ifcfg-<src-nic>` after ten seconds
3. Login hostB, run `systemctl stop keepalived`

**Expected behavior**
HostA becomes MASTER.

**Keepalived version**
```
Keepalived v2.2.8 (05/31,2023)

Copyright(C) 2001-2023 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.10.157
Running on Linux 5.10.157-1.el8.stack #1.el8.stack SMP Fri Jul 7 08:19:02 UTC 2023
Distro: CentOS Linux 8

configure options: --disable-dynamic-linking

Config options:  LVS VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT INIT=systemd

System options:  VSYSLOG MEMFD_CREATE IPV6_MULTICAST_ALL IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK
```

**Distro (please complete the following information):**
 - Name: [CentOS]
 - Version: [8]
 - Architecture: [x86_64]

**Configuration file:**
```
vrrp_instance VI {
  virtual_router_id 220
  state BACKUP
  priority 103
  nopreempt
  interface <src-nic>
  unicast_src_ip <src-ip>
  unicast_peer {
     <peer-ip>
  }
  advert_int 1
  authentication {
      auth_type PASS
      auth_pass **********
  }
  notify_master  "systemctl restart nginx"
}
```

**System Log entries**
```
2月 02 16:54:49 test09 Keepalived_vrrp[3162279]: Interface <src-nic>  added
2月 02 16:54:49 test09 Keepalived_vrrp[3162279]: (VI) interface <src-nic> is down
2月 02 16:54:49 test09 Keepalived_vrrp[3162279]: Netlink reports <src-nic> up
2月 02 16:54:49 test09 Keepalived_vrrp[3162279]: (VI) Entering BACKUP STATE
2月 02 16:54:49 test09 Keepalived_vrrp[3162279]: VI: sending gratuitous ARP for <src-ip>
2月 02 16:54:49 test09 Keepalived_vrrp[3162279]: Sending gratuitous ARP on <src-nic> for <src-ip>
```

**Did keepalived coredump?**

No

**Comment by pqarmitage** [comment]
After you restart the NIC can you please run tcpdump with filter "proto 112" (i.e. the VRRP protocol) on the system on which you restarted the NIC?

What happens if you do:
```
ip link set <src-nic> down
sleep 10
ip link set <src-nic> up
```
Does that work for you or not?

I don't experience a problem when doing the above, so it will be interesting to know what happens for you.

Also, after you have done the ifdown/ifup, can you ping the unicast-peer address from the master, and vice versa?

**Comment by bobbyz3g** [comment]
> After you restart the NIC can you please run tcpdump with filter "proto 112" (i.e. the VRRP protocol) on the system on which you restarted the NIC?

After I restart the NIC, tcpdump can capture the incoming "proto 112" package. But when I stop keepalived on another host, it will not send VRRP package, there is noting happend.

>  ```
> ip link set <src-nic> down
> sleep 10
> ip link set <src-nic> up
> ```
>  Does that work for you or not?

Yes, it works for me, host can become master.

> Also, after you have done the ifdown/ifup, can you ping the unicast-peer address from the master, and vice versa?

Yes, I can ping the unicast-peer address from the master, and vice versa.

**Comment by pqarmitage** [comment]
Are you using the NetworkManager ifup/down, or the network-scripts ifup (in other words is /usr/sbin/ipup a link to /usr/libexec/nm-ifup or to /etc/sysconfig/network-scripts/ifup?

If you are using the NetworkManager version, can you try executing
```
nmcli connection load /etc/sysconfig/network-scripts/ifcfg-<src-nic>
nmcli connection down filename /etc/sysconfig/network-scripts/ifcfg-<src-nic>
sleep 10
nmcli connection up filename /etc/sysconfig/network-scripts/ifcfg-<src-nic>
```
and see if keepalived works properly after that.

**Comment by pqarmitage** [comment]
Since you are using the NetworkManager versions of ifup/down, can you please try executing the following are advise what happens:
```
nmcli connection load /etc/sysconfig/network-scripts/ifcfg-<src-nic>
nmcli connection down filename /etc/sysconfig/network-scripts/ifcfg-<src-nic>
sleep 10
nmcli connection up filename /etc/sysconfig/network-scripts/ifcfg-<src-nic>
```

**Comment by bobbyz3g** [comment]
Apologizes for the inconvenience, but I'm unable to provide further testing information at this time due to the removal of the testing environment. I will be closing this issue.
