### ISSUE TITLE
1.2.19 "smtp_server" only works with IP address, not with host name

### ISSUE THREAD

**Issue by daku3649** [acassen/keepalived#239]
Sending email via the host specified with "smtp_server" does only work when giving an ip address. Giving a host name for "smtp_server" disables mail notfication.

For reason of flexibility, I would suggest to make smtp_server setting also accepting a host name.

**Comment by pqarmitage** [comment]
I have just tested using the latest version in git, and specifying a host name for "smtp_server" does work.

The documentation keepalived.SYNOPSIS and man page keepalived.conf(5) weren't as complete as they might have been. Pending commit c9cd61f resolves this.
