### ISSUE TITLE
Add documentation for notify script option

### ISSUE THREAD

**Issue by hashworks** [acassen/keepalived#2396]
Currently keepalived has a code for a `notify` configuration option in addition to `notify_master`, `notify_backup` and `notify_ stop`, which is called on any event:

https://github.com/acassen/keepalived/blob/v2.2.8/keepalived/vrrp/vrrp_parser.c#L366
```
static void
vrrp_gnotify_handler(const vector_t *strvec)
{
	if (current_vsyncg->script) {
		report_config_error(CONFIG_GENERAL_ERROR, "vrrp group %s: notify script already specified - ignoring %s", current_vsyncg->gname, strvec_slot(strvec,1));
		return;
	}
	current_vsyncg->script = set_vrrp_notify_script(strvec, 4);
	current_vsyncg->notify_exec = true;
}
```

However, the documentation and the samples don't mention it anywhere:
https://github.com/acassen/keepalived/blob/v2.2.8/doc/source/configuration_synopsis.rst

Is is deprecated? If so, that should be noted somewhere. If not, it should be documented.

**Comment by pqarmitage** [comment]
Unfortunately configuration_synopsis.rst is not currently maintained. The documentation for the keepalived configuration is maintained in doc/man/man5/keepalived.conf.5.in which is used to generate keepalived.conf.5 for installation in the man/man5 directory. The vrry_sync_group (and the vrrp_instance) notify scripts are documented in the man page.
