### ISSUE TITLE
Inconsistent spelling of Keepalived / keepalived

### ISSUE THREAD

**Issue by daku3649** [acassen/keepalived#240]
On http://keepalived.org/ it is mostly spelled "Keepalived" while on https://github.com/acassen/keepalived it is spelled "keepalived" on the main readme text and e.g. in the man page https://github.com/acassen/keepalived/blob/master/doc/man/man5/keepalived.conf.5

I would suggest to spell it consistently.

**Comment by acassen** [comment]
are you serious ?

**Comment by daku3649** [comment]
You do not care about a definition of spelling Your product?
