### ISSUE TITLE
TCP disconnection upon master switchover

### ISSUE THREAD

**Issue by EVMBugs** [acassen/keepalived#2414]
**Describe the bug**  
Despite using Keepalived with Conntrackd, the Master switchover leads to TCP disconnection.  
See the **to reproduce** (next) section for the setup and issues.  

**To Reproduce**  
Any steps necessary to reproduce the behaviour:
- Machine 1: HAProxy 1: 192.168.1.26 (VIP: 192.168.1.210)
- Machine 2: HAProxy 2: 192.168.1.27 (VIP: 192.168.1.210)
- Machine 3: Nginx 1: 192.168.1.28  
- Machine 4: Nginx 2: 192.168.1.29  
- Machine 5: Client: 192.168.1.213  

I found two scenarios with two different outcomes:    
1. When sending request with apache benchmark from the client (192.168.1.213) to the VIP (192.168.1.210), if I stop the `keepalived` service, then the TCP connection is left hanging.  From there two options (note that in both scenarios, the TCP connection is never switched over to the new Master instance): 
- *Scenarii 1.1:* If I restart the keepalived service prior to the 30sec, all requests left hanging are served once the initial master goes back online (e.g. connection did not have the time to timeout).  
- *Scenarii 1.2:* If I do not restart the service, after the delay set by the client (apache benchmark, ab, has a default of 30sec), then the timeout is reached `apr_pollset_poll: The timeout specified has expired (70007)`. The remaining node (initially backup, now master) never continues the TCP connection. Upon monitoring the traffic the only traffic I see is a `[FIN,ACK]` from the client and the node replying a `RST` after the timeout (30s here, so with a service shutdown at t=5s, I got it at t~=35s).  
<img width="1263" alt="1 1-fin-ack-rst" src="https://github.com/acassen/keepalived/assets/88000613/3b5f1693-cb0d-4b11-93c8-e5582500293f">

In both cases (1.1, 1.2), I do not understand why the TCP connection does not continue after the switchover.  

2. When blasting request with apache benchmark, if I shutdown the master host, the TCP connection immediately shuts down: `apr_socket_recv: Connection reset by peer (104)`. The client immediately receives a `[RST, ACK]`.  
![poff_immediate_rst](https://github.com/acassen/keepalived/assets/88000613/4cf2e2fb-daf1-44e7-a53f-ecc3c41be5f6)  

In all cases, I see nothing alarming in the logs, and the switchover seems to work. If I query the virtual IP address after shutting down the master host or the keepalived service on the master host, request are served successfully via the backup (now master) node. So, the switchover happens, just not at the TCP level. On the conntrackd end, if list connections with `sudo conntrackd -i`, I can see a lot of TCP connections replicated.  

I would have assumed there's something wrong my configuration, except that I have proof that these exact same configurations worked. I have one run where the switchover was successfully made, with no interruption of the TCP connection.  
Below, I highlight the exact request at which the takeover between HAP1 and HAP2 happened. Seems like right at the end of a communication (`[FIN, ACK]`). I guess it's perfect timing?  

![success-takeover](https://github.com/acassen/keepalived/assets/88000613/68a26a90-a965-4894-b164-523f8a51906e)  

**Expected behavior**  
TCP connection should not end or be left hanging, they should be served by the remaining node upon failover.  

**Keepalived version**  
```
Keepalived v2.2.8 (04/04,2023), git commit v2.2.7-154-g292b299e+
```

**Distro (please complete the following information):**  
 - Name: Ubuntu 
 - Version: 22.04.4 LTS
 - Architecture: x86_64

**Details of any containerisation or hosted service**  
Ran inside VMs, the hypervisor in use is XCP-NG.  

**Configuration file:**
`192.168.1.26 (MASTER)>keepalived.conf`  
```
global_defs {
    router_id 192.168.1.26
    vrrp_skip_check_adv_addr
    vrrp_garp_master_refresh 60
    vrrp_garp_master_refresh_repeat 2
    vrrp_garp_master_repeat 5
    vrrp_garp_interval 0.001
}

vrrp_sync_group VG1 {
   group {
      LB_EXT
   }
}

vrrp_instance LB_EXT {
    state MASTER
    interface eth0
    virtual_router_id 51

    unicast_src_ip 192.168.1.26

    unicast_peer {
        192.168.1.27
    }

    priority 101
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass passw123
    }
    virtual_ipaddress {
        192.168.1.210/24
    }
    notify_master "/etc/conntrackd/primary-backup.sh primary"
    notify_backup "/etc/conntrackd/primary-backup.sh backup"
    notify_fault  "/etc/conntrackd/primary-backup.sh fault"
    garp_master_delay 1
}
```

`primary-backup.sh`
```
#!/bin/sh
#
# (C) 2006-2011 by Pablo Neira Ayuso <pablo@netfilter.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Description:
#
# This is the script for primary-backup setups for keepalived
# (http://www.keepalived.org). You may adapt it to make it work with other
# high-availability managers.
#
# Do not forget to include the required modifications to your keepalived.conf
# file to invoke this script during keepalived's state transitions.
#
# Contributions to improve this script are welcome :).
#

CONNTRACKD_BIN=/usr/local/sbin/conntrackd
CONNTRACKD_LOCK=/var/lock/conntrack.lock
CONNTRACKD_CONFIG=/etc/conntrackd/conntrackd.conf

case "$1" in
  primary)
    #
    # commit the external cache into the kernel table
    #
    $CONNTRACKD_BIN -C $CONNTRACKD_CONFIG -c
    if [ $? -eq 1 ]
    then
        logger "ERROR: failed to invoke conntrackd -c"
    fi

    #
    # flush the internal and the external caches
    #
    $CONNTRACKD_BIN -C $CONNTRACKD_CONFIG -f
    if [ $? -eq 1 ]
    then
    	logger "ERROR: failed to invoke conntrackd -f"
    fi

    #
    # resynchronize my internal cache to the kernel table
    #
    $CONNTRACKD_BIN -C $CONNTRACKD_CONFIG -R
    if [ $? -eq 1 ]
    then
    	logger "ERROR: failed to invoke conntrackd -R"
    fi

    #
    # send a bulk update to backups
    #
    $CONNTRACKD_BIN -C $CONNTRACKD_CONFIG -B
    if [ $? -eq 1 ]
    then
        logger "ERROR: failed to invoke conntrackd -B"
    fi
    ;;
  backup)
    #
    # is conntrackd running? request some statistics to check it
    #
    $CONNTRACKD_BIN -C $CONNTRACKD_CONFIG -s
    if [ $? -eq 1 ]
    then
        #
	# something's wrong, do we have a lock file?
	#
    	if [ -f $CONNTRACKD_LOCK ]
	then
	    logger "WARNING: conntrackd was not cleanly stopped."
	    logger "If you suspect that it has crashed:"
	    logger "1) Enable coredumps"
	    logger "2) Try to reproduce the problem"
	    logger "3) Post the coredump to netfilter-devel@vger.kernel.org"
	    rm -f $CONNTRACKD_LOCK
	fi
	$CONNTRACKD_BIN -C $CONNTRACKD_CONFIG -d
	if [ $? -eq 1 ]
	then
	    logger "ERROR: cannot launch conntrackd"
	    exit 1
	fi
    fi
    #
    # shorten kernel conntrack timers to remove the zombie entries.
    #
    $CONNTRACKD_BIN -C $CONNTRACKD_CONFIG -t
    if [ $? -eq 1 ]
    then
    	logger "ERROR: failed to invoke conntrackd -t"
    fi

    #
    # request resynchronization with master firewall replica (if any)
    # Note: this does nothing in the alarm approach.
    #
    $CONNTRACKD_BIN -C $CONNTRACKD_CONFIG -n
    if [ $? -eq 1 ]
    then
    	logger "ERROR: failed to invoke conntrackd -n"
    fi
    ;;
  fault)
    #
    # shorten kernel conntrack timers to remove the zombie entries.
    #
    $CONNTRACKD_BIN -C $CONNTRACKD_CONFIG -t
    if [ $? -eq 1 ]
    then
    	logger "ERROR: failed to invoke conntrackd -t"
    fi
    ;;
  *)
    logger "ERROR: unknown state transition"
    echo "Usage: primary-backup.sh {primary|backup|fault}"
    exit 1
    ;;
esac

exit 0
````

`192.168.1.26 (MASTER)>conntrackd.conf`
```
Sync {
    Mode FTFW {
        DisableExternalCache off
	CommitTimeout 180
        PurgeTimeout 5
	StartupResync on
    }

    UDP {
        # Dedicated link for connection replication
        IPv4_address 10.10.1.1
        IPv4_Destination_Address 10.10.1.2
        Port 3780
        Interface ctd0
        SndSocketBuffer 1249280
        RcvSocketBuffer 1249280
        Checksum on
    }
}

General {
    Systemd on
    Nice -20
    HashSize 32768
    HashLimit 131072
    LogFile on
    Syslog on
    NetlinkOverrunResync 5
    NetlinkEventsReliable on
    PollSecs 5
    EventIterationLimit 200
    LockFile /var/lock/conntrack.lock
    UNIX {
        Path /var/run/conntrackd.ctl
        Backlog 20
    }
    NetlinkBufferSize 2097152
    NetlinkBufferSizeMaxGrowth 8388608
    Filter From Userspace {
        Protocol Accept {
            TCP
            UDP
            ICMP # This requires a Linux kernel >= 2.6.31
        }
        Address Ignore {
            IPv4_address 127.0.0.1 # loopback
            IPv4_address 10.10.1.1
            IPv4_address 192.168.1.26
        }
    }
}
```

`192.168.1.27 (BACKUP)>keepalived.conf`
```
global_defs {
    router_id 192.168.1.27
    vrrp_skip_check_adv_addr
    vrrp_garp_master_refresh 60
    vrrp_garp_master_refresh_repeat 2
    vrrp_garp_master_repeat 5
    vrrp_garp_interval 0.001
}

vrrp_sync_group VG1 {
   group {
      LB_EXT
   }
}

vrrp_instance LB_EXT {
    state BACKUP
    interface eth0
    virtual_router_id 51

    unicast_src_ip 192.168.1.27

    unicast_peer {
        192.168.1.26
    }

    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass passw123
    }
    virtual_ipaddress {
        192.168.1.210/24
    }
    notify_master "/etc/conntrackd/primary-backup.sh primary"
    notify_backup "/etc/conntrackd/primary-backup.sh backup"
    notify_fault "/etc/conntrackd/primary-backup.sh fault"
    nopreempt
    garp_master_delay 1
}
```

`192.168.1.27 (BACKUP)>conntrackd.conf`
```
Sync {
    Mode FTFW {
        DisableExternalCache off
	CommitTimeout 180
        PurgeTimeout 5
	StartupResync on
    }

    UDP {
        # Dedicated link for connection replication
        IPv4_address 10.10.1.2
        IPv4_Destination_Address 10.10.1.1
        Port 3780
        Interface ctd0
        SndSocketBuffer 1249280
        RcvSocketBuffer 1249280
        Checksum on
    }
}

General {
    Systemd on
    Nice -20
    HashSize 32768
    HashLimit 131072
    LogFile on
    Syslog on
    NetlinkOverrunResync 5
    NetlinkEventsReliable on
    PollSecs 5
    EventIterationLimit 200
    LockFile /var/lock/conntrack.lock
    UNIX {
        Path /var/run/conntrackd.ctl
        Backlog 20
    }
    NetlinkBufferSize 2097152
    NetlinkBufferSizeMaxGrowth 8388608
    Filter From Userspace {
        Protocol Accept {
            TCP
            UDP
            ICMP # This requires a Linux kernel >= 2.6.31
        }
        Address Ignore {
            IPv4_address 127.0.0.1 # loopback
            IPv4_address 10.10.1.2
            IPv4_address 192.168.1.27
        }
    }
}
```

**System Log entries**  
```
18:53:06 hap2 systemd[1]: Started LVS and VRRP High Availability monitor.
18:53:06 hap2 Keepalived[569299]: Starting Keepalived v2.2.8 (04/04,2023), git commit v2.2.7-154-g292b299e+
18:53:06 hap2 Keepalived[569299]: WARNING - keepalived was built for newer Linux 5.15.148, running on Linux 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024
18:53:06 hap2 Keepalived[569299]: Command line: '/usr/local/sbin/keepalived' '--dont-fork'
18:53:06 hap2 Keepalived[569299]: WARNING - using deprecated default config file '/etc/keepalived/keepalived.conf' - please move to 'NONE/etc/keepalived/keepalived.conf'
18:53:06 hap2 Keepalived[569299]: Configuration file /etc/keepalived/keepalived.conf
18:53:06 hap2 Keepalived[569299]: NOTICE: setting config option max_auto_priority should result in better keepalived performance
18:53:06 hap2 Keepalived[569299]: Starting VRRP child process, pid=569300
18:53:06 hap2 sudo[569295]: pam_unix(sudo:session): session closed for user root
18:53:06 hap2 Keepalived_vrrp[569300]: Script user 'keepalived_script' does not exist
18:53:06 hap2 Keepalived_vrrp[569300]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
18:53:06 hap2 Keepalived_vrrp[569300]: Sync group VG1 has only 1 virtual router(s) - this probably isn't what you want
18:53:06 hap2 Keepalived[569299]: Startup complete
18:53:06 hap2 Keepalived_vrrp[569300]: (LB_EXT) Entering BACKUP STATE (init)
18:53:06 hap2 conntrack-tools[568052]: flushing conntrack table in 5 secs
18:53:06 hap2 conntrack-tools[568052]: resync requested
18:53:11 hap2 conntrack-tools[568052]: flushing kernel conntrack table (scheduled)
18:54:28 hap2 sudo[569320]:       tf : TTY=pts/6 ; PWD=/home/tf ; USER=root ; COMMAND=/usr/bin/tcpdump -i any -w hap2output.pcap
18:54:28 hap2 sudo[569320]: pam_unix(sudo:session): session opened for user root(uid=0) by tf(uid=1000)
18:54:54 hap2 Keepalived_vrrp[569300]: (LB_EXT) Entering MASTER STATE
18:54:54 hap2 Keepalived_vrrp[569300]: VRRP_Group(VG1) Syncing instances to MASTER state
18:54:54 hap2 conntrack-tools[568052]: committing all external caches
18:54:54 hap2 conntrack-tools[568052]: Committed 3702 new entries
18:54:54 hap2 conntrack-tools[568052]: commit has taken 0.025379 seconds
18:54:54 hap2 conntrack-tools[568052]: flushing caches
18:54:54 hap2 conntrack-tools[568052]: resync with master conntrack table
18:54:54 hap2 conntrack-tools[568052]: sending bulk update
```

**Did keepalived coredump?**  
No.  

**Additional context**  
I don't think it's similar to #2254, but I could be wrong?

**Comment by pqarmitage** [comment]
@EVMBugs There doesn't appear to be anything wrong with your keepalived configs. I do note that you have modified the path to the conntrackd binary from /usr/sbin/conntrackd to /usr/local/sbin/conntrackd. When I install the conntrackd package on Ubuntu 22.04 the binary is installed to /usr/sbin.

From the logs you provide, when the VRRP instance transitions from backup to master keepalived does appear to be running the primary-backup.sh script, and that in turn appears to be executing conntrackd.

The Wireshark extracts you provide are interesting.
pkts 2515-6: It appears that neither end of the connection has sent any data (seq=1, ack=1).

pkts 439...: You refer to blasting request with apache benchmark. Only 81 bytes have been received on the server side.

pkts 370...: The connection between ports 80 and 49274 is shown shutting down from the client side, but there is no server side shutdown shown. The connection between ports 80 and 49280 is successfully set up, and the client sends data, but no server side response to that is shown.

You don't state on which system the Wireshark extracts were captured - was it on the client or on hap1 or 2?

I am confused about your reference to machines 3 and 4 (Nginx 1 and 2) since I can see nowhere where they are involved, and nowhere where their IP addresses are shown being used. Given what you have set out, I would expect to see some IPVS configuration so that packets sent to 192.168.1.210 are forwarded to 192.168.1.28 or 192.168.1.29.

You state that `conntrackd -i` shows a lot of TCP connections. What is important, however, is what is in the kernel conntrack tables, and for this you need to use the `conntrack` program rather than the `conntrackd` program.

I think, after hap2 has taken over as master, you need to capture packets on hap1 and hap2 to see what they are doing (you probably need to show the MAC addresses as well since 192.168.1.210 will have different MAC addresses depending whether it is on hap1 or hap2. You also need to look at the conntrack tables on hap2 to ensure that it has the relevant entries for the connections in progress.

**Comment by EVMBugs** [comment]
> I do note that you have modified the path to the conntrackd binary from /usr/sbin/conntrackd to /usr/local/sbin/conntrackd. When I install the conntrackd package on Ubuntu 22.04 the binary is installed to /usr/sbin.  

From my experiments, I've noticed that if you install conntrackd using aptitude on U22.04, the binary can be found in `/usr/sbin`. However, if you compile it from sources, it will be in `/usr/local/sbin/conntrackd` instead. Here, I compiled the binary from the sources.  


pkts 2515-6 is the scenario in which I stop the keepalived service, and let the connection timeout. The dump was captured on the client (192.168.1.213) that is sending the requests using apache benchmark.  

pkts 439...: This scenario is the one in which I shut down the master keepalived node (hap1, 192.168.1.26) and the connection breaks immediately upon shut down. This dump was also captured on the client (192.168.1.213). By blasting, I meant that I'm sending thousands of requests. 81 bytes seems to match with the expected TCP payload being sent to the server: `GET / HTTP/1.0 Host: 192.168.1.210 User-Agent: ApacheBench/2.3 Accept: */*`. 

pkts 370...: This scenario is the one in which I shut down the master keepalived node (hap1, 192.168.1.26) and the connection continued. This dump was also captured on the client (192.168.1.213). There is a server side response. I did not include it in the dump as I did not want to bury you with details. I added more detail with respect to that connection below 

![tcpconn_switch_success](https://github.com/acassen/keepalived/assets/88000613/74d3bfd2-a52e-4919-a3b1-69589458c33c)  


Machines 3 and 4 (Nginx 1 and 2) and two simple stupid web server that serve the default Nginx page. When a request comes in any of the two HAProxy (machine 1 and 2, aka HAProxy 1 and 2), the request is dispatched to either machine 3 or machine 4. Sorry if that was not clear. Ofc, I made sure the setup with the two haproxy and the two nginx was working prior to setting up keepalived+conntrackd.  
So any request from the client will flow in the following way: `192.168.1.213 --> 192.168.1.210 --> 192.168.1.26 (if hap1 is the master) --> 192.168.1.28 (assuming machine 1 (hap1) dispatched the request to machine 3 (nginx1))` 


My goal would be to have a setup whereby no connection is lost upon a node failure.  
As per your message, here are some more network-level details for each of the scenario.  

**Nominal Case (pkts 370...)** 
In this case, everything went well and the connection was switched seamlessly upon the failure of hap1 (simulated by a `sudo poweroff` without any notice). The goal is that this behavior should always happen.  

Here, we can clearly see the seamless switchover and the change in MAC address, showing that the setup worked once: 
*Before switchover, MAC address is HAP1 MAC address.*  
![clientside_before_switchover_hap1mac](https://github.com/acassen/keepalived/assets/88000613/0ded2353-a4cb-4b98-9577-4cad26e5ab37)  

*After switchover, MAC address is HAP2 MAC address.*
![clientside_after_switchover_hap2mac](https://github.com/acassen/keepalived/assets/88000613/cbcd60de-c509-426c-bb11-c3b2a704d1e6)

And on HAP2, here are the first requests being served upon switchover: 

![hap2_first_pkts_served_upon_switchover](https://github.com/acassen/keepalived/assets/88000613/06d898f8-a7dd-4d92-9315-20185e933b30)

**Error upon switchover: MASTER keepalived service stop; TCP connection left hanging till timeout (pkts 2515-6)**

Truthfully, I don't think I understand that dump. It was taken on HAP2. Upon HAP1 having its keepalived service shutdown we see a request coming in (req#2515). We can then see some conntrackd ICMP and UDP being exchanged, but I do not know if that's the expected behavior between keepalived+conntrack. You might be able to shed the light on this? 

![3](https://github.com/acassen/keepalived/assets/88000613/c73d7555-4579-4e34-9273-098bfd371557). 

**Error upon switchover: MASTER shutdown; TCP connection immediately breaks (pkts 439...)**
The connection immediately breaks, then we can see some keepalived and conntrackd messages being sent (only from 10.10.1.2 since 10.10.1.1 is down). Note that I filtered a few irrelevant SSH packets. This dump was taken on the client (192.168.1.213).  

![1](https://github.com/acassen/keepalived/assets/88000613/7ac5bc73-6ca6-4820-b1b4-4e29acdd0b82)

If we also take a look at what's happening on HAP2 (same experiment, HAP2 instead of Client view now), we can see the last packet coming from `10.10.1.1` prior to unannounced shutdown. The SYN, SYN-ACK, ACK between 192.168.1.27-192.168.1.28 and 192.168.1.27-192.168.1.29 are periodic checks coming from the HAProxy configuration.  

![2](https://github.com/acassen/keepalived/assets/88000613/de67acf9-7c7c-427b-ad7a-0b4db9f0c61a)

Note that keepalived still works in the sense that once the BACKUP becomes MASTER, I can send HTTP request to 192.168.1.210 and they will be served. My issue is that there's no seamless TCP connection switchover as seen in the nominal case.

**Comment by pqarmitage** [comment]
@EVMBugs You write `but I do not know if that's the expected behavior between keepalived+conntrack`. This is a misunderstanding; there is no connection between keepalived and conntrack (or conntrackd).

I have never used HAProxy, but I have done some looking into it. I don't think HAProxy supports what you want to achieve. My understanding is that HAProxy receives an incoming TCP connection, creates a corresponding connection to a backend server, and traffic arrives on one TCP connection, passes through HAProxy (which may modify the data) and then sends it out on the other TCP connection. In other words, there is one TCP connection between the client and, say, hap1, and a different TCP connection between hap1 and, say, Nginx1; incoming data on one connection is sent out on the other TCP connection. Now suppose hap1 fails. keepalived can transfer the IP address (192.168.1.210) from hap1 to hap2, and conntrackd can update the kernel connection tracking system, but there is no corresponding TCP connection between hap2 and nginx1, and so the connection from the client will be broken.

In your examples above, my understanding is that the apache benchmark you are running is creating very short duration TCP connections, i.e. TCP open, HTTP GET, HTTP response (1 packet), TCP close. Where you appear to have had successful test results it can only be because at the time of the failure/shutdown on hap1, there happened to be no open TCP connections at the time.

In order to achieve what I understand you are wanting to do, you need to use IPVS, or an equivalent. keepalived supports IPVS with its virtual server/real server configuration, and also has checkers to monitor the availability of the real servers (in your case the nginx systems). IPVS also supports load balancing.

HAProxy has additional functionality over using IPVS, but so far as I can see if you want to be able to survive the failure of one of your load balancing systems and keep TCP connections open, you cannot use it.
