### ISSUE TITLE
 Code analysis: deref after free in ipwrapper.c

### ISSUE THREAD

**Issue by Aruise** [acassen/keepalived#2421]
![изображение](https://github.com/acassen/keepalived/assets/47882486/082e43a6-242a-4bb1-bf09-d612a66e85b0)
At ipwrapper:1267 vsgname is called from structure vs, but vs was already freed at ipwrapper:1253, which can cause unexpected behavior 
![изображение](https://github.com/acassen/keepalived/assets/47882486/93c98a64-412d-451d-aae1-fb8bd97fbc7d)
free_vs function from check_data.c
![изображение](https://github.com/acassen/keepalived/assets/47882486/e6766e37-933e-417f-af9d-b9cb49089e88)
Which also leaves vs as a dangling pointer as vs was not assigned to NULL

**Comment by pqarmitage** [comment]
Line 1253 is in a loop:
```
    list_for_each_entry_safe(vs, vs_tmp, &check_data->vs, e_list) {
    }
```
There are also 3 other occurrences of `free_vs(vs)` in that loop at lines 1221, 1239 and 1245. vs is the loop variable and is not referenced again after `free_vs(vs)` is called within the loop until the next iteration of the loop, when vs has been assigned a new value.

In free_vs(), at line 629 `free_del_init(&vs->e_list)` removes the entry pointed to by vs from the list.

Line 1267 is in a new loop, `list_for_each_entry(vs, &check_data->vs, e_list) {`, and so the vs entry that was removed at line 1253 is no longer in the `check_data->vs` list, and so there is not deference after free.
