### ISSUE TITLE
I can not interrupt the gdb debugger by entering ctrl+c when it has attached a keepalived_vrrp process

### ISSUE THREAD

**Issue by smithAchang** [acassen/keepalived#2430]
**Describe the bug**
I can not interrupt the gdb debugger by entering ctrl+c when it has attached a keepalived_vrrp process

**To Reproduce**
1. compile keepalived 2.0.20 or 2.2.7/8 version and deploy it on CentOS7
2. start keepalived and make gdb attatching  the keepalived_vrrp process by `gdb att $vrrp_pid`
3. continue when gdb firstly promopts
4. enter `ctrl+c`
5. the debugged vrrp process exited normally

**Expected behavior**
When enter `ctrl+c`， I can interrupt the gdb but not make the vrrp process exited

**Keepalived version**
```
keepalived 2.0.20 or 2.2.7/8 version
```

**Distro (please complete the following information):**
 - Name: [CentOS7]
 - Version: [3.10.957]
 - Architecture: [x86_64]

**Details of any containerisation or hosted service (e.g. AWS)**
no

**Configuration file:**
a simplest Configuration file will be ok

**Notify and track scripts**
no any scripts

**System Log entries**
no helpful information

**Did keepalived coredump?**
no

**Additional context**
no

**Comment by pqarmitage** [comment]
When you type Ctrl-C, SIGINT is sent to the keepalived process. keepalived treats SIGINT the same as SIGTERM and terminates. For a description of why the signal is delivered to keepalived see [https://bugzilla.kernel.org/show_bug.cgi?id=9039#c8](https://bugzilla.kernel.org/show_bug.cgi?id=9039#c8) (keepalived uses signalfd).

If you change
`    signal_set(SIGINT, sigend_vrrp, NULL);`
to
`    signal_ignore(SIGINT);`
in vrrp_signal_init() in vrrp_daemon.c and rebuild keepalived, then keepalived should work as you want.

I have added commit 7e4c75f which adds a `--ignore-sigint` command line option. This enables keepalived to be sucessfully run under GDB.
