### ISSUE TITLE
ip address associated with VRID 1 not present in MASTER advert

### ISSUE THREAD

**Issue by subhajit-cdot** [acassen/keepalived#2444]
Hi,

I am getting the below print continuously from keepalived. The issue is that , there are two separate keepalived master backup instance running (2 + 2) in 2 different servers. One interface has same vrrp id 1 in both master-backup set running in 2 different servers.

In between switch may flood vrrp multicast message which is creating this issue. This is may be misconfiguration as this issue will get resolved if I change vrrp id of one instance to another number other than 1. But what other can be done to mitigate this issue or prints?

Jul 10 09:27:24 node Keepalived_vrrp[3352]: (ens3-1) ip address associated with VRID 1 not present in MASTER advert : 200.200.200.200
Jul 10 09:27:24 node Keepalived_vrrp[3352]: bogus VRRP packet received on ens3 !!!
Jul 10 09:27:24 node Keepalived_vrrp[3352]: VRRP_Instance(ens3-1) ignoring received advertisment...
Jul 10 09:27:25 node Keepalived_vrrp[3352]: (ens3-1): ip address associated with VRID 1 not present in MASTER advert : 200.200.200.200
Jul 10 09:27:25 node Keepalived_vrrp[3352]: bogus VRRP packet received on ens3 !!!
Jul 10 09:27:25 node Keepalived_vrrp[3352]: VRRP_Instance(ens3-1) ignoring received advertisment...
Jul 10 09:27:25 node Keepalived_vrrp[3352]: (ens3-1): ip address associated with VRID 1 not present in MASTER advert : **200.200.200.200**
Jul 10 09:27:25 node Keepalived_vrrp[3352]: bogus VRRP packet received on ens3 !!!
Jul 10 09:27:25 node Keepalived_vrrp[3352]: VRRP_Instance(ens3-1) ignoring received advertisment...

09:28:22.332074 52:54:00:48:8d:46 > 01:00:5e:00:00:12, ethertype IPv4 (0x0800), length 60: (tos 0xc0, ttl 255, id 30046, offset 0, flags [none], proto VRRP (112), length 40)
    **192.168.122.188** > 224.0.0.18: vrrp 192.168.122.188 > 224.0.0.18: VRRPv2, Advertisement, **vrid 1**, prio 100, authtype none, intvl 1s, length 20, addrs: **200.200.200.200**
	0x0000:  45c0 0028 755e 0000 ff70 29d0 c0a8 7abc
	0x0010:  e000 0012 2101 6401 0001 e96a c8c8 c8c8
	0x0020:  0000 0000 0000 0000 0000 0000 0000
09:28:22.332090 52:54:00:31:b9:7b > 01:00:5e:00:00:12, ethertype IPv4 (0x0800), length 60: (tos 0xc0, ttl 255, id 4238, offset 0, flags [none], proto VRRP (112), length 40)
    192.168.122.143 > 224.0.0.18: vrrp **192.168.122.143** > 224.0.0.18: VRRPv2, Advertisement, **vrid 1**, prio 100, authtype none, intvl 1s, length 20, addrs: **100.100.100.100**
	0x0000:  45c0 0028 108e 0000 ff70 8ecd c0a8 7a8f
	0x0010:  e000 0012 2101 6401 0001 b233 6464 6464
	0x0020:  0000 0000 0000 0000 0000 0000 0000

Thanks
Subhajit

**Comment by pqarmitage** [comment]
It appears that 192.168.122.188 is sending an advert with virtual_router_id 1 with one virtual_ipaddress 200.200.200.200, and 192.168.122.143 is sending an advert with the same virtual router id (1) but with a different virtual_ipaddress (100.100.100.100). keepalived on 192.168.122.143 is quite rightly complaining that it is receiving an advert which does not contain the correct IP address(es).

I don't really understand your setup, but different virtual routers (i.e. protecting different addresses) must have different virtual_router_ids (VRID), since it is the VRIDs that identify the different virtual routers.
