### ISSUE TITLE
When the check child process and VRRP child process are abnormally terminated and restarted by the parent process, they might not have a PID file.

### ISSUE THREAD

**Issue by swimlessbird** [acassen/keepalived#2460]
**Describe the bug**
After [commit 2c4cd3b](https://github.com/acassen/keepalived/commit/2c4cd3b927e5f12f59c62481261621b70375a304),when the check child process and VRRP child process are abnormally terminated and restarted by the parent process, they may not have a PID file.

**To Reproduce**

1. Start keepalived
2. kill -15 check child process or VRRP child process

Their PID files are missing.

**Expected behavior**
Their PID files are still present.

**Keepalived version**
```
Keepalived v2.2.4 (08/21,2021)

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.10.0
Running on Linux 5.10.0-60.18.0.50.h815.eulerosv2r11.x86_64 #1 SMP Tue Mar 28 09:30:42 UTC 2023
Distro: EulerOS 2.0 (SP11x86_64)

configure options: --build=x86_64-openEuler-linux-gnu --host=x86_64-openEuler-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-sha1 --with-init=systemd --enable-snmp --enable-snmp-rfc build_alias=x86_64-openEuler-linux-gnu host_alias=x86_64-openEuler-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/generic-hardened-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection  LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/generic-hardened-ld

Config options:  LIBIPSET_DYNAMIC NFTABLES LVS VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 INIT=systemd SYSTEMD_NOTIFY

System options:  VSYSLOG MEMFD_CREATE IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA IPTABLES NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK
```
and   [commit 2c4cd3b](https://github.com/acassen/keepalived/commit/2c4cd3b927e5f12f59c62481261621b70375a304)

**Distro (please complete the following information):**
 - Name: [e.g. Fedora, Ubuntu]
 - Version: [e.g. 29]
 - Architecture: [e.g. x86_64]

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
```
A full copy of the configuration file, obfuscated if necessary to protect passwords and IP addresses
```

**Notify and track scripts**

NA

**System Log entries**
NA

**Did keepalived coredump?**
No

**Additional context**
![image](https://github.com/user-attachments/assets/5485cfac-2461-480e-a288-75126b9e89be)

**Comment by pqarmitage** [comment]
Many thanks for reporting this. I have discovered that is actually worse than just the problem above. If the child process is killed with a signal that doesn't make the process exit cleanly (e.g. SIGKILL, SIGSEGV), then the new pid is appended to the original pid file, so the pidfile then has two (or more) lines, and it is the last line that is the current pid.

Commit 7cb09b2 should resolve this issue.
