### ISSUE TITLE
Keepalived + HAproxy FTP with session persistant

### ISSUE THREAD

**Issue by Azgar1998** [acassen/keepalived#2473]
Hello,
I set up a keppalived load balancer with haproxy with a virtual IP. In my backend, I currently only have an FTP server. However, I have two front-end servers with a virtual IP address. My problem is that when I'm copying and I run my loadbalancer on the client, it tells me "the session is over" and therefore cancels the current copy.
I have read topics regarding sticky tables and their synchronization between load-balancer but it does not seem to work on the HAproxy side. Regarding Keepalived, I have this possibility but it requires the use of nat on the server, but that is not what I want.

Do you have any idea why this isn't working without interruption?

Thank you for your help

**To Reproduce**
1 - connection to the FTP client via virtual IP
2 - start a copy
3 - switch the load balancer to the second (disable the haproxy service. keepelived switches if the haproxy service is disabled)

**Keepalived version**
```
Keepalived v2.2.8
```

**Distro (please complete the following information):**
 - Name: Ubuntu
 - Version: 24.04 LTS
 - Architecture: X64

**Configuration file:**

master:
```
global_defs {
  # Keepalived process identifier
  router_id haproxy
  enable_script_security
  lvs_sync_daemon ens192 VI_02 id 1

}

# Script to check whether haproxy is running or not
vrrp_script chk_haproxy {
  script "/bin/check_haproxy.sh"
  interval 1
  weight 50
}

# Virtual interface - The priority specifies the order in which the assigned interface to take over in a failover
vrrp_instance VI_02 {
  state MASTER
  interface ens160
  virtual_router_id 192
  priority 110
  # Check inter-load balancer toutes les 1 secondes
  advert_int 1
  # The virtual ip address shared between the two IIS Server which will float
  virtual_ipaddress {
    Virtual_ip/mask
  }
  track_script {
    chk_haproxy
  }
  authentication {
    auth_type PASS
    auth_pass secret
  }
}
```
slave:
```
global_defs {
  # Keepalived process identifier
  router_id haproxy
  enable_script_security
  lvs_sync_daemon ens192 VI_02 id 2

}

# Script to check whether haproxy is running or not
vrrp_script chk_haproxy {
  script "/bin/check_haproxy.sh"
  interval 1
  weight 50
}

# Virtual interface - The priority specifies the order in which the assigned interface to take over in a failover
vrrp_instance VI_02 {
  state BACKUP
  interface ens160
  virtual_router_id 192
  priority 100
  # Check inter-load balancer toutes les 1 secondes
  advert_int 1
  # The virtual ip address shared between the two IIS Server which will float
  virtual_ipaddress {
    Virtual_ip/mask
  }
  track_script {
    chk_haproxy
  }
  authentication {
    auth_type PASS
    auth_pass secret
  }
}
```

**Comment by pqarmitage** [comment]
You have specified `id 1` on your master system and `id 2` on your slave system. This means that the backup lvs_sync_daemon will filter out all the multicast messages, and so the "slave" system will not have the state of any of the existing connections on the "master" system.

See the ipvsadm man page:
       **--syncid syncid**
              Specify  the  syncid that the sync master daemon fills in the SyncID header while sending multicast messages, or the sync backup daemon uses to filter out multi‐
              cast messages not matched with the SyncID value. The valid values of syncid are 0 through to 255. The default is 0, which means no filtering at all.

**Comment by Azgar1998** [comment]
Hello,

Thank you for your response. based on what you tell me, I need to specify a common value in the syncid? for example 1. Or do not specify and the system will manage it automatically?

I also read that lvs_sync_daemon worked in the case of virtual servers but not with Haproxy. can you confirm this for me?

Because when I look at the status of the current sessions I don't see any session when I enter
ipvsadm -lc (mate and slave)

For information, communication on the ENS192 interface has been tested between the two servers

**Comment by pqarmitage** [comment]
> Thank you for your response. based on what you tell me, I need to specify a common value in the syncid? for example 1. Or do not specify and the system will manage it automatically?

Correct
> I also read that lvs_sync_daemon worked in the case of virtual servers but not with Haproxy. can you confirm this for me?

Correct. lvs_sync_daemon is for synchronizing the connection status of real servers, so is not applicable to haproxy.
