### ISSUE TITLE
Docs have a typo for "lvs_sync_daemon_interface" setting

### ISSUE THREAD

**Issue by roadSurfer** [acassen/keepalived#2489]
The documentation has a minor discrepancy on the `lvs_sync_daemon_interface`, in for part it used `lvs_sync_daemon_inteface` and this is confusing to new users like myself.

**To Reproduce**
Read the [documentation](https://github.com/acassen/keepalived/blob/master/doc/source/configuration_synopsis.rst#vrrp-instance-definitions-synopsis) and observe that it uses `lvs_sync_daemon_inteface` under the "VRRP Instance Definitions Synopsis" section

**Expected behavior**
The docs to be accurate

**Keepalived version**
N/A - Source documentation in GitHub

**Comment by roadSurfer** [comment]
I have just spotted in the code that `lvs_sync_daemon_interface` is actually deprecated and the documentation makes no mention of this fact.

**Comment by pqarmitage** [comment]
Commits cf6bbed and 6b19ac3 update the source of the web page. The web page will be updated the next time updates are pushed to it.

Unfortunately the web page is very out of date at the moment; the best reference is the keepalived.conf(5) man page. I will try and work out a way of updating the web site without us having to update two lots  of documentation every time there is an update.
