### ISSUE TITLE
when using HTTP_GET, --dump-conf prints invalid connect_ip value.

### ISSUE THREAD

**Issue by fraff** [acassen/keepalived#250]
Hi,

When using a virtual servers with multiple real servers and HTTP_GET check, --dump-conf prints every connect_ip with the value of the last one.

How to reproduce:
git clone https://github.com/acassen/keepalived.git
cd keepalived
./configure
make
./bin/keepalived --use-file=$PWD/doc/samples/keepalived.conf.virtual_server_group --log-console --log-detail --dont-fork --check --dump-conf

It prints:
 [192.168.200.1]:1358
...
   Connection dest = [192.168.200.2]:1358    <- invalid value here
...
 [192.168.200.2]:1358
...
   Connection dest = [192.168.200.2]:1358    <- the last one is correct.
...
Activating healthchecker for service [192.168.200.1]:1358   <- but this is correct
Activating healthchecker for service [192.168.200.2]:1358   <- this is also correct
...

Anyway, this is just cosmetic because everything works as expected.

Thanks.

**Comment by andriyanov** [comment]
Acknowledge, I'll fix this.

**Comment by andriyanov** [comment]
The fix is in repository, the issue can be closed.
