### ISSUE TITLE
Does Keepalived support cross-subnet functionality, and how can it be configured to do so?

### ISSUE THREAD

**Issue by hengqiali** [acassen/keepalived#2505]
Consider a setup with two LVS machines designated as master LVS and backup LVS, both of which use Keepalived to implement high availability (HA). The master LVS resides in the subnet 10.1.1.0/24, while the backup LVS is located in the subnet 10.1.2.0/24. To achieve HA, Keepalived employs vrrp protocols unicast (unicast_peer )to enable VRRP instance switching between master and backup and to share the same VIP (floating IP). However, I have the following questions:
- How should I select the VIP for Keepalived, and how will clients determine the appropriate route when accessing this VIP?
- Assuming the VIP is set as 10.1.1.2, if a crash arises with the master and then the VIP floats to the backup server in the 10.1.2.0/24 subnet, will traffic still be accessible to VIP and backup las as expected? If not, what steps are required to ensure normal access?

**Comment by pqarmitage** [comment]
keepalived can manage the VIPs, but you will have to configure your network to handle the appropriate routeing. I cannot see how what you want to do is achievable.

There might be a way if you change the VIP to a new subnet, say 10.1.255.0/24, and let's say the VIP is 10.1.255.1. You don't have any other address in the 10.1.255.0/24 subnet configured anywhere. If you run a dynamic routeing protocol, such as OSPF, then when the VIP is added, OSPF should be able to update its neighbouring routers with the new route to 10.1.255.0/24.
