### ISSUE TITLE
keepalived -"bogus VRRP Packet received"

### ISSUE THREAD

**Issue by jgerry2002** [acassen/keepalived#255]
We’ve been experiencing odd VRRP problems on our nginx load balancers.

Sometimes, following a reboot the other node in the cluster is flooded with these:

Feb 23 11:12:32 nginx-lb-001 Keepalived_vrrp[3533]: VRRP_Instance(INSIDE_1) ignoring received advertisment...
Feb 23 11:12:33 nginx-lb-001 Keepalived_vrrp[3533]: bogus VRRP packet received on em2 !!!
Feb 23 11:12:33 nginx-lb-001 Keepalived_vrrp[3533]: VRRP_Instance(INSIDE_1) ignoring received advertisment...
Feb 23 11:12:34 nginx-lb-001 Keepalived_vrrp[3533]: bogus VRRP packet received on em2 !!!
Feb 23 11:12:34 nginx-lb-001 Keepalived_vrrp[3533]: VRRP_Instance(INSIDE_1) ignoring received advertisment...
Feb 23 11:12:35 nginx-lb-001 Keepalived_vrrp[3533]: bogus VRRP packet received on em2 !!!
Feb 23 11:12:35 nginx-lb-001 Keepalived_vrrp[3533]: VRRP_Instance(INSIDE_1) ignoring received advertisment...
Feb 23 11:12:36 nginx-lb-001 Keepalived_vrrp[3533]: bogus VRRP packet received on em2 !!!
Feb 23 11:12:36 nginx-lb-001 Keepalived_vrrp[3533]: VRRP_Instance(INSIDE_1) ignoring received advertisment...

Which can cause an inadvertent failover as I think the cluster is unable to determine who is master.

If I leave the node alone for some time, and restart keepalived later. I am able to successfully start it without any problems. Failovers work properly.

This almost appears to be some sort of bug related to how it is advertising its ip information.

I’ve noticed the version of keepalived that is in the nginx-ha-keepalived package is 2.15, which is a few behind the current release.

Here is a copy of our keepalived config:

global_defs {
  notification_email {
    <emails>
  }
  <email config removed>
  router_id nginx-lb-001
}

vrrp_script chk_nginx_service {
  script "/usr/lib/keepalived/nginx-ha-check"
  interval 3
  weight 50
}

vrrp_script forced_failover {
  script "/usr/lib/keepalived/forced_failover"
  interval 10
  weight 50
}

vrrp_script check_gateway {
  script "/usr/lib/keepalived/check_gateway"
  interval 10
  weight 50
}

vrrp_instance INSIDE_1 {
  interface em2
  state BACKUP
  priority 100
  virtual_router_id 51
  advert_int 1
  unicast_src_ip 192.168.0.1

  track_interface {
    em2
    p1p2.30
    p1p1.6
  }

  unicast_peer {
    192.168.0.2
  }
  authentication {
    auth_type PASS
    auth_pass <removed>
  }
  virtual_ipaddress {
    10.160.0.10/32 dev em1
    10.160.2.88/32 dev p1p1.6
    outside ip's removed dev p1p2.30
    outside ip's removed dev p1p2.30
	outside ip's removed dev p1p2.30
	outside ip's removed dev p1p2.30
	outside ip's removed dev p1p2.30
	outside ip's removed dev p1p2.30
	outside ip's removed dev p1p2.30
	outside ip's removed dev p1p2.30
	outside ip's removed dev p1p2.30
	outside ip's removed dev p1p2.30
	outside ip's removed dev p1p2.30
  }
  virtual_ipaddress_excluded {
    <outside ip's removed> dev p1p2.30
  }
  track_script {
    chk_nginx_service
    forced_failover
    check_gateway
  }
  notify "/usr/lib/keepalived/nginx-ha-notify"
  notify "/usr/lib/keepalived/notify_html"
  smtp_alert
}

And our interfaces configuration file from one nginx box.

auto lo
iface lo inet loopback

auto p1p1
iface p1p1 inet manual
mtu 9000

auto p1p2
iface p1p2 inet manual

auto p1p1.6
iface p1p1.6 inet static
        address 10.160.2.9
        netmask 255.255.254.0
        vlan-raw-device p1p1
        post-up /sbin/ip link set p1p1 txqueuelen 2000
        post-up /sbin/ip link set p1p1.6 txqueuelen 2000
        mtu 9000

auto p1p2.30
iface p1p2.30 inet static
        address <outside ip>
        netmask 255.255.255.0
        gateway <outside gateway>
        vlan-raw-device p1p2
        post-up /sbin/ip link set p1p2 txqueuelen 2000
        post-up /sbin/ip link set p1p2.30 txqueuelen 2000
        
auto em1
iface em1 inet static
        address         10.160.0.6
        dns-nameservers 10.160.4.25 10.160.4.26 10.160.4.25
        dns-search      <removed>
        netmask         255.255.255.0
        mtu            1500
        up ip route add 10.0.0.0/8 via 10.160.0.1 || true

auto em2
iface em2 inet static
  address       192.168.0.1
  netmask       255.255.255.0

**Comment by pqarmitage** [comment]
You appear to be running NGINX plus, and so you really need to use NGINX support to resolve this issue.

If NGINX have not modified the keepalived source code from version 1.2.15, then it would appear from the v1.2.15 source code here that the only reason that a "bogus VRRP packet" can be reported without a previous error message relating to what is wrong with the packet is if that address family configured for the (INSIDE_1) instance is neither AF_INET nor AF_INET6, and that would appear to be an error in the configuration parsing, or configuration information being overwritten, but how this is happening isn't immediately obvious. That restarting keepalived resolves the problem for you suggests this is an intermittent problem.

If you are able to build and run the latest version from this git repository and the problem still exists, then I could investigate further.
