### ISSUE TITLE
Only first url is check in HTTP_GET

### ISSUE THREAD

**Issue by fraff** [acassen/keepalived#258]
Hi,

When using multiple URLs sections in HTTP_GET, only the first one get checked, in some conditions, others might be checked to.

This behavior has been described here: http://permalink.gmane.org/gmane.linux.keepalived.devel/4372

How to reproduce:

\# cat << EOF > /tmp/keepalived.conf
global_defs {
   router_id LVS_DEVEL
}

virtual_server 192.168.200.100 800 {
    delay_loop 6
    lb_algo rr
    lb_kind NAT
    protocol TCP

    real_server 127.0.0.1 800 {
        weight 1
        HTTP_GET {
            url {
              path /
              status_code 200
            }
            url {
              path /mrtg/
              status_code 200
            }
            connect_timeout 3
            nb_get_retry 3
            delay_before_retry 3
        }
    }
}
EOF

\# echo -n 200 > /tmp/status
\# while true ; do echo -e "HTTP/1.1 $(cat /tmp/status) OK\r\n$(date)\r\n\r\nHello World!" | nc -q 1 -l -p 800; sleep 1; done
\# ./bin/keepalived --log-console --log-detail --dont-fork --check --dump-conf -f /tmp/keepalived.conf
\# echo -n 404 > /tmp/status
wait until quorum is lost
\# echo -n 200 > /tmp/status

And watch the netcat's loop to see what URLs are checked.

Regards,

**Comment by pqarmitage** [comment]
An HTTP_GET section only supports one url statement (yes, ideally an error message should be produced if more than one url is specified).

If you alter the real_server block as follows, it should work as you want.
real_server 127.0.0.1 800 {
    weight 1
    HTTP_GET {
        url {
          path /
          status_code 200
        }
        connect_timeout 3
        nb_get_retry 3
        delay_before_retry 3
    }
    HTTP_GET {
        url {
          path /mrtg/
          status_code 200
        }
        connect_timeout 3
        nb_get_retry 3
        delay_before_retry 3
    }
}
