### ISSUE TITLE
Which version to use with Ubuntu LTS?

### ISSUE THREAD

**Issue by tluzon** [acassen/keepalived#287]
Ubuntu 14.04 LTS repository holds v1.2.7 which is a very old build of keepalived.
Trying to install the v1.2.19 .deb package of keepalived fails due to dependencies version mismatch.
Building the binaries from sources is successful but I'm afraid it leans on old library versions which are not the ones this version was build for.

What is the recommended version and action plan in case of Ubuntu LTS?

Thanks,
Tal.

**Comment by acassen** [comment]
last one is the best. 1.2.20

regs,
