### ISSUE TITLE
"preempt_delay " set, but doesn't  work ？？

### ISSUE THREAD

**Issue by TigererFeng** [acassen/keepalived#296]
Maybe ms_down_timer expire,the device (it's fault state) transition to master state ,but “preempt_delay 60“ configuration doesn't work ,Does Keepalived1.2.19 support preemption delay function ??

**Comment by wtaps** [comment]
Same question.

**Comment by wtaps** [comment]
You can see the changelog, i think Keepalived 1.2.19 was supported.

**Comment by TigererFeng** [comment]
it not support !!
   I think it's necessary to wait some secends to transition to backup state (the initial state in configure file) from fault state (when network dropped); 
    Because it's not steady when network resume  ** result in**  that  vrrp stance being backup state can not receive vrrp packet from master device , so it send Gratuitous ARP to gatway , then it (Device A)received the vrrp packet that higher prio advert from master device (Device B), so  transition to backup state , But** gatway keep the Mac address of Device A **other than the Mac address of master Device B !!!!!

**Comment by Cugar15** [comment]
I'm also having difficulties to get 'preemt_delay' or 'nopreempt' to work (latest revision).
Neither setting shows any effect.

**Comment by jonasj76** [comment]
Maybe this commit fixes the problem: fdd37e4.
https://github.com/jonasj76/keepalived/tree/respect-preempt-from-fault

**Comment by pqarmitage** [comment]
I think I can see where the problem is (in vrrp_state_backup(), but I need to think this through a bit further to double check I have got this right. I'm busy until after 18:00 GMT, but I'll investigate it further then.
