### ISSUE TITLE
How to test a service that is only bound to a virtual ip?

### ISSUE THREAD

**Issue by dekimsey** [acassen/keepalived#306]
I am using LVS in a direct routing setup. One director, two real servers. I have a number of services that are listening only on their respective virtual ips. I've found that the CHECKS send traffic to the real server's maintenance ip. What is the recommended way to set this up so that the test are correctly forwarded to the virtual ips on the boxes?

Additionally, is there a way to test this from outside the cluster, such as our monitoring software?

I couldn't find any clear documentation mentioning the limitation. But it comes into play with httpd virtual servers if they cannot bind to *.

**Comment by andriyanov** [comment]
I use TUN ipvs transport to achieve the same packet flow for probes and real traffic.
I set up checks specifying both
connect_ip = service virtual ip
fwmark = integer corresponding to a real server

Then I use https://github.com/andriyanov/check-tun daemon program to direct the probe packets destined to virtual IP to specific real server according to fwmark set on packet.
