### ISSUE TITLE
keepalived -f <filename> not support relative path

### ISSUE THREAD

**Issue by MerkerXu** [acassen/keepalived#308]
I run the following command to start keepalived
`keepalived -f etc/keepalived/keepalived.conf`
only found that the configuration file did not work!

Finally, someone tell me the -f option does not work with a relative path
Will the next release add a warning message or something?

Thanks.

**Comment by MerkerXu** [comment]
same issue as https://github.com/acassen/keepalived/issues/304
closed

**Comment by pqarmitage** [comment]
If keepalived runs as a daemon (which is the default), it does `chdir("/")` prior to reading the config file(s), and so any path names are relative to /. If the command line option -n is specified, keepalived doesn't `chdir("/")`, and so path names are relative to the initial working directory.

Commit e8d3d9d adds an error message if the configuration file(s) cannot be read, and keepalived then terminates.
