### ISSUE TITLE
segfault keepalived v1.2.20

### ISSUE THREAD

**Issue by Cugar15** [acassen/keepalived#313]
Just compiled and installed v1.2.20 and experiencing a segfault on debian wheezy:

May  4 15:00:56 mymachine Keepalived[3185]: Stopping Keepalived v1.2.19 (12/08,2015)
May  4 15:00:56 mymachine Keepalived_vrrp[3188]: VRRP_Instance(VI_1) sending 0 priority
May  4 15:00:57 mymachine Keepalived[15011]: Starting Keepalived v1.2.20 (05/04,2016)
May  4 15:00:57 mymachine Keepalived[15012]: Starting Healthcheck child process, pid=15013
May  4 15:00:57 mymachine Keepalived[15012]: Starting VRRP child process, pid=15014
May  4 15:00:57 mymachine Keepalived_healthcheckers[15013]: Initializing ipvs 2.6
May  4 15:00:57 mymachine Keepalived_healthcheckers[15013]: Registering Kernel netlink reflector
May  4 15:00:57 mymachine Keepalived_healthcheckers[15013]: Registering Kernel netlink command channel
May  4 15:00:57 mymachine Keepalived_healthcheckers[15013]: Opening file '/etc/keepalived/keepalived.conf'.
May  4 15:00:57 mymachine Keepalived_vrrp[15014]: Registering Kernel netlink reflector
May  4 15:00:57 mymachine Keepalived_vrrp[15014]: Registering Kernel netlink command channel
May  4 15:00:57 mymachine Keepalived_vrrp[15014]: Registering gratuitous ARP shared channel
May  4 15:00:57 mymachine Keepalived_vrrp[15014]: Opening file '/etc/keepalived/keepalived.conf'.
May  4 15:00:57 mymachine Keepalived_vrrp[15014]: Truncating auth_pass to 8 characters
May  4 15:00:57 mymachine Keepalived_vrrp[15014]: Using LinkWatch kernel netlink reflector...
May  4 15:00:57 mymachine Keepalived_healthcheckers[15013]: Using LinkWatch kernel netlink reflector...
May  4 15:00:57 mymachine Keepalived_vrrp[15014]: VRRP_Script(chk_nginx) succeeded
May  4 15:01:02 mymachine Keepalived_vrrp[15014]: VRRP_Instance(VI_1) Transition to MASTER STATE
May  4 15:01:02 mymachine kernel: [67343.220634] keepalived[15014]: segfault at 10 ip 0000000000418320 sp 00007ffc11aeed10 error 4 in keepalived[400000+37000]
May  4 15:01:02 mymachine Keepalived[15012]: pid 15014 exited due to segmentation fault (SIGSEGV).
May  4 15:01:02 mymachine Keepalived[15012]:   Please report a bug at https://github.com/acassen/keepalived/issues
May  4 15:01:02 mymachine Keepalived[15012]:   and include this log from when keepalived started, what happened
May  4 15:01:02 mymachine Keepalived[15012]:   immediately before the crash, and your configuration file.
May  4 15:01:02 mymachine Keepalived[15012]: VRRP child process(15014) died: Respawning
May  4 15:01:02 mymachine Keepalived[15012]: Starting VRRP child process, pid=15041
May  4 15:01:02 mymachine Keepalived_vrrp[15041]: Registering Kernel netlink reflector
May  4 15:01:02 mymachine Keepalived_vrrp[15041]: Registering Kernel netlink command channel
May  4 15:01:02 mymachine Keepalived_vrrp[15041]: Registering gratuitous ARP shared channel
May  4 15:01:02 mymachine Keepalived_vrrp[15041]: Opening file '/etc/keepalived/keepalived.conf'.
May  4 15:01:02 mymachine Keepalived_vrrp[15041]: Truncating auth_pass to 8 characters
May  4 15:01:02 mymachine Keepalived_vrrp[15041]: Using LinkWatch kernel netlink reflector...
May  4 15:01:02 mymachine Keepalived_vrrp[15041]: VRRP_Script(chk_nginx) succeeded

Configuration file:
vrrp_script chk_nginx {
    script "pidof nginx"
    interval 2
}

vrrp_instance VI_1 {
    interface eth0
    state MASTER
    priority 200
    advert_int 5

    virtual_router_id 33
    unicast_src_ip xxx.xxx.xxx.xxx
    unicast_peer {
       yyy.yyy.yyy.yyy
    }

    authentication {
        auth_type PASS
        auth_pass 1234567890
    }

    track_script {
        chk_nginx
    }

    notify /etc/keepalived/master.sh
}

Pls note: the IP addresses are not sharing the same network!

Thanks!

**Comment by Cugar15** [comment]
Hi, thanks for taking care of this problem....

To test, I just pulled the latest revision - however, this revision segfaults pretty much right away..
I also tested the previous commit - same result. SegFault at the same location.

May 15 10:03:16 178 Keepalived[5110]: Starting Keepalived v1.2.20 (05/15,2016)
May 15 10:03:16 178 kernel: [1567657.530325] keepalived[5111]: segfault at 2 ip 0000000000421932 sp 00007ffefd5152c0 error 4 in keepalived[400000+37000]

Do you want me to log a separat issue for this?

Thanks!

**Comment by pqarmitage** [comment]
On Sun, 2016-05-15 at 01:09 -0700, Cugar15 wrote:

> Hi, thanks for taking care of this problem....
> 
> To test, I just pulled the latest revision - however, this revision
> segfaults pretty much right away..
> I also tested the previous commit - same result. SegFault at the same
> location.
> 
> May 15 10:03:16 178 Keepalived[5110]: Starting Keepalived v1.2.20
> (05/15,2016)
> May 15 10:03:16 178 kernel: [1567657.530325] keepalived[5111]:
> segfault at 2 ip 0000000000421932 sp 00007ffefd5152c0 error 4 in
> keepalived[400000+37000]
> 
> Do you want me to log a separat issue for this?
> 

Yes please, logging a new issue would be most helpful. It would also
help if you could run keepalived with the -D command line option, since
that produces some extra output, and could help reduce the area of code
that needs to be looked at. And a copy of your configuration file will
be needed so that we can attempt to reproduce the problem.

Many thanks,

Quentin Armitage
