### ISSUE TITLE
SegFault at start up

### ISSUE THREAD

**Issue by Cugar15** [acassen/keepalived#328]
Keepalived segfaults at startup on latest version of wheezy.

Last version working:
commit 2e3cbb5ce04f27b448a3bf393298ccf2a756f3c6
Author: Quentin Armitage <quentin@armitage.org.uk>
Date:   Wed May 4 13:22:48 2016 +0100

Then, there are several versions, which don't compile.

Below version compiles again:
Version:
commit 08db6b91528ecca73b51382bb573321a7c37500b
Merge: 1ab8901 f11f2de
Author: Alexandre Cassen <acassen@gmail.com>
Date:   Thu May 5 18:26:03 2016 +0200

However segfaults obvioulsy right at startup:
May 15 12:13:53 178 Keepalived[33100]: Starting Keepalived v1.2.20 (05/15,2016)
May 15 12:13:53 178 kernel: [1575494.288532] keepalived[33101]: segfault at 2 ip 0000000000421932 sp 00007ffdc96b2220 error 4 in keepalived[400000+37000]

Adding -D does not give any more information.

ConfigurationFile: 
vrrp_script chk_nginx {
script "pidof nginx"
interval 2
}

vrrp_instance VI_1 {
interface eth0
state MASTER
priority 200
advert_int 5

virtual_router_id 33
unicast_src_ip xxx.xxx.xxx.xxx
unicast_peer {
   yyy.yyy.yyy.yyy
}

authentication {
    auth_type PASS
    auth_pass 1234567890
}

track_script {
    chk_nginx
}

notify /etc/keepalived/master.sh

}

Thanks for looking into this.

**Comment by pqarmitage** [comment]
Unfortunately I don't experience the same problem on my development system, but I'm not running Debian. On the other hand, there is very little code that executes between the initial fork to detach from the controlling terminal (and your log entries show that that fork has happened) and the next log entry that should occur, which is when the healthchecker and vrrp processes are started, and so it shouldn't be too hard to track down where this is happening.

Just to give me a bit more info, could you please provide the output of the following:
uname -a
gcc -v
keepalived -v
and also the command line options passed to keepalived when you run it.

Could you build a debug version of keepalived with "make clean; make debug", and enable core dumps, and then generate a back trace from the core dump, so we can see where it is seg faulting?

If this doesn't work, or generating a core dump isn't feasible, I can produce a patch (or a series of patches) to help pin down exactly where the problem is occurring.

**Comment by Cugar15** [comment]
uname -a:
Linux easybasar 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u4 x86_64 GNU/Linux

gcc -v:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.7.2 (Debian 4.7.2-5)

keepalived -v

Keepalived v1.2.20 (05/15,2016)

Copyright (C) 2001-2016 Alexandre Cassen, <acassen@gmail.com>

Build options: KRNL_2_6 WITH_LVS HAVE_IPVS_SYNCD WITH_VRRP HAVE_VRRP_VMAC WITHOUT_ADDR_GEN_MODE WITHOUT_SNMP WITHOUT_SNMP_KEEPALIVED WITHOUT_SNMP_CHECKER WITHOUT_SNMP_RFC WITHOUT_SNMP_RFCV2 WITHOUT_SNMP_RFCV3 WITHOUT_LIBNL WITH_VRRP_AUTH WITH_SO_MARK WITHOUT_LIBIPTC WITHOUT_LIBIPSET WITHOUT_IPV4_DEVCONF WITHOUT_IF_H_LINK_H_COLLISION HAVE_LINUX_NET_IF_H_COLLISION

Commandline option:

I'm simply executing out of shell:  /usr/local/sbin/keepalived -D

I'm working on the core dump... Right now, it's not cooperating... Stay tuned..

**Comment by pqarmitage** [comment]
I've found I've got a virtual machine running exactly that version of Debian, so I'll give it a go on there, but if you can generate the core dump, that'll be really helpful.

**Comment by Cugar15** [comment]
I hope, this is what you are looking for:

root@mymachine:~/software/keepalived# gdb /usr/local/sbin/keepalived /tmp/core_keepalived.53702
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/sbin/keepalived...done.
[New LWP 53702]

warning: Can't read pathname for load map: Input/output error.
Core was generated by `/usr/local/sbin/keepalived -D'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000421932 in check_conf_file (conf_file=<optimized out>) at parser.c:292
292                             if (access(globbuf.gl_pathv[i], R_OK)) {
(gdb)

**Comment by pqarmitage** [comment]
I'm not sure of the significance of the (conf_file=); I wonder if it means a null path name was specified for some reason.

Could you try applying the following patch, and see what it reports:
`
diff --git a/lib/parser.c b/lib/parser.c
index ed19e49..9a0cf45 100644
--- a/lib/parser.c
+++ b/lib/parser.c
@@ -280,9 +280,13 @@ bool check_conf_file(const char *conf_file)
 	glob_t globbuf;
 	int i;
 	bool ret = true;
+	int res;
+
+log_message(LOG_INFO, "check_conf_file called with conf_file %p (%s)", conf_file, conf_file ? conf_file : "(null)");
 
 	globbuf.gl_offs = 0;
-	glob(conf_file, 0, NULL, &globbuf);
+	res = glob(conf_file, 0, NULL, &globbuf);
+log_message(LOG_INFO, "glob returned %d. globbuf.gl_pathc = %d", res, globbuf.gl_pathc);
 
 	if (globbuf.gl_pathc == 0) {
 		log_message(LOG_INFO, "Unable to find configuration file %s", conf_file);
`

It looks to me as though it is failing to find the default configuration file (/etc/keepalived/keepalived.conf on my system), and there aren't the correct checks of the return value from the call to glob(). Although it doesn't seg fault on my system, I think it is the luck of the draw as to what happens to be on the stack where the glob_t is allocated, and I happen to get globuf.gl_pathc ==0, whereas I suspect you don't.

If you can confirm this, I can create a patch easily enough to resolve the underlying problem.

**Comment by Cugar15** [comment]
I hope, I#ve done this correctly...The format above is a bit odd for a git diff...
Here is the code:
--- a/lib/parser.c
+++ b/lib/parser.c
@@ -280,10 +280,17 @@ bool check_conf_file(const char *conf_file)
        glob_t globbuf;
        int i;
        bool ret = true;
+
+       int res;
+
+       log_message(LOG_INFO, "check_conf_file called with conf_file %p (%s)", conf_file, conf_file ? conf_file : "(null)");

        globbuf.gl_offs = 0;
        glob(conf_file, 0, NULL, &globbuf);

+       res = glob(conf_file, 0, NULL, &globbuf);
+       log_message(LOG_INFO, "glob returned %d. globbuf.gl_pathc = %d", res, globbuf.gl_pathc);
+
        if (globbuf.gl_pathc == 0) {
                log_message(LOG_INFO, "Unable to find configuration file %s", conf_file);
                ret = false;


Here is the output:

May 15 16:00:28 178 Keepalived[58424]: Starting Keepalived v1.2.20 (05/15,2016)
May 15 16:00:28 178 Keepalived[58425]: check_conf_file called with conf_file (nil) ((null))
May 15 16:00:28 178 Keepalived[58425]: glob returned -1. globbuf.gl_pathc = -1480208832
May 15 16:00:28 178 kernel: [1589089.849992] keepalived[58425]: segfault at 2 ip 0000000000421982 sp 00007ffd0d9065e0 error 4 in keepalived[400000+37000]

**Comment by Cugar15** [comment]
Update:
I add the conf file to the startup options and then it works:

/usr/local/sbin/keepalived -D -f /etc/keepalived/keepalived.conf

```
May 15 16:14:14 178 Keepalived[59508]: Starting Keepalived v1.2.20 (05/15,2016)
May 15 16:14:14 178 Keepalived[59509]: check_conf_file called with conf_file 0x7ffe22cf5e49 (/etc/keepalived/keepalived.conf)
May 15 16:14:14 178 Keepalived[59509]: glob returned 0. globbuf.gl_pathc = 1
May 15 16:14:14 178 Keepalived[59509]: Starting Healthcheck child process, pid=59510
May 15 16:14:14 178 Keepalived_healthcheckers[59510]: Initializing ipvs 2.6
May 15 16:14:14 178 Keepalived[59509]: Starting VRRP child process, pid=59511
May 15 16:14:14 178 Keepalived_healthcheckers[59510]: Setting base index for eth0 to ifi_index 2
May 15 16:14:14 178 Keepalived_healthcheckers[59510]: Netlink reflector reports IP 178.248.241.85 added
May 15 16:14:14 178 Keepalived_healthcheckers[59510]: Netlink reflector reports IP fe80::782a:2ff:fed5:7165 added
May 15 16:14:14 178 Keepalived_healthcheckers[59510]: Registering Kernel netlink reflector
May 15 16:14:14 178 Keepalived_healthcheckers[59510]: Registering Kernel netlink command channel
May 15 16:14:14 178 Keepalived_healthcheckers[59510]: Opening file '/etc/keepalived/keepalived.conf'.
May 15 16:14:14 178 Keepalived_vrrp[59511]: Setting base index for eth0 to ifi_index 2
May 15 16:14:14 178 Keepalived_vrrp[59511]: Netlink reflector reports IP 178.248.241.85 added
May 15 16:14:14 178 Keepalived_vrrp[59511]: Netlink reflector reports IP fe80::782a:2ff:fed5:7165 added
May 15 16:14:14 178 Keepalived_vrrp[59511]: Registering Kernel netlink reflector
May 15 16:14:14 178 Keepalived_vrrp[59511]: Registering Kernel netlink command channel
May 15 16:14:14 178 Keepalived_vrrp[59511]: Registering gratuitous ARP shared channel
May 15 16:14:14 178 Keepalived_vrrp[59511]: Opening file '/etc/keepalived/keepalived.conf'.
May 15 16:14:14 178 Keepalived_vrrp[59511]: Truncating auth_pass to 8 characters
May 15 16:14:14 178 Keepalived_vrrp[59511]: Using LinkWatch kernel netlink reflector...
May 15 16:14:14 178 Keepalived_vrrp[59511]: VRRP_Instance(VI_1) Entering BACKUP STATE
May 15 16:14:14 178 Keepalived_vrrp[59511]: Opening script file /etc/keepalived/backup.sh
May 15 16:14:14 178 Keepalived_vrrp[59511]: VRRP sockpool: [ifindex(2), proto(112), unicast(1), fd(10,11)]
May 15 16:14:14 178 Keepalived_healthcheckers[59510]: Using LinkWatch kernel netlink reflector...
May 15 16:14:14 178 Keepalived_vrrp[59511]: VRRP_Script(chk_nginx) succeeded

```

**Comment by pqarmitage** [comment]
That's what I was expecting to see. On my system it reports globbuf.gl_pathc = 0, which is my it doesn't segfault. I suspect the bullet points were introduced by the Markdown formatting, but what you've applied is what I had intended.

I've been looking at check_conf_file() and there seems to be more than one issue. There is this issue about not checking the return value from glob(), but also access() will return success if the path given is a directory, which would be problematical, and also why isn't the default configuration file name passed if none has been specified.

I'll need a little bit of time to sort out a full patch for theses issues, but if you revert the previous patch I sent, and apply the following patch, then I think it will work around your problem for now (I hope attaching the patch as below helps with the formatting:

[parser.1.patch.txt](https://github.com/acassen/keepalived/files/265023/parser.1.patch.txt)

Many thanks for your help, and I'll reference this issue when I submit the pull request with a full fix, so you should get notification.

It would be helpful if you could confirm if he patch I've included does resolve the problem.

**Comment by Cugar15** [comment]
I figured out the trick to format the code correctly: 
It's tripple back-ticks before and after the code section.  
The formatting help just suggests double back-ticks :(

Your current patch - above - stops keepalived gracefully..

```
May 15 16:31:48 178 Keepalived[4509]: Starting Keepalived v1.2.20 (05/15,2016)
May 15 16:31:48 178 Keepalived[4510]: Unable to find configuration file (null) (glob returned -1)
May 15 16:31:48 178 Keepalived[4510]: Stopped Keepalived v1.2.20 (05/15,2016)
```

I will watchout for the resolution and will test as soon as available.

Thanks so much for now.

**Comment by pqarmitage** [comment]
I think the following patch should enable keepalived to run:
```
--- a/keepalived/core/main.c
+++ b/keepalived/core/main.c
@@ -384,7 +384,7 @@ main(int argc, char **argv)
  	   This means that if any config file names are not
  	   absolute file names, the behaviour will be different
  	   depending on whether we forked or not. */
-	if (!check_conf_file(conf_file))
+	if (!check_conf_file(conf_file ? conf_file : CONF))
 		goto end;
 
 	/* write the father's pidfile */
```
(thanks for the tip about triple back-ticks).
IT seems that the code was totally relying on globbuf.pathc = 0 if the glob() call failed. This patch passes the default config file name if one hasn't been specified, and so check_conf_file() should now succeed, and keepalived should run successfully.

**Comment by Cugar15** [comment]
Yepp, now, it succeeds!
Thanks a ton again.
