### ISSUE TITLE
some question about vmac？

### ISSUE THREAD

**Issue by Michael754267513** [acassen/keepalived#334]
keepalived configure is use_vmac，i use to command ifconfig ，i found  other vNIC，and on，i use ping other private ip，but this ip is  Destination Host Unreachable，how to finish off with this problem！ 

3: vrrp.51@eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN 
    link/ether 00:00:5e:00:01:33 brd ff:ff:ff:ff:ff:ff
    inet 192.168.32.105/24 scope global vrrp.51
    inet6 fe80::200:5eff:fe00:133/64 scope link 
       valid_lft forever preferred_lft forever
[root@crm-nginx-test1 samples]# ping 192.168.32.110
PING 192.168.32.110 (192.168.32.110) 56(84) bytes of data.
From 192.168.32.105 icmp_seq=1 Destination Host Unreachable

**Comment by pqarmitage** [comment]
From what you have provided, the only issue I can see is that you appear to have configured the vrrp_instance with
virtual_ipaddress {
    192.168.32.105**/24**
}

It should be configured as
virtual_ipaddress {
    192.168.32.105**/32**
}

Whether that is the cause of your problem I can't tell, though.

What host/interface is 192.168.32.110 on? Can you ping that address from another machine?

I think the first place to look is your routing table to see how it is attempting to route to 192.168.32.110. After attempting to ping 192.168.32.110 does 'arp -a' show an entry for that address?

**Comment by Michael754267513** [comment]
this is my test keepalive vmac!  i saw a link,this feature only supper kernel pacth!  http://git.kernel.org/?p=linux/kernel/git/torvalds/linux.git;a=commitdiff;h=729e72a10930ef765c11a5a35031ba47f18221c4
i don`t use this pacth!

[root@QA-PUB01 ~]# service keepalived stop 
Stopping keepalived: [  OK  ]
[root@QA-PUB01 ~]# ping baidu.com
PING baidu.com (123.125.114.144) 56(84) bytes of data.
64 bytes from 123.125.114.144: icmp_seq=1 ttl=50 time=26.8 ms
64 bytes from 123.125.114.144: icmp_seq=2 ttl=50 time=28.8 ms
^C
--- baidu.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 7821ms
rtt min/avg/max/mdev = 26.864/27.833/28.803/0.983 ms
[root@QA-PUB01 ~]# cat /etc/keepalived/keepalived.conf | grep 'vmac'
    use_vmac
[root@QA-PUB01 ~]# service keepalived start
Starting keepalived: [  OK  ]
[root@QA-PUB01 ~]# ip a 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:0c:29:27:a1:c8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.188/24 brd 192.168.2.255 scope global eth1
    inet6 fe80::20c:29ff:fe27:a1c8/64 scope link 
       valid_lft forever preferred_lft forever
5: vrrp.51@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN 
    link/ether 00:00:5e:00:01:33 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.16/32 scope global vrrp.51
    inet6 fe80::200:5eff:fe00:133/64 scope link 
       valid_lft forever preferred_lft forever
[root@QA-PUB01 ~]# ping baidu.com
ping: unknown host baidu.com
[root@QA-PUB01 ~]# vi /etc/keepalived/keepalived.conf 
[root@QA-PUB01 ~]# cat /etc/keepalived/keepalived.conf | grep 'vmac'
    #use_vmac
[root@QA-PUB01 ~]# service keepalived restart
Stopping keepalived: [  OK  ]
Starting keepalived: [  OK  ]
[root@QA-PUB01 ~]# ping baidu.com
PING baidu.com (123.125.114.144) 56(84) bytes of data.
64 bytes from 123.125.114.144: icmp_seq=4 ttl=50 time=34.3 ms
64 bytes from 123.125.114.144: icmp_seq=5 ttl=50 time=53.6 ms

**Comment by pqarmitage** [comment]
It appears that when keepalived is up, and presumably in master mode, that you can no longer access devices on the network.

When keepalived is running, could you try the following command:
`ping -S eth1 123.125.114.114`
and post the output.

You mention that you don't use the kernel patch referred to above. What kernel version are you using? Have you applied any patches to the kernel?

Also, what version of keepalived are you using?

Could you also please post a copy of your configuration file too.

**Comment by Michael754267513** [comment]
[root@QA-PUB01 ~]# ping -S eth1 114.114.114.114
ping: bad sndbuf value.
[root@QA-PUB01 ~]# uname -a 
Linux QA-PUB01 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

! Configuration File for keepalived

global_defs {
   notification_email {
        754267513@qq.com
   }
   notification_email_from Alexandre.Cassen@firewall.loc 
   smtp_server smtp.qq.com
   smtp_connect_timeout 30
   router_id Nginx_DEVEL
}
vrrp_script chk_nginx {
    script "/etc/keepalived/scripts/Check_Nginx.sh"
    interval 2
}
vrrp_instance VI_1 {
    state MASTER
    interface eth1
    virtual_router_id 51
    use_vmac
    priority 100
    advert_int 1
    nopreempt
    unicast_src_ip  192.168.2.188
    unicast_peer {
                  192.168.12.186
                }
    authentication {
        auth_type PASS
        auth_pass rayootech
    }
    virtual_ipaddress {
        192.168.2.16/32
    }
   track_script {
        chk_nginx
   }
}

**Comment by pqarmitage** [comment]
I'm really sorry, I meant to as you to try
`ping -I eth1 123.125.114.114`
This is to ensure that when you send the ping, it is not going from the vmac interface. The address needs to be the address of baidu.com that you used for the successful ping (I want to avoid having to do a name lookup, which is my the address should be specified).

Could you also please specify the version of keepalived you are using. `keepalived -v` should report that.

**Comment by acassen** [comment]
please use keepalived-user mailing-list.
