### ISSUE TITLE
[(null)] VRRP instance

### ISSUE THREAD

**Issue by Cugar15** [acassen/keepalived#338]
Hi,

 I'm running keepalived on two (almost) identical machines and enabled smtp_alert.
Software is separately compiled and there are no obvious differences in the compile log.

On one box, I'm getting the following subject in the email alert (backup config):
[122.45.567.34] VRRP instance VL_1 - Entering Master state

On the other box, I'm getting (null) instead of the IP address (master config):
[(null)] VRRP instance VL_1 - Entering Master state

I cannot spot anything wrong.... config files are identical (well obviously master/backup config)

Any pointer why that behavior might happen?
I'm mainly concerned, that s.th. else might not work either... 

Thanks

**Comment by pqarmitage** [comment]
Can you confirm that the messages are actually:
`[122.45.567.34] VRRP instance VL_1 - Entering MASTER state`
and
`[(null)] VRRP instance VL_1 - Entering MASTER state`
i.e. MASTER is capitalised. I can't see anywhere in the code where there is a message like that without MASTER being capitalised.

Looking at the function smtp_alert() in keepalived/core/smpt.c, it would appear that on one machine in the global config section you have
`router_id 122.45.567.34`
and on the other machine you don't have any router_id configured.

If the above is the case, it would explain what you are experiencing. If this isn't the case, then copies of your two configs would be helpful.

**Comment by Cugar15** [comment]
Yes, I can confirm these messages.
I take it, that the capitalized MASTER and BACKUP are taken from 'state MASTER' in the vrrp_instance VI_1. 

I have not set router_id in any of my two config files.
However, I can confirm, that once setting the router_id, this string is taken as part of the subject line and the (null) is replaced.

On the other side, there seems to be a default setting to use the IP address in case the router_id is not set. This default is taken on one box and is not taken on the other box...

In global_data.c, the default is set by a function called: get_local_name();
Not sure where this once comes from and what exactly this function is reading.

**Comment by pqarmitage** [comment]
On Tue, 2016-05-24 at 00:18 -0700, Cugar15 wrote:


> I have not set router_id in any of my two config files.
> However, I can confirm, that once setting the router_id, this string
> is taken as part of the subject line and the (null) is replaced.
> 
> On the other side, there seems to be a default setting to use the IP
> address in case the router_id is not set. This default is taken on one
> box and is not taken on the other box...
> 
> In global_data.c, the default is set by a function called:
> get_local_name();


Can you try the following patch and run it on the machine that is
reporting null for the router_id, and post the output from your log.
diff --git a/lib/utils.c b/lib/utils.c
index 3010b4d..de28afe 100644
--- a/lib/utils.c
+++ b/lib/utils.c
@@ -28,6 +28,8 @@
 #include "signals.h"
 #include "bitops.h"
 
+#include "logger.h"
+
 /* global vars */
 unsigned long debug = 0;
 
@@ -476,11 +478,15 @@ get_local_name(void)
 	memset(&hints, 0, sizeof(struct addrinfo));
 	hints.ai_flags = AI_CANONNAME;
 
-	if (uname(&name) < 0)
+	if (uname(&name) < 0) {
+		log_message(LOG_INFO, "get_local_name - uname() returned < 0");
 		return NULL;
+	}
 
-	if (getaddrinfo(name.nodename, NULL, &hints, &res) != 0)
+	if (getaddrinfo(name.nodename, NULL, &hints, &res) != 0) {
+		log_message(LOG_INFO, "get_local_name - getaddrinfo() returned !=
0");
 		return NULL;
+	}
 
 	if (res && res->ai_canonname) {
 		len = strlen(res->ai_canonname);
@@ -488,10 +494,17 @@ get_local_name(void)
 		if (canonname) {
 			memcpy(canonname, res->ai_canonname, len);
 		}
+		else
+			log_message(LOG_INFO, "get_local_name - MALLOC failure");
 	}
 
 	freeaddrinfo(res);
 
+	if (canonname)
+		log_info(LOG_INFO, "get_local_name returning - %s", canonname);
+	else
+		log_info(LOG_INFO, "get_local_name returnning NULL");
+
 	return canonname;
 }

**Comment by Cugar15** [comment]
Here you go:

May 24 12:13:53 my-box Keepalived_healthcheckers[41918]: get_local_name - getaddrinfo() returned != 0
May 24 12:13:53 my-box Keepalived_vrrp[41920]: get_local_name - getaddrinfo() returned != 0

FYI: Up there:   log_info(LOG_INFO,... needs to be:   log_message(LOG_INFO,....
 
Thanks a ton, Cugar15

**Comment by pqarmitage** [comment]
Oops, I thought I had compiled it, so it shouldn't have had that
log_info() error. For some reason I typed that in another code change I
was making today too.

Does the getaddrinfo() returned != 0 resolve your issue? I presume that
on your other machine getaddrinfo() returns 0.

**Comment by Cugar15** [comment]
OK, well, not really...
I think, we know now, that getaddrinfo() fails. This sparks the question on why it fails - I guess..

The other box returns the IP address...

Any idea?

**Comment by pqarmitage** [comment]
It looks like like either uname () is not returning anything useful, or
getaddrinfo() isn't.

At a command prompt on the machine that isn't returning anything
helpful, can you enter the following commands, and see what output you
get:
uname -n
dig $(uname -n) ANY

Could you also try the following patch, and see if that gives any more
info:
diff --git a/lib/utils.c b/lib/utils.c
index 3010b4d..bf069bd 100644
--- a/lib/utils.c
+++ b/lib/utils.c
@@ -28,6 +28,8 @@
 #include "signals.h"
 #include "bitops.h"
 
+#include "logger.h"
+
 /* global vars */
 unsigned long debug = 0;
 
@@ -479,8 +481,11 @@ get_local_name(void)
 	if (uname(&name) < 0)
 		return NULL;
 
-	if (getaddrinfo(name.nodename, NULL, &hints, &res) != 0)
+int err;
+	if ((err = getaddrinfo(name.nodename, NULL, &hints, &res)) != 0) {
+log_message(LOG_INFO, "getaddrinfo(%s, ...) returned error (%d) - %s",
name.nodename, err, gai_strerror(err));
 		return NULL;
+}
 
 	if (res && res->ai_canonname) {
 		len = strlen(res->ai_canonname);

**Comment by Cugar15** [comment]
name.nodename returns the correct name,
err = 1
gai_strerror(err) -> Unknown error

on the 'working box', the difference is that err = 0 - all the rest is identical.

So, it must be s.th. with &hints???

**Comment by pqarmitage** [comment]
On Tue, 2016-05-24 at 08:13 -0700, Cugar15 wrote:

> name.nodename returns the correct name,
> err = 1
> gai_strerror(err) -> Unknown error
> 

A return value from getaddrinfo() is either 0 for success, or one of the
error codes EAI_... , as defined in <netdb.h>, which on my system are
all negative, so returning 1 would seem to be invalid, and explain why
gai_strerror(err) reports unknown error.

Do the shell commands:
$ uname -n
and
$ dig $(uname -n) ANY
return correctly?

You could try the following stand-alone program to see what you get, and
if it doesn't work on your machine, then it would appear not to be a
problem with keepalived:

#include <netdb.h>
#include <stdio.h>
#include <sys/utsname.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <memory.h>

int main(int argc, char** argv)
{
	struct utsname sname;
	int sav_errno;
	struct addrinfo hints;
	struct addrinfo *addr;
	int err;

	err = uname(&sname);
	if (err < 0) {
		sav_errno = errno;
		printf("uname failed with err %, errno %d (%s)\n", err, sav_errno,
strerror(sav_errno));
		return (1);
	}
	printf("uname returned %s\n", sname.nodename);

	memset(&hints, 0, sizeof(hints));
	hints.ai_flags = AI_CANONNAME;

	err = getaddrinfo(sname.nodename, NULL, &hints, &addr);
	if (err) {
		printf ("getaddrinfo returned err = %d, %s\n", gai_strerror(err));
		return(1);
	}
	printf("Canonical name is %s\n", addr->ai_canonname);
	freeaddrinfo(addr);
}

**Comment by Cugar15** [comment]
OK, I found it! 
It's most likely a wrong entry in the /etc/hosts file.
Some time ago the machine name was changed and got a different IP address - but the hosts file was never updated...

Sorry for keeping you work on this...

I will proof this later tonight..

I'm closing this for now - sorry again!

**Comment by Cugar15** [comment]
OK, verified. The hostname was not correctly configured in the /etc/hosts file.
Changing the configuration, getaddrinfo works and returns the correct IP address.

**Comment by pqarmitage** [comment]
Good news you've got it sorted.
