### ISSUE TITLE
Add support for SMTP authentication and TLS

### ISSUE THREAD

**Issue by toddjames** [acassen/keepalived#343]
Looking through the documentation and source code, it looks like SMTP authentication and TLS are not current implemented in keepalived.

As organizations are increasing their security, they (including mine) are disabling anonymous SMTP access, as well as unencrypted SMTP. keepalived notifications will not work in such environments.

Please consider adding support.

**Comment by mschneid** [comment]
Under normal circumstances it makes no sense to configure any software to use the company's STMP server directly. Install a MTA like Postfix and securely relay any message to the company's SMTP server. With this setup you can configure any software running on the local machine to send mails via localhost:25.

**Comment by acassen** [comment]
+1

alternatively if this feature is really needed (I dont see urgent matter for this) please consider sponsoring...

**Comment by ismailazerty** [comment]
Hello,

    please reopen this issue, it's really needed.

Regards

**Comment by toddjames** [comment]
@ismailazerty 

No. I originally opened this issue 5.5 years ago thinking requesting the same thing that you think you need now. I've evolved after this. The authors of keepalived are 100% correct and I completely changed my own system architecture theory in this regard after the response from @mschneid.

You need to configure an SMTP relay that supports all of the SMTP options, like Postfix. It can be on the same box (and likely should). Not for the reason you believe.

THE MOST IMPORTANT PART IS that none of your systems require that a single email server is alive before sending an email. They all have their own relay, specific to that system, and part of that system. If that system cannot contact the email server, it should have its own internal relay (Postfix, or otherwise) to queue up email until the destination email server (even if internal) is available.

Keepalived cannot queue emails. If you care about getting emails, even if your email server is down, you need to install an MTA like Postfix. EVERY service should queue its own email. Keepalived does not queue email, so add Postfix alongside it to do so. That's your service. Keepalived + Postfix on one server. Or at least, that was the result we rolled with for several years before the solution was replaced.
