### ISSUE TITLE
keepalived will not compile under linux headers >4.4

### ISSUE THREAD

**Issue by gregnetau** [acassen/keepalived#350]
Hi,

I cannot get keepalived to compile under Linux 4.4 kernel/headers:

check_snmp.c: In function 'check_snmp_virtualserver':
check_snmp.c:213:2: error: unknown type name 'U64'
  static U64 counter64_ret;
  ^
check_snmp.c:390:16: error: request for member 'low' in something not a structure or union
   counter64_ret.low = v->stats.inbytes & 0xffffffff;
                ^
check_snmp.c:391:16: error: request for member 'high' in something not a structure or union
   counter64_ret.high = v->stats.inbytes >> 32;
                ^
check_snmp.c:392:21: error: 'U64' undeclared (first use in this function)
   *var_len = sizeof(U64);
                     ^
check_snmp.c:392:21: note: each undeclared identifier is reported only once for each function it appears in
check_snmp.c:396:16: error: request for member 'low' in something not a structure or union
   counter64_ret.low = v->stats.outbytes & 0xffffffff;
                ^
check_snmp.c:397:16: error: request for member 'high' in something not a structure or union
   counter64_ret.high = v->stats.outbytes >> 32;
                ^
check_snmp.c: In function 'check_snmp_realserver':
check_snmp.c:491:2: error: unknown type name 'U64'
  static U64 counter64_ret;
  ^
check_snmp.c:680:16: error: request for member 'low' in something not a structure or union
   counter64_ret.low = be->stats.inbytes & 0xffffffff;
                ^
check_snmp.c:681:16: error: request for member 'high' in something not a structure or union
   counter64_ret.high = be->stats.inbytes >> 32;
                ^
check_snmp.c:682:21: error: 'U64' undeclared (first use in this function)
   *var_len = sizeof(U64);
                     ^
check_snmp.c:686:16: error: request for member 'low' in something not a structure or union
   counter64_ret.low = be->stats.outbytes & 0xffffffff;
                ^
check_snmp.c:687:16: error: request for member 'high' in something not a structure or union
   counter64_ret.high = be->stats.outbytes >> 32;
                ^
make[2]: *** [Makefile:26: check_snmp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/tmp/portage/sys-cluster/keepalived-1.2.19/work/keepalived-1.2.19/keepalived/check'
make[1]: *** [Makefile:45: all] Error 1
make[1]: Leaving directory '/var/tmp/portage/sys-cluster/keepalived-1.2.19/work/keepalived-1.2.19/keepalived'
make: *** [Makefile:15: all] Error 2
 * ERROR: sys-cluster/keepalived-1.2.19::gentoo failed (compile phase):
 *   emake failed

Thanks,

Greg

**Comment by pqarmitage** [comment]
On my 4.4 system (with keepalived ver 1.2.21):
check_snmp.c includes snmp.h (in keepalived/include)
snmp.h includes <net-snmp/net-snmp-includes.h>
<net-snmp/net-snmp-includes.h> includes <net-snmp/utilities.h>
<net-snmp/utilities.h> includes <net-snmp/library/int64.h>
<net-snmp/library/int64.h> has typedef struct counter64 U64;

and struct counter64 is defined in <net-snmp/library/asn1.h> which is included from <net-snmp/utilities.h>

It appears that in keepalived ver 1.2.19 snmp.h is included via check_snmp.h

The version I have of net-snmp is 5.7.3.

Can you check what is happening on your system.

By the way, you might find it beneficial to upgrade to keepalived ver 1.2.21.

**Comment by gregnetau** [comment]
Hi,

 

I’ve done further debugging and even if I downgrade my system linux-headers to 3.18 it still fails to compile with the same error:

 

check_snmp.c: In function 'check_snmp_virtualserver':

check_snmp.c:313:2: error: unknown type name 'U64'

  static U64 counter64_ret;

  ^

check_snmp.c:481:16: error: request for member 'low' in something not a structure or union

   counter64_ret.low = v->stats.inbytes & 0xffffffff;

                ^

check_snmp.c:482:16: error: request for member 'high' in something not a structure or union

   counter64_ret.high = v->stats.inbytes >> 32;

                ^

check_snmp.c:483:21: error: 'U64' undeclared (first use in this function)

   *var_len = sizeof(U64);

                     ^

check_snmp.c:483:21: note: each undeclared identifier is reported only once for each function it appears in

check_snmp.c:487:16: error: request for member 'low' in something not a structure or union

   counter64_ret.low = v->stats.outbytes & 0xffffffff;

                ^

check_snmp.c:488:16: error: request for member 'high' in something not a structure or union

   counter64_ret.high = v->stats.outbytes >> 32;

                ^

check_snmp.c: In function 'check_snmp_realserver':

check_snmp.c:582:2: error: unknown type name 'U64'

  static U64 counter64_ret;

  ^

check_snmp.c:771:16: error: request for member 'low' in something not a structure or union

   counter64_ret.low = be->stats.inbytes & 0xffffffff;

                ^

check_snmp.c:772:16: error: request for member 'high' in something not a structure or union

   counter64_ret.high = be->stats.inbytes >> 32;

                ^

check_snmp.c:773:21: error: 'U64' undeclared (first use in this function)

   *var_len = sizeof(U64);

                     ^

check_snmp.c:777:16: error: request for member 'low' in something not a structure or union

   counter64_ret.low = be->stats.outbytes & 0xffffffff;

                ^

check_snmp.c:778:16: error: request for member 'high' in something not a structure or union

   counter64_ret.high = be->stats.outbytes >> 32;

                ^

make[2]: *** [Makefile:25: check_snmp.o] Error 1

 

 

My current installed versions are:

 

[ebuild   R    ] sys-kernel/linux-headers-4.4

[ebuild   R    ] net-analyzer/net-snmp-5.7.3-r5

 

OS: Gentoo

 

If I don’t use the –snmp compile flag, it will compile fine.

 

Thanks,

 

Greg

**Comment by SjonHortensius** [comment]
@gregnetau what version of net-snmp do you have installed? These errors have nothing to do with the kernel(-headers) you have

**Comment by pqarmitage** [comment]
This does not look like a Linux 4.4 issue, but more like an issue with your net-snmp headers, although we both appear to have net-snmp v5.7.3 installed.

It appears that in my first comment where I gave the chain of include files to get to the definition of U64 (which is what appears to be the problem) some of the info is missing.

It should have said:
`check_snmp.c` includes `snmp.h` (in keepalived/include)
`snmp.h` includes `<net-snmp/net-snmp-includes.h>`
`<net-snmp/net-snmp-includes.h>` includes `<net-snmp/utilities.h>`
`<net-snmp/utilities.h>` includes `<net-snmp/library/int64.h>`
`<net-snmp/library/int64.h>` has `typedef struct counter64 U64;`

Can you check the chain of include files to make sure that `<net-snmp/library/int64.h>` is being included, and also that it has `typedef struct counter64 U64;`

**Comment by gregnetau** [comment]
I've attached int64.h from /usr/include/net-snmp/library/int64.h
[int64.zip](https://github.com/acassen/keepalived/files/301631/int64.zip)

**Comment by pqarmitage** [comment]
Thanks for your copy of int64.h; we can now see what has happened.

It would appear that you are not using the released version of net-snmp v5.7.3, but a later snapshot from https://sourceforce.net/p/net-snmp/ that was taken on or after 21 February 2016. Their commit 477b43 removed the typedef U64 that check_snmp.c was using.

keepalived commit 9c04279 updates check_snmp.c so that it uses `struct counter64` rather than `U64`, and so now you should be able to compile successfully.

Thanks for the heads-up on this; it'll save others having this problem later.

**Comment by gregnetau** [comment]
Confirmed that commit [https://github.com/acassen/keepalived/commit/9c0427947283c0e67aaa107064546105cc32c5b2](url) fixes this issue.
