### ISSUE TITLE
vrrp_ipaddress.c:121: error: expected identifier before ‘&’ token  At Centos6.2

### ISSUE THREAD

**Issue by dhpark21** [acassen/keepalived#357]
In file included from /usr/src/linux/include/linux/netfilter/x_tables.h:3,
                 from /usr/include/libiptc/libxtc.h:6,
                 from ../include/vrrp_iptables.h:27,
                 from vrrp_ipaddress.c:26:
/usr/src/linux/include/linux/kernel.h:733:2: warning: #warning Attempt to use kernel headers from user space, see http:
vrrp_ipaddress.c: In function ‘netlink_ipaddress’:
vrrp_ipaddress.c:121: error: expected identifier before ‘&’ token
vrrp_ipaddress.c:121: error: too few arguments to function ‘addattr_l’
make[2]: *** [vrrp_ipaddress.o] Error 1

happen At CentOS 6.2

**Comment by acassen** [comment]
fixed by last commit
