### ISSUE TITLE
Update documentation on www.keepalived.org

### ISSUE THREAD

**Issue by harobed** [acassen/keepalived#361]
Hi,

I see this documentation folder: https://github.com/acassen/keepalived/tree/master/doc where is this documentation in keepalived website? This is very light documentation page http://www.keepalived.org/documentation.html.

Best regards,
Stéphane

**Comment by harobed** [comment]
I've build the documentation with:

```
$ pip install sphinx sphinx_rtd_theme
$ cd doc
$ make html
$ open -a firefox build/html/
```

afterwards I've a beautiful documentation… why this documentation isn't available online?

<img width="1101" alt="capture d ecran 2016-06-20 a 15 11 16" src="https://cloud.githubusercontent.com/assets/230143/16195328/51cb1fd8-36f9-11e6-8be1-d53c910ec971.png">

**Comment by vikas027** [comment]
@harobed I tried to create html documentation as below in vain

```
$ pip install sphinx sphinx_rtd_theme
$ git clone git@github.com:acassen/keepalived.git
$ cd keepalived/doc
$ 
$ make html
make: *** No rule to make target `html'.  Stop.
$ 
$ cp -v Makefile.in Makefile
$ make html
Makefile:15: *** missing separator.  Stop.
$

```
Not sure, what I am missing.

**Comment by pqarmitage** [comment]
After the git clone:
```
cd keepalived
./configure
cd doc
make html
```
Executing configure creates doc/Makefile

**Comment by giovtorres** [comment]
Perhaps, one of the keepalived members could connect the repo to readthedocs.org and have the beautiful documentation above built automatically.  keepalived.org could then have pointer to readthedocs.  Just a suggestion :)

**Comment by acassen** [comment]
I will try to find out time to update website ;)

**Comment by adarshaj** [comment]
Gentle reminder, the site still has very old documentation links. /cc @acassen

**Comment by k0ste** [comment]
`Perhaps, one of the keepalived members could connect the repo to readthedocs.org and have the beautiful documentation above built automatically. keepalived.org could then have pointer to readthedocs. Just a suggestion :)`

Perhaps this has already happened? -> [keepalived.readthedocs.io](http://keepalived.readthedocs.io/en/latest/)

**Comment by acassen** [comment]
Keepalived.org documentation section is now based on sphinx generated output. This section is automatically updated.
