### ISSUE TITLE
unable to run multiple instances with keepalived 1.2.22

### ISSUE THREAD

**Issue by markrechler** [acassen/keepalived#363]
Attempting to run multiple instances of keeplaived with unique VRRPs on the same box results in the last instance tearing down anything previously running and becoming the only active VRRP. In the below example `1.1.1.2` would become the only active VRRP. Also tried with unique strings, did not make a difference and works fine with `1.2.13`

ie instance1:
```
vrrp_instance BITLY_FE {
    interface bond1
    virtual_router_id 26
    nopreempt
    state BACKUP
    priority 50
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass xxxx
    }
    virtual_ipaddress {
        1.1.1.1
    }
}
```
instance 2:
```
vrrp_instance BITLY_FE {
    interface bond1
    virtual_router_id 27
    nopreempt
    state MASTER
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass xxxx
    }
    virtual_ipaddress {
        1.1.1.2
    }
}
```
```

**Comment by acassen** [comment]
there is not enough info to debug here. Your cons is really simple, running same stuff here works... Hmm maybe a system conf like iptables setting ? dunno. Without more info we dont know how to troubleshoot for now...

**Comment by markrechler** [comment]
Hmm, possible it was/is a firewall issue. Did have split-brain on the older version before adding allows for VRRP, will attempt to re-replicate and post more info.

**Comment by markrechler** [comment]
Was able to replicate the behavior with firewall completely disabled, both IP's stay up but IPVS only keeps the virtual server/real server setup of the last instance to start.

```
[06:51 PM] root ~ (master)
$ svc -u /service/keepalived_dev_test
[06:51 PM] root ~ (master)
$ ip addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 00:0c:29:d6:e1:df brd ff:ff:ff:ff:ff:ff
    inet 192.168.148.128/24 brd 192.168.148.255 scope global eth0
    inet 172.16.207.249/32 brd 172.16.207.255 scope global eth0
    inet6 fe80::20c:29ff:fed6:e1df/64 scope link
       valid_lft forever preferred_lft forever
[06:52 PM] root ~ (master)
$ ipvsadm -L -n
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  172.16.207.249:80 sh persistent 120
  -> 127.0.0.1:80                 Local   1      0          0
[06:53 PM] root ~ (master)
$ svc -u /service/keepalived_dev_test2
[06:53 PM] root ~ (master)
$ ip addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 00:0c:29:d6:e1:df brd ff:ff:ff:ff:ff:ff
    inet 192.168.148.128/24 brd 192.168.148.255 scope global eth0
    inet 172.16.207.249/32 brd 172.16.207.255 scope global eth0
    inet 172.16.207.250/32 brd 172.16.207.255 scope global eth0
    inet6 fe80::20c:29ff:fed6:e1df/64 scope link
       valid_lft forever preferred_lft forever
[06:54 PM] root ~ (master)
$ ipvsadm -L -n
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  172.16.207.250:80 sh persistent 120
  -> 127.0.0.1:80                 Local   1      0          0
```

configs:
```
cat /bitly/local/keepalived/conf/keepalived.dev_test.conf

global_defs {
   notification_email {
     none
   }
   notification_email_from nobody
   router_id dev.bitly.org
}

vrrp_sync_group BITLY_VIPS {
    group {
        BITLY_FE
    }
}


vrrp_instance BITLY_FE {
    interface eth0
    virtual_router_id 249
    nopreempt
    state BACKUP
    priority 50
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass xxxx
    }
    virtual_ipaddress {
        172.16.207.249/32 brd 172.16.207.255
    }
}


# dev test
virtual_server 172.16.207.249 80 {
    delay_loop 6
    lb_algo sh
    lb_kind DR
    persistence_timeout 120
    protocol TCP

    # 127.0.0.1
    real_server 127.0.0.1 80 {
        weight 1
        HTTP_GET {
            url {
                path /internal/lb.ping
            }
            connect_timeout 3
            nb_get_retry 3
            delay_before_retry 3
        }
    }

}

cat /bitly/local/keepalived/conf/keepalived.dev_test2.conf

global_defs {
   notification_email {
     none
   }
   notification_email_from nobody
   router_id dev.bitly.org
}

vrrp_sync_group BITLY_VIPS {
    group {
        BITLY_FE
    }
}


vrrp_instance BITLY_FE {
    interface eth0
    virtual_router_id 250
    nopreempt
    state MASTER
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass xxxx
    }
    virtual_ipaddress {
        172.16.207.250/32 brd 172.16.207.255
    }
}


# dev test2
virtual_server 172.16.207.250 80 {
    delay_loop 6
    lb_algo sh
    lb_kind DR
    persistence_timeout 120
    protocol TCP

    # 127.0.0.1
    real_server 127.0.0.1 80 {
        weight 1
        HTTP_GET {
            url {
                path /internal/lb.ping
            }
            connect_timeout 3
            nb_get_retry 3
            delay_before_retry 3
        }
    }

}
```

**Comment by pqarmitage** [comment]
A couple of minor points with your configuration first:
1. On the vrrp instances, specifying state MASTER and nopreempt are mutually exclusive
2. Is it right to specify a broadcast address that is outside the address range of a configured sub-network? By that I mean that 172.16.207.255 does not lie in the 172.16.207.249/32 "network". I suspect the simplest solution to this is not to specify the broadcast address; I can't see any need for it.
3. vrrp_sync_groups with only 1 member are ignored.

I am able to reproduce the problem you describe, and will look into it. I'm not sure though that keepalived is designed to have multiple instances of it running simultaneously on one system, although at the moment other than having to specify different pid files, I can't see any reason why not. Certainly the design of keepalived is that everything can be specified in a single configuration file, and a single instance of keepalived can handle everything. It would be really helpful if you could explain your use case for having two separate instances of keepalived running in the same machine.

As you say, it appears that the second instance of keepalived removes the IPVS configuration set up by the first instance, but it does appear that the VRRP side, with the VIPs is functioning correctly and that the vrrp processes are not interfering with each other. If I start the two instances simultaneously then ipvsadm -L does show the two virtual servers, so it definitely does appear that a later instance starting up removes all of the earlier instances' configuration re IPVS.

**Comment by markrechler** [comment]
@pqarmitage appreciate the input.

Our reasoning for running multiple keepalived instances is for more isolation/to lessen the impact to production facing VIPs on config changes since reloading without downtime on the version we currently run `1.2.13` has issues (ie can't add a new VRRP/VIP with a HUP). Keeping everything in one config currently and having to restart for a VRRP/VIP addition would blip all of our endpoints.

**Comment by pqarmitage** [comment]
The above commit changes the behaviour of keepalived so that it will only flush the LVS configuration (i.e. remove any existing configuration) at startup if the global lvs_flush parameter is specified. The default configuration will now not flush the configuration, which is the behaviour wanted here.

**Comment by pqarmitage** [comment]
Thanks for the description of why running multiple instances is useful. You will probably find it beneficial to upgrade to keepalived v1.2.22 plus the latest commits, since that resolves some intermittent issues relating to reloading (see issue #365).

You should also find that keepalived v1.2.22 will allow adding additional VRRPs/VIPs on HUP reload. If you find that v1.2.22 doesn't handle reloading with additional VRRPs/VIPs in the way you want, then it would be really helpful if you could file a further issue report identifying what isn't working in the way you need.

**Comment by markrechler** [comment]
Thanks @pqarmitage! Will check out how things look with the new commit.

**Comment by markrechler** [comment]
Confirmed #372 fixed the issue. Thanks!
