### ISSUE TITLE
use_vmac do not work well

### ISSUE THREAD

**Issue by s09816** [acassen/keepalived#364]
in my evironment，when I config use_vmac，both two node go to master
when i do not config use_vmac, it can work well.

the version of keepalived is 1.2.7

global_defs {
	router_id ubuntu122
}

vrrp_script chk_tgtd {
	script "killall -0 tgtd"
	interval 2
	weight -100
	fall 2
	rise 2
}

vrrp_instance VI_25 {
	state MASTER----------> another node is BACKUP
	interface eth0
	virtual_router_id 25
	priority 240
	advert_int 1
        use_vmac
	authentication {
	auth_type PASS
	auth_pass 1111
	}
	track_script {
	chk_tgtd
	}
	virtual_ipaddress {
	192.168.33.127/24
	}
        notify_master /etc/keepalived/vmac_tweak.sh
        notify_backup /etc/keepalived/vmac_backup.sh
}

node1,node2 have the following vip
8: vrrp.25@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/ether 00:00:5e:00:01:19 brd ff:ff:ff:ff:ff:ff
    inet 192.168.33.127/24 scope global vrrp.25
       valid_lft forever preferred_lft forever
    inet6 fe80::200:5eff:fe00:119/64 scope link tentative dadfailed 
       valid_lft forever preferred_lft forever

**Comment by pqarmitage** [comment]
This probably relates to not setting the configuration on the physical and vmac interfaces. On the physical interface set:
arp_ignore=1
accept_local=1
rp_filter=0

On the vmac, set:
arp_ignore=1
arp_filter=1

For more details see https://github.com/acassen/keepalived/blob/master/doc/NOTE_vrrp_vmac.txt .

Current versions of keepalived adjust these settings for you. The version of keepalived you are running is very old, so you would probably be better off upgrading to keepalived ver 1.2.22 which will not only handle these settings for you, but also has many bug fixes and enancements compared to 1.2.7.

**Comment by s09816** [comment]
I config according https://github.com/acassen/keepalived/blob/master/doc/NOTE_vrrp_vmac.txt .
but It do not work, always two nodes go to master
1) Global configuration

	net.ipv4.conf.all.arp_ignore = 1
	net.ipv4.conf.all.arp_announce = 1
	net.ipv4.conf.all.arp_filter = 0
net.ipv4.conf.eth0.arp_filter = 1


net.ipv4.conf.vrrp.250.arp_filter = 0
net.ipv4.conf.vrrp.250.accept_local = 1 (this is needed for the address owner case)
net.ipv4.conf.vrrp.250.rp_filter = 0

**Comment by s09816** [comment]
i use vmware virtual machine  which install system ubuntu 14.04

**Comment by s09816** [comment]
the following is my configuration
root@ubuntu122:/# sysctl -p
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.all.arp_announce = 1
net.ipv4.conf.all.arp_filter = 0
net.ipv4.conf.eth0.arp_filter = 1



root@ubuntu122:/proc/sys/net/ipv4/conf/vrrp.25# cat arp_ignore 
1
root@ubuntu122:/proc/sys/net/ipv4/conf/vrrp.25# cat arp_filter 
0
root@ubuntu122:/proc/sys/net/ipv4/conf/vrrp.25# cat accept_local 
1
root@ubuntu122:/proc/sys/net/ipv4/conf/vrrp.25# cat rp_filter 
0
root@ubuntu122:/proc/sys/net/ipv4/conf/vrrp.

**Comment by pqarmitage** [comment]
Looking at vrrp_if_config.c, which now sets the relevant configuration, it sets:
/proc/sys/net/ipv4/conf/vrrp.25/arp_ignore = 1
/proc/sys/net/ipv4/conf/vrrp.25/accept_local = 1
/proc/sys/net/ipv4/conf/vrrp.25/rp_filter = 0
/proc/sys/net/ipv4/conf/vrrp.25/promote_secondaries =1     # this only relates to address deletion, so isn't part of your issue

and on the underlyinging interface:
/proc/sys/net/ipv4/conf/eth0.arp_ignore = 1
/proc/sys/net/ipv4/conf/eth0.arp_filter = 1

So the one difference on arp_filter on eth0.

Are you setting the interface parameters on the vrrp.25 interface from a script run by keepalived? If so, when is the script run, e.g. transition to master, transition to backup. If such a script is not being run, how are the interface parameters being set?
 
One thing I have noticed that is odd is that in your original message, vrrp.25 shows as state UNKNOWN, and also that dad failed on the link-local address, which suggests that there is something wrong with the vlan interface.

Is it possible for you to upgrade to keepalived v 1.2.22? IT may well solve your problems.

**Comment by mschneid** [comment]
@s09816 You mentioned that you run your setup in a VMware environment. In such a case ensure that you enabled the promiscuous mode on the virtual switch.

[Configuring promiscuous mode on a virtual switch or portgroup](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1004099)

**Comment by s09816** [comment]
the following is the log
log on one node2
Jun 23 21:40:07 ubuntu123 Keepalived[9821]: Stopping Keepalived v1.2.7 (03/24,2016)
Jun 23 21:40:07 ubuntu123 Keepalived_vrrp[9824]: VRRP_Instance(VI_25) sending 0 priority
Jun 23 21:40:07 ubuntu123 kernel: [57255.026003] device eth0 left promiscuous mode
Jun 23 21:40:08 ubuntu123 Keepalived[9844]: Starting Keepalived v1.2.7 (03/24,2016)
Jun 23 21:40:08 ubuntu123 Keepalived[9845]: Starting Healthcheck child process, pid=9846
Jun 23 21:40:08 ubuntu123 Keepalived[9845]: Starting VRRP child process, pid=9848
Jun 23 21:40:08 ubuntu123 Keepalived_healthcheckers[9846]: Initializing ipvs 2.6
Jun 23 21:40:08 ubuntu123 Keepalived_healthcheckers[9846]: Interface queue is empty
Jun 23 21:40:08 ubuntu123 Keepalived_healthcheckers[9846]: No such interface, eth1
Jun 23 21:40:08 ubuntu123 Keepalived_healthcheckers[9846]: Registering Kernel netlink reflector
Jun 23 21:40:08 ubuntu123 Keepalived_healthcheckers[9846]: Registering Kernel netlink command channel
Jun 23 21:40:08 ubuntu123 Keepalived_healthcheckers[9846]: Opening file '/etc/keepalived/keepalived.conf'.
Jun 23 21:40:08 ubuntu123 Keepalived_healthcheckers[9846]: Configuration is using : 5813 Bytes
Jun 23 21:40:08 ubuntu123 Keepalived_vrrp[9848]: Interface queue is empty
Jun 23 21:40:08 ubuntu123 Keepalived_vrrp[9848]: No such interface, eth1
Jun 23 21:40:08 ubuntu123 Keepalived_vrrp[9848]: Registering Kernel netlink reflector
Jun 23 21:40:08 ubuntu123 Keepalived_healthcheckers[9846]: Using LinkWatch kernel netlink reflector...
Jun 23 21:40:08 ubuntu123 Keepalived_vrrp[9848]: Registering Kernel netlink command channel
Jun 23 21:40:08 ubuntu123 Keepalived_vrrp[9848]: Registering gratuitous ARP shared channel
Jun 23 21:40:08 ubuntu123 Keepalived_vrrp[9848]: Initializing ipvs 2.6
Jun 23 21:40:08 ubuntu123 Keepalived_vrrp[9848]: Opening file '/etc/keepalived/keepalived.conf'.
Jun 23 21:40:08 ubuntu123 Keepalived_vrrp[9848]: vmac_ifname=vrrp.25 for vrrp_instace VI_25
Jun 23 21:40:08 ubuntu123 Keepalived_healthcheckers[9846]: Netlink: filter function error
Jun 23 21:40:08 ubuntu123 Keepalived_vrrp[9848]: No such interface, vrrp.25
Jun 23 21:40:08 ubuntu123 kernel: [57256.055673] device eth0 entered promiscuous mode
Jun 23 21:40:08 ubuntu123 Keepalived_vrrp[9848]: Configuration is using : 64140 Bytes
Jun 23 21:40:08 ubuntu123 Keepalived_vrrp[9848]: Using LinkWatch kernel netlink reflector...
Jun 23 21:40:08 ubuntu123 Keepalived_vrrp[9848]: VRRP_Instance(VI_25) Entering BACKUP STATE
Jun 23 21:40:08 ubuntu123 Keepalived_vrrp[9848]: VRRP_Script(chk_tgtd) succeeded
Jun 23 21:40:09 ubuntu123 kernel: [57256.610210] IPv6: vrrp.25: IPv6 duplicate address fe80::200:5eff:fe00:119 detected!
Jun 23 21:40:11 ubuntu123 ntpd[2764]: Deleting interface #11 vrrp.25, 192.168.33.127#123, interface stats: received=0, sent=0, dropped=0, active_time=56511 secs
Jun 23 21:40:11 ubuntu123 ntpd[2764]: peers refreshed
Jun 23 21:40:12 ubuntu123 Keepalived_vrrp[9848]: VRRP_Instance(VI_25) Transition to MASTER STATE
Jun 23 21:40:13 ubuntu123 Keepalived_vrrp[9848]: VRRP_Instance(VI_25) Entering MASTER STATE
Jun 23 21:40:13 ubuntu123 Keepalived_vrrp[9848]: Opening script file /etc/keepalived/vmac_tweak.sh
Jun 23 21:40:15 ubuntu123 ntpd[2764]: Listen normally on 12 vrrp.25 192.168.33.127 UDP 123
Jun 23 21:40:15 ubuntu123 ntpd[2764]: peers refreshed
Jun 23 21:40:15 ubuntu123 ntpd[2764]: new interface(s) found: waking up resolver

log on node1

Jun 23 21:41:43 ubuntu122 Keepalived[23254]: Stopping Keepalived v1.2.7 (03/24,2016)
Jun 23 21:41:44 ubuntu122 Keepalived[17953]: Starting Keepalived v1.2.7 (03/24,2016)
Jun 23 21:41:44 ubuntu122 Keepalived[17954]: Starting Healthcheck child process, pid=17956
Jun 23 21:41:44 ubuntu122 Keepalived[17954]: Starting VRRP child process, pid=17957
Jun 23 21:41:44 ubuntu122 Keepalived_vrrp[17957]: Interface queue is empty
Jun 23 21:41:44 ubuntu122 Keepalived_vrrp[17957]: No such interface, eth1
Jun 23 21:41:44 ubuntu122 Keepalived_vrrp[17957]: Registering Kernel netlink reflector
Jun 23 21:41:44 ubuntu122 Keepalived_vrrp[17957]: Registering Kernel netlink command channel
Jun 23 21:41:44 ubuntu122 Keepalived_vrrp[17957]: Registering gratuitous ARP shared channel
Jun 23 21:41:44 ubuntu122 Keepalived_vrrp[17957]: Initializing ipvs 2.6
Jun 23 21:41:44 ubuntu122 Keepalived_vrrp[17957]: Opening file '/etc/keepalived/keepalived.conf'.
Jun 23 21:41:44 ubuntu122 Keepalived_vrrp[17957]: vmac_ifname=vrrp.25 for vrrp_instace VI_25
Jun 23 21:41:44 ubuntu122 Keepalived_healthcheckers[17956]: Initializing ipvs 2.6
Jun 23 21:41:44 ubuntu122 Keepalived_healthcheckers[17956]: Interface queue is empty
Jun 23 21:41:44 ubuntu122 Keepalived_healthcheckers[17956]: No such interface, eth1
Jun 23 21:41:44 ubuntu122 Keepalived_healthcheckers[17956]: No such interface, vrrp.25
Jun 23 21:41:44 ubuntu122 kernel: [57362.408515] device eth0 entered promiscuous mode
Jun 23 21:41:44 ubuntu122 Keepalived_vrrp[17957]: No such interface, vrrp.25
Jun 23 21:41:44 ubuntu122 Keepalived_vrrp[17957]: Configuration is using : 64140 Bytes
Jun 23 21:41:44 ubuntu122 Keepalived_vrrp[17957]: Using LinkWatch kernel netlink reflector...
Jun 23 21:41:44 ubuntu122 Keepalived_healthcheckers[17956]: Registering Kernel netlink reflector
Jun 23 21:41:44 ubuntu122 Keepalived_healthcheckers[17956]: Registering Kernel netlink command channel
Jun 23 21:41:44 ubuntu122 Keepalived_healthcheckers[17956]: Opening file '/etc/keepalived/keepalived.conf'.
Jun 23 21:41:44 ubuntu122 Keepalived_healthcheckers[17956]: Configuration is using : 5933 Bytes
Jun 23 21:41:45 ubuntu122 Keepalived_healthcheckers[17956]: Using LinkWatch kernel netlink reflector...
Jun 23 21:41:45 ubuntu122 Keepalived_vrrp[17957]: VRRP_Script(chk_tgtd) succeeded
Jun 23 21:41:45 ubuntu122 Keepalived_vrrp[17957]: VRRP_Instance(VI_25) Transition to MASTER STATE
Jun 23 21:41:46 ubuntu122 Keepalived_vrrp[17957]: VRRP_Instance(VI_25) Entering MASTER STATE
Jun 23 21:41:46 ubuntu122 Keepalived_vrrp[17957]: Opening script file /etc/keepalived/vmac_tweak.sh
Jun 23 21:41:48 ubuntu122 ntpd[1868]: Listen normally on 13 vrrp.25 192.168.33.127 UDP 123
Jun 23 21:41:48 ubuntu122 ntpd[1868]: Listen normally on 14 vrrp.25 fe80::200:5eff:fe00:119 UDP 123
Jun 23 21:41:48 ubuntu122 ntpd[1868]: peers refreshed
Jun 23 21:41:48 ubuntu122 ntpd[1868]: new interface(s) found: waking up resolver

**Comment by s09816** [comment]
1.
vmac_tweak.sh
#!/bin/bash
echo "0" >/proc/sys/net/ipv4/conf/vrrp.25/arp_filter
echo "1" >/proc/sys/net/ipv4/conf/vrrp.25/accept_local
echo "0" >/proc/sys/net/ipv4/conf/vrrp.25/rp_filter

2.
root@ubuntu123:/etc/keepalived# sysctl -p
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.all.arp_announce = 1
net.ipv4.conf.all.arp_filter = 0
net.ipv4.conf.eth0.arp_filter = 1

3.
global_defs {
        router_id ubuntu123
}

vrrp_script chk_tgtd {
        script "killall -0 tgtd"
        interval 2
        weight -100
        fall 2
        rise 2
}

vrrp_instance VI_25 {
        state BACKUP
        interface eth0
        virtual_router_id 25
        priority 139
        advert_int 1
        use_vmac
        authentication {
        auth_type PASS
        auth_pass 1111
        }
        track_script {
        chk_tgtd
        }
        virtual_ipaddress {
        192.168.33.127/24
        }
        notify_master /etc/keepalived/vmac_tweak.sh
}

**Comment by s09816** [comment]
@mschneid  I have configured promiscuous mod

**Comment by pqarmitage** [comment]
It would appear that both systems are using the same MAC address. This then causes a duplicate IPv6 link local address. This may be a cause of the problem.

Node1 is also repoprting "No such interface vrrp.25"  which could be a problem.
