### ISSUE TITLE
1.2.22, reload & vrrp scripts

### ISSUE THREAD

**Issue by bpaquet** [acassen/keepalived#366]
Hi,

We have a big problem with keepalived 1.2.20 and 1.2.22. Works fine in 1.2.13.

When we reload with 1.2.20 or 1.2.22, (send HUP signal), keepalived seems to have problem to handle VRRP Scripts.

For example, before reload, our server announce 150, after the reload, and waiting few seconds, the server announce 126, due to some vrrp scripts in timeout. Not other changes on the server are done during the reload (vrrp scripts should have the same result after and before).

You can find our [config](https://github.com/acassen/keepalived/files/328707/keepalived.conf.txt), and keepalived log below (you can show scripts timeout). Adding timeout in vrrp_script section does not change anything.

Any idea of what happen ?

Jun 22 10:30:27 cache00 Keepalived_healthcheckers[12382]: Got SIGHUP, reloading checker configuration
Jun 22 10:30:27 cache00 Keepalived_healthcheckers[12382]: Initializing ipvs 2.6
Jun 22 10:30:27 cache00 Keepalived_healthcheckers[12382]: Registering Kernel netlink reflector
Jun 22 10:30:27 cache00 Keepalived_healthcheckers[12382]: Registering Kernel netlink command channel
Jun 22 10:30:27 cache00 Keepalived_healthcheckers[12382]: Opening file '/etc/keepalived/keepalived.conf'.
Jun 22 10:30:27 cache00 Keepalived_healthcheckers[12382]: Using LinkWatch kernel netlink reflector...
Jun 22 10:30:27 cache00 keepalived[12488]: Reloading keepalived configuration.......
Jun 22 10:30:28 cache00 Keepalived_vrrp[12383]: VRRP_Instance(vip_cache) Transition to MASTER STATE
Jun 22 10:30:29 cache00 Keepalived_vrrp[12383]: VRRP_Script(unpromote_vip_cache) timed out
Jun 22 10:30:29 cache00 Keepalived_vrrp[12383]: VRRP_Script(tcp_vip_cache_6379) timed out
Jun 22 10:30:29 cache00 Keepalived_vrrp[12383]: VRRP_Instance(vip_cache) Entering MASTER STATE
Jun 22 10:30:29 cache00 Keepalived_vrrp[12383]: Opening script file /usr/local/bin/keepalived_logger
Jun 22 10:30:29 cache00 Keepalived_vrrp[12383]: VRRP_Instance(vip_cache) Effective priority = 126
Jun 22 10:30:29 cache00 Keepalived_vrrp: INSTANCE vip_cache MASTER 150

**Comment by pqarmitage** [comment]
While investigating issue #365 I found two issues of potential memory corruption when reloading. One of those issues relates to scripts, and how the completion of scripts being run may be missed after a reload.

Could you please try keepalived from git commit 6de660e to see if this resolves your problem.

**Comment by bpaquet** [comment]
Yes, it seems to be fixed !

Very good news.

Is a new release planned ?

**Comment by pqarmitage** [comment]
v1.2.23 has since been released which contains the fixes.

If everything is now resolved, it would be helpful if you could now close the issue.
