### ISSUE TITLE
reload fail to add static ipaddress

### ISSUE THREAD

**Issue by ze42** [acassen/keepalived#377]
Hello,

With a simple configuration, reloading keepalived fails to bring up an IP in `static_address` block.

```
static_ipaddress {
        10.0.0.1/32 dev dummy0
        10.0.0.2/32 dev dummy0
}
```

Starting keepalived, I correctly have both IP showing.

```
static_ipaddress {
        10.0.0.1/32 dev dummy0
}
```

Reloading, `10.0.0.2` properly disappear.

```
static_ipaddress {
        10.0.0.1/32 dev dummy0
        10.0.0.3/32 dev dummy0
}
```

Reloading, `10.0.0.3` fails to appear.

Tested with `v1.2.20` and `v1.2.22`.

Worked fine in `v1.2.13`.

Reload not working would break our production, and prevent us from pushing those latest release in further tests and production.

**Comment by pqarmitage** [comment]
Some issues with reloading were recently reported and fixed. Please pull the latest code from git. It should resolve your problems.

It would be very helpful if you could report if this does fix your problems; if not we will investigate further.

**Comment by ze42** [comment]
Just got it packaged, and tested. Still having the same buggy behavior.

**Comment by pqarmitage** [comment]
I love your simple configuration. It made it really easy to find the problem!

The patch in pull request #378 should resolve your issue.

**Comment by ze42** [comment]
Yeah, simple configuration also help reproduce it, and provide something without disclosing our huge configurations.

We built a package including the mentioned PR, it does fix that behavior.

Seems it is now already merged, closing the issue.

Thanks
