### ISSUE TITLE
about lvs's configuration in keepalived.conf 

### ISSUE THREAD

**Issue by s09816** [acassen/keepalived#380]
the keepalived.conf of  node1 

global_defs {
        router_id ubuntu122
}

vrrp_script chk_tgtd {
        script "killall -0 tgtd"
        interval 2
        weight 0
        fall 2
        rise 2
}

vrrp_script chk_radosgw {
        script "killall -0 radosgw"
        interval 2
        weight 0
        fall 2
        rise 2
}

vrrp_instance VI_13 {
        state BACKUP
        interface eth0
        virtual_router_id 13
        priority 240
        nopreempt
        advert_int 1
        authentication {
        auth_type PASS
        auth_pass 1111
        }
        lvs_sync_daemon_interface eth0
        virtual_ipaddress {
        192.168.33.126/24
        }
}
#end vrrp_instance VI_13

virtual_server 192.168.33.126 3260 {
        delay_loop 2
        lb_algo wlc
        lb_kind DR
        persistence_timeout 30
        protocol TCP

        real_server 192.168.33.123 3260 {
        weight 1
        TCP_CHECK {
        connect_port 3260
        bindto 192.168.33.122
        connect_timeout 3
        }
        }
        #end real_server 192.168.33.123 3260

        real_server 192.168.33.122 3260 {
        weight 1
        TCP_CHECK {
        connect_port 3260
        bindto 192.168.33.122
        connect_timeout 3
        }
        }
        #end real_server 192.168.33.122 3260

        real_server 192.168.33.124 3260 {
        weight 1
        TCP_CHECK {
        connect_port 3260
        bindto 192.168.33.122
        connect_timeout 3
        }
        }
        #end real_server 192.168.33.124 3260
}
#end virtual_server 192.168.33.126 3260

vrrp_instance VI_5 {
        state BACKUP
        interface eth0
        virtual_router_id 5
        priority 239
        nopreempt
        advert_int 1
        authentication {
        auth_type PASS
        auth_pass 1111
        }
        lvs_sync_daemon_interface eth0
        virtual_ipaddress {
        192.168.33.127/24
        }
}
#end vrrp_instance VI_5

virtual_server 192.168.33.127 3260 {
        delay_loop 2
        lb_algo wlc
        lb_kind DR
        persistence_timeout 30
        protocol TCP

        real_server 192.168.33.123 3260 {
        weight 1
        TCP_CHECK {
        connect_port 3260
        bindto 192.168.33.122
        connect_timeout 3
        }
        }
        #end real_server 192.168.33.123 3260

        real_server 192.168.33.122 3260 {
        weight 1
        TCP_CHECK {
        connect_port 3260
        bindto 192.168.33.122
        connect_timeout 3
        }
        }
        #end real_server 192.168.33.122 3260

        real_server 192.168.33.124 3260 {
        weight 1
        TCP_CHECK {
        connect_port 3260
        bindto 192.168.33.122
        connect_timeout 3
        }
        }
        #end real_server 192.168.33.124 3260
}
#end virtual_server 192.168.33.127 3260

**Comment by s09816** [comment]
the keepalived.conf of node2

global_defs {
        router_id ubuntu123
}

vrrp_script chk_tgtd {
        script "killall -0 tgtd"
        interval 2
        weight 0
        fall 2
        rise 2
}

vrrp_script chk_radosgw {
        script "killall -0 radosgw"
        interval 2
        weight 0
        fall 2
        rise 2
}

vrrp_instance VI_13 {
        state BACKUP
        interface eth0
        virtual_router_id 13
        priority 239
        nopreempt
        advert_int 1
        authentication {
        auth_type PASS
        auth_pass 1111
        }
        notify_master " /var/lib/ceph/shell/ha_notify.sh master 192.168.33.126 13 3260 00:0c:29:12:a6:53 "
        notify_backup " /var/lib/ceph/shell/ha_notify.sh backup 192.168.33.126 13 3260 00:0c:29:12:a6:53 "
        lvs_sync_daemon_interface eth0
        virtual_ipaddress {
        192.168.33.126/24
        }
}
#end vrrp_instance VI_13

virtual_server fwmark 13 {
        delay_loop 2
        lb_algo wlc
        lb_kind DR
        persistence_timeout 30
        protocol TCP

        real_server 192.168.33.123 3260 {
        weight 1
        TCP_CHECK {
        connect_port 3260
        bindto 192.168.33.123
        connect_timeout 3
        }
        }
        #end real_server 192.168.33.123 3260

        real_server 192.168.33.122 3260 {
        weight 1
        TCP_CHECK {
        connect_port 3260
        bindto 192.168.33.123
        connect_timeout 3
        }
        }
        #end real_server 192.168.33.122 3260

        real_server 192.168.33.124 3260 {
        weight 1
        TCP_CHECK {
        connect_port 3260
        bindto 192.168.33.123
        connect_timeout 3
        }
        }
        #end real_server 192.168.33.124 3260
}
#end virtual_server fwmark 13

vrrp_instance VI_5 {
        state BACKUP
        interface eth0
        virtual_router_id 5
        priority 239
        nopreempt
        advert_int 1
        authentication {
        auth_type PASS
        auth_pass 1111
        }
        notify_master " /var/lib/ceph/shell/ha_notify.sh master 192.168.33.127 5 3260 00:0c:29:12:a6:53 "
        notify_backup " /var/lib/ceph/shell/ha_notify.sh backup 192.168.33.127 5 3260 00:0c:29:12:a6:53 "
        lvs_sync_daemon_interface eth0
        virtual_ipaddress {
        192.168.33.127/24
        }
}
#end vrrp_instance VI_5

virtual_server fwmark 5 {
        delay_loop 2
        lb_algo wlc
        lb_kind DR
        persistence_timeout 30
        protocol TCP

        real_server 192.168.33.123 3260 {
        weight 1
        TCP_CHECK {
        connect_port 3260
        bindto 192.168.33.123
        connect_timeout 3
        }
        }
        #end real_server 192.168.33.123 3260

        real_server 192.168.33.122 3260 {
        weight 1
        TCP_CHECK {
        connect_port 3260
        bindto 192.168.33.123
        connect_timeout 3
        }
        }
        #end real_server 192.168.33.122 3260

        real_server 192.168.33.124 3260 {
        weight 1
        TCP_CHECK {
        connect_port 3260
        bindto 192.168.33.123
        connect_timeout 3
        }
        }
        #end real_server 192.168.33.124 3260
}
#end virtual_server fwmark 5

**Comment by s09816** [comment]
i want to know if the config will be effective. There will be two lvs service 

node1    node2 

master    backup   192.168.33.126

backup  master     192.168.33.127

**Comment by pqarmitage** [comment]
Have issues #364 and #368 been resolved yet? If so, you you please close those issues.

What version of keepalived are you now running?

**Comment by pqarmitage** [comment]
There can only be one lvs_sync_daemon per system (in order to have multiple sync daemons, with potentially some in master state and some in backup state it would be necessary to specify a sync_id against each real server, and there is no configuration option for that (see the `ipvsadm` command)).

You appear to have configured the real servers within the vrrp_instance blocks. That isn't how it works; the real_server blocks need to be at the same outer level as the vrrp instances.

The configuration of lvs_sync_daemon_interface against a vrrp instance is deprecated in recent versions of keepalived (since it is confusing); use the global lvs_sync_daemon option instead.
