### ISSUE TITLE
port by service name very badly handled

### ISSUE THREAD

**Issue by ze42** [acassen/keepalived#391]
Hello,

I just loadbalance a service using the service port by name instead of the number. (letting it search in /etc/services, ...).

  * It loaded "properly"
  * Healthcheck are logged as starting correctly (with port number)
  * Real healthcheck is done to port 0
  * It never can remove the entry from ipvsadm (reload, stop, restrat, nothing would find and remove it)

Version used: somewhere between 1.2.22 and 1.2.23

Sorry, didn't get time to get a more detailed report today.

**Comment by acassen** [comment]
there is not enough infos here to open a truly valuable issue discussion. Please provide more infos, I am closing this issue cause we just can find a way to investigate...

**Comment by pqarmitage** [comment]
@ze42 Is what you are saying is that you tried configuration that looked like:
virtual_server 10.0.0.1 http {
   ...
   real_server 10.0.1.1 http {
       ...
    }
}

rather than
virtual_server 10.0.0.1 80 {
   ...
   real_server 10.0.1.1 80 {
       ...
    }
}

If so, this isn't supported. The third parameter to both virtual_server and real_server is read as an integer, using atoi(), which will return 0 for a non-numeric string. It is valid to specify a virtual server with port 0, and so the virtual server is added, but it is not valid to specify a real server with port 0, and so adding the real servers fails.

I don't have any problem with the servers being removed.

**Comment by ze42** [comment]
Hello.

Sorry for the light bug report, opened it a friday evening, planning to update it on monday, but already got closed by that time, so I didn't bother to recheck further till now.


After checking further, my tests were using service name on `connect_port` for `tcp_check`, but I'd get the same behavior with VS and RS as mentioned.


You mention that having a VS with port 0 is valid... may I ask what purpose that might have, and an example wher that would be used?



As for the `atoi`, unfortunately, it doesn't allow to detect errors in configuration files. I'd much rather have an error when trying to load a configuration with unrecognized/bad values (text where number is expected) rather than silently ignored and converted to zero.

I'd advice to either check the string is fully numeric before running `atoi`, or move to `strtol` and check it properly used the whole argument.

**Comment by pqarmitage** [comment]
Thanks for the update.

A virtual server with port 0 would be equivalent to using a command like `ipvsadm -A -t 10.0.0.1 -s rr --persistent`.

I fully agree that `atoi` should be avoided, and that `strtol` is a better solution. At the moment the config parser will correctly parse valid configuration, but it is not good at handling (or reporting) invalid configuration, and it needs a considerable amount of work.

You also mentioned in your initial report:
It never can remove the entry from ipvsadm (reload, stop, restrat, nothing would find and remove it)
Could you please explain what couldn't be removed, and what entry in the configuration file caused the problem.

**Comment by ze42** [comment]
Oh yeah. And after trying again, I got trouble figuring out what was the problem... :)

Found 2 cases of bad behaviours.

## bad everlasting entry

  * Get a configuration (see `config0` below) with everything placed as named...
  * Load it
  * Wait for the checks to fail
  * Replace with port numbers (see `config1` below)
  * reload

Server with the bad port number (0) stays in memory, and a stop won't remove it.

Not sure if it is really related to VSG port being 0 or not.

```text
# config0
static_ipaddress {
        10.0.0.1/32 dev dummy0
}
virtual_server_group vsg0 {
        10.0.0.1 ldaps
}
virtual_server group vsg0 {
        delay_loop 5
        lb_algo wrr
        lb_kind DR
        protocol TCP
        real_server 10.0.1.1 ldaps {
                weight 1
                TCP_CHECK {
                  connect_port ldaps
                  connect_timeout 5
                  nb_get_retry 1
                  delay_before_retry 0
                }
        }
        real_server 10.0.1.2 ldaps {
                weight 1
                TCP_CHECK {
                  connect_port ldaps
                  connect_timeout 5
                  nb_get_retry 1
                  delay_before_retry 0
                }
        }
}
```

```text
# config1
static_ipaddress {
        10.0.0.1/32 dev dummy0
}
virtual_server_group vsg0 {
        10.0.0.1 636
}
virtual_server group vsg0 {
        delay_loop 5
        lb_algo wrr
        lb_kind DR
        protocol TCP
        real_server 10.0.1.1 636 {
                weight 1
                TCP_CHECK {
                  connect_port 636
                  connect_timeout 5
                  nb_get_retry 1
                  delay_before_retry 0
                }
        }
        real_server 10.0.1.2 636 {
                weight 1
                TCP_CHECK {
                  connect_port 636
                  connect_timeout 5
                  nb_get_retry 1
                  delay_before_retry 0
                }
        }
}
```


## Fails to insert failed server, when check removed

  * Configured two servers with healthcheck
  * Check fails
  * Remove 1 server from config, and remove health check from the other (no real need of check as only one server)
  * Reload
  * Server won't be checked anymore, and not restored either

Probably work with a single server that fails, and reload with healthcheck removed.
