### ISSUE TITLE
invoke over one lvs_sync_daemon isn't work for keepalived 1.2.23

### ISSUE THREAD

**Issue by zhongguanqun** [acassen/keepalived#396]
I'm studying the mode of master to master,  master 1 has VIP1, master 2 has VIP2, backup 1 is with master 2 together, backup 2 is with master 1 together, so I have the following configurtation block:

! Configuration File for keepalived
global_defs {
   notification_email {
     xx@yy.com
   }
   notification_email_from keepalived@yy.com
   smtp_server 127.0.0.1
   smtp_connect_timeout 5
   router_id ri1

   lvs_sync_daemon eth0 VI_1 1
   lvs_sync_daemon eth0 VI_2 2

}
include conf/*.conf

the other configuration is the same expext route_id ri2, however, in fact, only V1_1 will be started, VI_2 won't. I wanna to asure whether the way of the config block is acheive?

**Comment by pqarmitage** [comment]
This configuration will not work in the way you want.

There can be only one lvs sync daemon running in a system at any one time, and keepalived should report an error if you attempt to configure a second one.

Although the syntax you have specified will be recognised, it is preferred to add `id` before the syncid, e.g. lvs_sync_daemon eth0  VI_1 id 1

Without seeing the configuration for the vrrp instances, it's not possible to comment on them, but I'm not sure what you mean by VI_2 won't be started.
