### ISSUE TITLE
DBus integration

### ISSUE THREAD

**Issue by lzmartinico** [acassen/keepalived#398]
I have been working on adding a DBus service to VRRP. This could be used an alternative to using signals. As of now both user signals in VRRP are in use (for printing data and stats), so moving over to DBus would allow the addition of new functionality. Would you be interested in having this feature pushed upstream?

**Comment by pqarmitage** [comment]
I would certainly be very interested in seeing this. Could you submit a pull request to https://github.compqarmitage/keepalived so I can have a look at it.

Many thanks.

**Comment by acassen** [comment]
this is a nice idea but not really an issue :D so I am closing the issue if you dont mind.
