### ISSUE TITLE
VRRP using multiple interfaces to avoid split brain

### ISSUE THREAD

**Issue by postol** [acassen/keepalived#408]
Hi,

first I would like to thank you for an excellent project. We would like to start using keepalived for our HA setup using the VIP failover. The one thing we are missing or don't understand how one can avoid split brain situation in case the network between VRRP instances stop working. Because we know it is sort of essential to have this link always up and running and that there should be a dedicated network cards and crossover cable between the boxes for such communication we still think it would be nice if one can set up multiple interfaces which will be used for VRRP communication between instances so in case one network link/interface goes down the next one (basically backup) will be used ... is something like this already possible and if not would it be difficult to add such functionality?

Also a more general question - is there some configuration example how to best avoid split brain? With some techniques like STONITH etc.? If not can you provide us some best practices?

Thank you.

Petr

**Comment by pqarmitage** [comment]
This question would be more appropriate on the mailing list keepalived-devel@lists.sourcefore.net. I will answer this here, but if you want to follow it up, could you please post the original messages and your follow-up on the list.

The best way to avoid split-brain, or at least to minimise the impact, is NOT to use a dedicated link for the VRRP communication, but for the VRRP communication to use the same network interfaces that keepalived will add the virtual IP addresses to. In terms of how to configure this, ensure that you don't have any `dev` keywords in the `virtual_ipaddress` and `virtual_ipaddress_excluded` blocks.

If the VRRP instances can't see each other over the interfaces they are operating on, then presumably no other host on the same sub-network can see both of the instances, and so no-one will see more than one instance of the virtual router.

If you use a separate interface for the VRRP traffic, there is a risk that the routing interface on the master router may become isolated from the rest of the network, but the backup will still see the master on the separate interface and hence won't take over as master.

So the overall most reliable way is for the routers to multicast VRRP traffic over the interface that the virtual router is on, which is as described in the RFCs.

If you really want to have multiple routes for the VRRP traffic, you could configure unicast peers, and then install alternative routes for that traffic between the systems.

How to best configure it depends on what you are trying to achieve.
