### ISSUE TITLE
centos7 tokeepalived-1.2.23 OpenSSL 1.1.0

### ISSUE THREAD

**Issue by qist** [acassen/keepalived#417]
make[2]: Leaving directory `/tmp/keepalived-1.2.23/keepalived/libipvs-2.6'
Building ../bin/keepalived
check/check_ssl.o: In function `build_ssl_ctx':
/tmp/keepalived-1.2.23/keepalived/check/check_ssl.c:68: undefined reference to `OPENSSL_init_ssl'
/tmp/keepalived-1.2.23/keepalived/check/check_ssl.c:70: undefined reference to `OPENSSL_init_ssl'
/tmp/keepalived-1.2.23/keepalived/check/check_ssl.c:79: undefined reference to `TLS_method'
collect2: error: ld returned 1 exit status
make[1]: *** [all] Error 1
make[1]: Leaving directory `/tmp/keepalived-1.2.23/keepalived'
make: *** [all] Error 2

**Comment by pqarmitage** [comment]
Thanks for the heads up on this.

keepalived builds without a problem on my Centos 7 system, but that is using openSSL version 1.0.1e. On another system it also builds against 1.0.2h, so this appears to be an issue with version 1.1.0.

Did you build openSSL yourself? If so, could you add the details here of how you built it (e.g. an rpm .spec file would be helpful). If you didn't build it yourself, could you provide a link where you downloaded it from.

Once I can get openSSL installed, I will have a look at what needs changing to support this new version of openSSL.

**Comment by pqarmitage** [comment]
It appears that although you are compiling with the new header files, you are not linking with the new libraries.
I have built openssl 1.1.0 with
```
./config --prefix=$HOME/openssl
make
make install
```
and then I patched configure.ac with the following patch
```
diff --git a/configure.ac b/configure.ac
index 8ccb229..73668cb 100644
--- a/configure.ac
+++ b/configure.ac
@@ -135,7 +135,7 @@ AM_PROG_AR
 ARFLAGS=cr
 AC_SUBST(ARFLAGS)

-KA_CPPFLAGS="$kernelinc"
+KA_CPPFLAGS="$kernelinc -I ~/openssl/include"
 KA_CFLAGS="-Wall -Wunused -Wstrict-prototypes"
 KA_LDFLAGS=
 KA_LIBS="-ldl"
@@ -253,7 +253,7 @@ AC_CHECK_LIB(ssl, SSL_CTX_new, [],
     fi
     BUILD_GENHASH=No
   ])
-add_to_var([KA_LIBS], [$LIBS])
+add_to_var([KA_LIBS], [-L ~/openssl/lib $LIBS])

 if test $BUILD_GENHASH = Yes; then
   GENHASH_LIBS=
```
and it builds without a problem. If I don't add -L ~/openssl/lib to KA_LIBS then I get the same error as you.

**Comment by qist** [comment]
I have resolved this question ,thanks.
