### ISSUE TITLE
realease 1.2.24 '$make' on centos 6.5 errors 

### ISSUE THREAD

**Issue by mjrao** [acassen/keepalived#419]
run $make on  my centos 6.5 have  an error occurred!

I had install automake 1.11 on my centos.

`[keepalived@hadoop148 keepalived-1.2.24]$ make
CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.15 
/bin/sh: aclocal-1.15: command not found
make: *** [aclocal.m4] Error 127
`
 upgrade my automake 1.15 ???

**Comment by acassen** [comment]
please run followinf command in your keepalived directory, as explained in INSTALL file.
aclocal && autoheader && automake --add-missing && autoreconf

**Comment by mjrao** [comment]
thanks. I tried it, and  it‘s work well !   Bless you
