### ISSUE TITLE
Compiling RPM for 1.2.24 version

### ISSUE THREAD

**Issue by stylobille** [acassen/keepalived#422]
Hello people,

I have some issues generating a RPM for keepalived 1.2.24 which I didn't have for the 1.2.23 version.

I'm facing this issue with RHEL6 and RHEL7.

Here is what I have when compiling 1.2.24 keepalived : 

```
Keepalived configuration
------------------------
Keepalived version       : 1.2.24
Compiler                 : gcc
Preprocessor flags       : -I/lib/modules/2.6.32-642.4.2.el6/build/include
Compiler flags           : -Wall -Wunused -Wstrict-prototypes
Linker flags             :
Extra Lib                : -ldl -lssl -lcrypto
Use IPVS Framework       : Yes
IPVS use libnl           : No
IPVS syncd attributes    : No
IPVS 64 bit stats        : No
fwmark socket support    : Yes
Use VRRP Framework       : Yes
Use VRRP VMAC            : Yes
Use VRRP authentication  : Yes
With ip rules/routes     : Yes
SNMP keepalived support  : No
SNMP checker support     : No
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
SHA1 support             : No
Use Debug flags          : No
Stacktrace support       : No
Memory alloc check       : No
libnl version            : None
Use IPv4 devconf         : No
Use libiptc              : No
Use libipset             : No
Build genhash            : Yes
Build documentation      : No
```

And it ends with this error : 

```
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.kcuqmD
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd keepalived-1.2.24
+ unset DISPLAY
+ grep -q 'IPVS_SUPPORT='\''_WITH_LVS_'\''' config.log
+ echo 'ERROR: We do not want keeepalived lacking LVS support.'
ERROR: We do not want keeepalived lacking LVS support.
+ exit 1
error: Bad exit status from /var/tmp/rpm-tmp.kcuqmD (%check)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.kcuqmD (%check)
```

So apparently version 1.2.24 adds this in the configuration menu : 

```
IPVS use libnl           : No
IPVS syncd attributes    : No
IPVS 64 bit stats        : No
```

So what I thought is, I should add libnl-devel package to my system then it should compile with it and I'm good to go.

Sadly when adding libnl-devel package I get this error : 

```
checking for nl_socket_alloc in -lnl-3... no
checking for nl_socket_modify_cb in -lnl... yes
checking libnfnetlink/libnfnetlink.h usability... no
checking libnfnetlink/libnfnetlink.h presence... no
checking for libnfnetlink/libnfnetlink.h... no
configure: error:
    !!! Please install libnfnetlink headers.              !!!
error: Bad exit status from /var/tmp/rpm-tmp.iPnNkB (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.iPnNkB (%build)

```

I looked for other packages called libnl in the RHEL6 and 7 repository, but there is nothing else.
So my main question is, what should I do to be able to make a RPM for keepalived 1.2.24 ?

Earlier with keepalived 1.2.23 my configuration resume looked like this : 

```
Keepalived configuration
------------------------
Keepalived version       : 1.2.23
Compiler                 : gcc
Compiler flags           : -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic
Extra Lib                : -lssl -lcrypto -lcrypt
Use IPVS Framework       : Yes
IPVS sync daemon support : Yes
IPVS use libnl           : No
fwmark socket support    : Yes
Use VRRP Framework       : Yes
Use VRRP VMAC            : Yes
Use VRRP authentication  : Yes
SNMP keepalived support  : No
SNMP checker support     : No
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
SHA1 support             : No
Use Debug flags          : No
Memory alloc check       : No
libnl version            : None
Use IPv4 devconf         : No
Use libiptc              : No
Use libipset             : No
```

And this went perfectly well. I'm using the spec file provided by the installation tarball and i'm just changing the version inside it before running the rpmbuild command, nothing else.

Any help is greatly appreciated :)

**Comment by pqarmitage** [comment]
Can you install libnfnetlink-devel? You should also install libnl3-devel
if it is available.

**Comment by stylobille** [comment]
Bah... that one is on me, I looked for libnl* and not libnf* that's why I didn't find it, so it works indead much better with the correct package, but it still hangs on the LVS support.

```
Keepalived configuration
------------------------
Keepalived version       : 1.2.24
Compiler                 : gcc
Preprocessor flags       : -I/lib/modules/2.6.32-642.4.2.el6/build/include -I/usr/include/libnl3
Compiler flags           : -Wall -Wunused -Wstrict-prototypes
Linker flags             :
Extra Lib                : -ldl -lssl -lcrypto  -lnl-genl-3 -lnl-3 -lnl-route-3
Use IPVS Framework       : Yes
IPVS use libnl           : Yes
IPVS syncd attributes    : No
IPVS 64 bit stats        : No
fwmark socket support    : Yes
Use VRRP Framework       : Yes
Use VRRP VMAC            : Yes
Use VRRP authentication  : Yes
With ip rules/routes     : Yes
SNMP keepalived support  : No
SNMP checker support     : No
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
SHA1 support             : No
Use Debug flags          : No
Stacktrace support       : No
Memory alloc check       : No
libnl version            : 3
Use IPv4 devconf         : No
Use libiptc              : No
Use libipset             : No
Build genhash            : Yes
Build documentation      : No
```

```
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.Nbc4w4
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd keepalived-1.2.24
+ unset DISPLAY
+ grep -q 'IPVS_SUPPORT='\''_WITH_LVS_'\''' config.log
+ echo 'ERROR: We do not want keeepalived lacking LVS support.'
ERROR: We do not want keeepalived lacking LVS support.
+ exit 1
error: Bad exit status from /var/tmp/rpm-tmp.Nbc4w4 (%check)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Nbc4w4 (%check)
```

**Comment by pqarmitage** [comment]
That error message looks to me as though it is generated from your
keepalived.spec file.

Since keepalived 1.2.24 now uses automake, the location and contents of
some of the files generated by configure are now different, and that
appears to be your problem.

In the .spec file, you have something like:
grep -q IPVS_SUPPORT=\''_WITH_LVS_\'' config.log
if [[ $? -ne 0 ]]; then
    echo 'ERROR: We do not want keeepalived lacking LVS support.'
    exit 1
fi

(btw keepalived does not have a triple 'e' after the 'k'!)

config.log no longer contains such a line. Instead you want to search
for something like:
| #define _WITH_LVS_  1 
                                     ^^^^
                                     Two spaces here, so use "#define
_WITH_LVS_  *1"

Also you will get better performance from keepalived if you install
libiptc-devel and libipset-devel if you are not using accept mode.

**Comment by stylobille** [comment]
Ok, that's indeed the problem here, well seen !

I simply took the spec.in file provided with the tar.bz file because I expected it too be valid for this version, so maybe there are other issues with that file...

I just changed what you pointed out and now it ends with this error : 

```
error: Installed (but unpackaged) file(s) found:
   /usr/lib/systemd/system/keepalived.service


RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/lib/systemd/system/keepalived.service
```

Do you have a link to a correct spec file from which I could start maybe ?

**Comment by pqarmitage** [comment]
I've push an updated keepalived.spec.in that now build keepalived.in to match the configure parameters. This should resolve the Installed (but unpacked) errors above.

**Comment by stylobille** [comment]
Great and i've seen you added support for systemd too, thanks !

There is small problem though when I try to create a RPM with the news spec file : 

error: line 19: Unknown tag: @LIBIPTC_TRUE@BuildRequires: iptables-devel

(iptables-devel is an installed package on my system)

**Comment by pqarmitage** [comment]
That's strange since it works for me.

Do you have a line in config.stats like `S["LIBIPTC_TRUE"]=""`?

In configure (not configure.ac) do you have a block:
```
if test $USE_LIBIPTC = Yes; then
    LIBIPTC_TRUE=
    LIBIPTC_FALSE='#'
else
    LIBIPTC_TRUE='#'
    LIBIPTC_FALSE=
fi
```

If you run `bash -x ./configure YOUR_CONFIG_OPTS >/tmp/conf.log 2>&1`, do you have line in /tmp/conf.log like `LIBIPTC_TRUE=` and `LIBIPTC_FALSE='#'`?

**Comment by stylobille** [comment]
Basically i've downloaded the zip file from git, convered it into a tar.gz and the only command i'm running is rpmbuild -ba ~/rpmbuild/SPECS/keepalived.spec.in (after having changed the version in the spec file of course and having put the tar.gz in the SOURCES folder).

So in configure yes i has the following block : 

```
 if test $USE_LIBIPTC = Yes; then
  LIBIPTC_TRUE=
  LIBIPTC_FALSE='#'
else
  LIBIPTC_TRUE='#'
  LIBIPTC_FALSE=
fi
```

I do not have a config.stats file (or I don't know where to look, but I'm not sure rpmbuild creates one).

if I run configure (with no options) i do have a line with `LIBIPTC_TRUE=` followed by a line with `LIBIPTC_FALSE='#'` in the log file.

Thanks for the help this far.

**Comment by pqarmitage** [comment]
When you run configure, it generates a `keepalived.spec` file, generated from `keepalived.spec.in` and based on whatever options were chosen for configure. It is the keepalived.spec file that you should be using for rpmbuild, and it will have been updated to include the version etc. All the @...TRUE@ string will have been removed from keepalived.spec.

**Comment by stylobille** [comment]
Ok my bad I didn't know that, thanks again for the tip !

So now I have a new problem after having created the spec file with configure : 
```

+ /usr/bin/make -j3 STRIP=/bin/true
CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.15
/bin/sh: aclocal-1.15: command not found
make: *** [aclocal.m4] Error 127
error: Bad exit status from /var/tmp/rpm-tmp.U1Hhy3 (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.U1Hhy3 (%build)
```

This comes probably due to the fact that the automake in RHEL 7.2 provides aclocal-1.13 and not aclocal-1.15. on RHEL6.8 it's aclocal-1.11 that is provided.

**Comment by pqarmitage** [comment]
You probably need to follow the instructions in INSTALL under "Modifying source code", i.e. `aclocal; autoheader; automake --add-missing; autoreconf`. After running all that lot, then generate the tarball.

Alternatively, checkout all the files from git again and run `find . -exec touch -r configure {} +`, and then create the tarball. This will adjust the timestamps and stop configure trying to rebuild its own files.

I'm sorry this isn't explained very well, but since the keepalived.spec.in file hadn't been updated for 9 years (to the day!) before we started looking at this problem, I thought it probably wasn't used by anyone.

**Comment by stylobille** [comment]
Ok I found a solution for that issue, it's related to the timestamps from the files downloaded from git so basicaly what to do to make it work : 

- Download the master.zip
- Extract de zip
- Go in to the extracted keepalived folder and run autoreconf -f -i
- Run configure
- copy the spec file to /root/rpmbuild/SPECS
- Make a tar.gz file from the keepalived folder 
- copy the tar.gz file in /root/rpmbuild/SOURCES

This works on RHEL 7.2 (creating the RPM exists on a code 0) but still triggers an error

Processing files: keepalived-1.2.24-5.x86_64
error: File not found: /root/rpmbuild/BUILDROOT/keepalived-1.2.24-5.x86_64/usr/lib/systemd/system/keepalived.service
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.f9qHuM

**Comment by pqarmitage** [comment]
You need to generate the keepalived.spec file (by running configure) on the target system. It looks to me as though there is a mismatch of the type of init in use (SYSV vs systemd) between the system where the keepalived.spec was generated, and the system on which you are doing the rpmbuild.

**Comment by stylobille** [comment]
Well i'm a bit new to this project (and new to building my own rpms too which you probably noticed hehe) so your help and fast replies are really appreciated :)

I just tested this out on RHEL6, is doesn't work that well on that environment : 

Even after having applied the `find . -exec touch -r configure {} +` trick the error about aclocal-1.15 triggers : 

```
+ /usr/bin/make -j3 STRIP=/bin/true
CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.15
/bin/sh: aclocal-1.15: command not found
make: *** [aclocal.m4] Error 127
error: Bad exit status from /var/tmp/rpm-tmp.LU5vFi (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.LU5vFi (%build)
```

So I tried the other way `aclocal; autoheader; automake --add-missing; autoreconf`

And that gives me this : 

```
[root@s-rdg-t-2 keepalived-1.2.24]# aclocal
configure.ac:138: warning: macro `AM_PROG_AR' not found in library
configure.ac:38: error: Autoconf version 2.65 or higher is required
configure.ac:38: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: autom4te failed with exit status: 63
```

Concerning RHEL7.2, I'm doing everything on the same system (generating the spec file and building the RPM) but the idea is to build this RPM for an exact same system running RHEL 7.2 too, so the error looks curious to me because this machine is freshly installed...

**Comment by pqarmitage** [comment]
Can you attach a tar file containing config.log, config.status, keepalived.spec and lib/config.h. I'll see if I can work out what is happening.

**Comment by stylobille** [comment]
Sure here you go, the files are from the RHEL 7.2 system : 

[tarforpqarmitage.zip](https://github.com/acassen/keepalived/files/476427/tarforpqarmitage.zip)

(It's a ziped tar file since git doesn't like tar files apparently)

**Comment by pqarmitage** [comment]
Could you also send your copy of keepalived/Makefile . I won't be able to look at this now for a few hours, but I'll get back to you when I can.

**Comment by stylobille** [comment]
Sure here it is : 
[tarforpqarmitage2.zip](https://github.com/acassen/keepalived/files/476499/tarforpqarmitage2.zip)

**Comment by stylobille** [comment]
Concerning the systemd file missing I just checked and in fact the whole system folder is missing in /root/rpmbuild/BUILDROOT/keepalived-1.2.24-5.x86_64/usr/lib (there is only a debug folder in that directory)

**Comment by pqarmitage** [comment]
What version of autoconf do you have on your system? On my Centos 7.2 system I have autoconf 2.69-11 and automake 1.13.4-3. From your output above at appears you have an autoconf version < 2.65.

**Comment by stylobille** [comment]
Yes me too I do have the same version, the version problem is for RHEL6 only.

I'm trying to build on both systems, 6 and 7, on RHEL7 the RPM creation is nearly complete (a problem with the systemD file remains) on RHEL6 it doesn't even start because of old versions.

**Comment by pqarmitage** [comment]
OK, I hadn't noticed that that error was from RHEL6.

I'll look at sorting the RHEL7 problem first, and then put my mind to the RHEL6 issue.

BTW, you really shouldn't be running rpmbuild as root. Since it does a make install, there is the potential risk of overwriting system files.

**Comment by stylobille** [comment]
Ok good to know, good that I'm using a dedicated virtual machine for my tests then :)

Thanks for the help !

**Comment by pqarmitage** [comment]
I've merged some commits that enable rpmbuild to work successfully on my Centos 7.2 system.

I'll look at your problems on RHEL6 in the next day or two.

**Comment by stylobille** [comment]
It's working for RHEL 7.2 now thanks to your changes !

So as a reminder for anyone finding this topic and being a beginner to RPM building and using git files :

Install a RHEL 7.2 system, then add some packages to be able to build RPMS (some packages in this list are useful for haproxy not keepalived, but this doesn't mater) : 

sudo yum -y install rpmdevtools && rpmdev-setuptree
sudo yum -y install pcre-devel gcc make openssl-devel kernel-devel iptables-devel glibc-devel libnl-devel libopenssl-devel libnl3 libnl3-devel libnfnetlink-devel automake

Now to the following : 

- Download the master zip file from git
- Unzip the file
- Rename the keepalived-master folder to keepalived-1.2.24
- Go in the folder
- Run autoreconf -f -i (I tried the` find . -exec touch -r configure {} +` trick, that doesn't work it keeps bugging me about aclocal-1.15 later)
- Run ./configure
- Copy the keepalived.spec file into /root/rpmbuild/SPECS
- Make a tar.gz file from the keepalived folder called keepalived-1.2.24.tar.gz
- copy keepalived-1.2.24.tar.gz into /root/rpmbuild/SOURCES/
- Run rpmbuild -bb /root/rpmbuild/SPECS/keepalived.spec

And voilà it works, you have a nice rpm ready to be installed !

Thanks again pqarmitage, this is nice step forward, now there is still the issue with RHEL6, I'll stay tuned to test out whatever you find :)

**Comment by pqarmitage** [comment]
Re your previous comment, the best way to make the tar.gz file is to run `make dist`. This will include precisely the files that are needed for building.

For RHEL6, the following has been successful for me on Centos 6.8. The key thing is we don't want to recreate configure during an RHEL6 build, since automake 1.11 doesn't understand AM_PROG_AR.

On your RHEL7.2 system, run

**Comment by pqarmitage** [comment]
For RHEL6, the following has been successful for me on Centos 6.8. The key thing is we don't want to recreate configure during an RHEL6 build, since automake 1.11 doesn't understand AM_PROG_AR.

On your RHEL7.2 system, run `autoreconf -f -i; ./configure; make dist`. Copy the resultant tarball to your RHEL 6.2 system.

On the RHEL 6.2 system, extract the tarball somewhere, and run `./configure` with the build options you want (the only bit we are interested in is generating a keepalived.spec that has the build options we want and the right system init files).

Now copy the tarball (there is no need to make a new one) and the keepalived.spec file into the rpmbuild tree, and run rpmbuild (i.e. `cd ~/rpmbuild; rpmbuild -bb SPECS/keepalived.spec`). This should successfully create your rpms.

**Comment by stylobille** [comment]
Yup that does the trick, maybe not the best way to solve this regarding RHEL 6.8 but i'm fine with this.
