### ISSUE TITLE
Netlink: error: Operation not permitted, type=(20), seq=1474249733, pid=0

### ISSUE THREAD

**Issue by justyu** [acassen/keepalived#427]
On vm1(172.17.0.3), logs are:
Starting VRRP child process, pid=1590
Interface queue is empty
Netlink reflector reports IP 172.17.0.3 added
Netlink reflector reports IP fe80::42:acff:fe11:3 added
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Initializing ipvs 2.6
IPVS: Can't initialize ipvs: Protocol not available
Opening file '/etc/keepalived/keepalived.conf'.
Configuration is using : 66144 Bytes
Using LinkWatch kernel netlink reflector...
VRRP sockpool: [ifindex(30), proto(112), fd(10,11)]
VRRP_Script(chk_service) succeeded
VRRP_Instance(VI_1) Transition to MASTER STATE
VRRP_Instance(VI_1) Entering MASTER STATE
VRRP_Instance(VI_1) setting protocol VIPs.
Netlink: error: Operation not permitted, type=(20), seq=1474249628, pid=0
VRRP_Instance(VI_1) Sending gratuitous ARPs on eth0 for 172.17.0.100
VRRP_Instance(VI_1) Sending gratuitous ARPs on eth0 for 172.17.0.100
VRRP_Instance(VI_1) Received higher prio advert
VRRP_Instance(VI_1) Entering BACKUP STATE
VRRP_Instance(VI_1) removing protocol VIPs.

it seems ok,
on vm2(172.17.0.4), logs are:
Starting VRRP child process, pid=1686
Interface queue is empty
Netlink reflector reports IP 172.17.0.4 added
Netlink reflector reports IP fe80::42:acff:fe11:4 added
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Initializing ipvs 2.6
IPVS: Can't initialize ipvs: Protocol not available
Opening file '/etc/keepalived/keepalived.conf'.
Configuration is using : 66144 Bytes
Using LinkWatch kernel netlink reflector...
VRRP sockpool: [ifindex(32), proto(112), fd(10,11)]
VRRP_Script(chk_service) succeeded
VRRP_Instance(VI_1) Transition to MASTER STATE
VRRP_Instance(VI_1) Entering MASTER STATE
VRRP_Instance(VI_1) setting protocol VIPs.
Netlink: error: Operation not permitted, type=(20), seq=1474249733, pid=0
VRRP_Instance(VI_1) Sending gratuitous ARPs on eth0 for 172.17.0.100
VRRP_Instance(VI_1) Sending gratuitous ARPs on eth0 for 172.17.0.100

and then nothing happens, no VIP on either vm.
I see "Netlink: error: Operation not permitted, type=(20), seq=1474249733, pid=0", but how to fix it?
keepalived.conf are:
# keepalived.conf
global_defs
{
    notification_email
    {
        root@localhost
    }
    notification_email_from root@localhost
    smtp_server 127.0.0.1
    stmp_connect_timeout 30
    router_id rgw
}
vrrp_script chk_service
{
    script /etc/keepalived/check_rgw.sh
    interval 5
}

vrrp_instance VI_1 {
    state MASTER
    interface eth0
    virtual_router_id 100
    priority 170
    advert_int 5
    track_interface {
        eth0
    }

    authentication {
        auth_type PASS
        auth_pass 123456
    }
    virtual_ipaddress {
        172.17.0.100
    }

    track_script {
        chk_service
    }
}

**Comment by justyu** [comment]
addition info may be helpful:
version: Keepalived v1.2.7 (08/14,2013)
OS: Ubuntu 14.04.4 LTS \n \l
keepalived runs in docker.

vm1:
root@7540e33d8839:/# ifconfig -a
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:03  
          inet addr:172.17.0.3  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:3/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:14017 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12528 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2524245 (2.5 MB)  TX bytes:2334613 (2.3 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:9 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:896 (896.0 B)  TX bytes:896 (896.0 B)


vm2:
root@6b33a8bd41cf:/# ifconfig -a
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:04  
          inet addr:172.17.0.4  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:13623 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12934 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2545490 (2.5 MB)  TX bytes:2401184 (2.4 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:28 errors:0 dropped:0 overruns:0 frame:0
          TX packets:28 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2632 (2.6 KB)  TX bytes:2632 (2.6 KB)

**Comment by justyu** [comment]
fixed it, it's not because keepalived.

**Comment by pqarmitage** [comment]
Have you noticed the typo in the config?
`stmp_connect_timeout 30`

Also there is no need to specify track_interface for the interface that the vrrp instance is running on, it will track it anyway.

**Comment by justyu** [comment]
Ooops, got it..
thanks :)

**Comment by MR-D3** [comment]
how to fix it? same question (怎么解决的，我跟你同样的问题)

**Comment by nemo1937** [comment]
config file has some mistakes.

**Comment by Paul-LKW** [comment]
It is annoying to say my fixed the problem but never have the solution on Post, selfish.

**Comment by TomaszKlosinski** [comment]
@justyu , what was the problem?

**Comment by odeng888** [comment]
What causes it?

**Comment by chenxu19921219** [comment]
Disable ipv6 will fix it；
echo "net.ipv6.conf.all.disable_ipv6=1" >> /usr/lib/sysctl.d/50-default.conf；

**Comment by pshizhsysu** [comment]
If you run keepalived as a container, you need to pass NET_ADMIN, NET_BROADCAST，NET_RAW to it

For example：

1、run as a docker container

```
docker run --cap-add=NET_ADMIN --cap-add=NET_BROADCAST --cap-add=NET_RAW ....
```

2、run a k8s pod

```
apiVersion: v1
kind: Pod
metadata:
  name: xxx
spec:
  containers:
  - name: keepalived
    image: xxxxx
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "NET_BROADCAST", "NET_RAW"]
...
```
