### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by JeanKerr** [acassen/keepalived#441]
Hi, all:
    I've met one problem when using keepalived, can anyone give me some explain if it is a bug or not,if not, is there any solution for the problem below:
    When I config keepalived scripts(backup and master mode), after the master node injected virtual IP into linux kernal, which also was used as the IP as source IP of VRRP broadcasted, it never care about the IP state in linux kernal.  for example, when you use ifdown and ifup cmd to restart the i/f which virtual IP on keepalived never process the lost virtural IPs again, but still using the IPs as source of VRRP packet sending. this will cause IP lost actually.

Can anyone explain me the case? many thanks.

**Comment by pqarmitage** [comment]
There are circumstances, with the current keepalived code, where it is possible to down and up an interface without keepalived noticing. The first thing to do is to run keepalived with the `-D` option, which causes more verbose logging, and then to look at the logs to see if it logs the vrrp instance going into fault state. If it does go into fault state, then when the interface comes back up, the vrrp instance should go into backup state, and then when it transitions to master it should add the IP address again.

If you are using vmacs though, the current code ignores the vmac interface being downed and uped, and so the vrrp instance will not go to fault state, and in this case the address would be lost.

The current code only checks the state of an interface just before it sends and advert if in master mode (or every 3 * advert interval when in backup or fault state). So if you down an interface and up it again between adverts, keepalived will not notice that the interface was downed.

I am currently working on changes to the keepalived code part of which is that it will be aware as soon as an interface is down (including vmac interfaces), and the vrrp instance will immediately be put into fault state. As a consequence of this, once the interface is restored and the vrrp instance transitions to master again, the IP address will be added to the interface again. It'll probably be another week before I have something to release for this, but you can find my latest version of the code at https://github.com/pqarmitage/keepalived/tree/fixes.quick but if you do try that, be aware that it is far from fully tested.

One aspect that I am not clear about is that I think you are saying that the source address of the VRRP packets is the virtual IP address. This should not be the case - it should be the primary IP address on the interface. If you could post your configuration file, and also state what version of keepalived you are using, I could try and see what is happening there.

**Comment by pqarmitage** [comment]
Closing due to no update for over 5 months.
