### ISSUE TITLE
one question about remove vip

### ISSUE THREAD

**Issue by sunjydev** [acassen/keepalived#442]
Hi,all:
    I have a problem about remove vip. For eaxample, I have two vrrp instances, which bind to the same interface, when one of the two vrrp instances become to BACKUP or FAULT, both of the two instances's vip lost and the other instance still sends vrrp advert packets.
   we review the source code and think the function below may have problem. when one instance state changed and need to remove its vips, the other instance's vips will be removed too. 
   can anyone explain this problem ? thanks very much.

```
`/* Add/Delete a list of IP addresses */
void
netlink_iplist(list ip_list, int cmd)
{
    ip_address_t *ipaddr;
    element e;

    /* No addresses in this list */
    if (LIST_ISEMPTY(ip_list))
        return;
```

```
    /*
     * If "--dont-release-vrrp" is set then try to release addresses
     * that may be there, even if we didn't set them.
     */
    for (e = LIST_HEAD(ip_list); e; ELEMENT_NEXT(e)) {
        ipaddr = ELEMENT_DATA(e);
        if ((cmd && !ipaddr->set) ||
            (!cmd &&
             (ipaddr->set || __test_bit(DONT_RELEASE_VRRP_BIT, &debug)))) {
            if (netlink_ipaddress(ipaddr, cmd) > 0)
                ipaddr->set = !(cmd == IPADDRESS_DEL);
            else
                ipaddr->set = 0;
        }
    }
}`
```

**Comment by sunjydev** [comment]
BTW:
Oct  9 14:50:58 SDN-1164-256 Keepalived_vrrp[26452]: VRRP_Instance(VI_MONGODB) Transition to MASTER STATE
Oct  9 14:50:59 SDN-1164-256 Keepalived_vrrp[26452]: VRRP_Instance(VI_MONGODB) Entering MASTER STATE
Oct  9 14:50:59 SDN-1164-256 Keepalived_vrrp[26452]: VRRP_Instance(VI_MONGODB) setting protocol VIPs.
Oct  9 14:50:59 SDN-1164-256 Keepalived_healthcheckers[26451]: Netlink reflector reports IP 192.168.80.90 added
Oct  9 14:50:59 SDN-1164-256 Keepalived_vrrp[26452]: VRRP_Instance(VI_MONGODB) Sending gratuitous ARPs on eth0 for 192.168.80.90
Oct  9 14:51:04 SDN-1164-256 Keepalived_vrrp[26452]: VRRP_Instance(VI_MONGODB) Sending gratuitous ARPs on eth0 for 192.168.80.90
Oct  9 14:52:46 SDN-1164-256 Keepalived_vrrp[26452]: pid 21162 exited with status 1
Oct  9 14:52:46 SDN-1164-256 Keepalived_vrrp[26452]: VRRP_Script(check_zamp) failed
Oct  9 14:52:46 SDN-1164-256 Keepalived_vrrp[26452]: VRRP_Instance(VI_ZAMP) Entering FAULT STATE
Oct  9 14:52:46 SDN-1164-256 Keepalived_vrrp[26452]: VRRP_Instance(VI_ZAMP) removing protocol VIPs.
Oct  9 14:52:46 SDN-1164-256 Keepalived_healthcheckers[26451]: Netlink reflector reports IP 192.168.80.90 removed
Oct  9 14:52:46 SDN-1164-256 Keepalived_healthcheckers[26451]: Netlink reflector reports IP 192.168.80.80 removed
Oct  9 14:52:46 SDN-1164-256 Keepalived_vrrp[26452]: VRRP_Instance(VI_ZAMP) Now in FAULT state
Oct  9 14:52:47 SDN-1164-256 Keepalived_vrrp[26452]: pid 21354 exited with status 1
Oct  9 14:52:48 SDN-1164-256 Keepalived_vrrp[26452]: pid 21543 exited with status 1
Oct  9 14:52:49 SDN-1164-256 Keepalived_vrrp[26452]: pid 21732 exited with status 1
Oct  9 14:52:50 SDN-1164-256 Keepalived_vrrp[26452]: pid 21921 exited with status 1

the config file is:
[root@SDN-1164-256 home]# cat /usr/local/etc/keepalived/keepalived.conf 
! Configuration File for keepalived

vrrp_script check_zamp {
    script "/home/zenic/scripts/for_zamp.sh"
    interval 1
    timeout  10
}

vrrp_script check_mongodb {
    script "/home/zenic/scripts/for_mongodb.sh"
    interval 1
    timeout  10
}

global_defs {
   router_id LVS_DEVEL
}
vrrp_instance VI_ZAMP {
    state BACKUP
    interface eth0
    virtual_router_id 80
    priority 100
    advert_int 1
    nopreempt
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    
    track_script {
        check_zamp
    }

    
    virtual_ipaddress {
        192.168.80.80/24
    }
}
vrrp_instance VI_MONGODB {
    state BACKUP
    interface eth0
    virtual_router_id 90
    priority 100
    advert_int 1
    nopreempt
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    
    track_script {
        check_mongodb
    }

    
    virtual_ipaddress {
        192.168.80.90/24
    }
}

**Comment by dingrui37** [comment]
when primary ip lost, both of all secondary ips will be lost too, you can find reason from netlink_parse_info fun comment:
                /* If have more than one IPv4 address in the same CIDR
                 * and the "primary" address is removed, unless promote_secondaries
                 * is configured on the interface, all the "secondary" addresses
                 * in the same CIDR are deleted */ 
echo 1 to config file as below can slove this problem:
`echo "1" > /proc/sys/net/ipv4/conf/ethX/promote_secondaries`

**Comment by pqarmitage** [comment]
Commit https://github.com/acassen/keepalived/commit/e5526cf9 added support for setting the promote_secondaries option when using VMACs. It also made a comment that I would add setting the option when not using VMACs, but I had forgotten to do so.

I think if you remove the `/24` from the configuration of the `virtual_ipaddress` blocks, then you won't need to use the `echo "1" > /proc/sys/net/ipv4/conf/ethX/promote_secondaries` command.

I'll make a note to remind me to add a configuration option to set the promote_secondaries flag for non VMAC interfaces.

**Comment by pqarmitage** [comment]
Commit 3939d96 adds a promote_secondaries configuration option for vrrp_instances. This commit is currently awaiting being merged.

**Comment by pqarmitage** [comment]
Commit 3939d96 now merged.
