### ISSUE TITLE
systemd doesn't detect correct main PID after restart

### ISSUE THREAD

**Issue by kustodian** [acassen/keepalived#443]
I was setting up Keepalived on CentOS 7 and I noticed that when I made some changes to the configuration and after I restarted keepalived with `systemctl restart keepalived` that it didn't refresh the configuration. Then I checked syslog and noticed that there is something wrong with the `keepalived.service` unit file. Here is what you need to do to reproduce this problem:

Setup some VRRP configuration and start keepalived with
```
# systemctl start keepalived
```
and check if it's running and what PIDs it is using:
```
# systemctl status keepalived
● keepalived.service - LVS and VRRP High Availability Monitor
   Loaded: loaded (/usr/lib/systemd/system/keepalived.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2016-10-11 14:00:13 CEST; 22s ago
  Process: 12473 ExecStart=/usr/sbin/keepalived $KEEPALIVED_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 12474 (keepalived)
   CGroup: /system.slice/keepalived.service
           ├─12474 /usr/sbin/keepalived -D
           ├─12475 /usr/sbin/keepalived -D
           └─12476 /usr/sbin/keepalived -D

Oct 11 14:00:13 lb-01 Keepalived_vrrp[12476]: VRRP sockpool: [ifindex(2), proto(112), unicast(1), fd(10,11)]
Oct 11 14:00:13 lb-01 Keepalived_healthcheckers[12475]: Configuration is using : 7668 Bytes
Oct 11 14:00:13 lb-01 systemd[1]: Started LVS and VRRP High Availability Monitor.
Oct 11 14:00:13 lb-01 Keepalived_healthcheckers[12475]: Using LinkWatch kernel netlink reflector...
Oct 11 14:00:14 lb-01 Keepalived_vrrp[12476]: VRRP_Instance(VI_1) Transition to MASTER STATE
Oct 11 14:00:15 lb-01 Keepalived_vrrp[12476]: VRRP_Instance(VI_1) Entering MASTER STATE
Oct 11 14:00:15 lb-01 Keepalived_vrrp[12476]: VRRP_Instance(VI_1) setting protocol VIPs.
Oct 11 14:00:15 lb-01 Keepalived_vrrp[12476]: VRRP_Instance(VI_1) Sending gratuitous ARPs on em1 for 192.168.216.52
Oct 11 14:00:15 lb-01 Keepalived_healthcheckers[12475]: Netlink reflector reports IP 192.168.216.52 added
Oct 11 14:00:20 lb-01 Keepalived_vrrp[12476]: VRRP_Instance(VI_1) Sending gratuitous ARPs on em1 for 192.168.216.52

# ps auxf | grep [k]eepalived
root     12474  0.0  0.0 111644  1304 ?        Ss   14:00   0:00 /usr/sbin/keepalived -D
root     12475  0.0  0.0 111644  2524 ?        S    14:00   0:00  \_ /usr/sbin/keepalived -D
root     12476  0.0  0.0 111644  1512 ?        S    14:00   0:00  \_ /usr/sbin/keepalived -D
```
As we can see the main PID is `12474` and it's reported correctly with `systemd` and `ps`.
Then we run a restart:
```
# systemctl restart keepalived
```
Now let's check how PIDs look like:
```
# systemctl status keepalived
● keepalived.service - LVS and VRRP High Availability Monitor
   Loaded: loaded (/usr/lib/systemd/system/keepalived.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2016-10-11 14:01:45 CEST; 1s ago
  Process: 12571 ExecStart=/usr/sbin/keepalived $KEEPALIVED_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 12474 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/keepalived.service
           ├─12572 /usr/sbin/keepalived -D
           ├─12573 /usr/sbin/keepalived -D
           └─12574 /usr/sbin/keepalived -D

Oct 11 14:01:45 lb-01 Keepalived_vrrp[12574]: Registering gratuitous ARP shared channel
Oct 11 14:01:45 lb-01 Keepalived_healthcheckers[12573]: Opening file '/etc/keepalived/keepalived.conf'.
Oct 11 14:01:45 lb-01 Keepalived_vrrp[12574]: Opening file '/etc/keepalived/keepalived.conf'.
Oct 11 14:01:45 lb-01 Keepalived_healthcheckers[12573]: Configuration is using : 7668 Bytes
Oct 11 14:01:45 lb-01 Keepalived_vrrp[12574]: Configuration is using : 64333 Bytes
Oct 11 14:01:45 lb-01 Keepalived_vrrp[12574]: Using LinkWatch kernel netlink reflector...
Oct 11 14:01:45 lb-01 Keepalived_vrrp[12574]: VRRP sockpool: [ifindex(2), proto(112), unicast(1), fd(10,11)]
Oct 11 14:01:45 lb-01 systemd[1]: Started LVS and VRRP High Availability Monitor.
Oct 11 14:01:45 lb-01 Keepalived_healthcheckers[12573]: Using LinkWatch kernel netlink reflector...
Oct 11 14:01:46 lb-01 Keepalived_vrrp[12574]: VRRP_Instance(VI_1) Transition to MASTER STATE

# ps auxf | grep [k]eepalived
root     12572  0.0  0.0 111644  1296 ?        Ss   14:01   0:00 /usr/sbin/keepalived -D
root     12573  0.0  0.0 111644  2524 ?        S    14:01   0:00  \_ /usr/sbin/keepalived -D
root     12574  0.0  0.0 111644  1512 ?        S    14:01   0:00  \_ /usr/sbin/keepalived -D
```
As you can see `systemd` is reporting that the main PID is still the old one `12474`, while the main PID is actually `12572` which we can see with `ps`. So what is interesting now is that you cannot stop `keepalived` with `systemd`, because `systemd` would now send a kill signal to the main PID which doesn't exist any more. You can only stop it manually with `kill`.

But let's not stop it now, let's do a restart again, that's how I found this problem. If we run restart again:
```
# systemctl restart keepalived
```
this time `systemd` correctly detects the previous main PID and reuses that process:
```
systemctl status keepalived
● keepalived.service - LVS and VRRP High Availability Monitor
   Loaded: loaded (/usr/lib/systemd/system/keepalived.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2016-10-11 14:03:41 CEST; 2s ago
  Process: 12622 ExecStart=/usr/sbin/keepalived $KEEPALIVED_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 12572 (keepalived)
   CGroup: /system.slice/keepalived.service
           ├─12572 /usr/sbin/keepalived -D
           ├─12573 /usr/sbin/keepalived -D
           └─12574 /usr/sbin/keepalived -D

Oct 11 14:03:41 lb-01 systemd[1]: Stopping LVS and VRRP High Availability Monitor...
Oct 11 14:03:41 lb-01 systemd[1]: Starting LVS and VRRP High Availability Monitor...
Oct 11 14:03:41 lb-01 Keepalived[12622]: Starting Keepalived v1.2.13 (11/20,2015)
Oct 11 14:03:41 lb-01 Keepalived[12622]: daemon is already running
Oct 11 14:03:41 lb-01 systemd[1]: Started LVS and VRRP High Availability Monitor.

# ps auxf | grep [k]eepalived
root     12572  0.0  0.0 111644  1296 ?        Ss   14:01   0:00 /usr/sbin/keepalived -D
root     12573  0.0  0.0 111644  2524 ?        S    14:01   0:00  \_ /usr/sbin/keepalived -D
root     12574  0.0  0.0 111644  1512 ?        S    14:01   0:00  \_ /usr/sbin/keepalived -D
```
But the problem is that it doesn't actually restart the process and it doesn't read the configuration again. Here is what it prints in the syslog (`/var/log/messages`):
```
Oct 11 14:03:41 lb-01 systemd: Stopping LVS and VRRP High Availability Monitor...
Oct 11 14:03:41 lb-01 systemd: Starting LVS and VRRP High Availability Monitor...
Oct 11 14:03:41 lb-01 Keepalived[12622]: Starting Keepalived v1.2.13 (11/20,2015)
Oct 11 14:03:41 lb-01 Keepalived[12622]: daemon is already running
Oct 11 14:03:41 lb-01 systemd: Started LVS and VRRP High Availability Monitor.
```

There are two ways to solve this problem:

1. Add `PIDFile=/var/run/keepalived.pid` into the `keepalived.service` (not sure if keepalived writes the pid file always into this directory on all platforms, but on CentOS 7 this is the case)
2. Set `type=simple` and add `-n` to `ExectStart`, so it looks like this: `ExecStart=/usr/sbin/keepalived -n $KEEPALIVED_OPTIONS`

I can easily make a pull request for this, just tell me which options do you think is better?

**Comment by pqarmitage** [comment]
The `keepalived.service` file included in the keepalived distribution already has `PIDFile=/var/run/keepalived.pid` (this filename is always used, unless keepalived is running in a network namespace, or the `use_pid_dir` configuration option is given, but these two features are recent additions to keepalived, and so won't be available in any CentOS package).

I added the `keepalived.service` file to the keepalived source tree by copying it from the Fedora repo. This will therefore presumably trickle through to a RedHat release, and hence into CentOS.

If you feel that CentOS needs to be updated, then presumably RedHat would have to update their current package in Enterprise Linux, and then CentOS would get the update.

**Comment by JasonYLong** [comment]
I also get the same error.  The reson is the file privillege 0755 , after I change the privillege to 0644 . the issue fixed.
[root@master-2 keepalived]# ls -l
total 8
-rw-r--r--. 1 root root 233 Jan  8 15:30 check_haproxy.sh
-rw-r--r--. 1 root root 529 Jan  8 15:30 keepalived.conf

**Comment by pqarmitage** [comment]
I think check_haproxy.sh should have the execute bit set. I also don't think privilege 0755 should cause a problem like this.

The interaction between keepalived and systemd has changed in the last few releases. @JasonYLong You don't say what version of keepalived you are running, or what distro you are using. Does /lib/systemd/system/keepalived.service have the following lines:
```
Type=notify
NotifyAccess=all
```
If not it would be worth considering upgrading to at least version 2.2.2, or better still v2.2.4.
