### ISSUE TITLE
Can't use VRRP without checker subsytem

### ISSUE THREAD

**Issue by AJDempsey** [acassen/keepalived#446]
Because of the IFDEFs in main.c, line 215, find_keepalived_child vrrp needs the checker for main.c to compile. 

[  117s]   CC       main.o
[  117s] main.c: In function 'find_keepalived_child':
[  117s] main.c:215:2: error: 'else' without a previous 'if'
[  117s]   else if (pid == vrrp_child)
[  117s]   ^

**Comment by pqarmitage** [comment]
Thanks for the report. Commit f5d9202 is now queued for merging.
