### ISSUE TITLE
http://www.keepalived.org/ is down?

### ISSUE THREAD

**Issue by yctn** [acassen/keepalived#473]
keepalived website is down?

**Comment by acassen** [comment]
yes... web server crashed down... need to find new hosting...

**Comment by yctn** [comment]
acassen. would it be possible to talk to you sometime? i have seveneral question regarding keepalived but i cand find out where i should ask them. the IRC channel is pretty dead

**Comment by acassen** [comment]
please use website contact email.

**Comment by yctn** [comment]
i did but you never replyed i emailed you on 26 september 2016

**Comment by yctn** [comment]
i have send you a new email. its a bit long but i realy hope you can answer it.
