### ISSUE TITLE
keepalived1.3.2  make error

### ISSUE THREAD

**Issue by keepleaning** [acassen/keepalived#477]
CentOS 6.4  keepalived1.3.2 make & make install 

namespaces.c: In function ‘setns’:
namespaces.c:187: error: ‘__NR_setns’ undeclared (first use in this function)
namespaces.c:187: error: (Each undeclared identifier is reported only once
namespaces.c:187: error: for each function it appears in.)
namespaces.c: In function ‘setns’:
namespaces.c:187: error: ‘__NR_setns’ undeclared (first use in this function)
namespaces.c:187: error: (Each undeclared identifier is reported only once
namespaces.c:187: error: for each function it appears in.)
make[2]: *** [namespaces.o] Error 1
make[2]: Leaving directory `/home/keepalived-1.3.2/keepalived/core'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/keepalived-1.3.2/keepalived'
make: *** [all-recursive] Error 1
make[2]: *** [namespaces.o] Error 1
make[2]: Leaving directory `/home/keepalived-1.3.2/keepalived/core'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/keepalived-1.3.2/keepalived'
make: *** [install-recursive] Error 1
[1]+  Exit 2                  make

**Comment by pqarmitage** [comment]
This would appear to be a problem with glibc headers. On a vanilla install of Centos 6.5, with glibc-headers-2.12-1.132.el6.x86_64 I get the following error: 
namespaces.c:187: error: ‘SYS_setns’ undeclared (first use in this function)

After doing yum update glibc, which updates glibc-headers-2.12-1.192.el6.x86_64, for me keepalived compiles successfully.

What is most strange is that the `#include <sys/syscalls.h>` includes <asm/unistd.h> which then includes either "unistd_32.h" or "unistd_64.h". Both of those latter two files define __NR_setns, even with the older version of glibc-headers installed.

Clearly you have a version of the headers that is defining SYS_setns to __NR_setns, but for some reason the definition of __NT_setns is not being picked up.

Can you check what version of glibc you have installed, and perhaps run `rpm -V glibc-headers` to check that the package is correctly installed.

Are you able to trace through the includes from /usr/include/sys/syscalls.h to ensure that one of unistd_32.h or unistd_64.h is included.

You could change to the keepalived/core directory and run:
`gcc -DHAVE_CONFIG_H -I. -I../../lib    -I./../include -I./../../lib  -Wall -Wunused -Wstrict-prototypes -Wextra -g -O2  -g -O2 -MT -MD -MP -MF .deps/namespaces.Tpo -E namespaces.c
>/tmp/namespaces.cc` and check what files are being included.

If you are not using the latest version of glibc available, can you upgrade to that and see if that resolves your problem.

**Comment by pqarmitage** [comment]
Closing due to no response for over 3 months.
