### ISSUE TITLE
reload problem

### ISSUE THREAD

**Issue by lewislyou** [acassen/keepalived#479]
in file check_daemon.c, line167,168
`	if (reload)
		clear_diff_services();`
I delete a realserver, then reload, if clear_diff_services() fail to reload, the realserver is lef, whether keepalived.conf change or not, wrong rules always there. can anyone explain this situation

**Comment by pqarmitage** [comment]
Could you please provide the configuration files you are using (i.e. before and after deleting the realserver), and also provide the output of `ipvsadm --list` before and after the reload.

**Comment by VegeChou** [comment]
@pqarmitage 
I got the same problem.

When I delete real server ```192.168.211.7```, the UDP packets will not be transmitted to ```192.168.211.4```.

My congfiguration is below
```
! Configuration file for keepalived
global_defs {
    notification_email {
        1@1.com
    }
    notification_email_from 1@1.com
    smtp_server 127.0.0.1
    smtp_connect_timeout 30
    router_id LVS_DEVEL
}

# monitor service such as nginx
vrrp_script NginxMonitor {
    script "/etc/keepalived/nginx_monitor.sh"
    interval 2
    weight 2
}

vrrp_instance VI_1 {
    state MASTER  # master(MASTER) or slave(BACKUP)
    interface eth0 # eth number 
    virtual_router_id 51
    mcast_src_ip 192.168.211.12 # local IP
    priority 50  
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass ***
    }
    virtual_ipaddress {
        192.168.211.120  #VIP
    }
    track_script {
        NginxMonitor  # monitor script
    }
}


virtual_server 192.168.211.120 1680 {
    lb_algo sh
    lb_kind DR
    protocol UDP
    persistence_timeout 5
    
    real_server 192.168.211.4 1680 {
    }
    #real_server 192.168.211.7 1680 {
    #}
}
```

**Comment by VegeChou** [comment]
@pqarmitage 
My keepalived version is v1.3.4, and the problem is also in v1.2.7.

Output of ```ipvsadm --list``` before and after the reload, the forward route is really changed. But the packets are not forwarded correctly.

**Comment by pqarmitage** [comment]
I have tried your configuration and it is working without a problem for me, so it makes it rather hard for me to see where the problem might be.

Can you try setting this up manually (i.e. without keepalived) and see what happens:
```
ipvsadm -A -u 192.168.211.120:1680 -s sh
ipvsadm -a -u 192.168.211.120:1680 -r 192.168.211.4
ipvsadm -a -u 192.168.211.120:1680 -r 192.168.211.7
ip addr add 192.168.211.120/32 dev eth0
```
Test to make sure this is working, then do
`ipvsadm -d -u 192.168.211.120:1680 -r 192.168.211.7`
and now test again. Can you please report if it now works or not.

To remove the added config:
```
ip addr del 192.168.211.120/32 dev eth0
ipvsadm -A -u 192.168.211.120:1680 -s sh
```
If it does work, could you please post the output of `ipvsadm -ln` for both the manual test and when testing with keepalived, and for each case the `ipvsadm -ln` output when two real servers and configured, and after one has been deleted (i.e. after the keepalived reload with the real server commented out).

If the manual test doesn't work then it would suggest it is something not related to keepalived, to do with the configuration on your systems.

**Comment by VegeChou** [comment]
@pqarmitage 

Thank you for your reply.

I have found the problem, it is really not related to keepalived.

The default UDP connection timeout is 300 seconds, even though I have deleted the real server, it will be effected after timeout.

I need to set the ```connect_timeout``` param and it works well.

Thanks again.
