### ISSUE TITLE
Keepalived version 1.3.2 compile error

### ISSUE THREAD

**Issue by gaowenk** [acassen/keepalived#480]
checking for setns... yes
checking for sphinx-build... No
systemd

checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating keepalived/Makefile
config.status: creating lib/Makefile
config.status: creating keepalived/core/Makefile
config.status: creating keepalived.spec
config.status: creating genhash/Makefile
config.status: creating keepalived/check/Makefile
config.status: creating keepalived/vrrp/Makefile
config.status: creating doc/Makefile
config.status: creating bin_install/Makefile
config.status: creating keepalived/dbus/Makefile
config.status: creating lib/config.h
config.status: executing depfiles commands

Keepalived configuration
------------------------
Keepalived version       : 1.3.2
Compiler                 : gcc
Preprocessor flags       :  -I/usr/include/libnl3  
Compiler flags           : -Wall -Wunused -Wstrict-prototypes -Wextra -g -O2   
Linker flags             : 
Extra Lib                : -ldl -lssl -lcrypto  -lnl-3 -lnl-genl-3 -lnl-route-3
Use IPVS Framework       : Yes
IPVS use libnl           : Yes
IPVS syncd attributes    : No
IPVS 64 bit stats        : No
fwmark socket support    : Yes
Use VRRP Framework       : Yes
Use VRRP VMAC            : Yes
Use VRRP authentication  : Yes
With ip rules/routes     : Yes
SNMP vrrp support        : No
SNMP checker support     : No
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
DBUS support             : No
SHA1 support             : No
Use Debug flags          : No
Stacktrace support       : No
Memory alloc check       : No
libnl version            : 3
Use IPv4 devconf         : No
Use libiptc              : No
Use libipset             : No
init type                : systemd
Build genhash            : Yes
Build documentation      : No
[root@centos71 keepalived-1.3.2]# make
Making all in lib
make[1]: Entering directory `/root/keepalived-1.3.2/lib'
make  all-am
make[2]: Entering directory `/root/keepalived-1.3.2/lib'
  CC       memory.o
  CC       utils.o
  CC       notify.o
  CC       timer.o
  CC       scheduler.o
  CC       vector.o
  CC       list.o
  CC       html.o
  CC       parser.o
  CC       signals.o
  CC       logger.o
  CC       rttables.o
  AR       liblib.a
make[2]: Leaving directory `/root/keepalived-1.3.2/lib'
make[1]: Leaving directory `/root/keepalived-1.3.2/lib'
Making all in keepalived
make[1]: Entering directory `/root/keepalived-1.3.2/keepalived'
Making all in core
make[2]: Entering directory `/root/keepalived-1.3.2/keepalived/core'
  CC       main.o
  CC       daemon.o
  CC       pidfile.o
  CC       layer4.o
  CC       smtp.o
  CC       global_data.o
  CC       global_parser.o
  CC       process.o
  CC       namespaces.o
  AR       libcore.a
make[2]: Leaving directory `/root/keepalived-1.3.2/keepalived/core'
Making all in vrrp
make[2]: Entering directory `/root/keepalived-1.3.2/keepalived/vrrp'
  CC       vrrp_daemon.o
In file included from vrrp_daemon.c:37:0:
./../include/vrrp_iproute.h:32:24: fatal error: linux/mpls.h: No such file or directory
 #include <linux/mpls.h>
                        ^
compilation terminated.
make[2]: *** [vrrp_daemon.o] Error 1
make[2]: Leaving directory `/root/keepalived-1.3.2/keepalived/vrrp'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/keepalived-1.3.2/keepalived'
make: *** [all-recursive] Error 1
[root@centos71 keepalived-1.3.2]# cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core) 

This OS is a KVM guest OS.
I think configure command should check mpls.h

**Comment by pqarmitage** [comment]
The problem is caused by RedHat having partially backported lightweight tunnel encapsulation into the latest RHEL 7 kernel; in particular they have backported IP and IP6 encapsulation, but not MPLS or ILA encapsulation.

Commit c134bf4 adds further conditional compilation checks to work around the partial implementation of lightweight tunnels.

**Comment by agibson2** [comment]
Is it easy to get a patch for the 1.3.2 version?  I tried just applying this commit as a patch but there are too many changes it seems.  I was hoping to stick with an official release instead of going with the master.

**Comment by agibson2** [comment]
I forgot that rpmbuild by default uses a fuzz=0 so patches have to match precisely.  I patched it outside of rpmbuild and then did another diff to include in the spec file.  Sorry for the chatter.
