### ISSUE TITLE
Keepalived 1.2.13. Issue with virtual routing/virtual rules

### ISSUE THREAD

**Issue by Genluck** [acassen/keepalived#483]
Hello.

We have a keepalived of version 1.2.13 that is installed at our servers. And we did try to use viartual_rules and virtual_routes segments for source routing. But when VRRP became a MASTER state we don't see any changes at "ip route show table ##" or at the "ip rule".
When I'm trying to add rules via console by typing "ip rule add [line from config]/ip route add [line from config]" the system is adding it without any errors. Also I don't see anything (even tryes to add rules) at the logs even with "-D" option.
The example of configuration from one of the servers in attachment.

I would be grateful for the help.
Best Regards.

[Config example.txt](https://github.com/acassen/keepalived/files/657318/Config.example.txt)

**Comment by pqarmitage** [comment]
Support for virtual rules wasn't added until v1.2.20, at which time support of virtual routes was significantly enhanced.

In the config, as above, `viartual_rules` should be `virtual_rules` (but you will need keepalived v1.2.20 or later).

There are a number of other keywords you have configured that didn't exist in v1.2.13, such as `vrrp_version` and `vrrp_check_unicast_src`, and `accept`. Also, `state SLAVE` should really be `state BACKUP`, although the only string it checks for is `MASTER`.

You have also configured authentication, but that is not part of VRRPv3, and you have specified vrrp_version 3.

keepalived v1.2.13 is VERY old now. Can you upgrade to v1.3.2 (current version), and see what happens then. You should at least get some error messages for some of the invalid configuration, and it will support all of the features you are attempting to use.

**Comment by Genluck** [comment]
Hello, pqarmitage.

Thank you very much for information. Really need to look at changelog. I thought that it was supported for a long time, because there wasn't been any errors ufter running with this config. It would be good to add comments at the manual that "this command" was added at "####/##/##".

Updating to lates version is very hard, because we have a CentOS 6.8 as corporate standart and the last version at epel is 1.2.13.

Will be thinking what to do for upgrading.

Best Regards.

**Comment by pqarmitage** [comment]
One of the problems with keepalived is that in the past it has silently ignored unknown keywords, although it is a lot better at reporting them in recent versions.

It's not a nice solution to what you want to do, but you could use a notify script to add the ip rules and ip routes. It the state (parameter 3) is MASTER, add the rules/routes, if it is anything else remove them. Please be aware that there are potential security implications with notify (and other) scripts. If you are running any version prior to 1.3 it is important to ensure that no-one other than the root user can modify the script, or any part of the path of the script.

I think the expectation is that people will look at either keepalived.conf(5) man page or the doc/keepalived.conf.SYNOPSIS that relates to the version of keepalived that they are running, in which case if it is the documentation it will be supported!

I you would like to update the current keepalived.conf.SYNOPSIS, or the keepalived.conf(5) man page with the version at which each config option was added, we will willingly merge it (after all, keepalived is an open source collaborative project!).

**Comment by Genluck** [comment]
Hi, pqarmitage.

Thanks for the idea. I will use your suggestion as the latest decision. Maybe it will be possible to install application from sources.

I did use a online manual and it was from the latest verwsion. Thanks for advice about using a manual from the current version.

I will try to update manual at the free time.

Thanks a lot for the help.
