### ISSUE TITLE
I can telnet to rs OK  but Activating healthchecker for service failed 

### ISSUE THREAD

**Issue by liangshaopeng** [acassen/keepalived#493]
this is version：
![image](https://cloud.githubusercontent.com/assets/8167269/21798699/e0e6a4b0-d750-11e6-98bd-4de9873e3dd8.png)

rs：54.192.75.240  (amazon.com cdn server)
when i see Activating healthchecker for service [54.192.75.240]:80 
i found the healthchecker tcp connection is ok :
![image](https://cloud.githubusercontent.com/assets/8167269/21798197/24c925ac-d74e-11e6-9093-74d0d359d01f.png)
but at same time from /var/log/messages  [54.192.75.240]:80  is failed!!!
![image](https://cloud.githubusercontent.com/assets/8167269/21798201/2a8fb956-d74e-11e6-92e1-e8cddd147de9.png)
and i try to telnet  [54.192.75.240]:80  it's ok 
![image](https://cloud.githubusercontent.com/assets/8167269/21799069/aa556a56-d752-11e6-8140-a97fbaff1930.png)

so i feel puzzled...
and i tcpdump :
![image](https://cloud.githubusercontent.com/assets/8167269/21799107/cf672b40-d752-11e6-82f0-4d23720d8c7c.png)
i think before190 the tcp connection has done and it's ok。
why healthchecker for service [54.192.75.240]:80  failed!!! 
ps:100.64.1.1 is gre tunnel src addr

**Comment by liangshaopeng** [comment]
![image](https://cloud.githubusercontent.com/assets/8167269/21799394/010bbf20-d754-11e6-9ced-cd6db2d71a3d.png)
 telnet packets：
![image](https://cloud.githubusercontent.com/assets/8167269/21799438/39f495e6-d754-11e6-9cbb-96d47945783a.png)
keepalive packets：
![image](https://cloud.githubusercontent.com/assets/8167269/21799536/9f62b250-d754-11e6-9abf-80c1b0dc1cd5.png)

**Comment by pqarmitage** [comment]
It appears that for some reason 54.192.75.240 is not seeing the ACK packet from 100.64.1.1, hence the "TCP Spurious Retransmission". Your end (100.64.1.1) thinks the TCP connection is established, but it looks as though 54.192.75.240 doesn't think the connection has completed. I do not get the "TCP Spurious Retransmission" when I manually establish a telnet connection to 54.192.75.240:80.

When you manually establish a TCP connection, if you type something after the `Escape character is '^]'.` output, do you get any response (I get some html output)?

It looks as though this is not a kepalived issue, but that you have a connectivity issue with 54.192.75.240.

**Comment by pqarmitage** [comment]
Closing due to no response for over 2 months.
