### ISSUE TITLE
IPv6 and IPv4 in Keepalived 1.3.2

### ISSUE THREAD

**Issue by twm139** [acassen/keepalived#500]
Sorry to start a new thread but there is something in my config that must be wrong but I just cannot figure it out and it does not seem to be answered in the other thread.  

CentOS 7.x with latest patches 1/18/2017
Keepalived build on the system grabbed from GitHub with the recent spec file fix to build on RHEL7

The setup is pretty simple 

- Direct routing (no NAT)
- One service across 6 servers on port 2811, basically ftp servers. 
- two LVS servers
- IPv4 and IPv6

IPv4 works fine, and I can see the servers and I can transfer to them fine but the IPv6 servers do not show up under 

ipvsadm
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  gftp.t2.ucsd.edu:gsiftp wrr
  -> gftp-1.t2.ucsd.edu:gsiftp    Route   1      0          1
  -> gftp-2.t2.ucsd.edu:gsiftp    Route   1      0          1
  -> gftp-3.t2.ucsd.edu:gsiftp    Route   1      0          2
  -> gftp-4.t2.ucsd.edu:gsiftp    Route   1      0          2
  -> gftp-5.t2.ucsd.edu:gsiftp    Route   1      0          2
  -> gftp-6.t2.ucsd.edu:gsiftp    Route   1      0          2

Below are my MASTER configs and the start log. The BACKUP server config is the same. 

[keepalived.txt](https://github.com/acassen/keepalived/files/715578/keepalived.txt)
[StartLog.txt](https://github.com/acassen/keepalived/files/715579/StartLog.txt)

Thanks for any tips.

**Comment by pqarmitage** [comment]
I think the clue is the following entries in the start log:
```
Jan 18 18:59:58 lvs-1 Keepalived_healthcheckers[18268]: IPVS: Operation not supported with specified address family
Jan 18 18:59:58 lvs-1 Keepalived_healthcheckers[18268]: IPVS: Operation not supported with specified address family
Jan 18 18:59:58 lvs-1 Keepalived_healthcheckers[18268]: IPVS: Operation not supported with specified address family
Jan 18 18:59:58 lvs-1 Keepalived_healthcheckers[18268]: IPVS: Operation not supported with specified address family
Jan 18 18:59:58 lvs-1 Keepalived_healthcheckers[18268]: IPVS: Operation not supported with specified address family
Jan 18 18:59:58 lvs-1 Keepalived_healthcheckers[18268]: IPVS: Operation not supported with specified address family
Jan 18 18:59:58 lvs-1 Keepalived_healthcheckers[18268]: IPVS: Operation not supported with specified address family
```
(the number of these log entries matches the number of ipvs commands that would be executed (one for adding the real server, and 6 for the 6 virtual servers).

Can you try entering the following commands as root and see whether you get an error or not:
```
ipvsadm -A -t [2607:f720:1700:1b30::80]:2811 -s wrr
ipvsadm -a -t [2607:f720:1700:1b30::80]:2811 -r [2607:f720:1700:1b30::8:2811 -m
```

I have run your config on a Centos 7 VM with kernel 3.10.0-514.2.2.el7 and it successfully loads the ipvs configuration, without the error messages I have highlighted above.

It looks as though for some reason your system isn't supporting IPVS over IPv6.

**Comment by twm139** [comment]
I completely agree the problem seems to be in those lines in the error log and something about the setup/config is not allowing those lines to work. 

ipvsadm -A -t [2607:f720:1700:1b30::80]:2811 -s wrr
ipvsadm -a -t [2607:f720:1700:1b30::80]:2811 -r [2607:f720:1700:1b30::83]:2811

I made a couple changes to fix the syntax and to make it a direct route.

It works fine.

[1032] root@lvs-2 ~# ipvsadm -a -t [2607:f720:1700:1b30::80]:2811 -r [2607:f720:1700:1b30::83]:2811
[1033] root@lvs-2 ~# ipvsadm
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  gftp.t2.ucsd.edu:gsiftp wlc
  -> gftp-1.t2.ucsd.edu:gsiftp    Route   1      0          0        
  -> gftp-2.t2.ucsd.edu:gsiftp    Route   1      0          0        
  -> gftp-3.t2.ucsd.edu:gsiftp    Route   1      0          0        
  -> gftp-4.t2.ucsd.edu:gsiftp    Route   1      0          0        
  -> gftp-5.t2.ucsd.edu:gsiftp    Route   1      0          0        
  -> gftp-6.t2.ucsd.edu:gsiftp    Route   1      0          0        
TCP  [2607:f720:1700:1b30::80]:gsiftp wrr
  -> [2607:f720:1700:1b30::83]:gsiftp Route   1      0          0        
[1033] root@lvs-2 ~#

The same on the other host that is running the 514.2.2 kernel.

With the above I can now ping the grid ftp server and I can connect through the control channel, though the data channel is still not working. That may be a different issue. It is not a firewall issue in any case, unless no firewalld running is equally as problematic as having it running. :)

Is there some subtle way I am screwing up the IPv6 addresses in my config file that causes that initial setup to mess up? I have the same error on two systems that should be identical. 

I guess I could try to go with a much simpler config and see if I can get at least one IPv6 address to load. Suggestions?

**Comment by pqarmitage** [comment]
Yes, I think trying to create a minimal config and seeing if it still demonstrates the problem would be the way to go, and if not gradually adding config until it fails.

It would be interesting to try running keepalived after the ipvsadm commands with ipv6 addresses have been successful (but then deleting the added entries) incase the issue relates to a kernel module not being loaded, but which is loaded when the ipvsadm command is run.

Regarding the firewall issue, it is possible that there are firewall entries configured nevertheless. It is also possible that the default action for the INPUT chain for IPv6 is set to DROP rather than ACCEPT. For testing purposes, so long as your systems are otherwise sufficiently secure, it might be worth executing `ip6tables -I INPUT -j ACCEPT` on each system, to ensure that it isn't the firewall that is causing the problem with the data channel.

It's really difficult for me to work out more at the moment about why the IPVS IPv6 keepalived configuration isn't working for you, since I'm not experiencing the problem on my systems, but I'll think on. Any more information you can provide would be helpful.

**Comment by twm139** [comment]
virtual_server 2607:f720:1700:1b30::080 2811 {

  delay_loop 10
  lb_algo wlc
  lb_kind DR
  protocol TCP

  real_server 2607:f720:1700:1b30::084 2811 {
    weight 1
    TCP_CHECK {
     connect_port 2811
     connect_timeout 3
    }
  }
}

I removed the bind for a moment, just to check.

Here is the IP setup from the config

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 0c:c4:7a:88:66:73 brd ff:ff:ff:ff:ff:ff
    inet 169.228.130.131/23 brd 169.228.131.255 scope global enp2s0
       valid_lft forever preferred_lft forever
    inet6 2607:f720:1700:1b30::80/128 scope global deprecated nodad 
       valid_lft forever preferred_lft 0sec
    inet6 2607:f720:1700:1b30::83/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::da7a:f33d/128 scope link deprecated nodad 
       valid_lft forever preferred_lft 0sec
    inet6 fe80::ec4:7aff:fe88:6673/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by twm139** [comment]
Sorry to answer the other question, restarting keepalived after adding the entries then deleting them manually still results in the same error.

**Comment by twm139** [comment]
Also this is the configuration that Keepalive wants to build as. 

Keepalived configuration
------------------------
Keepalived version       : 1.3.2
Compiler                 : gcc
Preprocessor flags       : 
Compiler flags           : -Wall -Wunused -Wstrict-prototypes -Wextra -g -O2
Linker flags             : 
Extra Lib                : -ldl -lssl -lcrypto 
Use IPVS Framework       : Yes
IPVS use libnl           : No
IPVS syncd attributes    : No
IPVS 64 bit stats        : No
fwmark socket support    : Yes
Use VRRP Framework       : Yes
Use VRRP VMAC            : Yes
Use VRRP authentication  : Yes
With ip rules/routes     : Yes
SNMP vrrp support        : No
SNMP checker support     : No
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
DBUS support             : No
SHA1 support             : No
Use Debug flags          : No
Stacktrace support       : No
Memory alloc check       : No
libnl version            : None
Use IPv4 devconf         : No
Use libiptc              : No
Use libipset             : No
init type                : systemd
Build genhash            : Yes
Build documentation      : Yes

**Comment by twm139** [comment]
Even on the remove keepalived does like those addresses. 

Jan 20 11:47:59 lvs-2 Keepalived_healthcheckers[10652]: Removing service [2607:f720:1700:1b30::84]:2811 from VS [2607:f720:1700:1b30::80]:2811
Jan 20 11:47:59 lvs-2 Keepalived_healthcheckers[10652]: IPVS (cmd 1160, errno 97): Operation not supported with specified address family
Jan 20 11:47:59 lvs-2 Keepalived_healthcheckers[10652]: Removing service [2607:f720:1700:1b30::85]:2811 from VS [2607:f720:1700:1b30::80]:2811
Jan 20 11:47:59 lvs-2 Keepalived_healthcheckers[10652]: IPVS (cmd 1160, errno 97): Operation not supported with specified address family
Jan 20 11:47:59 lvs-2 Keepalived_healthcheckers[10652]: Removing service [2607:f720:1700:1b30::86]:2811 from VS [2607:f720:1700:1b30::80]:2811
Jan 20 11:47:59 lvs-2 Keepalived_healthcheckers[10652]: IPVS (cmd 1160, errno 97): Operation not supported with specified address family
Jan 20 11:47:59 lvs-2 Keepalived_healthcheckers[10652]: Removing service [2607:f720:1700:1b30::87]:2811 from VS [2607:f720:1700:1b30::80]:2811
Jan 20 11:47:59 lvs-2 Keepalived_healthcheckers[10652]: IPVS (cmd 1160, errno 97): Operation not supported with specified address family
Jan 20 11:47:59 lvs-2 Keepalived_healthcheckers[10652]: Removing service [2607:f720:1700:1b30::88]:2811 from VS [2607:f720:1700:1b30::80]:2811
Jan 20 11:47:59 lvs-2 Keepalived_healthcheckers[10652]: IPVS (cmd 1160, errno 97): Operation not supported with specified address family
Jan 20 11:47:59 lvs-2 Keepalived_healthcheckers[10652]: Removing service [2607:f720:1700:1b30::89]:2811 from VS [2607:f720:1700:1b30::80]:2811
Jan 20 11:47:59 lvs-2 Keepalived_healthcheckers[10652]: IPVS (cmd 1160, errno 97): Operation not supported with specified address family
Jan 20 11:47:59 lvs-2 Keepalived_healthcheckers[10652]: IPVS (cmd 1156, errno 97): Operation not supported with specified address family

Also this is after I manually added. 

TCP  [2607:f720:1700:1b30::80]:gsiftp wrr
  -> [2607:f720:1700:1b30::84]:gsiftp Route   1      0          0         
  -> [2607:f720:1700:1b30::85]:gsiftp Route   1      0          0         
  -> [2607:f720:1700:1b30::86]:gsiftp Route   1      0          0         
  -> [2607:f720:1700:1b30::87]:gsiftp Route   1      0          0         
  -> [2607:f720:1700:1b30::88]:gsiftp Route   1      0          0         
  -> [2607:f720:1700:1b30::89]:gsiftp Route   1      0          0

**Comment by twm139** [comment]
Ok so the issue was that you need to install libnl before you build. 

libnl version : None

Should be 

libnl version : 1

libnl.x86_64 0:1.1.4-3.el7

Without that library this is the error you get. 

Jan 18 18:59:58 lvs-1 Keepalived_healthcheckers[18268]: IPVS: Operation not supported with specified address family

**Comment by pqarmitage** [comment]
Many thanks for your work on this. I'll have a look and see if I can work out why this makes a difference, and incorporate something into configure.ac if possible.

BTW, if you install the following packages, you will get a better performing version of keepalived:
   libnl3-devel iptables-devel ipset-devel libnfnetlink-devel

Installing the above packages should make the following changes to the output of configure:
IPVS use libnl : Yes
libnl version : 3
Use libiptc : Yes
Use libipset : Yes

**Comment by pqarmitage** [comment]
The problem above was originally caused by keepalived being build without libnl/libnl-3, and then attempting to use IPv6 with IPVS. When using the socket interface to configure IPVS (rather than the netlink interface), IPv6 isn't supported. Commit 343109b now reports both at build time and run time that IPv6 isn't supported with IPVS if keepalived is build without libnl support.
