### ISSUE TITLE
致命错误：linux/mpls.h：没有那个文件或目录

### ISSUE THREAD

**Issue by li1191863273** [acassen/keepalived#501]
I user CentOS Linux release 7.3.1611 (Core), keepalived1.3.2
It happen errors when install 
hint message linux/mpls.h：not found
How to solve it?

**Comment by pqarmitage** [comment]
Commit c134bf4 resolves the issue you have here. If you pull the latest code from github.com/acassen/keepalived it should solve your problem.

The issue was caused by RedHat adding a partial backport of lightweight tunnels, but not including the MPLS code.

**Comment by li1191863273** [comment]
Thank you
