### ISSUE TITLE
could not manage iproute2 rules for vmac interface

### ISSUE THREAD

**Issue by kam1kaze** [acassen/keepalived#507]
Hello,

I need to manage iproute2 rules and routes for virtual mac interface. Unfortunately, I couldn't do this because vmac interface does not exist when the rules are applied.

Example block:
```
vrrp_instance pr_inside_network {
  ...
  use_vmac vrrp.51
  vmac_xmit_base
  virtual_ipaddress {
    10.6.0.254/16 brd 10.6.255.255
  }
  virtual_routes {
    10.6.0.0/16 dev vrrp.51 src 10.6.0.254 table 51
  }
  virtual_rules {
    from 10.6.0.254/32 table 51
    iif vrrp.51 table 51
  }
}
```

Here is logs where you could see the problem:
```
Starting Keepalived v1.3.2 (11/29,2016)
WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Opening file '/etc/keepalived/keepalived.conf'.
Starting VRRP child process, pid=42
Netlink reflector reports IP 10.6.4.9 added
Registering Kernel netlink reflector
Registering Kernel netlink command channel
Registering gratuitous ARP shared channel
Opening file '/etc/keepalived/keepalived.conf'.
Truncating auth_pass to 8 characters
Truncating auth_pass to 8 characters
VRRP is trying to assign VROUTE to unknown vrrp.51 interface !!! go out and fix your conf !!!
Unknown interface vrrp.51 for rule
VRRP_Instance(pr_outside_network) removing protocol Virtual Routes
VRRP_Instance(pr_outside_network) removing protocol VIPs.
vmac: Success creating VMAC interface vrrp.51 for vrrp_instance pr_inside_network
------< Global definitions >------
...
------< VRRP Topology >------
...
 VRRP Instance = pr_inside_network
   Using VRRPv2
   Want State = MASTER
   Running on device = vrrp.51
   Skip checking advert IP addresses = no
   Enforcing strict VRRP compliance = no
   Using src_ip = 10.6.4.9
   Gratuitous ARP delay = 5
   Gratuitous ARP repeat = 5
   Gratuitous ARP refresh timer = 0
   Gratuitous ARP refresh repeat = 1
   Gratuitous ARP lower priority delay = 5
   Gratuitous ARP lower priority repeat = 5
   Send advert after receive lower priority advert = true
   Virtual Router ID = 51
   Priority = 100
   Advert interval = 1 sec
   Accept enabled
   Promote_secondaries disabled
   Authentication type = SIMPLE_PASSWORD
   Password = ***
   Virtual IP = 1
     10.6.0.254/16 brd 10.6.255.255 dev vrrp.51 scope global
   Generic state transition script = /etc/keepalived/notify, uid:gid 0:0
   Using smtp notification
   Using VRRP VMAC (flags:UP|xmit_base), vmac ifindex 3
```

**Comment by kam1kaze** [comment]
After some additional research. During the first run of keepalived, the config validator/parser executes before virtual mac (use_vmac) interface, so all ip_route2 rules/routes related to vmac are ignored. When I send HUP signal to keepalived process, all rules are added to the configuration. 

```
 VRRP Instance = pr_inside_network
   Using VRRPv2
   Want State = MASTER
   Running on device = vrrp.51
   Skip checking advert IP addresses = no
   Enforcing strict VRRP compliance = no
   Using src_ip = 10.6.4.9
   Gratuitous ARP delay = 5
   Gratuitous ARP repeat = 5
   Gratuitous ARP refresh timer = 0
   Gratuitous ARP refresh repeat = 1
   Gratuitous ARP lower priority delay = 5
   Gratuitous ARP lower priority repeat = 5
   Send advert after receive lower priority advert = true
   Virtual Router ID = 51
   Priority = 100
   Advert interval = 1 sec
   Accept enabled
   Promote_secondaries disabled
   Authentication type = SIMPLE_PASSWORD
   Password = ***
   Virtual IP = 1
     10.6.0.254/16 brd 10.6.255.255 dev vrrp.51 scope global
   Virtual Routes = 1
      10.6.0.0/16 src 10.6.0.254 dev vrrp.51 table 51
   Virtual Rules = 2
     from 10.6.0.254 lookup 51
     from all iif vrrp.51 lookup 51
   Using smtp notification
   Using VRRP VMAC (flags:UP|xmit_base), vmac ifindex 3
```

As workaround I've wrote notify script that send HUP signal when by pattern :)

```
After some additional research. During the first run of keepalived, the config validator/parser executes before virtual mac (use_vmac) interface, so all ip_route2 rules/routes related to vmac are ignored. When I send HUP signal to keepalived process, all rules are added to the configuration. 

```
 VRRP Instance = pr_inside_network
   Using VRRPv2
   Want State = MASTER
   Running on device = vrrp.51
   Skip checking advert IP addresses = no
   Enforcing strict VRRP compliance = no
   Using src_ip = 10.6.4.9
   Gratuitous ARP delay = 5
   Gratuitous ARP repeat = 5
   Gratuitous ARP refresh timer = 0
   Gratuitous ARP refresh repeat = 1
   Gratuitous ARP lower priority delay = 5
   Gratuitous ARP lower priority repeat = 5
   Send advert after receive lower priority advert = true
   Virtual Router ID = 51
   Priority = 100
   Advert interval = 1 sec
   Accept enabled
   Promote_secondaries disabled
   Authentication type = SIMPLE_PASSWORD
   Password = ***
   Virtual IP = 1
     10.6.0.254/16 brd 10.6.255.255 dev vrrp.51 scope global
   Virtual Routes = 1
      10.6.0.0/16 src 10.6.0.254 dev vrrp.51 table 51
   Virtual Rules = 2
     from 10.6.0.254 lookup 51
     from all iif vrrp.51 lookup 51
   Using smtp notification
   Using VRRP VMAC (flags:UP|xmit_base), vmac ifindex 3
```

As workaround do config reload via notify script when server is up

``
After some additional research. During the first run of keepalived, the config validator/parser executes before virtual mac (use_vmac) interface, so all ip_route2 rules/routes related to vmac are ignored. When I send HUP signal to keepalived process, all rules are added to the configuration. 

```
 VRRP Instance = pr_inside_network
   Using VRRPv2
   Want State = MASTER
   Running on device = vrrp.51
   Skip checking advert IP addresses = no
   Enforcing strict VRRP compliance = no
   Using src_ip = 10.6.4.9
   Gratuitous ARP delay = 5
   Gratuitous ARP repeat = 5
   Gratuitous ARP refresh timer = 0
   Gratuitous ARP refresh repeat = 1
   Gratuitous ARP lower priority delay = 5
   Gratuitous ARP lower priority repeat = 5
   Send advert after receive lower priority advert = true
   Virtual Router ID = 51
   Priority = 100
   Advert interval = 1 sec
   Accept enabled
   Promote_secondaries disabled
   Authentication type = SIMPLE_PASSWORD
   Password = ***
   Virtual IP = 1
     10.6.0.254/16 brd 10.6.255.255 dev vrrp.51 scope global
   Virtual Routes = 1
      10.6.0.0/16 src 10.6.0.254 dev vrrp.51 table 51
   Virtual Rules = 2
     from 10.6.0.254 lookup 51
     from all iif vrrp.51 lookup 51
   Using smtp notification
   Using VRRP VMAC (flags:UP|xmit_base), vmac ifindex 3
```

As workaround, I've wrote the script that send HUP signal via notify param:

```
#!/bin/bash

# Save last run log for debugging
set -x
exec > /tmp/notify.log 2>&1

pid=$(pgrep -o keepalived)
kill -USR1 $pid
fgrep 'src 10.6.0.254' /tmp/keepalived.data || kill -HUP $pid
```

**Comment by commonism** [comment]
I'm facing the same problem.

Workign with the example given:

```
vrrp_instance pr_inside_network {
  ...
  use_vmac vrrp.51
  vmac_xmit_base
  virtual_ipaddress {
    10.6.0.254/16 brd 10.6.255.255 dev vrrp.51
  }
  virtual_routes {
    10.6.0.0/16 dev vrrp.51 src 10.6.0.254 metric 1
  }
}
```

This is a valid use case, as it adds the routes specifically for the vrrp created interface. Having two interfaces in the same network requires using routing metrics. This setup adds a route with a metric for the VRRP interface.

This setup was working before (at least in 1.2.13 -debian jessie-), but current keepalived does not allow using the VRRP Interface name for virtual routes, as it does not exist.

Maybe broken in https://github.com/acassen/keepalived/commit/238b91d1782516c90747f636e38c65cc6b2f553e

I guess it may be possible to create a macvlan interface manually and have keepalived use the existing interface instead of creating the interface himself, but ... having keepalived taking care of creating the interfaces is more comfortable.

**Comment by kam1kaze** [comment]
@commonism I did the same. Rewrote configuration, so all VMAC interfaces are managed by external configuration management system.

**Comment by pqarmitage** [comment]
@commonism Thanks for the use description. I can now see the logic for having routes configured on the vmac interface (and I presume the same applies to ip rules too).

I've been working on a major development and a side effect of that is that it will be able to handle routes that are specified for interfaces that don't exist when keepalived starts. I'll ensure that it can handle this scenario.

**Comment by Rocco83** [comment]
@commonism i have tested your conf in Debian Jessie.

```
vrrp_instance pr_inside_network {
    state MASTER
    interface eth0
  use_vmac vrrp.51
  vmac_xmit_base
  virtual_ipaddress {
    10.6.0.254/16 brd 10.6.255.255 dev vrrp.51
  }
  virtual_routes {
    10.6.0.0/16 dev vrrp.51 src 10.6.0.254 metric 1
  }
}
```


root@test:/etc/keepalived# keepalived -Dnl -f /etc/keepalived/keepalived.conf.test 
Starting Healthcheck child process, pid=22224
Starting VRRP child process, pid=22225
[...]
VRRP is trying to assign VIP to unknown vrrp.51 interface !!! go out and fix your conf !!!
VRRP is trying to assign VROUTE to unknown vrrp.51 interface !!! go out and fix your conf !!!
VRRP_Instance(pr_inside_network) the virtual id must be set!
[...]
```

What am i doing wrongly? Have you tested this config in Debian Jessie?
Or should we declare the way to assign ip address on vmac interface fully broken even in Debian Jessie, with the need to use an external script at least as temporary workaround?

**Comment by pqarmitage** [comment]
@Rocco83 Remove the dev vrrp.1 from the virtual ip address (the interface that the vrrp instance is operating on is the default interface for virtual addresses, and the vrrp.1 interface doesn't exist when the configuration is read). Remove the virtual_routes section - the kernel will add that route anyway.

You will also need to add a line:
`virtual_router_id 1`
The 1 can be any number from 1 to 255.

I would also remove the `state MASTER` and `vmac_xmit_base` lines. The `state MASTER` will have no effect unless the priority is 255, and unless you have a specific need for `vmac_xmit_base` it will cause the VRRP packets not to have the 00:00:5e:00:01:id MAC address.

So the following should work:
```
vrrp_instance pr_inside_network {
    interface eth0
  use_vmac vrrp.51
  virtual_ipaddress {
    10.6.0.254/16 brd 10.6.255.255
  }
}
```

**Comment by pqarmitage** [comment]
I can confirm that this works with the beta branch.

**Comment by Rocco83** [comment]
Has this bug been fixed on released version? if so, in which version?

**Comment by pqarmitage** [comment]
This is still just in the beta branch.

**Comment by pqarmitage** [comment]
This is now fully supported in the released version.
