### ISSUE TITLE
VMAC and VLAN : Physical address, not virtual one

### ISSUE THREAD

**Issue by dominiquefournier** [acassen/keepalived#511]
Hi !
I try to have a HA firewall with VLAN and VMAC, but actually, the clients don't learn the MAC address by ARP correctely. I see in the sniffer that the gratuitous arp is correctely sent by keepalived, but if the ARP is loosed, the client can't found the right ARP anymore.  The recorded ARP is then the VLAN (or eth1) one and not the virtual one.

When I try to use the sysctl parameters provided in the doc, I was not able to have an ARP answer from the keepalived server, and I am forced to use the default sysctl configuration of the server, which is bad.

Do you have an example of working configuration for VMAC and VLAN ?

I may add that the test environnement is based on Virtualbox with promiscuous mode activated.

Thanks !

**Comment by pqarmitage** [comment]
The following is a simple working configuration:
```
vrrp_instance VI_0 {
	interface eth0.4
	virtual_router_id 1
	priority 170
	advert_int 4
	version 3
	use_vmac
	virtual_ipaddress {
		10.1.0.254/32
	}
}
```
I use VMAC over VLANs extensively without any problems.

What version of keepalived are you using? Some time ago I added functionality to keepalived to set the necessary sysctl parameters to make keepalived work with VMACs, so if you are running an old version it may not havethat functionality.

**Comment by dominiquefournier** [comment]
My problem was due to a bad copy/paste : I forget to change the interface in the instance, after my tests on the real interface. So the MAC of the real interface answer.

It is working well with the version 1.3.2 (Debian Testing) with virtual MAC, but not on the version 1.2.13 (Debian Stable), answer with physical MAC.
Do you have a list of mandatory sysctl for 1.3.2 ?

Thanks a lot !

**Comment by pqarmitage** [comment]
It would have been version 1.2.20 or later when I added the sysctl settings into keepalived, so I wouldn't expect version 1.2.13 to work unless the settings are handled in a notify script.

For the sysctl parameters that keepalived sets, see source file keepalived/vrrp/vrrp_if_config.c. I don't need to set any other sysctl parameters on any of my systems to make keepalived work, with or without VMACs.

**Comment by dominiquefournier** [comment]
You are the best !
I tweak the interface by:
 logger "Tweak interface $1"
echo 1 > /proc/sys/net/ipv4/conf/$1/arp_ignore
echo 1 > /proc/sys/net/ipv4/conf/$1/accept_local
echo 0 > /proc/sys/net/ipv4/conf/$1/rp_filter
echo 1 > /proc/sys/net/ipv4/conf/$1/promote_secondaries

And the system is tweak with:
## VMAC Support
net.ipv4.conf.all.arp_ignore=1
net.ipv4.conf.all.arp_announce=1
net.ipv4.conf.default.arp_announce=1
net.ipv4.conf.eth0.arp_announce=1
net.ipv4.conf.eth1.arp_announce=1
net.ipv4.conf.eth2.arp_announce=1
net.ipv4.conf.all.arp_filter=0
net.ipv4.conf.eth0.arp_filter=1
net.ipv4.conf.eth1.arp_filter=1
net.ipv4.conf.eth2.arp_filter=1
net.ipv4.conf.vlan90.arp_filter=1
net.ipv4.conf.vlan91.arp_filter=1
net.ipv4.conf.vlan92.arp_filter=1

# VLAN OK
# Solution : mettre 2 !
net.ipv4.conf.all.rp_filter=2
net.ipv4.conf.default.rp_filter=2
net.ipv4.conf.eth0.rp_filter=2
net.ipv4.conf.eth1.rp_filter=2
net.ipv4.conf.eth2.rp_filter=2
net.ipv4.conf.vlan90.rp_filter=2
net.ipv4.conf.vlan91.rp_filter=2
net.ipv4.conf.vlan92.rp_filter=2

Thanks a lot !!!
