### ISSUE TITLE
Make error for 1.3.2 

### ISSUE THREAD

**Issue by skyfish69** [acassen/keepalived#514]
Hi , 

Happen following error when make for v1.3.2 source code.Apprecicate for any help in advance.  

Making all in lib
make[1]: Entering directory `/root/keepalived-1.3.2/lib'
make  all-am
make[2]: Entering directory `/root/keepalived-1.3.2/lib'
make[2]: Leaving directory `/root/keepalived-1.3.2/lib'
make[1]: Leaving directory `/root/keepalived-1.3.2/lib'
Making all in keepalived
make[1]: Entering directory `/root/keepalived-1.3.2/keepalived'
Making all in core
make[2]: Entering directory `/root/keepalived-1.3.2/keepalived/core'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/keepalived-1.3.2/keepalived/core'
Making all in vrrp
make[2]: Entering directory `/root/keepalived-1.3.2/keepalived/vrrp'
  CC       vrrp_daemon.o
In file included from vrrp_daemon.c:37:0:
./../include/vrrp_iproute.h:32:24: fatal error: linux/mpls.h: No such file or directory
 #include <linux/mpls.h>
                        ^
compilation terminated.
make[2]: *** [vrrp_daemon.o] Error 1
make[2]: Leaving directory `/root/keepalived-1.3.2/keepalived/vrrp'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/keepalived-1.3.2/keepalived'
make: *** [all-recursive] Error 1

**Comment by skyfish69** [comment]
i tried to compile latest code from master branch and there are following error when run make command.

Making all in lib
make[1]: Entering directory `/root/keepalived-master/lib'
make  all-am
make[2]: Entering directory `/root/keepalived-master/lib'
  CC       memory.o
  CC       utils.o
  CC       notify.o
  CC       timer.o
  CC       scheduler.o
  CC       vector.o
  CC       list.o
  CC       html.o
  CC       parser.o
  CC       signals.o
  CC       logger.o
  CC       rttables.o
  AR       liblib.a
make[2]: Leaving directory `/root/keepalived-master/lib'
make[1]: Leaving directory `/root/keepalived-master/lib'
Making all in keepalived
make[1]: Entering directory `/root/keepalived-master/keepalived'
Making all in core
make[2]: Entering directory `/root/keepalived-master/keepalived/core'
  CC       main.o
main.c:50:64: error: expected ',' or ';' before 'GIT_DATE'
 #define VERSION_STRING  PACKAGE_NAME " v" PACKAGE_VERSION " (" GIT_DATE ")"
                                                                ^
main.c:57:30: note: in expansion of macro 'VERSION_STRING'
 const char *version_string = VERSION_STRING;  /* keepalived version */
                              ^
main.c: In function 'parse_cmdline':
main.c:51:47: error: expected ')' before 'GIT_YEAR'
 #define COPYRIGHT_STRING "Copyright(C) 2001-" GIT_YEAR " Alexandre Cassen, <acassen@gmail.com>"
                                               ^
main.c:631:34: note: in expansion of macro 'COPYRIGHT_STRING'
    fprintf(stderr, "\n\n%s\n\n", COPYRIGHT_STRING);
                                  ^
make[2]: *** [main.o] Error 1
make[2]: Leaving directory `/root/keepalived-master/keepalived/core'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/keepalived-master/keepalived'
make: *** [all-recursive] Error 1

**Comment by pqarmitage** [comment]
The reason for the first build error is the partial backport in the kernel of light weight tunnels (I presume this is a RedHat based system you are using). This was resolved in commit c134bf4, which was not in version 1.3.2, but will have been resolved by you pulling master.

Regarding the second problem, can you check in lib/git-commit.h to see if GIT_DATE is defined, and if so, please post the definition. It should be something like `"01/26,2017"`. Likewise GIT_YEAR should be defined as `"2017"`.

After pulling master, did you run autoreconf? It might be that lib/Makefile is not up-to-date.

**Comment by pqarmitage** [comment]
I've now found that there is a problem building when the version of the source code has a git tag (which it does for a released version of keepalived). Commit bd8f6bc resolves the problem.

With apologies for any difficulties caused.
