### ISSUE TITLE
Compiling on CentOS 7 issues

### ISSUE THREAD

**Issue by agibson2** [acassen/keepalived#516]
There were a few things I had to do to get this to compile on CentOS7.  I am posting this mainly to see if there is something that can be done upstream so that the latest version of RHEL and CentOS7 can be supported by keepalived 1.3.2.

First issue was that keepalived requires automake 1.15.  CentOS 7 only has 1.13.  I resolved this by using autotools from softwarecollections.org (SCL) which the site seems to be somehow tied to RedHat which serves the purpose of allowing third parties to package alternative versions of apps to be installed and switch to them at a shell prompt to compile things.
https://www.softwarecollections.org/repos/praiskup/autotools/epel-7-x86_64/noarch/

Once you have the yum repo installed from the link above you can install autotools 1.15.
# yum install autotools-latest

They will not overwrite your existing autotools install and will only be enabled in a shell via the command below.  Once you issue the command below you can compile or build your RPM under that new shell environment.
# scl enable autotools-latest bash

Because of the alternative autotools install from SCL another issue appeared because of that alternative autotools install.  The aclocal defaults in the scl autotools for the pkgconfig m4 files directory is wrong(pgk.m4 for example should be in there).  You get an error below during configure.

PKG_PROG_PKG_CONFIG: command not found

I had to modify the rpm SPEC file to add the line below just underneath the %build line in the SPEC file to get past that issue.  The line below points the SCL version of autotools to use the base CentOS pkgconfig m4 directory.

%build
export ACLOCAL_PATH=/usr/share/aclocal

The third issue was of the known issue where redhat made a kernel change.  I had to take the patch from the commit below and modify it (only the position of where lines get put in) to make it apply cleanly to the official 1.3.2 build.  It is attached.  I added that patch to the RPM spec file.
https://github.com/acassen/keepalived/commit/c134bf4f13bb57e5b5c77a608ef5699d4eb34582
[keepalived_1.3.2_centos73_patch.zip](https://github.com/acassen/keepalived/files/767733/keepalived_1.3.2_centos73_patch.zip)

After that I had a fully functional keepalived-1.3.2 RPM that is working fine so far.

Also... a big thank you to all the developers.  The enhancements going from the CentOS 7 included keepalived-1.2.13 to 1.3.2 was huge.  State information dump via USR1 and USR2, @ macros to have a single config file for both systems, better emails alerts of switches, etc.

FYI... I only use VRRP portion of keepalived for IP failover for multiple interfaces.  I don't use LVS stuff.

Any chance of autotools 1.13 becoming the minimum version?  I assume the kernel problem above will be in the next 1.3.3 build since it was already commited. The autotools version is the biggest hurdle.

**Comment by fenice2** [comment]
I'm not a developer but I've just built this on a CentOS7 server without problems but a couple of minor hiccups. For the automake 'problem' I just ran  "autoreconf -f -i"  and everything worked after that, the build worked and 1.3.2 is  now installed and wor4king fine on my servers. Doesn't that solve the problem or am I missing something?

**Comment by agibson2** [comment]
I am not familiar with autoconf or automake.  I will have to test that out.  Thanks!  I assumed 1.13 was required based on the error that came back which stated that.  All that wasted time if that solves it.  :)

**Comment by agibson2** [comment]
That fixed it.  I just put the 'autoreconf -f -i' in the SPEC file right after %setup.  I also had to add the custom patch that I included above as that patch is not in the stable 1.3.2 release.

%setup
autoreconf -f -i

Thanks.

**Comment by pqarmitage** [comment]
Many thanks for finding the problem. One of the difficulties is that the rpmbuild doesn't have the problem on CentOS 7 if configure/configure.ac aren't patched.

The underlying cause here is that patching configure/configure.ac causes some of the autoconf/automake generated to be regenerated, and since the versions of autoconf/automake on CentOS 7 are different from the versions on the systems that generated the autoconf/automake files that are commited to git, they ends up with mismatched versions of files.

Commit 7bb10c6 updates the keepalived.spec file to add `autoreconf -f -i` as suggested above.
