### ISSUE TITLE
1.3.3 "make install" installs upstart file; probably shouldn't do this

### ISSUE THREAD

**Issue by otheus** [acassen/keepalived#525]
I'm working on preparing a spec file for the EPEL team (or at least, internal use). The current build output shows that it's trying to install the upstart service:

```
make[3]: Entering directory `/home/c102/c10267/rpmbuild/BUILD/keepalived-1.3.3/keepalived'
...
 /bin/mkdir -p '/home/c102/c10267/rpmbuild/BUILDROOT/keepalived-1.3.3-3.el6_UIBK_ZID.x86_64/etc/init'
 /usr/bin/install -c -m 644 etc/init/keepalived.conf '/home/c102/c10267/rpmbuild/BUILDROOT/keepalived-1.3.3-3.el6_UIBK_ZID.x86_64/etc/init'
```

While I do want to use upstart here, the fact is, installing the script directly from Make presents a problem  for non-upstart systems, especially w.r.t packaging. Note: other packaging systems might depend on this "Feature".

**Comment by otheus** [comment]
Moreover, this upstart conf installation uses a hardcoded configuration file "/usr/local/sbin" which is likely to fail on many systems.

**Comment by otheus** [comment]
Given the limitations of upstart and exsiting sysconfig file,  a more sensible upstart service file would be as follows:

```
description "load-balancing and high-availability service"

start on runlevel [2345]
stop on runlevel [!2345]

respawn

script
        . /etc/sysconfig/keepalived
        exec keepalived --dont-fork ${KEEPALIVED_OPTIONS}
end script
```

There's no reason to set the path here, as that is the responsibility of either the admin or the packager to make sure the PATH is appropriately set. In this case, the PATH can be set in /etc/sysconfig/keepalived if needed. However, I duly must note, this might be a redhat-specific implementation.

**Comment by pqarmitage** [comment]
configure detects the system init type, and the relevant files get installed for that. We could add some override options to configure to allow the desired init type to be specified if it is not the same as the init type on the build system. It that what you need?

Looking at a Ubuntu 14.04 system, the location of executables in most .spec files appears to be hardcoded, although some are not. I wonder if the appropriate upstart service file could be generated when `make` is executed, using sbindir.

**Comment by otheus** [comment]
In the old days, `make install` not do anything to system files because it was considered dangerous to run such a thing as root -- for good reason. The fact that this works at all is because its in a package environment which changes the root installation directory. Nowadays, there are too many options to consider, and the build system can't handle all the cases. Let the packagers do that. (we) have enough trouble as it is, trying to support RPMsfor at least 3 different versions, but this problem is well-understood.

**Comment by pqarmitage** [comment]
Commit dc57f4d removes the hardcoded paths in the init files and uses the appropriate automake variables. It also removes the hardcoded path /etc/sysconfig/keepalived in the upstart file.
