### ISSUE TITLE
Issue building v1.3.4 on CentOS7

### ISSUE THREAD

**Issue by fenice2** [acassen/keepalived#531]
I'm having a problem building the current master branch on CentOS7 (again), all seems to go well during the "make dist" until this point:

make  dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory `/downloads/keepalived-1.3.4'
if test -d "keepalived-1.3.4"; then find "keepalived-1.3.4" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "keepalived-1.3.4" || { sleep 5 && rm -rf "keepalived-1.3.4"; }; else :; fi
test -d "keepalived-1.3.4" || mkdir "keepalived-1.3.4"
 (cd lib && make  top_distdir=../keepalived-1.3.4 distdir=../keepalived-1.3.4/lib \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory `/downloads/keepalived-1.3.4/lib'
make[2]: Leaving directory `/downloads/keepalived-1.3.4/lib'
 (cd keepalived && make  top_distdir=../keepalived-1.3.4 distdir=../keepalived-1.3.4/keepalived \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory `/downloads/keepalived-1.3.4/keepalived'
 (cd core && make  top_distdir=../../keepalived-1.3.4 distdir=../../keepalived-1.3.4/keepalived/core \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/downloads/keepalived-1.3.4/keepalived/core'
make[3]: Leaving directory `/downloads/keepalived-1.3.4/keepalived/core'
 (cd vrrp && make  top_distdir=../../keepalived-1.3.4 distdir=../../keepalived-1.3.4/keepalived/vrrp \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/downloads/keepalived-1.3.4/keepalived/vrrp'
make[3]: Leaving directory `/downloads/keepalived-1.3.4/keepalived/vrrp'
 (cd check && make  top_distdir=../../keepalived-1.3.4 distdir=../../keepalived-1.3.4/keepalived/check \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/downloads/keepalived-1.3.4/keepalived/check'
make[3]: Leaving directory `/downloads/keepalived-1.3.4/keepalived/check'
 (cd dbus && make  top_distdir=../../keepalived-1.3.4 distdir=../../keepalived-1.3.4/keepalived/dbus \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/downloads/keepalived-1.3.4/keepalived/dbus'
make[3]: Leaving directory `/downloads/keepalived-1.3.4/keepalived/dbus'
 (cd etc && make  top_distdir=../../keepalived-1.3.4 distdir=../../keepalived-1.3.4/keepalived/etc \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[3]: Entering directory `/downloads/keepalived-1.3.4/keepalived/etc'
make[3]: *** No rule to make target `dbus-1', needed by `distdir'.  Stop.
make[3]: Leaving directory `/downloads/keepalived-1.3.4/keepalived/etc'
make[2]: *** [distdir] Error 1
make[2]: Leaving directory `/downloads/keepalived-1.3.4/keepalived'
make[1]: *** [distdir] Error 1
make[1]: Leaving directory `/downloads/keepalived-1.3.4'
make: *** [dist] Error 2

This branch also seems to needs "autoreconf -f -i" to be run after the ./configure (my last build of 1.3.2 builds OK), if it's an error on my part or any additional info you need just let me know. :)

**Comment by pqarmitage** [comment]
Commit a46e811 should resolve the issue.

I have no idea why I address the dbus-1 directory to EXTRA_DIST in the keepalived/etc/Makefile.am file. Apologies for the problems caused.

**Comment by fenice2** [comment]
Thanks for your quick reply, unfortunately one more error has popped up:

/usr/bin/install: cannot stat 'doc/KEEPALIVED-MIB': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.FP8ZXH (%install)

**Comment by pqarmitage** [comment]
What rpm .spec file are you using? It looks as though it is referring to doc/KEEPALIVED-MIB whereas it should be doc/KEEPALIVED-MIB.txt. Also, if you are using the RFC MIBs, they have .txt at the end of the filename too.

**Comment by fenice2** [comment]
Ah, I'm using the spec file from SRPM for keepalived and the extension was  missing in there - it built correctly when I added that. It's no inconvenience to find bugs and report the, I hope it helps in some small way. Thanks again for you replies.

**Comment by pqarmitage** [comment]
Bug reports are always appreciated, especially if there is enough information to be able to find the problem.

I'm not clear what you mean by 'the spec file from SRPM'. Could you provide a link to it so I can have a look at it.

**Comment by fenice2** [comment]
I thought the version with the spec file that I used was from this link: http://vault.centos.org/7.1.1503/os/Source/SPackages/ 

After checking the spec file I have and the one in that file, there seem to be some slight differences such as the missing extension on the mib file. I did change to using the spec file from the 'make dist' and that obviously worked without problems.

**Comment by pqarmitage** [comment]
The spec file from vault.centos.org is for keepalived version 1.2.13, and quite a few things have changed since then. A more up-to-date spec file for a RedHat environment might be better found at http://pkgs.fedoraproject.org/cgit/rpms/keepalived.git/tree .

**Comment by fenice2** [comment]
Yes, I realise the other one was old I'll give the fedora version a go a bit later today. Thanks again. :)
