### ISSUE TITLE
Systemd detection broken in Archlinux

### ISSUE THREAD

**Issue by SjonHortensius** [acassen/keepalived#533]
Have a look at the workaround they have in their repo: https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/keepalived&id=51d7c00c0425ec8806d9574dbd041d26ebbfb787

After they removed this; the .service file did not get generated by make. This is unexpected. Can someone explain what `systemctl | grep -q -- "-\.mount"` is supposed to detect?

**Comment by pqarmitage** [comment]
The workaround that you refer to appears to be commenting out a trick that was used, but now no longer is (it was added for version 1.3.2-2, and is removed for version 1.3.4-1). Presumably this means that the standard test is now working for them.

I found the tests for system init type at http://unix.stackexchange.com/questions/18209/detect-init-system-using-the-shell . It is searching for the following output from systemctl:
`-.mount                                                                                   loaded active mounted   /`
which appears to be checking that a root filesystem has been mounted.

I've installed an Archlinux VM and it detects systemd for me.

If you look in configure.ac at the section beginning `Determine system init type` you will see the scriptlet that attempts to determine the init type. Can you attempt to debug that to find out what is happening? Is it that the test was not working on an older version of Archlinux, but is now working on the latest version?

**Comment by SjonHortensius** [comment]
Thanks for your response. I will investigate further. Please note however; that you can view the [list of files that are included in the package](https://www.archlinux.org/packages/community/x86_64/keepalived/) as built by the official maintainer. It does not include a service file

**Comment by SjonHortensius** [comment]
Okay; it seems someone has [already reported this at the Archlinux bugtracker](https://bugs.archlinux.org/task/53038); I suspect they will fix this (since it should work as expected). I will monitor their tracker and reopen this issue if required.

**Comment by pqarmitage** [comment]
I've done further testing on my Archlinux VM, and `make install` does install /usr/lib/systemd/system/keepalived.service so I'm not sure why it isn't included in the package.

It would be interesting to know the cause of the problem, so if you could update this issue with the cause once they have found it that would be helpful.

**Comment by SjonHortensius** [comment]
So what's happening is that when users build this package it'll work fine (without the commented systemctl tweak). However; the official package is [built in a clean chroot](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_Clean_Chroot) which doesn't have `systemd` installed.

They have [enabled their tweak again](https://git.archlinux.org/svntogit/community.git/commit/trunk/PKGBUILD?h=packages/keepalived&id=82473f9b09f0a4a0ca608a21827d3b8ccab2780b) and I don't see any reason to change/fix anything in keepalived

**Comment by pqarmitage** [comment]
Thanks for the update.

I added a `--with-init=` option to configure, so for example `--with-init=systemd` could be specified, and the tweak could then be avoided. This feature is currently in the master git branch, and should be included in the next release.
