### ISSUE TITLE
sync-groups not completing transitions in a timely manor

### ISSUE THREAD

**Issue by andempsey** [acassen/keepalived#560]
A customer raised an issue with us and I think it's applicable as an upstream fix as well.
This is only really noticeable on large transition times (we used 20 seconds) but individual groups in a sync group don't transition at the same time as the first group to transition. In the best case they'll transition with in one advert interval and in the worst case 3 * advert interval. This looks to me to be because the FSM for the sync groups hasn't been updated in line with the FSM for the individual groups. The groups would eventually switch to the new state but there would be some time problems.

I've got a diff set that works on 1.2.19 (first found on an older version of our product) and this might've been fixed since then. The diff set has some changes to the scheduler and I'm not that familiar with that area of the code. In my tests I haven't broken anything but I'm only using VRRP and testing the usual scenarios. Some feedback on the diffs and then integration into the main line would be much appreciated.

[fix_sync_timers.txt](https://github.com/acassen/keepalived/files/858938/fix_sync_timers.txt)

Cheers,
Anthony

**Comment by pqarmitage** [comment]
I'll certainly have a look at it and let you have some feedback. However the development that I'm working on at the moment has changed the way it works, and now once one instance of a sync group transitions, all others transition immediately.

If you would like to try the code (and it would be really helpful to have some feedback), it is available at https://github.com/pqarmitage/keepalived/tree/fixes.quick . The plan is that this will be available as a beta release soon.

**Comment by pqarmitage** [comment]
This should be fixed in the beta branch.
