### ISSUE TITLE
On receiving wrong VRRP packets why we are updating the master_down_timer

### ISSUE THREAD

**Issue by Navjot01** [acassen/keepalived#562]
Hi,
I have two DUT's.

{Backup}-----{master}

Both side have same adv-interval, Now if i change the adv-interval on backup side this will cause "	ret = vrrp_check_packet(vrrp, buf, buflen, check_addr);" to return VRRP_PACKET_DROP and this eventually goes into the logic "vrrp_state_backup" where it update the master_down_timer keeping the state of backup router as it is.

In case we have bogus packet (Bad TTL, Checksum or VIP mismatch etc. ) we are updating the master_down_timer keeping the state of router as backup.

**Ideally these bogus packet's should be discarded and we should not update the master_down_timer and change the state to master.**

**Comment by pqarmitage** [comment]
You are quite right that the packets should be discarded and the master_down_timer not updated.

In my development version, at https://github.com/pqarmitage/keepalived/fixes.quick I have already resolved this problem as part of commit a42613f. If you are able to test that version and confirm that it resolves the issue you have observed it would be very helpful. The plan is that this development version will soon be made a beta release for keepalived.

**Comment by Navjot01** [comment]
I see a lot of changes in this commit, are all these changes related to above mentioned problem ?

**Comment by pqarmitage** [comment]
It looks like it is only the changes to keepalived/vrrp/vrrp.c in the block starting at line 1393 that are to do with ignoring bad adverts.

**Comment by pqarmitage** [comment]
This is resolve in the beta branch.

See https://github.com/acassen/keepalived/pull/683#issue-269383338 for other new functionality that is included in the beta branch.
