### ISSUE TITLE
strange behaviour of systemctl onto centos 7 servers with keepalived git commit v1.3.5-6-g6fa32f2

### ISSUE THREAD

**Issue by milari** [acassen/keepalived#563]
Hi.
Thanks for Your great work.
I'm compiling and installing keepalived 1.3.5 onto a centos 7 server.
Now what I've seen is, after compiled and installed keepalived.conf:
- if I launch command "systemctl start keepalived" without "enabling" service at start, before, it starts correctly, but later command "systemctl stop keepalived" doesn't work.
- so, after a pkill keepalived, I've launched command "systemctl enable keepalived"; but now the next "systemctl start keepalived", failed...
It seems second "start" operation never "communicate" its ends...

Looking at logs, I've seen the "make install" command doesn't create /usr/local/var/run directory, so keepalived.pid state cannot be checked from systemctl

Updating the keepalived.service, for letting it use /var/run directory for pid file, it works correctly.
I hope this may help.
bye!

**Comment by pqarmitage** [comment]
Thanks you for reporting this issue.

Commit 668f8c2 resolves the problem, but also adds the configure option --enable-gnu-std-paths, which means that pid files will be put in /usr/local/var/run if enabled. The default remains /var/run and the keepalived.service file is now created consistently with what keepalived will do.
