### ISSUE TITLE
Keepalived IPv6 working as MASTER-MASTER

### ISSUE THREAD

**Issue by dseira** [acassen/keepalived#565]
I'm trying to configure the keepalived to be able to create a virtual IP of IPv6.

I have the following keepalived configuration:

**kepalived.conf-router1**

```
vrrp_instance vip1 {
    state MASTER
    interface ens192
    unicast_src_ip x.x.x.99
    unicast_peer {
        x.x.x.102
    }
    garp_master_delay 2
    virtual_router_id 1
    priority 101
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 11111
    }
    virtual_ipaddress {
        x.x.x.103/27 brd x.x.x.127
    }
}

vrrp_instance vip2 {
    state BACKUP
    interface ens192
    unicast_src_ip x.x.x.99
    unicast_peer {
        x.x.x.102
    }
    garp_master_delay 2
    virtual_router_id 2
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 11111
    }
    virtual_ipaddress {
        x.x.x.105/27 brd x.x.x.127
    }
}


vrrp_instance vip3 {
    state MASTER
    interface ens256
    virtual_router_id 50
    priority 101
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 11111
    }
    virtual_ipaddress {
        x:x:x:x::103/64 dev ens256
    }
}

vrrp_instance vip4 {
    state BACKUP
    interface ens256
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 11111
    }
    virtual_ipaddress {
        x:x:x:x::105/64 dev ens256
    }
}
```

**keepalived.conf-router2**

```
vrrp_instance vip1 {
    state BACKUP
    interface ens192
    unicast_src_ip x.x.x.102
    unicast_peer {
        x.x.x.99
    }
    garp_master_delay 2
    virtual_router_id 1
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 11111
    }
    virtual_ipaddress {
        x.x.x.103/27 brd x.x.x.127
    }
}

vrrp_instance vip2 {
    state MASTER
    interface ens192
    unicast_src_ip x.x.x.102
    unicast_peer {
        x.x.x.99
    }
    garp_master_delay 2
    virtual_router_id 2
    priority 101
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 11111
    }
    virtual_ipaddress {
        x.x.x.105/27 brd x.x.x.127
    }
}

vrrp_instance vip3 {
    state BACKUP
    interface ens256
    virtual_router_id 50
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 11111
    }
    virtual_ipaddress {
        x:x:x:x::103/64 dev ens256
    }
}

vrrp_instance vip4 {
    state MASTER
    interface ens256
    virtual_router_id 51
    priority 101
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 11111
    }
    virtual_ipaddress {
        x:x:x:x::105/64 dev ens256
    }
}
```
At sysctl level both routers have the following IPv6 variables:
```
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
```

There is no mix between IPv4 and IPv6 interfaces; **ens192** is for IPv4 and **ens256** for IPv4.

The problem comes when the keepalived service is reloaded; the vip1 and vip2 (IPv4) are configured properly, every interface has it own MASTER vip ip in every router. But for the vip3 and vip4 (IPv6) both routers have every VIP configured. This is the interfaces configuration:

**ip addr ls - router1**
```
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:89:09:da brd ff:ff:ff:ff:ff:ff
    inet x.x.x.99/27 brd x.x.x.127 scope global ens192
       valid_lft forever preferred_lft forever
    inet x.x.x.103/27 brd x.x.x.127 scope global secondary ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe89:9da/64 scope link 
       valid_lft forever preferred_lft forever

4: ens256: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:89:9e:ba brd ff:ff:ff:ff:ff:ff
    inet6 x:x:x:x::105/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 x:x:x:x::103/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 x:x:x:x::99/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe89:9eba/64 scope link 
       valid_lft forever preferred_lft forever
```
**ip addr ls - router2**
```
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:89:2a:74 brd ff:ff:ff:ff:ff:ff
    inet x.x.x.102/27 brd x.x.x.127 scope global ens192
       valid_lft forever preferred_lft forever
    inet x.x.x.105/27 brd x.x.x.127 scope global secondary ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe89:2a74/64 scope link
       valid_lft forever preferred_lft forever

4: ens256: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:89:27:75 brd ff:ff:ff:ff:ff:ff
    inet6 x:x:x:x::105/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 x:x:x:x::103/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 x:x:x:x::102/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe89:2775/64 scope link 
       valid_lft forever preferred_lft forever
```

In the syslog I can see the following logs regarding the IPv6 instances:
**router1**
```
Mar 24 03:28:16 router1 Keepalived_vrrp[9145]: VRRP_Instance(vip4) Entering BACKUP STATE
Mar 24 03:28:17 router1 Keepalived_vrrp[9145]: VRRP_Instance(vip3) Transition to MASTER STATE
Mar 24 03:28:20 router1 Keepalived_vrrp[9145]: VRRP_Instance(vip4) Transition to MASTER STATE
Mar 24 03:28:21 router1 Keepalived_vrrp[9145]: VRRP_Instance(vip4) Entering MASTER STATE
```
**router2**
```
Mar 24 03:28:18 router2 Keepalived_vrrp[1412]: VRRP_Instance(vip3) Transition to MASTER STATE
Mar 24 03:28:18 router2 Keepalived_vrrp[1412]: VRRP_Instance(vip4) Transition to MASTER STATE
Mar 24 03:28:19 router2 Keepalived_vrrp[1412]: VRRP_Instance(vip4) Entering MASTER STATE
```

There is no firewall rules between them.

From the outside both IPv6 are working properly but I don't know if this is the expected behaviour (maybe because of something that I miss the IPv6 protocol) or I did something wrong. 

The system versions are:

* ubuntu 16.04.2 LTS
* keepalived 1.2.19-1ubuntu0.1
* kernel 4.4.0-66-generic

Can someone clarify?

**Comment by pqarmitage** [comment]
Your configurations work for me with both v1.2.19 and the current version v1.3.5 without the problem you describe. Upgrading to v1.3.5 is highly recommended.

Please note that there are some configuration issues with your setup:
1. Using IPv6 requires VRRPv3, but VRRPv3 does not support authentication; you need to remove the authentication blocks from your IPv6 instances.
2. For the virtual ip addresses, remove the /64 and /128, and the brd x.x.x.127; you are adding individual addresses to existing subnets (I assume that the x.x.x are all the same, and also the x:x:x:x are also the same)
3. VRRPv3 requires that the first virtual IP address is a link local address.
4. It is unnecessary to dev ens... against the virtual ip addresses since if defaults to the interface of the vrrp instance.

If you can post the full log outputs from both systems we might be able to work out what is happening (ensure you run keepalived with the -D option).

**Comment by dseira** [comment]
After more tests, and following your indications, finally it seems to work, with the following configuration:

**keepalived.conf-router1**
```
global_defs {
    router_id testing
    vrrp_priority -20
    checker_priority -20
    vrrp_no_swap
    checker_no_swap
    vrrp_check_unicast_src
    vrrp_version 3
}
vrrp_instance vip1 {
    state MASTER
    interface ens192
    track_script {
        chk_haproxy
    }
    unicast_src_ip x.x.x.99
    unicast_peer {
        x.x.x.102
    }
    garp_master_delay 2
    virtual_router_id 1
    priority 101
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 11111
    }
    virtual_ipaddress {
        x.x.x.103/27
    }
}

vrrp_instance vip2 {
    state BACKUP
    interface ens192
    track_script {
        chk_haproxy
    }
    unicast_src_ip x.x.x.99
    unicast_peer {
        x.x.x.102
    }
    garp_master_delay 2
    virtual_router_id 2
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 11111
    }
    virtual_ipaddress {
        x.x.x.105/27
    }
}

vrrp_instance vip3 {
    state MASTER
    interface ens256
    virtual_router_id 50
    priority 101
    native_ipv6
    advert_int 1
    virtual_ipaddress {
        x:x:x:x::103/64
    }
}

vrrp_instance vip4 {
    state BACKUP
    interface ens256
    virtual_router_id 51
    priority 100
    native_ipv6
    advert_int 1
    virtual_ipaddress {
        x:x:x:x::105/64
    }
}
```
**keepalived.conf-router2**
```
global_defs {
    router_id testing
    vrrp_priority -20
    checker_priority -20
    vrrp_no_swap
    checker_no_swap
    vrrp_check_unicast_src
    vrrp_version 3
}
vrrp_instance vip1 {
    state BACKUP
    interface ens192
    track_script {
        chk_haproxy
    }
    unicast_src_ip x.x.x.102
    unicast_peer {
        x.x.x.99
    }
    garp_master_delay 2
    virtual_router_id 1
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 11111
    }
    virtual_ipaddress {
        x.x.x.103/27
    }
}

vrrp_instance vip2 {
    state MASTER
    interface ens192
    track_script {
        chk_haproxy
    }
    unicast_src_ip x.x.x.102
    unicast_peer {
        x.x.x.99
    }
    garp_master_delay 2
    virtual_router_id 2
    priority 101
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 11111
    }
    virtual_ipaddress {
        x.x.x.105/27
    }
}

vrrp_instance vip3 {
    state BACKUP
    interface ens256
    virtual_router_id 50
    priority 100
    native_ipv6
    advert_int 1
    virtual_ipaddress {
        x:x:x:x::103/64
    }
}

vrrp_instance vip4 {
    state MASTER
    interface ens256
    virtual_router_id 51
    priority 101
    native_ipv6
    advert_int 1
    virtual_ipaddress {
        x:x:x:x::105/64
    }
}
```
I've enabled the vrrp v3 and the native_ipv6 in the IPv6 instances; without this it didn't work. Finally, I decide to put the netmask /64 in the virtual_ipaddress because if I didn't do that, the virtual ips were  configured with /128 (I don't know if this the expected behaviour), getting in the syslog the following warning:

```Keepalived_vrrp[1776]: x.x.x.x::105 has a prefix length of 128, setting preferred_lft to 0```

With this configuration all works as expected, but do you see something wrong?

Thanks for your support, I appreciate it.

**Comment by dseira** [comment]
Making more tests, at this point, the ips are working properly but I'm getting the following errors in the log:

```
Keepalived_vrrp[1902]:  ip address associated with VRID  not present in received packet : x.x.x.x::103
Keepalived_vrrp[1902]: one or more VIP associated with VRID mismatch actual MASTER advert
Keepalived_vrrp[1902]: bogus VRRP packet received on eth1 !!!
Keepalived_vrrp[1902]: VRRP_Instance(vip3) Dropping received VRRP packet...
Keepalived_vrrp[1902]: one or more VIP associated with VRID mismatch actual MASTER advert
Keepalived_vrrp[1902]: bogus VRRP packet received on eth1 !!!
Keepalived_vrrp[1902]: VRRP_Instance(vip4) ignoring received advertisment...
Keepalived_vrrp[1902]: ip address associated with VRID  not present in received packet : x.x.x.x::105
```
Those messages appear every second in both routers. I've checked that the VRID were correctly (pasted before) and there is no firewall rules blocking some kind of vrrp traffic.

Any suggestion?

**Comment by pqarmitage** [comment]
I assume you have upgraded to a more recent version of keepalived than v1.2.19 since you are now using keywords `vrrp_priority` etc. Could you please confirm which version you are now using.

`native_ipv6` is really a superseded keyword, and it never did what was intended. It's purpose was to allow a mixture of IPv4 and IPv6 in a VRRP instance, but that cannot work. You already have the global `vrrp_version 3` specified. 

There is no problem with the log message `Keepalived_vrrp[1776]: x.x.x.x::105 has a prefix length of 128, setting preferred_lft to 0`. I suggest removing the `/27` and `/64` from the IP addresses and ignoring that message.

keepalived sets the nodad option on IPv6 address since the speeds up adding the address to the interface. keepalived assumes that the network and keepalived are properly configured, so that it's virtual IP addresses are not configured anywhere else.

The `ip address associated with VRID  not present in received packet` messages are certainly not expected. What is more peculiar is that it is being reported that the packets are being received on eth1, whereas your configuration shows that keepalived is using interfaces ens192 and ens256. Is there another instance of keepalived running which is configured to use eth1?

**Comment by dseira** [comment]
I'm still using the ```1.2.19```; I've added ```vrrp_priority``` as a kind of improvement. I thought ```1.2.19``` was compatible with that feature.

Regarding the ```ip address associated with VRID not present in received packet``` message; it was a copy/paste mistake, the interfaces are ens192 and ens256.

I don't know the reason but the ```bogus VRRP packet received``` messages disappear after change the VRID of the IPv6 instances.

**Comment by pqarmitage** [comment]
The first release the `vrrp_priority` and `vrrp_no_swap` etc were in was v1.2.20.

Changing the VRID resolving your problem suggests that there is another instance of keepalived on the ens256 network that is also using VRIDs 50 and 51, but with different IP addresses.

Are you happy to close this now?

**Comment by dseira** [comment]
Changing the VRID solved the problem; I'm not aware of more instance in the same network but I'll investigate the issue.

I'm going to close the issue.

Thanks.
