### ISSUE TITLE
compile issue on some fedora versions

### ISSUE THREAD

**Issue by sbagmeijer** [acassen/keepalived#577]
I create rpm packages for Keepalived and I tried to update them to the latest version 1.3.5 but somehow I cannot get it compiled anymore on certain Fedora versions (19, 20, 21) could be they are to old or something has changed from 1.3.4.

the error I get is this:
```
In file included from vrrp_iptables_calls.c:47:0:
/usr/include/linux/netfilter/xt_set.h:69:31: error: field 'packets' has incomplete type
  struct ip_set_counter_match0 packets;
                               ^
/usr/include/linux/netfilter/xt_set.h:70:31: error: field 'bytes' has incomplete type
  struct ip_set_counter_match0 bytes;
                               ^
```

Do you maybe know what could be wrong and if it is still fixable for me on the older Fedora versions?

**Comment by pqarmitage** [comment]
I think commit 510c6b4 resolves this issue.

**Comment by sbagmeijer** [comment]
> I think commit 510c6b4 resolves this issue.

I will give it a try thank you!

**Comment by sbagmeijer** [comment]
@pqarmitage I can confirm that commit indeed resolved the issue on Fedora 19, 20 and 21!

Thank you :)
