### ISSUE TITLE
Unable to resolve default script username 'keepalived_script' - ignoring

### ISSUE THREAD

**Issue by cscowx** [acassen/keepalived#586]
The operating system is：CentOS Linux release 7.3.1611
Keepalived version：keepalived-1.3.5
ipvsadm version：ipvsadm-1.27-7.el7.x86_64

systemctl start keepalived.service At startup, this is a mistake in /var/log/messages:

May 12 02:06:04 localhost Keepalived[36514]: Unable to resolve default script username 'keepalived_script' - ignoring

I don't know how to solve this mistake

**Comment by pqarmitage** [comment]
Commit 1c5bfa2 changes keepalived so that the message is only output if scripts are configured, and they don't have a user specified.

Adding the user keepalived_script means that any scripts configured without a user specified will be executed with the user id of the keepalived_script user, rather than root, since executing scripts as root has potential security implications.

**Comment by cscowx** [comment]
This is my configuration：

! Configuration File for keepalived

global_defs {
   router_id keepalived-slave
   lvs_sync_daemon ens33 NanJing-HouTai-FTP-VIP
   lvs_flush
   vrrp_check_unicast_src
   script_user keepalived_script
   enable_script_security
}

vrrp_script check_lvs_health {
       script "/wangxiang/check_lvs_health.sh"
       interval 3 #每3秒检查一次
       weight -20 #如果检查错误，那么优先级减少20
       fall 2 #需要检查2次错误，才认为是错误
       rise 2 #需要检查2次成功，才认为是成功
}

vrrp_instance NanJing-HouTai-FTP-VIP {
    state BACKUP
    interface ens33
    virtual_router_id 51
    priority 90
    advert_int 3

    unicast_src_ip 192.168.98.129
    unicast_peer {
        192.168.98.128
    }

    authentication {
        auth_type PASS
        auth_pass hofchina
    }

    virtual_ipaddress {
        192.168.98.130 dev ens33
    }

    track_script {
        check_lvs_health
    }

}



In addition, I created users in the Linux system：keepalived_script

Still, I didn't understand why the error was reported at startup：

May 17 12:52:20 localhost Keepalived[12936]: Unable to resolve default script username 'keepalived_script' - ignoring

**Comment by cscowx** [comment]
This is my script configuration:

#!/bin/bash

count=`ps aux|grep -v grep|grep "/usr/sbin/sshd -D"|wc -l`
cnt=0

if [ "$count" -gt "$cnt" ]; then

 exit 0;

else

 exit 1;

fi

**Comment by pqarmitage** [comment]
The security risk is that the script `/wangxiang/check_lvs_health.sh` is executed with root privileges unless the user `keepalived_script` exists, and if any not privileged user has write access to either /wangxiang or the script itself, they could modify the script and therefore execute arbitrary code with root privileges.

**Comment by cscowx** [comment]
But my keepalived. Conf configuration has the parameters specified in the global:


global_defs {

script_user keepalived_script

}


When running this script, should you use the keepalived_script account?

I still don't get why systemctl start keepalived.service will report this error:

May 17 12:52:20 localhost Keepalived[12936]: Unable to resolve default script username 'keepalived_script' - ignoring



How can I solve this problem?
