### ISSUE TITLE
Small typo in systemd init script

### ISSUE THREAD

**Issue by stylobille** [acassen/keepalived#598]
Hello

I've just compiled keepalived 1.3.5 for rhel 7.3 and the systemd script (/usr/lib/systemd/system/keepalived.service) contains the following line : 

EnvironmentFile=-/etc/sysconfig/keepalived

I'm not sure this "-" should be there (well at least for all I know it should not be there, but if I'm wrong sorry about this tread).

Regards,

**Comment by tersmitten** [comment]
> The argument passed should be an absolute filename or wildcard expression, optionally prefixed with "-", which indicates that if the file does not exist, it will not be read and no error or warning message is logged. This option may be specified more than once in which case all specified files are read. If the empty string is assigned to this option, the list of file to read is reset, all prior assignments have no effect.

**Comment by pqarmitage** [comment]
@stylobille thanks for the report, and @tersmitten thanks for the confirmation that it is correct.

In fact I based the keepalived.service.in file on the Fedora keepalived.service file at https://src.fedoraproject.org/cgit/rpms/keepalived.git/tree/keepalived.service, just generalizing it for different @sysconfdir@s.
