### ISSUE TITLE
notify_master Not Working on Keepalived v1.2.24

### ISSUE THREAD

**Issue by santu1120** [acassen/keepalived#600]
HI Team,

notify_master not working can anyone help on that..Configuration file in below ...

vrrp_script chk_haproxy
{
script "pidof haproxy"
interval 2
weight 2
}
vrrp_instance VI_1
{
debug 2
interface eth0
state MASTER
virtual_router_id 1 # Assign one ID for this route
priority 101 # 101 on master, 100 on backup
unicast_src_ip 10.0.2.28 # My IP
unicast_peer
{
10.0.1.58 # peer IP
}
track_script
{
                chk_haproxy
}
notify_master "/etc/keepalived/master.sh master">  /etc/keepalived/abc.txt
}

==================================

The massages log good its changing master to backup...

LOg details...

Jun 10 20:18:02 ip-10-0-1-58 Keepalived_vrrp[16912]: VRRP_Instance(VI_1) Entering MASTER STATE
Jun 10 20:18:54 ip-10-0-1-58 Keepalived_vrrp[16912]: VRRP_Instance(VI_1) Received higher prio advert 103
Jun 10 20:18:54 ip-10-0-1-58 Keepalived_vrrp[16912]: VRRP_Instance(VI_1) Entering BACKUP STATE

But somehow the  notify_master not working..please help

**Comment by pqarmitage** [comment]
Change the line:
`notify_master "/etc/keepalived/master.sh master"> /etc/keepalived/abc.txt`
to
`notify_master "/etc/keepalived/master.sh master >/etc/keepalived/abc.txt"`

i.e. move the second '"' to the end of the line.

The notify_* scripts only use the first parameter specified as the command to execute, including any command line parameters to be passed to the script, so the whole command, including parameters, needs to be enclosed in quotes.
