### ISSUE TITLE
failed_checkers across reload

### ISSUE THREAD

**Issue by rik78** [acassen/keepalived#608]
If a realserver is down and keepalived is reloaded with a new configuration file new checker ids don't match the old ones. During reload failed checker id are copied from the old structure. This means that the realserver may contain some invalid checkerid in its failed_checkers list, and for this reason realserver is never added to the virtualserver when healthckeck goes green.
How can this issue be resolved? Is it acceptable to delete all failed_checkers during reload and force the rs to be alive?

**Comment by pqarmitage** [comment]
I think the proper solution to this is to compare the checkers before and after the reload and set the failed list only for those checkers that were failed before the reload and still exist after the reload.

**Comment by rik78** [comment]
I agree.

**Comment by pandax381** [comment]
I'm just working on solving this issue.
I will report it when there is progress.

**Comment by rik78** [comment]
@pandax381 fwiw I started a patch for misc check, it lives [here ](https://github.com/rik78/keepalived/tree/fix-failed-cid)

**Comment by pqarmitage** [comment]
@pandax381 has pushed a series of patches that resolve this issue.
