### ISSUE TITLE
issue with keepalived using only ipv6, more than one master appears on switchover event

### ISSUE THREAD

**Issue by huyvo98** [acassen/keepalived#615]
Hi,

currently, on my setup, I have 4 servers run Keepalived version 1.2.13 with IPV6 VIP under VRRP instance like the one bellows:
vrrp_instance VI_1 {
       state BACKUP
       interface br4004
       virtual_router_id 176
       priority 100
       advert_int 2
       nopreempt
       authentication {
           auth_type PASS
           auth_pass 123
       }
       track_script {
           chk_ipv6_monitor
           chk_cluster_manager_health
       }
       virtual_ipaddress {
           ipv6/64
       }
       notify_master /etc/keepalived/ka_master.sh
       notify_backup /etc/keepalived/ka_slave.sh
       notify_fault  /etc/keepalived/ka_fault.sh
}

Everytime switchover happens, I see more than one master node (2, or 3 node say it is the master). Is there anyway I can make ipv6 work with this keepalived version?

Thanks,

**Comment by pqarmitage** [comment]
Comments in the ChangeLog for v1.2.14 to v1.2.20 suggest that there were fixes for various problems with IPv6 throughout those versions.

Is there a reason you can't upgrade to a recent version? There are a significant number of fixes and enhancements between v1.2.13 and v1.3.5.

**Comment by huyvo98** [comment]
Hi,

Thanks for getting back to me related to the issue. yes, we can upgrade to a later version of keepalived. Do you know which version of keepalived fully support for ipv6 under Debian OS?

Thanks,

**Comment by pqarmitage** [comment]
I would go with v1.3.5, or better still the latest code from git, since they have multiple fixes and enhancements.

One thing to note, though, is that using IPv6 requires VRRPv3, and that doesn't support authentication, so it would be sensible to remove the authentication block from the vrrp_instance.

**Comment by huyvo98** [comment]
Hi,
Thanks for the advice.
I tried to deploy v1.3.5 and failed due to libssl version. Apparently, keepalived requires libssl1.0.0 (= 1.0.1t-1+deb8u6), however, we are running libssl version 1.0.2k-1~bpo8+1 and we cannot downgrade it. Do you know how do I overcome the issue and able to run keepalived with ipv6?

**Comment by pqarmitage** [comment]
I cannot think of any reason why keepalived should require a particular version of libssl. I'm using libssl version 1.1.0f on at least one of my systems.

Can you remove the requirement on the specific version of libssl and try again?

**Comment by pqarmitage** [comment]
Closing due to no update for 8 weeks.
