### ISSUE TITLE
Keepalived accepts any value as 'state' in config.

### ISSUE THREAD

**Issue by sndrsmnk** [acassen/keepalived#618]
Keepalived hapily starts with any value as 'state' in a vrrp_instance {} block. There's no warning that 'SLAVE' isn't a correct state, and the incorrect value gives unpredictable behaviour of master/backup transitioning.

Perhaps warn users about odd states defined, or refuse to start of the config file doesn't parse?

**Comment by sndrsmnk** [comment]
As the matter of fact, any odd value is silently ignored by Keepalived.

```sh
vrrp_instance HAProxy_VRRP {
    jemoeder 1
    state BACKUP

   [ ... ]
}
```
Just starts, no questions asked!

**Comment by pqarmitage** [comment]
keepalived v1.3.5 (and for a number of earlier versions - since commit 40e4a178) does log a message
```
static void
vrrp_state_handler(vector_t *strvec)
{
        char *str = strvec_slot(strvec, 1);
        vrrp_t *vrrp = LIST_TAIL_DATA(vrrp_data->vrrp);
        vrrp_sgroup_t *vgroup = vrrp->sync;

        if (!strcmp(str, "MASTER")) {
                vrrp->wantstate = VRRP_STATE_MAST;
                vrrp->init_state = VRRP_STATE_MAST;
        }
        else if (strcmp(str, "BACKUP"))
                log_message(LOG_INFO,"(%s): unknown state '%s', defaulting to BACKUP", vrrp->iname, str);

        /* set eventual sync group */
        if (vgroup)
                vgroup->state = vrrp->wantstate;
}
```
It should never have caused any problem specifying `state SLAVE` - if it didn't recognise the state it defaulted to BACKUP.
