### ISSUE TITLE
Vrrp state machine has error

### ISSUE THREAD

**Issue by s09816** [acassen/keepalived#627]
vrrp_fault
if (vrrp->init_state == VRRP_STATE_BACK || vrrp->nopreempt) {
here need to add a condition, because init_state will be modify when reload keepalived.

reset_vrrp_state do this change

**Comment by s09816** [comment]
vrrp. c   restore_vrrp_state can  chang init_state  to master

**Comment by pqarmitage** [comment]
It's taken me a long time to understand what this issue was about. I've now understood the issue you reported, and commit fe775ce resolves the problem. Commit e0fc908 build on this change and simplifies the code.
