### ISSUE TITLE
Add support @config-id for the value-only configuration lines

### ISSUE THREAD

**Issue by skokhanovskiy** [acassen/keepalived#629]
Parser now supports the "@config-id" feature only for keyed configuration lines. For example, this feature can not be used to specify unique unicast peers for different config-id.

```
vrrp_instance vrrp_foo {
  unicast_peer {
@configid1 192.168.0.1
@configid2 192.168.0.2
  }
  ...
}
```
The configuration lines, as specified above, generate the following error:
```
Configuration error: VRRP instance[vrrp_foo] malformed unicast peer address[@configid1]. Skipping...
Configuration error: VRRP instance[vrrp_foo] malformed unicast peer address[@configid2]. Skipping...
```

**Comment by pqarmitage** [comment]
This was fixed in commit 2386de3. The first version of keepalived to include that commit was v1.3.5.
