### ISSUE TITLE
VRRP_Instance(VI_1) Received advert with lower priority 100, ours 150, forcing new election

### ISSUE THREAD

**Issue by leibus** [acassen/keepalived#632]
just modify the default config  and remove vrrp_strict from global_defs

log：
VRRP_Instance(VI_1) Received advert with lower priority 100, ours 150, forcing new election

[root@localhost ~]# tcpdump -i eth0 -n 'host 224.0.0.18'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
05:57:53.327873 IP 192.168.0.105 > 224.0.0.18: VRRPv2, Advertisement, vrid 51, prio 100, authtype simple, intvl 1s, length 20
05:57:53.328043 IP 192.168.0.107 > 224.0.0.18: VRRPv2, Advertisement, vrid 51, prio 150, authtype simple, intvl 1s, length 20

The backup has the vip too

**Comment by pqarmitage** [comment]
Please can you provide a copy of your configuration files, and also the output of `keepalived -v`.

**Comment by leibus** [comment]
I think the problem is caused by the virtual machine 
I will check it

**Comment by leibus** [comment]
The virtual machine ( backup ) discards the vrrp packets.

**Comment by yelongyu** [comment]
@leibus hey, can you explain it that how the backup virtual machine drop the VRRP packets?
