### ISSUE TITLE
Keepalived_healthcheckers exited due to segmentation fault (SIGSEGV).

### ISSUE THREAD

**Issue by igroost** [acassen/keepalived#634]
Today, when you reload keepalied in the logs we saw the message Keepalived_healthcheckers exited due to a segmentation fault (SIGSEGV). The problem was solved by a restart of keepalived.

Before the manifestation of the problem was made the configuration changes made comments lines
!dsh-db-1
real_server 10.1.72.53 3306 {
MISC_CHECK {
misc_path "/etc/keepalived/HC/HC-DB-master 10.1.72.53"
}
}
in section virtual_server 10.9.200.27 3306.

As misc_check script is used

#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin
curl-qs-m 3 http://$1/ | grep -qF "master"
rc=$?
echo $rc
exit $rc

keepalived -v
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

Copyright(C) 2001-2017 Alexandre Cassen, <acassen@gmail.com>

Build options:  PIPE2 IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF RTA_VIA FRA_OIFNAME FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LINUX_NET_IF_H_COLLISION LVS LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC FIB_ROUTING INET6_ADDR_GEN_MODE SNMP_V3_FOR_V2 SNMP SNMP_KEEPALIVED SNMP_CHECKER SNMP_RFC SNMP_RFCV2 SNMP_RFCV3 SO_MARK

In the attachment put our configuration file and the log.

[files.zip](https://github.com/acassen/keepalived/files/1214152/files.zip)

**Comment by pqarmitage** [comment]
From the log file, it is clear that the healthcheckers process had previously terminated and been restarted by keepalived (the original pid of keepalived_healthcheckers would have been 3162, or thereabouts) but the pid of the keepalived_healthcheckers that terminated was 1681). Do you know what caused the original instance of keepalived_healthchecker (pid 3162) to terminate?

After pid 1681 segfaulted, a keepalived_healthchecker process (pid 763) was respawned by keepalived. Was keepalived working properly at that point, i.e. before the second SIGHUP at 09:43:36. Was keepalived working properly after the second SIGHUP (after which it didn't segfault), or was there still a problem with it, thereby necessitating the restart?

Is the problem reproducible? If so, can you run keepalived with the `-m` option and generate a coredump, and have a look at that to find the line of code that is producing the segfault.

**Comment by igroost** [comment]
No, we do not know what caused the end of the process with PID 3162. In keepalived logs no records about the process with that PID.

The chronology of events is this:
to 09:43:07 comments real server in the VIP 10.1.72.53 10.9.200.27, in the logs there is a message about a segmentation fault
after that, remove comments real server in the VIP 10.1.72.53 10.9.200.27 and do reload. While in the VIP 10.9.200.27 keepalived doesn't add real server 10.1.72.53. 
Comment the entire section 10.9.200.27 VIP, reload, remove comment section, reload. Not solve the problem.
Then at 09:56:37 do restart keepalived.

**Comment by pqarmitage** [comment]
Without further information there is nothing we can do to progress this issue. If the problem recurs please reopen this issue and add further details.

**Comment by baowentao** [comment]
does this problem solved? it also occur on my testbed, keeplaive version is 2.2.4. @pqarmitage
