### ISSUE TITLE
Keepalived fails to see interface and crashes  

### ISSUE THREAD

**Issue by dotanp** [acassen/keepalived#638]
Hello , 
I have an Ubuntu 14.04 machine running keepalived .
After upgrading from 12.04 as well as upgrading the keepalived version to 1.3.5 , I'm experiencing a problem in which the service starts successfully and after a while it reports that the physical interface is unknown following which it crashes .
My configurations [1] used to work fine prior to the upgrade .
Here's the /var/log/messages output [2] and the syslog output[3] . 
I'd be happy if you could assist .

Thanks.

[1] - 
! Configuration File for keepalived

global_defs {
   notification_email {
#    dev<at>example.com
   }
   notification_email_from dev<at>example.com
   smtp_server mailrelay
   smtp_connect_timeout 30
   router_id LVS
}

vrrp_script chk_haproxy {
script "/usr/bin/killall -0 haproxy" # check the haproxy process
interval 2 # every 2 seconds
weight 2 # add 2 points if OK
}

vrrp_instance VI_111 {
    state MASTER
    interface eth1
    garp_master_delay 10
    virtual_router_id 111
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass hgksdhg
    }

    virtual_ipaddress {
	10.24.166.214 dev eth1 label eth1:214
    }
    track_script {
    chk_haproxy
}
}

[2] -
...skipping...
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP ::1 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP fe80::acff:fe18:a6c2 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP fe80::aff:fe18:a6c2 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Registering Kernel netlink reflector
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Got SIGHUP, reloading checker configuration
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Opening file '/usr/local/a/etc/keepalived.conf'.
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP 127.0.0.1 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP 172.24.166.194 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP 10.24.166.194 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP 10.24.166.214 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP ::1 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP fe80::acff:fe18:a6c2 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP fe80::aff:fe18:a6c2 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Registering Kernel netlink reflector
Aug 15 08:14:35 a172-24-166-194 Keepalived_vrrp[21612]: message repeated 3 times: [ Sending gratuitous ARP on eth1 for 10.24.166.214]
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Registering Kernel netlink reflector
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Registering Kernel netlink command channel
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Registering gratuitous ARP shared channel
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Opening file '/usr/local/a/etc/keepalived.conf'.
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: VRRP_Script(chk_haproxy) considered successful on reload
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: VRRP_Instance(VI_111) setting protocol VIPs.
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Using LinkWatch kernel netlink reflector...
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: VRRP sockpool: [ifindex(3), proto(112), unicast(0), fd(10,11)]
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Netlink: Cannot open netlink socket : (-6)
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Netlink: Cannot open netlink socket : (-6)
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Registering Kernel netlink reflector
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Registering Kernel netlink command channel
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Registering gratuitous ARP shared channel
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Opening file '/usr/local/a/etc/keepalived.conf'.
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Cant find interface eth1 for vrrp_instance VI_111 !!!
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: VRRP is trying to assign ip address 10.24.166.214 to unknown eth1 interface !!! go out and fix your conf !!!
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: VRRP_Script(chk_haproxy) considered successful on reload
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: VRRP_Instance(VI_111) Unknown interface !
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Stopped
Aug 15 08:17:52 a172-24-166-194 Keepalived[21610]: Keepalived_vrrp exited with permanent error CONFIG. Terminating
Aug 15 08:17:52 a172-24-166-194 Keepalived[21610]: Stopping
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Stopped
Aug 15 08:17:57 a172-24-166-194 Keepalived[21610]: Stopped Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

[3] - 
Aug 15 08:17:01 a172-24-166-194 /USR/SBIN/CRON[24438]: (root) CMD (test -d /usr/local/a/etc/ghostmon && /usr/bin/ntpq -np 2> /dev/null > /usr/local/a/etc/ghostmon/ntp_state)
Aug 15 08:17:52 a172-24-166-194 Keepalived[21610]: Opening file '/usr/local/a/etc/keepalived.conf'.
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Got SIGHUP, reloading checker configuration
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Initializing ipvs
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Opening file '/usr/local/a/etc/keepalived.conf'.
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP 127.0.0.1 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP 172.24.166.194 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP 10.24.166.194 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP 10.24.166.214 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP ::1 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP fe80::acff:fe18:a6c2 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP fe80::aff:fe18:a6c2 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Registering Kernel netlink reflector
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Got SIGHUP, reloading checker configuration
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Initializing ipvs
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Opening file '/usr/local/a/etc/keepalived.conf'.
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP 127.0.0.1 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP 172.24.166.194 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP 10.24.166.194 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP 10.24.166.214 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP ::1 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP fe80::acff:fe18:a6c2 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Netlink reflector reports IP fe80::aff:fe18:a6c2 added
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Registering Kernel netlink reflector
Aug 15 08:14:35 a172-24-166-194 Keepalived_vrrp[21612]: message repeated 3 times: [ Sending gratuitous ARP on eth1 for 10.24.166.214]
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Registering Kernel netlink reflector
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Registering Kernel netlink command channel
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Registering gratuitous ARP shared channel
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Opening file '/usr/local/a/etc/keepalived.conf'.
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: VRRP_Script(chk_haproxy) considered successful on reload
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: VRRP_Instance(VI_111) setting protocol VIPs.
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Using LinkWatch kernel netlink reflector...
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: VRRP sockpool: [ifindex(3), proto(112), unicast(0), fd(10,11)]
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Netlink: Cannot open netlink socket : (-6)
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Netlink: Cannot open netlink socket : (-6)
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Registering Kernel netlink reflector
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Registering Kernel netlink command channel
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Registering gratuitous ARP shared channel
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Opening file '/usr/local/a/etc/keepalived.conf'.
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Cant find interface eth1 for vrrp_instance VI_111 !!!
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: VRRP is trying to assign ip address 10.24.166.214 to unknown eth1 interface !!! go out and fix your conf !!!
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: VRRP_Script(chk_haproxy) considered successful on reload
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: VRRP_Instance(VI_111) Unknown interface !
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Stopped
Aug 15 08:17:52 a172-24-166-194 Keepalived[21610]: Keepalived_vrrp exited with permanent error CONFIG. Terminating
Aug 15 08:17:52 a172-24-166-194 Keepalived[21610]: Stopping
Aug 15 08:17:52 a172-24-166-194 Keepalived_healthcheckers[21611]: Stopped
Aug 15 08:17:57 a172-24-166-194 Keepalived[21610]: Stopped Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

**Comment by pqarmitage** [comment]
I appears that interface names on Ubuntu 14.04 aren't necessarily eth0, eth1 etc - see https://askubuntu.com/questions/578650/interface-device-name-em1-to-eth0-linux-14-04-lts

What is the output of `ip link show`?

**Comment by dotanp** [comment]
Right, but in my case the interface name did not change:
root@172.24.166.194:~# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 7200
    link/ether 02:00:ac:18:a6:c2 brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 7200
    link/ether 02:00:0a:18:a6:c2 brd ff:ff:ff:ff:ff:ff

**Comment by pqarmitage** [comment]
What kind of environment are you running in? since the MAC addresses are locally administered.

The problem relates to the messages:
```
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Netlink: Cannot open netlink socket : (-6)
Aug 15 08:17:52 a172-24-166-194 Keepalived_vrrp[21612]: Netlink: Cannot open netlink socket : (-6)
```
and it is via netlink that keepalived reads what interfaces the system has. 

It looks as though keepalived is receiving a SIGHUP while it is loading, and that would cause it some problems. Do you know where the SIGHUP came from? Seeing what happened earlier in the log might help, and it also might help if you run keepalived with the -D option.

**Comment by dotanp** [comment]
This particular machine is a vm running on OpenNebula .
Here's strace for this process , it shows the SIGHUP 
root@172.24.166.194:~# strace -p 28264
Process 28264 attached
select(1024, [4], [], [], {0, 700059})  = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = 0 (Timeout)
select(1024, [4], [], [], {1, 0})       = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGHUP {si_signo=SIGHUP, si_code=SI_USER, si_pid=28679, si_uid=0} ---
write(5, "\1\0\0\0", 4)                 = 4
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
read(4, "\1\0\0\0", 4)                  = 4
stat("/usr/local/a/etc/keepalived.conf", {st_mode=S_IFREG|0644, st_size=712, ...}) = 0
sendto(3, "<142>Aug 10 15:02:03 Keepalived["..., 93, MSG_NOSIGNAL, NULL, 0) = 93
open("/usr/local/a/etc/keepalived.conf", O_RDONLY) = 6
fstat(6, {st_mode=S_IFREG|0644, st_size=712, ...}) = 0
getcwd("/", 4096)                       = 2
chdir("/usr/local/a/etc")          = 0
fstat(6, {st_mode=S_IFREG|0644, st_size=712, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc448bb8000
read(6, "#! Configuration File for keepal"..., 4096) = 712
read(6, "", 4096)                       = 0
close(6)                                = 0
munmap(0x7fc448bb8000, 4096)            = 0
chdir("/")                              = 0
kill(28266, SIGHUP)                     = 0
kill(28265, SIGHUP)                     = 0
read(4, 0x7ffc6e75fc2c, 4)              = -1 EAGAIN (Resource temporarily unavailable)
select(1024, [4], [], [], {1, 0})       = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=28266, si_status=3, si_utime=0, si_stime=2} ---
write(5, "\21\0\0\0", 4)                = 4
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
read(4, "\21\0\0\0", 4)                 = 4
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 3}], WNOHANG, NULL) = 28266
sendto(3, "<142>Aug 10 15:02:03 Keepalived["..., 103, MSG_NOSIGNAL, NULL, 0) = 103
tgkill(28264, 28264, SIGTERM)           = 0
--- SIGTERM {si_signo=SIGTERM, si_code=SI_TKILL, si_pid=28264, si_uid=0} ---
write(5, "\17\0\0\0", 4)                = 4
rt_sigreturn()                          = 0
wait4(-1, 0x7ffc6e75fbfc, WNOHANG, NULL) = 0
read(4, "\17\0\0\0", 4)                 = 4
sendto(3, "<142>Aug 10 15:02:03 Keepalived["..., 48, MSG_NOSIGNAL, NULL, 0) = 48
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], NULL, 8) = 0
kill(28266, SIGTERM)                    = -1 ESRCH (No such process)
kill(28265, SIGTERM)                    = 0
rt_sigtimedwait([CHLD], NULL, {5, 0}, 8) = 17
wait4(28266, 0x7ffc6e75facc, WNOHANG, NULL) = -1 ECHILD (No child processes)
wait4(28265, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 28265
rt_sigtimedwait([CHLD], NULL, {4, 999608000}, 8) = -1 EAGAIN (Resource temporarily unavailable)
rt_sigprocmask(SIG_UNBLOCK, [CHLD], NULL, 8) = 0
read(4, 0x7ffc6e75fc2c, 4)              = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGHUP, {SIG_IGN, [], SA_RESTORER|SA_RESTART, 0x7fc44793bcc0}, {0x430480, [], SA_RESTORER|SA_RESTART, 0x7fc44793bcc0}, 8) = 0
rt_sigaction(SIGINT, {SIG_IGN, [], SA_RESTORER|SA_RESTART, 0x7fc44793bcc0}, {0x430480, [], SA_RESTORER|SA_RESTART, 0x7fc44793bcc0}, 8) = 0
rt_sigaction(SIGTERM, {SIG_IGN, [], SA_RESTORER|SA_RESTART, 0x7fc44793bcc0}, {0x430480, [], SA_RESTORER|SA_RESTART, 0x7fc44793bcc0}, 8) = 0
rt_sigaction(SIGCHLD, {SIG_IGN, [], SA_RESTORER|SA_RESTART, 0x7fc44793bcc0}, {0x430480, [], SA_RESTORER|SA_RESTART, 0x7fc44793bcc0}, 8) = 0
rt_sigaction(SIGUSR1, {SIG_IGN, [], SA_RESTORER|SA_RESTART, 0x7fc44793bcc0}, {0x430480, [], SA_RESTORER|SA_RESTART, 0x7fc44793bcc0}, 8) = 0
rt_sigaction(SIGUSR2, {SIG_IGN, [], SA_RESTORER|SA_RESTART, 0x7fc44793bcc0}, {0x430480, [], SA_RESTORER|SA_RESTART, 0x7fc44793bcc0}, 8) = 0
close(5)                                = 0
close(4)                                = 0
unlink("/var/run/vrrp.pid")             = -1 ENOENT (No such file or directory)
unlink("/var/run/checkers.pid")         = -1 ENOENT (No such file or directory)
unlink("/a/var/run/keepalived.pid")     = 0
sendto(3, "<142>Aug 10 15:02:08 Keepalived["..., 108, MSG_NOSIGNAL, NULL, 0) = 108
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++

**Comment by pqarmitage** [comment]
I think the first thing to resolve is why is keepalived being sent a SIGHUP, and where is it coming from.

So this is the parent process that is being traced, and it is receiving a SIGHUP from 28679, which is not one of the keepalived processes, which are 28264, 28265 and 28266. What is (was) pid 28679? and why is it signalling keepalived?

Can you post the output of `keepalived -v`. The only way that keepalived can send itself a SIGHUP is from the DBus code, so I want to make sure that isn't enabled.

Can you track down what process is sending the SIGHUP to keepalived, since I think that is the underlying cause of the problem.

**Comment by dotanp** [comment]
root@172.24.166.194:~# /usr/local/akamai/sbin/keepalived -v
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

Copyright(C) 2001-2017 Alexandre Cassen, <acassen@gmail.com>

Build options:  PIPE2 IPV4_DEVCONF IF_H_LINK_H_COLLISION LIBNL3 FRA_OIFNAME FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP RTAX_QUICKACK LVS LIBIPVS_NETLINK VRRP VRRP_AUTH VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC FIB_ROUTING SO_MARK

Yeah, question is , how do I catch it in time when the process crashes to check the pid of the process who sighuped keepalived . It could take between minutes to a couple of hours . Any creative ideas ?

**Comment by pqarmitage** [comment]
Do this help? https://unix.stackexchange.com/questions/44208/does-linux-log-when-a-process-is-started-and-the-pid-that-gets-assigned-to-it

**Comment by dotanp** [comment]
Thanks . Seems like this problem was related to the version of libnl and the bug was already reported:
https://bugs.launchpad.net/ubuntu/+source/libnl3/+bug/1511735
Thanks much for your help!
