### ISSUE TITLE
How to config lvs_timeouts?

### ISSUE THREAD

**Issue by silenceshell** [acassen/keepalived#639]
I want to specify lvs_timeouts for lvs, to keep session remainning for 7200s.
I add a line in global_defs, like:

```
global_defs {
   lvs_timeouts tcp 7200 tcpfin 120 udp 300
}
```

But after keepalived started, the `ipvsadm -l --timeout` is not affected, still the old values(900 120 300). No errors in logs.
Is there something I have to add for lvs_timeouts?

**Comment by pqarmitage** [comment]
Do you have an `lvs_sync_daemon` statement in your globl_defs? Without that, keepalived won't set the sync daemon timeouts.

**Comment by silenceshell** [comment]
After add `lvs_sync_daemon` in globl_defs, `lvs_timeouts` works.
Thanks!  @pqarmitage
