### ISSUE TITLE
Centos7 Build failure - missing docs.

### ISSUE THREAD

**Issue by fenice2** [acassen/keepalived#640]
I've just tried to build the latest 1.3.6 on a CentOS 7.3.1611 server with the following errors:

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.VLucug (%doc)
    File not found: /home/a.user/rpmbuild/BUILDROOT/keepalived-1.3.6-2.x86_64/usr/share/doc/keepalived-1.3.6/README
    File not found: /home/a.user/rpmbuild/BUILDROOT/keepalived-1.3.6-2.x86_64/usr/share/doc/keepalived-1.3.6/TODO
    File not found: /home/a.user/rpmbuild/BUILDROOT/keepalived-1.3.6-2.x86_64/usr/share/doc/keepalived-1.3.6/keepalived.conf.SYNOPSIS
    File not found: /home/a.user/rpmbuild/BUILDROOT/keepalived-1.3.6-2.x86_64/usr/share/doc/keepalived-1.3.6/samples

[a.user@centosdev SPECS]$ ls -l /home/a.user/rpmbuild/BUILDROOT/keepalived-1.3.6-2.x86_64/usr/share/doc/
total 0
drwxr-xr-x 2 a.user a.user 68 Aug 16 17:56 keepalived-1.3.6
[a.user@centosdev SPECS]$ ls -l /home/a.user/rpmbuild/BUILDROOT/keepalived-1.3.6-2.x86_64/usr/share/doc/keepalived-1.3.6
total 316
-rw-r--r-- 1 a.user a.user     41 Aug 14 17:47 AUTHOR
-rw-r--r-- 1 a.user a.user 294910 Aug 14 17:47 ChangeLog
-rw-r--r-- 1 a.user a.user    830 Aug 14 17:47 CONTRIBUTORS
-rw-r--r-- 1 a.user a.user  18092 Aug 14 17:47 COPYING

I also tried with the latest git clone with the same result. Have  I missed something obvious?

Regards

Bill

**Comment by pqarmitage** [comment]
Which kernel.spec file are you using? the one included in the keepalived git repository, or the Centos keepalived.spec file.

If I try building on Fedora using the Centos .spec file I get the same errors as you. If I try building using the keepalived git keepalived.spec file, I get different errors. I will have a look at this later and see what I can find.

**Comment by fenice2** [comment]
My first attempt was from the tar download and I used the spec file from there, it didn't occur to me that the one from the git repository might be different so I was still using the same downloaded tar  spec file.

I will be away until Sunday so I won't be able to try any fix if you produce one before then. :)

Regards


Bill

**Comment by pqarmitage** [comment]
I'm sorry, I think I confused you. The keepalived.spec file from the github.com keepalived repository will be the same. The alternative I was referring to is the Centos one at https://git.centos.org/commit/rpms!keepalived.git/c33c4bfc5135ceb504c727bd4cffd9d73f682f27 .

**Comment by fenice2** [comment]
It was just the one from git that I used not the centos one.

Regards


Bill

**Comment by pqarmitage** [comment]
If you add the line
`mv README.md README`
at the end of the %build block, i.e. after the %{__make} line it should enable the build to work.

I am looking at a proper solution.

**Comment by fenice2** [comment]
Done that, it works a treat. Thanks for that quick workaround. :)

Regards


Bill

**Comment by pqarmitage** [comment]
Commit 3b83f50 properly resolves this issue.
