### ISSUE TITLE
all real servers are not taken into account

### ISSUE THREAD

**Issue by mced** [acassen/keepalived#643]
I'd like to report a behavior that seems to be a bug to me.

According the following virtual_server, we can expect the load balancer will send requests to each real_servers following round robin algorithm.

```
virtual_server 10.0.3.100 80 {
    delay_loop 6
    lb_algo rr
    lb_kind DR
    protocol TCP

    real_server 10.0.3.94 8000 {
        weight 1
    }

    real_server 10.0.3.94 80 {
        weight 1
    }
}
```

But what I discovered is that all real servers are not taken into account. Only the real server sharing the same ip with the others and has the smallest last byte is taken. So in this sample, only `10.0.3.94:80` is considered, the `10.0.3.94:8000` is discarded.

We understand by this is that the linked list containing all real servers in the virtual_server_t struct are not created from file's top to bottom but sorts the real servers before.

That seems to be illogical to setup keepalived in this way but I didn't find any documentation forbidding that way to configure.

Tested with
```
Ubuntu 14.04.5 LTS
Keepalived v1.2.23 (07/26,2016)
```

**Comment by pqarmitage** [comment]
This works fine for me, both with version v1.3.6 and v1.2.23.

I see the following output:
```
# ipvsadm -l
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.0.3.100:http rr
  -> 10.0.3.94:http               Route   1      0          0         
  -> 10.0.3.94:irdmi              Route   1      0          0  
```
which is what I'd expect.

**Comment by mced** [comment]
You're right, I have the same output from ipvsadm -l
But when I setup a http server with python on each port and stress the virtual server I got response only from the http server serving on port 80. The another server on 8000 port is not hit.

I changed the port on the virtual server to 8000 and stressed the virtual ip with 8000 port and I got the same behavior but in this case only the http server on port 8000 is hit.

It seems there is a hard mapping between ports on virtual server and real servers.

**Comment by pqarmitage** [comment]
Your configuration is specifying that Direct Routing is used to the real servers. DR requires that the port of the real server must equal the port of the virtual server. See the man page for ipvsadm:
```
       -r, --real-server server-address
              Real  server  that  an  associated  request  for service may be assigned to.  The server-address is the host
              address of a real server, and may plus port. Host can be either a plain IP address or a hostname.  Port  can
              be either a plain port number or the service name of port.  In the case of the masquerading method, the host
              address is usually an RFC 1918 private IP address, and the port can be different from that of the associated
              service.  With  the tunneling and direct routing methods, port must be equal to that of the service address.
              For normal services, the port specified  in the service address will be used if port is not  specified.  For
              fwmark  services,  port  may  be omitted, in which case  the destination port on the real server will be the
              destination port of the request sent to the virtual service.
```

**Comment by mced** [comment]
What I guess is that packet is just forwarded without being rewrited with real real server port.

I will test a iptables rule and report my results.
