### ISSUE TITLE
ipv6 neighbor table is not updated on new master when switch over happens

### ISSUE THREAD

**Issue by huyvo98** [acassen/keepalived#648]
Hi,

Currently, I see an issue where ipv6 neighbor table is not updated on new master. on all standby nodes, it is updated correctly. 
the command that I use to check ipv6 neighbor table is: ip -6 neigh
the keepalived that I run is 1.3.2, but I also see the same issue on keepalived 1.2.13.

Is the issue reported before? if it was, do we have any plan to fix it?

Thanks,

**Comment by pqarmitage** [comment]
I can see that the ipv6 neighbour table is not updated on the master, but this doesn't appear to be a problem. If, after a new master has taken over, on the new master you send a message to one of the virtual IP addresses (e.g. ping6) the communication is successful but the neighbour table is not updated.

It appears that when the Linux kernel wants to send a packet, it first checks if the address is a local address, and if it is it forwards the packet to the local destination. Only if it is not a local address does it consider the ipv6 neighbour table.
