### ISSUE TITLE
keepalived 1.3.6 does not find scripts

### ISSUE THREAD

**Issue by emcepe** [acassen/keepalived#653]
using keepalived 1.3.6 I get this error messages:

Sep 16 12:13:46 foomaster Keepalived_vrrp[10127]: Unable to access script `/opt/scripts/keepalived/health-check.sh INSTANCENAME IP_TO_CHECK`
Sep 16 12:13:46 foomaster Keepalived_vrrp[10127]: Unable to access script `/opt/scripts/keepalived/vmac.sh backup eth4 vrrp/6`
Sep 16 12:13:46 foomaster Keepalived_vrrp[10127]: Unable to access script `/opt/scripts/keepalived/vmac.sh master eth4 vrrp/6`

downgrading to 1.3.5 works again like any other version before.

health-check.sh is defined as:

        vrrp_script chk_INSTANCE {
                script "/etc/keepalived/health-check.sh INSTANCENAME IP_TO_CHECK"
        }

and vmac.sh is defined as:

        notify_master "/etc/keepalived/vmac.sh master eth4 vrrp/6"
        notify_backup "/etc/keepalived/vmac.sh backup eth4 vrrp/6"

and health-check.sh and vmac.sh are symlinks to /opt/scripts/keepalived

**Comment by pqarmitage** [comment]
This was resolved in commit faf4a87. Apologies for any inconvenience caused.

**Comment by emcepe** [comment]
cool. Thank you! :)

What's up with a 1.3.7 release? I think w/o scripts keepalived is not very usable.

**Comment by acassen** [comment]
will push a new release. Thanks for feedback

**Comment by ErYoung2** [comment]
Have you closed the selinux?

**Comment by pqarmitage** [comment]
@ErYoung2 Could you please explain what you mean by "Have you closed the selinux?".

Please note that this issue was resolved and closed over 2 years ago.

**Comment by ErYoung2** [comment]
> @ErYoung2 Could you please explain what you mean by "Have you closed the selinux?".
> 
> Please note that this issue was resolved and closed over 2 years ago.

I mean, you should set selinux configure to "Permissive" or "Disabled" rather than "Enforcing".
