### ISSUE TITLE
keepalived is not recovered when the management bridge (interface) is added after running keepalived

### ISSUE THREAD

**Issue by huyvo98** [acassen/keepalived#655]
Hi,

on our set up, keepalvied is running on a bridge interface. However, when the keepalived is started, our program has not configured the bridge yet. after some time, we configure the bridge, and expected the keepalvied will recover and start function which it does not.

the issue happens on keepalive 1.2.13 and 1.3.2.
Do we have to have any special configuration for it to work in our situation?

Thanks,
Huy Vo

**Comment by pqarmitage** [comment]
keepalived doesn't (yet) support handling interfaces that are added after it has started running. In fact, if you specify an interface that doesn't exist I would expect keepalived to log an error message "Cant find interface NAME for vrrp_instance ..." and then exit.

I have a version at https://github.com/pqarmitage/keepalived/tree/fixes.quick which supports the dynamic addition and removal of interfaces, so you could try that. It is shortly to be made available as a "beta" release, so if you do try it it would be greatly appreciated if you would report any issues (or successes) that you have.

**Comment by pqarmitage** [comment]
The beta branch should now support this functionality. You will need to add the `dynamic_interfaces` keyword in the `global_defs` section of the config to enable it to work.

See https://github.com/acassen/keepalived/pull/683#issue-269383338 for other new functionality that is included in the beta branch.
