### ISSUE TITLE
keepalived 1.3.7 Email bug

### ISSUE THREAD

**Issue by gregnetau** [acassen/keepalived#666]
Since upgrading to keepalived 1.3.7 i have received 130,000 falsified up/down email alerts. There seems to be some kind of bug since 1.3.6 that is causing this.

**Comment by pqarmitage** [comment]
Could you post some sample output from your logs. It would be helpful if the log output was generated when running keepalived with the -D option.

Could you also post the exact content of the emails, since that also may help tie it down.

**Comment by gregnetau** [comment]
The emails are all "Up" emails - there are no corresponding down emails.

Subject: 
[SJC-FW2] Realserver [XXXX:XXXX:XXXX:dee0::e411]:tcp:443 - UP
Body:
=> CHECK succeed on service <=

I currently can't restart the service but will do tomorrow running as debug.

**Comment by pqarmitage** [comment]
FYI the -D option is for details log output.

It would also be helpful if you could post your config file, and also same of your existing log output.

**Comment by pqarmitage** [comment]
I have set up a simple test using an SSL_CHECK healthchecker and at the moment I'm not getting repeated up emails.

Once I have a copy of your configuration I will try that.

**Comment by gregnetau** [comment]
Rebooting server has resolved the issue.
