### ISSUE TITLE
1.3.5 -> 1.3.7 Config Parsing Regression

### ISSUE THREAD

**Issue by gregnetau** [acassen/keepalived#667]
Hi,

In order to go from keepalived 1.2.x to 1.3.x you helped with a bunch of work to bring our configuration up to vrrp3 and remove syntax/legacy configuration errors.

After upgrading from 1.3.5 to 1.3.7, keepalived now only adds IPv6 virtual servers for the first and last virtual servers in my configuration.

IPVSadm output 1.3.7

TCP  [2406:bd00:de00:de00::10]:80 wrr
  -> [2406:bd00:de00:dee0::e11]:80 Route   80     48         135
  -> [2406:bd00:de00:dee0::e21]:80 Route   80     47         145
  -> [2406:bd00:de00:dee0::e31]:80 Route   80     43         144
  -> [2406:bd00:de00:dee0::e41]:80 Route   80     51         146
TCP  [2406:bd00:de00:de00::29]:80 wrr
  -> [2406:bd00:de00:dee0::e15]:80 Route   80     0          0
  -> [2406:bd00:de00:dee0::e25]:80 Route   80     0          0
  -> [2406:bd00:de00:dee0::e35]:80 Route   80     0          0
  -> [2406:bd00:de00:dee0::e45]:80 Route   80     0          0

IPVSadm output 1.3.5
TCP  [2406:bd00:de00:de00::10]:80 wrr
  -> [2406:bd00:de00:dee0::e11]:80 Route   80     40         106
  -> [2406:bd00:de00:dee0::e21]:80 Route   80     44         102
  -> [2406:bd00:de00:dee0::e31]:80 Route   80     39         109
  -> [2406:bd00:de00:dee0::e41]:80 Route   80     39         102
TCP  [2406:bd00:de00:de00::21]:443 wrr persistent 3600
  -> [2406:bd00:de00:dee0::e12]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e22]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e32]:443 Route   80     1          0
  -> [2406:bd00:de00:dee0::e42]:443 Route   80     1          0
TCP  [2406:bd00:de00:de00::22]:443 wrr persistent 3600
TCP  [2406:bd00:de00:de00::23]:443 wrr persistent 3600
  -> [2406:bd00:de00:dee0::e13]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e23]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e33]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e43]:443 Route   80     0          0
TCP  [2406:bd00:de00:de00::24]:443 wrr persistent 3600
  -> [2406:bd00:de00:dee0::e17]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e27]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e37]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e47]:443 Route   80     0          0
TCP  [2406:bd00:de00:de00::25]:443 wrr persistent 3600
  -> [2406:bd00:de00:dee0::e14]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e24]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e34]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e44]:443 Route   80     0          0
TCP  [2406:bd00:de00:de00::26]:443 wrr persistent 3600
TCP  [2406:bd00:de00:de00::27]:443 wrr persistent 3600
  -> [2406:bd00:de00:dee0::e29]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e39]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e49]:443 Route   80     0          0
TCP  [2406:bd00:de00:de00::29]:80 wrr
  -> [2406:bd00:de00:dee0::e15]:80 Route   80     0          0
  -> [2406:bd00:de00:dee0::e25]:80 Route   80     0          0
  -> [2406:bd00:de00:dee0::e35]:80 Route   80     0          0
  -> [2406:bd00:de00:dee0::e45]:80 Route   80     0          0
TCP  [2406:bd00:de00:de00::29]:443 wrr persistent 3600
  -> [2406:bd00:de00:dee0::e15]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e25]:443 Route   80     0          0
  -> [2406:bd00:de00:dee0::e35]:443 Route   80     0          2
  -> [2406:bd00:de00:dee0::e45]:443 Route   80     0          2

Example config for the 2nd IPv6 virtual server that does not get added in 1.3.7:

virtual_server 2406:bd00:de00:de00::21 443 {
    delay_loop 5
    lb_algo wrr
    lb_kind DR
    persistence_timeout 3600
    protocol TCP

    real_server 2406:bd00:de00:dee0::e12 443 {
        weight 80
                TCP_CHECK {
                        connect_timeout 2
                        bindto 2406:bd00:de00:dee0::e1
                }
     }

    real_server 2406:bd00:de00:dee0::e22 443 {
        weight 80
                TCP_CHECK {
                        connect_timeout 2
                        bindto 2406:bd00:de00:dee0::e1
                }
     }

    real_server 2406:bd00:de00:dee0::e32 443 {
        weight 80
                TCP_CHECK {
                        connect_timeout 2
                        bindto 2406:bd00:de00:dee0::e1
                }
     }

    real_server 2406:bd00:de00:dee0::e42 443 {
        weight 80
                TCP_CHECK {
                        connect_timeout 2
                        bindto 2406:bd00:de00:dee0::e1
                }
     }

}

**Comment by pqarmitage** [comment]
Many thanks for reporting this, and apologies for causing a problem.

Commit 18cc1b4 resolves this issue.

It didn't actually relate to the first and last VSs in the configuration (in fact it was the first and penultimate VSs in your config that worked), but it was any virtual server with persistence configured that had the problem.
