### ISSUE TITLE
Keepalived error

### ISSUE THREAD

**Issue by hw12813** [acassen/keepalived#697]
I can't execute keepalived. Below is detail log.  Please help to assist

Nov  3 17:31:34 sin-apinviewap01 systemd: Starting LVS and VRRP High Availability Monitor...
Nov  3 17:31:34 sin-apinviewap01 kernel: show_signal_msg: 199 callbacks suppressed
Nov  3 17:31:34 sin-apinviewap01 kernel: keepalived[41739]: segfault at 0 ip           (null) sp 00007ffe966336a8 error 14 in libgcc_s-4.8.5-20150702.so.1[7f9c5bf98000+15
000]
Nov  3 17:31:34 sin-apinviewap01 Keepalived[41736]: Starting Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
Nov  3 17:31:34 sin-apinviewap01 systemd: Started LVS and VRRP High Availability Monitor.
Nov  3 17:31:34 sin-apinviewap01 Keepalived[41736]: Unable to resolve default script username 'keepalived_script' - ignoring
Nov  3 17:31:34 sin-apinviewap01 Keepalived[41736]: Opening file '/etc/keepalived/keepalived.conf'.
Nov  3 17:31:34 sin-apinviewap01 journal: Suppressed 17891 messages from /system.slice/keepalived.service
Nov  3 17:31:34 sin-apinviewap01 Keepalived[41737]: Starting Healthcheck child process, pid=41738
Nov  3 17:31:34 sin-apinviewap01 Keepalived[41737]: Starting VRRP child process, pid=41739
Nov  3 17:31:34 sin-apinviewap01 Keepalived_healthcheckers[41738]: Opening file '/etc/keepalived/keepalived.conf'.
Nov  3 17:31:34 sin-apinviewap01 Keepalived_vrrp[41739]: Registering Kernel netlink reflector
Nov  3 17:31:34 sin-apinviewap01 Keepalived_vrrp[41739]: Registering Kernel netlink command channel
Nov  3 17:31:34 sin-apinviewap01 Keepalived_vrrp[41739]: Registering gratuitous ARP shared channel
Nov  3 17:31:34 sin-apinviewap01 Keepalived_vrrp[41739]: Opening file '/etc/keepalived/keepalived.conf'.
Nov  3 17:31:34 sin-apinviewap01 Keepalived_vrrp[41739]: VRRP parsed invalid IP 10.215.20.310. skipping IP...
Nov  3 17:31:34 sin-apinviewap01 Keepalived[41737]: Keepalived_vrrp exited due to segmentation fault (SIGSEGV).
Nov  3 17:31:34 sin-apinviewap01 Keepalived[41737]:  Please report a bug at https://github.com/acassen/keepalived/issues
Nov  3 17:31:34 sin-apinviewap01 Keepalived[41737]:  and include this log from when keepalived started, what happened
Nov  3 17:31:34 sin-apinviewap01 Keepalived[41737]:  immediately before the crash, and your configuration file.
Nov  3 17:31:34 sin-apinviewap01 Keepalived[41737]: VRRP child process(41739) died: Respawning
Nov  3 17:31:34 sin-apinviewap01 Keepalived[41737]: Starting VRRP child process, pid=41740
Nov  3 17:31:34 sin-apinviewap01 Keepalived_vrrp[41740]: Registering Kernel netlink reflector
Nov  3 17:31:34 sin-apinviewap01 Keepalived_vrrp[41740]: Registering Kernel netlink command channel
Nov  3 17:31:34 sin-apinviewap01 Keepalived_vrrp[41740]: Registering gratuitous ARP shared channel
Nov  3 17:31:34 sin-apinviewap01 Keepalived_vrrp[41740]: Opening file '/etc/keepalived/keepalived.conf'.
Nov  3 17:31:34 sin-apinviewap01 Keepalived_vrrp[41740]: VRRP parsed invalid IP 10.215.20.310. skipping IP...
Nov  3 17:31:34 sin-apinviewap01 kernel: keepalived[41740]: segfault at 0 ip           (null) sp 00007ffe96633628 error 14 in libgcc_s-4.8.5-20150702.so.1[7f9c5bf98000+15
000]
Nov  3 17:31:34 sin-apinviewap01 Keepalived[41737]: Keepalived_vrrp exited due to segmentation fault (SIGSEGV).
Nov  3 17:31:34 sin-apinviewap01 Keepalived[41737]:  Please report a bug at https://github.com/acassen/keepalived/issues

**Comment by pqarmitage** [comment]
This is a known issue and is discussed in issues #650 and #654.

I assume you are running on Centos7 or possibly RHEL7.

If you are running with selinux enabled you need to ensure you have selinux-policy version  selinux-policy-3.13.1-166.el7_4.4 or later installed.

You will also need to build your own version of keepalived, using commit 47b5e44 or later. Since you will be building your own version, it might just be worth using v1.3.9.

I have logged an RHEL bug at https://bugzilla.redhat.com/show_bug.cgi?id=1508435 asking that RedHat build a later version of keepalived. it might be worth adding your details to that bug report, especially if you are using RHEL.

**Comment by hw12813** [comment]
Thanks for your inputs. Issue is solved.
