### ISSUE TITLE
fedora 27 keepalived 1.3.9

### ISSUE THREAD

**Issue by sbagmeijer** [acassen/keepalived#700]
I moved recently to Fedora 27 from previously Fedora 26, I am trying to build the latest version of keepalived as a rpm:

Spec file: `https://github.com/ulyaoth/repository/blob/master/ulyaoth-keepalived/SPECS/ulyaoth-keepalived.spec`

Build part:
```
./configure --enable-sha1 --enable-snmp --enable-dbus --prefix=%{_prefix} --sysconfdir=%{_sysconfdir}
make %{?_smp_mflags}

%install
%{__make} DESTDIR=$RPM_BUILD_ROOT INSTALLDIRS=vendor install
```

It works fine on F26, but on Fedora 27 I get this error:

> make[2]: Entering directory '/home/ulyaoth/rpmbuild/BUILD/keepalived-1.3.9/keepalived'
>   CC       main.o
>   CCLD     keepalived
> /usr/bin/ld: core/libcore.a(main.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: vrrp/libvrrp.a(vrrp_iptables_calls.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: vrrp/libvrrp.a(vrrp_ipset.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: vrrp/libvrrp.a(vrrp_snmp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: ../lib/liblib.a(scheduler.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: ../lib/liblib.a(vector.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: ../lib/liblib.a(parser.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: ../lib/liblib.a(signals.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: ../lib/liblib.a(logger.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: ../lib/liblib.a(rttables.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: Nonrepresentable section on output
> collect2: error: ld returned 1 exit status

Does anyone maybe know how I could fix this? I tried to add the "-fPIC" to the configure bit but it did not work, could be I misunderstand the error.

Thank you in advanced for any help.

**Comment by rohara** [comment]
Is there something wrong with the rpm provided in the Fedora repos?

Ryan

**Comment by sbagmeijer** [comment]
> Is there something wrong with the rpm provided in the Fedora repos?

Well I assume you guys make newer versions to be used, we like to stay up to date with the latest release.

Not sure what your comment indicates but I assume you had nothing to contribute on how to resolve the issue?

**Comment by pqarmitage** [comment]
Commit 4954b09 resolves this. It was necessary to add the `-pie` linker option.

In order to build the keepalived package your ulyaoth-keepalived.spec file needs a couple of changes, to remove a dulicated README file and to handle new files in the doc/samples directory. I have submitted a pull request that incorporate those changes and also add some other suggested changes

**Comment by sbagmeijer** [comment]
wow @pqarmitage that is even more i asked for thank you so much really kind of you! I will give it a try directly when I am home!

**Comment by sbagmeijer** [comment]
Can confirm everything is working fine, again many thanks for helping me @pqarmitage

**Comment by rohara** [comment]
​I maintain keepalived for both RHEL and Fedora.​ It appears that
keepalived-1.3.9 was built on October 27 and was available in the testing
repo. I requested that it be pushed to stable on November 9 and it became
available in updates repo on November 11. This is why I was confused about
why you would build the rpm when it was available. If there was a problem
with the package, I would need to know about it, therefore I asked.
