### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by gongdeyang195** [acassen/keepalived#703]
Kernel_Version:2.6.32-696.13.2.el6.x86_64(CentOS6.9)
Keepalived_Version:1.3.9
# ./configure --prefix=/usr/local/keepalived
All is ok.
but:
# make
Making all in lib
make[1]: Entering directory `/usr/local/src/keepalived-1.3.9/lib'
make  all-am
make[2]: Entering directory `/usr/local/src/keepalived-1.3.9/lib'
  CC       parser.o
parser.c: In function ‘read_conf_file’:
parser.c:430: error: ‘O_PATH’ undeclared (first use in this function)
parser.c:430: error: (Each undeclared identifier is reported only once
parser.c:430: error: for each function it appears in.)
make[2]: *** [parser.o] Error 1
make[2]: Leaving directory `/usr/local/src/keepalived-1.3.9/lib'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/local/src/keepalived-1.3.9/lib'
make: *** [all-recursive] Error 1

**Comment by pqarmitage** [comment]
@gongdeyang195 Can you please confirm what kernel version you are using and also what libc library and version. Also what Linux distro you are using and it's version.

I will put together a patch to resolve the problem, but the above information will be helpful to enable me to test it and make sure it will work in your environment.

**Comment by pqarmitage** [comment]
@gongdeyang195 - apologies, I hadn't noticed the kernel version at the top of your post, and also Centos 6.9.

O_PATH was introduced in Linux 2.6.39, which explains the reason for the problem. I'll put a patch together shortly.

**Comment by pqarmitage** [comment]
Commit 6cdd015 should resolve this problem.

In order to get keepalived to build I have to use the `--disable-libiptc` configure option. I'm not yet sure if this is due to RedHat backporting ipset functionality from Linux 2.6.39 to 2.6.32, or whether keepalived needs fixing.

**Comment by gongdeyang195** [comment]
Thanks for you！My glibc version is：
glibc-headers-2.12-1.209.el6_9.2.x86_64
glibc-common-2.12-1.209.el6_9.2.x86_64
glibc-devel-2.12-1.209.el6_9.2.x86_64
glibc-2.12-1.209.el6_9.2.x86_64

**Comment by pqarmitage** [comment]
Commit e941d1b now fixes the problem of building with ipsets, so the `--disable-libipset` option is no longer required (it should have said `--disable-libipset` rather that `--disable-libiptc` in my previous comment.

This now builds in my Centos 6.9 VM without any problems (other than some warnings that aren't issued by current versions of gcc).
