### ISSUE TITLE
unknown state 'EQUAL', defaulting to BACKUP

### ISSUE THREAD

**Issue by cristifalcas** [acassen/keepalived#707]
I get the following warning when running keepalived:

    unknown state 'EQUAL', defaulting to BACKUP

I really like EQUAL, so I was wondering if this has changed.

keepalived is started from a container: openshift/origin-keepalived-ipfailover:v3.6.1

This is the config file used:

        global_defs {
        notification_email_from root@APIAppliance.com
        smtp_server 127.0.0.1
        smtp_connect_timeout 30
        # System identifier for subject of email
        router_id Appliance_hostname-or-IP_address
        }

        vrrp_script check_apiserver {
            script     "/usr/bin/curl -s --cacert /etc/kubernetes/pki/ca.crt https://$(hostname):6443 > /dev/null"
            interval 2
            fall 2
            rise 2
        }

        vrrp_instance apiserver {
            #https://serverfault.com/questions/44122/prevent-vrrp-master-from-becoming-master-once-it-has-failed
            state EQUAL
            priority 100
            nopreempt

            interface         eth0
            virtual_router_id 124

            unicast_peer {
            10.220.24.31
            10.220.24.37
            10.220.24.38
            }
            virtual_ipaddress {
            10.220.24.100
            }
            track_script {
            check_apiserver
            }
        }

**Comment by pqarmitage** [comment]
There are three states that a vrrp instance can be in - master, backup or fault. It doesn't make sense to configure an instance to be in the fault state, so the two configuration options for state are backup and master. Generally one wants to start up in the backup state (which is the default), so the state option doesn't needs to be configured. Configuring state MASTER doesn't actually make the vrrp instance transition to master state immediately (unless the priority is 255), but it only waits for 1 advert interval rather that 3  advert intervals before transitioning to master.

I'm not clear what state EQUAL would mean. If you could explain what you would like to achieve, it is possible that it can already been done, but in some other way, or it might be useful additional functionality that could be added.

So far as I can see keepalived has never supported state EQUAL. Until commit 40e4a178 an unknown state was just silently ignored, commit 40e4a178 added the message you reported, but made no other change in that respect.

**Comment by cristifalcas** [comment]
I took the option from here: https://serverfault.com/questions/44122/prevent-vrrp-master-from-becoming-master-once-it-has-failed

I admit that i didn't read the manual

**Comment by acassen** [comment]
EQUAL has never been part of Keepalived. it is not part of VRRP FSM. In the past everything else than MASTER was falling back to BACKUP while parsing configuration file. So you can even imagine BIGSTATE the result was simply BACKUP.

This is definitely not an issue.
