### ISSUE TITLE
It seems  Bug 1245993 still exists in  the latest 1.3.5 version

### ISSUE THREAD

**Issue by qiyunfeng01** [acassen/keepalived#718]
The previous virtual IP still exists after i restart the keepalived process in master status, from the /var/log/messages it indeed transfer to backup status.
BTW, I use the -P option to run keepalived daemon.

The configuration info on both machines:
[root@master keepalived]# cat /etc/keepalived/keepalived.conf
vrrp_instance VR_1 {
    state BACKUP
    interface eno16777736
    virtual_router_id 1
    priority 50
    garp_master_delay 60
    nopreempt
    advert_int 2
    track_interface {
        eno16777736
    }
    virtual_ipaddress {
        169.254.0.1/24 dev eno16777736
    }
}

[root@slave1 ~]# keepalived -version
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

**Comment by pqarmitage** [comment]
Thank you for reporting this. I presume you are referring to RedHat Bugzilla bug 1245993.

I have been able to reproduce the problem, and commit e90a633c now resolves it. Although commit f4c10426 stated that it resolved the problem, further testing revealed that it didn't resolve the issue for ip addresses, although it did for iptables and ipset configuration.

**Comment by qiyunfeng01** [comment]
Pqarmitage, 
Sorry for the delay,  thanks a lot for your effort.
