### ISSUE TITLE
HA program startup depends on VIP

### ISSUE THREAD

**Issue by linbo** [acassen/keepalived#731]
Hi,

This is not a bug, I just meet a specific scenario and can't figure out an solution when using keepalived.

I want to use Nginx to manager multiple https website, refer to [nginx document](http://nginx.org/en/docs/http/configuring_https_servers.html) (Name-based HTTPS servers section), one method is to assign a separate IP for every HTTPS servers. And in our environment, this is the only method.

Due to single-point issue,  I want to use keepalived to manage master-backup Nginx node.  The logic is:
1. Setup master/backup nginx node
2. Master nginx will assign multiple vip via keepalived
3. Master nginx will be up, backup nginx is down. (due to backup nginx has no vip, start will fail)
4. If master nginx is down, vip transfer to backup node, backup nginx start.

I test in Centos 7 with keepalived v1.3.5, but meet some issue.

# Configuration
## master node
```
global_defs {
   router_id LVS_DEVEL
}

vrrp_script chk_nginx {
    script "/usr/sbin/pidof nginx"
    interval 3
    !weight -5
    rise 1
    fall 2
}

vrrp_instance VI_1 {
    state MASTER
    interface eth1
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        192.168.2.16
        192.168.2.17
    }
    track_script {
        chk_nginx
    }

    notify /etc/keepalived/notify_keepalived.sh
    notify_stop "systemctl stop nginx"
}
```

## backup node
```
global_defs {
   router_id LVS_DEVEL
}

vrrp_script chk_nginx {
    script "/usr/sbin/pidof  nginx"
    interval 3
    !weight -5
    rise 1
    fall 2
}

vrrp_instance VI_1 {
    state BACKUP
    interface eth1
    virtual_router_id 51
    priority 96
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        192.168.2.16
        192.168.2.17
    }
    track_script {
        chk_nginx
    }

    notify /etc/keepalived/notify_keepalived.sh
    notify_stop "systemctl stop nginx"
}
```

```
$ cat /etc/keepalived/notify_keepalived.sh
#!/bin/bash
TYPE=$1
NAME=$2
STATE=$3

echo $STATE > /tmp/k.log
:
case $STATE in
        "MASTER") systemctl start nginx
                  exit 0
                  ;;
        "BACKUP") systemctl stop nginx
                  exit 0
                  ;;
        "FAULT")  systemctl stop nginx
                  exit 0
                  ;;
        *)        echo "ipsec unknown state"
                  exit 1
                  ;;
esac
```

# method 1
If unset weight, keepalived startup will check nginx pid immediately, even I set interval and fall parameter. Master nginx won't enter master state, all node will enter fault state. No master will elect and no active nginx will come up.

```
Dec 30 04:59:00 localhost systemd: Starting LVS and VRRP High Availability Monitor...
Dec 30 04:59:00 localhost Keepalived[20039]: Starting Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
Dec 30 04:59:00 localhost Keepalived[20039]: Unable to resolve default script username 'keepalived_script' - ignoring
Dec 30 04:59:00 localhost Keepalived[20039]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 30 04:59:00 localhost systemd: PID file /var/run/keepalived.pid not readable (yet?) after start.
Dec 30 04:59:00 localhost Keepalived[20040]: Starting Healthcheck child process, pid=20041
Dec 30 04:59:00 localhost Keepalived[20040]: Starting VRRP child process, pid=20042
Dec 30 04:59:00 localhost systemd: Started LVS and VRRP High Availability Monitor.
Dec 30 04:59:00 localhost Keepalived_healthcheckers[20041]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 30 04:59:00 localhost Keepalived_vrrp[20042]: Registering Kernel netlink reflector
Dec 30 04:59:00 localhost Keepalived_vrrp[20042]: Registering Kernel netlink command channel
Dec 30 04:59:00 localhost Keepalived_vrrp[20042]: Registering gratuitous ARP shared channel
Dec 30 04:59:00 localhost Keepalived_vrrp[20042]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 30 04:59:00 localhost Keepalived_vrrp[20042]: VRRP_Instance(VI_1) removing protocol VIPs.
Dec 30 04:59:00 localhost Keepalived_vrrp[20042]: WARNING - script `systemctl` resolved by path search to `/usr/bin/systemctl`. Please specify full path.
Dec 30 04:59:00 localhost Keepalived_vrrp[20042]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Dec 30 04:59:00 localhost Keepalived_vrrp[20042]: Using LinkWatch kernel netlink reflector...
Dec 30 04:59:00 localhost Keepalived_vrrp[20042]: VRRP sockpool: [ifindex(3), proto(112), unicast(0), fd(10,11)]
Dec 30 04:59:00 localhost Keepalived_vrrp[20042]: /usr/sbin/pidof nginx exited with status 1
Dec 30 04:59:01 localhost Keepalived_vrrp[20042]: VRRP_Instance(VI_1) Now in FAULT state
Dec 30 04:59:03 localhost Keepalived_vrrp[20042]: /usr/sbin/pidof nginx exited with status 1
Dec 30 04:59:06 localhost Keepalived_vrrp[20042]: /usr/sbin/pidof nginx exited with status 1
```

# method 2
If uncomment weigth, startup works fine. Master node assign vip and master nginx startup. Backup nginx is down.

However, when I shutdown master nginx, master node priority (100-5) > backup node (96-5). Although master nginx is down, but vip still be in master node.

# method 3
set master weight -5, set backup weigth 2.

1. Startup keepalived, master node get vip, master nginx start. Backup nginx is down.
2. Shutdown master nginx, master node priority 95 < backup node 96, backup node get vip, backup nginx start.
3. Shutdown backup nginx, master node priority 95 < backup node 96(98-2), backup still hold vip, no active nginx come up.

For this scenario, program startup depends on vip, how to manage HA?

Thanks.

**Comment by pqarmitage** [comment]
I think an idea like the following might work. Essentially the notify script saves the state of the vrrp_instance, and the vrrp_track_script only checks if nginx is running if the saved state is MASTER. If the track_script does notice that nginx is not running while the state is MASTER, then it will record the time that it first returns a failure to keepalived. Then, it will continue reporting failure for a further 5 seconds (you may need to adjust that), to ensure that the backup transitions to master. Once it stops reporting failure, the backup will have taken over, and since nopreempt is configured, the lower priority system will remain in master mode until it detects a fault.

This approach will not work using weights due to the `nopreempt`.

I haven't tested it, but it should work.

1. Add keyword `nopreempt` to the vrrp_instance on both systems.

2. Modify /etc/keepalived/notify_keepalived.sh on both systems to the following
```
#!/bin/bash
TYPE=$1
NAME=$2
STATE=$3

case $STATE in
        "MASTER") systemctl start nginx
                  ;;
        "BACKUP") systemctl stop nginx
                  ;;
        "FAULT")  systemctl stop nginx
                  ;;
        *)        echo "ipsec unknown state" >/tmp/$NAME.log
                  exit 1
                  ;;
esac

echo $STATE > /tmp/$NAME.state

exit 0
```

3. In the keepalived configuration, change
```
vrrp_script chk_nginx {
    script "/usr/sbin/pidof nginx"
```
to
```
vrrp_script chk_nginx {
    script "/etc/keepalived/check_nginx"
```

4. Add script /etc/keepalived/check_nginx:
```
#!/bin/bash

# How long we remain indicating fault after reporting nginx not running
FAULT_TIME=5

STATE=$(cat /tmp/VI_1.log)

if [[ -f /tmp/VI_1.log ]]; then
    DOWN_TIME=$(cat /tmp/VI_1.log)
    [[ $((DOWN_TIME + $FAULT_TIME)) -ge $(date -u +%s) ]] && exit 1
    rm -f /tmp/VI_1.log
    exit 0
fi

[[ $STATE != "MASTER ]] && exit 0

# If nginx not running, return 1 so VI_1 transitions to fault state
/usr/bin/pidof nginx
if [[ $? -ne 0 ]]; then
    # Save when we transition to fault state, so stay if fault state for sufficiently long
    echo $(date -u +%s) >/tmp/VI_1.time
    exit 1
fi

exit 0
```

You might need to use the keepalived code from the beta branch, since that will transition to FAULT state immediately the track script returns 1, whereas the code in the master branch will not transition to fault state until the next scheduler advert transmission.

If you do use the beta version of the code, the approach could be optimised by using a track_file, especially if nginx writes a PID file.

**Comment by linbo** [comment]
@pqarmitage Thanks.

I tested the solution, it works. One small issue, if nginx startup time > check interval, keepalived may loop in master elect. I will adjust check interval.
