### ISSUE TITLE
notify.sh perm

### ISSUE THREAD

**Issue by nippo** [acassen/keepalived#742]
Hi, What are the good permissions for a notify script to remove security alert https://github.com/acassen/keepalived/blob/2fe3f8ecfbf68344e27ae89c35b58e30f15ee1ef/lib/notify.c#L626 ?

Thanks!

**Comment by pqarmitage** [comment]
What is being checked (or at least what is intended to be checked) is that if the script is being executed by root, then no part of the path, nor the file itself, can be modified by a non-root user.

The reason for this is that if a script or program is being executed by keepalived with root privileges, then if a non root user is able to modify the script or the path to the script, that user would be able to gain root privileges.

**Comment by nippo** [comment]
If I move notify.sh in /root dir, I don't see the log message no more.  
But I still have a message: "SECURITY VIOLATION - scripts are being executed but script_security not enabled" but I don't know how to enable script_scurity?

**Comment by pqarmitage** [comment]
Add `enable_script_security` to the global_defs section of the config.

**Comment by nippo** [comment]
It works, thanks!
