### ISSUE TITLE
Healthcheck child process(42880) died: Respawning

### ISSUE THREAD

**Issue by yoonico** [acassen/keepalived#747]
log中一直打，我是搭建的keepalived+mysql双主，mysql停止后无法执行杀死keepalived的脚本，使用的是1.4.0版本

Jan 10 00:38:17 localhost Keepalived_healthcheckers[51341]: Opening file '/etc/keepalived/keepalived.conf'.
Jan 10 00:38:17 localhost Keepalived[30802]: Keepalived_healthcheckers exited due to segmentation fault (SIGSEGV).
Jan 10 00:38:17 localhost Keepalived[30802]:  Please report a bug at https://github.com/acassen/keepalived/issues
Jan 10 00:38:17 localhost Keepalived[30802]:  and include this log from when keepalived started, what happened
Jan 10 00:38:17 localhost Keepalived[30802]:  immediately before the crash, and your configuration file.
Jan 10 00:38:17 localhost Keepalived[30802]: Healthcheck child process(51341) died: Respawning
Jan 10 00:38:17 localhost Keepalived[30802]: Starting Healthcheck child process, pid=51343
Jan 10 00:38:17 localhost Keepalived[30802]: Healthcheck child process(51343) died: Respawning
Jan 10 00:38:18 localhost Keepalived[30802]: Healthcheck child process(51347) died: Respawning
Jan 10 00:38:18 localhost Keepalived[30802]: Healthcheck child process(51349) died: Respawning
Jan 10 00:38:18 localhost Keepalived[30802]: Healthcheck child process(51354) died: Respawning
Jan 10 00:38:18 localhost Keepalived[30802]: Healthcheck child process(51358) died: Respawning
Jan 10 00:38:18 localhost Keepalived[30802]: Healthcheck child process(51360) died: Respawning
Jan 10 00:38:18 localhost Keepalived[30802]: Healthcheck child process(51363) died: Respawning
Jan 10 00:38:18 localhost Keepalived[30802]: Healthcheck child process(51365) died: Respawning
Jan 10 00:38:18 localhost Keepalived[30802]: Healthcheck child process(51367) died: Respawning
Jan 10 00:38:18 localhost Keepalived[30802]: Healthcheck child process(51369) died: Respawning
Jan 10 00:38:18 localhost Keepalived[30802]: Healthcheck child process(51371) died: Respawning
Jan 10 00:38:18 localhost Keepalived[30802]: Healthcheck child process(51373) died: Respawning
Jan 10 00:38:18 localhost Keepalived[30802]: Healthcheck child process(51375) died: Respawning

**Comment by pqarmitage** [comment]
Please see the message in the log above: `... and your configuration file`. Also please include the output of `keepalived -v`, what distro you are running on, and the environment keepalived is running in, e.g. directly on the host system, in a VM, in a container etc, and is this the distro's keepalived package or have you built keepalived yourself.

Once we have that information, we can have a look at the problem. It looks as though keepalived is segfaulting before it even opens the configuration file, so could you also try running keepalived with an empty configuration file to see if you still get the segfault.

**Comment by pqarmitage** [comment]
Closing due to no information allowing the problem to be investigated.

If you are still experiencing the problem please provide the additional information identified above and we can then investigate it.
