### ISSUE TITLE
How to create keepalived dump?

### ISSUE THREAD

**Issue by igroost** [acassen/keepalived#750]
Hello.

Please tell me how to make keepalived dump? Have keepalived has key -m which allows you to do a dump. I tried to run keepalived with this key, but where to find the dump is not clear in the log is also no mention if the dump is not. Tell me, in order that the dump was created, you need only specify options or need some kind of OS settings, installed packages?

Tried to ask this question in the mailing list keepalived, but no reply received.

**Comment by pqarmitage** [comment]
On Mon, 2018-01-15 at 12:21 +0000, igroost wrote:
> Hello.
> 
> Please tell me how to make keepalived dump? Have keepalived has key
> -m which allows you to do a dump. I tried to run keepalived with this
> key, but where to find the dump is not clear in the log is also no
> mention if the dump is not. Tell me, in order that the dump was
> created, you need only specify options or need some kind of OS
> settings, installed packages?
> 
> Tried to ask this question in the mailing list keepalived, but no
> reply received.
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

kill -SEGV $(cat /var/run/keepalived.pid)should make it segfault and
cause a coredump. Where it puts it is distro dependant. Look at
/proc/sys/kernel/core_pattern to see what the kernel does with
coredumps.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/acassen/k
> eepalived","title":"acassen/keepalived","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in GitHub","url":"https://gi
> thub.com/acassen/keepalived"}},"updates":{"snippets":[{"icon":"DESCRI
> PTION","message":"How to create keepalived dump?
> (#750)"}],"action":{"name":"View Issue","url":"https://github.com/aca
> ssen/keepalived/issues/750"}}}

**Comment by igroost** [comment]
Thank you
