### ISSUE TITLE
Functionality Question - De-weighting based on hash

### ISSUE THREAD

**Issue by gregnetau** [acassen/keepalived#760]
This may be a feature request or functionality question. I have four real servers under a virtual server, all configured with an SSL_GET test/check and the same weighting.

If a configuration or other outage error occurs, i currently have a sorry_server defined that will point the entire virtual_server load at a specific server. 

The question is - is it possible for a SSL_GET or other up/down check within a real_server to de-weight, or, de-prioritize a real_server within a virtual_server to prevent all real_servers being removed in the event of a specific outage?

Thanks!

**Comment by pqarmitage** [comment]
Currently there is no weight that can be specified for an SSL_GET (or any other checker) that will reduce the weight of a real server, although I can see no reason why this could not be done.

I think, though, that you can achieve what you want by using `quorum` configured against the virtual server. If you want the virtual server to use its working real servers until there are no working real servers, and only then add the sorry server, you could specify `quorum 1`, i.e. 1 real server working is sufficient to enable the virtual server. Likewise `quorum 2` would mean that the real servers would be disabled and the sorry server enabled if only 1 real server is working, but with two working real servers, the virtual server would work normally and the sorry server would be disabled. You can also use `hysteresis` with quorum.

Does this work for you?

**Comment by pqarmitage** [comment]
Closing due to no update for over 2 months.
