### ISSUE TITLE
INSTALL: note linux distro package that provides 'sphinx_rtd_theme'

### ISSUE THREAD

**Issue by salewski** [acassen/keepalived#761]
I just tripped over the below err when building the latest `master` on my Debian machine using the `sphinx-build` tool supplied by version `1.4.9-2` of the `python-sphinx` package:
```
make[1]: Entering directory '/path/to/keepalived/doc'
sphinx-build -b html -d build/doctrees -D latex_paper_size=a4  source build/html
Running Sphinx v1.4.9
loading pickled environment... not yet created

Theme error:
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme)
Makefile:704: recipe for target 'html' failed
make[1]: *** [html] Error 1
make[1]: Leaving directory '/path/to/keepalived/doc'
Makefile:425: recipe for target 'html-recursive' failed
make: *** [html-recursive] Error 1
```
While the error message is helpful, the solution for somebody trying to keep within the distro packaging system would be to install the `python-sphinx-rtd-theme` as a build prerequisite. It might be helpful to add this to the information of other build prereqs already provided in the `INSTALL` file.

While I'm most familiar with Debian, I'll try to put together a small doc patch that addresses all of the distros that currently have a section in the `INSTALL` file (RedHat-based, Debian-based,  Alpine Linux, and Archlinux).

**Comment by pqarmitage** [comment]
Many thanks for this; very happy to merge a patch.

If you (or anyone else) can add information for other distros, that would be much appreciated. The current information is based on experience I have from my main development distro (Fedora) and variuos VMs I have set up.

**Comment by acassen** [comment]
Hello,

BTW, I remove the old deprecated documentation on keepalived.org website and replace it by the contents of sphinx generated doc from source code. In the future, I will automate the documentation update/generation based on git master repo doc directory changes.

**Comment by pqarmitage** [comment]
I have also found that in order to build the latex and pdf files, the following packges are also necessary:
texlive-latex-base texlive-generic-extra texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra

The INSTALL file is now updated with the additional packages that are needed for Debian, and also for Fedora. When you can submit a patch for any other distros, that will be merged.

Commit d52ec01 updates the INSTALL file.

**Comment by salewski** [comment]
Apologies for the delay with my patch; should have sent the pieces I had a few
weeks ago rather than try to go Hole Hawg. I was working on verifying the doc
updates for each distro using Vagrant, but ended-up down a rabbit hole with
CentOS and then got sidetracked with real life.

I've since rebased my changes on top of the changes committed in the interim:

    655d3c7fee17af1bfa0a7baf085e514ec7f9be04

and have created created PR #785.
    
I also updated my changes to include info on building the LaTeX/PDF
documentation. I verified these changes for each distro (using Vagrant), as
well.

In case it is useful for other folks, I've put the distro-specific
`Vagrantfile`'s into GitHub gists:

   * Fedora 27
     https://gist.github.com/salewski/c1c16ca1739307cb7fe158b8c41284cf

   * CentOS 7
     https://gist.github.com/salewski/6ae376bfffb3b282f634aeba1c1b4515
     
   * Debian
     https://gist.github.com/salewski/7996d67445155fc8d8a2b91e4a313cbb
   
   * Ubuntu
     https://gist.github.com/salewski/895ec8b36fa5a431597198992c96ac1b

   * Alpine Linux
     https://gist.github.com/salewski/54bba62d1c90c4d432e03d8ffb08590f
     
   * Archlinux
     https://gist.github.com/salewski/fa3b310f078af721864f7b68029d37ea

Each of those has distro-specific notes in the comments.

For Alpine Linux, I only tested the build of HTML docs because texlive is not
yet a supported package for that distro. See also:

   https://bugs.alpinelinux.org/issues/3920
   https://bugs.alpinelinux.org/issues/4969

Note that for the 'RedHat-based' category, two different distros were used:
CentOS and Fedora. The steps necessary to build the docs on both turned out to
be quite different; I ran into problems that I suspect are limited to CentOS
(and, presumably, RHEL). The underlying issue is documented here:

   * Bug 1492884 - fontawesome-fonts-web doesn't include SVG or WOFF files, breaking many EPEL doc builds
     https://bugzilla.redhat.com/show_bug.cgi?id=1492884

For all but the CentOS distro, simply installing the prerequisite packages
noted is enough to allow `'make html'` from the top of the `keepalived` source
tree to work.

For the CentOS distro, the following is a cookbook that happens to work, but
should become unnecessary once Bug 1492884 is addressed or a more recent
version of the `fontawesome-fonts-web` package (`4.1.0-2` or newer) finds its
way into the core of the distro:

   0. `$ sudo -s`
   1. `# PAGER=/usr/bin/cat man man > /dev/null 2>/dev/null || yum -y reinstall man-pages rpm yum bash`
   2. `# yum -y install git gcc automake autoconf`
   3. `# yum -y install openssl-devel libnl3-devel ipset-devel iptables-devel libnfnetlink-devel`
   4. `# yum -y install python-sphinx`

At this point the `sphinx-build` tool is available, but we still need the
`sphinx_rtd_theme`. That is not available in the core CentOS distro, but it is
available from the "Enterprise Packages for Enterprise Linux"
([EPEL][epel-repo]) repo; the `epel-release` package we'll install next makes
that repo available to the `yum` configuration on local machine, so we can
then install the theme package:

   5. `# yum -y install epel-release`
   6. `# yum -y install python-sphinx_rtd_theme`

At this point the `python-sphinx_rtd_theme` has pulled in the
`fontawesome-fonts-web` dependency, but it is version `4.1.0-1` of the package
which does not include the `fontawesome-webfont.woff` and
`fontawesome-webfont.svg` files (bug 1492884). We'll force an override of this
package with a version from the Fedora project:

   7. `# yum -y install wget`
   8. `# wget -nd 'https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/26/Everything/x86_64/os/Packages/f/fontawesome-fonts-4.7.0-2.fc26.noarch.rpm'`
   9. `# wget -nd 'https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/26/Everything/x86_64/os/Packages/f/fontawesome-fonts-web-4.7.0-2.fc26.noarch.rpm'`
   10. `# rpm -i --nodeps --force ./fontawesome-fonts-4.7.0-2.fc26.noarch.rpm ./fontawesome-fonts-web-4.7.0-2.fc26.noarch.rpm`
   
From this point a "from scratch" doc build for `keepalived` works with just a
little tweaking of the `doc/source/conf.py` file that is used by
`sphinx-build` (adding a python `import` statement and uncommenting an
existing line):

   11. `# exit`
   12. `$ test -d src || mkdir src`
   13. `$ cd src`
   14. `$ git clone https://github.com/acassen/keepalived.git`
   15. `$ cd keepalived`
   14. `$ sed -i.bak -e 's/^\(html_theme = '"'"'sphinx_rtd_theme'"'"'\)/import sphinx_rtd_theme\n\1/' -e 's/^#\(html_theme_path = [[]sphinx_rtd_theme[.]get_html_theme_path[(][)][]]\)/\1/' doc/source/conf.py`
   15. `$ find . -exec touch -r configure {} +`
   16. `$ ./configure --prefix=/tmp/blah-keepalived-build`
   17. `$ make html`

To be able to build the LaTeX and/or PDF documenation, you additionally
need to:

   18. `$ sudo -s`
   19. `# yum -y install latexmk texlive texlive-titlesec texlive-framed texlive-threeparttable texlive-wrapfig texlive-multirow`
   20. `# exit`
   21. `$ cd doc`
   22. `$ make latexpdf`


[epel-repo]: https://fedoraproject.org/wiki/About_EPEL
