### ISSUE TITLE
Unknown keyword 'prompte_secondaries'  in vrrp_instance with 1.4.0 version

### ISSUE THREAD

**Issue by lxf1992521** [acassen/keepalived#763]
version: 1.4.0
system: centos 6.9
configure: enable snmp

I have set “prompte_secondaries” in vrrp_instance blocks, but **Only when** parse conf with "Starting SNMP subagent", it says that "Unknown keyword 'prompte_secondaries'"
————————————————————————————————————
Starting SNMP subagent
Opening file '/etc/keepalived/peer.conf'.
Unknown keyword 'prompte_secondaries'
Opening file '/etc/keepalived/peer.conf'.
Unknown keyword 'prompte_secondaries'
No config files matched 'lvs.d/*.conf'.
Starting SNMP subagent
NET-SNMP version 5.5 AgentX subagent connected
————————————————————————————————————

and Promote_secondaries status is  "disabled"!

**Comment by pqarmitage** [comment]
Yes indeed, there is no keyword `prompte_secondaries` since it should be `promote_secondaries`.

I have tested this, and even without SNMP it logs that `prompte_secondaries` is an unknown keyword.
