### ISSUE TITLE
HTTP_GET not working when UDP protocol is being used for the real_server

### ISSUE THREAD

**Issue by coretemp** [acassen/keepalived#765]
Using keepalived 1.3.6 HTTP_GET functionality appears to be broken when one has a UDP server. 

Executing 
`wget -O - http://192.168.122.145:10000` on the master returns HTTP `status 200`.

On 192.168.122.145 a service is running which unconditionally returns `status 200` for every request to it. 

To be clear: 
On 192.168.122.145:9999 an UDP server is running and on 192.168.122.145:10000 a trivial HTTP (so, TCP) server is running.

I have seen some people use the work around of using a TCP check instead, but what really needs to happen is that this gets fixed, such that people don't need to use workarounds for workarounds anymore.

I am using the following configuration (I am just using a single master for now without backup):

```
global_defs {
}
vrrp_instance VI_1 {
  interface enp0s2
  state MASTER
  virtual_router_id 1
  priority 100
  unicast_peer {
  }
  virtual_ipaddress {
    192.168.122.253/32 dev enp0s2
  }
advert_int 1
}
virtual_server 192.168.122.253 9999 {
  delay_loop 2
  ops
  lvs_sched rr
  lb_algo wlc
  lb_kind NAT
  protocol UDP
real_server 192.168.122.145 9999 {
  weight 1
  HTTP_GET {
    url {
      path /
      status_code 200
    }
    connect_timeout 10
    nb_get_retry 3
    delay_before_retry 3
    connect_port 10000
  }
}
real_server 192.168.122.145 9999 {
  weight 1
  HTTP_GET {
    url {
      path /
      status_code 200
    }
    connect_timeout 10
    nb_get_retry 3
    delay_before_retry 3
    connect_port 10000
  }
}
}
```

**Comment by pqarmitage** [comment]
To make it easier for me to test, can you provide details of how you have set up the HTTP server on 192.168.122.145:10000 to always return HTTP status 200.

**Comment by coretemp** [comment]
I am pretty sure that I did something off HTTP specification here (see also the other issue I reported more recently).

Execute the below script to get the script. 
```
cat <<EOF > ./fakehealth &&
#!/usr/bin/env bash
#
# Fake HTTP 200 OK Daemon
#
PORT=\$1
HTTP_BODY='It Works!'
BODY_LENGTH=$( expr length "\$HTTP_BODY" )
HTTP_HEADER="HTTP/1.1 200 OK\r\n"\
"Content-Type: text/plain\r\n"\
"Content-Length: \$BODY_LENGTH\r\n"\
"Pragma: no-cache\r\n"\
"Expires: Thu, 01 Jan 1970 00:00:00 GMT\r\n"\
"Connection: Close\r\n\r\n"\
"\$HTTP_BODY"

if [ -z "\$PORT" ]; then
    PORT=10000
fi

echo "Fake 200 server listening on port \$PORT"
while true; do echo -e "\$HTTP_HEADER" | nc -l "\$PORT"; done;
EOF

```

**Comment by coretemp** [comment]
https://github.com/acassen/keepalived/issues/766 is likely related.

**Comment by pqarmitage** [comment]
I have tried the above configuration with the dummy http server shown, and so far as I can see it is working as expected.

Could you please provide an explanation what is wrong with what you are experiencing.

BTW, you do not need to specify a device for the virtual_ipaddress when it is the same as the interface of the vrrp instance.

**Comment by pqarmitage** [comment]
@coretemp In your fakehealth script in the penultimate line, adding `-n` option will mean that it sends the number of bytes as specified by `Content-Length`.

**Comment by pqarmitage** [comment]
@acassen Re dropping genhash and using wget/md5sum instead, I can't see an equivalent with wget for using the `--fwmark` option to genhash. All the other genhash options could be specified for wget/md5sum/sha1sum.

**Comment by coretemp** [comment]
The cause was an incorrect HTTP server. Not a keepalived issue.
