### ISSUE TITLE
keepalived crashed with version 1.4.1

### ISSUE THREAD

**Issue by michael2009** [acassen/keepalived#773]
cat /etc/keepalived/keepalived.conf
global_defs {
        router_id test
}

vrrp_script sync_config {
        script "/opt/cmd.sh sync_config"
        interval 10
}

vrrp_instance test {
        authentication {
                auth_type PASS
                auth_pass test
        }

        virtual_ipaddress {
        }

        virtual_routes {
        }

        track_script {
                sync_config
        }

        notify_master "/opt/cmd.sh active"
        notify_backup "/opt/cmd.sh standby"
        notify_fault "/opt/cmd.sh fault"
        notify_stop "/opt/cmd.sh stop"

        interface eth1
        dont_track_primary
        garp_master_delay 2
        priority 100
        advert_int 1
        nopreempt
        state BACKUP
        virtual_router_id 100
        track_interface {
        }
}

cat cmd.sh
#!/bin/sh

**Comment by pqarmitage** [comment]
Could you please provide the log output so that we can see at what point keepalived crashed (I'm assuming its version 1.4.1 you are referring to).

I've tried this config and it works for me, but I can see that there may be some issues due to the unusual configuration, such as empty virtual_ipaddress, virtual_routes and track_interface blocks.

**Comment by michael2009** [comment]
I had enabled debug logs . but no more logs . Please use my config file , then 100% reproduce.

**Comment by michael2009** [comment]
Feb  5 19:19:50 localhost Keepalived[26205]: Starting Keepalived v1.4.1 (unknown)
Feb  5 19:19:50 localhost Keepalived[26205]: Running on Linux 4.9.54-29.el7.x86_64 #1 SMP Tue Oct 10 15:11:23 UTC 2017 (built for Linux 4.9.54)
Feb  5 19:19:50 localhost Keepalived[26205]: Opening file '/etc/keepalived/keepalived.conf'.
Feb  5 19:19:50 localhost Keepalived[26205]: Remove a zombie pid file /var/run/keepalived.pid
Feb  5 19:19:50 localhost Keepalived[26206]: Opening file '/etc/keepalived/keepalived.conf'.
Feb  5 19:19:50 localhost Keepalived[26206]: Registering Kernel netlink reflector
Feb  5 19:19:50 localhost Keepalived[26206]: Registering Kernel netlink command channel
Feb  5 19:19:50 localhost Keepalived[26206]: Registering gratuitous ARP shared channel
Feb  5 19:19:50 localhost Keepalived[26206]: Opening file '/etc/keepalived/keepalived.conf'.
Feb  5 19:19:50 localhost Keepalived[26206]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Feb  5 19:19:50 localhost Keepalived[26206]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Feb  5 19:19:50 localhost Keepalived[26206]: Using LinkWatch kernel netlink reflector...
Feb  5 19:19:50 localhost Keepalived[26206]: VRRP_Instance(E-SBC) Entering BACKUP STATE
Feb  5 19:19:50 localhost Keepalived[26206]: VRRP sockpool: [ifindex(3), proto(112), unicast(0), fd(8,9)]
Feb  5 19:19:50 localhost Keepalived[26206]: assert: signals.c:137: signal_handler: Assertion: `0' failed.

**Comment by pqarmitage** [comment]
The logs above do not appear to be produced from the configuration file that you have provided; the logs refer to vrrp instance E-SBC whereas the configuration file has vrrp instance test.

Could you please provide matching log output (adding the `-D` option would be helpful) and configuration file, and also provide the output of `keepalived -v`.

**Comment by michael2009** [comment]
Please put cmd.sh file to /opt/cmd.sh, then issue come

**Comment by pqarmitage** [comment]
Please build keepalived without the `--enable-debug` option. It should work then.

**Comment by michael2009** [comment]
Yes , Solved if build without --enable-debug
