### ISSUE TITLE
vrrp_script times out

### ISSUE THREAD

**Issue by leonlcw92** [acassen/keepalived#774]
hi , I meet a problem difficult to solve.
```
 Feb  2 20:29:43 master2 Keepalived_vrrp[2558]: VRRP_Script(check-registry) succeeded
 Feb  2 20:29:47 master2 Keepalived_vrrp[2558]: VRRP_Script(check-registry) timed out
 Feb  2 20:29:49 master2 Keepalived_vrrp[2558]: VRRP_Script(check-registry) succeeded
 Feb  2 20:29:55 master2 Keepalived_vrrp[2558]: VRRP_Script(check-registry) timed out
 Feb  2 20:29:57 master2 Keepalived_vrrp[2558]: VRRP_Script(check-registry) succeeded
 Feb  2 20:30:17 master2 Keepalived_vrrp[2558]: VRRP_Script(check-registry) timed out
 Feb  2 20:30:18 master2 Keepalived_vrrp[2558]: VRRP_Script(check-registry) succeeded
 Feb  2 20:31:09 master2 Keepalived_vrrp[2558]: VRRP_Script(check-registry) timed out
 Feb  2 20:31:11 master2 Keepalived_vrrp[2558]: VRRP_Script(check-registry) succeeded
 Feb  2 20:31:45 master2 Keepalived_vrrp[2558]: VRRP_Script(check-registry) timed out
 Feb  2 20:31:47 master2 Keepalived_vrrp[2558]: VRRP_Script(check-registry) succeeded
 Feb  2 20:32:21 master2 Keepalived_vrrp[2558]: VRRP_Script(check-registry) timed out
 Feb  2 20:32:23 master2 Keepalived_vrrp[2558]: VRRP_Script(check-registry) succeeded
```
But my service log shows a normal response, all request  status is 200 

```
Feb  2 20:31:09 master2 docker-registry[3008]: time="2018-02-02T20:31:09+08:00" level=info msg="response completed" http.response.duration=46.776ms http.response.status=200 http.response.written=3212 version="v2.4.1+debian"

```

I want to know what state the "timed out"  will appear

**Comment by leonlcw92** [comment]
Three machines at the same time the emergence of this issue, ( check service is independent )

**Comment by leonlcw92** [comment]
vrrp_script check-registry {
script "check-http.sh '-k  https://127.0.0.1/v2/'"
interval 2
weight -10
}

**Comment by pqarmitage** [comment]
You don't really provide enough information for us to be able to work out what it happening. Can you please provide the following information:

1. A complete copy of your configuration
2. Copies of any other scripts referred to in the configuration file
3. Output of `keepalived -v`
4. A description of the environment you are running in, i.e. what distro and version you are running, and container details etc.
5. Full logs from when keepalived starts, running keepalived with the `-d` option.

Having said the above there is something strange with what is happening. The timeout for scripts defaults to the interval if timeout is not set, so keepalived should be running the check-registry script every 2 seconds and timing out after two seconds (this doesn't fit with the curl command timing out after 10 seconds). After a script fails, the success then occurs 2 seconds later, but why are the timeouts for the scripts taking so long, and also generally increasing.

It would be worth adding some diagnostics into your check-http.sh script, writing what it is doing and what it is returning (with timestamps) to a file.

**Comment by leonlcw92** [comment]
Thank you for your advise.
 I tried to recurrent the problem, but I failed.
If recurrent ,  I will come back

**Comment by pqarmitage** [comment]
Closing issue for now, but if the problem recurs we can re-open it. If the problem recurs, please not e the information required, as set out above, in order to investigate further.
