### ISSUE TITLE
why does this docs incomplete?

### ISSUE THREAD

**Issue by hehe717** [acassen/keepalived#778]
in installing keepalived, 

http://www.keepalived.org/doc/installing_keepalived.html

I think it isn't complete docs, finished by "On RHEL,"

and in this document,

http://www.keepalived.org/doc/configuration_synopsis.html

I can't find vrrp's "script" document.

and also think it is 1.2 version, current version is 1.4 

can you update?
thanks for giving good solution.

**Comment by pqarmitage** [comment]
Commit ea45a4a updates installing_keepalived.rst which is used to generate installing_keepalived.html.

There are three types of script that keepalived can call:
1. notify scripts
2. vrrp track scripts
3. misc_check scripts 
The use of these is explained in doc/keepalived.SYNOPSIS and the keepalived.conf(5) man page.

1. notify scripts
These are called when there is a state transition of a vrrp instance, and are configured by `notify_master`, `notify_backup`, `notify_fault`, `notify_stop` and `notify` keywords (see sections 2 .2 and 2.4 of keepalived.SYNOPSIS).
2. vrrp track scripts
These scripts are used for checking whether a vrrp instance should be forced into fault state, for example if a process that is needed when in master state is not running (see section 2.1 for `vrrp_script` and section 2.4 for `track_script`).
3. misc_check scripts
These scripts are used by the healthchecker to determine whether a real server is unavailable and hence should be disabled in the real server pool.

The documentation is, as you indicate, very old, and we will endeavour to bring it up to date and maintain it thereafter.
