### ISSUE TITLE
exited due to signal 15

### ISSUE THREAD

**Issue by janneojala** [acassen/keepalived#781]
Hello,

I'm getting error on Keepalived v1.3.9  while executing check script on Ubuntu-16.04.2.

/etc/keepalived/check_gateway.sh exited due to signal 15

keepalived.conf:
```
vrrp_script chk_ping {
  script "/etc/keepalived/check_gateway.sh"
  weight 2
  interval 1
}
```

/etc/keepalived/check_gateway.sh:
```
#!/bin/bash
ping_return()
{
    ping -c2 8.8.8.8 > /dev/null  #it's just an example ip
    if [ $? -eq 0 ]
    then
          return 0
    else
          return 1
    fi
 }
 ping_return
```

Permissions should be ok:
```
-rwxr-xr-x   1 root root  543 Feb 14 12:23 check_gateway.sh
-rw-r-----   1 root root  967 Feb 14 11:51 keepalived.conf
-rwxr-xr-x   1 root root  683 Feb 14 11:54 notify_ipsec.sh
```

PRIO should be 152, not 150:
```
ubuntu@vpnserver-se-sthlm-1a-production:/etc/keepalived$ sudo tcpdump -i ens3 -nn 'vrrp'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ens3, link-type EN10MB (Ethernet), capture size 262144 bytes
12:43:03.356857 IP 10.1.100.211 > 224.0.0.18: VRRPv2, Advertisement, vrid 51, prio 150, authtype simple, intvl 1s, length 20
```

**Comment by pqarmitage** [comment]
Could you please provide the full keepalived.conf, the contents of any scripts configured (I presume notify_ipsec.sh is one of them), the full logs of keepalived since it started, and the output of `keepalived -v`.

We can then attempt to reproduce the problem.

**Comment by janneojala** [comment]
Increasing vrrp_script.interval from 1->2 and fix /etc/hosts for missing hostname seams to solve the issue?
