### ISSUE TITLE
Notify_fault is called twice as soon you start keepalived. why?

### ISSUE THREAD

**Issue by LolikaPadmanbhan** [acassen/keepalived#782]
Hi.,
can anyone help me on his ..
On Master Machine every time when we start keepalived , 'Notify fault' is called twice resulting in making the BACKUP Machine --> MASTER and test is started there.

**Comment by pqarmitage** [comment]
Can you please provide the following:
your keepalived configuration file
the full logs of keepalived when run using the `-D` option
your notify scripts
the output of `keepalived -v`

We can then attempt to see what is happening.

**Comment by LolikaPadmanbhan** [comment]
@pqarmitage 
hey since there are too many files in it how do i attach it here? or can i send it to your email id..
thanks!!

**Comment by pqarmitage** [comment]
@LolikaPadmanbhan You could either create a tar file of the files and attach that, or I am happy if you send them directly to me via email.

**Comment by LolikaPadmanbhan** [comment]
@pqarmitage
Sorry i forgot to attach this version of keepalived : Keepalived v1.2.19 (03/13,2017). kindly check the mail and help me out.
Thanks.

**Comment by pqarmitage** [comment]
Your script cl_1.sh you provided is:
```
#!/bin/bash
func_script() {
logger "Inside check script"
if [ $# -ne 3 ]
then
        echo "Insufficient arguments"
        exit 0
fi
for i in "${cla[@]}"
do
        echo $i
        /home/netstorm/lolika/./$i.sh
        retval=$?
        echo $retval
        logger "process:$i Retval:$retval"
        if [ $retval -eq 0 ]
        then
                logger "$i succeeded"
                count=$((count+1))
        fi
done
logger "Count :$count"
if [ $count -eq 3 ]
then
        retval=0
        logger "Check_myscript Retval:$retval"
        return $retval
else
        retval=1
        logger "Check_myscript Retval:$retval"
        return $retval
        echo "retval:$retval"
fi
}
cla=("$@")
func_script $@
```
(I would recommend initialising `count` to 0 at the beginning of `func_script()` since if none of the scripts exists the line `if [ $count -eq 3 ]` gives a syntax error; this doesn't appear to be the cause of the problem though).

and the initial log output is
```
Feb 15 16:48:19 ubuntu Keepalived_healthcheckers[47844]: Opening file
'/etc/keepalived/keepalived.conf'.
Feb 15 16:48:19 ubuntu Keepalived_vrrp[47846]: Configuration is using : 78630 Bytes
Feb 15 16:48:19 ubuntu Keepalived_vrrp[47846]: Using LinkWatch kernel netlink reflector...
Feb 15 16:48:19 ubuntu Keepalived_vrrp[47846]: VRRP_Instance(VI_2) Entering BACKUP STATE
Feb 15 16:48:19 ubuntu Keepalived_vrrp[47846]: Opening script file
/home/netstorm/lolika/notify_backup.sh
Feb 15 16:48:19 ubuntu Keepalived_healthcheckers[47844]: Configuration is using : 12201 Bytes
Feb 15 16:48:19 ubuntu Keepalived_healthcheckers[47844]: Using LinkWatch kernel netlink
reflector...
Feb 15 16:48:19 ubuntu root: Inside check script
Feb 15 16:48:19 ubuntu root: Inside check script
Feb 15 16:48:19 ubuntu root: Inside Notify_fault, Retval:1
Feb 15 16:48:22 ubuntu Keepalived_vrrp[47846]: VRRP_Instance(VI_1) Now in FAULT state
Feb 15 16:48:22 ubuntu Keepalived_vrrp[47846]: Opening script file
/home/netstorm/lolika/notify_fault.sh
Feb 15 16:48:22 ubuntu Keepalived_vrrp[47846]: Opening script file
/home/netstorm/lolika/notify_fault.sh
Feb 15 16:48:22 ubuntu root: Inside Notify_fault: Retval:1
Feb 15 16:48:22 ubuntu root: Inside Notify_fault: Retval:1
Feb 15 16:48:22 ubuntu root: Creating Process pname:test1
Feb 15 16:48:22 ubuntu root: Creating Process pname:test1
Feb 15 16:48:22 ubuntu root: PID=47876#01247877
Feb 15 16:48:23 ubuntu root: PID=47876#01247877
Feb 15 16:48:24 ubuntu root: Inside check script
Feb 15 16:48:25 ubuntu root: process:t1 Retval:0
Feb 15 16:48:25 ubuntu root: t1 succeeded
Feb 15 16:48:25 ubuntu root: process:t2 Retval:0
Feb 15 16:48:25 ubuntu root: t2 succeeded
Feb 15 16:48:25 ubuntu root: Inside check_myscript , Retval:0 PID:47876#01247877
Feb 15 16:48:25 ubuntu root: process:t3 Retval:0
Feb 15 16:48:25 ubuntu root: t3 succeeded
Feb 15 16:48:25 ubuntu root: Count :3
Feb 15 16:48:25 ubuntu root: Check_myscript Retval:0
Feb 15 16:48:29 ubuntu Keepalived_vrrp[47846]: VRRP_Instance(VI_2) Now in FAULT state
Feb 15 16:48:29 ubuntu Keepalived_vrrp[47846]: Opening script file
/home/netstorm/lolika/notify_fault.sh
Feb 15 16:48:29 ubuntu Keepalived_vrrp[47846]: Opening script file
/home/netstorm/lolika/notify_fault.sh
Feb 15 16:48:29 ubuntu root: Inside Notify_fault: Retval:1
Feb 15 16:48:29 ubuntu root: Creating Process pname:sig
Feb 15 16:48:29 ubuntu root: Inside Notify_fault: Retval:1
Feb 15 16:48:29 ubuntu root: Creating Process pname:sig
Feb 15 16:48:29 ubuntu root: PID=47911
Feb 15 16:48:29 ubuntu root: PID=47911#01247915
```

Firstly, this works for me, and I don't get VI_2 transitioning to fault state. However, it appears that there is something strange happening on your system.

At 16:48:19 there are the following log entries, which are for initial runs of the check script for VI_1 and VI_2:
```
Feb 15 16:48:19 ubuntu root: Inside check script
Feb 15 16:48:19 ubuntu root: Inside check script
```
but there is no more log output from the scripts, as there is at 16:48:24, so it would appear that for some reason the scripts aren't running properly, which could be the reason why VI_1 is going to fault state.

Executing the notify_fault script twice appears to be a bug in v1.2.19, which has been resolved at some time since v1.2.19 since the notify_fault script is only executed once when using v1.4.1.

As always, I would recommend upgrading to the latest version of keepalived since there have been many bug fixes (and enhancements) since v1.2.19.

**Comment by LolikaPadmanbhan** [comment]
@pqarmitage Hey, will upgrade and check. 
Thanks for the help. will get back if i come across any error :-)

**Comment by LolikaPadmanbhan** [comment]
@pqarmitage hi, i have upgraded to the latest version which is v1.4.1, now the problem is the that vrrp_instances continues to be in the fault state. i don't know why am unable to figure out. the same files works fine in the old version. i don't know where am i going wrong. 
Am sending you the log and configuration file to your mail. kindly help me out.
Thanks !

**Comment by pqarmitage** [comment]
You have two vrrp instances, and each one has a track_script. The scripts are:
**cl_sig.sh**
```
#!/bin/bash
find_pid() {
    pid=$(pgrep -x "sig")
    if ! kill -0 $pid
    then
        retval=1
    else
        retval=0
    fi
    logger "Inside check_myscript SIG, Retval:$retval PID:$pid"
    return $retval
}
find_pid
```
and
**cl_test.sh**
```
#!/bin/bash
find_pid() {
    pid=$(pgrep -x "test1")
    if ! kill -0 $pid
    then
        retval=1
    else
        retval=0
    fi
    logger "Inside check_myscript TEST1, Retval:$retval PID:$pid"
    return $retval
}
find_pid
```
and you also have a notify_backup script
**notify_backup.sh**
```
#!/bin/bash
logger "Inside Notify_backup "
name=$1
pid=$(pgrep -x "$name")
echo "checking"
if ! kill -0 $pid
then
    retval=1
else
    retval=0
fi
if [ $retval -eq 0 ]
    then
    logger "Killing Process Name:$1"
    echo "killing"
    kill -9 $pid
fi
```
and a notify_fault script
**notify_fault.sh**
```
#!/bin/bash
find_pid() {
    pname=$1
    pid=$(pgrep -x "$pname")
    if ! kill -0 $pid
    then
        retval=1
    else
        retval=0
    fi
    logger "Inside Notify_fault $1 : Retval:$retval"
    if [ $retval -eq 1 ]
    then
        logger "Creating Process Pname:$pname"
        /home/parallels/./$pname &
        pid=$(pgrep -x "$pname")
        logger "pid:$pid"
    fi
}
find_pid $1
```

The notify_backup script is called with a single parameter, either `1` or `2` depending on whether it is called for vrrp instance VI_1 or VI_2. The notify_backup script is therefore attempting to kill a process whose name is either `1` or `2`, and these seem unlikely names for processes. The log output shows that the script does not find the process.

The log output from running the `cl_sig.sh` script is
```
Feb 20 09:55:59 Syslog_client root: <13>Feb 20 09:55:59 root: Inside check_myscript SIG, Retval:1
PID:
Feb 20 09:55:59 Syslog_client Keepalived_vrrp[23381]: <142>Feb 20 09:55:59
Keepalived_vrrp[23381]: VRRP_Script(check_myscript_sig) failed (exited with status 1)
```
and there is similar output from running cl_test.sh.

The log output shows that $retval = 1 and $pid is empty, and this would imply that there is no process called `sig` running. Therefore you would expect the script to exit with status 1 and so the vrrp instance should transition to fault state. It appears that keepalived is behaving correctly.

There are also some issues with your scripts:

A test after the line `pid=$(pgrep -x "sig")` to see whether that failed or not would be a good idea:
```
pid=$(pgrep -x "sig")
[[ $? -ne 0 ]] && return 1
if ! kill -0 $pid
```

The output from executing the notify_fault.sh script is:
```
Keepalived_vrrp[23381]: Opening script file /home/parallels/notify_fault.sh
Feb 20 09:56:00 Syslog_client root: <13>Feb 20 09:56:00 root: Inside Notify_fault test1: Retval:1
Feb 20 09:56:00 Syslog_client root: <13>Feb 20 09:56:00 root: Creating Process Pname:test1
Feb 20 09:56:00 Syslog_client root: <13>Feb 20 09:56:00 root: pid:
```
Again, a check for whether the `pgrep`s are successful would be beneficial. Also, the output shows that process test1 either hasn't been successfully started, or that it exited immediately.

Taking your notify_fault.sh script as an example, the following might be better:
```
#!/bin/bash
find_pid() {
    pname=$1
    pid=$(pgrep -x "$pname")
    if [[ $? -ne 0 ]]
    then
        retval=1
    else
        retval=0
    fi
    logger "Inside Notify_fault $1 : Retval:$retval"
    if [ $retval -eq 1 ]
    then
        logger "Creating Process Pname:$pname"
        /home/parallels/./$pname &
        if [[ $? -ne 0 ]]
        then
            logger "Failed to start process $pname"
        else
            pid=$(pgrep -x "$pname")
            if [[ $? -ne  0 ]]; then
                logger "Failed to find $pname after starting it"
            else
                logger "pid:$pid"
            fi
        fi
    fi
}
find_pid $1
```

I hope that helps.

**Comment by pqarmitage** [comment]
Closing due to no response for 13 days.
