### ISSUE TITLE
lvs_id is an unknown keyword

### ISSUE THREAD

**Issue by coretemp** [acassen/keepalived#789]
I have this in my configuration (copy pasted byte by byte) excluding the <snip>, but it says that lvs_id is an unknown keyword, which according to the documentation it is not.  

Version: 1.35 (because 1.41 is broken for me for which there is another issue).

```
global_defs {

  ! this should be defined here, but it apparently doesn't work as advertised
! lvs_sync_daemon_interface eth0 VI_2
! name of the LVS director
lvs_id LVS_2

}
```

**Comment by pqarmitage** [comment]
`lvs_id` was changed to `router_id` in keepalived v1.1.8, and although the commit says `lvs_id kept for backward compatibility`, it wasn't.

Before you say it, yes, the documentation needs updating! The best place to find current documentation is in doc/keepalived.SYNOPSIS or the man page keepalived.conf(5).

I had a go at updating the RST format documentation, but I couldn't get it to format properly. I will have another go when I have some time.

**Comment by coretemp** [comment]
@pqarmitage  `lvs_sync_daemon_interface eth0 VI_2` also wasn't working. Do you know why that might  happen? I thought it was moved to work in the global_defs block, because of the confusion it caused for users.  Was that also renamed?

**Comment by pqarmitage** [comment]
The keyword is `lvs_sync_daemon` in global_defs.

**Comment by coretemp** [comment]
Thank you, parsing errors are gone, not tested yet whether the feature works.
