### ISSUE TITLE
1.42 nice to have: Remove ambiguity

### ISSUE THREAD

**Issue by coretemp** [acassen/keepalived#792]
While it's a good thing to say "We are not sure whether this will work", perhaps it's better to just fail hard and say "There is no reason this is going to work" and then `exit 1`. One could always add an option `--i_am_keepalived_dev` to work around it, but this would also simplify support (because less configurations are supported).

`WARNING - keepalived was build for newer Linux 4.15.0, running on Linux 4.9.75`

The best option would be for the software to actually know its exact run-time compatibility with the various kernels and either work (and not warn) or fail as specified above.

**Comment by pqarmitage** [comment]
We can't actually say what features a kernel supports by its version number. For example, Red Hat have in the past backported some newer kernel functionality into an older kernel (e.g. partial backport of lightweight tunnels, ipsets) - see commits c134bf4 and e941d1b. This would also create a large amount of bloat in the keepalived executable, and would encourage us not to make use of newer kernel features. The best we can do is to check for the functionality in the kernel headers at build time.

I think if we exited if the runtime kernel were older than the kernel headers against which keepalived was built we would get a lot of complaints, and would have to revert the change. Also, if someone upgraded their system and that included an upgrade of both keepalived and the kernel, then keepalived wouldn't be able to be started again until the system had been rebooted.

If there is an easy way for us to handle it better, I am happy to consider it, but I think refusing to run is not the best way.

**Comment by coretemp** [comment]
Thank you.

The warning message should say `was built`, not `was build`, btw.

I currently cannot run 1.42, because I cannot run that kernel, because of another dependency of my project not compiling against that kernel, but I hope to be able to switch in a couple of days.
