### ISSUE TITLE
vrrp instance erroneously transitions to master state when vlan is removed

### ISSUE THREAD

**Issue by kczauz** [acassen/keepalived#798]
While doing some testing of my keepalived configuration, I noticed something odd.  On my BACKUP vrrp_instance, when the underlying vlan configuration is removed from the switchport, the BACKUP vrrp_instance transitions to MASTER STATE:

this is what my `keeplived.conf` looks like for the backup vrrp instance:
```bash
vrrp_instance prd1 {
    state BACKUP
    interface prd1.302
    virtual_router_id 51
    nopreempt
    priority 100
    advert_int 1
    notify /etc/keepalived/state-change-prd1.sh
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        10.0.0.102
    }
}
```

And when I remove the vlan 302 from the switchport on the switch, this is what keepalived log looks like:
```bash
Mar  5 16:07:46 my_host Keepalived_vrrp[27246]: VRRP_Instance(prd1) Transition to MASTER STATE
Mar  5 16:07:47 my_host Keepalived_vrrp[27246]: VRRP_Instance(prd1) Entering MASTER STATE
Mar  5 16:07:47 my_host Keepalived_vrrp[27246]: VRRP_Instance(prd1) setting protocol VIPs.
Mar  5 16:07:47 my_host Keepalived_vrrp[27246]: Sending gratuitous ARP on prd1.302 for 10.0.0.102
Mar  5 16:07:47 my_host Keepalived_vrrp[27246]: VRRP_Instance(prd1) Sending/queueing gratuitous ARPs on prd1.302 for 10.0.0.102
```

any idea whats happening here?

**Comment by pqarmitage** [comment]
Could you please provided:
1.The output of keepalived -v
2. The system logs at the time that the vlan is removed
3. A description of the environment this keepalived is running in, e.g. what Linux distro and version, whether you are running in a VM, container etc.

I've not heard of this problem before, but the above information might help reproduce the problem.

**Comment by kczauz** [comment]
Hello,

I just tried this with the latest version of keepalived - same issue:
```bash
 /usr/local/sbin/keepalived -v
Keepalived v1.4.2 (02/24,2018), git commit v1.4.1-41-g6a2987e+

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016

Build options:  PIPE2 RTA_ENCAP RTA_EXPIRES FRA_OIFNAME FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LVS VRRP VRRP_AUTH VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE OLD_CHKSUM_COMPAT FIB_ROUTING INET6_ADDR_GEN_MODE SO_MARK
```

I originally ran this the rpm version for centos 7, and had the same issue:
```bash
keepalived -v
Keepalived v1.2.13 (11/05,2016)
```

There is nothing in the system logs when removing the vlan, the output in the first post with the keepalived logs was taken from ```/var/log/messages```, and there were no other logs from the system around that time.

I am running a bare metal host, with ```CentOS Linux release 7.3.1611 (Core)```

One thing to note though, is that I am running a different configuration than I have seen documented.  I am running both my MASTER and BACKUP vrrp instances on the same node, just using different interfaces:
```bash
! Configuration File for keepalived

global_defs {
   notification_email {
     sysadmin@mydomain.com
     support@mydomain.com
   }
   notification_email_from lb1@mydomain.com
   smtp_server localhost
   smtp_connect_timeout 30
}

vrrp_instance prd0 {
    state MASTER
    interface prd0.302
    virtual_router_id 51
    nopreempt
    priority 101
    advert_int 1
    notify /etc/keepalived/state-change-prd0.sh
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        10.0.0.102
    }
}

vrrp_instance prd1 {
    state BACKUP
    interface prd1.302
    virtual_router_id 51
    nopreempt
    priority 100
    advert_int 1
    notify /etc/keepalived/state-change-prd1.sh
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        10.0.0.102
    }
```

My goal here is to provide HA without using any bonding.  The virtual IP address allows for end users to access the host with a single ip address, even in the event of a nic failure, and the notify script can manage the routing table / default route when one of the nics fails.  Is there any reason keepalived should not work in the configuration above?

**Comment by pqarmitage** [comment]
I should have realised this before. When the underlying vlan configuration is removed from the switchport, the switch stops forwarding any traffic on that VLAN to the connected interface. The backup instance therefore stops receiving VRRP adverts, times out and transitions to master.

Does this seem reasonable to you?

**Comment by kczauz** [comment]
Yes, that makes sense.

Is there anything I can do in my scenario to prevent this?  Since both vrrp instances are on the same host, is there a way I can check in the primary interface is still up and functional, and stop the backup from transitioning?  I'm even ok with just shutting down the backup interface when something like this occurs.

**Comment by pqarmitage** [comment]
I think it is probably very difficult to distinguish between a NIC failure, which you want to detect, and the deletion of a vlan. Presumably if the vlan on the NIC that the master instance is using were deleted, you would want the backup to become master.

**Comment by pqarmitage** [comment]
Closing due to no response for 41 days. If you have any further issues with this, please report them against this issue and it can be reopened.
