### ISSUE TITLE
vrrp_script does not execute

### ISSUE THREAD

**Issue by stfast** [acassen/keepalived#802]
Hi, 

I have a problem since tracking script is invoked only on keepalived startup/restart and so does not failover when status is changed. There is no reocurring of vrrp_script execution for given interval.

- System verisons

cat /etc/redhat-release 
Fedora release 27 (Twenty Seven)

keepalived -v
Keepalived v1.4.2 (02/24,2018), git commit v1.4.1-41-g6a2987e+
Built with kernel headers for Linux 4.15.7
Running on Linux 4.15.6-300.fc27.x86_64 #1 SMP Mon Feb 26 18:43:03 UTC 2018

Build options:  PIPE2 IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF RTA_VIA FRA_OIFNAME FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_UID_RANGE LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_DYNAMIC LVS LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP VRRP_AUTH VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE OLD_CHKSUM_COMPAT FIB_ROUTING INET6_ADDR_GEN_MODE SNMP_V3_FOR_V2 SNMP SNMP_VRRP SNMP_CHECKER SNMP_RFC SNMP_RFCV2 SNMP_RFCV3 SO_MARK

- Configuration 

 cat /etc/keepalived/keepalived.conf
....
vrrp_script mysql_check {
	script "/usr/libexec/keepalived/mysql_check.sh"
	interval 5
	fall 1
	rise 2
	weight -2
}

vrrp_instance base1 {
	state MASTER
	interface vlan3101
	virtual_router_id 1
	priority 150
	advert_int 1
	garp_master_delay 1
	use_vmac
	vmac_xmit_base
	authentication {
		auth_type PASS
		auth_pass ******
	}
	virtual_ipaddress {
		172.16.103.11/24 dev vlan103-vip
	}
	track_script {
		mysql_check
	}
       #/# notify conntrackd
	notify_master "/usr/libexec/keepalived/primary-backup.sh primary"
	notify_backup "/usr/libexec/keepalived/primary-backup.sh backup"
	notify_fault "/usr/libexec/keepalived/primary-backup.sh fault"
	smtp_alert
}

- Script is executed only once, on restart and there isn't any occurrence for vrrp_script in  given interval:

cat /var/log/messages|grep VRRP_Script
Mar 12 14:01:39 starbase1 Keepalived_vrrp[26664]: VRRP_Script(mysql_check) succeeded
Mar 12 14:04:17 starbase1 Keepalived_vrrp[26971]: VRRP_Script(mysql_check) succeeded
Mar 12 14:05:29 starbase1 Keepalived_vrrp[27110]: VRRP_Script(mysql_check) succeeded
....

- Tracking script

cat /usr/libexec/keepalived/mysql_check.sh
##!/bin/bash
#/# monitor mysql status
#/# if this node mysql is dead and its slave delay less than 120 seconds, then stop its keepalived. The other node will bind the IP.
 
export MYSQL_HOME=/usr
export PATH=$MYSQL_HOME/bin:$PATH
 
mysql="$MYSQL_HOME/bin/mysql"
 
$mysql --connect_timeout=2 --execute="select version();"

echo $?
 
if [ $? -ne 0 ]; then
  exit 1 #bad
else
  exit 0 #good
fi

**Comment by dclabaut-ovh** [comment]
Hello,
There are no logs for vrrp scripts unless the state changes. This change was, I believe, introduced in version 1.4.0:
*  Rationalise reporting of child process exit status.
  report_child_status() is now only called in the main keepalived
  program. The reporting of the exit status of vrrp track scripts
  and MISC_CHECK scripts is now handled in the specific code for
  those scripts. This means that non 0 exit statuses aren't
  repeatedly reported for vrrp track scripts.
If you modify the script while keepalived is running to make it return 1, does Keepalived send a log line ?
You can do so (on a lab environment) by putting "exit 1" on the line before the first export MYSQL_HOME.
Regards,

**Comment by stfast** [comment]
I've changed mysql_check script and looks  that  $? (exit status of the last executed command) executed from keepalived is always 1 (false!?), but from shell directly is 0 (right!?)  

#!/bin/bash
# monitor mysql status

/usr/bin/mysql --connect_timeout=2 --execute="select version();"
#exit $?
echo $? >> /tmp/keepalived


[root@starbase1 keepalived]# ./mysql_check.sh 
+-----------------+
| version()       |
+-----------------+
| 10.2.12-MariaDB |
+-----------------+
[root@starbase1 keepalived]# ./mysql_check.sh 
+-----------------+
| version()       |
+-----------------+
| 10.2.12-MariaDB |
+-----------------+
[root@starbase1 keepalived]# ./mysql_check.sh 
+-----------------+
| version()       |
+-----------------+
| 10.2.12-MariaDB |
+-----------------+

[root@starbase1 keepalived]# tail -f /tmp/keepalived 
1 - keepalived mysql_check
1 - keepalived mysql_check
1 - keepalived mysql_check
1 - keepalived mysql_check
1 - keepalived mysql_check
0 - ./mysql_check.sh from shell
1 - keepalived mysql_check
0 -  ./mysql_check.sh  from shell
0 -  ./mysql_check.sh  from shell
1 - keepalived mysql_check

**Comment by stfast** [comment]
OK, found out, that this is password related, since script executed from keepalived does not read .my.cnf where root password is stored.

Hm, how can we achieve that?!

**Comment by pqarmitage** [comment]
In the mysql_check script, add `-u USER -pPASSWORD` to the `/usr/bin/mysql` command line (replacing USER and PASSWORD with relevant values).

For security reasons you will probably want to give USER minimal mysql privileges, in particular no access to any databases.

An alternative might be to add a `.my.cnf` for the root user, but that probably isn't a good idea from a security perspective.

Yet another alternative would be to add a line `user USERNAME` in the `vrrp_script mysql_check` block, and add a .my.cnf file for the specified user.
