### ISSUE TITLE
SSL_GET: SNI support

### ISSUE THREAD

**Issue by costela** [acassen/keepalived#804]
It seems the [SSL_GET check does not use SNI](https://github.com/acassen/keepalived/blob/master/keepalived/check/check_ssl.c) (no call to `SSL_set_tlsext_host_name`) when checking. This is an issue for cases where the `real_server`s have no sane fallback vhost for connections without SNI.

Any reason why this isn't done by default? If there is, anything against providing an argument to SSL_GET to use it?

Or maybe I'm missing something obvious?

**Comment by pqarmitage** [comment]
I can't see any reason why this shouldn't be done, and it sounds like a useful addition.

Are you able to provide a patch?

**Comment by costela** [comment]
My C is pretty rusty, but I can give it a go.
I believe it might be OK to use it per default (without a switch to enable/disable it), because:
1. the SNI extension should be ignored by `real_servers` that don't support it.
2. since we currently also don't verify either certificate validity or domain match, the fact that we suddenly might get a different certificate with SNI should not change the result of the check.

There might be edge-cases where the `real_server` rates SNI higher than the `Host` header when selecting a vhost, which would mean we might suddenly get different content, but I don't know of any such case. Do you think this warrants a "disable SNI" switch?

**Comment by pqarmitage** [comment]
I think what we should have is an `enable_sni` option in the SSL_GET configuration block, so that backwards compatibility is guaranteed to be maintained.

Since your C is rusty, I'm happy to put a patch together if you could then test it before it is released, although if you'd like to produce the patch yourself I'd be more than happy for you to do so.

**Comment by costela** [comment]
Ok, sounds reasonable.
I'll try to cook something up over the weekend. If I got nothing until next week, than I'd still be happy to test it! :)

**Comment by costela** [comment]
Got a first pass in #814. Would appreciate some constructive feedback! :)
