### ISSUE TITLE
persistence_granularity validation logic is inverted

### ISSUE THREAD

**Issue by sim-** [acassen/keepalived#806]
Hello :)

I'm in the process of a cluster migration and, in the process, upgrading to a newer keepalived. I had "persistence_granularity 255.255.255.192" (using fwmarks), but this is now being rejected:

Thu Feb  8 21:40:54 2018: Invalid IPv4 persistence_granularity specified - 255.255.255.192

The validation in keepalived/check/check_parser.c's pgr_handler() seems to have an inverted logic test for the result from inet_aton():
    
    if (inet_aton(strvec_slot(strvec, 1), &addr)) {
            log_message(LOG_INFO, "Invalid IPv4 persistence_granularity specified - %s", FMT_STR_VSLOT(strvec, 1));

from the inet_aton man page, "inet_aton() returns 1 if the supplied string was successfully interpreted".

BTW, the last touch to the "if" line was be7ae8008 "Stop segfaulting when configuration keyword is missing its parameter", which was released back in v1.3.0. However, before that, fecfe5af9 changed inet_ston to inet_aton, which seems to have the same return values as the standard inet_aton, but started checking the return value.

Looking back to v1.2.2, where I know it used to work, inet_ston() is used without checking the return value.

So, I think it has been broken since fecfe5af9 (v1.2.24), according to git tag --contains! I guess not many people use this...

BTW, in noticing be7ae8008, I should also point out that I was hitting a segfault for having "nb_get_retry" with no value. It seems there is still some missing logioc for this.

Made pull request https://github.com/acassen/keepalived/pull/805

**Comment by pqarmitage** [comment]
Many thanks for the patch, now committed, and the detailed analysis.

The commit be7ae80 you referenced above that was designed to stop keepalived from segfaulting if parameters were missing missed the "hidden" uses of vector_slot() - i.e. those used via definitions in header files. Commit aa64424 resolves the segfault. Many thanks for reporting this.

BTW `nb_get_retry` is now deprecated. Use `retry` for consistency across all checkers.
