### ISSUE TITLE
Long-lived tcp Websocket connections not failing over

### ISSUE THREAD

**Issue by mikekuzak** [acassen/keepalived#808]
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

We see the following behavior with Web Sockets:
If KAD failover is triggered but the first box is still up with having a long lived Websocket connection it does not seem this connection is terminated but still live with no data being transmitted as the second server now is active.  Any idea if this behavior can be controlled to drop the current TCP connection, and reestablish to the new server ?

**Comment by pqarmitage** [comment]
Could you please provide a more detailed description of what you are experiencing. What do you mean by Web Sockets? What is KAD?

A copy of your keepalived configuration and a description of the problem in the context of that would be helpful.

**Comment by pqarmitage** [comment]
Closing due to no response for 27 days. If you have any further issues with this, please post them against this issue and it can be reopened.
