### ISSUE TITLE
keepalived the VIP is not acquired by the MASTER 

### ISSUE THREAD

**Issue by Olumuyiwa** [acassen/keepalived#815]
I set up keepalived on 2 servers   A and B.  Everything looks fine on server B. When I shut down HAProxy on server B, the VIP does not move to server A. When I check the keepalived status on server A,
 I am getting the error below.  Can some please assist?
[status_B_BACKUP.txt](https://github.com/acassen/keepalived/files/1832288/status_B_BACKUP.txt)
[server_A_MASTER.txt](https://github.com/acassen/keepalived/files/1832289/server_A_MASTER.txt)
[server_B_BACKUP.txt](https://github.com/acassen/keepalived/files/1832290/server_B_BACKUP.txt)
[status_A_MASTER.txt](https://github.com/acassen/keepalived/files/1832291/status_A_MASTER.txt)

#  service keepalived status
Redirecting to /bin/systemctl status  keepalived.service
● keepalived.service - LVS and VRRP High Availability Monitor
   Loaded: loaded (/usr/lib/systemd/system/keepalived.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-03-20 17:13:41 WAT; 14h ago
  Process: 4961 ExecStart=/usr/sbin/keepalived $KEEPALIVED_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 4962 (keepalived)
   CGroup: /system.slice/keepalived.service
           ├─ 4962 /usr/sbin/keepalived -D
           ├─ 4964 /usr/sbin/keepalived -D
           └─12513 /usr/sbin/keepalived -D

Mar 21 07:43:15 ungredbox02a Keepalived[4962]:   Please report a bug at https://github.com/acassen/keepalived/issues
Mar 21 07:43:15 ungredbox02a Keepalived[4962]:   and include this log from when keepalived started, what happened
Mar 21 07:43:15 ungredbox02a Keepalived[4962]:   immediately before the crash, and your configuration file.
Mar 21 07:43:15 ungredbox02a Keepalived[4962]: VRRP child process(10585) died: Respawning
Mar 21 07:43:15 ungredbox02a Keepalived[4962]: Starting VRRP child process, pid=12513
Mar 21 07:43:15 ungredbox02a Keepalived_vrrp[12513]: Registering Kernel netlink reflector
Mar 21 07:43:15 ungredbox02a Keepalived_vrrp[12513]: Registering Kernel netlink command channel
Mar 21 07:43:15 ungredbox02a Keepalived_vrrp[12513]: Registering gratuitous ARP shared channel
Mar 21 07:43:15 ungredbox02a Keepalived_vrrp[12513]: Opening file '/etc/keepalived/keepalived.conf'.
Mar 21 07:43:15 ungredbox02a Keepalived_vrrp[12513]: VRRP_Instance(VI_1) removing protocol VIPs.

Thank you

**Comment by pqarmitage** [comment]
Could you please provide the following information:
1. The output of keepalived -v
2. What Linux distro you are using, and the version
3. The logs on the system where keepalived died from the time keepalived started running until the time the vrrp process dies.
4 The output of `ip link show` on both systems

That should help us identify what is causing the problem.

**Comment by pqarmitage** [comment]
Closing due to no repose for 24 days. If you have any further issues with this, please post them against this issue and the issue can be reopened.
