### ISSUE TITLE
should script "</dev/tcp/127.0.0.1/80" work out-of-the-box on linux?

### ISSUE THREAD

**Issue by SjonHortensius** [acassen/keepalived#817]
Should the script mentioned in `doc/samples/keepalived.conf.vrrp.localcheck` work out of the box? On my linux machine, trying it results in:

```
Script </dev/tcp/127.0.0.1/80 cannot be accessed - No such file or directory
Disabling track script chk_http_port since not found/accessible
```

Some research suggests the linux kernel doesn't provide this, and if it works it is probably implemented in userspace, eg. bash.

Should this work or is there another method to quickly check if a process is listening on a port ?

**Comment by pqarmitage** [comment]
Yes, they should have worked.

Commit 5cd5fff resolves the problem.
