### ISSUE TITLE
keepalived vmac problems of use

### ISSUE THREAD

**Issue by saga1015** [acassen/keepalived#823]
Environment:
OS CentOS 6.5
Kernel 4.9.90  enable macvlan
keepalive version 1.4.2
complie options:
./configure --prefix=/opt/websuite/keepalived \
--sysconfdir=/opt/config/keepalived \
--localstatedir=/opt/run/keepalived \
--runstatedir=/opt/run/keepalived \
--disable-lvs-syncd \
--disable-lvs \
--disable-snmp-checker \
--enable-snmp-vrrp \
--enable-snmp-rfc \
--disable-vrrp-auth \
--disable-libipset \
--disable-libiptc \
--enable-json \
--with-kernel-dir=/lib/modules/4.9.90-1.el6.x86_64 \
--with-init=SYSV

keepalived.conf:
global_defs {
   router_id Haproxy
}

vrrp_instance haproxy {
    interface eth0
    virtual_router_id 101
    priority 100
    advert_int 1
    use_vmac
    vmac_xmit_base
    virtual_ipaddress {
        172.16.4.10/23 brd 172.16.5.255
    }
}

when i use /etc/init.d/keepalived start keepalived，I use sysctl -a|grep vrrp, i see:
net.ipv4.conf.vrrp/101.arp_accept = 0
net.ipv4.conf.vrrp/101.arp_announce = 0
net.ipv4.conf.vrrp/101.arp_filter = 0
not 
net.ipv4.conf.vrrp.101.arp_accept = 0
net.ipv4.conf.vrrp.101.arp_announce = 0
net.ipv4.conf.vrrp.101.arp_filter = 0

when i modify keepalived.conf to 
global_defs {
   router_id Haproxy
}

vrrp_instance haproxy {
    interface eth0
    virtual_router_id 101
    priority 100
    advert_int 1
    use_vmac vrrp101
    vmac_xmit_base
    virtual_ipaddress {
        172.16.4.10/23 brd 172.16.5.255
    }
}

restart keepalived ,and keepalived work well 
net.ipv4.conf.vrrp101.arp_filter = 0
net.ipv4.conf.vrrp101.arp_ignore = 1
net.ipv4.conf.vrrp101.arp_notify = 0
all can use sysctl -w to config

**Comment by pqarmitage** [comment]
@saga1015 You have stated:
```
when i use /etc/init.d/keepalived start keepalived，I use sysctl -a|grep vrrp, i see:
net.ipv4.conf.vrrp/101.arp_accept = 0
net.ipv4.conf.vrrp/101.arp_announce = 0
net.ipv4.conf.vrrp/101.arp_filter = 0
not
net.ipv4.conf.vrrp.101.arp_accept = 0
net.ipv4.conf.vrrp.101.arp_announce = 0
net.ipv4.conf.vrrp.101.arp_filter = 0
```
but the two sets of sysctl settings are identical.

You have then shown:
```
restart keepalived ,and keepalived work well
net.ipv4.conf.vrrp101.arp_filter = 0
net.ipv4.conf.vrrp101.arp_ignore = 1
net.ipv4.conf.vrrp101.arp_notify = 0
```
which are a different set of sysctl settings.

You then state `all can use sysctl -w to config`, and I'm not clear what you mean by that.

The comment at the beginning of keepalived/vrrp/vrrp_config_if.c states:
```
/* The following parameters need to be set on the vmac interface and its parent:
 *
 *   vmac interface:
 *     accept_local=1   // We need to be able to hear another instance multicasting it's presence
 *     arp_ignore=1     // We mustn't reply to ARP requests on this interface for IP address on parent interface
 *                      // and we mustn't only reply to addresses on the same subnet.
 *     rp_filter=0      // Allows us to receive on VMAC interface when it has no IP address.
 *
 *   parent interface:
 *     arp_ignore=1     // We mustn't reply to ARP requests on this interface for vrrp IP address
 *     arp_filter=1     // We mustn't reply to ARP requests for our own IP address
 */
```

Can you check with the first config, when you don't specify the VMAC name, whether the above options are being set correctly by keepalived or not. On my systems these options are being correctly set.

**Comment by pqarmitage** [comment]
Closing due to no response for 16 days. If you have any further issues with this please post them against this issue and it can be reopened.
