### ISSUE TITLE
LVS-DR two-way communication

### ISSUE THREAD

**Issue by coretemp** [acassen/keepalived#832]
I have a classic echo udp client and server. 

Is it possible to setup Keepalive, such that the client sends something to a keepalive host, then the keepalive forwards this to the server and the server sends a message back over that same socket, which then ends up at the client again? 

Or is that fundamentally impossible via DR?

**Comment by pqarmitage** [comment]
Keepalived has no capability of forwarding packets itself. It would be possible to use keepalived to set up an IPVS virtual server with a real server and that virtual server/real server could forward and return the udp packet as you describe. However, first your issue #831 would need to be resolved.

**Comment by coretemp** [comment]
I have seen two way communication work by fixing #831.
