### ISSUE TITLE
segfault at 0 ip (null) sp 00007fffaf183d68 error 14 in libgcc_s-4.8.5-20150702.so.1

### ISSUE THREAD

**Issue by lwsbox** [acassen/keepalived#846]
Apr 26 05:56:38 node1 Keepalived[303]:  Please report a bug at https://github.com/acassen/keepalived/issues
Apr 26 05:56:38 node1 Keepalived[303]:  and include this log from when keepalived started, what happened
Apr 26 05:56:38 node1 Keepalived[303]:  immediately before the crash, and your configuration file.
Apr 26 05:56:38 node1 Keepalived[303]: VRRP child process(972) died: Respawning
Apr 26 05:56:38 node1 Keepalived[303]: Starting VRRP child process, pid=974
Apr 26 05:56:38 node1 Keepalived_vrrp[974]: Registering Kernel netlink reflector
Apr 26 05:56:38 node1 Keepalived_vrrp[974]: Registering Kernel netlink command channel
Apr 26 05:56:38 node1 Keepalived_vrrp[974]: Registering gratuitous ARP shared channel
Apr 26 05:56:38 node1 Keepalived_vrrp[974]: Opening file '/etc/keepalived/keepalived.conf'.
Apr 26 05:56:38 node1 kernel: keepalived[32016]: segfault at 0 ip           (null) sp 00007fffaf183d68 error 14 in libgcc_s-4.8.5-20150702.so.1[7ff668e28000+15000]
[root@node1 /]# tail /var/log/messages 
Apr 26 05:56:42 node1 Keepalived[303]: Keepalived_vrrp exited due to segmentation fault (SIGSEGV).
Apr 26 05:56:42 node1 Keepalived[303]:  Please report a bug at https://github.com/acassen/keepalived/issues
Apr 26 05:56:42 node1 Keepalived[303]:  and include this log from when keepalived started, what happened
Apr 26 05:56:42 node1 Keepalived[303]:  immediately before the crash, and your configuration file.
Apr 26 05:56:42 node1 Keepalived[303]: VRRP child process(1051) died: Respawning
Apr 26 05:56:42 node1 Keepalived[303]: Starting VRRP child process, pid=1053
Apr 26 05:56:42 node1 Keepalived_vrrp[1053]: Registering Kernel netlink reflector
Apr 26 05:56:42 node1 Keepalived_vrrp[1053]: Registering Kernel netlink command channel
Apr 26 05:56:42 node1 Keepalived_vrrp[1053]: Registering gratuitous ARP shared channel
Apr 26 05:56:42 node1 Keepalived_vrrp[1053]: Opening file '/etc/keepalived/keepalived.conf'.

>> I run keepalived in a docker container built by centos 7.3 docker ?
>> How to fix this issue?   thanks

**Comment by pqarmitage** [comment]
There have been problems in the past when keepalived is run in a container when the necessary kernel modules have not been loaded in the host system.

Can you please provide what version of keepalived you are using (output of `keepalived -v`), and a copy of your configuration. The output of `lsmod` would also be helpful.

**Comment by lwsbox** [comment]
the keepalived version is 1.3.5

now we use the 1.4.3 keepalived installed in centos7.3

we found the error report:
Apr 27 07:56:25 rjbdnode3 Keepalived[2141]:  and include this log from when keepalived started, what happened
Apr 27 07:56:25 rjbdnode3 Keepalived[2141]:  immediately before the crash, and your configuration file.
Apr 27 07:56:25 rjbdnode3 Keepalived[2141]: VRRP child process(5119) died: Respawning
Apr 27 07:56:25 rjbdnode3 Keepalived[2141]: Starting VRRP child process, pid=5121
Apr 27 07:56:25 rjbdnode3 Keepalived_vrrp[5121]: Registering Kernel netlink reflector
Apr 27 07:56:25 rjbdnode3 Keepalived_vrrp[5121]: Registering Kernel netlink command channel
Apr 27 07:56:25 rjbdnode3 Keepalived_vrrp[5121]: Registering gratuitous ARP shared channel
Apr 27 07:56:25 rjbdnode3 Keepalived_vrrp[5121]: Opening file '/etc/keepalived/keepalived.conf'.
Apr 27 07:56:25 rjbdnode3 Keepalived_vrrp[5121]: VRRP_Instance(VI_1) removing protocol VIPs.
Apr 27 07:56:25 rjbdnode3 kernel: keepalived[10280]: segfault at 0 ip           (null) sp 00007ffe258ec728 error 14 in keepalived[558ebc0a0000+5f000]
[root@rjbdnode3 /]# tail /var/log/messages 
Apr 27 07:56:26 rjbdnode3 Keepalived[2141]:  Please report a bug at https://github.com/acassen/keepalived/issues
Apr 27 07:56:26 node3 Keepalived[2141]:  and include this log from when keepalived started, what happened
Apr 27 07:56:26 node3 Keepalived[2141]:  immediately before the crash, and your configuration file.
Apr 27 07:56:26 node3 Keepalived[2141]: VRRP child process(5126) died: Respawning
Apr 27 07:56:26 node3 Keepalived[2141]: Starting VRRP child process, pid=5128
Apr 27 07:56:26 node3 Keepalived_vrrp[5128]: Registering Kernel netlink reflector
Apr 27 07:56:26 node3 Keepalived_vrrp[5128]: Registering Kernel netlink command channel
Apr 27 07:56:26 node3 Keepalived_vrrp[5128]: Registering gratuitous ARP shared channel
Apr 27 07:56:26 node3 Keepalived_vrrp[5128]: Opening file '/etc/keepalived/keepalived.conf'.
Apr 27 07:56:26 node3 Keepalived_vrrp[5128]: VRRP_Instance(VI_1) removing protocol VIPs.

the keepalived.conf:
global_defs {
   router_id LVS_DEVEL  
}

vrrp_instance VI_1 {
    state BACKUP  
    interface ens1f0  
    virtual_router_id 51  
    priority 90  
    advert_int 1 
    unicast_src_ip 172.18.135.4   
    unicast_peer {
        172.18.135.3   
    }
    authentication {
        auth_type PASS
        auth_pass test
    }
    virtual_ipaddress {
        172.18.135.5  
    }
}

**Comment by lwsbox** [comment]
after i install keepalived on ubuntu , thise issue is fixed
