### ISSUE TITLE
keepalived smtp_server port number being ignored.

### ISSUE THREAD

**Issue by ericavijay** [acassen/keepalived#851]
I have a keepalived config where I want the smtp connection to use a different host and port due to the server being mailserver and there is an open relay internal server which will be able to send page emails out. But the configuration does not seem to work as the port number is ignored. 
global_defs {
notification_email {
  dev@sarvepalli.net 
}
notification_email_from dev@sarvepalli.net 
smtp_server 172.20.0.8 2025
}

The logs still show connecting to port 25. Is this port number only in newer versions? My version is Keepalived v1.2.19 (03/13,2017) 

Remote SMTP server [172.20.0.8]:25 connected.

Thanks
Vijay

**Comment by ericavijay** [comment]
Thanks! I tested it with the newest install it works fine.  Except when I run only --dump-conf it seems to want to start the daemon even with just "--check" options.  A bit confusing as I was only expecting to see the config dump and exit.

Vijay

**Comment by pqarmitage** [comment]
Glad to hear it is working for you now.

The `--check` option means only run the healthchecker child process (and not run the vrrp child process). The `--dump-conf` option is not designed to cause keepalived to exit after dumping the configuration.
