### ISSUE TITLE
Please support point-to-point virtual addresses

### ISSUE THREAD

**Issue by akorn** [acassen/keepalived#852]
I'd like keepalived to execute, on becoming master, the equivalent of

```
ip addr add 1.2.3.4 peer 2.3.4.5 dev foo
```

Currently, I have to use something like this:

```
virtual_ipaddress {
    1.2.3.4/32 dev foo
}

notify_master "/sbin/ip ro add 2.3.4.5/32 srv 1.2.3.4 dev foo"
```

This is obviously a workaround. Since the kernel supports point-to-point links, perhaps `keepalived` could too?

**Comment by pqarmitage** [comment]
This is still a workaround, but a neater one than using notify_master. You could add a `virtual_routes` block in the vrrp_instance block:
```
    virtual_routes {
        2.3.4.5 src 1.2.3.4 dev foo
    }
```

I'll look at adding the peer option to virtual_ipaddress configuration.

**Comment by pqarmitage** [comment]
Commit cee5e41 adds the peer option for virtual and static ip addresses to the beta branch of keepalived.
