### ISSUE TITLE
check tcp by asynchronous connect repeatly ?

### ISSUE THREAD

**Issue by lingji** [acassen/keepalived#856]
I glanced over check_tcp.c . There is tcp avail check by asynchronous connect repeatly  , isn't it ? Meanwhile, when I detected the application net protocol was avialable,  it was no more timely than that by user-defined heartbeat(the socket options such as SO_SNDTIMEO, SO_RECVTIMEO is setted properly) . @acassen

**Comment by pqarmitage** [comment]
The TCP_CHECK option can be configured against a real_server to periodically check that a tcp connection can be established to the specified server. It is configured as follows:
```
virtual_server 192.168.179.111 80 {
    ...
    real_server 192.168.179.5 80 {
        ...
        TCP_CHECK {
            connect_timeout 5  # allow 5 seconds before timing out a connection attempt
            connect_port 80     # connect to port 80 
            delay_loop 3           # delay 3 seconds between attempts to reconnect
        }
        ...
    }
    ...
}
```

Further details of how to configure health checkers are in the keepalived.conf(5) man page, or the doc/keepalived.conf.SYNOPSIS file in the source tree.

Does that answer your question?

**Comment by lingji** [comment]
That means every 3 seconds tcp_check will connect the real server.

**Comment by pqarmitage** [comment]
Yes, that's correct.
