### ISSUE TITLE
Compile keepalived fail on mac os

### ISSUE THREAD

**Issue by realdog** [acassen/keepalived#86]
When i compile keepalived on mac os,there is a error:
configure: error: crypt() function is required

**Comment by OptimusGREEN** [comment]
mac os support would be nice

**Comment by pqarmitage** [comment]
I don't think macos support is possible, even if it were desired. keepalived uses quite a few Linux specific features that so far as I am aware macos does not support - one such feature is IPVS which would mean that half of what keepalived does macos simply has no support for.

**Comment by OptimusGREEN** [comment]
Ahhh, thanks for the info, appreciate you taking the time.
