### ISSUE TITLE
keepalived (beta) doesn't receive signals on CentOS 6.9

### ISSUE THREAD

**Issue by pqarmitage** [acassen/keepalived#864]
Issue #862 identified that keepalived (beta branch) doesn't appear to receive signals sent to the parent process.

This has been tested without using signalfd() too, and that doesn't seem to make a difference.

This problem has also been observed on my Centos 6.9 VM.

**Comment by rwgroenenberg** [comment]
Problem appears to be with the value of SIG_MAX in lib/signals.c.
Adding some traces show that the SIGCHLD from the notify scripts on changing state are ignored as the received signals is larger than SIG_MAX:

`May 15 18:45:24 vm1 Keepalived_vrrp[16571]:   17 > 12`

> 312:		if (sig >= 1 && sig <= SIG_MAX && signal_handler_func[sig-1])

Overriding the 'SIG_MAX magic' at the top of signals.c by redefining it to 64 makes the signals work and Keepalived stop on Ctrl-C  (don't fork) or a SIGTERM on the main process.

The SIG_MAX magic is apparently broken, on CentOS 6.9 at least.

**Comment by rwgroenenberg** [comment]
```
 #if SIGCHLD > SIGUSR2
   ...
     #define SIG_MAX **SIGUSR2**
   #endif 
```
I think this should be:
` #define SIG_MAX SIGCHLD`
(line 69 of lib/signals.c)

**Comment by pqarmitage** [comment]
@rwgroenenberg Many thanks for your investigation into this. You are quite right.

I'm sorry, I didn't see that you had pushed a commit to resolve the problem, and I had already merged 1cf3ee9. I think we don't want the possibility of logs to be flooded if there is a signal being generated that is greater than SIG_MAX; perhaps it should only log the BUG message is larger that the largest signal number received so far?

**Comment by rwgroenenberg** [comment]
AFAIK the signal_set() is used to register a signal + handler function. So anytime that is called with a signal > SIG_MAX would be a bug. Right?

**Comment by pqarmitage** [comment]
Yes, you're right re signal_set, and that is certainly one place to detect the bug. However, if a signal were delivered that isn't one we expect to handle but it hasn't been masked properly, that would also be a bug and the only place that could be detected is where you have already added the check.

**Comment by pqarmitage** [comment]
@rwgroenenberg I was thinking of a slight modification to your patch along the lines
```
+#ifdef _SIGNAL_DEBUG_
+       static int max_signo = SIG_MAX;
+       static int min_signo = 1;
 
-       if ((signo < 1) || (signo > SIG_MAX)) {
+       if ((signo < min_signo) || (signo > max_signo)) {
                log_message(LOG_ERR, "BUG - signal %d out of range (1..%d)", signo, SIG_MAX);
+               if (signo > max_signo)
+                       max_signo = signo;
+               else
+                       min_signo = signo;
                return;
        }
+#endif
```

What do you think?

**Comment by rwgroenenberg** [comment]
Yes, makes sense!

**Comment by pqarmitage** [comment]
@rwgroenenberg Many thanks for your help with this. All the above changes are now merged.
