### ISSUE TITLE
How to use keepalived to achieve high availability of multiple services?

### ISSUE THREAD

**Issue by brandonbai** [acassen/keepalived#874]
#### There are two servers and the following software is installed

* Mysql
* Nginx
* Keepalived

**Q: How to achieve high availability both mysql and nginx?**

**Comment by pqarmitage** [comment]
@brandonbai You need to describe in more detail what it is you want to achieve and then someone may be able to suggest a configuration.

This shouldn't be reported as an issue, which is for problems/bugs with the code. Please send your request for help to the keepalived-devel mailing list - see (http://www.keepalived.org/listes.html) for more details.
