### ISSUE TITLE
Keepalived sends DBUS signal with old state when it transition from BACKUP to FAULT state

### ISSUE THREAD

**Issue by balmnm** [acassen/keepalived#877]
Hi All,

Im using keepalived version 1.3.9 to achieve VRRP functionality. 
Our client code registers with keepalived DBUS to get "VrrpStatusChange" notification.
Im seeing when the VRRP instance changes from BACKUP to FAULT state (trigger is make the interface oper down) the DBUS notify signal is sent with old state (which is BACKUP) instead of new state (which is FAULT).

Logs:
root@router:~# busctl monitor org.keepalived.Vrrp1
Monitoring bus message stream.
\u2023 Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=2
  Sender=org.freedesktop.DBus  Destination=:1.9  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameAcquired
  MESSAGE "s" {
          STRING ":1.9";
  };

\u2023 Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=4
  Sender=org.freedesktop.DBus  Destination=:1.9  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameLost
  MESSAGE "s" {
          STRING ":1.9";
  };

\u2023 Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=623
  Sender=:1.2  Path=/org/keepalived/Vrrp1/default/Instance/br3516/32/IPv4  Interface=org.keepalived.Vrrp1.Instance  Member=VrrpStatusChange
  UniqueName=:1.2
  MESSAGE "u" {
          UINT32 1; ---------------> **Sending with old state value BACKUP instead of FAULT**
  };

May 22 06:45:41 router Keepalived_vrrp_default[1144]: Kernel is reporting: interface vrrp1.32 DOWN
May 22 06:45:41 router Keepalived_vrrp_default[1144]: VRRP_Instance(br3516_v4_32) Now in FAULT state

\u2023 Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=627
  Sender=:1.2  Path=/org/keepalived/Vrrp1/default/Instance/br3516/32/IPv4  Interface=org.keepalived.Vrrp1.Instance  Member=VrrpStatusChange
  UniqueName=:1.2
  MESSAGE "u" {
          UINT32 1;
  };

May 22 06:45:53 router Keepalived_vrrp_default[1144]: VRRP_Instance(br3516_v4_32) Entering BACKUP STATE

Further analysing the code, I could see the API "dbus_send_state_signal" retrieves state value from the vrrp database (vrrp->state) and it is not updated in this problem scenario before calling API "dbus_send_state_signal".  Kindly correct me if my understanding is wrong.

I think following diff will solve the issue. Kindly let me know your comments.

```
--- vrrp_scheduler.c_bkup       2018-05-22 12:21:57.157956000 +0530
+++ vrrp_scheduler.c    2018-05-22 12:22:08.673157000 +0530
@@ -659,8 +659,8 @@
                log_message(LOG_INFO, "VRRP_Instance(%s) Now in FAULT state",
                       vrrp->iname);
                if (vrrp->state != VRRP_STATE_FAULT) {
-                       notify_instance_exec(vrrp, VRRP_STATE_FAULT);
                        vrrp->state = VRRP_STATE_FAULT;
+                       notify_instance_exec(vrrp, VRRP_STATE_FAULT);
 #ifdef _WITH_SNMP_KEEPALIVED_
                        vrrp_snmp_instance_trap(vrrp);
 #endif
```

**Comment by Sivabs77** [comment]
Hi Bala,

Looks like a bug. Wondering how this was working earlier.

Re
Sivabalan

**Comment by pqarmitage** [comment]
Commit f274c04 should fix this problem.

@balmnm Could you please confirm if this does resolve your problem

@Sivabs77 It looks to me as though this never worked correctly.

**Comment by balmnm** [comment]
@pqarmitage  I have verified your fix and it is working fine. Thanks !
