### ISSUE TITLE
VMWare issue IP's not being removed

### ISSUE THREAD

**Issue by titansmc** [acassen/keepalived#883]
Hi,
I am running into a lot of troubles when having a HAProxy and keepalived running.  This setup is hosted over VMWare(vSphere) infrastructure.

So, I start haproxy03, it gets the 2 IP properly setup, when haproxy04 comes online it has none of the IP (which is what we want), I reboot haproxy03 and the IP's move to haproxy04 (which is fine), but the problem comes here, when haproxy03 boots up and the IP's move back from haproxy04 to haproxy03 but they remain active in haproxy04 (I don't see anything on the haproxy04 logs).

From haproxy03 I can see:

```
May 24 11:45:38 haproxy03 Keepalived_vrrp[1177]: Sending gratuitous ARP on ens192 for 10.11.6.
41
May 24 11:45:38 haproxy03 Keepalived_vrrp[1177]: VRRP_Instance(VI_1) Sending/queueing gratuito
us ARPs on ens192 for 10.11.6.41
May 24 11:45:38 haproxy03 Keepalived_vrrp[1177]: Sending gratuitous ARP on ens192 for 10.11.6.
41
May 24 11:45:38 haproxy03 Keepalived_vrrp[1177]: Sending gratuitous ARP on ens192 for 10.11.6.
41
May 24 11:45:38 haproxy03 Keepalived_vrrp[1177]: Sending gratuitous ARP on ens192 for 10.11.6.
41
May 24 11:45:38 haproxy03 Keepalived_vrrp[1177]: Sending gratuitous ARP on ens192 for 10.11.6.41
May 24 11:45:38 haproxy03 Keepalived_vrrp[1177]: Sending gratuitous ARP on ens192 for 10.11.6.44
May 24 11:45:38 haproxy03 Keepalived_vrrp[1177]: VRRP_Instance(VI_2) Sending/queueing gratuitous ARPs on ens192 for 10.11.6.44
May 24 11:45:38 haproxy03 Keepalived_vrrp[1177]: Sending gratuitous ARP on ens192 for 10.11.6.44
May 24 11:45:38 haproxy03 Keepalived_vrrp[1177]: Sending gratuitous ARP on ens192 for 10.11.6.44
May 24 11:45:38 haproxy03 Keepalived_vrrp[1177]: Sending gratuitous ARP on ens192 for 10.11.6.44
May 24 11:45:38 haproxy03 Keepalived_vrrp[1177]: Sending gratuitous ARP on ens192 for 10.11.6.44
```

I am using:

    [root@haproxy04 ~]# keepalived --version
    Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

And the  keepalived.conf looks like:

```

[root@haproxy03 ~]# cat /etc/keepalived/keepalived.conf 
vrrp_script chk_haproxy {
  script    "/usr/bin/killall -0 haproxy"
  interval  2
  weight    2
}

global_defs {
  vrrp_garp_master_delay 10
  vrrp_garp_master_refresh 60
  vrrp_garp_lower_prio_repeat 1
}

vrrp_instance VI_1 {
  interface                 ens192
  state                     MASTER
  virtual_router_id         71
  priority                  101
  advert_int                1
  garp_master_delay         5




  # notify scripts and alerts are optional
  #
  # filenames of scripts to run on transitions
  # can be unquoted (if just filename)
  # or quoted (if has parameters)




  track_script {
    chk_haproxy
  }


  virtual_ipaddress {
    10.11.6.41 dev ens192
  }





}
vrrp_instance VI_2 {
  interface                 ens192
  state                     MASTER
  virtual_router_id         72
  priority                  101
  advert_int                1
  garp_master_delay         5




  # notify scripts and alerts are optional
  #
  # filenames of scripts to run on transitions
  # can be unquoted (if just filename)
  # or quoted (if has parameters)




  track_script {
    chk_haproxy
  }


  virtual_ipaddress {
    10.11.6.44 dev ens192
  }





}

```

For the other instance it is:

```
[root@haproxy04 ~]# cat /etc/keepalived/keepalived.conf 
vrrp_script chk_haproxy {
  script    "/usr/bin/killall -0 haproxy"
  interval  2
  weight    2
}

global_defs {
  vrrp_garp_master_delay 10
  vrrp_garp_master_refresh 60
  vrrp_garp_lower_prio_repeat 1
}

vrrp_instance VI_1 {
  interface                 ens192
  state                     BACKUP
  virtual_router_id         71
  priority                  40
  advert_int                1
  garp_master_delay         5




  # notify scripts and alerts are optional
  #
  # filenames of scripts to run on transitions
  # can be unquoted (if just filename)
  # or quoted (if has parameters)




  track_script {
    chk_haproxy
  }


  virtual_ipaddress {
    10.11.6.41 dev ens192
  }





}
vrrp_instance VI_2 {
  interface                 ens192
  state                     BACKUP
  virtual_router_id         72
  priority                  40
  advert_int                1
  garp_master_delay         5




  # notify scripts and alerts are optional
  #
  # filenames of scripts to run on transitions
  # can be unquoted (if just filename)
  # or quoted (if has parameters)




  track_script {
    chk_haproxy
  }


  virtual_ipaddress {
    10.11.6.44 dev ens192
  }





}

```

I am using a Puppet module to configure Keepalived and it somehow adds blank lines...I've tried to remove them but it didn't help.

Also using extreme networks for the networking.

And also running another pair of loadbalancers with different priority and virtual_router_id.

**Comment by pqarmitage** [comment]
This looks as though either `nopreempt` is set on the vrrp instances, or for some reason after rebooting haproxy03, haproxy04 isn't receiving data from haproxy03 (and also since haproxy03 isn't reporting receiving lower priority adverts from haproxy04, presumably haproxy03 isn't receiving data from haproxy04).

Since `nopreempt` is not the default option, that is unlikely (although would could try executing `kill -USR1 $(cat /var/run/keepalived.pid)` acd checking the /tmp/keepalived.data file).

What would be useful would be to run `tcpdump -n -nn -v -i ens192 proto 112` on both haproxy03 and haproxy04 after haproxy03 is rebooted, starting the tcpdumps before keepalived on haproxy03 is started. You should then be able to see whether VRRP traffic is being sent/received on haproxy03 and haproxy04.

**Comment by titansmc** [comment]
Hi,
Right I don't have specifically set nopreempt option, here is the keepalived.data

[root@haproxy03 ~]# cat /tmp/keepalived.data 
------< VRRP Topology >------
 VRRP Instance = VI_1
 VRRP Version = 2
   State = MASTER
   Last transition = 1527155133 (Thu May 24 11:45:33 2018)
   Listening device = ens192
   Using src_ip = 10.11.6.38
   Gratuitous ARP delay = 5
   Gratuitous ARP repeat = 5
   Gratuitous ARP refresh = 0
   Gratuitous ARP refresh repeat = 1
   Gratuitous ARP lower priority delay = 5
   Gratuitous ARP lower priority repeat = 5
   Send advert after receive lower priority advert = true
   Send advert after receive higher priority advert = false
   Virtual Router ID = 71
   Priority = 101
   Advert interval = 1 sec
   Accept = enabled
   Preempt = enabled
   Promote_secondaries = disabled
   Authentication type = none
   Tracked scripts = 1
 VRRP Script = chk_haproxy
   Command = /usr/bin/killall -0 haproxy
   Interval = 2 sec
   Weight = 2
   Rise = 1
   Full = 1
   Insecure = no
   uid:gid = 0:0
   Status = GOOD
   Interface weight 2
   Virtual IP = 1
     10.11.6.41/32 dev ens192 scope global
 VRRP Instance = VI_2
 VRRP Version = 2
   State = MASTER
   Last transition = 1527155133 (Thu May 24 11:45:33 2018)
   Listening device = ens192
   Using src_ip = 10.11.6.38
   Gratuitous ARP delay = 5
   Gratuitous ARP repeat = 5
   Gratuitous ARP refresh = 0
   Gratuitous ARP refresh repeat = 1
   Gratuitous ARP lower priority delay = 5
   Gratuitous ARP lower priority repeat = 5
   Send advert after receive lower priority advert = true
   Send advert after receive higher priority advert = false
   Virtual Router ID = 72
   Priority = 101
   Advert interval = 1 sec
   Accept = enabled
   Preempt = enabled
   Promote_secondaries = disabled
   Authentication type = none
   Tracked scripts = 1
 VRRP Script = chk_haproxy
   Command = /usr/bin/killall -0 haproxy
   Interval = 2 sec
   Weight = 2
   Rise = 1
   Full = 1
   Insecure = no
   uid:gid = 0:0
   Status = GOOD
   Interface weight 2
   Virtual IP = 1
     10.11.6.44/32 dev ens192 scope global

**Comment by pqarmitage** [comment]
From the configurations and what you have said above, we are only interested if VRIDs 71 and 72, so the relevant traffic on haproxy03 is:
```
14:18:40.390052 IP (tos 0xc0, ttl 255, id 1, offset 0, flags [none], proto VRRP (112), length 40)
    10.11.6.38 > 224.0.0.18: vrrp 10.11.6.38 > 224.0.0.18: VRRPv2, Advertisement, vrid 71, prio 101, authtype none, intvl 1s, length 20, addrs: 10.11.6.41
14:18:40.391241 IP (tos 0xc0, ttl 255, id 1, offset 0, flags [none], proto VRRP (112), length 40)
    10.11.6.38 > 224.0.0.18: vrrp 10.11.6.38 > 224.0.0.18: VRRPv2, Advertisement, vrid 72, prio 103, authtype none, intvl 1s, length 20, addrs: 10.11.6.44
```
and the relevant traffic on haproxy04 is:
```
14:18:37.754373 IP (tos 0xc0, ttl 255, id 27364, offset 0, flags [none], proto VRRP (112), length 40)
    10.11.6.40 > 224.0.0.18: vrrp 10.11.6.40 > 224.0.0.18: VRRPv2, Advertisement, vrid 71, prio 42, authtype none, intvl 1s, length 20, addrs: 10.11.6.41
14:18:37.755061 IP (tos 0xc0, ttl 255, id 27364, offset 0, flags [none], proto VRRP (112), length 40)
    10.11.6.40 > 224.0.0.18: vrrp 10.11.6.40 > 224.0.0.18: VRRPv2, Advertisement, vrid 72, prio 42, authtype none, intvl 1s, length 20, addrs: 10.11.6.44
14:18:38.754565 IP (tos 0xc0, ttl 255, id 27365, offset 0, flags [none], proto VRRP (112), length 40)
    10.11.6.40 > 224.0.0.18: vrrp 10.11.6.40 > 224.0.0.18: VRRPv2, Advertisement, vrid 71, prio 42, authtype none, intvl 1s, length 20, addrs: 10.11.6.41
14:18:38.755163 IP (tos 0xc0, ttl 255, id 27365, offset 0, flags [none], proto VRRP (112), length 40)
    10.11.6.40 > 224.0.0.18: vrrp 10.11.6.40 > 224.0.0.18: VRRPv2, Advertisement, vrid 72, prio 42, authtype none, intvl 1s, length 20, addrs: 10.11.6.44
14:18:39.755459 IP (tos 0xc0, ttl 255, id 27366, offset 0, flags [none], proto VRRP (112), length 40)
    10.11.6.40 > 224.0.0.18: vrrp 10.11.6.40 > 224.0.0.18: VRRPv2, Advertisement, vrid 71, prio 42, authtype none, intvl 1s, length 20, addrs: 10.11.6.41
14:18:39.758663 IP (tos 0xc0, ttl 255, id 27366, offset 0, flags [none], proto VRRP (112), length 40)
    10.11.6.40 > 224.0.0.18: vrrp 10.11.6.40 > 224.0.0.18: VRRPv2, Advertisement, vrid 72, prio 42, authtype none, intvl 1s, length 20, addrs: 10.11.6.44
```

From the keepalived.data file, haproxy03 is using source address `10.11.6.38`, and so I presume that haproxy04 is using source address `10.11.6.40` (looking at a keepalived.data on haproxy04 would confirm this).

From the above, it is clear that the only VRRP traffic using VRIDs 71/72 that haproxy03 is seeing on ens192 is the VRRP packets that it is sending, and likewise haproxy04 is only seeing the packets that it is sending; i.e. neither of them is seeing the VRRP packets sent by the other. This is the reason why haproxy04 is remaining in master mode after haproxy03 is rebooted.

It looks to me as though the VRRP adverts from haproxy03 and haproxy04 for some reason are not leaving those machines. It would probably be worth looking on one or more of your other machines (e.g. 10.11.6.26 or 10.11.4.2) to see if they are receiving any VRRP adverts from VRIDs 71 and 72.

At the moment this is not looking like a keepalived problem, but more some other issue to do with the system setup. Could it be that somehow the IGMP Report (join) messages are not being processed properly?

**Comment by titansmc** [comment]
Nice explanation!
haproxy01 and haproxy02 are seeing VRRP sent by haproxy[03-04] .... and all the machines are within the same VLAN and the same VMWare cluster.... I am not sure what could be happening. 

I have 4 instances in my network haproxy[01-04] , and all of them are only able to see VRRP advert from haproxy01 and haproxy03.....I am not sure if this is the expected behaviour.... 

But I still don't see any advert in haproxy03 from haproxy04. And those are machines that I amdeploying with puppet and foreman, so I mean that I can just deploy new centos 7.5 and apply puppet manifest for haproxy, keepalived,  sysctl and limits and nothing will change.

A

**Comment by titansmc** [comment]
What I see now is that everything is fine if I reboot master node (haproxy03) or stop keepalived, it means everything gets moved to haproxy04. But if I stop haproxy, I see :
 
```
[root@haproxy03 ~]# 
May 25 16:41:16 haproxy03 Keepalived_vrrp[1142]: /usr/bin/killall -0 haproxy exited with status 1
May 25 16:41:18 haproxy03 Keepalived_vrrp[1142]: /usr/bin/killall -0 haproxy exited with status 1
May 25 16:41:20 haproxy03 Keepalived_vrrp[1142]: /usr/bin/killall -0 haproxy exited with status 1
^C
```

But still seeing VRRP advertisements comming from haproxy03 ot haproxy04. But stoping haproxy should cause the VRRP to fail over the backup.

```
[root@haproxy04 ~]# tcpdump -n -nn -v -i ens192 proto 112 | grep 10.11.6.38
tcpdump: listening on ens192, link-type EN10MB (Ethernet), capture size 262144 bytes
    10.11.6.38 > 224.0.0.18: vrrp 10.11.6.38 > 224.0.0.18: VRRPv2, Advertisement, vrid 71, prio 101, authtype none, intvl 1s, length 20, addrs: 10.11.6.41
    10.11.6.38 > 224.0.0.18: vrrp 10.11.6.38 > 224.0.0.18: VRRPv2, Advertisement, vrid 72, prio 101, authtype none, intvl 1s, length 20, addrs: 10.11.6.44
    10.11.6.38 > 224.0.0.18: vrrp 10.11.6.38 > 224.0.0.18: VRRPv2, Advertisement, vrid 71, prio 101, authtype none, intvl 1s, length 20, addrs: 10.11.6.41
    10.11.6.38 > 224.0.0.18: vrrp 10.11.6.38 > 224.0.0.18: VRRPv2, Advertisement, vrid 72, prio 101, authtype none, intvl 1s, length 20, addrs: 10.11.6.44
    10.11.6.38 > 224.0.0.18: vrrp 10.11.6.38 > 224.0.0.18: VRRPv2, Advertisement, vrid 71, prio 101, authtype none, intvl 1s, length 20, ad
```

**Comment by titansmc** [comment]
I've just tested Haproxy[01-02] pair and their failover the backup when stopping haproxy daemon... So the only difference I see is that those are running CentOS 7.4 and the haproxy[03-04] pair are running CentOS 7.5....

**Comment by pqarmitage** [comment]
@titansmc I think you are going to need to try and work out why the VRRP adverts aren't appearing on the other side of the haproxy[03-04] pair. For a start, are haproxy[01-02] seeing the adverts from haproxy[03-04]? That should at least tell you whether it is a send or a receive problem. It might then we worth looking at the iptables configurations to see if protocol 112 is allowed.

**Comment by titansmc** [comment]
We have 2 VMWare clusters (in diferent DC) interconnected, so if I put one node in DC1 and the other in DC2, the one in DC2 can only see its VRRP adverts(doesn't matter I use haproxy[01-02] or haproxy[03-04] )
Also if I leave both nodes in DC2 I have problems, but not when having both nodes on DC1.

There is no iptables setup.

**Comment by titansmc** [comment]
Might this have something to do?

https://github.com/acassen/keepalived/blob/master/doc/NOTE_vrrp_vmac.txt

**Comment by titansmc** [comment]
Sorry guys, I think I found some core switch blocking VRRP traffic, so depending which path the traffic took, it was blocked or not. So I decided to use unicast.

**Comment by pqarmitage** [comment]
@titansmc Glad to hear you've resolved your problem.
