### ISSUE TITLE
master keep sending vrrp advertisement when interface down

### ISSUE THREAD

**Issue by Cythwell** [acassen/keepalived#890]
Hello, I am new for keepalived. And met an issue.
The issue is that when I ifdown the interface. The interface release all the IP address include VIP and real IP.
But I found the backup cannot take over the master. Then I use "tcpdump" to debug and found that the origin master still keeps sending vrrp advertisement to the backup. This could explain why backup cannot take over the master. Also when I ifup the interface on master.  I saw the real IP had come back to the interface, but VIP no more come back. So the VIP had lost until I restart keepalived service on master.
The configurations are simple and same as the master and backup server 
vrrp_instance VI_1 {
    state BACKUP
    interface eno1
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        172.16.1.201
    }
}

So I had some question and hope someone can help me.
1. master will send vrrp advertisement when interface down, does it normal?
2. It seems keepalived will not monitor the interface status. does it right?
3. Does it possible to make it work with "ifdown/ifup" or "service network stop" command?

Finally, I am not good in English and hope you can get what I said.  And thanks for the helping

**Comment by pqarmitage** [comment]
This issue has been resolved in the latest release of keepalived, v2.0.0, which was released two days ago.

**Comment by Cythwell** [comment]
Oh thanks very much @pqarmitage
