### ISSUE TITLE
segmentation fault with keepalived

### ISSUE THREAD

**Issue by raffaelespazzoli** [acassen/keepalived#898]
I am seeing a segmentation fault with keepalived. I am running keepalived as a container with this image: registry.access.redhat.com/openshift3/ose-keepalived-ipfailover:v3.9.14.
as instructed by the error message here is the log:
```
Starting Healthcheck child process, pid=113407
Initializing ipvs
Opening file '/etc/keepalived.d/routers-keepalived.conf'.
Unknown keyword 'lvs_id'
Keepalived_healthcheckers exited due to segmentation fault (SIGSEGV).
  Please report a bug at https://github.com/acassen/keepalived/issues
  and include this log from when keepalived started, what happened
  immediately before the crash, and your configuration file.
Healthcheck child process(113407) died: Respawning
```
the configuration is as follows:
```
[root@infranode-1 ~]# cat /etc/kubelet.pod.d/routers-keepalived.conf 
global_defs {
   lvs_id routers
}

vrrp_instance vi_master {
    interface eth0
    
    state  BACKUP     
    virtual_router_id 52
    
    priority  100     
    advert_int 1
    
    unicast_peer {
            192.168.99.11
            192.168.99.10
        
    }  
    
    virtual_ipaddress {
      192.168.99.101
    }
}

virtual_server 192.168.99.101 80 {
    delay_loop 20
    lb_algo rr
    lb_kind NAT
    persistence_timeout 360
    protocol TCP

 
       
 
       
 
       
 

    real_server 192.168.99.9 80 {
        weight 1
        TCP_CHECK {
            connect_timeout 3
        }        
#        HTTP_GET
#        {
#            url {
#                path /healthz
#                digest d95679752134a2d9eb61dbd7b91c4bcc
#            }
#            connect_port 1936
#            connect_timeout 3
#            retry 3
#            delay_before_retry 2
#        }
    }


 
       
 

    real_server 192.168.99.11 80 {
        weight 1
        TCP_CHECK {
            connect_timeout 3
        }        
#        HTTP_GET
#        {
#            url {
#                path /healthz
#                digest d95679752134a2d9eb61dbd7b91c4bcc
#            }
#            connect_port 1936
#            connect_timeout 3
#            retry 3
#            delay_before_retry 2
#        }
    }


 
       
 

    real_server 192.168.99.10 80 {
        weight 1
        TCP_CHECK {
            connect_timeout 3
        }        
#        HTTP_GET
#        {
#            url {
#                path /healthz
#                digest d95679752134a2d9eb61dbd7b91c4bcc
#            }
#            connect_port 1936
#            connect_timeout 3
#            retry 3
#            delay_before_retry 2
#        }
    }


 
       
 
       
    
  
}

virtual_server 192.168.99.101 443 {
    delay_loop 20
    lb_algo rr
    lb_kind NAT
    persistence_timeout 360
    protocol TCP

 
       
 
       
 
       
 

    real_server 192.168.99.9 443 {
        weight 1
        TCP_CHECK {
            connect_timeout 3
        }        
#        HTTP_GET
#        {
#            url {
#                path /healthz
#                digest d95679752134a2d9eb61dbd7b91c4bcc
#            }
#            connect_port 1936
#            connect_timeout 3
#            retry 3
#            delay_before_retry 2
#        }
    }

 
       
 

    real_server 192.168.99.11 443 {
        weight 1
        TCP_CHECK {
            connect_timeout 3
        }        
#        HTTP_GET
#        {
#            url {
#                path /healthz
#                digest d95679752134a2d9eb61dbd7b91c4bcc
#            }
#            connect_port 1936
#            connect_timeout 3
#            retry 3
#            delay_before_retry 2
#        }
    }

 
       
 

    real_server 192.168.99.10 443 {
        weight 1
        TCP_CHECK {
            connect_timeout 3
        }        
#        HTTP_GET
#        {
#            url {
#                path /healthz
#                digest d95679752134a2d9eb61dbd7b91c4bcc
#            }
#            connect_port 1936
#            connect_timeout 3
#            retry 3
#            delay_before_retry 2
#        }
    }

 
       
 
       
    
  
}
```
it is autogenerated, hence all those white spaces and comments.

**Comment by pqarmitage** [comment]
Could you please provide the following further information:
1. Output of `keepalived -v`
2. Full logs from the start of keepalived
3. Description of the environment you are running keepalived in, e.g. distro and version, whether running in a container.

**Comment by raffaelespazzoli** [comment]
it looks like the issue was due to the comments in the configuration file. once I removed them it started working. What is the right way to create comments?

**Comment by pqarmitage** [comment]
The version of keepalived in the container is v1.3.5, Redhat build version 1. v1.3.6 had at least one commit to resolve segfaults when running in a container, commit 5ca36cb5. Redhat backported this into their build 6 and image registry.access.redhat.com/openshift3/ose-keepalived-ipfailover:v3.9.27-1 has this updated version of keepalived. If you upgrade the image, the fault is likely to be resolved, although there have been other problems when running keepalived in a container.

The problem is caused when a kernel module that is required by keepalived isn't loaded in the host kernel, and the container cannot cause the module to be loaded due to the isolation of that container. It is possible that since you had the problem, the necessary modules have been loaded in the host kernel.

The comments look fine to me. Also I have run the configuration above, albeit with a more recent version of keepalived, and it doesn't have a problem.

You should fix the error reported regarding `Unknown keyword 'lvs_id'`

**Comment by raffaelespazzoli** [comment]
I will upgrade, thanks.
what are the kernel modules required by keepalived? I can make sure they are loaded.
`lvs_id` seems a valid entry based on this: http://www.keepalived.org/doc/configuration_synopsis.html
but it is being rejected, not sure why, any suggestion? 
I didn't find a lot of explanation on what it does, Is it needed?

**Comment by pqarmitage** [comment]
`lvs_id` was replace by `router_id` in version 1.1.8 (January 2005).

We know the documentation is out of date,  but 13 years is quite something! It is on our todo list to update the documentation.

The modules needed include ip_vs, and potentially iptables modules and ipset modules.
