### ISSUE TITLE
vmac_xmit_base does not works with IPv6

### ISSUE THREAD

**Issue by Jean-Daniel** [acassen/keepalived#917]
I have a simple configuration:

```
vrrp_instance instance1 {
    state BACKUP
    version 3
    interface enp1s0
    virtual_router_id 250
    use_vmac vrrp_250
    vmac_xmit_base         # Transmit VRRP adverts over physical interface
    @master priority 150
    @backup priority 50
    advert_int 1
    virtual_ipaddress {
        fe80::1234
    }
    notify_master "/etc/keepalived/vmac_tweak.sh vrrp_250"
}
```

Everything work great when I'm using an IPv4, but when I'm using an IPv6, the both node switch to MASTER status and ignore other node advertisements.

A quick look at the network trace show me that the VRRP frames are send using the vrrp interface, and not the base interface:

```
18:06:38.717215 00:00:5e:00:02:fa > 33:33:00:00:00:12, ethertype IPv6 (0x86dd), length 78: (class 0xc0, flowlabel 0x47585, hlim 255, next-header VRRP (112) payload length: 24) fe80::5054:ff:fe73:1b9b > ff02::12: ip-proto-112 24
```

If i remove the `vmac_xmit_base` setting, the emitted frames are identical but at least, keepalived accepts them and only one node switch to master mode at a time.

**Comment by pqarmitage** [comment]
@Jean-Daniel Many thanks for reporting this. Commit 18ec95a resolves the problem.
