### ISSUE TITLE
can't add virtual_route to vmac interface

### ISSUE THREAD

**Issue by Jean-Daniel** [acassen/keepalived#920]
When switching to master, I need to update some routes and so I'm trying to use virtual_route {} block to do so. 
My route have to use the vrrp.id iface created by keepalived when using vmac.

My issue is that as keepalived try to validate the route dev before creating the vmac interface, it fails with the following message:

`WARNING - interface vrrp_150 for VROUTE nexthop doesn't exist`

and the route is not setup when switching to master.

If I don't specify device in the route definition, it emits that warning: `Warning - cannot track route default with no interface specified, not tracking` and the route is instantiated on an other interface.

My config looks like this:

```
vrrp_instance instance1 {
    state BACKUP
    version 3
    interface enp1s0
    virtual_router_id 150
    use_vmac vrrp_150
    vmac_xmit_base         # Transmit VRRP adverts over physical interface
    @master priority 150
    @backup priority 50
    advert_int 1
    virtual_ipaddress {
        fe80::1234
    }
    virtual_route {
      default6 via fe80::1 dev vrrp_150
    }
    notify_master "/etc/keepalived/vmac_tweak.sh vrrp_150"
}
```

**Comment by pqarmitage** [comment]
In order for keepalived to accept configuration on interfaces that don't exist when keepalived is reading the configuration file (such as on VMACs), you need to specify `dynamic_interfaces` in the global_defs section of the configuration.

**Comment by pqarmitage** [comment]
Also `virtual_route` should be `virtual_routes`.
