### ISSUE TITLE
Keepalived Segmentation Fault

### ISSUE THREAD

**Issue by iliesh** [acassen/keepalived#926]
Trying to use VRRP V3 is causing keepalived to crash.
This is the log file:

Fri Jun 22 10:56:16 2018: Starting Keepalived v2.0.4 (06/17,2018)
Fri Jun 22 10:56:16 2018: Running on Linux 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 (built for Linux 3.10.0)
Fri Jun 22 10:56:16 2018: Opening file '/usr/local/etc/keepalived/keepalived.conf'.
Fri Jun 22 10:56:16 2018: Starting VRRP child process, pid=30434
Fri Jun 22 10:56:16 2018: Keepalived_vrrp exited due to segmentation fault (SIGSEGV).
Fri Jun 22 10:56:16 2018:   Please report a bug at https://github.com/acassen/keepalived/issues
Fri Jun 22 10:56:16 2018:   and include this log from when keepalived started, a description
Fri Jun 22 10:56:16 2018:   of what happened before the crash, your configuration file and the details below.
Fri Jun 22 10:56:16 2018:   Also provide the output of keepalived -v, what Linux distro and version
Fri Jun 22 10:56:16 2018:   you are running on, and whether keepalived is being run in a container or VM.
Fri Jun 22 10:56:16 2018:   A failure to provide all this information may mean the crash cannot be investigated.
Fri Jun 22 10:56:16 2018:   If you are able to provide a stack backtrace with gdb that would really help.
Fri Jun 22 10:56:16 2018:   Source version 2.0.4
Fri Jun 22 10:56:16 2018:   Built with kernel headers for Linux 3.10.0
Fri Jun 22 10:56:16 2018:   Running on Linux 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018
Fri Jun 22 10:56:16 2018:   configure options: --enable-snmp --enable-snmp-vrrp --enable-snmp-keepalived --enable-snmp-checker
Fri Jun 22 10:56:16 2018:                       --enable-snmp-rfc
Fri Jun 22 10:56:16 2018:   Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP
Fri Jun 22 10:56:16 2018:                    SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3
Fri Jun 22 10:56:16 2018:   System options:  PIPE2 SIGNALFD INOTIFY_INIT1 LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_TUN_ID
Fri Jun 22 10:56:16 2018:                    RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME NET_LINUX_IF_H_COLLISION
Fri Jun 22 10:56:16 2018:                    LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC
Fri Jun 22 10:56:16 2018:                    O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK
Fri Jun 22 10:56:16 2018: VRRP child process(30434) died: Respawning
Fri Jun 22 10:56:16 2018: Starting VRRP child process, pid=30454
Fri Jun 22 10:56:17 2018: Keepalived_vrrp exited due to segmentation fault (SIGSEGV).
Fri Jun 22 10:56:17 2018:   Please report a bug at https://github.com/acassen/keepalived/issues
Fri Jun 22 10:56:17 2018:   and include this log from when keepalived started, a description
Fri Jun 22 10:56:17 2018:   of what happened before the crash, your configuration file and the details below.
Fri Jun 22 10:56:17 2018:   Also provide the output of keepalived -v, what Linux distro and version
Fri Jun 22 10:56:17 2018:   you are running on, and whether keepalived is being run in a container or VM.
Fri Jun 22 10:56:17 2018:   A failure to provide all this information may mean the crash cannot be investigated.
Fri Jun 22 10:56:17 2018:   If you are able to provide a stack backtrace with gdb that would really help.
Fri Jun 22 10:56:17 2018:   Source version 2.0.4
Fri Jun 22 10:56:17 2018:   Built with kernel headers for Linux 3.10.0
Fri Jun 22 10:56:17 2018:   Running on Linux 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018
Fri Jun 22 10:56:17 2018:   configure options: --enable-snmp --enable-snmp-vrrp --enable-snmp-keepalived --enable-snmp-checker
Fri Jun 22 10:56:17 2018:                       --enable-snmp-rfc
Fri Jun 22 10:56:17 2018:   Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP
Fri Jun 22 10:56:17 2018:                    SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3
Fri Jun 22 10:56:17 2018:   System options:  PIPE2 SIGNALFD INOTIFY_INIT1 LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_TUN_ID
Fri Jun 22 10:56:17 2018:                    RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME NET_LINUX_IF_H_COLLISION
Fri Jun 22 10:56:17 2018:                    LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC
Fri Jun 22 10:56:17 2018:                    O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK
Fri Jun 22 10:56:17 2018: VRRP child process(30454) died: Respawning

[root@host keepalived-2.0.4]# /usr/local/sbin/keepalived -v
Keepalived v2.0.4 (06/17,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018

configure options:

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK

[root@host keepalived-2.0.4]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

Keepalived daemon is running on a physical machine.

Configuration File:

global_defs {
vrrp_version 3
script_user root
enable_script_security
#enable_traps
    notification_email {
        user@company.com
   }
   notification_email_from "[Keepalive] Service <user@company.com>"
   smtp_server 127.0.0.1
   smtp_connect_timeout 30
}

**Comment by pqarmitage** [comment]
@iliesh Your configuration works for me, albeit I haven't tried it on CentOS yet.

There is something strange with the output of `/usr/local/bin/keepalived -v` compared to the logs you have provided. The output of `/usr/local/bin/keepalived -v` doesn't show any configure options, whereas the system logs show `--enable-snmp --enable-snmp-vrrp --enable-snmp-keepalived --enable-snmp-checker --enable-snmp-rfc` (and also the Config options output is different) so it would appear that the keepalived executed when the system logs are produced is a different version of keepalived from /usr/local/bin/keepalived.

If you can provide a stack backtrace using gdb it would help to track down the cause of the problem.

**Comment by iliesh** [comment]
@pqarmitage, 
yes, the output of /usr/local/bin/keepalived -v could be different because i was thinking that the issue is with snmp module, and i recompiled it again before post here an issue.

[root@host keepalived]# /usr/local/sbin/keepalived -v
Keepalived v2.0.4 (06/17,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018

configure options:

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK

-----------------------------------------------------------------------------------------------------------
Jun 23 11:53:47 Keepalived[11667]:  Built with kernel headers for Linux 3.10.0
Jun 23 11:53:47 Keepalived[11667]:  Running on Linux 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018
Jun 23 11:53:47 Keepalived[11667]:  Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING
Jun 23 11:53:47 Keepalived[11667]:  System options:  PIPE2 SIGNALFD INOTIFY_INIT1 LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_TUN_ID
Jun 23 11:53:47 Keepalived[11667]:                   RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME NET_LINUX_IF_H_COLLISION
Jun 23 11:53:47 Keepalived[11667]:                   LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC
Jun 23 11:53:47 Keepalived[11667]:                   O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK
Jun 23 11:53:47 Keepalived[11667]: VRRP child process(11668) died: Exiting
Jun 23 11:53:47 Keepalived[11667]: Stopping

this is the backtrace using gdb command:
[root@host keepalived]# gdb /usr/local/sbin/keepalived /core.11668

GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/sbin/keepalived...done.
[New LWP 11668]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/local/sbin/keepalived -D -f /usr/local/etc/keepalived/keepalived.conf -g /'.
Program terminated with signal 11, Segmentation fault.
#0  vrrp_update_pkt (vrrp=vrrp@entry=0x55c85b3cc080, prio=254 '\376', addr=0x55c85b3ad164) at vrrp.c:419
419             if (hd->priority != prio) {
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 elfutils-libelf-0.170-4.el7.x86_64 elfutils-libs-0.170-4.el7.x86_64 glibc-2.17-222.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-19.el7.x86_64 libattr-2.4.46-13.el7.x86_64 libcap-2.22-9.el7.x86_64 libcom_err-1.42.9-12.el7_5.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libnl3-3.2.28-4.el7.x86_64 libselinux-2.5-12.el7.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 pcre-8.32-17.el7.x86_64 systemd-libs-219-57.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) 

(gdb) bt
#0  vrrp_update_pkt (vrrp=vrrp@entry=0x55c85b3cc080, prio=254 '\376', addr=0x55c85b3ad164) at vrrp.c:419
#1  0x000055c859f0418e in vrrp_in_chk (vrrp=vrrp@entry=0x55c85b3cc080, buffer=buffer@entry=0x55c85b3cb9b0 "E\300", 
    buflen_ret=buflen_ret@entry=32, check_vip_addr=<optimized out>) at vrrp.c:913
#2  0x000055c859f04ed9 in vrrp_check_packet (check_vip_addr=<optimized out>, buflen=32, buf=0x55c85b3cb9b0 "E\300", vrrp=0x55c85b3cc080)
    at vrrp.c:1403
#3  vrrp_state_backup (vrrp=vrrp@entry=0x55c85b3cc080, buf=0x55c85b3cb9b0 "E\300", buflen=buflen@entry=32) at vrrp.c:1713
#4  0x000055c859f0a74c in vrrp_backup (len=32, buffer=<optimized out>, vrrp=0x55c85b3cc080) at vrrp_scheduler.c:703
#5  vrrp_dispatcher_read (sock=0x55c85b3cb730, sock=0x55c85b3cb730) at vrrp_scheduler.c:960
#6  vrrp_read_dispatcher_thread (thread=0x55c85b3cc000) at vrrp_scheduler.c:996
#7  0x000055c859f1fdf3 in thread_call (thread=0x55c85b3cc000) at scheduler.c:1283
#8  process_threads (m=0x55c85b3b3640) at scheduler.c:1162
#9  0x000055c859f1fe9c in launch_scheduler () at scheduler.c:1292
#10 0x000055c859efd259 in start_vrrp_child () at vrrp_daemon.c:818
#11 0x000055c859ee665b in start_keepalived () at main.c:462
#12 keepalived_main (argc=<optimized out>, argv=<optimized out>) at main.c:1489
#13 0x00007feda96ba445 in __libc_start_main () from /lib64/libc.so.6
#14 0x000055c859ee48fe in _start ()

Full Configuration file:

global_defs {
vrrp_version 3
script_user root
enable_script_security
    notification_email {
        admin@mail.com
   }
   notification_email_from "Keepalive <keepalived@mail.com>"
   smtp_server 127.0.0.1
   smtp_connect_timeout 30
}
vrrp_instance MGMT {
    state BACKUP
    interface em1
    virtual_router_id 10
    priority 80
    advert_int 1
    dont_track_primary

    track_interface {
        br_0.10
    }

    virtual_ipaddress {
        172.16.10.1/25 brd 172.16.10.127 dev br_0.10
    }
unicast_src_ip 192.168.1.2
    unicast_peer {
     192.168.1.1
    }
}


Thank You.

**Comment by pqarmitage** [comment]
Commit  27e9865 resolves the segfault.
