### ISSUE TITLE
Not able to switch to slave when the master network interface is down  

### ISSUE THREAD

**Issue by s33n** [acassen/keepalived#927]
vrrp_instance VI_1 {
state MASTER
interface p4p1
virtual_router_id 51
priority 100
advert_int 1
authentication {
auth_type PASS
auth_pass 1111
}
virtual_ipaddress {
10.34.221.170
}
}
virtual_server 10.34.221.170 80 {
delay_loop 6
lb_algo rr
lb_kind NAT
protocol TCP

real_server 10.34.220.68 80 {
    TCP_CHECK {
            connect_timeout 10
    }
}
real_server 10.34.221.23 80 {
    TCP_CHECK {
            connect_timeout 10
    }
This is the code i had on my keepalived.conf. And It is switching from master to slave only incase of Keepalived service is down not with the cases where my realserver(master) is down. Guys need your help correct me if im wrong i wanted to switch even in cases the Master IP is not reachable.

Here are the var/log msgs

Jun 22 20:06:05 suri2 Keepalived_healthcheckers[7801]: TCP connection to [10.34.220.68]:80 failed !!!
Jun 22 20:06:05 suri2 Keepalived_healthcheckers[7801]: Removing service [10.34.220.68]:80 from VS [10.34.221.170]:80
Jun 22 20:06:05 suri2 Keepalived_healthcheckers[7801]: Remote SMTP server [0.0.0.0]:25 connected.
Jun 22 20:06:05 suri2 Keepalived_healthcheckers[7801]: SMTP alert successfully sent.

**Comment by pqarmitage** [comment]
There is no configuration option to make a vrrp instance transition out of master state due to a virtual server (or real server) being down.

If you want the vrrp instance to go down if 10.34.220.68 or 10.34.221.23 are unreachable, then you will need to use a track_script that does the check and returns an appropriate exit code.
