### ISSUE TITLE
Keepalived Errno 88

### ISSUE THREAD

**Issue by iliesh** [acassen/keepalived#930]
When i'm trying to stop keepalived daemon, in logs i see a lot of error messages:

```
Jun 25 15:58:29 host Keepalived_vrrp[12240]: Read on vrrp send socket 0 failed - errno 88 (Socket operation on non-socket)
Jun 25 15:58:29 host Keepalived_vrrp[12240]: Read on vrrp send socket 0 failed - errno 88 (Socket operation on non-socket)
Jun 25 15:58:29 host Keepalived_vrrp[12240]: Read on vrrp send socket 0 failed - errno 88 (Socket operation on non-socket)
Jun 25 15:58:29 host Keepalived_vrrp[12240]: Read on vrrp send socket 0 failed - errno 88 (Socket operation on non-socket)
Jun 25 15:58:29 host Keepalived_vrrp[12240]: Read on vrrp send socket 0 failed - errno 88 (Socket operation on non-socket)
```

What they are caused by? Is there any way to stop them?

Also, all the time when i'm starting keepalived daemon i'm receiving such error in logs:
`Jun 25 09:25:39 host Keepalived_vrrp[10148]: Kernel/system configuration issue causing multicast packets to be received but IP_MULTICAST_ALL unset`

I checked on all interfaces and "allmulticast" parameter is set:

[root@host keepalived]# ip link show dev eth0
5: eth0: <BROADCAST,MULTICAST,**ALLMULTI**,UP,LOWER_UP> mtu 1500 qdisc mq master br0 state UP mode DEFAULT group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff

Is there something wrong with configuration or this is a bug?
Thank You.

NAME="CentOS Linux"
VERSION="7 (Core)"

Configuration File:
```
global_defs {
vrrp_version 3
script_user root
enable_script_security
enable_snmp_vrrp
enable_snmp_checker
enable_snmp_rfc
enable_snmp_rfcv3
enable_traps
    notification_email {
       admin@mail.com
   }
   notification_email_from "Keepalive keepalived@company>"
   smtp_server 127.0.0.1
   smtp_connect_timeout 30
vrrp_mcast_group4 224.0.0.18
vrrp_mcast_group6 ff02::12
}

vrrp_instance V_I {
    state MASTER
    interface br0.10
    virtual_router_id 10
    priority 100
    smtp_alert
    advert_int 1

    virtual_ipaddress {
        192.168.1.1/25 brd 192.18.1.127 dev br0.10
    }

    notify_master "/usr/scripts/keepalived_notify.sh MASTER INTERNAL"
    notify_backup "/usr/scripts/keepalived_notify.sh BACKUP INTERNAL"
    notify_fault "/usr/scripts/keepalived_notify.sh FAULT INTERNAL"
    notify_stop "/usr/scripts/keepalived_notify.sh STOP INTERNAL"
}

```
[root@host keepalived]# /usr/local/sbin/keepalived -v
Keepalived v2.0.4 (unknown)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018

configure options: --enable-snmp --enable-snmp-vrrp --enable-snmp-keepalived --enable-snmp-checker --enable-snmp-rfc

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK

**Comment by iliesh** [comment]
@pqarmitage,

Thank you for the prompt answer, I just tried again with the latest commit - and anyway i'm receiving such errors.

**Comment by iliesh** [comment]
Also, I checked the source code files and seems that commit 88c698d is applied, but anyway the errors are coming up, so I guess that the problem is in something else.

**Comment by iliesh** [comment]
@pqarmitage 

Yes, of course:

```
[root@host keepalived]# /usr/local/sbin/keepalived -v
Keepalived v2.0.4 (unknown)

Copyright(C) 2001-2018 Alexandre Cassen, acassen@gmail.com

Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018

configure options: --enable-snmp --enable-snmp-vrrp --enable-snmp-keepalived --enable-snmp-checker --enable-snmp-rfc

Config options: LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options: PIPE2 SIGNALFD INOTIFY_INIT1 LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK
```
I run 2 instances - Master and Backup, config is the same - just STATE and PRIORITY are different.

**Comment by pqarmitage** [comment]
keepalived built with the latest commit should show:
`Keepalived v2.0.4 (06/25,2018), git commit v2.0.4-16-g8650e8b3`
as the first line of the output of `keepalived -v`. It looks like you are still running the vanilla v2.0.4 version of keepalived.

**Comment by iliesh** [comment]
@pqarmitage 
On the server where actually I have installed keepalived, I don't have internet and I was copying the zip archive from GitHub, now i cloned keepalived repo on my pc and then moved to the server.

Now this is what i get by running keepalived -v:

[root@host keepalived]# /usr/local/sbin/keepalived -v
Keepalived v2.0.4 (06/25,2018), git commit v2.0.4-18-gbc7af53

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018

configure options: --enable-snmp --enable-snmp-vrrp --enable-snmp-keepalived --enable-snmp-checker --enable-snmp-rfc

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RT SCHED_RESET_ON_FORK
[root@host keepalived]#

**Comment by pqarmitage** [comment]
@iliesh Can you confirm that with version v2.0.4-18-gbc7af53 you are still getting the
`Jun 25 15:58:29 host Keepalived_vrrp[12240]: Read on vrrp send socket 0 failed - errno 88 (Socket operation on non-socket)`
log messages on termination of keepalived.

**Comment by pqarmitage** [comment]
Commit 7ff7ea1 should resolve the problem.

**Comment by iliesh** [comment]
@pqarmitage 
Yes, now it's working better. What about this message: 
`Kernel/system configuration issue causing multicast packets to be received but IP_MULTICAST_ALL unset`
?

**Comment by pqarmitage** [comment]
@iliesh Thanks for the confirmation that its working now. The `IP_MULTICAST_ALL unset` message is just a diagnostic message, so don't worry about it. I'll have a look at it sometime soon.

**Comment by iliesh** [comment]
@pqarmitage 
Great, Thank you very much for your support.
