### ISSUE TITLE
MISC_PATH execve() quoting changed

### ISSUE THREAD

**Issue by sim-** [acassen/keepalived#931]
Hello! I'm trying to debug a problem with the IPVS sync daemon never being promoted to master on a build I made between versions 1.4.2 and 1.4.3 (actual commit was 4f3ea7094c2788889fd6d73a3baca171eb5c47f1). On this version, and every version prior, I've used a misc_path string that I am expecting to work with shell quoting; for example, the line looks like:

misc_path "/usr/local/bin/http_test https 1.2.3.4 2.3.4.5 'Storage is working' ...other stuff..."

I just did a build of master and now this check is failing because the execve() for it has changed: 

From: [pid  2944] execve("/usr/local/bin/http_test", ["/usr/local/bin/http_test", "https", "1.2.3.4", "2.3.4.5", "Storage is working", ...])

To: [pid 11272] execve("/usr/local/bin/http_test", ["/usr/local/bin/http_test", "https", "1.2.3.4", "2.3.4.5", "'Storage", "is", "working'", ...])

This makes it not work. How can I now pass an argument with spaces to the script? This probably shouldn't be intended as it will break older configuration (like mine).

BTW: I also have to probably now move the http_test script to /etc/keepalived or somewhere since the default /usr/local permissions are root:staff g+w, and it also complains about this.

**Comment by sim-** [comment]
I bisected this to b4566528e64370eb2ca07d24e43ecaef55d43073 which has an obvious comment but I missed it because of merge order and the order of "git log". git tag --contains says this didn't get released until v2.0.0. In any event, while it's nicer to use execve() than system() (which is basically execve with "/bin/sh","-c",&lt;string&gt;), is there now any way to pass single arguments with spaces?

If I try: misc_path /bin/echo "hello world", only "/bin/echo" is executed.

If I try: misc_path "/bin/echo 'hello world'", the words are passed separately with no quote handling:
[pid 26835] execve("/bin/echo", ["/bin/echo", "'hello", "world'"], 0x7ffdaf6e1f58 /* 56 vars */) = 0

If I try misc_path "/bin/sh -c 'echo hello world'" or with quoted spaces or similar, the same thing happens -- only the first word is passed, "'echo".

So, since this commit, I can't find any way to pass arguments containing spaces to any command. The only workaround would be to make all scripts not accept such arguments.

For backwards compatibility, I suggest this commit be reverted. Maybe there is a way to make it accept execve-style argument arrays in some cases (like specific parsing of single quotes or something ala what /bin/sh -c _was_ doing), but then I bet some odd people are using and relying on other shell features working (like variable subsitution of $HOST, maybe?). I don't know what's best to do here that doesn't break my existing configuration. ;)

**Comment by pqarmitage** [comment]
I will have to look into this. I don't think the solution is to revert the commit; I need to have a look at how to passed arguments with spaces.

**Comment by sim-** [comment]
I can probably fix up set_script_params_array() to parse quotes/apostrophes as /bin/sh did, if that would work for you.

**Comment by pqarmitage** [comment]
I'm just completing a patch for some other functionality that I think should do what you want. I'll post the patch and a description here when it is ready.

**Comment by pqarmitage** [comment]
I've pushed commit cb3e966 which should resolve this issue. `"/bin/echo 'hello world'"` should now work as you indicated it should. See section 0.6 or doc/keepalived.conf.SYNOPSIS for what has been implemented.

**Comment by sim-** [comment]
Yes, indeed, it now works without me changing anything as of a build from master pulled a few minutes ago. Thanks!

BTW, it _does_ now log "Keepalived_vrrp[26989]: Kernel/system configuration issue causing multicast packets to be received but IP_MULTICAST_ALL unset"... Do you want assistance debugging this?

This is a relatively vanilla 4.14.48 kernel but with some of our (unrelated) patches. It is not based on an upstream Debian kernel. strace shows all of the raw sockets it has open, fds 8 through 15, are receiving the same multicast packets. lib/config.h has "#define HAVE_DECL_IP_MULTICAST_ALL 1", so the if_setsockopt_mcast_all() should be happening. I would probably try tracing ip_mc_sf_allow() in the kernel which is likely either returning 1 because of ipv4_is_multicast(loc_addr) or the pmc foreach loop.

**Comment by pqarmitage** [comment]
Regarding the "IP_MULTICAST_ALL unset" message, this was introduced by commit 6fb5980. The comments with that commit should explain the reasoning. Any help on the reason for this happening would be much appreciated.

Would you be happy to close this issue and raise a new issue for the IP_MULTICAST_ALL unset issue?

**Comment by sim-** [comment]
Yep! Thanks!
