### ISSUE TITLE
Using keepalived with multiple interfaces and unicast ip address on dummy interface

### ISSUE THREAD

**Issue by jeunito** [acassen/keepalived#935]
Running into problems running keepalived with multiple interfaces. 

1.  Active/passive setup of two servers.
2. Unicast communication for keepalived
3. Both servers have two interfaces that are connected to the switch
4. Server ip is on a dummy interface so traffic is routed into one of the two interfaces
5. VIP managed by keepalived is also on a dummy interface

When all interfaces are up on both nodes, keepalived has problems with the election and so both nodes come up as MASTER.

```
VRRP_Instance(my_app) Received lower prio advert, forcing new election
VRRP_Instance(my_app) Sending gratuitous ARPs on vip for 10.30.2.1
....
```

On tcpdump this is what is seen:

```
23:59:26.004923 IP node2 > node1: ICMP node2 protocol 112 unreachable, length 48
```

When only one interface is up on each node, things work as expected.

**Version: Keepalived v1.2.19 (05/18,2016)**

**/etc/network/interfaces** on both servers:
```
auto vip
iface vip inet manual
pre-up /sbin/ip link add vip type dummy
up /sbin/ip link set vip up
down /sbin/ip link del vip

auto mgmt
iface mgmt inet manual
pre-up /sbin/ip link add mgmt type dummy
up /sbin/ip link set mgmt up
up /sbin/ip addr add 10.30.10.50/32 dev mgmt
down /sbin/ip link del mgmt

auto eth0
iface eth0 inet6 auto

auto eth1
iface eth1 inet6 auto
```

**/etc/keepalived/keepalived.conf** (almost the same on both servers except for priority and unicast configuration):
```
vrrp_instance my_app {
        interface eth0
        state BACKUP
        virtual_router_id 100
        priority 100
        advert_int 1
        unicast_src_ip 10.30.10.50
        unicast_peer {
            10.30.10.51
        }
        track_script {
        ...
        }
        authentication {
        ...
        }

        virtual_ipaddress {
            10.30.2.1/32 dev vip
        }
}
```

**Comment by pqarmitage** [comment]
This would appear to be a problem with your network configuration; somehow having both interfaces up makes the other node unreachable as shown by the tcpdump output.

if you still suspect the problem is with keepalived, then please upgrade to the latest version (v2.0.5) to see if you still have the problem with that version. If you then still have the problem, please post the output of the following commands from both systems:
```
ip link show
ip addr show
ip route show
kernel version and distro details
keepalived -v
The full system logs from both systems from when keepalived starts to the problem being exhibited (for this it would be good to start with one interface down so keepalived works as you expect, and then up the downed interface.
```

**Comment by jeunito** [comment]
Ok thanks will try to upgrade first.

**Comment by jeunito** [comment]
@pqarmitage is there a make target that organizes keepalived into a directories that simulate how files will be installed on a Debian system? I am trying to build a deb file out of this.
