### ISSUE TITLE
about keepalived start

### ISSUE THREAD

**Issue by LinSizhan** [acassen/keepalived#938]
I had a problem when I started the keepalived service:
![qq 20180702180422](https://user-images.githubusercontent.com/40759729/42158197-6214b0b2-7e22-11e8-93a2-5383ab009292.png)
keepalived version is 2.0.5

/etc/keepalived/keepalived.conf:
-----------------------------------------------------------------------------
! Configuration File for keepalived

global_defs {
   notification_email {
	linsizhan@xmiles.cn
	312890237@qq.com
   }
   notification_email_from root
   smtp_server 127.0.0.1
   smtp_connect_timeout 30
   router_id LVS_DEVEL
   vrrp_skip_check_adv_addr
   vrrp_strict
   vrrp_garp_interval 0
   vrrp_gna_interval 0
}

vrrp_script chk_haproxy {
    #script "killall -0 haproxy"
    script "ps aux | grep -v "grep" | grep haproxy"
    interval 2
    weight 2
}

vrrp_instance VI_1 {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 101
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        47.106.94.80
    }
    track_script {
        chk_haproxy
    }
}

virtual_server 47.106.94.80 48066 {
    delay_loop 6
    lb_algo rr
    lb_kind NAT
    persistence_timeout 50
    protocol TCP
    real_server 47.106.94.79 48066 {
        weight 1
	TCP_CHECK {
		connect_timeout 3
		nb_get_retry 3
		delay_before_retry 3
	}
    }
    real_server 47.106.94.79 48066 {
        weight 1
        TCP_CHECK {
                connect_timeout 3
                nb_get_retry 3
                delay_before_retry 3
        }
    }
}
-----------------------------------------------------------------------------

 /etc/init.d/keepalived:

-----------------------------------------------------------------------------
#!/bin/sh

. /etc/rc.d/init.d/functions
. /etc/sysconfig/keepalived

RETVAL=0

prog="keepalived"

start() {
    echo -n $"Starting $prog: "
    daemon keepalived ${KEEPALIVED_OPTIONS}
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
}

stop() {
    echo -n $"Stopping $prog: "
    killproc keepalived
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
}

reload() {
    echo -n $"Reloading $prog: "
    killproc keepalived -1
    RETVAL=$?
    echo
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    reload)
        reload
        ;;
    restart)
        stop
        start
        ;;
    condrestart)
        if [ -f /var/lock/subsys/$prog ]; then
            stop
            start
        fi
        ;;
    status)
        status keepalived
        RETVAL=$?
        ;;
    *)
        echo "Usage: $0 {start|stop|reload|restart|condrestart|status}"
        RETVAL=1
esac

exit $RETVAL
-----------------------------------------------------------------------------

When I look at the start log
tail -f /var/log/messages
-----------------------------------------------------------------------------
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32743]: Starting Keepalived v2.0.5 (06/29,2018)
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32743]: Running on Linux 2.6.32-696.6.3.el6.x86_64 #1 SMP Wed Jul 12 14:17:22 UTC 2017 (built for Linux 2.6.32)
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32743]: Opening file '/etc/keepalived/keepalived.conf'.
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]: Starting Healthcheck child process, pid=32746
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]: Starting VRRP child process, pid=32747
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: Registering Kernel netlink reflector
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: Registering Kernel netlink command channel
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: Opening file '/etc/keepalived/keepalived.conf'.
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: (VI_1) State MASTER must match being address owner
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: (VI_1) Strict mode does not support authentication. Ignoring.
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: Assigned address 172.18.183.39 for interface eth0
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: Registering gratuitous ARP shared channel
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_healthcheckers[32746]: Opening file '/etc/keepalived/keepalived.conf'.
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]: Keepalived_healthcheckers exited due to segmentation fault (SIGSEGV).
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:   Please report a bug at https://github.com/acassen/keepalived/issues
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:   and include this log from when keepalived started, a description
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:   of what happened before the crash, your configuration file and the details below.
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:   Also provide the output of keepalived -v, what Linux distro and version
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:   you are running on, and whether keepalived is being run in a container or VM.
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:   A failure to provide all this information may mean the crash cannot be investigated.
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:   If you are able to provide a stack backtrace with gdb that would really help.
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:   Source version 2.0.5 
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:   Built with kernel headers for Linux 2.6.32
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:   Running on Linux 2.6.32-696.6.3.el6.x86_64 #1 SMP Wed Jul 12 14:17:22 UTC 2017
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z kernel: keepalived[32746]: segfault at 0 ip 00007f54f62fe30f sp 00007ffc13191fd0 error 4 in keepalived[7f54f62ea000+61000]
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:   configure options: --prefix=/usr/local/keepalived
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:   Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:   System options:  PIPE2 SIGNALFD INOTIFY_INIT1 LIBNL3 NET_LINUX_IF_H_COLLISION
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:                    LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]:                    GLOB_BRACE SO_MARK SCHED_RT SCHED_RESET_ON_FORK
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]: Stopping
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: (VI_1) removing VIPs.
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: (VI_1) removing iptable drop rule
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: (VI_1) Entering BACKUP STATE (init)
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: VRRP sockpool: [ifindex(2), proto(112), unicast(0), fd(8,9)]
Jul  2 18:14:46 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: Child process 32744 in our process group 32744
Jul  2 18:14:47 iZwz93056tlb7i0jgvkju6Z Keepalived_vrrp[32747]: Stopped
Jul  2 18:14:47 iZwz93056tlb7i0jgvkju6Z Keepalived[32744]: Stopped Keepalived v2.0.5 (06/29,2018)

------------------------------------------------------------------------------------------

What's the problem

**Comment by pqarmitage** [comment]
Commit cd1dc19 should resolve your segfault.

You also appear to have defined the same real server twice for the same virtual server, which won't achieve anything and won't work properly.

`nb_get_retry` is a deprecated keyword that only applied to HTTP_GET and SSL_GET checkers. The correct keyword to use, which works for all checkers is `retry`.
