### ISSUE TITLE
configure --enable-debug flag results in undeclared ‘parent_child_remover’

### ISSUE THREAD

**Issue by rohara** [acassen/keepalived#940]
Running the configure script with the --enable-debug flag fails to build:

$ ./configure --enable-debug ...
...
$ make
...
main.c: In function ‘keepalived_main’:
main.c:1258:20: error: ‘parent_child_remover’ undeclared (first use in this function); did you mean ‘set_child_remover’?
  set_child_remover(parent_child_remover);
                    ^~~~~~~~~~~~~~~~~~~~
                    set_child_remover
main.c:1258:20: note: each undeclared identifier is reported only once for each function it appears in

A quick peak at the code does indeed show that the parent_child_remover function is wrapped in '#ifndef _DEBUG_" yet the call to it in the keepalived_main function is not wrapped in the same ifndef. The obvious solution is to wrap the call to set_child_remover in "#ifndef _DEBUG_", but I'd like confirmation before submitting a patch.

**Comment by pqarmitage** [comment]
@rohara Yes, I agree with your diagnosis that `set_child_remover()` should be wrapped in `#ifndef DEBUG`.

**Comment by pqarmitage** [comment]
Commit d1a9777 resolves this issue and also resolves other warnings when building with --enable-debug.
