### ISSUE TITLE
Master does not enter FAULT state if track_script fails

### ISSUE THREAD

**Issue by sivann** [acassen/keepalived#942]
Master's script exits non-zero, priority is reduced , this is communicated to backup which has a higher priority (saw via tcpdump). Master never enters FAILED state it remains the master, even with the minimal priority of 1. I tried the preempt option with no luck.

Version is keepalived-2.0.5

Master conf:
```
# check filesystem health
vrrp_script chk_fs {
       script "/usr/local/bin/keepalived_chk_fs.sh"
       interval 2                      # check every 2 seconds
       weight -200                     # default prio: -4 if KO
       fall 3                          # fail after 3 retries (6 seconds)
       rise 3                          # require 3 successes for OK
}


global_defs {
   notification_email {
     sivann@inaccess.com
   }
   notification_email_from keepalived@ark3440.local
   smtp_server relay.inaccess.com
   smtp_connect_timeout 30
   router_id 3440
   script_user nobody
   enable_script_security

}

vrrp_instance VI_1 {
    state MASTER
    interface eno1
    virtual_router_id 51
    priority 200
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass lala
    }
    track_script {
        chk_fs
    }
    notify /usr/local/bin/keepalived_notify.sh
    virtual_ipaddress {
        192.168.2.50/24
    }
    unicast_peer {
        192.168.4.167
    }
    preempt
    preempt_delay 1
}
```

backup conf:

```
# check filesystem health
vrrp_script chk_fs {
       script "/usr/local/bin/keepalived_chk_fs.sh"
       interval 2                      # check every 2 seconds
       weight -150                     # default prio: -4 if KO
       fall 3                          # fail after 3 retries (6 seconds)
       rise 3                          # require 3 successes for OK
}


global_defs {
   notification_email {
     sivann@inaccess.com
   }
   notification_email_from keepalived@ark3440.local
   smtp_server relay.inaccess.com
   smtp_connect_timeout 30
   router_id atom
   script_user nobody
   enable_script_security
}

vrrp_instance VI_1 {
    state BACKUP
    interface enp0s25
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass lala
    }
    track_script {
        chk_fs
    }
    notify /root/state_change.sh
    virtual_ipaddress {
        192.168.2.50/24
    }
    unicast_peer {
        192.168.4.51
    }
    preempt
    preempt_delay 1
}
```

Logs in master just show:
```
Jul 05 10:54:26 ark-3440 Keepalived_vrrp[24299]: VRRP_Script(chk_fs) failed (exited with status 1)
Jul 05 10:54:26 ark-3440 Keepalived_vrrp[24299]: (VI_1) Changing effective priority from 200 to 1
```

**Comment by sivann** [comment]
Ah found it, weight must be commented. This must be better depicted in the documentation.

**Comment by pqarmitage** [comment]
@sivann Could you please explain what you mean by `weight must be commented`. If the documentation needs updating I will happily do that.

If a weighted script returns a non-zero exit code, it doens't make the vrrp instance go to fault state, instead it adjusts the effective priority, so that, as you were expecting, the priority of the original master is reduced and what was the backup has higher priority and becomes the new master.

I have tested your configurations as you set out above and they work for me.

**Comment by sivann** [comment]
Thank you for the prompt response! Yes I meant that weight should not be specified. The part of the keelalived.conf(5) reads:  
"...will cause vrrp instances to go down it they exit  a non-zero exist status or if a weight is specified will add or subtract the weight to/from the priority" 
That was not very clear to me as I thought that the weight of -200 could reduce priority to 0, but priority does not go below 1. One should read the RFC to understand this and the importance of priority=0 as well.

I propose to amend the documentation to read:
"...will cause vrrp instance to go to FAULT state it they exit with a non-zero exit status;  if a weight is specified that will be added or subtracted to/from the priority but the node will not enter the FAULT state"
