### ISSUE TITLE
Unable to set parameters for base interface

### ISSUE THREAD

**Issue by idosch** [acassen/keepalived#944]
Hi,

I was trying to use keepalived VRRP in vmac mode where the base interface is a bridge, but my host received incorrect ARP replies for the virtual IP. This is because keepalived didn't manage to configure the `arp_filter` and `arp_ignore` sysctls for the base interface. Relevant part from the log:

```
Sat Jul  7 18:35:57 2018: Assigned address 1.1.1.2 for interface br0    
Sat Jul  7 18:35:57 2018: Assigned address fe80::7efe:90ff:feff:27d1 for interface br0
Sat Jul  7 18:35:57 2018: (vrrp_test): Success creating VMAC interface vrrp.5
Sat Jul  7 18:35:57 2018: Unable to set parameters for vrrp.5
```

Using strace I traced it down to the netlink request that tries to set the above two options on the base interface using the `IFLA_AF_SPEC` attribute:

```
sendmsg(7, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=60, type=RTM_SETLINK, flags=NLM_F_REQUEST|NLM_F_ACK, seq=1530551978, pid=1979714821}, {ifi_family=AF_BRIDGE, ifi_type=ARPHRD_NETROM, ifi_index=if_nametoindex("br0"), ifi_flags=0, ifi_change=0}, {{nla_len=28, nla_type=IFLA_AF_SPEC}, "\x18\x00\x02\x00\x14\x00\x01\x00\x08\x00\x0d\x00\x01\x00\x00\x00\x08\x00\x13\x00\x01\x00\x00\x00"}}, iov_len=60}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 60
recvmsg(7, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=80, type=NLMSG_ERROR, flags=0, seq=1530551978, pid=1979714821}, {error=-EOPNOTSUPP, msg={{len=60, type=RTM_SETLINK, flags=NLM_F_REQUEST|NLM_F_ACK, seq=1530551978, pid=1979714821}, {ifi_family=AF_BRIDGE, ifi_type=ARPHRD_NETROM, ifi_index=if_nametoindex("br0"), ifi_flags=0, ifi_change=0}, {{nla_len=28, nla_type=IFLA_AF_SPEC}, "\x18\x00\x02\x00\x14\x00\x01\x00\x08\x00\x0d\x00\x01\x00\x00\x00\x08\x00\x13\x00\x01\x00\x00\x00"}}}}, iov_len=16384}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_PEEK|MSG_TRUNC) = 80
recvmsg(7, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=80, type=NLMSG_ERROR, flags=0, seq=1530551978, pid=1979714821}, {error=-EOPNOTSUPP, msg={{len=60, type=RTM_SETLINK, flags=NLM_F_REQUEST|NLM_F_ACK, seq=1530551978, pid=1979714821}, {ifi_family=AF_BRIDGE, ifi_type=ARPHRD_NETROM, ifi_index=if_nametoindex("br0"), ifi_flags=0, ifi_change=0}, {{nla_len=28, nla_type=IFLA_AF_SPEC}, "\x18\x00\x02\x00\x14\x00\x01\x00\x08\x00\x0d\x00\x01\x00\x00\x00\x08\x00\x13\x00\x01\x00\x00\x00"}}}}, iov_len=16384}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 80
write(2, "Mon Jul  2 20:19:36 2018: Unable to set parameters for vrrp.5\n", 62) = 62
```

Problem is that `ifi_family` is set to `AF_BRIDGE`, whereas it should be set to `AF_UNSPEC`. The kernel function that handles `RTM_SETLINK` messages for `AF_BRIDGE` doesn't know how to process the `IFLA_AF_SPEC` attribute.

Thanks

**Comment by idosch** [comment]
Forgot to mention that the workaround is to set above two options manually so that keepalived won't try to do it (and fail):

```
sysctl -q -w net.ipv4.conf.br0.arp_ignore=1
sysctl -q -w net.ipv4.conf.br0.arp_filter=1
```

**Comment by pqarmitage** [comment]
@idosch How do you manage to get strace to decode so much of the netlink messages? I've built the latest strace from [github](http://github.com/strace/strace) and it doesn't decode nearly so much of the netlink messages.

Commit 9b2b2c9 resolves the issue of setting arp_filter and arp_ignore on bridge interfaces. The issue you identified appears to be a problem with libnl3, so I have changed the code to construct the netlink messages directly. I will report this upstream against libnl.

It might be that we don't really need to use libnl3 at all; although I haven't looked at it in detail, it does look as though there could be quite some overhead in using it.

**Comment by idosch** [comment]
@pqarmitage I tested the fix on my machines and it works. Thank you! I'll close the issue.

Regarding strace, I'm not sure myself. I noticed that on my Fedora 28 machine it even parses more of the netlink packet. Probably because it has a newer strace compared to Fedora 27. I'll try to understand why there's a difference between my Fedora 27 machines.

**Comment by idosch** [comment]
@pqarmitage Do you have CONFIG_NETLINK_DIAG enabled in your kernel config? After enabling this option, strace is able to parse the entire message. See this post for more details:
http://blog.saruta.eu/netlink_strace.html

**Comment by pqarmitage** [comment]
@idosch CONFIG_NETLINK_DIAG is enabled as a module and the module is loaded, but I'm still not getting the full netlink decode. For example, I just get:
sendmsg(8<NETLINK:[2734374]>, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=60, type=0x10 /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK, seq=1531222038, pid=0}, "\x00\x00\x00\x00\x4d\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1c\x00\x1a\x00\x18\x00\x02\x00\x14\x00\x01\x00\x08\x00\x0d\x00\x00\x00\x00\x00\x08\x00\x13\x00\x00\x00\x00\x00"}, iov_len=60}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 60

**Comment by pqarmitage** [comment]
@idosch I have run this now on Fedora 28 and I am getting the detailed Netlink message decoding. It looks as though the additional support for Netlink decoding was added in strace 4.23.
