### ISSUE TITLE
nopreempt start is backup, serveral seconds, it become master

### ISSUE THREAD

**Issue by yywf** [acassen/keepalived#959]
i have two keepalived server use the configuration as follows，only the priority is different.
but when I only start one server, first it will be backup, serveral seconds it will become master, and the serveral seconds is indetermination， who can tell me the accurate value？ thanks。
```
vrrp_instance VI_vrrp1 {
    state BACKUP
    interface eth0
    track_interface {
        eth0
    }
    virtual_router_id 105
    priority 150
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass waf@dbapp
    }
    virtual_ipaddress {
        192.168.40.253/24 brd 192.168.40.255
    }

    nopreempt
    notify_master "/waf/scripts/keepalived_notify.sh master"
    notify_backup "/waf/scripts/keepalived_notify.sh backup"
}
```

**Comment by pqarmitage** [comment]
This is a question and not an issue. The place to ask questions is on the keepalived-devel mailing list.

You are using keepalived version 2, and so the specification is RFC3768. The Master Down Interval as stated in the RFC is calculated as: 
```
Skew_Time               Time to skew Master_Down_Interval in seconds.
    Calculated as:      ( (256 - Priority) / 256 )

Master_Down_Interval    Time interval for Backup to declare Master down (seconds).
    Calculated as:  (3 * Advertisement_Interval) + Skew_time
```
In other words the Master Down Interval is 3 * Advertisement_Interval + (256 - Priority) / 256.

**Comment by yywf** [comment]
@pqarmitage many thanks
