### ISSUE TITLE
http healthcheck may be received an unexpected response and cause memory access violation in extract_status_code

### ISSUE THREAD

**Issue by sayicheng** [acassen/keepalived#960]
when http server response an unexpected response during http healthcheck, for example:
"aa aaaaaaaaaaaHTTP/1.1aa200aaaaaaaaaaOKaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..........."

then, strncat will cause memory  corrupted in extract_status_code, due to inc++  is increasing to a large value ( > 10 ).

https://github.com/acassen/keepalived/blob/master/lib/html.c:
	while (buffer < end && *buffer++ != ' ')
		inc++;
	strncat(buf_code, begin, inc);

but, buf_code has only 10 bytes. 

this is 100% reproduced.

**Comment by yywf** [comment]
I think it is a bug...

**Comment by pqarmitage** [comment]
Commit f280156 should resolve this issue. It also ensures that the status code is three digits long, is non-negative and occurs on the first line of the response. If anyone feels that these additional checks are too strict, please add a comment to this issue.
