### ISSUE TITLE
keepalived and snmp support in docker container

### ISSUE THREAD

**Issue by sergeyglazyrindev** [acassen/keepalived#962]
Hello guys!
We are working on integrating kolla-ansible solution to install openstack and it provides HA stuff using keepalived, one of our tasks we need to do is to get a HA situation/status of all services
We should use snmp approach integrated into keepalived.
I almost got it working but still no success.
What I did ?
1. Changed keepalived startup parameters, added -x and added snmp agentx address. Snmp agent address specified as "HOSTIP:78001", HOSTIP is an IP address of the server where this docker container is working. Its accessible from docker container, pinged it. Keepalived installed from redhat rpm and its compiled with snmp support. SNMP customized agentx address specified in /etc/snmp/snmpd.conf
and as a confirmation that it's connected successfully to snmp server, keepalived says in logs:

> Starting SNMP subagent
> NET-SNMP version X AgentX subagent connected
> 

2. I added master agentx and rocommunity option to /etc/snmp/snmpd.conf, restarted snmpd

> rocommunity public
> master agentx
> 

3. Copied MIB files to /usr/share/snmp/mibs (maybe wrong location, writing it based on memory flashes ) but when I ask list of available OIDS through snmpwalk it recognizes these mibs for keepalived
3. Still no data from keepalived. When I ask for the data I get such responses.

> snmpwalk -v2c -cpublic localhost KEEPALIVED-MIB::vrrpInstanceState.1
> KEEPALIVED-MIB::vrrpInstanceState.1 = No more variables left in this MIB View (It is past the end of the MIB tree)
> snmpwalk -v2c -cpublic localhost  .1.3.6.1.4.1.9586.100.5
> SNMPv2-SMI::enterprises.9586.100.5 = No more variables left in this MIB View (It is past the end of the MIB tree)
> 

I checked this link ( https://github.com/acassen/keepalived/issues/186 ) and found nothing useful. TBH, I tried few options from this discussion but nothing helped. Unfortunately, I wasn't able to strace what's happening inside vrrp process because in container it simply said: **"Man, you need to be root."** . I'll give it a try again.

I decided to post an issue on github because there's no guidance on how to use keepalived and configure snmp support for keepalived inside container.

I believe it would be useful for community in future.

Any ideas what could be wrong ?
Is there anyone who was able to use snmp stuff for keepalived in container.

**Comment by sergeyglazyrindev** [comment]
I forgot there's a problem with libipset not loaded while keepalived runtime. Could be that a reason ?

**Comment by robgarner** [comment]
that error is usually an indication of a permissions problem wrt communities or access groups in your snmpd.conf

**Comment by pqarmitage** [comment]
keepalived dynamically links to libipset. It might be that for running in a container you would be better off specifying `--disable-libipset-dynamic` to `configure`.

There is some information on how to run snmp at the start of keepalived/vrrp/vrrp_snmp.c source file, although it doesn't specifically address containers. I have had difficulty running with snmpd running in the main network namespace and keepalived in a different network namespace, and that is essentially the same problem.

**Comment by sergeyglazyrindev** [comment]
How do I debug/ensure if it is a problem with communities/access groups in snmpd.conf ? Sorry for the stupid question but I didn't work with snmp before.

**Comment by pqarmitage** [comment]
Can you try running keepalived directly in the server rather than in the container, and see if snmp works in that simpler situation.

**Comment by sergeyglazyrindev** [comment]
Hello guys!
I was busy with release. Now I am back to this problem

Seems like I found a reason but don't know how to fix.
I tested the keepalived with snmp locally and it works only when I use default agentx socket: udp:127.0.0.1:162
Though server has more interfaces, eth0, etc it doesn't work with another interfaces.
I tested it like this:
1. in one ssh session I started tcpdump on docker0 interface and port 162
tcpdump -i docker0 -n udp port 162
2.  echo "This is my data" > /dev/udp/172.17.0.1/162

And tcpdump doesn't show any traffic.
SELinux disabled, firewalld doesn't work, iptables rules are empty.

> [root@ci-vosc-z etc]# ifconfig
> docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
>         inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
>         ether 02:42:c6:89:f1:31  txqueuelen 0  (Ethernet)
>         RX packets 52  bytes 3844 (3.7 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 0  bytes 0 (0.0 B)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 106.120.104.110  netmask 255.255.255.0  broadcast 106.120.104.255
>         ether 52:54:00:52:2f:f9  txqueuelen 1000  (Ethernet)
>         RX packets 1745161  bytes 3968565194 (3.6 GiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 1577291  bytes 334476907 (318.9 MiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 128.0.0.110  netmask 255.255.255.0  broadcast 128.0.0.255
>         ether 52:54:00:a9:62:c4  txqueuelen 1000  (Ethernet)
>         RX packets 1382503  bytes 471588107 (449.7 MiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 1201371  bytes 582844376 (555.8 MiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> eth2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 128.0.100.110  netmask 255.255.255.0  broadcast 128.0.100.255
>         ether 52:54:00:25:57:e6  txqueuelen 1000  (Ethernet)
>         RX packets 72  bytes 5104 (4.9 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 51  bytes 4374 (4.2 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         loop  txqueuelen 1  (Local Loopback)
>         RX packets 20711170  bytes 4758494982 (4.4 GiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 20711170  bytes 4758494982 (4.4 GiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
>  

Any idea how to fix it ?

**Comment by sergeyglazyrindev** [comment]
Hello guys!
Finally I got it working locally. But in container it still doesn't work
In logs it's saying: SNMP AgentX connected
but then I go to container and check all 3 keepalived processes. No one of these processes have a socket opened.
The process has following opened files:

> keepalive 12378 root    0u      CHR                1,3      0t0    1041 /dev/null
> keepalive 12378 root    1u      CHR                1,3      0t0    1041 /dev/null
> keepalive 12378 root    2u      CHR                1,3      0t0    1041 /dev/null
> keepalive 12378 root    3u     unix 0xffff880096d8e580      0t0 1368064 socket
> keepalive 12378 root    4r     FIFO                0,8      0t0 1368572 pipe
> keepalive 12378 root    5w     FIFO                0,8      0t0 1368572 pipe
> keepalive 12378 root    6u  netlink                         0t0 1368575 ROUTE
> keepalive 12378 root    7u  netlink                         0t0 1368576 ROUTE
> keepalive 12378 root    8u     pack            1368577      0t0    RARP type=SOCK_RAW
> keepalive 12378 root    9u     pack            1368578      0t0    IPV6 type=SOCK_RAW
> keepalive 12378 root   10r     FIFO                0,8      0t0 1368579 pipe
> keepalive 12378 root   11w     FIFO                0,8      0t0 1368579 pipe
> keepalive 12378 root   12r     FIFO                0,8      0t0 1368580 pipe
> keepalive 12378 root   13w     FIFO                0,8      0t0 1368580 pipe
> keepalive 12378 root   15u      raw                         0t0 1368598 00000000:0070->00000000:0000 st=07
> keepalive 12378 root   16u      raw                         0t0 1368599 00000000:0070->00000000:0000 st=07
> 

But process doesn't have socket line:

> keepalive 12378 root   14u     unix 0xffff880099613100      0t0 1368581 socket

When I request keepalived version through snmp it says: **"No response from 127.0.0.1"**

I started snmp process with option : -x udp:162 -> it is listening on all interfaces, on port 162
and keepalived started with option: -A udp:127.0.0.1:162

**Comment by pqarmitage** [comment]
@sergeyglazyrindev I've tried this too in the past and never managed to get it working (actually I wasn't even using a container but I was trying with snmp and keepalived in separate network namespace).

**Comment by kcem** [comment]
@sergeyglazyrindev 
It seems that UDP is not working correctly. Keepalived is registering to SNMP but I cannot walk through keepalived objects. Use socket or switch UDP to TCP for temporary workaround for this problem.

Commands:
/usr/sbin/snmpd -x tcp:127.0.0.1:700 -f
/usr/sbin/keepalived -nld -x -A tcp:127.0.0.1:700 2>&1 | grep -i snmp
 SNMP keepalived enabled
 SNMP checker enabled
 SNMP RFCv2 enabled
 SNMP RFCv3 enabled
 SNMP traps disabled
 SNMP socket = tcp:127.0.0.1:700
NET-SNMP version 5.7.2 AgentX subagent connected

Check:
snmpwalk -r 2 -t 5 -v2c -cpublic 127.0.0.1 -O e KEEPALIVED-MIB::version
KEEPALIVED-MIB::version.0 = STRING: Keepalived v1.3.5 (03/19,2017)

--
Commands:
/usr/sbin/snmpd -x udp:127.0.0.1:700 -f
/usr/sbin/keepalived -nld -x -A udp:127.0.0.1:700 2>&1 | grep -i snmp
 SNMP socket = udp:127.0.0.1:700
 SNMP keepalived enabled
 SNMP checker enabled
 SNMP RFCv2 enabled
 SNMP RFCv3 enabled
 SNMP traps disabled
 SNMP socket = udp:127.0.0.1:700
NET-SNMP version 5.7.2 AgentX subagent connected

Check:
snmpwalk -r 2 -t 5 -v2c -cpublic 127.0.0.1 -O e KEEPALIVED-MIB::version
Timeout: No Response from 127.0.0.1

Commands:
/usr/sbin/snmpd -x unix:/var/agentx/master -D -LS0-7d -f
/usr/sbin/keepalived -nld -p /run/keepalived1.pid -x 2>&1 | grep -i snmp
 SNMP keepalived enabled
 SNMP checker enabled
 SNMP RFCv2 enabled
 SNMP RFCv3 enabled
 SNMP traps disabled
 SNMP socket = default (unix:/var/agentx/master)
NET-SNMP version 5.7.2 AgentX subagent connected

Check:
snmpwalk -r 2 -t 5 -v2c -cpublic 127.0.0.1 -O e KEEPALIVED-MIB::version
KEEPALIVED-MIB::version.0 = STRING: Keepalived v1.3.5 (03/19,2017)

**Comment by pqarmitage** [comment]
@kcem Many thanks for the information.

I've just tried it with net-snmp v5.8 to see if that is any better, and it is worse! Using udp snmpd outputs the following:
```
netsnmp_assert 0 failed transports/snmpIPv4BaseDomain.c:215 netsnmp_ipv4_fmtaddr()
unknown addr type of size -1
double free or corruption (fasttop)
Aborted (core dumped)
```

TCP and unix domain socket work as before.

Should the UDP issues be reported as bugs to net-snmp?

**Comment by sergeyglazyrindev** [comment]
I think yes, it should be reported to net-snmp. I'll do that. Thanks guys for investigation.
@pqarmitage I wanted to ask one more question: is it normal to have one snmp instance per one keepalived instance ? And do I need to ask all snmp instances to get a status of all keepalived instances ?
Or is there a way to collect it in one place ? And ask only snmp instance ? As far as I understand it's impossible right now. Right ?

**Comment by pqarmitage** [comment]
@sergeyglazyrindev When you report the UDP issue to net-snmp, could you also please mention the issue I identified above with net-snmp v5.8.

My understanding is that an OID can only be registered once with an instance of snmpd. Since the OIDs are fixed for keepalived (.1.3.6.1.4.1.9586.100), VRRPv2 (.1.3.6.1.2.1.68) and VRRPv3 (.1.3.6.1.2.1.207), that means that only one instance of keepalived can register with an instance of snmpd (well, strictly three could if one used the proprietary keepalived mib, one the VRRPv2 mib and the third the VRRPv3 mib).

If you have one instance of snmpd per keepalived instance, then each snmpd instance would need to be queried to get the status of the keepalived instance connected to it.

I don't think there could ever be a way of being able to collect all the information in one snmpd instance since it wouldn't be possible to identify the data relating to different instances of keepalived; this is down to the architecture of SNMP.

Collecting the output of multiple SNMP agents in one place is the job of a network management system.

**Comment by sergeyglazyrindev** [comment]
Okay, I think we can close this issue and reopen if net-snmp team explains that its a problem with keepalived.
