### ISSUE TITLE
Keepalived not logging messages for track/action scripts

### ISSUE THREAD

**Issue by pritishmishra** [acassen/keepalived#968]
We have implemented a HA setup for our component using Keepalived. We notice that keepalived logs the actions performed by the service properly and we have also configured it so that it forwards the relevant logs to the relevant stderr and stdout log files. These logs help us a lot to debug, if something goes wrong with the setup. The component being used for HA setup makes it even more imperative to have a proper logging mechanism.

However, we notice that the logs provided by the component scripts (which are invoked by Keepalived service) are eaten up and never appear in the logs file. For example, we have a track script (for checking the status of the nodes) and an action script (for performing certain actions during change of state). We have relevant logger actions defined in those scripts, however, these logs never appear. Thus, we become clueless if our action script internally fails.

Are we missing something here? Does keepalived not provide a mechanism such that the component scripts can also forward their logs?

Kindly help us to resolve this issue.
Thanks!

**Comment by pqarmitage** [comment]
Are you using the `-G` and `-g` options to control the logging of keepalived? If not, that is the most straightforward way to manage where logs are written (this isn't related to your question though).

> Are we missing something here? Does keepalived not provide a mechanism such that the component scripts can also forward their logs?

keepalived does **not** provide any mechanism for directing the output/logging of scripts that it runs. If a keepalived process and scripts were both to write to the same file, or indeed if two different scripts were both to write to the same file, then the contents of the log file can end up with lines written by one process appearing in the middle of a line written by another process.

If you want your scripts to produce logging, they will need to control for themselves the output of their logging. An example of a script that I use that does its own logging is:
```
#!/bin/bash
  
if [[ $# -ge 1 ]]; then
        NAME=$1
else
        NAME=${0##*/}
        NAME=${NAME%.sh}
fi

echo -n "$(date +"%a %b %e %X %Y")": \[$PPID:$$\] >>/tmp/$NAME.log
for i in $(seq 1 $#); do
        echo -n " '$1'" >>/tmp/$NAME.log
        shift
done
echo >>/tmp/$NAME.log

if [[ -f /tmp/$NAME.sig ]]; then
        SIG=$(cat /tmp/$NAME.sig)
        kill -$SIG $$
        echo "  Sent signal $SIG" >>/tmp/$NAME.log

        sleep 5
fi

if [[ -f /tmp/$NAME.slp ]]; then
        SLEEP=$(cat /tmp/$NAME.slp)
        echo "  Sleeping $SLEEP seconds" >>/tmp/$NAME.log

        sleep $SLEEP
fi

[[ ! -f /tmp/$NAME.ret ]] && echo 0 >/tmp/$NAME.ret

RET=$(cat /tmp/$NAME.ret)

if [[ $RET -ge 3 && $RET -le 15 ]]; then
        echo $((RET - 1)) >/tmp/$NAME.ret
        echo "  Ret sleeping $SLEEP seconds" >>/tmp/$NAME.log

        sleep $RET
fi

echo "  Returning $RET" >>/tmp/$NAME.log

exit $RET
```
I find this, especially with the timestamps of all the entries, means that I can trace through what is happening and when.

**Comment by pritishmishra** [comment]
Thank you @pqarmitage for your quick reply on this issue. 
I completely agree with your logic of not populating logs in the same log file as used by Keepalived to keep the logs consistent and distinct. However, I was hoping the tool was logging in the messages from component scripts to some other log file. May be, that would be too cumbersome for the tool. :)

Anyway, as suggested by you in the example, we also intend to handle the logging for the component scripts in the similar way, by redirecting the logs to a separate file, by appending timestamps to each log.

Closing this issue, the conclusion being, the logging should be handled by the component scripts as given in the example.
