### ISSUE TITLE
after reboot keepalived setting vip failed

### ISSUE THREAD

**Issue by xujintao** [acassen/keepalived#972]
`cat keepalived -v`
> Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

`uname -a`
> Linux kube-master1 3.10.0-862.2.3.el7.x86_64`

`cat /etc/redhat-release`
> CentOS Linux release 7.5.1804 (Core)

`cat /etc/keepalived/keepalived.conf`
> global_defs {
    router_id lb-master-105
}
vrrp_script check-haproxy {
    script "killall -0 haproxy"
    interval 5
    weight -30
}
vrrp_instance VI-kube-master {
    state MASTER
    priority 120
    dont_track_primary
    interface eth1
    virtual_router_id 68
    advert_int 3
    track_script {
        check-haproxy
    }
    virtual_ipaddress {
        192.168.0.10
    }
}

When i reboot, keepalived setting vip failed. 
`ip addr`
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:c9:c7:04 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic eth0
       valid_lft 83111sec preferred_lft 83111sec
    inet6 fe80::5054:ff:fec9:c704/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:33:0e:8b brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.11/24 brd 192.168.0.255 scope global noprefixroute eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe33:e8b/64 scope link 
       valid_lft forever preferred_lft forever

There is no inet 192.168.0.10/24, then i grab log like this:
`sed -n -e '/Keepalived\|NetworkManager/p' /var/log/messages`
> Aug  7 18:39:17 kube-master1 Keepalived[856]: Starting Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
Aug  7 18:39:17 kube-master1 Keepalived[856]: Opening file '/etc/keepalived/keepalived.conf'.
Aug  7 18:39:17 kube-master1 Keepalived[874]: Starting Healthcheck child process, pid=875
Aug  7 18:39:17 kube-master1 Keepalived[874]: Starting VRRP child process, pid=876
Aug  7 18:39:17 kube-master1 Keepalived_vrrp[876]: Registering Kernel netlink reflector
Aug  7 18:39:17 kube-master1 Keepalived_vrrp[876]: Registering Kernel netlink command channel
Aug  7 18:39:17 kube-master1 Keepalived_vrrp[876]: Registering gratuitous ARP shared channel
Aug  7 18:39:17 kube-master1 Keepalived_vrrp[876]: Opening file '/etc/keepalived/keepalived.conf'.
Aug  7 18:39:17 kube-master1 Keepalived_vrrp[876]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Aug  7 18:39:17 kube-master1 Keepalived_vrrp[876]: WARNING - script `killall` resolved by path search to `/usr/bin/killall`. Please specify full path.
Aug  7 18:39:17 kube-master1 Keepalived_vrrp[876]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Aug  7 18:39:17 kube-master1 Keepalived_vrrp[876]: VRRP_Instance(VI-kube-master) removing protocol VIPs.
Aug  7 18:39:17 kube-master1 Keepalived_vrrp[876]: Using LinkWatch kernel netlink reflector...
Aug  7 18:39:17 kube-master1 Keepalived_vrrp[876]: VRRP sockpool: [ifindex(3), proto(112), unicast(0), fd(10,11)]
Aug  7 18:39:18 kube-master1 Keepalived_vrrp[876]: VRRP_Script(check-haproxy) succeeded
Aug  7 18:39:18 kube-master1 Keepalived_healthcheckers[875]: Opening file '/etc/keepalived/keepalived.conf'.
Aug  7 18:39:20 kube-master1 Keepalived_vrrp[876]: VRRP_Instance(VI-kube-master) Transition to MASTER STATE
Aug  7 18:39:23 kube-master1 Keepalived_vrrp[876]: VRRP_Instance(VI-kube-master) Entering MASTER STATE
Aug  7 18:39:23 kube-master1 Keepalived_vrrp[876]: VRRP_Instance(VI-kube-master) setting protocol VIPs.
Aug  7 18:39:23 kube-master1 Keepalived_vrrp[876]: Sending gratuitous ARP on eth1 for 192.168.0.10
Aug  7 18:39:23 kube-master1 Keepalived_vrrp[876]: VRRP_Instance(VI-kube-master) Sending/queueing gratuitous ARPs on eth1 for 192.168.0.10
Aug  7 18:39:23 kube-master1 Keepalived_vrrp[876]: Sending gratuitous ARP on eth1 for 192.168.0.10
Aug  7 18:39:23 kube-master1 Keepalived_vrrp[876]: Sending gratuitous ARP on eth1 for 192.168.0.10
Aug  7 18:39:23 kube-master1 Keepalived_vrrp[876]: Sending gratuitous ARP on eth1 for 192.168.0.10
Aug  7 18:39:23 kube-master1 Keepalived_vrrp[876]: Sending gratuitous ARP on eth1 for 192.168.0.10
Aug  7 18:39:26 kube-master1 NetworkManager[562]: <info>  [1533638366.7791] device (eth1): state change: activated -> deactivating (reason 'user-requested', sys-iface-state: 'managed')
Aug  7 18:39:26 kube-master1 NetworkManager[562]: <info>  [1533638366.7819] audit: op="device-disconnect" interface="eth1" ifindex=3 pid=1738 uid=0 result="success"
Aug  7 18:39:26 kube-master1 NetworkManager[562]: <info>  [1533638366.7820] device (eth1): state change: deactivating -> disconnected (reason 'user-requested', sys-iface-state: 'managed')
Aug  7 18:39:26 kube-master1 NetworkManager[562]: <info>  [1533638366.8234] caught SIGTERM, shutting down normally.
Aug  7 18:39:26 kube-master1 NetworkManager[562]: <info>  [1533638366.8274] exiting (success)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8461] NetworkManager (version 1.10.2-13.el7) is starting... (after a restart)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8463] Read config: /etc/NetworkManager/NetworkManager.conf (lib: 10-slaves-order.conf)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8569] manager[0x555e065d0070]: monitoring kernel firmware directory '/lib/firmware'.
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8588] hostname: hostname: using hostnamed
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8588] hostname: hostname changed from (none) to "kube-master1"
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8590] dns-mgr[0x555e065ed940]: init: dns=default, rc-manager=file
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8662] settings: loaded plugin ifcfg-rh: (c) 2007 - 2015 Red Hat, Inc.  To report bugs please use the NetworkManager mailing list. (/usr/lib64/NetworkManager/libnm-settings-plugin-ifcfg-rh.so)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8664] settings: loaded plugin iBFT: (c) 2014 Red Hat, Inc.  To report bugs please use the NetworkManager mailing list. (/usr/lib64/NetworkManager/libnm-settings-plugin-ibft.so)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8664] settings: loaded plugin keyfile: (c) 2007 - 2016 Red Hat, Inc.  To report bugs please use the NetworkManager mailing list.
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8676] ifcfg-rh: new connection /etc/sysconfig/network-scripts/ifcfg-eth1 (9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04,"System eth1")
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8681] ifcfg-rh: new connection /etc/sysconfig/network-scripts/ifcfg-eth0 (5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03,"System eth0")
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8830] manager: rfkill: WiFi enabled by radio killswitch; enabled by state file
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8830] manager: rfkill: WWAN enabled by radio killswitch; enabled by state file
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8830] manager: Networking is enabled by state file
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8832] dhcp-init: Using DHCP client 'dhclient'
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8833] Loaded device plugin: NMBondDeviceFactory (internal)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8833] Loaded device plugin: NMBridgeDeviceFactory (internal)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8833] Loaded device plugin: NMDummyDeviceFactory (internal)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8833] Loaded device plugin: NMEthernetDeviceFactory (internal)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8833] Loaded device plugin: NMInfinibandDeviceFactory (internal)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8833] Loaded device plugin: NMIPTunnelDeviceFactory (internal)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8833] Loaded device plugin: NMMacsecDeviceFactory (internal)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8833] Loaded device plugin: NMMacvlanDeviceFactory (internal)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8834] Loaded device plugin: NMPppDeviceFactory (internal)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8834] Loaded device plugin: NMTunDeviceFactory (internal)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8834] Loaded device plugin: NMVethDeviceFactory (internal)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8834] Loaded device plugin: NMVlanDeviceFactory (internal)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8834] Loaded device plugin: NMVxlanDeviceFactory (internal)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8842] Loaded device plugin: NMTeamFactory (/usr/lib64/NetworkManager/libnm-device-plugin-team.so)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8854] device (lo): carrier: link connected
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8859] manager: (lo): new Generic device (/org/freedesktop/NetworkManager/Devices/1)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8862] device (eth0): carrier: link connected
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8867] manager: (eth0): new Ethernet device (/org/freedesktop/NetworkManager/Devices/2)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8877] manager: (eth0): assume: will attempt to assume matching connection 'System eth0' (5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03) (indicated)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8877] device (eth0): state change: unmanaged -> unavailable (reason 'connection-assumed', sys-iface-state: 'assume')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8880] device (eth0): state change: unavailable -> disconnected (reason 'connection-assumed', sys-iface-state: 'assume')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8887] device (eth0): Activation: starting connection 'System eth0' (5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8889] device (eth1): carrier: link connected
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8894] manager: (eth1): new Ethernet device (/org/freedesktop/NetworkManager/Devices/3)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.8899] device (eth1): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9043] device (eth0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'assume')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9052] device (eth0): state change: prepare -> config (reason 'none', sys-iface-state: 'assume')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9053] device (eth1): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'managed')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9065] policy: auto-activating connection 'System eth1'
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9072] device (eth1): Activation: starting connection 'System eth1' (9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9073] device (eth1): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'managed')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9074] manager: NetworkManager state is now CONNECTING
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9075] device (eth1): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9130] device (eth0): state change: config -> ip-config (reason 'none', sys-iface-state: 'assume')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9136] dhcp4 (eth0): activation: beginning transaction (timeout in 45 seconds)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9330] dhcp4 (eth0): dhclient started with pid 1775
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9335] device (eth1): state change: config -> ip-config (reason 'none', sys-iface-state: 'managed')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9520] device (eth1): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'managed')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9604] device (eth1): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'managed')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9605] device (eth1): state change: secondaries -> activated (reason 'none', sys-iface-state: 'managed')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9606] manager: NetworkManager state is now CONNECTED_LOCAL
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9672] policy: set 'System eth0' (eth0) as default for IPv4 routing and DNS
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9684] device (eth1): Activation: successful, device activated.
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9847] dhcp4 (eth0):   address 10.0.2.15
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9847] dhcp4 (eth0):   plen 24 (255.255.255.0)
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9847] dhcp4 (eth0):   gateway 10.0.2.2
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9847] dhcp4 (eth0):   lease time 86400
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9847] dhcp4 (eth0):   nameserver '10.0.2.3'
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9847] dhcp4 (eth0): state changed unknown -> bound
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9851] device (eth0): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'assume')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9854] device (eth0): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'assume')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9855] device (eth0): state change: secondaries -> activated (reason 'none', sys-iface-state: 'assume')
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9856] manager: NetworkManager state is now CONNECTED_SITE
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9895] device (eth0): Activation: successful, device activated.
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9897] manager: startup complete
Aug  7 18:39:26 kube-master1 NetworkManager[1757]: <info>  [1533638366.9899] manager: NetworkManager state is now CONNECTED_GLOBAL
Aug  7 18:39:28 kube-master1 Keepalived_vrrp[876]: Sending gratuitous ARP on eth1 for 192.168.0.10
Aug  7 18:39:28 kube-master1 Keepalived_vrrp[876]: VRRP_Instance(VI-kube-master) Sending/queueing gratuitous ARPs on eth1 for 192.168.0.10
Aug  7 18:39:28 kube-master1 Keepalived_vrrp[876]: Sending gratuitous ARP on eth1 for 192.168.0.10
Aug  7 18:39:28 kube-master1 Keepalived_vrrp[876]: Sending gratuitous ARP on eth1 for 192.168.0.10
Aug  7 18:39:28 kube-master1 Keepalived_vrrp[876]: Sending gratuitous ARP on eth1 for 192.168.0.10
Aug  7 18:39:28 kube-master1 Keepalived_vrrp[876]: Sending gratuitous ARP on eth1 for 192.168.0.10

The log shows that in terms of reboot start keepalived will be resulted in network restart. 

But if i just systemctl restart keepalived instead of reboot, it will be ok.
I want a help.

**Comment by pqarmitage** [comment]
The problem appears to be indicated by the lines
```
Aug 7 18:39:26 kube-master1 NetworkManager[562]: [1533638366.7791] device (eth1): state change: activated -> deactivating (reason 'user-requested', sys-iface-state: 'managed')
Aug 7 18:39:26 kube-master1 NetworkManager[562]: [1533638366.7819] audit: op="device-disconnect" interface="eth1" ifindex=3 pid=1738 uid=0 result="success"
Aug 7 18:39:26 kube-master1 NetworkManager[562]: [1533638366.7820] device (eth1): state change: deactivating -> disconnected (reason 'user-requested', sys-iface-state: 'managed')
```
and then for some reason NetworkManager restarts (but this probably isn't a problem since doing a manual restart of NetworkManager on my Centos 7.5 VM doesn't cause keepalived added addresses to be removed).

On my CentOS 7.5 VM, keepalived doesn't lose its virtual ipaddresses, but NetworkManager isn't requested to take the interface down, so it isn't a fundamental problem but more an issue of why NetworkManager is requested to take eth1 down.

I think you have two solutions available to you:
1. Sort out why something/someone is requesting that eth1 is taken down, and stop that happening
2. Upgrade to keepalived v2.0.x (v2.0.6 is recommended). This will notice the virtual ipaddress being deleted, and the vrrp instance will transition to backup state until it can become master again, when the virtual ipaddress will be added again.

**Comment by xujintao** [comment]
I adopt the second solution and update keepalived from v1.3.5 to v2.0.6. 
Althouth the network is still restart after reboot, but the vip(192.168.0.10) does appear.
I found the healthcheck child process can not spawn from log, which means only two process of keepalived running but it also seems work normally.

**Comment by pqarmitage** [comment]
Glad to hear that your problem is solved.

In keepalived v2.x.y if there is no checker configuration, then no checker child process is started. Likewise, if there is no vrrp configuration, no vrrp child process is started. It just saves on system resources.
