### ISSUE TITLE
Build docker image exception

### ISSUE THREAD

**Issue by zengqinglei** [acassen/keepalived#987]
### Run Environment
* **keepalived version:** v2.0.7
* **docker version:** 18.06-ce
* **system:** centos 7

### Exception  
![image](https://user-images.githubusercontent.com/7374317/44617021-10792f80-a88e-11e8-8cb8-b74be5e4dbea.png)  
![image](https://user-images.githubusercontent.com/7374317/44617019-fe978c80-a88d-11e8-8ac7-d5d3f08f237c.png)
### With the following the steps to reproduce:
**1. Initialization**
```
mk docker-keepalived  
cd docker-keepalived
wget  http://keepalived.org/software/keepalived-2.0.7.tar.gz
mkdir -p keepalived-sources
tar -xzf keepalived-2.0.7.tar.gz --strip 1 -C keepalived-sources
```
**2. Create dockerfile**
```
FROM alpine:3.5
MAINTAINER Bertrand Gouny <bertrand.gouny@osixia.net>

# add keepalived sources to /tmp/keepalived-sources
ADD keepalived-sources /tmp/keepalived-sources

# Add keepalived default script user to make sure their IDs get assigned consistently,
# regardless of whatever dependencies get added
RUN addgroup -S keepalived_script && adduser -D -S -G keepalived_script keepalived_script

# 1. install required libraries and tools
# 2. compile and install keepalived
# 3. remove keepalived sources and unnecessary libraries and tools
RUN apk --no-cache add \
       gcc \
       ipset \
       ipset-dev \
       iptables \
       iptables-dev \
       libnfnetlink \
       libnfnetlink-dev \
       libnl3 \
       libnl3-dev \
       make \
       musl-dev \
       openssl \
       openssl-dev \
       autoconf \
    && cd /tmp/keepalived-sources \
    && ./configure --disable-dynamic-linking \
    && make && make install \
    && cd - \
    && rm -rf /tmp/keepalived-sources \
    && apk --no-cache del \
        gcc \
        ipset-dev \
        iptables-dev \
        libnfnetlink-dev \
        libnl3-dev \
        make \
        musl-dev \
        openssl-dev \
        autoconf

ADD keepalived.conf /usr/local/etc/keepalived/keepalived.conf

# set keepalived as image entrypoint with --dont-fork and --log-console (to make it docker friendly)
# define /usr/local/etc/keepalived/keepalived.conf as the configuration file to use
ENTRYPOINT ["/usr/local/sbin/keepalived","--dont-fork","--log-console", "-f","/usr/local/etc/keepalived/keepalived.conf"]

# example command to customise keepalived daemon:
# CMD ["--log-detail","--dump-conf"]
```
**3. Create keepalived.conf**
``` java
vrrp_instance VI_1 {
    interface ens33
    state MASTER
    virtual_router_id 127
    priority 100

    virtual_ipaddress {
        192.168.0.102
    }
}
```
**4. Start building**
``` java
docker build -t keepalived .
```
**Can you help me analyze what is the reason?**
**How can I solve it?**

**_thank you very much !_**

**Comment by pqarmitage** [comment]
I've just merged a commit (b75d3e7) that should resolve the `sh: yes: unknown operand` error, and another commit (6c7a281) which should resolve the compilation error in process.c.

If you get any more `unknown type name bool` or `true undeclared` or `false undeclared` you cold try adding `#include <stdbool.h>` at the top of the source file, but please also log here any source files that needed stdbool.h to be added, so that we can updated the source code here.

**Comment by pqarmitage** [comment]
@zengqinglei To create a new tar file from the git source tree, run `./build_setup; make; make dist`

**Comment by zengqinglei** [comment]
@pqarmitage 

**Hi, I run the following command as you said:**
```
git clone https://github.com/acassen/keepalived.git
cd keepalived/
./build_setup
./configure
make
make dist
``` 
**The above steps worked fine with no errors, but an exception occurred when I ran the following command:**
```
make docker
```
### Exception:
![image](https://user-images.githubusercontent.com/7374317/44621101-d2522f00-a8d2-11e8-9ea3-8d779c26ad40.png)  
**View the file list as follows:**
![image](https://user-images.githubusercontent.com/7374317/44621112-0fb6bc80-a8d3-11e8-8f39-f40ab27f2699.png)  
**Can you help me solve the problem?**
**_thank you very much !_**

**Comment by zengqinglei** [comment]
@pqarmitage Hello, I have solved the problem, I want to share my solution!
#### Instructions: 
Because these files in the above figure: install-sh, missing, depcomp, ar-lib, all exist in a shortcut way, so can not be copied to the container through Dockerfile Add . /tmp/keepalived-sources, resulting in files not found To.
#### My solution is:
Delete the shortcut and copy the source file from the shortcut to the file.
[Please see my git readme documentation](https://github.com/zengqinglei/keepalived-dokcer/tree/master)

**_Now that I have successfully built the docker image successfully, it has been running successfully, thank you very much._**

**Comment by pqarmitage** [comment]
The simplest solution is probably to create the tar file, and then extract the contents of the tar file in the container. This should work since the tar file includes the ar-lib, depcomp, install-sh and missing files, rather than symbolic links. Doing it this way is then the same as downloading the tar file and building from that.
