### ISSUE TITLE
Build docker image exception

### ISSUE THREAD

**Issue by zengqinglei** [acassen/keepalived#989]
**Hi:**  
**I probably didn't notice this problem yesterday. The following exception occurred when building the docker image today:**  
![image](https://user-images.githubusercontent.com/7374317/44641106-f2c7d980-a9f7-11e8-9b23-1666c85a0f70.png)  
**Can you analyze the reason for me?**

**_thank you very much._**

**Comment by pqarmitage** [comment]
Please see the comment in the code immediately before line 809:
```
/* NOTE: ah below is initialised above. Older versions of gcc may
 * however warn that it may be used uninitialised. */
```
This is simply an issue that older versions of gcc weren't as good at detecting that variables had been initialised through all possible code paths that could reach the line in question.
