### ISSUE TITLE
keepalived-2.0.7 make rpm error

### ISSUE THREAD

**Issue by 402309718** [acassen/keepalived#995]
|| chmod -R a+r "keepalived-2.0.7"
tardir=keepalived-2.0.7 && ${TAR-tar} chof - "$tardir" | GZIP=--best gzip -c >keepalived-2.0.7.tar.gz
make[2]: Leaving directory `/root/keepalived-2.0.7'
if test -d "keepalived-2.0.7"; then find "keepalived-2.0.7" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "keepalived-2.0.7" || { sleep 5 && rm -rf "keepalived-2.0.7"; }; else :; fi
make[1]: Leaving directory `/root/keepalived-2.0.7'
rpmbuild -ba keepalived.spec
error: failed to create directory %{_sourcedir}: /root/rpmbuild/SOURCES: No such file or directory
make: *** [rpm] Error 1

but SOURCES file was be created by compiling

**Comment by pqarmitage** [comment]
First of all it looks as though you are attempting to build the keepalived rpm as the root user, which you should never do; you should be running this as a normal, unprivileged, user.

The `~/rpmbuild/SOURCES` directory is created by running the script `rpm-setuptree`; it is not created by any part of the process of compiling keepalived. So it appears as though you haven't set up the rpm build environment for the root user.
