### ISSUE TITLE
SIGSEGV on config reload with regex support enabled

### ISSUE THREAD

**Issue by vrit** [acassen/keepalived#997]
(gdb) where
    #0  http_get_check_compare (a=<optimized out>, b=<optimized out>) at check_http.c:331
    #1  0x00005555555713b0 in migrate_checkers (old_checkers_queue=0x5555557c1360, new_rs=<optimized out>, old_rs=<optimized out>) at ipwrapper.c:753
    #2  clear_diff_rs (new_vs=<optimized out>, old_checkers_queue=0x5555557c1360, old_vs=0x5555557c98d0) at ipwrapper.c:817
    #3  clear_diff_services (old_checkers_queue=old_checkers_queue@entry=0x5555557c1360) at ipwrapper.c:895
    ....

If HTTP_GET check doens't use regex, u1->regex is null. 

    331         if (u1->regex->pcre2_options != u2->regex->pcre2_options)
    332             return false;
    333         if (u1->regex_no_match != u2->regex_no_match)
    334             return false;
    335         if (u1->regex_min_offset != u2->regex_min_offset ||
    336             u1->regex_max_offset != u2->regex_max_offset)
    337             return false;

Example config:

             HTTP_GET {
                        connect_ip 127.0.0.1
                        connect_port 8000
                        connect_timeout 1
                        retry 0
                        url {
                                path /blahblah
                                digest d418bc9793388dd9bfcffa954ceabf73
                        }
                }

**Comment by pqarmitage** [comment]
@vrit Many thanks for reporting this along with the detailed analysis.

Commit afb8db5 resolves the segfault.
